# Part 1 of batch4 translations (keys 1-35)
PART1: dict[str, str] = {
    "Parsha: $it": "פרשה: $it",
    "e.g., Sarah B.": "לדוגמה, שרה ב.",
    "Beardy Top Productions": "הפקות Beardy Top",
    "Performed by G.E.U.L.A © 2026": "בוצע על ידי G.E.U.L.A © 2026",
    "Currently using: $effectiveName": "בשימוש כעת: $effectiveName",
    "Enjoy the official Mitz Mode song!": "תהנו משיר Mitz Mode הרשמי!",
    "You can eat $allowedFood as of ${endedAt ?:": "מותר לאכול $allowedFood מ-${endedAt ?:",
    "Yaknehaz order when Shabbat leads into Yom Tov": 'סדר יקנה"ז כששבת נכנסת ליום טוב',
    "You may open the app again $tzeitNote — $endLabel.": "ניתן לפתוח שוב את האפליקציה $tzeitNote — $endLabel.",
    "blessing over fire in Yaknehaz and regular Havdalah": 'בורא מאורי האש — ברכה על האש ביקנה"ז ובהבדלה רגילה',
    "Ten Days of Repentance from Rosh Hashana to Yom Kippur": "עשרת ימי תשובה — מראש השנה עד יום כיפור",
    "Shalom bayit — peace in the home; a central Jewish value": "שלום בית — שלום בבית; ערך יהודי מרכזי",
    "guarding one's speech from lashon hara and harmful words": "שמירת הלשון — שמירה מלשון הרע ומדיבור מזיק",
    "tradition faithfully transmitted generation to generation": "מסורה — מסורה שנמסרה נאמנה מדור לדור",
    "Gemara — Talmudic commentary and discussion on the Mishnah": "גמרא — פרשנות ודיון תלמודי על המשנה",
    "fearing of Heaven; living with awareness that G-d is present": "יראת שמים — חיים במודעות לנוכחות ה'",
    "gabbai — synagogue officer who coordinates aliyot and services": "גבאי — מתאם עליות ותפילות בבית כנסת",
    "assur bemelacha — forbidden to do melacha on Shabbat or Yom Tov": "אסור במלאכה — אסור לעשות מלאכה בשבת או ביום טוב",
    "karmelit — rabbinic semi-public area with carrying restrictions": "כרמלית — אזור חצי-ציבורי דרבנן עם הגבלות על הוצאה",
    "HaNeiros halalu — paragraph sung after lighting Chanukah candles": "הנרות הללו — פסוקה הנשירה לאחר הדלקת נרות חנוכה",
    "festive meal tied to a mitzvah (e.g. brit, siyum, wedding, etc.)": "סעודת מצווה — סעודה חגיגית הקשורה למצווה (למשל ברית, סיום, חופה וכו')",
    "Nachum Ish Gamzu — sage known for finding good in every situation": "נחום איש גמזו — חכם הידוע במציאת טוב בכל מצב",
    "imitating divine kindness (clothing the needy, visiting the sick)": "הליכה בדרכי ה' — חיקוי חסד אלוקי (הלבשת עניים, ביקור חולים)",
    "charity box; collecting coins for those in need is itself a mitzvah": "קופת צדקה — איסוף מטבעות לנזקקים הוא בפני עצמו מצווה",
    "mesorah — tradition faithfully transmitted generation to generation": "מסורה — מסורה שנמסרה נאמנה מדור לדור",
    "Give the next person you see a blessing for a long and healthy life.": "תנו לאדם הבא שתפגשו ברכה לחיים ארוכים ובריאים.",
    "Eruv techumin — extends the Shabbat walking boundary in special cases": "עירוב תחומין — מרחיב את תחום הליכת השבת במקרים מיוחדים",
    "hakarat hatov — recognizing the good; thanking someone for a kindness": "הכרת הטוב — הכרה בטובה; הודאה למישהו על חסד",
    "refuah shleimah — complete healing; said when praying for someone ill": "רפואה שלמה — ריפוי מלא; נאמר בתפילה עבור חולה",
    '"guard (Shabbat)" from the Deuteronomy version of the Ten Commandments': "«שמור (שבת)» מנוסח דברים של עשרת הדיברות",
    "loving your fellow Jew — central Torah principle taught by Rabbi Akiva": "ואהבת לרעך כמוך — עיקרון תורה מרכזי שלמד רבי עקיבא",
    "palm branch waved with the etrog, willows, and myrtle branches on Sukkot": "לולב — ענף דקל שננענע עם אתרוג, ערבות והדסים בסוכות",
    "melachot — the 39 categories of transformative labor forbidden on Shabbat": 'מלאכות — ל"ט קטגוריות של מלאכה משנה האסורה בשבת',
    'Shamor — "guard (Shabbat)" from the Deuteronomy version of the Ten Commandments': "שמור — «שמור (שבת)» מנוסח דברים של עשרת הדיברות",
    "This year, Shabbat is Erev $chagName — $chagName begins tonight at nightfall (Motzei Shabbat). This doesn't happen every year.": "השנה שבת היא ערב $chagName — $chagName מתחיל הלילה עם צאת השבת (מוצאי שבת). זה לא קורה בכל שנה.",
}
