"""Shared ES formal (usted) → informal (tú) conversion for app copy."""

from __future__ import annotations

import re

_ES_TU_PAIRS: tuple[tuple[str, str], ...] = (
    # Reflexive / compound imperatives (before bare « su »)
    ("prepárese", "prepárate"),
    ("Prepárese", "Prepárate"),
    ("asegúrese", "asegúrate"),
    ("Asegúrese", "Asegúrate"),
    ("procúrese", "procúrate"),
    ("Procúrese", "Procúrate"),
    ("lávese", "lávate"),
    ("Lávese", "Lávate"),
    ("acuérdese", "acuérdate"),
    ("Acuérdese", "Acuérdate"),
    ("Siéntese", "Siéntate"),
    ("siéntese", "siéntate"),
    ("levántese", "levántate"),
    ("Levántese", "Levántate"),
    ("deténgase", "detente"),
    ("Deténgase", "Detente"),
    ("concéntrese", "concéntrate"),
    ("Concéntrese", "Concéntrate"),
    ("tómese", "tómate"),
    ("Tómese", "Tómate"),
    ("preocúpese", "preocúpate"),
    ("Preocúpese", "Preocúpate"),
    # Phrase fixes before single-word imperatives
    ("pregunte a su", "pregunta a tu"),
    ("Pregunte a su", "Pregunta a tu"),
    ("consulte a su", "consulta a tu"),
    ("Consulte a su", "Consulta a tu"),
    ("confirme con su", "confirma con tu"),
    ("Confirme con su", "Confirma con tu"),
    ("confirme con el", "confirma con el"),
    ("Confirme con el", "Confirma con el"),
    ("siga su", "sigue tu"),
    ("Siga su", "Sigue tu"),
    ("siga el", "sigue el"),
    ("Siga el", "Sigue el"),
    ("siga la", "sigue la"),
    ("Siga la", "Sigue la"),
    ("use su", "usa tu"),
    ("Use su", "Usa tu"),
    ("use el", "usa el"),
    ("Use el", "Usa el"),
    ("use la", "usa la"),
    ("Use la", "Usa la"),
    ("use vino", "usa vino"),
    ("Use vino", "Usa vino"),
    ("utilice su", "utiliza tu"),
    ("Utilice su", "Utiliza tu"),
    ("utilice el", "utiliza el"),
    ("Utilice el", "Utiliza el"),
    ("utilice la", "utiliza la"),
    ("Utilice la", "Utiliza la"),
    ("necesita eruv", "necesitas eruv"),
    ("Necesita eruv", "Necesitas eruv"),
    ("puede cocinar", "puedes cocinar"),
    ("Puede cocinar", "Puedes cocinar"),
    ("puede beber", "puedes beber"),
    ("Puede beber", "Puedes beber"),
    ("debe ayunar", "debes ayunar"),
    ("Debe ayunar", "Debes ayunar"),
    ("debe decir", "debes decir"),
    ("Debe decir", "Debes decir"),
    ("si tiene dudas", "si tienes dudas"),
    ("Si tiene dudas", "Si tienes dudas"),
    ("si no está seguro", "si no estás seguro"),
    ("Si no está seguro", "Si no estás seguro"),
    ("si no está segura", "si no estás segura"),
    ("Si no está segura", "Si no estás segura"),
    ("cuando tenga", "cuando tengas"),
    ("Cuando tenga", "Cuando tengas"),
    ("antes de que comience", "antes de que comiences"),
    # Possessives (user-facing)
    (" su rav", " tu rav"),
    (" su rabino", " tu rabino"),
    (" su sidur", " tu sidur"),
    (" su comunidad", " tu comunidad"),
    (" su kehilá", " tu kehilá"),
    (" su kehilla", " tu kehilla"),
    (" su minhag", " tu minhag"),
    (" su tradición", " tu tradición"),
    (" su siddur", " tu siddur"),
    (" su machzor", " tu machzor"),
    (" sus zmanim", " tus zmanim"),
    (" Su rav", " Tu rav"),
    (" Su rabino", " Tu rabino"),
    (" Su sidur", " Tu sidur"),
    (" Su comunidad", " Tu comunidad"),
    # Capitalized imperatives
    ("Consulte siempre", "Consulta siempre"),
    ("Consulte ", "Consulta "),
    ("consulte ", "consulta "),
    ("Pregunte ", "Pregunta "),
    ("pregunte ", "pregunta "),
    ("Confirme ", "Confirma "),
    ("confirme ", "confirma "),
    ("Utilice ", "Utiliza "),
    ("utilice ", "utiliza "),
    ("Siga ", "Sigue "),
    ("siga ", "sigue "),
    ("Use ", "Usa "),
    ("use ", "usa "),
    ("Recite ", "Recita "),
    ("recite ", "recita "),
    ("Observe ", "Observa "),
    ("observe ", "observa "),
    ("Evite ", "Evita "),
    ("evite ", "evita "),
    ("Prepare ", "Prepara "),
    ("prepare ", "prepara "),
    ("Aprenda ", "Aprende "),
    ("aprenda ", "aprende "),
    ("Estudie ", "Estudia "),
    ("estudie ", "estudia "),
    ("Verifique ", "Verifica "),
    ("verifique ", "verifica "),
    ("Configure ", "Configura "),
    ("configure ", "configura "),
    ("Ajuste ", "Ajusta "),
    ("ajuste ", "ajusta "),
    ("Complete ", "Completa "),
    ("complete ", "completa "),
    ("Termine ", "Termina "),
    ("termine ", "termina "),
    ("Empiece ", "Empieza "),
    ("empiece ", "empieza "),
    ("Continúe ", "Continúa "),
    ("continúe ", "continúa "),
    ("Encienda ", "Enciende "),
    ("encienda ", "enciende "),
    ("Apague ", "Apaga "),
    ("apague ", "apaga "),
    ("Revise ", "Revisa "),
    ("revise ", "revisa "),
    ("Procure ", "Procura "),
    ("procure ", "procura "),
    ("Escuche ", "Escucha "),
    ("escuche ", "escucha "),
    ("Haga ", "Haz "),
    ("haga ", "haz "),
    ("Diga ", "Di "),
    ("diga ", "di "),
    ("Beba ", "Bebe "),
    ("beba ", "bebe "),
    ("Coma ", "Come "),
    ("coma ", "come "),
    ("Lave ", "Lava "),
    ("lave ", "lava "),
    ("Vaya ", "Ve "),
    ("vaya ", "ve "),
    ("Tome ", "Toma "),
    ("tome ", "toma "),
    ("Elija ", "Elige "),
    ("elija ", "elige "),
    ("Active ", "Activa "),
    ("active ", "activa "),
    ("Marque ", "Marca "),
    ("marque ", "marca "),
    ("Anote ", "Anota "),
    ("anote ", "anota "),
    ("Escriba ", "Escribe "),
    ("escriba ", "escribe "),
    ("Lea ", "Lee "),
    ("lea ", "lee "),
    ("Mire ", "Mira "),
    ("mire ", "mira "),
    ("Mantenga ", "Mantén "),
    ("mantenga ", "mantén "),
    ("Permita ", "Permite "),
    ("permita ", "permite "),
    ("Recuerde ", "Recuerda "),
    ("recuerde ", "recuerda "),
    ("Pida ", "Pide "),
    ("pida ", "pide "),
    ("Busque ", "Busca "),
    ("busque ", "busca "),
    ("Encuentre ", "Encuentra "),
    ("encuentre ", "encuentra "),
    ("Usted ", "Tú "),
    (" usted ", " tú "),
)

_ES_TU_POST: tuple[tuple[str, str], ...] = (
    ("tu tu ", "tu "),
    ("Tu tu ", "Tu "),
    ("usa tu tu ", "usa tu "),
    ("Usa tu tu ", "Usa tu "),
    ("sigue tu tu ", "sigue tu "),
    ("tú puedes cocinar", "puedes cocinar"),
    ("Tú puedes", "Puedes"),
)


def apply_es_tu(text: str) -> str:
    """Convert formal usted/su to tú/tu in direct-address UI copy; preserve « » quotes."""
    protected: list[str] = []

    def prot(m: re.Match[str]) -> str:
        protected.append(m.group(0))
        return f"__PROT{len(protected) - 1}__"

    text = re.sub(r"«[^»]*»", prot, text)
    for old, new in _ES_TU_PAIRS:
        text = text.replace(old, new)
    for old, new in _ES_TU_POST:
        text = text.replace(old, new)
    for i, chunk in enumerate(protected):
        text = text.replace(f"__PROT{i}__", chunk)
    return text
