"""FR tu rewrites for Learn-about explainers still using vous."""

PREFIX_FR_TU_EXPLAINERS: dict[str, str] = {
    'Learn about Oneg Shabbat!': (
        "Oneg Chabbat ! 🍽️ Prendre plaisir au Chabbat n'est pas qu'une agréable coutume — c'est une mitsva et partie de sa sainteté. Repas festifs, repos, étude de Torah, prière et temps en famille. Le Talmud (Chabbat 118a) promet d'abondantes bénédictions à qui se délecte du Chabbat. Savourez, faites la sieste du Chabbat, détends-toi : chaque plaisir pour honorer le jour est mitsva. Apprends une halakha sur les repas de Chabbat pour enrichir ta table."
    ),
    'Learn about honoring the Kohanim!': (
        "Apprends à honorer les Kohanim ! Les Kohanim sont les descendants mâles d'Aharon le Cohen dans la Torah ! C'étaient eux qui accomplissaient le service dans le Beit HaMikdash, offrant tous les sacrifices de la nation devant Hashem sur l'autel. Même aujourd'hui, ils sont toujours tenus à un niveau de sainteté plus élevé, ce qui signifie qu'ils doivent éviter le contact avec les morts et suivre des lois matrimoniales spécifiques pour maintenir leur niveau spirituel. Dans notre vie quotidienne, nous honorons leur statut élevé en leur accordant la première Aliyah à la synagogue lors de la lecture de la Torah, et en sollicitant leur Bénédiction sacerdotale (dans les communautés hors d'Israël, cela n'a lieu parfois qu'aux jours de fête). C'est aussi une belle tradition de montrer un respect supplémentaire aux Kohanim observants en ne leur demandant pas d'accomplir des tâches ménagères ou des corvées personnelles, reconnaissant que leur temps est consacré à un but plus élevé. En les traitant avec cette dignité particulière, nous gardons vivante l'étincelle ancienne de la prêtrise dans notre monde moderne. Ton mission : la prochaine fois que tu verrez un Kohen, souviens-toi de lui accorder un honneur spécial et de ne pas lui demander de faire des tâches ménagères pour toi ;)."
    ),
    'Learn about kavod sefarim': (
        "Apprends le kavod sefarim — l'obligation halachique de traiter les livres saints avec respect — et le niveau de détail surprenant que cela implique ! 📚 Le Rambam statue que les écrits de Torah ont une sainteté inhérente. Règles pratiques du Choulhan Aroukh et des poskim : (1) Ne pose pas un livre saint face contre terre — c'est irrespectueux. (2) Ne t'assieds pas sur une surface où se trouve un livre de Torah. (3) N'utilise pas un livre de Torah comme oreiller ou appui-tête, ni pour tes propres besoins comme bloquer la pluie ou le soleil de tes yeux. (4) La hiérarchie compte : un 'Houmash (Cinq Livres) a une sainteté supérieure à Na'h (Prophètes/Écrits) ; Na'h a une sainteté supérieure à un Guémara ou autres livres. La sainteté supérieure va DESSUS. (5) Quand un sefer tombe par terre, il est d'usage de l'embrasser en le ramassant. (6) Si un sefer devient trop usé pour être lu, il ne peut pas être jeté — il doit aller au geniza (stockage respectueux/inhumation). De nombreuses communautés ont une geniza communautaire pour les livres saints usés."
    ),
    "Learn about ona'ah": (
        "Apprends l'ona'ah — l'interdiction toranique de la fraude sur les prix — et la fascinante règle du 1/6 qui détermine exactement quand elle s'applique ! 💼 La Torah dit : « Ne trompe pas ton prochain » (Lévitique 25:17). Les Sages précisent que cela s'applique aux transactions financières : si tu vendes quelque chose à un prix SUPÉRIEUR de plus de 1/6 à sa valeur marchande, ou l'achètes INFÉRIEUR de plus de 1/6 à la valeur marchande — c'est de l'ona'ah, et la transaction peut être annulée halachiquement. Si quelque chose est très difficile à obtenir dans une certaine région du monde, alors la personne qui le vend a plus de liberté pour fixer les prix, puisqu'elle fixe effectivement le prix pour cette région !"
    ),
    'Learn about one of the main vessels of the Beit HaMikdash': (
        "Apprends l'un des principaux ustensiles du Beit HaMikdash — la sainte Menorah. Savais-tu qu'il existe un débat fascinant entre les Sages sur la fréquence réelle de l'allumage de la Menorah dans le Beit HaMikdash ? Bien qu'il soit communément admis que les lampes étaient allumées une fois par jour vers le soir pour brûler toute la nuit — une opinion défendue par le Raavad et le Rashba — le Rambam (Maïmonide) soutient que la Menorah était en réalité allumée deux fois par jour, matin et soir, pour garantir une lumière véritablement continue. Ajoutant une couche de mystère, le Talmud et l'Alter Rebbe expliquent que même si les autres lampes s'éteignaient, la Lampe occidentale (il y a beaucoup de discussions sur laquelle des 7 bougies il s'agissait exactement) restait allumée toute la journée comme témoignage miraculeux que la Présence divine reposait parmi le peuple d'Israël ! Apprenez-en plus !"
    ),
    'Learn about saying the Shema!': (
        "Apprends à dire le Shema ! Bonne nouvelle — tu peux le dire debout, en marchant, ou même en chevauchant ton âne fidèle (ou en voiture, de nos jours 😉). N'essaie simplement pas de le dire allongé sur le dos ou le ventre — ce n'est pas permis. S'allonger sur le côté, c'est parfait ! Et si tu ne tu sentez pas bien ou ne pouvez pas tu tourner sur le côté ? Pas de souci — penche-toi un peu sur le côté et c'est bon. L'essentiel est de le dire d'une manière qui montre du respect tout en restant pratique pour ton situation."
    ),
    'Learn about seeing the good in everything!': (
        "Apprends à voir le bien en tout ! Quand la vie t'envoie une épreuve, essaie de dire « Gam zu l'tovah » (גם זו לטובה) — ceci aussi est pour le bien ! ✡ Cette phrase puissante a été rendue célèbre par le sage Nahoum Ish Gam Zu, qui trouvait toujours une lumière cachée. Même dans les moments difficiles, ayez confiance que D. a un plan parfait. C'est comme un GPS pour l'âme — parfois l'itinéraire semble étrange, mais il tu mène exactement où tu dois aller ! 🗺️"
    ),
    'Learn about thanking Hashem for sustaining you!': (
        "Apprends à remercier D. de te sustenter ! 🍞 Le Birkat Hamazon (bénédiction après le repas) est unique car c'est l'une des seules bénédictions commandées directement dans la Torah — après un repas avec du pain. Toutes les autres bénédictions avant et après les aliments ont été instituées par les rabbins. Ce n'est pas un simple « merci pour la nourriture », mais un voyage en quatre parties à travers l'histoire juive ! D'abord « HaZan », écrit par Moshe pour remercier D. de la Manne dans le désert (nourriture miraculeuse tombée du Ciel). Ensuite « HaAretz », écrit par Yehoshoua en hommage à la Terre d'Israël. 🇮🇱 Troisièmement « Boneh Yerushalayim », ajouté par les rois David et Shlomo pour prier pour la Ville Sainte. Enfin « Hatov Vehametiv », ajouté par les Sages après le miracle de Betar ! 🕊️ Pour le faire correctement, tu dois manger au moins un « kazayit » de pain (environ la taille d'une balle de golf) en environ 4 à 9 minutes. Si trois hommes ou plus mangent ensemble, ils forment un « Zimoun » — une invitation formelle à bénir en équipe — ce qui élève la sainteté ! 🤝 La halakha dit que tu devriez tu asseoir et tu concentrer sur les mots. On dirait une pastille après le dîner ! On fabrique des mitzvot, la famille ! 🎊🍷"
    ),
    "Learn about the Rambam's specific, practical description": (
        "Apprends la description spécifique et pratique du Rambam de ce à quoi ressemblera réellement l'ère messianique — tu pourrais être surpris par son côté terre-à-terre ! 🌍 La célèbre décision du Rambam (Hilchot Melachim 11-12) : « Le Roi messianique se lèvera et restaurera la monarchie de David à sa gloire d'antan... Il reconstruira le Temple et rassemblera tout Israël. » Mais le Rambam ajoute ensuite quelque chose de remarquable : « Ne pensez pas que le monde s'écartera de son cours normal à l'ère messianique... Le loup ne habitera pas avec l'agneau — c'est une métaphore pour Israël habitant paisiblement parmi les nations. » Le Rambam statue explicitement que l'ère messianique sera un temps NATUREL, pas surnaturel. Les arbres devront encore être plantés, le soleil se lèvera et se couchera normalement. La différence : Israël sera libre de l'oppression étrangère, et pourra se consacrer à l'étude de la Torah sans distraction. « En ce temps, il n'y aura ni famine, ni guerre, ni jalousie, ni conflit — car les biens seront abondants, et toutes les délicatesses disponibles comme la poussière. » Et le but ultime : « Les sages et les prophètes n'ont pas aspiré à l'ère messianique pour gouverner le monde ou pour manger, boire et s'amuser — mais pour être libres d'étudier la Torah et la sagesse, sans que personne ne les opprime. » D'autres rabbins ne sont pas d'accord et estiment que le monde ne sera pas si normal, mais plutôt une époque de miracles ouverts. Lequel penses-tu serait le mieux ?"
    ),
    'Learn about the Tithe-to-Table system': (
        "Apprends le système Tithe-to-Table qui transforme chaque collation israélienne en mission sainte ! 🧺 En terre d'Israël, tes fruits et légumes ne sont pas que de la nourriture — ils font partie d'un immense cycle spirituel. Avant de pouvoir prendre une seule bouchée, tu dois déclasser le produit de son état restreint appelé Tevel en séparant plusieurs portions spécifiques. 🏛️ L'ordre sacré des opérations commence par la Terumah Gedolah, une portion de la récolte originellement donnée aux Kohanim. Comme elle est super sainte, seuls les Kohanim en état de pureté pouvaient la manger (personne n'est en état de pureté aujourd'hui, donc nous ne la mangeons pas de nos jours). 🕊️ Vient ensuite le Maaser Rishon, où dix pour cent de ce qui reste va aux Lévites. Puis vient la dîme alternée appelée Maaser Sheni ou Ani. Les années un, deux, quatre et cinq du cycle de Shemittah, tu preniez encore dix pour cent à Jérusalem pour un festin saint ! Mais les années trois et six, cette portion devient Maaser Ani et va directement aux pauvres. 🍎🤝 Même aujourd'hui, si tu fais tes courses dans un shouk israélien, tu pourrais rencontrer du Tevel, c'est-à-dire de la nourriture qui n'a pas encore été traitée. La halakha moderne maintient la tradition vivante en séparant de petites quantités symboliques. C'est comme une taxe spirituelle qui nous rappelle que la terre ne nous appartient pas, elle appartient à Hashem !"
    ),
    'Learn about the Torah obligation to TEACH': (
        "Apprends l'obligation toranique d'ENSEIGNER — pas seulement d'apprendre — et la mitzvah spécifique de « v'shinantam l'vanecha » ! 📚 La Torah dit : « Tu les enseigneras soigneusement à tes enfants » (Deutéronome 6:7). C'est un commandement positif pour tout adulte juif d'enseigner la Torah — et plus précisément, l'obligation est d'abord envers ses propres enfants. Le Rambam statue (Hilchot Talmud Torah 1:1) : un père est obligé d'enseigner la Torah à son fils. Si le père ne peut pas enseigner, il doit engager un professeur. Quand l'obligation commence-t-elle ? Dès que l'enfant peut parler ! Les premiers mots que tu enseignez à un enfant devraient être de la Torah — traditionnellement le verset « Torah tzivah lanu Moshe » et le Shema. Sens élargi : le Talmud statue que « l'vanecha » signifie à la fois les enfants biologiques ET les élèves. Enseigner des élèves, c'est comme élever des enfants spirituels. La mitzvah s'applique aussi à chaque personne elle-même : tu dois apprendre pour pouvoir enseigner. Une décision fascinante : tu n'avez PAS le droit de demander de l'argent pour enseigner la Torah elle-même. Un professeur peut facturer le temps perdu pour d'autres travaux (comme coût d'opportunité), mais un paiement direct POUR l'enseignement de la Torah est déconseillé et considéré comme une forme de profanation de la Torah. C'est pourquoi de nombreux professeurs de Talmud étaient historiquement soutenus par des fonds communautaires plutôt que par les frais de scolarité des élèves."
    ),
    "Learn about the Torah's obligations of respect for Torah scholars": (
        "Respect des savants et des anciens 🙌 « Devant les cheveux blancs, lève-toi » (Vayikra 19:32). Deux mitsvot : personnes âgées (70+) et talmid 'hakham. Lève-toi quand ils approchent à environ deux mètres ; pour un gadol, dès l'entrée dans la pièce — ne tu asseyez pas avant qu'il soit à sa place. Ne ridiculisez pas un savant — le Talmud compare cela à la destruction du Temple ; l'honneur des sages soutient toute la communauté."
    ),
    'Learn about the divine command to have the best time': (
        "Apprends le commandement divin de passer le meilleur moment de ta vie ! 🎊 La Torah ne se contente pas de suggérer de s'amuser les jours de fête — elle le commande littéralement avec la mitzvah de Sim'hat Yom Tov ! Cela s'applique aux « Trois Grands » festivals : Pessa'h, Chavouot et Souccot ! 🗓️ Puisque « il n'y a pas de vraie joie sans viande et vin », le menu des fêtes est essentiellement un devoir saint. 🍷🥩 Mais la halakha sait que chacun trouve la joie différemment, alors elle détaille le plan de fête pour toute la famille ! Pour les hommes, l'accent est mis sur la viande délicieuse et le vin. Pour les femmes, la mitzvah s'accomplit en obtenant de nouveaux vêtements ou bijoux spécifiquement pour la fête ! Pour les enfants, c'est tout sur le rush de sucre — leur donner des friandises et des noix pour maintenir l'ambiance festive ! 🍬 Le chef de famille est tenu de fournir ces choses à sa famille selon ses moyens ! Nos Sages avertissent aussi que si tu festoyez seulement avec ton propre famille en fermant la porte, tu ne faites pas de la « joie de fête » mais seulement de la « joie d'estomac ». Pour bien faire, il faut tirer une chaise supplémentaire pour les pauvres et les seuls, car le vrai bonheur n'est réel que lorsqu'il est partagé ! Au minimum, tu devriez donner de la tsedaka à une personne juive dans le besoin pour qu'elle puisse aussi profiter de la fête. Apprenez-en plus et prépare-toi pour la prochaine fête, quelle qu'elle soit !"
    ),
    'Learn about the fascinating laws of Nedarim': (
        "Nedarim — vœux : les paroles peuvent rendre un objet interdit pour toi. La Torah prévoit hatarat nedarim — annulation par un sage. Le Rambam (Hilkhot Nedarim 4:13) décrit des cas où quelqu'un jure de ne pas profiter d'une ville entière puis a besoin d'eau d'un puits communal. Les mots comptent — demande à ton rav avant de jurer. Un vœu mal formulé peut compliquer la vie — la Torah prévoit l'annulation par un sage."
    ),
    'Learn about the gid ha-nasheh': (
        "Gid hanashe — le nerf sciatique interdit ; une des rares mitsvot avec raison explicite dans la Torah (Berechit 32:33) : Yaakov lutta toute la nuit avec l'ange et boita à l'aube. En cacheroute on l'extrait de la hanche ; beaucoup ne mangent que « glatt » avec contrôle approfondi. Souviens-toi de la lutte de Yaakov et de la fragilité humaine même après la victoire spirituelle. Le gid hanashe rappelle que même les grands peuvent boiter après une nuit de lutte."
    ),
    'Learn about the incredible "sliding scale" system': (
        "Apprends l'incroyable système « à échelle glissante » qui garantissait que personne ne soit jamais exclu d'un nouveau départ ! 🕊️ Le Korban Oleh V'Yored est une preuve de plus que Hashem se soucie de chaque Juif ! Selon ce que tu aviez dans ton poche, le prix de ton offrande montait ou descendait littéralement ! 📉📈 Ce système flexible s'appliquait à des moments précis comme entrer accidentellement dans le Temple ou manger de la nourriture sainte en étant impur, oublier un serment personnel et le briser accidentellement, garder le silence quand tu auriez dû témoigner, guérir de l'affection cutanée spirituelle Tzara'at, ou même l'offrande d'une jeune mère après un accouchement. Si les affaires allaient bien, tu apportiez un animal. Mais si les choses étaient un peu serrées, tu pouviez n'offrir que des oiseaux. Dans certains cas, tu pouviez même tu présenter avec un sac de farine ! 🌾 Que tu soyez un gros bonnet ou que tu tu en sortiez à peine, le chemin du retour vers la sainteté était toujours grand ouvert. Il ne s'agissait pas du coût du cadeau, mais du cœur de la personne qui l'apportait ! Ton mission : réfléchissez à la façon dont D. n'est pas comme la plupart des dirigeants humains : Il veut vraiment être connecté à Ses sujets, et pas seulement à leur argent !"
    ),
    'Learn about the incredible power of praying for everyone!': (
        "Découvre l'incroyable pouvoir de prier pour tout le monde ! 🙏 Quand tu pries (daven) D. pour des bénédictions, la santé et la parnassa (subsistance), ou pour tout bien pour tout Am Israël (le peuple juif) — et pas seulement pour toi — les Sages enseignent que ton prière a plus de chances d'être exaucée ! C'est comme un gagnant-gagnant spirituel : tu t'aides en aidant tout le monde. Qui ne voudrait pas vivre dans un monde où personne n'est stressé ? La prochaine fois que tu as besoin de bénédictions, élargissez ton champ de prière et priez pour toute la communauté !"
    ),
    'Learn about the joy of mitzvot! Take a moment': (
        "Découvre la joie de mitzvot! Prends un moment pour réfléchir sur une bonne action que tu as faite récemment et laisse-toi sentir vraiment heureux à ce sujet. Ce bonheur particulier (simcha shel)mitzvah) n'est pas seulement un bonus - il améliore en fait le mitzvah Le Talmud enseigne que servir D. avec joie est une partie fondamentale de la vie juive. Quand nous serons heureux de faire mitzvot, nous tirons encore plus de bénédictions divines !"
    ),
    'Learn about the mikveh — a bath with requirements': (
        "Apprends le mikvé — un bain aux exigences si précises que les rabbins doivent maîtriser la plomberie ! 💧 Un mikvé n'est PAS qu'une simple piscine. La loi juive a des exigences extrêmement précises : (1) Volume minimum de 40 se'ah d'eau — environ 750 litres. (2) L'eau ne peut pas être « tirée » — l'eau pompée directement d'un robinet dans le mikvé est invalide ! Elle doit venir du Ciel, c'est-à-dire de l'eau de pluie ou éventuellement de la neige transportée de manière halachiquement appropriée. (3) La personne doit être complètement immergée SANS RIEN entre son corps et l'eau — ce qui signifie pas de pansements, pas de vernis à ongles, etc. Qui utilise un mikvé aujourd'hui ? Les femmes après leur période mensuelle de niddah (l'usage principal) ; les convertis finalisant leur conversion ; certains hommes l'utilisent aussi pour atteindre un niveau de sainteté plus élevé. Beaucoup l'utilisent la veille de Yom Kippour. Les mikvot servent aussi à immerger les ustensiles achetés auprès de non-Juifs (tevilat keilim — oui, tu immergez aussi tes casseroles !). Fait amusant : quand une nouvelle communauté juive est établie, la halakha dit que le mikvé est construit AVANT la synagogue, car c'est ce qui permet aux maris et femmes d'être ensemble, ce qui est un fondement de la vie juive."
    ),
    'Learn about the mitzvah of Hadlakat Nerot': (
        "Découvre la mitsva d'Hadlakat Nerot — bougies de Chabbat — et un casse-tête halakhique fascinant ! 🕯️ Les Sages les ont instituées pour le shalom bayit, pas seulement l'ambiance : il faut profiter activement de la lumière. Et si tu accueilles Chabbat tôt alors que le soleil brille encore ? Débat du « à quoi bon une lampe à midi ? » (Houllin 60b). Maguen Avraham (O.H. 263:11) : si tu allumes et partez, assieds-toi pour en bénéficier brièvement. Choulhan Aroukh ha-Rav et Aroukh ha-Choulhan divergent : la lumière de jour est inutile — des bougies longues encore allumées au retour. Des autorités modernes comme Shemirat Chabbat Kehilchata (43:17) proposent des minuteries dans la salle à manger avec kavana que la berakha couvre bougies et lumières (Michna Beroura 263:41) — la mitsva est accomplie à la tombée de la nuit !"
    ),
    'Learn about the obligation to check your mezuzot and tefillin': (
        "Apprends l'obligation de vérifier tes mezouzot et tefillin — et à quelle fréquence le Choulhan Aroukh dit que tu dois le faire ! 🛠️ Mezouzot : le Choulhan Aroukh (Yoreh Deah 291:1) exige de vérifier les mezouzot deux fois tous les sept ans. Certains disent que si elles sont en sécurité à l'intérieur dans des climats normaux, elles peuvent rester non vérifiées à condition qu'elles étaient casher initialement. Mais dans les environnements humides ou côtiers (où le parchemin est plus susceptible d'être endommagé par l'humidité), tu devriez vérifier plus fréquemment. Signes que ton mezouza nécessite une vérification immédiate : le boîtier extérieur est fissuré, de l'eau est entrée, elle est tombée. Tefillin : tes tefillin personnelles devraient aussi être vérifiées au moins deux fois tous les 7 ans par un professionnel. Si les tefillin se mouillent ou tombent dans l'eau — vérifie immédiatement. Si elles ont été stockées inutilisées longtemps — vérifiez. Le défi pratique : la vérification nécessite d'ouvrir les boîtes, d'examiner les lettres du parchemin et de re-sceller les batim (boîtes). Seule une personne compétente et formée peut le faire. Restez saints, la famille !"
    ),
    'Learn about the power of forgiveness! Take a moment': (
        "Le pouvoir du pardon ! Prends un moment pour pardonner à qui t'a blessé, peu ou beaucoup. Tout est orchestré par D.ieu avec un dessein. Quand tu fais miséricorde, D.ieu t'en fait davantage — comme un boomerang spirituel de bonté. Lâcher la rancune libère de la place pour la joie et la paix. Avant Yom Kippour, le pardon envers autrui ouvre la porte au pardon divin. Prends un moment aujourd'hui pour lâcher une rancune — c'est un cadeau pour toi aussi."
    ),
    'Learn about the power of proper speech!': (
        "Apprends le pouvoir de la parole juste ! 🗣️ Prends un moment pour étudier ce qui est arrivé à Miriam (l'un des 10 souvenirs quotidiens) : bien qu'elle fût prophétesse et eût de bonnes intentions, elle parla avec critique de son frère Moïse et en subit les conséquences. Voici la leçon incroyable : si quelqu'un d'aussi grand que Miriam devait faire attention à ses paroles, imaginez combien tu dois être prudents ! Rappelle-toi : chaque mot que tu prononces a un pouvoir incroyable pour construire ou détruire. Utilisons ce pouvoir avec sagesse !"
    ),
    "Learn about the prohibition of 'chukot ha'akum'": (
        "Apprends l'interdiction des « houkot ha'akum » — suivre les coutumes non juives — et à quel point la halakha réelle est nuancée ! 🕊️ La Torah dit : « Ne suis pas les coutumes des nations » (Lévitique 18:3). Le Rambam et le Choulhan Aroukh codifient cela comme une interdiction d'adopter des pratiques associées aux religions non juives ou ayant pour origine des coutumes païennes. Le Choulhan Aroukh (Yoreh Deah 178) statue : une personne juive ne peut pas porter de vêtements distinctifs non juifs si le but est de les imiter, surtout pour des raisons religieuses ou idolâtres. Ce qui N'est PAS interdit : les choses universellement adoptées pour des raisons pratiques (par exemple, porter un costume-cravate — pas païen, juste un vêtement professionnel pratique). L'interdiction vise les coutumes qui sont « houkat hagoy » — des pratiques spécifiquement identifiées à la tradition religieuse non juive ou qui n'ont aucune base logique sauf en tant que leur tradition. Important : cette interdiction n'a rien à voir avec le manque de respect envers les non-Juifs — il s'agit de maintenir une identité juive distincte et d'éviter la confusion spirituelle !"
    ),
    'Learn about the prohibition of receiving lashon hara': (
        "Apprends l'interdiction de recevoir du lashon hara — qui est tout aussi grave que de le prononcer, et qui est en réalité plus difficile à éviter ! 🤐 Le Hafets 'Haïm statue : il est interdit d'ÉCOUTER le lashon hara et d'y croire. Plus précisément, il est interdit de : (1) Écouter attentivement et encourager l'orateur à continuer ; (2) Prendre plaisir à entendre l'information négative ; (3) Croire ce que tu as entendu comme un fait établi. Le Talmud dit qu'une personne qui écoute du lashon hara est en réalité pire que l'orateur, car l'orateur peut faire téshouva en disant à la personne dont il a parlé qu'il a inventé — mais l'auditeur a déjà reçu l'information dans son esprit et le dommage à sa perception est fait. Implications pratiques : si quelqu'un commence à toi dire quelque chose de négatif sur un tiers et que tu êtes coincé dans la conversation — tu as deux niveaux d'obligation : (a) Essayer de rediriger ou de sortir. (b) Si tu êtes coincé, décider consciemment de NE PAS croire ce que tu entendez. Tu pouvez écouter sans croire. Le Hafets 'Haïm appelle cela « entendre sans accepter ». Une intuition clé : nous sommes commandés de NE PAS croire le lashon hara à propos d'un autre Juif — même si nous ne pouvons pas immédiatement le réfuter. Nous devons maintenir la présomption d'innocence. C'est extrêmement contre-intuitif pour nos oreilles modernes, mais c'est la halakha réelle. Source : Hafets 'Haïm, Hilchot Rechilut ; Talmud, Niddah 61a."
    ),
    'Learn about the quality-control laws for offerings': (
        "Apprends les lois de contrôle qualité pour les offrandes dans le Beit HaMikdash ! Un animal offert au Maître de l'Univers devait être parfait. Le Rambam énumère des dizaines de défauts physiques (aussi appelés « mum ») qui disqualifient un animal. Si un animal a un défaut permanent comme un membre manquant ou un os cassé, il ne peut jamais être offert, tandis que les défauts temporaires comme une affection cutanée en voie de guérison ne disqualifient l'animal que jusqu'à sa guérison. D'autres caractéristiques disqualifiantes incluent un œil trop grand ou trop petit, être trop vieux, ou même simplement sentir mauvais ! Le message plus profond ici est que ce que nous offrons représente ce que nous valorisons. Tu n'offrirais pas un cadeau gâté à un roi, et les standards du Temple nous rappellent que le service divin repose sur un investissement authentique et sur le fait de donner son absolu meilleur, pas seulement ses restes ! Réfléchis-y une minute !"
    ),
    'Learn about the ultimate "legal permit" to enjoy the world': (
        "Apprends le « permis légal » ultime pour profiter du monde ! 🍎 Le Talmud dit que tout sur terre appartient à D., alors prendre une bouchée sans bénédiction, c'est comme « voler » au palais du Roi. Dire une bénédiction (bracha), c'est essentiellement demander la permission et transformer une collation physique en moment spirituel ! 🏛️ Le système est incroyablement précis : si ça pousse sur un arbre, tu dites « Ha'etz ». Si ça vient du sol, c'est « Ha'adamah ». Pour le pain, tu as le poids lourd « HaMotzi », et pour tout le reste — viande, fromage ou chocolat — tu dites « Shehakol ». 🕊️ Mais il y a le VIP du monde des boissons : le vin ! Parce que le vin est si spécial et utilisé pour des moments saints comme le Kiddouch, il a sa propre bénédiction unique : « Boré Pri HaGafen ». 🍷 C'est si puissant que si tu buvez du vin pendant un repas, il couvre souvent toutes les autres boissons sur la table ! 🥂 Il existe même un « ordre des opérations » spécifique appelé Mag'a Esh pour toi aider à décider quel aliment reçoit la bénédiction en premier si tu as une grande assiette. 🍇 C'est comme une session d'entraînement quotidienne à la pleine conscience — s'arrêter pour reconnaître exactement d'où vient ton nourriture et toutes les créations, goûts et saveurs merveilleux que D. a mis dans le monde pour que nous en profitions 🎊🥯."
    ),
    "Learn about the ultimate 'Heavenly delivery service'": (
        "Apprends le « service de livraison céleste » ultime qui a sustenté une nation pendant quarante ans ! ☁️ La Manne était une nourriture surnaturelle qui tombait du ciel chaque matin, et la halakha qui l'entoure est absolument fascinante. C'était l'« alimentation saine » originelle car elle était parfaitement absorbée par le corps sans aucun déchet ! 🥯 Chaque personne recevait exactement un « omer » (environ le volume de 43 œufs), peu importe combien elle essayait d'en accumuler. Si tu en gardiez pour le lendemain, elle se gâtait miraculeusement — enseignant à la nation la leçon ultime de faire confiance à D. pour son pain quotidien ! 🕊️ Mais le vendredi, la « double portion » tombait, donnant à chacun assez pour le Chabbat sans aucun travail. C'est d'ailleurs de là que vient la coutume d'avoir deux pains de 'hallah sur nos tables de Chabbat aujourd'hui ! 🍞🍞 Le midrash dit qu'elle avait le goût de ce que tu imaginiez — du gâteau au miel à un steak savoureux — ce qui en faisait le menu le plus polyvalent de l'histoire. 🍯🥩 Elle n'a cessé de tomber qu'une fois que le peuple juif a traversé le Jourdain et est entré dans la Terre d'Israël. Tu savais ? Pour que nous n'oubliions jamais ce miracle, D. a commandé à Moshe de placer un vase d'or de Manne dans le Saint des Saints, à côté de l'Arche ! 🏺 Quand le roi Yoshiyahu a caché l'Arche pour la protéger des envahisseurs avant la destruction du Temple, il a caché le vase de Manne avec elle, où il reste caché jusqu'à ce jour. Quand le Mashiah viendra, nous espérons mériter de le revoir et de dire la bénédiction sur la manne : « HaMotzi Lechem Min HaShamayim » (Celui qui fait sortir le pain des Cieux) ! On parle d'un petit-déjeuner de champions !"
    ),
    'Learn about the ultimate spiritual "high-voltage" connection!': (
        "Les téfilines sont deux petites boîtes de cuir noir contenant des passages de la Torah, portées pendant la prière du matin. C'est l'une des mitsvot quotidiennes les plus importantes pour les hommes juifs.\n\nCe que c'est :\nLes téfilines (תְּפִלִּין) sont deux boîtes de cuir noir, chacune avec quatre passages de la Torah écrits à la main sur parchemin.\n• Shel yad (de la main) : sur le bras près du cœur, avec le lien enroulé sept fois autour de l'avant-bras puis sur la main.\n• Shel rosh (de la tête) : sur le sommet de la tête, centrée au-dessus de la ligne des cheveux, les liens pendant devant.\n\nSource torahique :\n« Lie-les comme un signe sur ton bras… entre tes yeux » (Deutéronome 6:8), lu dans le Shema.\n\nPourquoi on les porte :\nElles unissent l'esprit (boîte de la tête), le cœur (boîte du bras) et l'action (main enroulée) à D.ieu pendant la prière.\n\nQuand les mettre :\nLa bénédiction du talit et des téfilines se dit à misheyakir — quand il y a assez de lumière pour reconnaître quelqu'un de loin. La Michna Beroura recommande d'attendre misheyakir avant le Shema et l'Amida.\n\nSi tu dois partir très tôt au travail :\n• Idéal : après misheyakir ; Amida au lever du jour.\n• Sinon : Igrot Moshe (O.H. 4:6) permet un cas particulier avant misheyakir — demande à ton rav.\n\nL'application débloque cet élément à misheyakir selon tes zmanim locaux.\n\nQuand on ne les porte pas :\n• Chabbat et Yom Tov\n• Hol hamoed de Pessah et Souccot — selon le minhag ; demande à ton rav.\n\nPour commencer :\nDes téfilines casher sont un investissement important. N'achète pas bon marché — beaucoup ne sont pas valides. Demande à ton rav de toi aider à en acquérir et à apprendre à les poser."
    ),
    "Learn about the world's first mandatory RSVP event - the Korban Pesach": (
        "Apprends le premier événement obligatoire avec RSVP au monde — le Korban Pesach ! 🐑 Ce n'était pas qu'une mitzvah, c'était un miracle logistique. Imagine des centaines de milliers de personnes descendant sur Jérusalem avec un seul objectif : faire griller assez de viande pour nourrir toute la nation ! 🌃 Mais tu ne pouvais pas simplement entrer et acheter quelques côtelettes d'agneau. Tu devais être inscrit sur l'animal d'un groupe spécifique avant même le coucher du soleil. Chaque personne devait faire partie d'une « 'haburah » ou groupe enregistré. Si tu n'étais pas sur la liste, tu ne mangeais pas ! 📝 L'après-midi du 14 Nissan, pratiquement tout Juif valide du pays se présentait au Temple en même temps. Pour gérer cette heure de pointe sacrée, les prêtres divisaient tout le monde en trois immenses rotations. Dès que le premier groupe remplissait la cour, les lourdes portes se fermaient et le service commençait ! C'est là que ça devient cinématographique, car les Kohanim (prêtres) se tenaient en lignes parfaitement orchestrées s'étendant jusqu'à l'autel. Une rangée ne tenait que des bols d'or et la suivante que de l'argent. Au fur et à mesure que les agneaux ou chèvres étaient offerts, le sang était passé de main en main le long de la ligne comme un relais ! Une fois ton animal abattu et son sang aspergé sur l'autel, tu récupérais ton animal. Chaque groupe se rendait ensuite là où il logeait, et devait rôtir sa viande entière, entièrement au feu ouvert, et tenir un seder de Pessa'h ! Et oublie le couteau à découper, car il t'était strictement interdit de briser un seul os ! Il devait rester entier et majestueux. 🦴 La pression était forte pour finir avant la deadline de minuit tandis que toute la ville éclatait en chants de Hallel. Jérusalem était si bondée que les toits étaient couverts de monde et que l'odeur de l'agneau rôti emplissait l'air ! C'était une célébration massive et rugissante de la liberté ! Puissions-nous mériter de la vivre nous-mêmes rapidement, dès que le Temple sera reconstruit ! En savoir plus ! 🎊🍷"
    ),
    'Learn about tochachah': (
        "Apprends la tochachah — l'obligation toranique de reprendre quelqu'un qui fait le mal — et les limites qui la rendent extrêmement difficile à accomplir en pratique ! 💬 La Torah commande : « Tu ne manqueras pas de reprendre ton prochain » (Lévitique 19:17). Le Rambam statue qu'il s'agit d'un commandement positif. Mais la halakha est pleine de conditions : (1) La tochachah doit être donnée EN PRIVÉ — jamais devant d'autres. Humilier quelqu'un en le reprenant est une transgression si grave que le Talmud la compare au meurtre. (2) Tu devez reprendre d'une voix CALME et douce — pas avec colère ni humiliation. (3) Voici la règle stupéfiante : tu dois les reprendre encore et encore — « même cent fois » si nécessaire — jusqu'à ce qu'ils acceptent ou tu demandent d'arrêter. (4) Si la personne répondra par des insultes et deviendra ENCORE plus pécheresse, tu n'êtes PAS obligé de la reprendre. Le but est d'aider, pas de provoquer. (5) Si la personne commet le péché par ignorance (elle ne sait pas que c'est mal), une opinion dit qu'il vaut mieux la laisser — « mieux vaut qu'elle pèche par ignorance que par défi ». Le Talmud dit : Rabbi Tarfon déclarait : « Je me demande s'il existe dans cette génération quelqu'un qui sait donner la tochachah » — impliquant qu'y parvenir correctement (sans humilier, au bon moment, de la bonne manière) est extraordinairement difficile. Apprenez-en plus !"
    ),
    'Learn about tumat meit': (
        "Apprends la tumat meit — l'impureté rituelle par contact avec la mort — et comment c'est en réalité la forme d'impureté la plus forte de toute la loi juive ! ☠️ Un cadavre est appelé le « père des pères de l'impureté » (avi avot hatumah) — le niveau absolu le plus élevé d'impureté rituelle dans l'ensemble du système toranique. Voici comment elle se propage : (1) Contact direct — toucher un cadavre tu rend impur pendant 7 jours. (2) Porter — porter un cadavre même sans le toucher cause aussi une impureté de 7 jours. (3) Impureté de tente (ohel) — c'est la règle la plus célèbre : toute personne ou chose À L'INTÉRIEUR du même espace clos qu'un cadavre devient impure, même sans le toucher ! Si quelqu'un meurt dans une maison, tout ce qui s'y trouve — personnes, ustensiles, meubles — devient impur simultanément. C'est pourquoi les Kohanim (prêtres) sont interdits d'entrer dans une maison avec un cadavre, ou même de marcher sur une tombe. Les Kohanim respectent cette loi aujourd'hui — c'est pourquoi tu verrez un Kohen faire un long détour dans un hôpital (ne pas traverser le bâtiment si quelqu'un a pu y mourir). La méthode de purification ? La Parah Adumah (eau aux cendres de Vache rousse) — aspergée le 3e et le 7e jour de la période d'impureté de 7 jours. Sans cela, tu restez impur indéfiniment. Comme nous n'avons pas de Vache rousse aujourd'hui, tous les Juifs sont considérés comme ayant une tumat meit."
    ),
    'Learn about tzedakah priorities': (
        "Apprends les priorités de tsedaka — la loi juive a un ordre spécifique pour qui reçoit ton argent de charité en premier ! 🎯 Le Choulhan Aroukh (Yoreh Deah 251) établit un ordre de priorité clair : (1) Tes PROPRES besoins de base viennent en premier — une personne n'est pas tenue de s'appauvrir pour donner la tsedaka. Tu devez maintenir tes standards de vie de base. (2) TON FOYER — conjoint, enfants, parents dépendant de toi. (3) PARENTÉ pauvre — les proches ont la priorité sur les plus éloignés. (4) Ton VILLE ou communauté — les pauvres de ton ville avant les pauvres d'une autre ville. (5) Les pauvres d'Israël avant les pauvres d'autres pays."
    ),
}
