"""Shared FR formal (vous) → informal (tu) conversion for app copy."""

from __future__ import annotations

import re

_FR_TU_PAIRS: tuple[tuple[str, str], ...] = (
    # Reflexive / compound imperatives (before bare « vous »)
    ("procurez-vous", "procure-toi"),
    ("Procurez-vous", "Procure-toi"),
    ("lavez-vous", "lave-toi"),
    ("Lavez-vous", "Lave-toi"),
    ("débarrassez-vous", "débarrasse-toi"),
    ("Débarrassez-vous", "Débarrasse-toi"),
    ("enveloppez-vous", "enveloppe-toi"),
    ("Enveloppez-vous", "Enveloppe-toi"),
    ("concentrez-vous", "concentre-toi"),
    ("Concentrez-vous", "Concentre-toi"),
    ("plongez-vous", "plonge-toi"),
    ("Plongez-vous", "Plonge-toi"),
    ("entraînez-vous", "entraîne-toi"),
    ("Entraînez-vous", "Entraîne-toi"),
    ("pratiquez-vous", "pratique"),
    ("Pratiquez-vous", "Pratique"),
    ("assurez-vous", "assure-toi"),
    ("Assurez-vous", "Assure-toi"),
    ("émerveillez-vous", "émerveille-toi"),
    ("Émerveillez-vous", "Émerveille-toi"),
    ("demandez-vous", "demande-toi"),
    ("excusez-vous", "excuse-toi"),
    ("arrêtez-vous", "arrête-toi"),
    ("Arrêtez-vous", "Arrête-toi"),
    ("interrogez-vous", "interroge-toi"),
    ("Interrogez-vous", "Interroge-toi"),
    ("reposez-vous", "repose-toi"),
    ("Reposez-vous", "Repose-toi"),
    ("renseignez-vous", "renseigne-toi"),
    ("Renseignez-vous", "Renseigne-toi"),
    ("hydratez-vous", "hydrate-toi"),
    ("Hydratez-vous", "Hydrate-toi"),
    ("tenez-vous", "tiens-toi"),
    ("Tenez-vous", "Tiens-toi"),
    ("réjouissez-vous", "réjouis-toi"),
    ("préparez-vous", "prépare-toi"),
    ("Préparez-vous", "Prépare-toi"),
    ("Souvenez-vous", "Souviens-toi"),
    ("souvenez-vous", "souviens-toi"),
    ("Rappelez-vous", "Rappelle-toi"),
    ("rappelez-vous", "rappelle-toi"),
    ("appelez l'organisme", "appelle l'organisme"),
    ("demandez à ton rav au début", "demande à ton rav au début"),
    ("asseyez-vous", "assieds-toi"),
    ("Opposez-vous", "Oppose-toi"),
    ("opposez-vous", "oppose-toi"),
    ("Méfiez-vous", "Méfie-toi"),
    ("méfiez-vous", "méfie-toi"),
    ("Connectez-vous", "Connecte-toi"),
    ("connectez-vous", "connecte-toi"),
    ("Qu'avez-vous", "Qu'as-tu"),
    ("qu'avez-vous", "qu'as-tu"),
    ("pouvez-vous", "peux-tu"),
    ("Pouvez-vous", "Peux-tu"),
    ("VOTRE FOYER", "TON FOYER"),
    ("tu vous aidez", "tu t'aides"),
    ("D.ieu vous en fait", "D.ieu t'en fait"),
    ("de vous sustenter", "de te sustenter"),
    ("de vous aider", "de t'aider"),
    ("N'achetez pas", "N'achète pas"),
    ("n'achetez pas", "n'achète pas"),
    ("Ne vous contentez pas", "Ne te contente pas"),
    ("ne vous contentez pas", "ne te contente pas"),
    ("si tu allumez", "si tu allumes"),
    ("tu accueillez", "tu accueilles"),
    ("tu allumez", "tu allumes"),
    ("vérifiez immédiatement", "vérifie immédiatement"),
    ("détendez-vous", "détends-toi"),
    ("penchez-vous", "penche-toi"),
    ("pensez-vous", "penses-tu"),
    ("Levez-vous", "Lève-toi"),
    ("levez-vous", "lève-toi"),
    ("Permettez-vous", "Permets-toi"),
    ("laissez-vous", "laisse-toi"),
    ("Achetez-vous", "Achète-toi"),
    ("Demandez-vous", "Demande-toi"),
    ("Voulez-vous", "Veux-tu"),
    ("Prenez un moment", "Prends un moment"),
    ("Prenez rendez-vous", "Prends rendez-vous"),
    ("Prenez ", "Prends "),
    ("prenez ", "prends "),
    ("Allez, ", "Va, "),
    ("Allez ", "Va "),
    ("Apprenez ", "Apprends "),
    ("Découvrez ", "Découvre "),
    ("Explorez ", "Explore "),
    ("Vivez ", "Vis "),
    ("Accomplissez ", "Accomplis "),
    ("Honorez ", "Honore "),
    ("Maîtrisez ", "Maîtrise "),
    ("Confirmez ", "Confirme "),
    ("confirmez ", "confirme "),
    ("activez ", "active "),
    ("Activez ", "Active "),
    ("accomplissez ", "accomplis "),
    ("accueillez ", "accueille "),
    ("Accueillez ", "Accueille "),
    ("passez ", "passe "),
    ("Passez ", "Passe "),
    ("Saviez-vous", "Savais-tu"),
    ("N'essayez", "N'essaie"),
    ("essayez", "essaie"),
    ("reconnaissez", "reconnais"),
    ("Reconnaissez", "Reconnais"),
    ("appréciez", "apprécie"),
    ("Appréciez", "Apprécie"),
    ("mangez ", "mange "),
    ("Mangez ", "Mange "),
    ("Allumez ", "Allume "),
    ("Ajoutez ", "Ajoute "),
    ("Terminez ", "Termine "),
    ("éteignez ", "éteins "),
    ("Récitez", "Récite"),
    ("Préparez ", "Prépare "),
    ("Lisez ", "Lis "),
    ("Suivez ", "Suis "),
    ("suivez ", "suis "),
    ("Choisissez ", "Choisis "),
    ("Gardez ", "Garde "),
    ("Protégez ", "Protège "),
    ("donnez ", "donne "),
    ("restez ", "reste "),
    ("Parlez ", "Parle "),
    ("Aidez-", "Aide-"),
    ("ne restez pas", "ne reste pas"),
    ("ne colportez", "ne colporte pas"),
    ("Si vous trouvez", "Si tu trouves"),
    ("enrichir votre table", "enrichir ta table"),
    ("de votre vie", "de ta vie"),
    ("votre argent", "ton argent"),
    ("vos mezouzot", "tes mezouzot"),
    ("vos enfants", "tes enfants"),
    ("vos zmanim", "tes zmanim"),
    ("vous-même", "toi-même"),
    ("vous comptererez", "tu compteras"),
    ("vous pourriez", "tu pourrais"),
    ("vous devriez", "tu devrais"),
    ("vous pouvez", "tu peux"),
    ("vous devez", "tu dois"),
    ("vous avez", "tu as"),
    ("vous priez", "tu pries"),
    ("vous faites", "tu fais"),
    ("vous aidez", "t'aides"),
    ("vous recevez", "tu reçois"),
    ("vous voyez", "tu vois"),
    ("vous allumez", "tu allumes"),
    ("vous accueillez", "tu accueilles"),
    ("vous intéresse", "t'intéresse"),
    ("vous concerne", "te concerne"),
    ("vous envoie", "t'envoie"),
    ("vous a ", "t'a "),
    ("quand vous", "quand tu"),
    ("Quand vous", "Quand tu"),
    ("si vous", "si tu"),
    ("Si vous", "si tu"),
    ("que vous", "que tu"),
    ("pour vous", "pour toi"),
    ("à vous", "à toi"),
    ("de vous", "de toi"),
    ("sur vous", "sur toi"),
    ("chez vous", "chez toi"),
    ("Vous ne", "Tu ne"),
    ("vous ne", "tu ne"),
    ("Vous êtes-vous", "T'es-tu"),
    ("vous êtes-vous", "t'es-tu"),
    ("*vous* êtes", "*tu* es"),
    ("Votre", "Ton"),
    ("votre", "ton"),
    ("Vos", "Tes"),
    ("vos", "tes"),
    ("Vous ", "Tu "),
    (" vous ", " tu "),
    (" vous.", " tu."),
    (" vous,", " tu,"),
    (" vous!", " tu!"),
    (" vous?", " tu?"),
    (" vous;", " tu;"),
    (" vous:", " tu:"),
    (" vous)", " tu)"),
    ("(vous ", "(tu "),
    ("interdit pour vous", "interdit pour toi"),
    ("Étudiez ", "Étudie "),
    ("Appelez ", "Appelle "),
    ("Sentez ", "Sens "),
    ("Répondez ", "Réponds "),
    ("Aidez ", "Aide "),
    ("Partagez ", "Partage "),
    ("refusez ", "refuse "),
    ("Refusez ", "Refuse "),
    ("consultez ", "consulte "),
    ("Consultez ", "Consulte "),
    ("priez ", "prie "),
    ("Priez ", "Prie "),
    ("étudiez ", "étudie "),
    ("Étudiez ", "Étudie "),
    ("profitez ", "profite "),
    ("Profitez ", "Profite "),
    ("Veuillez ranger ton appareil", "Range ton appareil"),
    ("veuillez ranger ton appareil", "range ton appareil"),
    ("Veuillez terminer", "Termine"),
    ("Veuillez signaler", "Signale"),
    ("dites ", "dis "),
    ("Dites ", "Dis "),
    ("Imaginez ", "Imagine "),
    ("Achetez ", "Achète "),
    ("faites-le ", "fais-le "),
    ("Faites-le ", "Fais-le "),
    ("Tu pouvez ", "Tu peux "),
    ("dites-le ", "dis-le "),
    ("Dites-le ", "Dis-le "),
    ("Trouvez ", "Trouve "),
    ("Lâchez ", "Lâche "),
    ("ne gardez ", "ne garde "),
    ("prêtez ", "prête "),
    ("ne portez ", "ne porte "),
    ("Parlez-leur ", "Parle-leur "),
    ("Tu sentez ", "Tu sens "),
    ("tu tu ", "tu "),
    ("ton maison", "ta maison"),
    ("Cette application tu est", "Cette application t'est"),
    ("prévoyez ", "prévois "),
    ("Fixez ", "Fixe "),
    ("achetez ", "achète "),
    ("faites une pause pour toi émerveiller", "fais une pause pour t'émerveiller"),
    ("nous profitons", "tu profites"),
    ("demandez à votre rav", "demande à ton rav"),
    ("Demandez à votre rav", "Demande à ton rav"),
    ("consultez votre rav", "demande à ton rav"),
    ("Consultez votre rav", "Demande à ton rav"),
    ("consultez votre rabbin", "demande à ton rav"),
    ("Consultez votre rabbin", "demande à ton rav"),
    ("observez Chabbat", "observe Chabbat"),
    ("Observez Chabbat", "Observe Chabbat"),
    ("N'utilisez pas", "N'utilise pas"),
    ("n'utilisez pas", "n'utilise pas"),
    ("utilisez ", "utilise "),
    ("Utilisez ", "Utilise "),
    ("Demandez à ton rav", "Demande à ton rav"),
    ("nous prononçons", "tu prononces"),
    ("nous devons", "tu dois"),
    ("nous avons", "tu as"),
    ("nous mangeons", "on mange"),
)

_FR_TU_POST_FIXES: tuple[tuple[str, str], ...] = (
    ("Tu n'avez", "Tu n'as"),
    ("tu n'avez", "tu n'as"),
    ("Tu en avez", "Tu en as"),
    ("tu en avez", "tu en as"),
    ("tu l'avez", "tu l'as"),
    ("Tu l'avez", "Tu l'as"),
    ("Tu êtes-vous", "T'es-tu"),
    ("tu êtes-vous", "t'es-tu"),
    ("tu éloignent", "t'éloignent"),
    ("Ne tu contentez", "Ne te contente"),
    ("ne tu contentez", "ne te contente"),
    ("tu devriez", "tu devrais"),
    ("tu pourriez", "tu pourrais"),
    ("de toi aider", "de t'aider"),
    ("si tu allumez", "si tu allumes"),
    ("tu dois tu ", "tu dois te "),
    ("Tu tu ", "Tu "),
    ("tu soyez", "tu sois"),
    ("tu n'allez", "tu ne vas"),
    ("tu êtes", "tu es"),
    ("tu savez", "tu sais"),
    (" et devez ", " et dois "),
    ("devez peut", "dois peut"),
    ("attendez ", "attends "),
    ("Attendez ", "Attends "),
    ("allaitez", "allaites"),
    ("Les Shekhinah", "La Chekhina"),
    ("Shekhinah—", "Chekhina —"),
    ("Chabbat.Kiddush", "Chabbat. Kidouch"),
    ("Dites-la", "Récite-la"),
    ("dites-la", "récite-la"),
    ("vérifiez ton connexion", "vérifie ta connexion"),
    ("vérifiez ta connexion", "vérifie ta connexion"),
    ("veut tu accorder", "veut t'accorder"),
    ("Entrez dans", "Entre dans"),
    ("faites descendre", "fais descendre"),
    ("Apprenez-en", "Apprends-en"),
)


def apply_fr_tu(text: str) -> str:
    """Convert formal vous/votre to tu/ton; preserve Torah quotes in « »."""
    protected: list[str] = []

    def prot(m: re.Match[str]) -> str:
        protected.append(m.group(0))
        return f"__PROT{len(protected) - 1}__"

    text = re.sub(r"«[^»]*»", prot, text)
    for old, new in _FR_TU_PAIRS:
        text = text.replace(old, new)
    for old, new in _FR_TU_POST_FIXES:
        text = text.replace(old, new)
    for i, chunk in enumerate(protected):
        text = text.replace(f"__PROT{i}__", chunk)
    return text
