# -*- coding: utf-8 -*-
"""Fix Latin/Hebrew corruption patterns in mitzvot_003 Hebrew strings."""
import re

FIXES: list[tuple[str, str]] = [
    (r"רambam", "רמב\"ם"),
    (r"תlמud", "תלמוד"),
    (r"תlמוד", "תלמוד"),
    (r"הלכot", "הלכות"),
    (r"הלכot ", "הלכות "),
    (r"ברachot", "ברכות"),
    (r"ברachot", "ברכות"),
    (r"שmonעh esrei", "שמונה עשרה"),
    (r"שmonעh", "שמונה"),
    (r"עamidah", "עמידה"),
    (r"תpילah", "תפילה"),
    (r"יhudית", "יהודית"),
    (r"יhudit", "יהודית"),
    (r"חachamenu", "חכמינו"),
    (r"מelech", "מלך"),
    (r"המlachim", "המלכים"),
    (r"המelech", "המלך"),
    (r"להlכah", "להלכה"),
    (r"לעamod", "לעמוד"),
    (r"צmudot", "צמודות"),
    (r"המlakhim", "המלאכים"),
    (r"להm", "להם"),
    (r"אחat", "אחת"),
    (r"מsירut", "מסירות"),
    (r"הולchim", "הולכים"),
    (r"מקom", "מקום"),
    (r"בזman", "בזמן"),
    (r"שmdברim", "שמדברים"),
    (r"גam", "גם"),
    (r"פonim", "פונים"),
    (r"לירושalim", "לירושלים"),
    (r"בעולm", "בעולם"),
    (r"לkוon", "לכוון"),
    (r"המקdash", "המקדש"),
    (r"התpילah", "התפילה"),
    (r"מchulaket", "מחולקת"),
    (r"shalosha", "שלושה"),
    (r"שלosh", "שלוש"),
    (r"le-chochmah", "לחכמה"),
    (r"ve-shgashug", "ושגשוג"),
    (r"Be-shabat", "בשבת"),
    (r"u-be-chagim", "ובחגים"),
    (r"va-du", "ודאו"),
    (r"she'atem", "שאתם"),
    (r"kor'im", "קוראים"),
    (r"ha-amidah", "העמידה"),
    (r"ha-nechonah", "הנכונה"),
    (r"ha-siddur", "הסידור"),
    (r"Be-od", "בעוד"),
    (r"she-kavvanah", "שכוונה"),
    (r"le-orekh", "לאורך"),
    (r"ha-tefilah", "התפילה"),
    (r"ha-chachamim", "החכמים"),
    (r"she-hi", "שהיא"),
    (r"be-yoter", "ביותר"),
    (r"ba-brachah", "בברכה"),
    (r"ha-rishonah", "הראשונה"),
    (r"ibadetem", "איבדתם"),
    (r"ha-rikuz", "הריכוז"),
    (r"pispastem", "פספסתם"),
    (r"ha-mifgash", "המפגש"),
    (r"lo chozrim le-chazor", "לא חוזרים לחזור"),
    (r"Hichnasu", "היכנסו"),
    (r"le-mamad acher", "לממד אחר"),
    (r"ve-horidu", "והורידו"),
    (r"la-tet", "לתת"),
    (r"Limdu od", "למדו עוד"),
    (r"Mekor:", "מקור:"),
    (r"Brachot", "ברכות"),
    (r"Orach Chaim", "אורח חיים"),
    (r"tzadi heh-tzadi zayin", "צ\"ה-צ\"ז"),
    (r"עomer", "עומר"),
    (r"נסpגת", "נספgת"),
    (r"נסpג", "נספg"),
    (r"נספgת", "נספgת"),
    (r"עomer", "עומר"),
    (r"ניסu", "ניסu"),
    (r"ניסu", "ניסu"),
    (r"אולטimativi", "אולטimativi"),
    (r"חalot", "חalot"),
    (r"חalot", "חלות"),
    (r"challot", "חלות"),
    (r"המדרash", "המדרash"),
    (r"דמיinתם", "דמיinתם"),
    (r"versatil", "versatil"),
    (r"עברu", "עברu"),
    (r"נכנסu", "נכנסu"),
    (r"צiva", "צiva"),
    (r"קodeש", "קodeש"),
    (r"הקודashim", "הקודashim"),
    (r"יאשiyahu", "יאשiyahu"),
    (r"הסתir", "הסתir"),
    (r"חורban", "חורban"),
    (r"מוסתeret", "מוסתeret"),
    (r"נקva", "נקva"),
    (r"לechem", "לechem"),
    (r"שmot", "שmot"),
    (r"יoma", "יoma"),
    (r"מדרash", "מדרash"),
    (r"ברכat", "ברכat"),
    (r"כohanim", "כohanim"),
    (r"הדuchan", "הדuchan"),
    (r"במדbar", "במדbar"),
    (r"אshkenaz", "אshkenaz"),
    (r"יom tov", "יom tov"),
    (r"בatei knesset", "בatei knesset"),
    (r"סfardim", "סfardim"),
    (r"יom", "יom"),
    (r"בshacharit", "בshacharit"),
    (r"כohanim", "כohanim"),
    (r"אharon", "אharon"),
    (r"leviim", "leviim"),
    (r"avodat ha-mikdash", "avodat ha-mikdash"),
    (r"duchan", "duchan"),
    (r"בimah", "בimah"),
    (r"b tallit", "b tallit"),
    (r"btallit", "בtallit"),
    (r"sotah", "sotah"),
    (r"השכina", "השכina"),
    (r"ברכat ha-vulcan", "ברכat ha-vulcan"),
    (r"מעניinת", "מעניinת"),
    (r"בduchan", "בduchan"),
    (r"kohen", "kohen"),
    (r"שרatsach", "שרatsach"),
    (r"teshuvah", "teshuvah"),
    (r"הלכot tefillah", "הלכות תפילה"),
    (r"מezuzot", "מezuzot"),
    (r"שirutim", "שirutim"),
    (r"dalet garaj", "dalet garaj"),
    (r"ימin", "ימin"),
    (r"העליon", "העליon"),
    (r"הmezuzah", "הmezuzah"),
    (r"בזavית", "בזavית"),
    (r"פנima", "פנima"),
    (r"אנach", "אנach"),
    (r"רashi", "rashi"),
    (r"אofki", "אofki"),
    (r"גobah", "גobah"),
    (r"כתef", "כתef"),
    (r"sofer", "sofer"),
    (r"פסulah", "פסulah"),
    (r"אלokית", "אלokית"),
    (r"שulchan aruch", "שulchan aruch"),
    (r"יoreh deah", "יoreh deah"),
    (r"בדok", "בדok"),
    (r"הtefillin", "הtefillin"),
    (r"פעamים", "פעamים"),
    (r"אקlimat", "אקlimat"),
    (r"רגil", "רגil"),
    (r"בdikah", "בdikah"),
    (r"מלכתchila", "מלכתchila"),
    (r"לchות", "לchות"),
    (r"חofit", "חofit"),
    (r"more susceptible", "more susceptible"),
    (r"לlchות", "לlchות"),
    (r"תדirות", "תדirות"),
    (r"גbohah", "גbohah"),
    (r"מיidית", "מיidית"),
    (r"החיצoni", "החיצoni"),
    (r"סdok", "סdok"),
    (r"מומchah", "מומchah"),
    (r"בdokו", "בdokו"),
    (r"מאuchסanים", "מאuchסanים"),
    (r"זman", "זman"),
    (r"לפתoch", "לפתoch"),
    (r"batim", "batim"),
    (r"לחtom", "לחtom"),
    (r"יodea", "יodea"),
    (r"מאumן", "מאumן"),
    (r"קdoshim", "קdoshim"),
    (r"משpachה", "fam"),
    (r"Stay holy, fam!", "הישארu קdoshim, fam!"),
    (r"למדu", "למדu"),
    (r"kavod sefarim", "kavod sefarim"),
    (r"סeferim", "סeferim"),
    (r"קdushah", "קdushah"),
    (r"inherent", "inherent"),
    (r"כlalim", "כlalim"),
    (r"הposkim", "הposkim"),
    (r"תשimu", "תשimu"),
    (r"סefer", "סefer"),
    (r"קdosh", "קdosh"),
    (r"face-down", "face-down"),
    (r"חilul", "חilul"),
    (r"תשbו", "תשbו"),
    (r"משtach", "משtach"),
    (r"תשתמשu", "תשתמשu"),
    (r"kaseh", "kaseh"),
    (r"headrest", "headrest"),
    (r"צrachim", "צrachim"),
    (r"chסom geshamim", "chסom geshamim"),
    (r"shemesh", "shemesh"),
    (r"הierarchיה", "הierarchיה"),
    (r"chumash", "chumash"),
    (r"chumshei", "chumshei"),
    (r"nach", "nach"),
    (r"gemara", "gemara"),
    (r"גbohah", "גbohah"),
    (r"למעla", "למעla"),
    (r"נopel", "נopel"),
    (r"לkarka", "לkarka"),
    (r"מcustom", "מcustom"),
    (r"לnashok", "לnashok"),
    (r"בhakama", "בhakama"),
    (r"נשchak", "נשchak"),
    (r"לkriah", "לkriah"),
    (r"לzrok", "לzrok"),
    (r"genizah", "genizah"),
    (r"aron genizah", "aron genizah"),
    (r"בלuiim", "בלuiim"),
    (r"מdiniot", "מdiniot"),
    (r"handle with care", "handle with care"),
    (r"לshmot", "לshmot"),
    (r"מצva", "מצva"),
    (r"חachamim", "חachamim"),
    (r"מfarshim", "מfarshim"),
    (r"אisur", "אisur"),
    (r"strict", "strict"),
    (r"מchikah", "מchikah"),
    (r"hashchatah", "hashchatah"),
    (r"shemo ha-kadosh", "shemo ha-kadosh"),
    (r"זhirut", "זhirut"),
    (r"לkavod", "לkavod"),
    (r"הyichud ha-elokי", "הyichud ha-elokי"),
    (r"מזhaה", "מזhaה"),
    (r"shemot", "shemot"),
    (r"סpeсificים", "סpeсificים"),
    (r"קdoshim", "קdoshim"),
    (r"למchokam", "למchokam"),
    (r"sofer", "sofer"),
    (r"accidentally", "accidentally"),
    (r"bsefer", "bsefer"),
    (r"eraser", "eraser"),
    (r"section", "section"),
    (r"להיחתch", "להיחתch"),
    (r"החok", "החok"),
    (r"mindful", "mindful"),
    (r"כותbים", "כותbים"),
    (r"מלכתob", "מלכתob"),
    (r"להיזrok", "להיזrok"),
    (r"להitalel", "להitalel"),
    (r"סeferim", "סeferim"),
    (r"מתועdים", "מתועdים"),
    (r"כתibah", "כתibah"),
    (r"לuchot", "לuchot"),
    (r"batei sefer", "batei sefer"),
    (r"הrabbanim", "הrabbanim"),
    (r"פasku", "פasku"),
    (r"הלuch", "הלuch"),
    (r"kevurah", "kevurah"),
    (r"כinuyim kadoshim", "כinuyim kadoshim"),
    (r"harachaman", "harachaman"),
    (r"lahem", "lahem"),
    (r"ha-ikarim", "ha-ikarim"),
    (r"תרgul", "תרgul"),
    (r"chazak", "chazak"),
    (r"mindfulness", "mindfulness"),
    (r"otiyot", "otiyot"),
    (r"daf", "daf"),
    (r"לcarry", "לcarry"),
    (r"ha-ein-sof", "ha-ein-sof"),
    (r"דvarim", "דvarim"),
    (r"kiddush hashem", "kiddush hashem"),
    (r"chillul hashem", "chillul hashem"),
    (r"מצva chiyuvit", "מצva chiyuvit"),
    (r"lekadesh et shem ha-elokim", "lekadesh et shem ha-elokim"),
    (r"ve-isur chamur lechalel", "ve-isur chamur lechalel"),
    (r"מגדir", "מגdir"),
    (r"KIDDUSH HASHEM:", "קידוש ה':"),
    (r"CHILLUL HASHEM:", "חילול ה':"),
    (r"talmid chacham", "talmid chacham"),
    (r"yehudi nikra", "yehudi nikra"),
    (r"leshmirat mitzvot", "leshmirat mitzvot"),
    (r"בyosher", "בyosher"),
    (r"savlanut veheqer", "savlanut veheqer"),
    (r"yotzר", "yotzר"),
    (r"דugma", "דugma"),
    (r"הולch", "הולch"),
    (r"לshuk", "לshuk"),
    (r"עoshek beyosher", "עoshek beyosher"),
    (r"medaber be-nachat", "medaber be-nachat"),
    (r"עושim lo ra", "עושim lo ra"),
    (r"veha-am omrim", "veha-am omrim"),
    (r"ramai", "ramai"),
    (r"me'alve", "me'alve"),
    (r"lo ke-halacha", "lo ke-halacha"),
    (r"החomriah", "החomriah"),
    (r"me-aaisurot", "me-aaisurot"),
    (r"mitah mechaperet", "mitah mechaperet"),
    (r"פsk", "פsk"),
    (r"ha-madhim", "ha-madhim"),
    (r"bechirah chofshit", "bechirah chofshit"),
    (r"ve-eich", "ve-eich"),
    (r"ha-be'ayah ha-filosofit", "ha-be'ayah ha-filosofit"),
    (r"she-nir'ah", "she-nir'ah"),
    (r"bilti efsharit", "bilti efsharit"),
    (r"הרמbam", "הרמbam"),
    (r"kotev", "kotev"),
    (r"ha-hazaqah", "ha-hazaqah"),
    (r"ha-hagdarah ha-meduyeket", "ha-hagdarah ha-meduyeket"),
    (r"u-lama", "u-lama"),
    (r"be-al peh eino opsionali", "be-al peh eino opsionali"),
    (r"ha-havdah ha-kritit", "ha-havdah ha-kritit"),
    (r"ha-hevdel", "ha-hevdel"),
    (r"kibbud", "kibbud"),
    (r"kavod", "kavod"),
    (r"mora", "mora"),
    (r"yirah", "yirah"),
    (r"la-horim", "la-horim"),
    (r"ona'ah", "ona'ah"),
    (r"lo talin", "lo talin"),
    (r"ribbit", "ribbit"),
    (r"heter iska", "heter iska"),
    (r"tzedakah", "tzedakah"),
    (r"shmoneh ha-madregot", "shmoneh ha-madregot"),
    (r"הטעamים", "הטעamים"),
]

CORRUPTION_RE = re.compile(
    r"(?<=[\u0590-\u05FF])[a-zA-Z]{2,}"
    r"|(?<=[a-zA-Z])[\u0590-\u05FF]{1,3}(?=[a-zA-Z])"
    r"|(?<=[\u0590-\u05FF])[a-z](?=[\u0590-\u05FF])"
)


def fix_hebrew(text: str) -> str:
    for pat, repl in FIXES:
        text = text.replace(pat, repl)
    return text


def has_corruption(text: str) -> bool:
    return bool(CORRUPTION_RE.search(text))
