# Native Hebrew glossary definitions — keys from _he_glossary_missing.json
HE_DEFINITIONS: dict[str, str] = {
    "Bal yimatzei forbids chametz being found in your possession on Pesach. Spiritual nullification (Kol Chamira) complements but does not replace cleaning. Chametz you owned over Pesach without sale may be forbidden to benefit from after Pesach — serious questions go to your rav.": (
        "בל ימצא אוסר שחמץ יימצא ברשותך בפסח. ביטול חמץ (כל חמירא) משלים אך לא מחליף ניקוי. חמץ שהיה ברשותך בפסח ללא מכירה עשוי להיות אסור בהנאה אחרי הפסח — שאלו רב."
    ),
    "Bar mitzvah is when a boy turns thirteen and becomes obligated in mitzvot — tefillin, fasting, counting the Omer, and the full moral law. The celebration is seudat mitzvah joy, but the essence is responsibility. Parents' chinuch before thirteen prepares him. Aliyah to the Torah often marks the day in shul.": (
        "בר מצווה — כשבן מגיע לגיל שלוש עשרה ונעשה חייב במצוות: תפילין, צום, ספירת העומר וכל תורת המוסר. החגיגה היא שמחת סעודת מצווה, אך המהות היא אחריות. חינוך ההורים לפני גיל שלוש עשרה מכין אותו. עלייה לתורה מסמנת לעיתים את היום בבית הכנסת."
    ),
    "Bedieved describes halachic guidance after the ideal was missed — unintentionally or unavoidably. It is not permission to plan poorly; it is how to recover. Example categories: Amidah repeats, chametz found on Pesach, missed Omer count. Your rav applies bedieved rules to your case; articles in the app summarize common patterns from standard halachic sources.": (
        "בדיעבד מתאר הלכה לאחר שהאידיאל הוחמץ — בלא כוונה או מכוח נסיבות. זו לא רשות לתכנן רשלנות, אלא איך להשתקם. דוגמאות: חזרה על עמידה, חמץ שנמצא בפסח, פספוס בספירת העומר. הרב שלכם יחיל בדיעבד על המקרה שלכם."
    ),
    "Birchot HaShachar are morning blessings thanking G-d for eyesight, clothing, strength, and being created — said at shul or home. They orient the day toward gratitude before requests. Women and men both say them; some women omit certain blessings per custom. They parallel waking gifts we overlook.": (
        "ברכות השחר — ברכות בוקר המודות לה' על ראייה, לבוש, כוח ובריאה — בבית כנסת או בבית. הן מכוונות את היום להכרת תודה לפני בקשות. נשים וגברים אומרים; יש נשים שמדלגות על ברכות מסוימות לפי מנהג."
    ),
    "Birchot HaShachar — Birchot HaShachar are morning blessings thanking G-d for eyesight, clothing, strength, and being created — said at shul or home. They orient the day toward gratitude before requests. Women and men both say them; some women omit certain blessings per custom. They parallel waking gifts we overlook.": (
        "ברכות השחר — ברכות בוקר המודות לה' על ראייה, לבוש, כוח ובריאה — בבית כנסת או בבית. הן מכוונות את היום להכרת תודה לפני בקשות."
    ),
    "Challah is the bread often prepared for Shabbat and festival meals — often braided and covered until Kiddush. Two loaves (lechem mishneh) recall the double portion in the desert. On Friday night, if wine or grape juice is completely unavailable, Kiddush can be recited over the challah loaves, provided one washes hands for bread immediately before reciting Kiddush and replaces the wine blessing with Hamotzi. Bread can never substitute for daytime Shabbat Kiddush on Saturday morning.": (
        "חלה — לחם לשבת ולחגים, לעיתים קלועה ומכוסה עד הקידוש. שני כיכרות (לחם משנה) מזכירים את המן הכפול במדבר. בליל שישי, אם אין יין כלל, יש מנהגים לקדש על החלה בתנאים מסוימים — שאלו רב. לחם אינו תחליף לקידוש שבת ביום."
    ),
    "Charoset is the sweet paste (apples, wine, nuts, etc.) recalling mortar between bricks. It is dipped with maror for Korech. Recipes vary by family — Ashkenazi, Sephardi, and Persian charoset all fulfill the mitzvah when made with intent. It is one of the Seder plate's sensory contrasts: bitter and sweet together.": (
        "חרוסת — מריחה מתוקה (תפוחים, יין, אגוזים וכו') המזכירה טיט בין לבנים. טובלים בה עם מרור לקורח. המתכונים משתנים לפי משפחה — אשכנז, ספרד ופרסי — כולם מקיימים את המצווה בכוונה."
    ),
    "Chilul Hashem is desecrating G-d's Name — behavior that makes Torah or Jews look contemptible, especially in public. Fraud, rage, or hypocrisy by a visibly Jewish person harms the whole people. The opposite is kiddush Hashem — sanctifying G-d's Name through integrity. Non-Jews judging Judaism by your conduct is a serious responsibility.": (
        "חילול השם — מחולל את שם ה' — התנהגות שגורמת לתורה או ליהודים להיראות בזויים, במיוחד בציבור. רמאות, כעס או צביעות של יהודי ניכר פוגעים בכל העם. ההפך הוא קידוש השם."
    ),
    "Chilul Hashem — Chilul Hashem is desecrating G-d's Name — behavior that makes Torah or Jews look contemptible, especially in public. Fraud, rage, or hypocrisy by a visibly Jewish person harms the whole people. The opposite is kiddush Hashem — sanctifying G-d's Name through integrity. Non-Jews judging Judaism by your conduct is a serious responsibility.": (
        "חילול השם — מחולל את שם ה' — התנהגות שגורמת לתורה או ליהודים להיראות בזויים. ההפך הוא קידוש השם."
    ),
    "Chol HaMoed (חול המועד) — the intermediate festival days — is not full Yom Tov, but it is not ordinary weekdays either.\n$hoshanaRabaBlock\n\nSpirit of the day:\n• Simchat moed — joy of the festival; nicer meals, family time, Torah learning.\n• Melacha — many labors are restricted (not as strict as Yom Tov). Work needed to avoid financial loss may be permitted — ask your rabbi before assuming.\n• Ochel nefesh — food preparation is permitted.\n\nWhat to do:\n$hallelBlock\n• Avoid treating it like a regular workday — schedule outings, learning, and visits that fit the moed.\n$festivalLines\n\nAvoid (without halachic guidance): heavy laundry, major home projects, shaving, haircuts, and activities that diminish the festival atmosphere.\n• Grooming restrictions: Shaving and getting a haircut are strictly prohibited on Chol HaMoed (Shulchan Arukh O.C. 531) — unless under highly specific conditions, such as a boy turning three or leaving prison (ask your rav). This applies even if you want to look clean for the remaining days of the festival.": (
        "חול המועד — ימי החג שאינם יום טוב מלא, אך גם לא חול רגיל.\n$hoshanaRabaBlock\n\nרוח היום:\n• שמחת המועד — ארוחות נעימות, זמן משפחה ולימוד תורה.\n• מלאכה — מוגבלת; עבודה למניעת הפסד כספי עשויה להיות מותרת — שאלו רב.\n• אוכל נפש — מותר.\n\nמה לעשות:\n$hallelBlock\n• אל תתייחסו ליום כחול רגיל — תכננו טיולים, לימוד וביקורים.\n$festivalLines\n\nלהימנע (ללא הכוונה הלכתית): כביסה כבדה, שיפוצים, גילוח ותספורת (שו\"ע או\"ח תקל\"א) — אלא בחריגים נדירים; שאלו רב."
    ),
    "Chol HaMoed are the intermediate days sandwiched between the first and last days of Pesach or Sukkot. They are still festival time, but melacha rules are lighter than on Yom Tov or Shabbat: many forms of work and food preparation are permitted, with limits on certain commercial activity and some melachot. Shaving and haircuts are strictly prohibited (O.C. 531) unless under specific exceptions — ask your rav.": (
        "חול המועד — הימים שבין ראשון ואחרון של פסח או סוכות. עדיין זמן חג, אך דיני מלאכה קלים יותר מיום טוב או שבת. גילוח ותספורת אסורים (או\"ח תקל\"א) אלא בחריגים — שאלו רב."
    ),
    "Chol HaMoed — Chol HaMoed are the intermediate days sandwiched between the first and last days of Pesach or Sukkot. They are still festival time, but melacha rules are lighter than on Yom Tov or Shabbat: many forms of work and food preparation are permitted, with limits on certain commercial activity and some melachot. Shaving and haircuts are strictly prohibited (O.C. 531) unless under specific exceptions — ask your rav.": (
        "חול המועד — ימי ביניים בין ראשון ואחרון של פסח או סוכות; דיני מלאכה קלים יותר. גילוח ותספורת אסורים (או\"ח תקל\"א) אלא בחריגים."
    ),
    "Eruv tavshilin is a symbolic meal set aside on Erev Yom Tov when Shabbat follows immediately afterward. You take a baked food (challah or matzah) and a cooked food (often meat, fish, or an unpeeled hard-boiled egg), recite the blessing and declaration from your siddur or machzor in a language you understand, and thereby may continue food preparation on Yom Tov for Shabbat — which would otherwise be forbidden because you may not cook on one holy day for the next. Store the designated foods in a safe, labeled spot — if they are eaten before you finish Friday cooking for Shabbat, the eruv is void. It also reminds the home to prepare for Shabbat, not only for the festival.": (
        "עירוב תבשילין — ארוחה סמלית בערב יום טוב כששבת עוקבת מיד. לוקחים מאפה ומאכל מבושל, מברכים ומצהירים, וכך מותר להמשיך הכנת אוכל ביום טוב לשבת. שמרו את המאכלים במקום מסומן — אם נאכלו לפני סיום הבישול לשבת, העירוב בטל."
    ),
    "Eruv tavshilin — Eruv tavshilin is a symbolic meal set aside on Erev Yom Tov when Shabbat follows immediately afterward. You take a baked food (challah or matzah) and a cooked food (often meat, fish, or an unpeeled hard-boiled egg), recite the blessing and declaration from your siddur or machzor in a language you understand, and thereby may continue food preparation on Yom Tov for Shabbat — which would otherwise be forbidden because you may not cook on one holy day for the next. Store the designated foods in a safe, labeled spot — if they are eaten before you finish Friday cooking for Shabbat, the eruv is void. It also reminds the home to prepare for Shabbat, not only for the festival.": (
        "עירוב תבשילין — מאפה ומאכל מבושל בערב יום טוב לשבת עוקבת; מאפשר בישול ביום טוב לשבת."
    ),
    "Haman — Haman is the Persian official who plotted to destroy the Jews in Esther's time. Mordechai and Esther foiled the plan. When the Megillah reader says Haman's name, many boo, rattle graggers, or stamp — erasing his name symbolically. The mitzvah is hearing the text, not drowning out so much that words are missed.": (
        "המן — פקיד פרסי שתכנן להשמיד את היהודים בימי אסתר. מרדכי ואסתר ביטלו את התוכנית. כשקוראים את שמו במגילה, רבים משמיעים רעש — אך המצווה היא לשמוע את הטקסט."
    ),
    "Hoshana Raba is the seventh day of Sukkot — the climax of Hoshanot with extra circuits around the bimah. The beating of aravot (willow branches) against the ground is classified as a Minhag Nevi'im — an ancient custom instituted by the final Prophets (Haggai, Zechariah, and Malachi). Because of its prophetic roots, it follows strict parameters that ordinary customs do not — notably striking the branches against the ground exactly five times to sweeten the divine judgments. See also Hoshanot.": (
        "הושענא רבה — יום שביעי של סוכות, שיא ההושענות עם הקפות נוספות. הכאת ערבות בקרקע הוא מנהג נביאים — חמש פעמים בדיוק. ראו גם הושענות."
    ),
    "Hoshana Raba — Hoshana Raba is the seventh day of Sukkot — the climax of Hoshanot with extra circuits around the bimah. The beating of aravot (willow branches) against the ground is classified as a Minhag Nevi'im — an ancient custom instituted by the final Prophets (Haggai, Zechariah, and Malachi). Because of its prophetic roots, it follows strict parameters that ordinary customs do not — notably striking the branches against the ground exactly five times to sweeten the divine judgments. See also Hoshanot.": (
        "הושענא רבה — יום שביעי של סוכות, שיא ההושענות; הכאת ערבות חמש פעמים."
    ),
    "Karpas is a vegetable (often parsley or potato) dipped in salt water at the Seder start — awakening curiosity before the meal. The salt water recalls tears of slavery. It is not the main maror mitzvah; it opens the night with a question. Prepare enough for every guest.": (
        "כרפס — ירק (לרוב פטרוזיליה או תפוח אדמה) שטובלים במי מלח בתחילת הסדר — מעורר סקרנות. מי המלח מזכירים דמעות השעבוד."
    ),
    "Kashering — Kashering makes utensils fit for kosher or Pesach use. The core principle is kebolo kach polto — as a vessel absorbed forbidden taste, so it expels it. Items used in boiling water often need hag'alah (immersion in rolling boiling water); items used directly on fire may need libun (intense heat until they turn red hot). Plastic and glass have highly conflicting rulings between Ashkenazim and Sephardim — and it's less lenient on Pesach. Ask your rav. Ceramic cannot be kashered. Many families keep a separate Pesach set.": (
        "הגעלה — הכשרת כלים לכשרות או לפסח. העיקרון: כבלוע כך פולט. כלים מרתיחה — הגעלה; על האש — ליבון. פלסטיק וזכוכית — מחלוקת אשכנזים וספרדים; קרמיקה אינה ניתנת להכשרה. שאלו רב."
    ),
    "Kashrut is the Torah system of permitted food, shechita, separating meat and dairy, and supervising production. It sanctifies eating — turning meals into service of G-d. Learning labels (OU, OK, etc.), hechsherim, and kitchen setup takes time; ask your rav when starting.": (
        "כשרות — מערכת התורה של מזון מותר, שחיטה, הפרדת בשר וחלב ופיקוח ייצור. מקדשת את האכילה — הופכת ארוחות לעבודת ה'. לימוד תוויות, הכשרים והקמת מטבח לוקח זמן; שאלו רב."
    ),
    "Kashrut is the system of Jewish dietary laws that governs what we eat, how food is prepared, and how meat and dairy are kept separate.\n\nWhat kosher means:\nKosher (כָּשֵׁר) literally means \"fit\" or \"proper.\" Food that meets all the Torah's dietary requirements is called kosher. Food that does not is called treif (טְרֵיף — literally \"torn,\" referring to torn-apart animals).\n\nThe main rules:\n\nPermitted and forbidden animals:\n• Land animals must have split hooves AND chew their cud: beef, lamb, and goat are kosher; pork is not\n• Fish must have fins AND scales: salmon, tuna, and carp are kosher; shrimp, lobster, and catfish are not\n• Chicken, turkey, duck, and other domestic fowl are kosher\n\nShechita (kosher slaughter):\n• All meat must be slaughtered by a shochet — a specially trained and G-d-fearing slaughterer — using a swift, painless cut. This is called shechita (שְׁחִיטָה)\n• After slaughter, the meat is salted to remove blood (melicha), since consuming blood is forbidden\n\nSeparating meat and dairy (basar b'chalav):\n• Meat and dairy may never be eaten together, cooked together, or served on the same dishes\n• After eating meat, you wait a period of time before dairy. Six hours is standard in many communities, but customs vary (some wait one or three hours) — follow your rabbi and community\n• Separate sets of dishes, pots, and utensils are kept for meat and dairy\n\nHechsher:\n• A hechsher (הֶכְשֵׁר) is a certification mark on packaged foods indicating rabbinical supervision. Look for a recognized symbol on labels.\n\nWhy these laws:\nThe Torah gives these laws as divine commands. Beyond the reason, observing them elevates every meal into an act of service to G-d and builds discipline and consciousness in our daily lives.\n\nGetting started:\nConsult your local Orthodox rabbi before setting up a kosher kitchen. Many people begin by removing non-kosher meat and seafood, then work toward full observance.": (
        "כשרות — מערכת דיני המזון ביהדות: מה מותר לאכול, איך מכינים, ואיך מפרידים בשר וחלב.\n\nכשר (כָּשֵׁר) פירושו «ראוי». טרף — אסור.\n\nחיות מותרות ואסורות:\n• בעלי מפרסים ומעלה גרה — מותרים; חזיר — לא.\n• דגים עם סנפירים וקשקשים — מותרים.\n• עוף ביתי — מותר.\n\nשחיטה:\n• בשר רק בשחיטת שוחט מיומן; מליחה להוצאת דם.\n\nבשר בחלב:\n• לא יחד; המתנה בין בשר לחלב לפי מנהג; כלים נפרדים.\n\nהכשר — סימון פיקוח רבני על מוצרים.\n\nהתחילו עם רב מקומי לפני הקמת מטבח כשר."
    ),
    "Kashrut — Kashrut is the Torah system of permitted food, shechita, separating meat and dairy, and supervising production. It sanctifies eating — turning meals into service of G-d. Learning labels (OU, OK, etc.), hechsherim, and kitchen setup takes time; ask your rav when starting.": (
        "כשרות — מערכת התורה של מזון מותר, שחיטה, הפרדת בשר וחלב ופיקוח ייצור."
    ),
    "Kiddush Hashem means sanctifying G-d's Name — living and speaking in a way that makes observers respect Torah and G-d. Examples include returning lost objects, honest dealings, and gracious behavior in public as a visibly Jewish person. Its opposite, chilul Hashem, is among the most serious sins because it pushes people away from holiness.": (
        "קידוש השם — לחלל את שם ה' בחיים ובדיבור כך שמכבדים את התורה וה'. ההפך, חילול השם, מחליף אנשים מקדושה."
    ),
    "Kiddush Hashem — Kiddush Hashem means sanctifying G-d's Name — living and speaking in a way that makes observers respect Torah and G-d. Examples include returning lost objects, honest dealings, and gracious behavior in public as a visibly Jewish person. Its opposite, chilul Hashem, is among the most serious sins because it pushes people away from holiness.": (
        "קידוש השם — לקדש את שם ה' בהתנהגות ישרה ומכבדת בציבור."
    ),
    "Kiddush Levana (קִידּוּשׁ לְבָנָה — Sanctification of the Moon) is a monthly blessing said once each Hebrew month when the new moon is visible at night. It is not worship of the moon — it praises G-d for creation's cycles and Israel's renewal. The Talmud (Sanhedrin 42a) compares one who blesses the moon properly to greeting the Shechinah. Men are obligated in this time-bound positive mitzvah; women are exempt (like most time-bound mitzvot) and the widespread longstanding custom is that women do not recite Kiddush Levana at all — prominent authorities (Shelah, Magen Avraham O.C. 426:1) advise against it for kabbalistic reasons as well. Say it outdoors under the open sky when possible, standing, after nightfall. Ashkenazim and Chabad often wait at least three days after the new moon; most Sephardim wait seven (Shulchan Arukh O.C. 426:4); Moroccan and some North African kehillot may begin after three days (Peninei Halakha 05-01-18). Motzei Shabbat is a widespread preference when people are dressed up and the moon is visible — but if waiting risks a string of cloudy nights and missing the monthly window, say it on the first clear weeknight the mitzvah becomes possible. The window ends at the moment of the full moon (roughly 14.75 days into the month) — saying it on the night of the 15th may already be too late; check Sof Zman Kiddush Levana for your location. Also called Birkat HaLevanah.": (
        "קידוש לבנה — ברכה חודשית כשהירח החדש נראה בלילה; לא עבודה לירח אלא שבח לבורא. גברים חייבים; נשים פטורות ורב המנהג שלא לומר. בחוץ, עומדים, אחרי צאת הכוכבים. חלון עד מילוא הלבנה — בדקו סוף זמן קידוש לבנה."
    ),
    "Kiddush Levana — Kiddush Levana (קִידּוּשׁ לְבָנָה — Sanctification of the Moon) is a monthly blessing said once each Hebrew month when the new moon is visible at night. It is not worship of the moon — it praises G-d for creation's cycles and Israel's renewal. The Talmud (Sanhedrin 42a) compares one who blesses the moon properly to greeting the Shechinah. Men are obligated in this time-bound positive mitzvah; women are exempt (like most time-bound mitzvot) and the widespread longstanding custom is that women do not recite Kiddush Levana at all — prominent authorities (Shelah, Magen Avraham O.C. 426:1) advise against it for kabbalistic reasons as well. Say it outdoors under the open sky when possible, standing, after nightfall. Ashkenazim and Chabad often wait at least three days after the new moon; most Sephardim wait seven (Shulchan Arukh O.C. 426:4); Moroccan and some North African kehillot may begin after three days (Peninei Halakha 05-01-18). Motzei Shabbat is a widespread preference when people are dressed up and the moon is visible — but if waiting risks a string of cloudy nights and missing the monthly window, say it on the first clear weeknight the mitzvah becomes possible. The window ends at the moment of the full moon (roughly 14.75 days into the month) — saying it on the night of the 15th may already be too late; check Sof Zman Kiddush Levana for your location. Also called Birkat HaLevanah.": (
        "קידוש לבנה — ברכה חודשית על הירח החדש; גברים חייבים, נשים פטורות לפי מנהג."
    ),
    "Kol Chamira is an Aramaic declaration nullifying chametz still in your possession. The night version (after bedikat chametz) nullifies only chametz you have not seen and do not know about — you may still legally own chametz for breakfast. The morning version (after biur on Erev Pesach) is structurally different and nullifies ALL chametz, whether seen or unseen, destroyed or not.": (
        "כל חמירא — הצהרה ארמית לביטול חמץ. בלילה — רק חמץ שלא נראה; בבוקר ערב פסח — ביטול כל החמץ."
    ),
    "Kol Chamira — Kol Chamira is an Aramaic declaration nullifying chametz still in your possession. The night version (after bedikat chametz) nullifies only chametz you have not seen and do not know about — you may still legally own chametz for breakfast. The morning version (after biur on Erev Pesach) is structurally different and nullifies ALL chametz, whether seen or unseen, destroyed or not.": (
        "כל חמירא — ביטול חמץ; גרסת לילה לעומת גרסת בוקר ערב פסח שונה."
    ),
    "Kol Nidrei opens Yom Kippur eve — annulling vows so the day can proceed with a clean slate regarding promises to G-d. The haunting melody is famous, but the legal text is serious. It does not cancel interpersonal debts or promises to others — only certain vows to G-d per specific formulas. Arrive early; the shul fills quickly.": (
        "כל נדרי — פותח ערב יום כיפור; מבטל נדרים לקראת היום. לא מבטל חובות לאדם — רק נדרים לה' לפי נוסח. הגיעו מוקדם."
    ),
    "Kol Nidrei — Kol Nidrei opens Yom Kippur eve — annulling vows so the day can proceed with a clean slate regarding promises to G-d. The haunting melody is famous, but the legal text is serious. It does not cancel interpersonal debts or promises to others — only certain vows to G-d per specific formulas. Arrive early; the shul fills quickly.": (
        "כל נדרי — פותח ערב יום כיפור; מבטל נדרים לה' בלבד."
    ),
    "Koteiv is writing two meaningful letters on Shabbat. Typing, texting, and permanent markers violate this rabbinically and often biblically. Avoid Scrabble with locking tiles, signing checks, and filling forms. Children should have Shabbat-appropriate activities prepared.": (
        "כותב — כתיבת שתי אותיות משמעותיות בשבת. הקלדה, SMS וטוש קבוע אסורים. הכינו פעילויות שבת לילדים."
    ),
    "Koteiv — Koteiv is writing two meaningful letters on Shabbat. Typing, texting, and permanent markers violate this rabbinically and often biblically. Avoid Scrabble with locking tiles, signing checks, and filling forms. Children should have Shabbat-appropriate activities prepared.": (
        "כותב — כתיבה בשבת אסורה; הימנעו ממשחקים וטפסים."
    ),
    "Machatzit HaShekel recalls the half-shekel each Jew gave for Temple upkeep in Adar. Today many give charity before Purim — often three coins half of a local unit. It is a widespread custom, not one of the four Purim mitzvot, but it connects the community to unified redemption. Give through your shul or reputable charity.": (
        "מחצית השקל — מזכיר את מחצית השקל לאחזקת המקדש באדר. היום נותנים צדקה לפני פורים — מנהג נרחב."
    ),
    "Mah Nishtanah (\"Why is this night different?\") is the Four Questions — usually asked by the youngest child at the Seder. The Haggadah answers each question with Torah, story, and mitzvot. The point is engagement: children (and adults) should feel the Exodus personally, not only hear a lecture.": (
        "מה נשתנה — ארבע השאלות; לרוב הילד הקטן שואל. המטרה: לחוות את יציאת מצרים אישית."
    ),
    "Mah Nishtanah — Mah Nishtanah (\"Why is this night different?\") is the Four Questions — usually asked by the youngest child at the Seder. The Haggadah answers each question with Torah, story, and mitzvot. The point is engagement: children (and adults) should feel the Exodus personally, not only hear a lecture.": (
        "מה נשתנה — ארבע השאלות בהגדה; מעורבות הילדים במרכז."
    ),
    "Motzei Shabbat — Motzei Shabbat is Saturday night after Shabbat ends.": (
        "מוצאי שבת — ליל שבת אחרי יציאת השבת."
    ),
    "Muktzeh means \"set aside\" — objects not used on Shabbat because they are not needed for Shabbat itself (tools, money, phones). The categories are detailed: some items may not be moved at all; others may be moved for a Shabbat need or to use the place they occupy. Learning basic muktzeh prevents accidental violations when tidying or handling objects on Shabbat.": (
        "מוקצה — חפצים שלא משתמשים בהם בשבת (כלים, כסף, טלפונים). קטגוריות מפורטות — למדו את הבסיס."
    ),
    "Muktzeh — Muktzeh means \"set aside\" — objects not used on Shabbat because they are not needed for Shabbat itself (tools, money, phones). The categories are detailed: some items may not be moved at all; others may be moved for a Shabbat need or to use the place they occupy. Learning basic muktzeh prevents accidental violations when tidying or handling objects on Shabbat.": (
        "מוקצה — חפצים שלא נוגעים בהם בשבת מחמת שאינם לצורך שבת."
    ),
    "Musaf is the \"additional\" Amidah remembering the extra Temple offerings (musaf offerings) brought on Shabbat, Rosh Chodesh, and Yom Tov. Its central blessing describes what was offered and prays for the Temple's restoration. Without the Temple, prayer replaces sacrifice — Musaf is how we still connect to that service.": (
        "מוסף — עמידה נוספת לזכר קרבנות המוסף בשבת, ראש חודש ויום טוב. התפילה מחליפה את הקרבן."
    ),
    "Musaf — Musaf is the \"additional\" Amidah remembering the extra Temple offerings (musaf offerings) brought on Shabbat, Rosh Chodesh, and Yom Tov. Its central blessing describes what was offered and prays for the Temple's restoration. Without the Temple, prayer replaces sacrifice — Musaf is how we still connect to that service.": (
        "מוסף — עמידה לזכר קרבנות המקדש."
    ),
    "Ne'ilah (\"closing\") is the final prayer service of Yom Kippur as the gates of repentance close. The ark often stays open; the congregation pleads intensely. Many have the custom to say Shema Yisrael together at the end. After Ne'ilah and nightfall (tzeit), one prays Maariv, makes Havdalah, and breaks the fast. It is the spiritual peak of the Ten Days of Teshuvah.": (
        "נעילה — תפילת הסגירה ביום כיפור כששערי תשובה נסגרים. אחריה מעריב, הבדלה ואכילה."
    ),
    "Ne'ilah — Ne'ilah (\"closing\") is the final prayer service of Yom Kippur as the gates of repentance close. The ark often stays open; the congregation pleads intensely. Many have the custom to say Shema Yisrael together at the end. After Ne'ilah and nightfall (tzeit), one prays Maariv, makes Havdalah, and breaks the fast. It is the spiritual peak of the Ten Days of Teshuvah.": (
        "נעילה — שיא עשרת ימי תשובה; אחריה מעריב והבדלה."
    ),
    "Nerot — candles, often referring especially to Shabbat and Yom Tov lights": (
        "נרות — נרות, לעיתים קרובות נרות שבת ויום טוב"
    ),
    "Neshama yeteira (\"extra soul\") is the tradition that Shabbat brings an added measure of spiritual capacity — more patience, joy, and ability to connect to Torah. It departs at Havdalah, which is why some feel a post-Shabbat dip. Honoring Shabbat meals, rest, and learning helps this soul express itself; rushing and stress diminish it.": (
        "נשמה יתירה — מסורת שנשמה נוספת מלווה את השבת; עוזבת בהבדלה."
    ),
    "Ona'at devarim is verbal wronging — insults, public embarrassment, or pressuring someone to sell. Even \"friendly\" teasing can be forbidden if it hurts. The Talmud lists it among sins that may not be forgiven until the victim is appeased. Guarding speech includes not only lashon hara but ona'at devarim.": (
        "אונאת דברים — פגיעה במילים: עלבונות, השפלה או לחץ למכור. גם «צחוק» יכול להיות אסור אם כואב."
    ),
    "Oneg Shabbat is delighting in Shabbat — good food, rest, Torah study, singing, and time with family or guests. It is a positive mitzvah, not only avoiding melacha. The Talmud criticizes those who fast or deprive themselves on Shabbat without need. Planning meals and atmosphere before Shabbat helps oneg happen without last-minute stress.": (
        "עונג שבת — הנאה בשבת: אוכל טוב, מנוחה, לימוד, שירה ומשפחה. מצווה חיובית."
    ),
    "Oneg Shabbat — Oneg Shabbat is delighting in Shabbat — good food, rest, Torah study, singing, and time with family or guests. It is a positive mitzvah, not only avoiding melacha. The Talmud criticizes those who fast or deprive themselves on Shabbat without need. Planning meals and atmosphere before Shabbat helps oneg happen without last-minute stress.": (
        "עונג שבת — לשמוח בשבת; תכננו מראש."
    ),
    "Patur means exempt from a particular mitzvah in a given situation — for example, someone ill on Yom Kippur from fasting, or a child before bar mitzvah. Patur is not \"off the hook\" morally; it means the obligation does not apply to you now. A different mitzvah or leniency may apply instead.": (
        "פטור — פטור ממצווה מסוימת במצב נתון; לא «פטור מכל» מוסרית."
    ),
    "Pikuach nefesh (saving life) overrides Shabbat and almost all mitzvot. Call emergency services, drive to hospital, and carry medicine when life is at risk. Doctors and nurses have detailed halacha for their shifts — but a layperson should never hesitate to save life. After the danger passes, ask your rav about what you did.": (
        "פיקוח נפש — הצלת חיים דוחה שבת וכמעט כל מצווה. אל תהססו לקרוא לחירום."
    ),
    "Pikuach nefesh — Pikuach nefesh (saving life) overrides Shabbat and almost all mitzvot. Call emergency services, drive to hospital, and carry medicine when life is at risk. Doctors and nurses have detailed halacha for their shifts — but a layperson should never hesitate to save life. After the danger passes, ask your rav about what you did.": (
        "פיקוח נפש — הצלת חיים דוחה שבת."
    ),
    "Pirkei Avot (Ethics of the Fathers) is a tractate of the Mishnah with wisdom sayings about character, community, and love of Torah — often studied on Shabbat afternoon between Pesach and Shavuot. It is not a law manual but a moral compass. Familiar lines include \"The world stands on Torah, service, and acts of kindness.\"": (
        "פרקי אבות — מסכת משנה עם אמרות חכמה על מידות ואהבת תורה; נלמדת לעיתים בשבת בין פסח לשבועות."
    ),
    "Rechilut is carrying tales that create hatred — even if true. Example: telling Reuven what Shimon said about him to stir conflict. Lashon hara speaks badly about someone; rechilut spreads words between parties. The Chofetz Chaim devotes extensive chapters to permitted speech for protection or constructive need; casual \"did you hear\" stories are almost never allowed.": (
        "רכילות — נשיאת דברים שיוצרים שנאה, גם אם אמת. חפץ חיים מפרט מתי דיבור מותר."
    ),
    "Selichot are penitential prayers recited before Rosh Hashana (Ashkenazim often from the Saturday night before, Sephardim from Elul). They include poetic pleas and the Thirteen Attributes of Mercy. Waking early or staying late for Selichot sets a tone of seriousness before the Days of Awe. Nusach and schedule vary — check your shul.": (
        "סליחות — תחינות לפני ראש השנה; אשכנזים ממוצאי שבת, ספרדים מאלול."
    ),
    "Shechita is kosher slaughter: a trained shochet cuts the throat swiftly with a perfectly smooth knife so the animal dies with minimal suffering and the meat is permitted. Afterwards, blood is removed through salting (melicha) and soaking. Non-kosher meat is called treif. Shechita is one of the most carefully regulated mitzvot in kashrut.": (
        "שחיטה — שחיטה כשרה על ידי שוחט מיומן; מליחה להוצאת דם."
    ),
    "Shekhinah — The Shekhinah is G-d's indwelling presence — especially associated with the Temple, with Israel in exile, and with holiness in marriage and Shabbat. Kiddush Levana tradition says blessing the moon is like greeting the Shekhinah. It is not a separate being; it is how we speak of G-d being near.": (
        "שכינה — נוכחות ה' השורה; לא ישות נפרדת."
    ),
    "Tachanun are supplication prayers after the Amidah on weekdays — omitted on Shabbat, Yom Tov, Rosh Chodesh, and other happy days. Many kneel or lean on the arm. Skipping tachanun on a sad day is a sign the calendar treats the day as joyful. If you are unsure whether tachanun is said, follow the shul or siddur headings.": (
        "תחנון — תחינות אחרי עמידה בימי חול; מדלגים בימים שמחים."
    ),
    "Tachanun — Tachanun are supplication prayers after the Amidah on weekdays — omitted on Shabbat, Yom Tov, Rosh Chodesh, and other happy days. Many kneel or lean on the arm. Skipping tachanun on a sad day is a sign the calendar treats the day as joyful. If you are unsure whether tachanun is said, follow the shul or siddur headings.": (
        "תחנון — תחינות בימי חול בלבד."
    ),
    "Tashlich is a Rosh Hashana custom of casting breadcrumbs or symbolic sins into flowing water, reciting Micah 7:19. It is not in the Talmud like shofar, but is widespread. When the first day of Rosh Hashana falls on Shabbat, tashlich is postponed to Sunday — a structural rule across mainstream Ashkenazi and Sephardic practice, not a local preference. The Sages enacted this to prevent carrying machzorim through a public domain without a kosher eruv. It is symbolic teshuvah — the real work is inward change and apology to people you hurt.": (
        "תשליך — מנהג ראש השנה לזרוק פירורים למים זורמים; סמלי. העבודה האמיתית — תשובה פנימית."
    ),
    "Tefillin are holy black leather boxes containing parchment with Torah verses, bound on the arm and head during weekdays. Men age thirteen and over are required to wear them. Shel yad (arm-tefillin) goes on the upper left arm for right-handed individuals, or the upper right arm if you are left-handed. Recite the bracha at misheyakir (see glossary). They require kosher scrolls and proper placement. They are not worn on Shabbat or festivals.": (
        "תפילין — קלפי עור עם פרשיות; גברים מגיל שלוש עשרה בימי חול בלבד."
    ),
    "Tefillin — Tefillin are holy black leather boxes containing parchment with Torah verses, bound on the arm and head during weekdays. Men age thirteen and over are required to wear them. Shel yad (arm-tefillin) goes on the upper left arm for right-handed individuals, or the upper right arm if you are left-handed. Recite the bracha at misheyakir (see glossary). They require kosher scrolls and proper placement. They are not worn on Shabbat or festivals.": (
        "תפילין — מצווה יומית לגברים; לא בשבת וחג."
    ),
    "Tzeit (tzeit hakochavim) is halachic nightfall — when three medium stars appear and the day ends for night mitzvot like counting the Omer, bedikat chametz, Chanukah candles, Purim, and the end of Shabbat. It is not identical to sunset; communities follow different standards — from three medium stars to fixed minutes after sunset, and in some Diaspora communities much later (e.g. Rabbeinu Tam). Note: While standard Shabbat and weekday Erev Yom Tov candles must be lit before sunset, whenever a festival begins on a Saturday night (Motzei Shabbat), the Yom Tov candles strictly must be lit after sunset, only once nightfall (tzeit) has arrived, using a pre-existing flame — lighting them before sunset on Shabbat is a severe violation. Shavuot candles also wait for tzeit. The app shows local zmanim; when in doubt on a borderline mitzvah, ask your rav.": (
        "צאת הכוכבים — לילה הלכתי; שלוש כוכבים בינוניות. נרות יום טוב במוצאי שבת רק אחרי צאה."
    ),
    "Tzeit — Tzeit (tzeit hakochavim) is halachic nightfall — when three medium stars appear and the day ends for night mitzvot like counting the Omer, bedikat chametz, Chanukah candles, Purim, and the end of Shabbat. It is not identical to sunset; communities follow different standards — from three medium stars to fixed minutes after sunset, and in some Diaspora communities much later (e.g. Rabbeinu Tam). Note: While standard Shabbat and weekday Erev Yom Tov candles must be lit before sunset, whenever a festival begins on a Saturday night (Motzei Shabbat), the Yom Tov candles strictly must be lit after sunset, only once nightfall (tzeit) has arrived, using a pre-existing flame — lighting them before sunset on Shabbat is a severe violation. Shavuot candles also wait for tzeit. The app shows local zmanim; when in doubt on a borderline mitzvah, ask your rav.": (
        "צאת הכוכבים — סוף היום ההלכתי ללילה."
    ),
    "Yizkor is the memorial prayer on Yom Tov (and Yom Kippur) for parents and sometimes other relatives. Many light a yahrzeit candle before the day. Pledging charity in their memory is a beautiful custom. Those with both parents living often leave the shul briefly per minhag. The prayer affirms that merit and memory continue beyond death.": (
        "יזכור — תפילת זיכרון ליום טוב ויום כיפור; נר יארצייט וצדקה לזכרם."
    ),
    "Yizkor — Yizkor is the memorial prayer on Yom Tov (and Yom Kippur) for parents and sometimes other relatives. Many light a yahrzeit candle before the day. Pledging charity in their memory is a beautiful custom. Those with both parents living often leave the shul briefly per minhag. The prayer affirms that merit and memory continue beyond death.": (
        "יזכור — תפילת זיכרון להורים."
    ),
    "Matanot la'evyonim (מתנות לאביונים) helps every Jew celebrate Purim with food and joy (Esther 9:22).\n\nThe mitzvah (Peninei Halakha 05-16-03):\n• Give at least one gift to each of two different poor people (minimum of two recipients total) during Purim daytime.\n• Each gift should enable a modest Purim meal — money is common (Peninei Halakha: roughly enough for about three slices of bread or your community's minimum; amounts vary).\n\nHow to do it:\n• Give during Purim daytime only (not at night); many give after the daytime Megillah reading (follow your minhag).\n• Ideally before your Purim seudah so recipients can use it for the meal.\n• You may give through a trustworthy messenger, gemach, or organization that distributes on Purim day — verify funds reach the poor that day\n• If you cannot find recipients, ask your rabbi or shul — many collect on Purim morning\n\nWho qualifies: Someone who lacks resources for Purim — your rav can guide you if unsure.": (
        "מתנות לאביונים (מתנות לאביונים) — מצווה שכל יהודי ישמח בפורים.\n\nהמצווה:\n• לפחות מתנה לשני עניים שונים ביום פורים.\n• מתנה שמאפשרת סעודת פורים צנועה — לרוב כסף.\n\nאיך:\n• רק ביום פורים, לא בלילה; רצוי לפני הסעודה.\n• אפשר דרך שליח, גמ\"ח או ארגון — ודאו שהגיע לעניים באותו יום.\n\nמי זכאי: מי שחסר לו לפורים — שאלו רב."
    ),
    "Matanot la'evyonim are gifts sent to the poor on Purim day so they can rejoice too: at least one gift to each of two different poor people (minimum of two recipients total). Money is common; food or vouchers work if they can use them that day. Unlike mishloach manot, this mitzvah focuses on need, not friendship. Many shuls collect on Purim morning; verify distribution happens on Purim itself (and on the same day you are celebrating it, i.e. on Shushan Purim).": (
        "מתנות לאביונים — מתנות לעניים ביום פורים: לפחות מתנה לשני נמענים. בניגוד למשלוח מנות — כאן צורך, לא חברות."
    ),
    "matanot la'evyonim — Matanot la'evyonim are gifts sent to the poor on Purim day so they can rejoice too: at least one gift to each of two different poor people (minimum of two recipients total). Money is common; food or vouchers work if they can use them that day. Unlike mishloach manot, this mitzvah focuses on need, not friendship. Many shuls collect on Purim morning; verify distribution happens on Purim itself (and on the same day you are celebrating it, i.e. on Shushan Purim).": (
        "מתנות לאביונים — מתנות לעניים ביום פורים לפחות לשני נמענים."
    ),
    "Melave Malka (מְלַוֶּה מַלְכָּה) means \"escorting the queen\" — a meal Saturday night to escort the Shabbat Queen as she departs, the way one would honor a beloved guest at the door (Talmud Shabbat 119b). It is also called Seudat David HaMelech: King David held a Motzei Shabbat feast each week after learning he would die on Shabbat (Shabbat 30a).\n\nWhen:\nAfter Havdalah, from tzeit (nightfall) until dawn Sunday. Men and women; all nusachim.\n\nWhat to do:\n• Spread a clean tablecloth and set the table — the sages say to set the table even if you will eat only a small amount\n• Sit and eat at the table. The ideal is a meal with bread: wash hands (netilat yadayim), say hamotzi, and eat. If you are too full for bread, you can still fulfill the mitzvah with cake or another meaningful portion of food — netilat yadayim applies only when you eat bread\n• When you can, prepare something for this meal rather than only finishing Shabbat leftovers\n• Many light candles on or near the table\n\nFour candles (optional — Baal Shem Tov, Siddur Tzelota D'Yisrael; Sefer Amrei Esh):\nSome light four candles at Melave Malka. Chassidic tradition teaches that King David is spiritually present at this meal. A common practice (Rabbi Aaron Roth, Shulchan HaTahor): dedicate one candle each to King David, Eliyahu HaNavi, Rabbi Meir Baal HaNess, and the Baal Shem Tov — or choose any four tzaddikim. Light them at the table, name each dedication, and ask then for your needs for the week ahead in the merit of the tzaddikim.\n\nIf you are truly too full from Shabbat, you are not required to force yourself — but even a little food at a set table honors the mitzvah.": (
        "מלווה מלכה (מְלַוֶּה מַלְכָּה) — סעודה במוצאי שבת ללוות את שבת המלכה.\n\nמתי: אחרי הבדלה, מצאת הכוכבים עד עלות השחר.\n\nמה לעשות:\n• ערכו שולחן; אידיאל עם לחם ונטילת ידיים.\n• אם שבעים מדי — גם מעט אוכל מכבד את המצווה.\n• רבים מדליקים נרות."
    ),
    "Mishloach manot (משלוח מנות) — sending portions of food — increases friendship and joy on Purim (Esther 9:19).\n\nThe mitzvah (Rambam, Shulchan Arukh 695:4; Aish; Peninei Halakha 05-16-04):\n• Send at least two different ready-to-eat foods or drinks to one friend on Purim day — one mishloach manot package.\n• Women are equally obligated; many send to a woman friend and men to a man (Rema). Sending to additional friends is praiseworthy.\n• Examples: wine and cookies, fruit and pastry — clearly two types, not one combined dish.\n\nHow to do it:\n• Deliver on Purim day before sunset — by you or a messenger (shul lists, kids, or neighbors are fine)\n• Food should be ready to eat without cooking\n• Label sender and recipient; mishloach manot should be identifiable\n\nTips: You need not reciprocate every package you receive the same day. Plan ahead on Erev Purim so deliveries are not rushed at the last minute.": (
        "משלוח מנות (משלוח מנות) — שליחת מנות מגבירה אהבה ושמחה בפורים.\n\nהמצווה:\n• לפחות שני מיני אוכל מוכנים לחבר אחד ביום פורים.\n• נשים חייבות כמו גברים.\n\nאיך: מסירה ביום פורים לפני השקיעה; מוכן לאכילה; סימון שולח ומקבל."
    ),
    "Simchat Yom Tov — Simchat Yom Tov (שִׂמְחַת יוֹם טוֹב) is the Torah mitzvah \"V'samachta b'chagecha\" — rejoice in your festival (Devarim 16:14). The head of household facilitates joy for each family member in the way that brings them happiness (Pesachim 109a; SA OC 529:2): wife — new clothing or jewelry l'fi mamono (within means); children — treats (today candies and toys; Talmud: grains and nuts); men — festive meat and wine meals. Halacha requires including the poor — joy only among yourselves without helping the needy is \"joy of one's stomach,\" not mitzvah joy. At the least it's recommended to provide the poor with tzedaka so they can enjoy the holiday as well.": (
        "שמחת יום טוב (שִׂמְחַת יוֹם טוֹב) — «ושמחת בחגך». ראש הבית מגיש שמחה לכל בן בית; כולל עניים — שמחה בלי צדקה אינה שמחת מצווה."
    ),
    "The Purim seudah (סעודת פורים) is one of the four Purim mitzvot (Esther 9:22; Peninei Halakha 05-16-02).\n\nWhen:\n• During Purim day — before sunset (many hold the meal in the afternoon after mitzvot are underway).\n\nHow:\n• A festive meal with bread (hamotzi — many use two rolls), meat, wine, and joy. Do not use matzah — there is no Purim custom for matzah, and many avoid matzah in the weeks before Pesach so the Seder taste stays distinct (Rema O.C. 471:2).\n• Include words of Torah or thanks to Hashem — the meal is a mitzvah, not only a party.\n• Drinking wine is a widespread custom but not required to excess; celebrate responsibly.\n\nPlan the menu and timing so matanot la'evyonim and mishloach manot are handled earlier in the day when possible.": (
        "סעודת פורים (סעודת פורים) — אחת מארבע מצוות פורים.\n\nמתי: ביום פורים לפני השקיעה.\n\nאיך: סעודה חגיגית עם לחם, בשר ויין; דברי תורה; שמחה באחריות."
    ),
    "matana al menat lehachzir — Matana al menat lehachzir (מַתָּנָה עַל מְנָת לְהַחְזִיר) is a \"gift on condition it is returned.\" The recipient legally owns the item for the moment it is in their hands, then returns it afterward. On the first day of Sukkot, if you do not own a lulav and etrog, someone may gift you their set conditionally so you fulfill the Torah obligation of ownership for the mitzvah, then you return it. This is not used for mechirat chametz — selling chametz requires an absolute sale.": (
        "מתנה על מנת להחזיר (מַתָּנָה עַל מְנָת לְהַחְזִיר) — מתנה בתנאי שמוחזרת. ביום ראשון של סוכות — לולב ואתרוג; לא למכירת חמץ."
    ),
}
