"""French human rewrites for the 23 Shabbat Melacha explainer essays (batch 16)."""

from __future__ import annotations

MELACHA_FR: dict[str, str] = {
    "Boneh": (
        "Apprenez la melakha de Boneh — l'acte délibéré de construire ou d'assembler une structure — "
        "et découvrez comment cette limite façonne notre usage des objets du foyer, des meubles et des "
        "abris temporaires le Shabbat ! Cette catégorie fondamentale de travail créatif remonte à la "
        "construction du Mishkan, où des artisans qualifiés érigeaient les panneaux muraux en bois et "
        "assemblaient les lourds socles pour créer un Tabernacle unifié et solide. La définition "
        "centrale de Boneh est la création, l'amélioration ou l'assemblage d'une structure, d'un "
        "récipient ou d'un espace fonctionnel en combinant des pièces en une unité stable. Le Shabbat, "
        "la construction lourde, l'installation d'étagères permanentes ou la réparation d'une poignée "
        "de porte tombée de son logement sont strictement interdits. Même si l'on ne coule pas de béton "
        "le samedi, Boneh donne des lignes directrices très pratiques pour la vie quotidienne. Un "
        "exemple classique : monter un auvent pop-up ou une grande tente multi-panneaux pour l'ombre — "
        "assembler un abri couvert qui protège une large zone peut constituer la création d'un Ohel "
        "(tente/auvent), soumis aux restrictions de Boneh. De même, assembler des meubles modulaires en "
        "plastique ou visser des pièces qui forment une unité rigide posent problème. En savoir plus !"
    ),
    "Hotza'ah": (
        "Découvrez la melakha de Hotza'ah — l'acte délibéré de transférer ou de transporter des objets "
        "entre différents domaines — et comment cette frontière transforme notre mouvement public et "
        "nos espaces communautaires le Shabbat ! Cette catégorie de travail créatif est mise en "
        "évidence dans toute la Torah et remonte à la construction du Mishkan. Lorsque Moshe rassembla "
        "le peuple pour bâtir le sanctuaire, il commença par un avertissement strict de respecter le "
        "Shabbat, enseignant que la construction de la maison de D. ne l'emporte pas sur le jour de "
        "repos. Ainsi, lorsque le peuple cessa de transporter publiquement or, argent et tissus de "
        "leurs tentes vers le camp commun, cette pause établit le plan légal pour cesser le transport "
        "public le jour saint. La définition centrale de Hotza'ah est le déplacement d'un objet d'un "
        "domaine privé (reshut hayachid) vers un domaine public (reshut harabim), ou inversement, ou "
        "le transport sur une distance de quatre coudées (environ deux mètres) dans un domaine public. "
        "Selon la loi de la Torah, un domaine privé est un espace clos d'au moins quatre tefahim sur "
        "quatre, avec des murs d'au moins dix tefahim de haut ; un vrai domaine public est une voie "
        "ouverte et non couverte, fréquentée par les masses. Cependant, la plupart des rues modernes ne "
        "remplissent pas les critères stricts d'un domaine public biblique ; elles sont classées "
        "rabbiniquement comme karmelit (zone semi-publique), où le transport reste limité pour "
        "préserver les frontières bibliques. Cela a des implications très concrètes en sortant de "
        "chez soi : porter clés, mouchoirs, bouteilles d'eau ou pousser une poussette devient interdit. "
        "Pour s'organiser sans éiruv — enceinte halakhique symbolique qui unifie un quartier en un "
        "seul domaine « privé » partagé — les personnes observantes utilisent des solutions créatives : "
        "transformer les clés en bijoux portables (pince à cravate, boucle de ceinture), car porter un "
        "ornement autorisé n'est pas un transport interdit. Les communautés investissent dans "
        "l'établissement et l'entretien d'un éiruv ; sans éiruv, on laisse à la maison tout ce qui "
        "n'est pas portable avant le coucher du soleil vendredi. En savoir plus !"
    ),
    "Koreah": (
        "Apprenez la melakha de Koreah — l'acte délibéré de déchirer des matériaux — et pourquoi "
        "« casser » quelque chose peut violer profondément le repos du Shabbat ! Si la déchirure semble "
        "destructrice, la Torah enseigne que lorsqu'elle sert un but constructif, c'est un acte "
        "d'artisanat. Ce travail remonte au Mishkan, où les ouvriers déchiraient des sections de "
        "rideaux lourds pour corriger une erreur de tissage ou reformer un tissu aux dimensions "
        "voulues. La définition centrale de Koreah est la déchirure d'un objet unifié — tissu, cuir, "
        "papier ou plastique — dans le but de l'améliorer, de le préparer à un acte créatif futur ou "
        "d'en tirer un bénéfice fonctionnel. Le Shabbat, déchirer un tissu pour en faire un chiffon, "
        "ouvrir une enveloppe scellée le long de son rabat collé ou couper du papier aluminium à une "
        "taille précise posent problème. Cette loi mène à l'une des discussions halakhiques les plus "
        "célèbres : déchirer du papier toilette d'un rouleau le Shabbat. Comme cela crée une feuille "
        "utilisable à partir d'un rouleau continu, beaucoup d'autorités voient l'acte comme une "
        "création fonctionnelle ; d'où l'usage de feuillettes pré-découpées ou la préparation avant le "
        "Shabbat. Pour ouvrir un emballage alimentaire le samedi, on peut déchirer de façon "
        "destructive pour accéder à la nourriture, car l'emballage ruiné n'est pas une création "
        "constructive. La plupart des rabbins déconseillent d'ouvrir au point de colle si de la colle "
        "a été utilisée, bien que certains soient plus indulgents. L'essence de Koreah nous rappelle "
        "que le Shabbat n'est pas un jour pour démonter le monde afin de le refaire à notre guise, "
        "mais pour sortir du cycle de transformation permanente. En savoir plus !"
    ),
    "Koteiv": (
        "Apprenez la melakha de Koteiv — l'interdiction fondamentale d'écrire — et découvrez comment "
        "cette limite créative façonne notre conduite le Shabbat ! Cette catégorie centrale remonte à "
        "la construction du Mishkan, où des artisans inscrivaient des lettres ou symboles sur les "
        "poutres en bois pour marquer les paires correspondantes, afin que l'édifice puisse être "
        "démonté et remonté avec précision. La définition centrale de Koteiv est la formation de tout "
        "symbole, caractère ou lettre porteur de sens sur une surface. Pour transgresser l'interdiction "
        "toranique, il faut écrire au moins deux lettres ou symboles distincts avec un support "
        "permanent sur une surface durable. Les Sages ont étendu cette limite pour protéger le jour de "
        "repos, interdisant rabbiniquement l'écriture temporaire et la formation de lettres ou images "
        "qui ne préexistent pas. De même, recoller une page déchirée pour que les lettres s'alignent "
        "peut violer Koteiv. Même les livres dont les tranches portent des mots ou motifs estampés "
        "posent une question : ouvrir et fermer le livre sépare et réunit le texte, ce qui pousse "
        "beaucoup d'autorités à préférer des livres sans impression sur les tranches le jour saint. "
        "Cette limite guide aussi les jeux comme le Scrabble : poser de simples lettres plates côte à "
        "côte est en général permis, mais les versions de voyage où les lettres s'enclenchent dans un "
        "cadre rigide sont discutées, car fixer fermement des lettres ressemble à écrire. Pour les "
        "scores, les joueurs soucieux de la halakha peuvent suivre les points en feuilletant les pages "
        "d'un livre (non saint) plutôt qu'en écrivant ! En savoir plus !"
    ),
    "Mafshit": (
        "Apprenez la melakha de Mafshit — l'acte délibéré d'écorcher et de séparer une peau de la "
        "chair — et comment cette séparation laborieuse révèle l'arrêt total de la transformation "
        "industrielle le Shabbat ! Cette catégorie avancée fait partie de la longue chaîne de "
        "production du cuir, vitale pour le Mishkan, où les ouvriers retiraient les peaux de béliers, "
        "tahash et chèvres pour fabriquer les rideaux protecteurs du sanctuaire. La définition "
        "centrale de Mafshit est la séparation physique de la peau d'un animal de sa viande ou "
        "carcasse de manière productive. Le Shabbat, tout acte d'écorchage, d'épluchage de peau pour "
        "le cuir ou de dépouillement d'une carcasse est strictement interdit. Les détails de Mafshit "
        "ont aussi des applications alimentaires : retirer la peau d'un morceau de poulet cuit pendant "
        "un repas est permis, car c'est manger et non fabriquer du cuir. En revanche, avec les "
        "articles en cuir le samedi, la halakha considère le fractionnement mécanique des couches "
        "collées : si une ceinture, une sangle ou une semelle en cuir commence à se déliter en deux "
        "couches distinctes, les écarter délibérément le Shabbat entre dans cette melakha peu connue ! "
        "En savoir plus !"
    ),
    "Makeh B'patish": (
        "Découvrez la melakha de Makeh B'patish — le coup de marteau final qui achève un ouvrage — et "
        "comment cette limite suspend les touches finales sur tous nos objets le Shabbat ! Cette "
        "catégorie remonte au Mishkan, où des artisans frappaient un dernier coup de marteau sur des "
        "vessels métalliques neufs pour lisser les imperfections et rendre l'objet pleinement "
        "fonctionnel. La définition centrale de Makeh B'patish est l'action finale intentionnelle qui "
        "transforme un objet incomplet, défectueux ou inutilisable en produit fini et prêt à l'emploi. "
        "Selon la Torah, cela s'applique à tout métier : couper un fil pendant qui dépasse d'une "
        "chemise neuve, insérer une vis pour stabiliser une table, redresser une cuillère tordue ou "
        "remettre en place une fermeture éclair détachée. De même, retirer un clou dangereux d'un mur "
        "pour rendre la surface sûre est considéré comme une finition par réparation. Le Shabbat, les "
        "personnes observantes repoussent toutes les petites réparations, assemblages et finitions "
        "jusqu'après la Havdala, profitant de leur environnement tel qu'il était préparé avant le jour "
        "saint. En savoir plus !"
    ),
    "Matir": (
        "Découvrez la melakha de Matir — l'acte délibéré de défaire un nœud — et la symétrie "
        "halakhique fascinante qui détermine quand ouvrir un paquet devient un travail interdit le "
        "Shabbat ! Contrepartie directe de Koshair, le déliement remonte au Mishkan, où les artisans "
        "défaisaient les nœuds permanents des tapisseries et cordages lorsque le camp se déplaçait. Le "
        "Shabbat, Matir interdit de défaire tout nœud permanent ou à long terme. La règle reflète "
        "celle du nouage : tout nœud dont la Torah interdit le nouage interdit aussi le déliement, "
        "et de même pour les interdictions rabbiniques. Un nœud professionnel destiné à rester indéfini "
        "— corde de chargement ou sangle en cuir — ne peut pas être défait le Shabbat, même s'il a "
        "été noué des années auparavant en semaine. Cela touche la vie quotidienne, de l'ouverture d'un "
        "nœud sur un paquet alimentaire aux lacets enchevêtrés. Si un nœud se forme accidentellement "
        "(le Shabbat ou avant), on est en général indulgent pour le défaire, car il n'était pas voulu. "
        "Nouer quelque chose qui ne doit pas durer plus de vingt-quatre heures — comme un lacet simple "
        "(non double) — est aussi permis. En savoir plus !"
    ),
    "Mav'ir": (
        "Apprenez la melakha de Mav'ir — l'acte délibéré d'allumer ou d'alimenter un feu — et "
        "découvrez comment cette limite suspend notre contrôle de la chaleur et de la combustion le "
        "Shabbat ! La Torah la mentionne explicitement ; elle remonte au Mishkan, où les artisans "
        "allumaient des feux pour fondre les métaux des vessels du Tabernacle et cuire les offrandes. "
        "La définition centrale de Mav'ir est la création, l'expansion ou l'alimentation intentionnelle "
        "d'une flamme, étincelle ou source de chaleur intense. Selon la Torah, cela inclut frapper une "
        "allumette, ajouter du bois à un feu ou appuyer sur l'accélérateur d'une voiture à moteur "
        "à combustion. Mav'ir introduit aussi des règles pratiques pour la technologie moderne : la "
        "halakha restreint la fermeture d'un circuit électrique pour allumer un appareil, régler un "
        "brûleur à gaz ou brancher un appareil, car créer un courant ou chauffer un élément imite "
        "l'allumage d'un feu. Cette frontière façonne l'usage de l'électricité, des appareils de "
        "cuisine et des hôtels. Le Shabbat, on programme des minuteries avant le début du jour, on "
        "règle les mijoteuses avant vendredi soir et on s'appuie sur chaleur et lumière déjà existantes "
        "pour honorer le repos. En savoir plus !"
    ),
    "Me'abeid": (
        "Apprenez la melakha de Me'abeid — l'art ancien de transformer une peau crue en cuir durable "
        "— et découvrez comment cette melakha modifie même notre façon de saler les aliments le "
        "Shabbat ! Cette catégorie remonte au Mishkan, où les ouvriers traitaient les peaux avec "
        "huiles, sels et bains chimiques pour les adoucir, teindre et conserver en cuir résistant "
        "nécessaire aux revêtements extérieurs. La définition centrale de Me'abeid est le traitement "
        "physique ou chimique d'une matière organique brute pour la préserver, la durcir ou empêcher "
        "sa décomposition. Le Shabbat, toute action de tannage, de traitement du cuir ou de "
        "assouplissement d'un matériau rigide est interdite. Me'abeid a une sous-catégorie directe, "
        "Molei'ach (salage) : comme saler est la première étape du tannage, saler une matière pour "
        "en modifier la texture entre dans la même catégorie. Cela touche la cuisine : saler "
        "abondamment des légumes crus (concombres, radis, oignons) pour les faire mariner ressemble au "
        "processus de conservation d'une peau. Le Shabbat, on évite de verser beaucoup de sel sur un "
        "bol de légumes crus pour les laisser mariner ; on préfère saler juste avant de servir, ou "
        "mélanger d'abord avec huile ou vinaigre pour atténuer l'effet de « cure ». L'essence "
        "spirituelle de Me'abeid : l'humanité sait transformer la nature en biens durables, mais le "
        "Shabbat suspend entièrement cette transformation. En savoir plus !"
    ),
    "Mechabeh": (
        "Apprenez la melakha de Mechabeh — l'acte délibéré d'éteindre un feu — et découvrez comment "
        "cette limite suspend notre contrôle des flammes et éléments chauffants le Shabbat ! Elle "
        "remonte au Mishkan, où les métallurgistes éteignaient des braises pour produire du charbon de "
        "bois ou réguler la chaleur des fours. La définition centrale de Mechabeh est l'extinction, "
        "l'atténuation ou l'amortissement intentionnel d'une flamme, étincelle ou feu. Selon la "
        "Torah, cela s'applique lorsque l'extinction est constructive — créer du charbon ou conserver "
        "une mèche pour plus tard. Les Sages ont étendu l'interdiction à toute extinction destructive. "
        "Le Shabbat, souffler une bougie, verser de l'eau sur une mèche ou éteindre un brûleur à gaz "
        "est interdit. Même baisser une flamme pour laisser mijoter est restreint, car atténuer un "
        "feu est une forme d'extinction partielle. Mechabeh façonne l'usage de l'éclairage et de la "
        "cuisine : on allume les bougies avant le Shabbat et on les laisse s'éteindre d'elles-mêmes, "
        "on programme des minuteries pour la lumière électrique et on laisse les brûleurs à température "
        "fixe sous un blech jusqu'à la fin du Shabbat. En savoir plus !"
    ),
    "Mechateich": (
        "Apprenez la melakha de Mechateich — l'acte délibéré de couper un matériau à une taille ou "
        "forme précise — et découvrez comment cette limite façonne l'ouverture des paquets, la "
        "préparation des aliments et l'usage des objets du foyer le Shabbat ! Elle remonte au Mishkan, "
        "où les artisans mesuraient et coupaient tapisseries, peaux et poutres aux dimensions exactes "
        "voulues. La définition centrale de Mechateich est la coupe, déchirure ou taille intentionnelle "
        "d'un objet fonctionnel à une dimension, forme ou mesure précise à des fins productives. Le "
        "Shabbat, tailler du film plastique à une longueur précise, couper un fil pour égaliser un "
        "bord de tissu ou scier une planche pour une étagère bricolage est interdit. Un exemple "
        "classique : déchirer du papier toilette le long des perforations — obtenir une feuille de "
        "taille mesurée viole Mechateich (même sans couper sur les lignes, Koreah peut s'appliquer). "
        "De même, séparer un multi-pack de yaourts à la couture perforée divise le matériau en unités "
        "de taille précise. En savoir plus !"
    ),
    "Melaben": (
        "Découvrez la melakha de Melaben — l'art du blanchiment et du nettoyage des tissus — et "
        "pourquoi nous ne faisons pas la lessive ni n'essuyons les taches le Shabbat ! Cette catégorie "
        "remonte au Mishkan, où les ouvriers lavaient et blanchissaient poils de chèvre et laine avant "
        "de les filer en tapisseries. Le Shabbat, Melaben suspend tout blanchiment, nettoyage et "
        "rafraîchissement des tissus, bien au-delà de la machine à laver. Même enlever une tache "
        "fraîche sur une nappe ou une chemise peut être une violation grave : tamponner immédiatement "
        "avec de l'eau ou frotter la tache avec intention de nettoyer, c'est forcer la saleté hors "
        "des fibres — Melaben. Les règles sont si sensibles que mouiller un vêtement sale peut parfois "
        "être considéré comme le début du processus de lessive. En savoir plus !"
    ),
    "Memachek": (
        "Découvrez la melakha de Memachek — l'art délicat du lissage et du grattage des surfaces — "
        "et comment cette limite modifie l'usage du savon, du dentifrice et des crèmes le Shabbat ! "
        "Elle remonte au Mishkan, où les artisans grattaient les peaux crues pour enlever les poils, "
        "lisser les aspérités et rendre le cuir uniforme pour les revêtements. La définition centrale "
        "de Memachek est le lissage, ponçage ou grattage mécanique d'un matériau rigide — bois, "
        "pierre, métal ou cuir — pour nivellement. Le Shabbat, poncer un meuble, gratter une sangle en "
        "cuir ou polir une égratignure sur du bois est interdit. Memachek a une contrepartie "
        "quotidienne majeure, Memarei'ach : lisser des substances pâteuses. Cela touche l'hygiène et "
        "les soins : étaler une épaisse couche de pommade, frotter un savon en barre jusqu'à mousse "
        "lisse ou presser une bande épaisse de dentifrice ressemble au nivellement d'une surface. Pour "
        "éviter cette limite, on utilise du savon liquide, des huiles ou lotions fines qui pénètrent "
        "vite, et on tamponne une pommade médicale sans l'étaler. En savoir plus !"
    ),
    "Menapetz": (
        "Découvrez la melakha de Menapetz — l'art de peigner et séparer les fibres brutes — et "
        "comment une technique textile du désert façonne ce que nous pouvons faire le Shabbat ! Elle "
        "remonte au Mishkan, où les ouvriers peignaient agressivement laine ou lin pour démêler les "
        "nœuds, séparer les brins et les aligner avant le filage. Le Shabbat, Menapetz interdit toute "
        "action qui imite ce raffinement industriel de matières enchevêtrées. Elle touche aussi la "
        "toilette personnelle : tirer une brosse dure dans des cheveux emmêlés risque d'arracher des "
        "poils — Gozez (tonte) — ; l'esprit de Menapetz invite à la douceur ce jour-là. Plutôt qu'un "
        "brossage force qui sépare les brins, on utilise des brosses douces ou peignes à larges dents "
        "sur cheveux secs. Une routine matinale devient un rappel de l'atelier du désert et du repos "
        "profond du Shabbat. En savoir plus !"
    ),
    "Mesarteit": (
        "Découvrez la melakha de Mesarteit — l'acte précis de tracer des lignes guides sur une "
        "surface — et comment cette limite préparatoire suspend la mise en place physique de l'écriture "
        "ou de la coupe le Shabbat ! Elle remonte au Mishkan, où scribes et artisans marquaient des "
        "lignes droites sur parchemins et peaux avant l'encre, pour une symétrie parfaite et des "
        "coupes exactes. La définition centrale de Mesarteit est le marquage, la gravure ou le "
        "grattage intentionnel de lignes sur un matériau souple ou solide pour guider une action "
        "future — écrire ou couper une frontière précise. Le Shabbat, presser une ligne faible dans "
        "une page blanche, gratter un guide sur du cuir ou marquer un pli au régle sur du papier épais "
        "est interdit. Les lois de Mesarteit touchent aussi la présentation des aliments : tracer une "
        "ligne profonde sur un gâteau ou des brownies pour guider les coupes futures, ou marquer un "
        "motif de découpe sur une pâte, imite le tracé du parchemin. Pour naviguer cette limite : si "
        "vous coupez le gâteau directement en tranchant, la ligne faite par le couteau en passant est "
        "permise ; le problème est de tracer une ligne préliminaire avant la coupe. Cette règle "
        "influence même le marquage du hallah avant Hamotzi : beaucoup font une légère entaille au "
        "point de départ, pas une ligne continue sur toute la miche, pour éviter de « régler » un "
        "guide de coupe. Fascinant ! En savoir plus !"
    ),
    "Mocheik": (
        "Découvrez la melakha de Mocheik — l'acte délibéré d'effacer ou d'essuyer des marques "
        "significatives — le Shabbat ! Elle remonte au Mishkan, où les scribes effaçaient ou "
        "grattaient toute erreur sur poutres ou parchemins pour préparer la surface à une écriture "
        "correcte. La définition centrale de Mocheik est l'effacement, grattage, dissolution ou "
        "oblitération intentionnelle de symboles, lettres ou graphiques significatifs. Selon la Torah, "
        "cela s'applique lorsque l'effacement est constructif — nettoyer une surface pour réécrire, "
        "comme essuyer un tableau. Les Sages interdisent aussi l'effacement destructive sans "
        "réécriture. Cette limite guide la manipulation des matériaux écrits le jour de repos : "
        "rayer du texte, effacer du crayon ou détruire un enregistrement permanent est interdit. "
        "Chez les Ashkenazim suivant le Rema, on évite de déchirer des lettres ou logos imprimés à "
        "l'ouverture d'emballages ; bédieved ou accidentellement, c'est permis. Chez les Séfaradim "
        "suivant Maran Rav Ovadia Yosef, déchirer du texte d'emballage pour accéder à la nourriture "
        "ou aux médicaments est permis dès le départ, sans intention d'effacer. En savoir plus !"
    ),
    "Oreg": (
        "Découvrez la melakha d'Oreg — l'art emblématique de tisser des fils ensemble — et les "
        "limites fascinantes qui séparent l'appréciation du tissu de sa création le Shabbat ! Le "
        "tissage est l'apogée de la production textile, remontant au Mishkan, où les maîtres artisans "
        "entrelacaient fils de chaîne et de trame pour les tapisseries majestueuses du sanctuaire. La "
        "définition centrale d'Oreg est l'entrelacement de deux ensembles distincts de fils à angle "
        "droit pour former une toile cohérente. Le Shabbat, tisser au métier, repriser un trou en "
        "entrelacant de nouveaux fils ou réintégrer un fil lâche dans un vêtement tissé peut violer "
        "Oreg. Le Talmud enseigne que tisser seulement deux fils horizontaux parallèles dans une "
        "grille verticale suffit pour transgresser. Cela touche broderie dense, point de croix et "
        "certaines vanneries serrées, qui partagent la mécanique du métier à tisser. L'essence "
        "spirituelle d'Oreg : la création du tissu est l'une des réalisations fondamentales de "
        "l'humanité, mais le Shabbat nous éloigne de la fabrication — nous portons nos beaux vêtements "
        "sans entrelacer un seul fil, honorant un jour où le tissu de l'univers est déjà complet. "
        "En savoir plus !"
    ),
    "Oseh Batei Nirin": (
        "Découvrez la melakha d'Oseh Batei Nirin — l'art complexe de créer lisses, harnais et boucles "
        "sur un métier — et comment l'ingénierie textile ancienne façonne notre compréhension du repos "
        "du Shabbat ! Sur un métier, les fils de chaîne verticaux passent par des lisses ou œillets "
        "fixés à des cadres mobiles. En levant ou abaissant ces cadres, le tisserand sépare les fils "
        "en deux couches, créant un « shed » (tunnel) par où passent les fils de trame. Au Mishkan, "
        "cette configuration était vitale pour les tapisseries à double face aux motifs géométriques et "
        "animaux visibles des deux côtés. La définition centrale d'Oseh Batei Nirin est la formation "
        "ou la mise en place de ces boucles guides : attacher des cordes pour former les œillets, "
        "passer les fils de chaîne dans les lisses existantes ou fixer les cadres à la mécanique du "
        "métier. Le Shabbat, assembler l'appareil de guidage d'un métier, créer des boucles servant de "
        "rail à d'autres fils ou réparer le gréement d'un métier est interdit. Comme Maisach, cette "
        "melakha est pure calibration structurelle au service du tissage à venir. En suspendant cette "
        "mise en place le samedi, la Torah enseigne que le vrai repos inclut l'arrêt de toute "
        "ingénierie préparatoire — harmonie avec un monde déjà aligné par l'Artisan suprême."
    ),
    "Potze'a": (
        "Apprenez la melakha de Potze'a — l'acte délibéré de séparer, démêler et défaire des fils "
        "tissés — et pourquoi tirer sur un fil lâche peut violer le repos du Shabbat ! Défaire "
        "stratégiquement un tissu est aussi créatif que le tisser. Cette catégorie remonte au Mishkan, "
        "où les tisserands corrigeaient des erreurs dans les tapisseries à double face ou récupéraient "
        "des sections endommagées en tranchant, démêlant et séparant fils de chaîne et de trame. La "
        "définition centrale de Potze'a est ce défaire constructif d'une structure tissée ou tressée, "
        "pour ramener le tissu à ses brins utilisables ou libérer de l'espace pour un nouveau motif. "
        "Le Shabbat, défaire systématiquement une couverture tricotée, démêler le bord effiloché "
        "d'un tissu pour récupérer le fil ou séparer les éléments tissés d'un panier est interdit. "
        "Dans la vie quotidienne, tirer sur un fil pendu à l'ourlet d'un pull et défaire une rangée de "
        "points ou séparer les fibres du vêtement imite le démontage du Mishkan. Le Shabbat, nous "
        "nous abstenons de construire et de déconstruire le monde matériel — nos vêtements restent "
        "tels quels. En savoir plus !"
    ),
    "Shochait": (
        "Apprenez la melakha de Shochait — l'acte d'abattre ou de prendre la vie d'une créature "
        "vivante — et comment cette interdiction grave touche même le fil dentaire le Shabbat ! Elle "
        "remonte au Mishkan, où des animaux étaient abattus pour les sacrifices et pour traiter leurs "
        "peaux en couvertures. La définition fondamentale de Shochait est la fin de la vie ; le Shabbat, "
        "chasser, abattre ou tuer tout mammifère, oiseau, poisson ou insecte est interdit (sauf danger "
        "pour la vie humaine). Comme Shochait concerne l'extraction du fluide vital, le Talmud inclut "
        "Chavurah — causer une blessure qui fait saigner un être vivant. Si quelqu'un a des gencives "
        "sensibles et sait avec certitude que le fil dentaire fera saigner, l'utiliser le Shabbat "
        "violerait l'interdiction de blesser. Les autorités règlent qu'il faut l'éviter si le saignement "
        "est garanti. Shochait enseigne une profonde révérence pour la vie : le Shabbat, nous laissons "
        "le règne animal en paix et nos corps sans blessure, comptant sur la nourriture préparée en "
        "semaine. En savoir plus !"
    ),
    "Soter": (
        "Découvrez la melakha de Soter — l'acte délibéré de démonter ou démolir une structure — et "
        "comment cette limite guide l'usage des objets du foyer, des installations temporaires et "
        "l'ouverture de contenants le Shabbat ! Elle remonte au Mishkan, où les Lévites démontaient "
        "soigneusement panneaux et socles lorsque la Nuée se levait, pour transporter et reconstruire "
        "au camp suivant. La définition de Soter est le démontage intentionnel de toute structure, "
        "récipient ou unité fonctionnelle stable. Selon la Torah, cela s'applique lorsque la "
        "déconstruction est constructive — reconstruire, améliorer ou libérer de l'espace. Les Sages "
        "restreignent aussi le démantèlement destructif. Par exemple, démonter un grand auvent "
        "extérieur ou une tente multi-panneaux le Shabbat peut violer Soter, car défaire un abri "
        "couvert inverse Boneh. De même, dévisser complètement une poignée de porte ou démonter des "
        "meubles modulaires serrés entre eux entre dans cette restriction. En savoir plus !"
    ),
    "Tofair": (
        "Découvrez la melakha de Tofair — l'art précis de la couture — et comment un seul point peut "
        "devenir une leçon profonde de repos du Shabbat ! Elle remonte au Mishkan, où les artisans "
        "cousaient les vastes feuilles de poils de chèvre et de laine pour les couvertures du "
        "sanctuaire et les vêtements sacerdotaux. La définition centrale de Tofair est l'assemblage "
        "de deux pièces flexibles — tissu, cuir ou papier — en une entité unifiée au moyen d'un "
        "élément de liaison : fil, corde ou colle. Le Shabbat, passer aiguille et fil pour repriser "
        "une déchirure est interdit. L'interdiction dépasse l'aiguille traditionnelle : toute liaison "
        "durable et continue entre objets séparés compte — colle liquide, ruban adhésif épais ou "
        "agrafeuse pour un dossier permanent. En cas d'urgence vestimentaire le samedi — bouton "
        "arraché, ourlet déchiré — on ne peut pas utiliser ruban ou colle, mais une épingle de "
        "sûreté posée de façon temporaire et non professionnelle est permise. Un incident mineur "
        "devient un rappel conscient : le Shabbat, garde-robe et monde restent tels quels. En savoir "
        "plus !"
    ),
    "Tzad": (
        "Apprenez la melakha de Tzad — l'acte délibéré de piéger des créatures vivantes — et les "
        "frontières halakhiques qui étendent une trêve totale du Shabbat jusqu'aux plus petits "
        "insectes ! Elle remonte au Mishkan, où chasseurs capturaient des animaux sauvages pour leurs "
        "peaux et piégeaient les escargots chilazon pour la teinture bleue sacrée. La définition "
        "fondamentale de Tzad est de restreindre la liberté d'une créature sauvage non domestiquée — "
        "mammifère, oiseau, poisson ou insecte — en la plaçant dans un espace clos d'où elle ne peut "
        "plus s'échapper facilement. Le Shabbat, jeter un filet sur un poisson, enfermer un animal "
        "dans une cage ou poursuivre une créature pour la confiner est interdit. Cela touche les "
        "nuisibles domestiques : recouvrir une mouche avec un verre ou claquer une boîte sur elle, "
        "c'est Tzad — lui retirer sa liberté de mouvement. Même fermer fenêtre ou porte peut poser "
        "problème si un oiseau sauvage s'est introduit par erreur. Exception essentielle : Pikuach "
        "Nefesh — si une créature venimeuse ou une abeille menace directement la vie, notamment en "
        "cas d'allergie mortelle, on peut piéger ou même tuer l'insecte. Hors urgence, les maisons "
        "observantes évitent plutôt que piéger — fenêtres ouvertes avec précaution ou attente que "
        "l'insecte parte. Fermer la porte sur un animal domestiqué (chien, chat) qui vient quand on "
        "l'appelle est permis ; les créatures sauvages restent libres — le Shabbat, nous reculons "
        "devant la domination du règne animal. En savoir plus !"
    ),
}
