"""Spanish human rewrites for the 23 Shabbat Melacha explainer essays (batch 17)."""

from __future__ import annotations

MELACHA_ES: dict[str, str] = {
    "Boneh": (
        "Aprende la melajá de Boneh — el acto deliberado de construir o ensamblar una estructura — "
        "y descubre cómo este límite moldea el uso de objetos del hogar, muebles y refugios temporales "
        "en Shabat. Esta categoría fundamental de trabajo creativo remonta a la construcción del "
        "Mishkan, donde artesanos cualificados erigían paneles murales de madera y ensamblaban pesados "
        "socles para crear un Tabernáculo unificado y sólido. La definición central de Boneh es la "
        "creación, mejora o ensamblaje de una estructura, un recipiente o un espacio funcional "
        "combinando piezas en una unidad estable. En Shabat, la construcción pesada, instalar "
        "estanterías permanentes o reparar una manija suelta que salió de su alojamiento están "
        "estrictamente prohibidos. Aunque no se vierta hormigón el sábado, Boneh da pautas muy "
        "prácticas para la vida cotidiana. Un ejemplo clásico: montar un toldo pop-up o una gran "
        "tienda multipanel para la sombra — ensamblar un refugio cubierto que protege una zona amplia "
        "puede constituir la creación de un Ohel (tienda/toldo), sujeto a las restricciones de Boneh. "
        "Del mismo modo, ensamblar muebles modulares de plástico o atornillar piezas que forman una "
        "unidad rígida plantean problemas. ¡Más información!"
    ),
    "Hotza'ah": (
        "Descubre la melajá de Hotza'ah — el acto deliberado de transferir o transportar objetos "
        "entre distintos dominios — y cómo esta frontera transforma nuestro movimiento público y "
        "espacios comunitarios en Shabat. Esta categoría de trabajo creativo está destacada en toda "
        "la Torá y remonta a la construcción del Mishkan. Cuando Moshe reunió al pueblo para edificar "
        "el santuario, comenzó con una advertencia estricta de respetar el Shabat, enseñando que "
        "construir la casa de D. no prevalece sobre el día de descanso. Así, cuando el pueblo dejó de "
        "transportar públicamente oro, plata y telas de sus tiendas al campamento común, esa pausa "
        "estableció el plan legal para cesar el transporte público en el día santo. La definición "
        "central de Hotza'ah es mover un objeto de un dominio privado (reshut hayachid) a uno "
        "público (reshut harabim), o viceversa, o transportarlo una distancia de cuatro amot "
        "(aproximadamente dos metros) en un dominio público. Según la Torá, un dominio privado es un "
        "espacio cerrado de al menos cuatro tefajim por cuatro, con muros de al menos diez tefajim "
        "de alto; un verdadero dominio público es una vía abierta y descubierta, transitada por las "
        "masas. Sin embargo, la mayoría de las calles modernas no cumplen los criterios estrictos de "
        "un dominio público bíblico; se clasifican rabínicamente como karmelit (zona semi-pública), "
        "donde el transporte sigue limitado para preservar las fronteras bíblicas. Esto tiene "
        "implicaciones muy concretas al salir de casa: llevar llaves, pañuelos, botellas de agua o "
        "empujar un cochecito queda prohibido. Para organizarse sin éiruv — cercado halájico "
        "simbólico que unifica un barrio en un solo dominio «privado» compartido — quienes observan "
        "la halajá usan soluciones creativas: convertir las llaves en joyas portables (pinza de "
        "corbata, hebilla de cinturón), porque llevar un adorno permitido no es transporte "
        "prohibido. Las comunidades invierten en establecer y mantener un éiruv; sin éiruv, se deja "
        "en casa todo lo no portable antes del atardecer del viernes. ¡Más información!"
    ),
    "Koreah": (
        "Aprende la melajá de Koreah — el acto deliberado de rasgar materiales — y por qué «romper» "
        "algo puede violar profundamente el descanso del Shabat. Aunque el desgarro parece destructivo, "
        "la Torá enseña que cuando sirve un fin constructivo, es un acto de artesanía. Este trabajo "
        "remonta al Mishkan, donde los obreros rasgaban secciones de cortinas pesadas para corregir "
        "un error de tejido o reformar una tela a las dimensiones deseadas. La definición central de "
        "Koreah es rasgar un objeto unificado — tela, cuero, papel o plástico — con el fin de "
        "mejorarlo, prepararlo para un acto creativo futuro o obtener un beneficio funcional. En "
        "Shabat, rasgar un paño para hacer un trapo, abrir un sobre sellado por la solapa pegada o "
        "cortar papel de aluminio a un tamaño preciso plantean problemas. Esta ley conduce a una de "
        "las discusiones halájicas más famosas: rasgar papel higiénico de un rollo en Shabat. Como "
        "esto crea una hoja utilizable a partir de un rollo continuo, muchas autoridades ven el acto "
        "como una creación funcional; de ahí el uso de hojas precortadas o la preparación antes del "
        "Shabat. Para abrir un envase de comida el sábado, se puede rasgar de forma destructiva para "
        "acceder a la comida, porque el envase arruinado no es una creación constructiva. La mayoría "
        "de los rabinos desaconsejan abrir en el punto de pegamento si se usó cola, aunque algunos "
        "son más indulgentes. La esencia de Koreah nos recuerda que Shabat no es un día para "
        "desmontar el mundo para reformarlo a nuestro gusto, sino para salir del ciclo de "
        "transformación permanente. ¡Más información!"
    ),
    "Koteiv": (
        "Aprende la melajá de Koteiv — la prohibición fundamental de escribir — y descubre cómo "
        "este límite creativo moldea nuestra conducta en Shabat. Esta categoría central remonta a la "
        "construcción del Mishkan, donde artesanos inscribían letras o símbolos en las vigas de "
        "madera para marcar pares correspondientes, de modo que el edificio pudiera desmontarse y "
        "remontarse con precisión. La definición central de Koteiv es formar cualquier símbolo, "
        "carácter o letra con significado sobre una superficie. Para transgredir la prohibición "
        "de la Torá, hay que escribir al menos dos letras o símbolos distintos con un medio "
        "permanente sobre una superficie duradera. Los Sabios ampliaron este límite para proteger "
        "el día de descanso, prohibiendo rabínicamente la escritura temporal y la formación de "
        "letras o imágenes que no preexisten. Igualmente, volver a pegar una página rasgada para "
        "alinear las letras puede violar Koteiv. Incluso libros cuyos cantos llevan palabras o "
        "motivos estampados plantean una cuestión: abrir y cerrar el libro separa y reúne el texto, "
        "lo que lleva a muchas autoridades a preferir libros sin impresión en los cantos el día "
        "santo. Este límite también guía juegos como el Scrabble: colocar letras planas simples "
        "lado a lado suele estar permitido, pero las versiones de viaje donde las letras encajan "
        "en un marco rígido se discuten, porque fijar letras firmemente se parece a escribir. Para "
        "las puntuaciones, quienes cuidan la halajá pueden seguir los puntos hojeando las páginas "
        "de un libro (no sagrado) en lugar de escribir. ¡Más información!"
    ),
    "Mafshit": (
        "Aprende la melajá de Mafshit — el acto deliberado de desollar y separar una piel de la "
        "carne — y cómo esta laboriosa separación revela la suspensión total de la transformación "
        "industrial en Shabat. Esta categoría avanzada forma parte de la larga cadena de producción "
        "de cuero, vital para el Mishkan, donde los obreros retiraban pieles de carneros, tahash y "
        "cabras para fabricar las cortinas protectoras del santuario. La definición central de "
        "Mafshit es la separación física de la piel de un animal de su carne o cadáver de manera "
        "productiva. En Shabat, todo acto de desollar, pelar piel para cuero o despojar un cadáver "
        "está estrictamente prohibido. Los detalles de Mafshit también tienen aplicaciones "
        "alimentarias: quitar la piel de un trozo de pollo cocido durante una comida está permitido, "
        "porque es comer y no fabricar cuero. En cambio, con artículos de cuero el sábado, la halajá "
        "considera la separación mecánica de capas pegadas: si un cinturón, una correa o una suela "
        "de cuero empieza a deshilacharse en dos capas distintas, separarlas deliberadamente en "
        "Shabat entra en esta melajá poco conocida. ¡Más información!"
    ),
    "Makeh B'patish": (
        "Descubre la melajá de Makeh B'patish — el golpe final de martillo que completa una "
        "artesanía — y cómo este límite suspende los toques finales en todos nuestros objetos en "
        "Shabat. Esta categoría remonta al Mishkan, donde artesanos daban un último golpe de martillo "
        "sobre vasijas metálicas nuevas para alisar imperfecciones y dejar el objeto plenamente "
        "funcional. La definición central de Makeh B'patish es la acción final intencional que "
        "transforma un objeto incompleto, defectuoso o inutilizable en un producto terminado y listo "
        "para usar. Según la Torá, esto aplica a cualquier oficio: cortar un hilo suelto que cuelga "
        "de una camisa nueva, insertar un tornillo para estabilizar una mesa, enderezar una cuchara "
        "torcida o volver a colocar un cierre desprendido. Igualmente, quitar un clavo peligroso de "
        "una pared para dejar la superficie segura se considera un acabado por reparación. En Shabat, "
        "quienes observan la halajá posponen todas las pequeñas reparaciones, montajes y acabados "
        "hasta después de la Havdalá, disfrutando del entorno tal como estaba preparado antes del "
        "día santo. ¡Más información!"
    ),
    "Matir": (
        "Descubre la melajá de Matir — el acto deliberado de deshacer un nudo — y la fascinante "
        "simetría halájica que determina cuándo abrir un paquete se convierte en trabajo prohibido en "
        "Shabat. Como contraparte directa de Koshair, el desatado remonta al Mishkan, donde los "
        "artesanos deshacían los nudos permanentes de tapices y cuerdas cuando el campamento se "
        "movía. En Shabat, Matir prohíbe deshacer cualquier nudo permanente o a largo plazo. La "
        "regla refleja la del atado: todo nudo cuyo atado la Torá prohíbe también prohíbe desatarlo, "
        "y lo mismo para las prohibiciones rabínicas. Un nudo profesional destinado a permanecer "
        "indefinidamente — cuerda de carga o correa de cuero — no puede deshacerse en Shabat, "
        "aunque se haya atado años antes en semana. Esto afecta la vida cotidiana, desde abrir un "
        "nudo en un paquete de comida hasta cordones enredados. Si un nudo se forma "
        "accidentalmente (en Shabat o antes), en general se es indulgente para deshacerlo, porque "
        "no fue intencional. Atar algo que no debe durar más de veinticuatro horas — como un cordón "
        "simple (no doble) — también está permitido. ¡Más información!"
    ),
    "Mav'ir": (
        "Aprende la melajá de Mav'ir — el acto deliberado de encender o alimentar un fuego — y "
        "descubre cómo este límite suspende nuestro control del calor y la combustión en Shabat. "
        "La Torá la menciona explícitamente; remonta al Mishkan, donde los artesanos encendían fuegos "
        "para fundir metales de las vasijas del Tabernáculo y cocinar ofrendas. La definición central "
        "de Mav'ir es la creación, expansión o alimentación intencional de una llama, chispa o "
        "fuente de calor intenso. Según la Torá, esto incluye encender un fósforo, añadir leña a una "
        "hoguera o pisar el acelerador de un coche de motor de combustión. Mav'ir también introduce "
        "reglas prácticas para la tecnología moderna: la halajá restringe cerrar un circuito "
        "eléctrico para encender un aparato, regular un quemador de gas o enchufar un dispositivo, "
        "porque crear corriente o calentar un elemento imita encender fuego. Esta frontera moldea el "
        "uso de la electricidad, los electrodomésticos y los hoteles. En Shabat, se programan "
        "temporizadores antes del inicio del día, se configuran ollas de cocción lenta antes del "
        "viernes por la noche y se confía en calor y luz ya existentes para honrar el descanso. "
        "¡Más información!"
    ),
    "Me'abeid": (
        "Aprende la melajá de Me'abeid — el antiguo arte de transformar piel cruda en cuero "
        "duradero — y descubre cómo esta melajá modifica incluso nuestra forma de salar alimentos en "
        "Shabat. Esta categoría remonta al Mishkan, donde los obreros trataban pieles con aceites, "
        "sales y baños químicos para ablandarlas, teñirlas y conservarlas en cuero resistente "
        "necesario para los revestimientos exteriores. La definición central de Me'abeid es el "
        "tratamiento físico o químico de materia orgánica cruda para preservarla, endurecerla o "
        "evitar su descomposición. En Shabat, todo acto de curtido, tratamiento de cuero o "
        "ablandamiento de material rígido está prohibido. Me'abeid tiene una subcategoría directa, "
        "Molei'ach (salado): como salar es el primer paso del curtido, salar un material para "
        "modificar su textura entra en la misma categoría. Esto afecta la cocina: salar "
        "abundantemente verduras crudas (pepinos, rábanos, cebollas) para marinarlas se parece al "
        "proceso de conservar una piel. En Shabat, se evita echar mucha sal sobre un bol de verduras "
        "crudas para dejarlas marinar; se prefiere salar justo antes de servir, o mezclar primero "
        "con aceite o vinagre para atenuar el efecto de «curado». La esencia espiritual de Me'abeid: "
        "la humanidad sabe transformar la naturaleza en bienes duraderos, pero Shabat suspende "
        "enteramente esa transformación. ¡Más información!"
    ),
    "Mechabeh": (
        "Aprende la melajá de Mechabeh — el acto deliberado de apagar un fuego — y descubre cómo "
        "este límite suspende nuestro control de llamas y elementos calefactores en Shabat. Remonta "
        "al Mishkan, donde metalúrgicos apagaban brasas para producir carbón vegetal o regular el "
        "calor de los hornos. La definición central de Mechabeh es la extinción, atenuación o "
        "amortiguación intencional de una llama, chispa o fuego. Según la Torá, esto aplica cuando "
        "la extinción es constructiva — crear carbón o conservar una mecha para más tarde. Los Sabios "
        "extendieron la prohibición a toda extinción destructiva. En Shabat, soplar una vela, echar "
        "agua sobre una mecha o apagar un quemador de gas está prohibido. Incluso bajar una llama "
        "para dejar cocinar a fuego lento está restringido, porque atenuar un fuego es una forma de "
        "extinción parcial. Mechabeh moldea el uso de la iluminación y la cocina: se encienden las "
        "velas antes del Shabat y se dejan apagarse solas, se programan temporizadores para la luz "
        "eléctrica y se dejan los quemadores a temperatura fija bajo un blech hasta el final del "
        "Shabat. ¡Más información!"
    ),
    "Mechateich": (
        "Aprende la melajá de Mechateich — el acto deliberado de cortar un material a un tamaño o "
        "forma precisa — y descubre cómo este límite moldea la apertura de paquetes, la preparación "
        "de alimentos y el uso de objetos del hogar en Shabat. Remonta al Mishkan, donde artesanos "
        "medían y cortaban tapices, pieles y vigas a las dimensiones exactas requeridas. La "
        "definición central de Mechateich es el corte, desgarro o recorte intencional de un objeto "
        "funcional a una dimensión, forma o medida precisa con fines productivos. En Shabat, recortar "
        "film plástico a una longitud precisa, cortar un hilo suelto para igualar un borde de tela "
        "o serrar una tabla para una estantería de bricolaje está prohibido. Un ejemplo clásico: "
        "rasgar papel higiénico a lo largo de las perforaciones — obtener una hoja de tamaño medido "
        "viola Mechateich (incluso sin cortar en las líneas, puede aplicarse Koreah). Igualmente, "
        "separar un multipack de yogures por la costura perforada divide el material en unidades de "
        "tamaño preciso. ¡Más información!"
    ),
    "Melaben": (
        "Descubre la melajá de Melaben — el arte del blanqueo y la limpieza de telas — y por qué "
        "no hacemos lavandería ni quitamos manchas en Shabat. Esta categoría remonta al Mishkan, "
        "donde los obreros lavaban y blanqueaban lana y pelo de cabra antes de hilarlos en tapices. "
        "En Shabat, Melaben suspende todo blanqueo, limpieza y refresco de telas, mucho más allá "
        "de la lavadora. Incluso quitar una mancha fresca de un mantel o una camisa puede ser una "
        "violación grave: empapar de inmediato con agua o frotar la mancha con intención de limpiar "
        "es forzar la suciedad fuera de las fibras — Melaben. Las reglas son tan sensibles que "
        "mojar una prenda sucia a veces se considera el inicio del proceso de lavado. ¡Más "
        "información!"
    ),
    "Memachek": (
        "Descubre la melajá de Memachek — el delicado arte de alisar y raspar superficies — y "
        "cómo este límite modifica el uso del jabón, la pasta de dientes y las cremas en Shabat. "
        "Remonta al Mishkan, donde artesanos raspaban pieles crudas para quitar pelos, alisar "
        "asperezas y dejar el cuero uniforme para los revestimientos. La definición central de "
        "Memachek es el alisado, lijado o raspado mecánico de un material rígido — madera, piedra, "
        "metal o cuero — para nivelarlo. En Shabat, lijar un mueble, raspar una correa de cuero o "
        "pulir un arañazo en madera está prohibido. Memachek tiene una contraparte cotidiana "
        "importante, Memarei'ach: alisar sustancias pastosas. Esto afecta la higiene y los cuidados: "
        "extender una capa gruesa de pomada, frotar jabón en barra hasta espuma lisa o presionar una "
        "tira gruesa de pasta dental se parece al nivelado de una superficie. Para evitar este "
        "límite, se usa jabón líquido, aceites o lociones finas que penetran rápido, y se aplica "
        "pomada médica sin extenderla. ¡Más información!"
    ),
    "Menapetz": (
        "Descubre la melajá de Menapetz — el arte de peinar y separar fibras crudas — y cómo una "
        "técnica textil del desierto moldea lo que podemos hacer en Shabat. Remonta al Mishkan, "
        "donde obreros peinaban lana o lino con fuerza para desenredar nudos, separar hebras y "
        "alinearlas antes del hilado. En Shabat, Menapetz prohíbe cualquier acción que imite este "
        "refinamiento industrial de materias enredadas. También afecta el aseo personal: pasar un "
        "cepillo duro por cabello enredado puede arrancar pelos — Gozez (esquila) — ; el espíritu de "
        "Menapetz invita a la suavidad ese día. En lugar de un cepillado fuerte que separa hebras, "
        "se usan cepillos suaves o peines de dientes anchos sobre cabello seco. Una rutina matinal "
        "se convierte en recuerdo del taller del desierto y del profundo descanso del Shabat. ¡Más "
        "información!"
    ),
    "Mesarteit": (
        "Descubre la melajá de Mesarteit — el acto preciso de trazar líneas guía sobre una "
        "superficie — y cómo este límite preparatorio suspende la puesta en marcha física de la "
        "escritura o el corte en Shabat. Remonta al Mishkan, donde escribas y artesanos marcaban "
        "líneas rectas en pergaminos y pieles antes de la tinta, para simetría perfecta y cortes "
        "exactos. La definición central de Mesarteit es marcar, grabar o raspar líneas "
        "intencionalmente sobre un material flexible o sólido para guiar una acción futura — escribir "
        "o cortar un límite preciso. En Shabat, presionar una línea tenue en una página en blanco, "
        "raspar una guía en cuero o marcar un pliegue con regla en papel grueso está prohibido. "
        "Las leyes de Mesarteit también tocan la presentación de alimentos: trazar una línea "
        "profunda sobre un pastel o brownies para guiar cortes futuros, o marcar un patrón de corte "
        "en masa, imita el trazado del pergamino. Para navegar este límite: si cortas el pastel "
        "directamente al rebanar, la línea que hace el cuchillo al pasar está permitida; el "
        "problema es trazar una línea preliminar antes del corte. Esta regla incluso influye en "
        "marcar el jalá antes de Hamotzi: muchos hacen una ligera muesca en el punto de inicio, no "
        "una línea continua en toda la hogaza, para evitar «reglar» una guía de corte. ¡Fascinante! "
        "¡Más información!"
    ),
    "Mocheik": (
        "Descubre la melajá de Mocheik — el acto deliberado de borrar o limpiar marcas "
        "significativas — en Shabat. Remonta al Mishkan, donde escribas borraban o raspaban "
        "cualquier error en vigas o pergaminos para preparar la superficie a una escritura correcta. "
        "La definición central de Mocheik es borrar, raspar, disolver u obliterar intencionalmente "
        "símbolos, letras o gráficos significativos. Según la Torá, esto aplica cuando el borrado es "
        "constructivo — limpiar una superficie para reescribir, como limpiar una pizarra. Los "
        "Sabios también prohíben el borrado destructivo sin reescritura. Este límite guía la "
        "manipulación de materiales escritos el día de descanso: tachar texto, borrar lápiz o "
        "destruir un registro permanente está prohibido. Entre ashkenazim que siguen al Rema, se "
        "evita rasgar letras o logotipos impresos al abrir envases; bedieved o accidentalmente, "
        "está permitido. Entre sefardíes que siguen a Maran Rav Ovadia Yosef, rasgar texto de "
        "envase para acceder a comida o medicamentos está permitido desde el principio, sin "
        "intención de borrar. ¡Más información!"
    ),
    "Oreg": (
        "Descubre la melajá de Oreg — el emblemático arte de tejer hilos juntos — y los fascinantes "
        "límites que separan apreciar la tela de crearla en Shabat. El tejido es la cúspide de la "
        "producción textil, remontando al Mishkan, donde maestros artesanos entrelazaban urdimbre y "
        "trama para las majestuosas tapicerías del santuario. La definición central de Oreg es "
        "entrelazar dos conjuntos distintos de hilos en ángulo recto para formar una tela coherente. "
        "En Shabat, tejer en telar, remendar un agujero entrelazando hilos nuevos o reintegrar un "
        "hilo suelto en una prenda tejida puede violar Oreg. El Talmud enseña que tejer solo dos "
        "hilos horizontales paralelos en una cuadrícula vertical basta para transgredir. Esto "
        "afecta bordado denso, punto de cruz y ciertas cesterías ajustadas, que comparten la "
        "mecánica del telar. La esencia espiritual de Oreg: crear tela es uno de los logros "
        "fundamentales de la humanidad, pero Shabat nos aleja de la fabricación — vestimos nuestra "
        "ropa hermosa sin entrelazar un solo hilo, honrando un día en que el tejido del universo ya "
        "está completo. ¡Más información!"
    ),
    "Oseh Batei Nirin": (
        "Descubre la melajá de Oseh Batei Nirin — el complejo arte de crear lizos, arneses y "
        "lazos en un telar — y cómo la ingeniería textil antigua moldea nuestra comprensión del "
        "descanso del Shabat. En un telar, los hilos verticales de urdimbre pasan por lizos u "
        "ojales fijados a marcos móviles. Al levantar o bajar estos marcos, el tejedor separa los "
        "hilos en dos capas, creando un «shed» (túnel) por donde pasan los hilos de trama. En el "
        "Mishkan, esta configuración era vital para tapicerías a doble cara con motivos geométricos "
        "y animales visibles por ambos lados. La definición central de Oseh Batei Nirin es formar o "
        "instalar estos lazos guía: atar cuerdas para formar ojales, pasar hilos de urdimbre por "
        "lizos existentes o fijar marcos a la mecánica del telar. En Shabat, ensamblar el aparato "
        "de guía de un telar, crear lazos que funcionan como riel para otros hilos o reparar el "
        "aparejo de un telar está prohibido. Como Maisach, esta melajá es calibración estructural "
        "pura al servicio del tejido venidero. Al suspender esta preparación el sábado, la Torá "
        "enseña que el verdadero descanso incluye cesar toda ingeniería preparatoria — armonía con "
        "un mundo ya alineado por el Artífice supremo."
    ),
    "Potze'a": (
        "Aprende la melajá de Potze'a — el acto deliberado de separar, desenredar y deshacer hilos "
        "tejidos — y por qué tirar de un hilo suelto puede violar el descanso del Shabat. Deshacer "
        "estratégicamente una tela es tan creativo como tejerla. Esta categoría remonta al Mishkan, "
        "donde tejedores corregían errores en tapicerías a doble cara o recuperaban secciones "
        "dañadas cortando, desenredando y separando urdimbre y trama. La definición central de "
        "Potze'a es este deshacer constructivo de una estructura tejida o trenzada, para devolver "
        "la tela a hebras utilizables o liberar espacio para un nuevo motivo. En Shabat, deshacer "
        "sistemáticamente una manta tejida, desenredar el borde deshilachado de una tela para "
        "recuperar hilo o separar elementos tejidos de un cesto está prohibido. En la vida "
        "cotidiana, tirar de un hilo colgando del dobladillo de un suéter y deshacer una fila de "
        "puntos o separar fibras de la prenda imita el desmontaje del Mishkan. En Shabat, nos "
        "abstenemos de construir y de desconstruir el mundo material — nuestra ropa permanece tal "
        "cual. ¡Más información!"
    ),
    "Shochait": (
        "Aprende la melajá de Shochait — el acto de sacrificar o quitar la vida a una criatura "
        "viviente — y cómo esta grave prohibición incluso afecta el hilo dental en Shabat. Remonta al "
        "Mishkan, donde animales eran sacrificados para las ofrendas y para tratar sus pieles en "
        "coberturas. La definición fundamental de Shochait es el cese de la vida; en Shabat, cazar, "
        "sacrificar o matar cualquier mamífero, ave, pez o insecto está prohibido (salvo peligro "
        "para la vida humana). Como Shochait concierne la extracción del fluido vital, el Talmud "
        "incluye Chavurah — causar una herida que hace sangrar a un ser vivo. Si alguien tiene "
        "encías sensibles y sabe con certeza que el hilo dental hará sangrar, usarlo en Shabat "
        "violaría la prohibición de herir. Las autoridades determinan que debe evitarse si el "
        "sangrado está garantizado. Shochait enseña profunda reverencia por la vida: en Shabat "
        "dejamos el reino animal en paz y nuestros cuerpos sin herida, confiando en la comida "
        "preparada en semana. ¡Más información!"
    ),
    "Soter": (
        "Descubre la melajá de Soter — el acto deliberado de desmontar o demoler una estructura — "
        "y cómo este límite guía el uso de objetos del hogar, instalaciones temporales y apertura de "
        "contenedores en Shabat. Remonta al Mishkan, donde los levitas desmontaban cuidadosamente "
        "paneles y socles cuando la Nube se levantaba, para transportar y reconstruir en el siguiente "
        "campamento. La definición de Soter es el desmontaje intencional de cualquier estructura, "
        "recipiente o unidad funcional estable. Según la Torá, esto aplica cuando la deconstrucción "
        "es constructiva — reconstruir, mejorar o liberar espacio. Los Sabios también restringen el "
        "desmantelamiento destructivo. Por ejemplo, desmontar un gran toldo exterior o una tienda "
        "multipanel en Shabat puede violar Soter, porque deshacer un refugio cubierto invierte "
        "Boneh. Igualmente, desatornillar por completo una manija suelta o desmontar muebles "
        "modulares firmemente unidos entra en esta restricción. ¡Más información!"
    ),
    "Tofair": (
        "Descubre la melajá de Tofair — el preciso arte de coser — y cómo una sola puntada puede "
        "ser una profunda lección de descanso del Shabat. Remonta al Mishkan, donde artesanos cosían "
        "vastas hojas de lana y pelo de cabra para las cubiertas del santuario y las vestiduras "
        "sacerdotales. La definición central de Tofair es unir dos piezas flexibles — tela, cuero o "
        "papel — en una entidad unificada mediante un elemento de unión: hilo, cuerda o pegamento. "
        "En Shabat, pasar aguja e hilo para remendar una rotura está prohibido. La prohibición "
        "supera la aguja tradicional: cualquier unión duradera y continua entre objetos separados "
        "cuenta — pegamento líquido, cinta adhesiva gruesa o grapadora para un archivo permanente. "
        "En una emergencia de vestimenta el sábado — botón arrancado, dobladillo roto — no se puede "
        "usar cinta ni pegamento, pero un imperdible colocado de forma temporal y no profesional "
        "está permitido. Un incidente menor se convierte en recordatorio consciente: en Shabat, "
        "guardarropa y mundo permanecen tal cual. ¡Más información!"
    ),
    "Tzad": (
        "Aprende la melajá de Tzad — el acto deliberado de atrapar criaturas vivas — y las "
        "fascinantes fronteras halájicas que extienden una tregua total del Shabat hasta los "
        "insectos más pequeños. Remonta al Mishkan, donde cazadores capturaban animales salvajes "
        "para sus pieles y atrapaban caracoles chilazon para el tinte azul sagrado. La definición "
        "fundamental de Tzad es restringir la libertad de una criatura salvaje no domesticada — "
        "mamífero, ave, pez o insecto — colocándola en un espacio cerrado del que ya no puede "
        "escapar fácilmente. En Shabat, echar una red sobre un pez, encerrar un animal en una jaula "
        "o perseguir una criatura para confinarla está prohibido. Esto afecta plagas domésticas: "
        "cubrir una mosca con un vaso o cerrar una caja sobre ella es Tzad — quitarle la libertad "
        "de movimiento. Incluso cerrar ventana o puerta puede ser problemático si un ave salvaje "
        "entró por error. Excepción esencial: Pikuach Nefesh — si una criatura venenosa o una "
        "abeja amenaza directamente la vida, especialmente con alergia mortal, se puede atrapar o "
        "incluso matar el insecto. Fuera de urgencia, los hogares observantes evitan más que "
        "atrapar — ventanas abiertas con cuidado o esperar a que el insecto se vaya. Cerrar la "
        "puerta sobre una mascota domesticada (perro, gato) que viene cuando se la llama está "
        "permitido; las criaturas salvajes quedan libres — en Shabat, retrocedemos ante dominar el "
        "reino animal. ¡Más información!"
    ),
}
