"""Full native-tone rewrites for worst Mitzvah Me alert strings (all langs)."""

from __future__ import annotations

# English key -> {lang: translation}
FULL_REWRITES: dict[str, dict[str, str]] = {
    "Discover the letter Dalet (ד)! 🚪 The shape of this letter teaches us about humility - it's bent over, like someone who is humble. Its name means 'door' in Hebrew, reminding us that humility is the doorway to all spiritual growth. Did you know? The Dalet's numerical value is 4, connecting to the 4 directions - showing how a humble person is open to learning from everyone! Take a moment to practice humility today by learning something new from someone else.": {
        "he": "גלו את האות דלת (ד)! 🚪 הצורה שלה מלמדת על ענווה — כפופה, כמו אדם צנוע. השם שלה «דלת» בעברית מזכיר: ענווה היא הדלת לכל צמיחה רוחנית. ידעתם? הערך הגימטרי של דלת הוא 4, ומחבר לארבע רוחות העולם — אדם צנוע פתוח ללמוד מכולם! היום: תרגלו ענווה — למדו משהו חדש מאדם אחר.",
        "es": "¡Descubre la letra Dalet (ד)! 🚪 Su forma enseña humildad: está inclinada, como quien es modesto. En hebreo significa «puerta» — la humildad es la puerta al crecimiento espiritual. ¿Sabías que? Su valor numérico es 4, como las cuatro direcciones: un alma humilde aprende de todos. Hoy: practica humildad aprendiendo algo nuevo de otra persona.",
        "fr": "Découvre la lettre Dalet (ד) ! 🚪 Sa forme enseigne l'humilité — courbée, comme quelqu'un de modeste. En hébreu, « dalet » veut dire « porte » : l'humilité ouvre toute croissance spirituelle. Tu savais ? Sa valeur est 4, comme les quatre directions — un humble apprend de tout le monde. Aujourd'hui : apprends quelque chose de nouveau à quelqu'un d'autre.",
        "ru": "Открой букву Далет (ד)! 🚪 Её форма учит смирению — она наклонена, как скромный человек. По-ивриту «далет» — «дверь»: смирение — дверь к духовному росту. А знаешь? Числовое значение 4, как четыре стороны света — скромный открыт учению от всех. Сегодня: узнай что-то новое у другого человека.",
    },
    "Discover the letter Nun (נ)! 🌊 The Nun teaches us about loyalty and trust (Ne'emanut). Did you know? Its bent shape (נ) represents a faithful servant, while its final form (ן) represents unwavering dedication. The Talmud reveals that Nun was left out of Ashrei (Psalm 145) because it represents 'falling' (Nofilah), but the next verse speaks of G-d's support - teaching that even in our falls, G-d catches us!": {
        "he": "גלו את האות נון (נ)! 🌊 נון מלמדת על נאמנות (Ne'emanut). ידעתם? הצורה הכפופה (נ) — עבד נאמן; הסופית (ן) — מסירות בלתי מתפשרת. הגמרא: נון הושמטה מאשרי (תהילים קמ״ה) כי מסמלת «נפילה» — והפסוק הבא על תמיכת ה'. גם בנפילות — ה' תופס אותנו!",
        "es": "¡Descubre la letra Nun (נ)! 🌊 Enseña lealtad y confianza (ne'emanut). ¿Sabías que? La forma curva (נ) es un siervo fiel; la final (ן), dedicación firme. El Talmud: Nun falta en Ashrei (Salmo 145) por «caída» — pero el siguiente verso habla del apoyo de D-s. ¡Incluso al caer, Él nos sostiene!",
        "fr": "Découvre la lettre Noun (נ) ! 🌊 Elle enseigne la loyauté (ne'emanout). Tu savais ? La forme courbée (נ) — serviteur fidèle ; la finale (ן) — dévotion sans faille. Le Talmud : Noun manque dans Ashrei (Psaume 145) pour « chute » — mais le vers suivant parle du soutien de D. Même en tombant, Il nous rattrape !",
        "ru": "Открой букву Нун (נ)! 🌊 Она учит верности (ne'emanut). А знаешь? Изогнутая (נ) — верный слуга; конечная (ן) — непоколебимая преданность. Талмуд: Нун выпала из Ашреи (Псалом 145) из-за «падения» — но следующий стих о поддержке В-га. Даже в падении Он нас ловит!",
    },
    "Discover the letter Tav (ת)! 🎯 The last letter of the Alef-Bet represents truth (Emet) and perfection! Did you know? The word Emet (truth) is made up of the first letter (א), middle letter (מ), and last letter (ת) of the Alef-Bet, teaching that truth must be consistent from beginning to end! Today's mission: Make sure your words and actions align with truth.": {
        "he": "גלו את האות תו (ת)! 🎯 האות האחרונה באלף-בית — אמת (Emet) ושלמות. ידעתם? «אמת» בנויה מאלף (א), מם (מ) ותו (ת) — אמת עקבית מההתחלה ועד הסוף! משימה להיום: ודאו שמילים ומעשים תואמים לאמת. כשהלב והמעשה מסונכרים — החיים נעשים ישרים וברורים.",
        "es": "¡Descubre la letra Tav (ת)! 🎯 La última del alef-bet — verdad (emet) y perfección. ¿Sabías que? «Emet» une la primera (א), la del medio (מ) y la última (ת): la verdad es coherente de principio a fin. Reto del día: que tus palabras y actos coincidan con la verdad.",
        "fr": "Découvre la lettre Tav (ת) ! 🎯 Dernière lettre de l'alef-bet — vérité (emet) et perfection. Tu savais ? « Emet » unit la première (א), la médiane (מ) et la dernière (ת) : la vérité va du début à la fin. Défi du jour : aligne tes paroles et tes actes sur la vérité.",
        "ru": "Открой букву Тав (ת)! 🎯 Последняя в алеф-бете — истина (emet) и совершенство. А знаешь? «Эмет» из первой (א), средней (מ) и последней (ת) букв — истина цельна от начала до конца. Задание на сегодня: пусть слова и дела совпадают с истиной.",
    },
    "Discover the letter Tet (ט)! ✡ This amazing letter represents goodness - it's the first letter that appears in the Torah in the word 'Tov' (good)! Did you know? Its shape is curved inward, teaching us that true goodness is often hidden and modest. The numerical value is 9, representing the 9 months of pregnancy - a time when hidden goodness grows! Take a moment today to notice the hidden blessings in your life.": {
        "he": "גלו את האות טית (ט)! ✡ האות הראשונה בתורה במילה «טוב»! ידעתם? הצורה כפופה פנימה — טוב אמיתי לעתים נסתר וצנוע. הערך 9 — תשעה חודשי הריון, זמן שבו טוב נסתר גדל. היום: שימו לב לברכות הנסתרות בחייכם.",
        "es": "¡Descubre la letra Tet (ט)! ✡ ¡La primera letra de «tov» (bueno) en la Torá! ¿Sabías que? Su forma curva hacia adentro enseña que el bien verdadero a veces es oculto y modesto. Valor 9 — nueve meses de embarazo, cuando crece el bien escondido. Hoy: nota las bendiciones ocultas en tu vida.",
        "fr": "Découvre la lettre Tet (ט) ! ✡ La première lettre de « tov » (bon) dans la Torah ! Tu savais ? Sa courbe vers l'intérieur : le vrai bien est souvent caché et modeste. Valeur 9 — neuf mois de grossesse, quand le bien caché grandit. Aujourd'hui : remarque les bénédictions cachées dans ta vie.",
        "ru": "Открой букву Тет (ט)! ✡ Первая буква слова «тов» (добро) в Торе! А знаешь? Форма изогнута внутрь — истинное добро часто скрыто и скромно. Число 9 — девять месяцев беременности, когда растёт скрытое добро. Сегодня: заметь скрытые благословения в жизни.",
    },
    "Discover the letter Vav (ו)! ✡ This amazing letter is shaped like a hook, connecting heaven and earth! Did you know? The letter Vav means 'and', teaching us that everything in creation is connected! Its numerical value is 6, representing the six days of creation. Here's something cool: When you add a Vav to the beginning of a Hebrew word, it transforms future tense to past - showing how G-d transcends time! Take a moment to notice the connections in your life.": {
        "he": "גלו את האות וו (ו)! ✡ כמו וו שמחבר שמיים וארץ! ידעתם? «ו» פירושו «ו» — הכל בבריאה מחובר. הערך 6 — ששת ימי בראשית. וזה מגניב: וו בתחילת מילה הופך עתיד לעבר — ה' מעל הזמן! שימו לב לקשרים בחייכם: משפחה, חברים, מצוות — הכל חוט אחד ארוך.",
        "es": "¡Descubre la letra Vav (ו)! ✡ Como un gancho entre cielo y tierra. ¿Sabías que? «Vav» significa «y» — todo en la creación está conectado. Valor 6 — los seis días de la creación. Y esto mola: un vav al inicio convierte futuro en pasado — ¡D-s trasciende el tiempo! Nota las conexiones en tu vida.",
        "fr": "Découvre la lettre Vav (ו) ! ✡ Comme un crochet entre ciel et terre. Tu savais ? « Vav » veut dire « et » — tout est relié dans la création. Valeur 6 — les six jours de la création. Et c'est cool : un vav au début transforme le futur en passé — D. transcende le temps ! Remarque les liens dans ta vie.",
        "ru": "Открой букву Вав (ו)! ✡ Как крючок между небом и землёй. А знаешь? «Вав» — «и», всё в творении связано. Число 6 — шесть дней творения. И это круто: вав в начале слова меняет будущее на прошедшее — В-г выше времени! Заметь связи в своей жизни.",
    },
    "Discover the letter Zayin (ז)! ✡ This powerful letter looks like a crown with a sword pointing down! Did you know? Zayin means 'weapon' in Hebrew, teaching us that Torah is our spiritual weapon against negativity! Its numerical value is 7, connecting to Shabbat, the 7th day. Here's something amazing: The Zayin's shape teaches us to crown our physical actions with spiritual purpose! Take a moment today to elevate a physical activity with holy intention.": {
        "he": "גלו את האות זין (ז)! ✡ כמו כתר עם חרב למטה! ידעתם? «זין» — נשק; התורה הנשק הרוחני שלנו נגד שליליות. הערך 7 — שבת, היום השביעי. וזה מדהים: צורת הזין מלמדת לעטור מעשים גשמיים בכוונה רוחנית! היום: הרימו פעילות גשמית בכוונה קדושה.",
        "es": "¡Descubre la letra Zayin (ז)! ✡ Como una corona con espada hacia abajo. ¿Sabías que? «Zayin» es «arma» — la Torá es nuestro arma espiritual contra la negatividad. Valor 7 — Shabat, el séptimo día. Y esto es increíble: su forma enseña a coronar lo físico con propósito espiritual. Hoy: eleva una actividad cotidiana con intención santa.",
        "fr": "Découvre la lettre Zaïn (ז) ! ✡ Comme une couronne avec une épée vers le bas. Tu savais ? « Zaïn » veut dire « arme » — la Torah est notre arme spirituelle contre la négativité. Valeur 7 — Shabbat, le septième jour. Et c'est incroyable : sa forme enseigne à couronner l'action physique d'un but spirituel. Aujourd'hui : élève une action du quotidien avec une intention sainte.",
        "ru": "Открой букву Заин (ז)! ✡ Как корона с мечом вниз. А знаешь? «Заин» — «оружие»; Тора — наше духовное оружие против негатива. Число 7 — Шаббат, седьмой день. И это потрясающе: форма Заина учит венчать физические дела духовной целью. Сегодня: возвыси обычное дело святой намерением.",
    },
    "Be an Amen enthusiast! 🗣️ Did you know? Saying Amen to a blessing is confirming that what the first person said is true - the letters alef (א), mem (מ), nun (נ) are an acronym for G-d, King, who is faithful. Confirm that G-d is great and the sages say you steal the show! The Talmud says responding Amen is greater than making the blessing itself. Today's mission: Keep your ears open for blessings and be ready with your spiritual encore - don't miss an Amen! And remember, you're confirming that G-d is great and He does what He says He will do!": {
        "he": "תהיו חובבי אמן! 🗣️ ידעתם? אמירת אמן לברכה מאשרת שהראשון דיבר אמת — האותיות א-מ-נ ראשי תיבות: אלוקים מלך נאמן. חכמינו אומרים שמי שעונה אמן «גונב את ההצגה»! הגמרא: עונֵי אמן גדול ממברך. משימה להיום: אוזניים פתוחות לברכות — אל תפספסו אמן! אתם מאשרים שה' גדול ועושה כהבטחתו.",
        "es": "¡Sé fan del Amén! 🗣️ ¿Sabías que? Decir amén confirma que lo dicho es verdad — א-מ-נ: D-s, Rey, fiel. Los sabios dicen que quien responde amén «roba el show». El Talmud: responder amén es mayor que bendecir. Reto del día: oídos atentos a las bendiciones — ¡no te pierdas un amén! Confirmas que D-s es grande y cumple Su palabra.",
        "fr": "Sois fan de l'Amen ! 🗣️ Tu savais ? Dire amen confirme que c'est vrai — א-מ-נ : D., Roi, fidèle. Les Sages disent que celui qui répond amen « vole la vedette ». Le Talmud : répondre amen est plus grand que bénir. Défi du jour : oreilles ouvertes aux bénédictions — ne rate pas un amen ! Tu confirmes que D. est grand et tient Sa parole.",
        "ru": "Будь фанатом «амен»! 🗣️ А знаешь? «Амен» подтверждает правду сказанного — א-מ-н: В-г, Царь, верный. Мудрецы: отвечающий «амен» «крадёт шоу». Талмуд: «амен» важнее самого благословения. Задание на сегодня: лови благословения — не пропусти «амен»! Ты подтверждаешь, что В-г велик и сдержит слово.",
    },
    "Connect through prayer! 🙏 Did you know? Prayer is our spiritual Wi-Fi connection to G-d! Here's something beautiful: The blessings are prescribed by the sages, who knew how to open heavenly gates using specific words and phrases. By just saying the words in a siddur, our prayers descend to unfathomable heights! Today's mission: Choose one prayer to say with extra concentration and feeling.": {
        "he": "התחברו דרך תפילה! 🙏 ידעתם? התפילה היא ה-Wi-Fi הרוחני שלנו לה'. וזה יפה: הברכות נקבעו על ידי חכמים שידעו לפתוח שערי שמיים במילים מדויקות. רק לומר מילים בסידור — והתפילות עולות לגבהים בלתי נתפסים! משימה להיום: בחרו תפילה אחת בקונצנטרציה ורגש מיוחדים.",
        "es": "¡Conéctate por la oración! 🙏 ¿Sabías que? La tefilá es nuestro Wi-Fi espiritual con D-s. Y esto es hermoso: los sabios fijaron las bendiciones con palabras que abren puertas celestiales. Solo decir las palabras del sidur — ¡y suben a alturas insondables! Reto del día: elige una oración con concentración y emoción extra.",
        "fr": "Connecte-toi par la prière ! 🙏 Tu savais ? La tefila, c'est notre Wi-Fi spirituel avec D. Et c'est beau : les Sages ont fixé les bénédictions avec des mots qui ouvrent les portes du ciel. Dire les mots du siddour — et la prière monte très haut ! Défi du jour : choisis une prière avec concentration et émotion.",
        "ru": "Соединись через молитву! 🙏 А знаешь? Тефила — наш духовный Wi-Fi к В-гу. И это прекрасно: мудрецы задали благословения словами, открывающими небесные врата. Произнеси слова из сидура — и молитва взлетает на невообразимую высоту! Задание на сегодня: выбери одну молитву с особой сосредоточенностью.",
    },
    "Walk in G-d's ways! 👣 The Rambam reveals in Hilchot Deot: Just as G-d is merciful, you should be merciful. Just as He is gracious, you should be gracious. Just as He is holy, you should be holy. Here's the key: Find the middle path in all your traits - not too harsh, not too soft. Today's mission: Pick one divine attribute (kindness, holiness, or mercy) and really focus on becoming it!": {
        "he": "לכו בדרכי ה'! 👣 הרמב\"ם בהלכות דעות: כשם שה' רחום — היו רחמים; חנון — חנונים; קדוש — קדושים. והנה המפתח: דרך האמצע — לא קשים מדי, לא רכים מדי. משימה להיום: בחרו תכונה אלוקית אחת (חסד, קדושה או רחמים) והתמקדו לפתח אותה!",
        "es": "¡Camina en los caminos de D-s! 👣 El Rambam en Hilchot Deot: como D-s es misericordioso, sé misericordioso; bondadoso, bondadoso; santo, santo. La clave: el camino medio — ni duro ni blando. Reto del día: elige un atributo divino (bondad, santidad o misericordia) y enfócate en cultivarlo.",
        "fr": "Marche dans les voies de D. ! 👣 Le Rambam dans Hilchot Deot : comme D. est miséricordieux, sois miséricordieux ; gracieux, gracieux ; saint, saint. La clé : la voie du milieu — ni dur ni mou. Défi du jour : choisis un attribut divin (bonté, sainteté ou miséricorde) et travaille-le vraiment.",
        "ru": "Иди путями В-га! 👣 Рамбам в Хилхот Деот: как В-г милосерден — будь милосерден; благ — благ; свят — свят. Вот ключ: золотая середина — не жёсткий, не мягкий. Задание на сегодня: выбери одно божественное качество (доброта, святость или милосердие) и развивай его.",
    },
    "Unlock the power of Hebrew letters! 📚 Today's special letter: Bet (ב) - the first letter of the Torah! Did you know? Its shape teaches us three amazing lessons: 1) It's closed on three sides but open in front - showing that we can't look 'behind' to what was before creation 2) It faces forward - teaching us to always move forward in life 3) Its numerical value is 2 - reminding us that the physical world was created with duality (heaven/earth, good/evil) but all serves one purpose! ✡": {
        "he": "פתחו את כוח האותיות העבריות! 📚 האות של היום: בית (ב) — האות הראשונה בתורה! ידעתם? שלושה לקחים: 1) סגור משלושה צדדים, פתוח קדימה — אין להסתכל «אחורה» לפני הבריאה 2) פונה קדימה — תמיד להתקדם 3) ערך 2 — העולם נברא בדואליות (שמיים/ארץ, טוב/רע) לתכלית אחת! ✡",
        "es": "¡Desbloquea el poder de las letras hebreas! 📚 Letra del día: Bet (ב) — ¡la primera de la Torá! ¿Sabías que? Tres lecciones: 1) Cerrada por tres lados, abierta al frente — no mires «atrás» antes de la creación 2) Mira adelante — sigue avanzando 3) Valor 2 — el mundo con dualidad (cielo/tierra, bien/mal) para un solo propósito. ✡",
        "fr": "Débloque le pouvoir des lettres hébraïques ! 📚 Lettre du jour : Bet (ב) — la première de la Torah ! Tu savais ? Trois leçons : 1) Fermée de trois côtés, ouverte devant — ne regarde pas « derrière » avant la création 2) Vers l'avant — avance toujours 3) Valeur 2 — le monde en dualité (ciel/terre, bien/mal) pour un seul but. ✡",
        "ru": "Открой силу еврейских букв! 📚 Буква дня: Бет (ב) — первая в Торе! А знаешь? Три урока: 1) Закрыта с трёх сторон, открыта впереди — не смотри «назад» до творения 2) Смотри вперёд — всегда двигайся 3) Число 2 — мир с дуальностью (небо/земля, добро/зло) для одной цели. ✡",
    },
    "Practice Hitbodedut — talk to Hashem in your own words! 🌳 Did you know Rabbi Nachman of Breslov taught that this is among the 'highest levels' of prayer? Hitbodedut is setting aside dedicated time (ideally in a quiet, private place like a field or forest, or even just your room!) to speak intimately with Hashem, just like you would with your best friend. Pour out your heart in your native language about anything and everything – your worries, dreams, gratitude, questions, or just your day. Rabbi Nachman emphasized that this unscripted, spontaneous prayer 'rises to a very high place' and creates tremendous spiritual delight and connection. Even 5-10 minutes a day can transform your spiritual life! Source: Likutei Moharan II, 25; Rabbi Nachman's Teachings.": {
        "he": "תרגלו התבודדות — דברו עם ה' במילים שלכם! 🌳 ידעתם? רבי נחמן מברסלב לימד שזו מדרגות העליונות של התפילה. התבודדות: זמן ייעודי (בשדה, ביער או בחדר) לדבר אינטימית עם ה', כמו עם חבר הכי טוב. שפכו לב בשפתכם — דאגות, חלומות, הכרת תודה, שאלות, היום שלכם. תפילה ספונטנית «עולה למקום גבוה מאוד». 5–10 דקות ביום יכולות לשנות את החיים הרוחניים!",
        "es": "¡Practica hitbodedut — habla con Hashem con tus palabras! 🌳 ¿Sabías que? El Rabí Najmán de Breslov enseñó que es de los niveles más altos de oración. Reserva tiempo (campo, bosque o tu cuarto) para hablar íntimamente con Hashem, como con tu mejor amigo. Vierte el corazón en tu idioma — preocupaciones, sueños, gratitud, preguntas, tu día. Esta oración espontánea «sube muy alto». ¡5–10 minutos al día pueden transformar tu vida espiritual!",
        "fr": "Pratique le hitbodedout — parle à Hachem avec tes mots ! 🌳 Tu savais ? Le rabbi Nahman de Breslev l'a enseigné parmi les plus hauts niveaux de prière. Du temps à part (champ, forêt ou ta chambre) pour parler intimement à Hachem, comme à ton meilleur ami. Déverse ton cœur dans ta langue — soucis, rêves, gratitude, questions, ta journée. Cette prière spontanée « monte très haut ». 5–10 minutes par jour peuvent transformer ta vie spirituelle !",
        "ru": "Практикуй хитбодедут — говори с Шем в своих словах! 🌳 А знаешь? Рабби Нахман из Бреслова учил: это из высших ступеней молитвы. Выдели время (поле, лес или комната), чтобы говорить с Шемом интимно, как с лучшим другом. Излей сердце на своём языке — заботы, мечты, благодарность, вопросы, свой день. Спонтанная молитва «восходит очень высоко». 5–10 минут в день могут изменить духовную жизнь!",
    },
    "Rise above superstition! 🎲 The Rambam explains in Chapter 10 that we shouldn't base decisions on 'lucky signs' or omens. Here's something powerful: Instead of relying on superstitions, we should trust in G-d! Did you know? Even if a sign 'works' multiple times, we still shouldn't rely on it. Today's challenge: Make decisions based on wisdom and faith, not superstition.": {
        "he": "התרוממו מעל כישוף! 🎲 הרמב\"ם בפרק י: לא לקבל החלטות לפי «סימנים מזליים» או מנבאים. וזה חזק: במקום כישוף — בוטחים בה'! ידעתם? גם אם סימן «עובד» כמה פעמים — לא סומכים עליו. אתגר להיום: החלטות מחוכמה ואמונה, לא מכישוף.",
        "es": "¡Sup0erar la superstición! 🎲 El Rambam, cap. 10: no decidas por «señales de suerte» u augurios. Y esto es poderoso: en vez de superstición — confía en D-s. ¿Sabías que? Aunque un signo «funcione» varias veces, no confíes en él. Reto del día: decide con sabiduría y fe, no con superstición.",
        "fr": "Dépasse la superstition ! 🎲 Le Rambam, ch. 10 : ne décide pas selon des « signes de chance » ou présages. Et c'est puissant : plutôt que la superstition — fais confiance à D. Tu savais ? Même si un signe « marche » plusieurs fois, ne t'y fie pas. Défi du jour : décide avec sagesse et foi, pas superstition.",
        "ru": "Поднимись над суеверием! 🎲 Рамбам, гл. 10: не решай по «счастливым знакам» и приметам. И это мощно: вместо суеверий — доверяй В-гу! А знаешь? Даже если знак «срабатывает» — не полагайся на него. Вызов на сегодня: решения из мудрости и веры, не из суеверий.",
    },
}

# Fix typo in Spanish Rise above
FULL_REWRITES[
    "Rise above superstition! 🎲 The Rambam explains in Chapter 10 that we shouldn't base decisions on 'lucky signs' or omens. Here's something powerful: Instead of relying on superstitions, we should trust in G-d! Did you know? Even if a sign 'works' multiple times, we still shouldn't rely on it. Today's challenge: Make decisions based on wisdom and faith, not superstition."
]["es"] = (
    "¡Supera la superstición! 🎲 El Rambam, cap. 10: no decidas por «señales de suerte» u augurios. "
    "Y esto es poderoso: en vez de superstición — confía en D-s. ¿Sabías que? Aunque un signo «funcione» "
    "varias veces, no confíes en él. Reto del día: decide con sabiduría y fe, no con superstición."
)

_MORE: dict[str, dict[str, str]] = {
    "Discover the power of Resh (ר)! 👑 This letter teaches us about leadership - it stands for 'Rosh' (head). Did you know? Its shape shows someone bent in humility, teaching that true leadership comes through serving others. The gap in its top shows that even a leader must remain open to learning from others. Today's mission: Practice being both a good leader and a good follower.": {
        "he": "גלו את כוח האות ריש (ר)! 👑 מלמדת על מנהיגות — «ראש». ידעתם? הצורה — אדם כפוף בענווה: מנהיגות אמיתית דרך שירות לאחרים. הפער בראש — גם מנהיג פתוח ללמוד מאחרים. משימה להיום: תהיו מנהיגים וגם עוקבים טובים.",
        "es": "¡Descubre el poder de Resh (ר)! 👑 Enseña liderazgo — «rosh» (cabeza). ¿Sabías que? Su forma es alguien humilde: el verdadero liderazgo es servir. La brecha arriba — incluso un líder sigue aprendiendo. Reto del día: sé buen líder y buen seguidor.",
        "fr": "Découvre la puissance de Resh (ר) ! 👑 Elle enseigne le leadership — « rosh » (tête). Tu savais ? Sa forme courbée : le vrai leadership, c'est servir. L'espace en haut — même un chef reste ouvert à apprendre. Défi du jour : sois bon leader et bon suiveur.",
        "ru": "Открой силу буквы Реш (ר)! 👑 Она о лидерстве — «рош» (голова). А знаешь? Форма — склонённый в смирении: истинное лидерство через служение. Просвет сверху — лидер учится у других. Задание на сегодня: будь хорошим лидером и последователем.",
    },
    "Discover the power of the Mezuzah! 🚪 Did you know? It's like a Divine security system for your home! Sages say that when a destructive force wants to hurt someone, if it sees a kosher mezuzah on that person's doorpost, it will get scared by G-d's name which is written on it and run away.": {
        "he": "גלו את כוח המזוזה! 🚪 ידעתם? כמו מערכת אבטחה אלוקית לבית! חכמים: כוח הרסני שרוצה לפגוע — רואה מזוזה כשרה על המשקוף, נבהל משם ה' שכתוב בה ובורח. בכל כניסה ויציאה — נשיקה או מגע — מזכירים את השמע ואחדות ה'.",
        "es": "¡Descubre el poder de la mezuzá! 🚪 ¿Sabías que? ¡Como un sistema de seguridad divino para tu hogar! Los sabios: una fuerza destructiva ve una mezuzá kosher en el marco — se asusta del Nombre de D-s escrito y huye.",
        "fr": "Découvre le pouvoir de la mezouza ! 🚪 Tu savais ? Comme un système de sécurité divin pour ta maison ! Les Sages : une force destructrice voit une mezouza casher sur le montant — effrayée par le Nom de D. écrit dessus, elle fuit.",
        "ru": "Открой силу мезузы! 🚪 А знаешь? Как божественная охрана для дома! Мудрецы: разрушительная сила видит кошерную мезузу на косяке — пугается Имени В-га на ней и убегает.",
    },
    "Understand the depth of Ayin (ע)! 👁️ The letter Ayin means 'eye' and has the numerical value of 70, representing different perspectives (like the 70 faces of Torah). Its shape teaches us to look deeper than surface appearances. Did you know? The Ayin in the Shema is traditionally written larger, reminding us to be witnesses (see with our eyes) G-d's unity.": {
        "he": "העמיקו באות עין (ע)! 👁️ «עין» — עין; ערך 70 — שבעים פנים לתורה. הצורה מלמדת לראות מעבר לשטח. ידעתם? העין בשמע נכתבת גדולה — להיות עדים (בעיניים) לאחדות ה'.",
        "es": "¡Profundiza en Ayin (ע)! 👁️ «Ayin» es «ojo»; valor 70 — setenta caras de la Torá. Su forma enseña a mirar más allá de la superficie. ¿Sabías que? El ayin del Shemá se escribe grande — ser testigos (con los ojos) de la unidad de D-s.",
        "fr": "Plonge dans Ayin (ע) ! 👁️ « Ayin » veut dire « œil » ; valeur 70 — soixante-dix faces de la Torah. Sa forme : voir au-delà des apparences. Tu savais ? L'ayin du Shema s'écrit grand — témoigner (des yeux) de l'unité de D.",
        "ru": "Познай глубину Аин (ע)! 👁️ «Аин» — «глаз»; число 70 — семьдесят граней Торы. Форма учит видеть глубже поверхности. А знаешь? Аин в Шма пишут крупнее — быть свидетелем (глазами) единства В-га.",
    },
    "Meet the towering Lamed (ל)! 🗼 This unique letter reaches higher than all others, representing the aspiration to reach beyond our limits! Did you know? Lamed means 'learn' and 'teach' - showing that true learning should lead to teaching others! Its shape suggests a tower pointing heavenward, reminding us to always strive higher in our spiritual growth. Today's challenge: Learn something new and share it with someone else.": {
        "he": "הכירו את למד (ל) הגבוה! 🗼 מגיע גבוה מכל האותיות — שאיפה מעבר לגבולות. ידעתם? «למד» — ללמוד וללמד: לימוד אמיתי מוביל להוראה! כמו מגדל לשמיים. אתגר להיום: למדו משהו חדש ושתפו עם מישהו.",
        "es": "¡Conoce al imponente Lamed (ל)! 🗼 Más alto que todas — aspirar más allá de los límites. ¿Sabías que? «Lamed» — aprender y enseñar: el estudio lleva a enseñar. Como una torre al cielo. Reto del día: aprende algo nuevo y compártelo.",
        "fr": "Découvre le Lamed (ל) imposant ! 🗼 Plus haut que toutes — aspirer au-delà des limites. Tu savais ? « Lamed » — apprendre et enseigner : l'étude mène à transmettre. Comme une tour vers le ciel. Défi du jour : apprends quelque chose de neuf et partage-le.",
        "ru": "Познакомься с высоким Ламед (ל)! 🗼 Выше всех букв — стремление за пределы. А знаешь? «Ламед» — учиться и учить: знание ведёт к передаче. Как башня к небу. Вызов на сегодня: узнай новое и поделись с кем-то.",
    },
    "Set your Torah time and guard it! ⏰ The sages emphasize that regular Torah learning - even short sessions - builds powerful long-term growth. Choose a realistic daily slot and keep it! It could be just a few minutes if you have a busy schedule, or several hours if you really want to reach 'Mitz Mode!' Did you know? According to the Talmud, when a person's soul reaches Heaven, one of the very first questions they are asked is: “Did you set fixed times for learning Torah?”": {
        "he": "קבעו זמן תורה ושמרו עליו! ⏰ חכמים: לימוד קבוע — אפילו קצר — בונה צמיחה ארוכת טווח. בחרו משבצת יומית ריאלית ושמרו! יכול להיות דקות בודדות או שעות ל«מצב מצווה». ידעתם? בגמרא: כשהנשמה עולה לשמים — מהשאלות הראשונות: «קבעת עיתים לתורה?»",
        "es": "¡Fija tu hora de Torá y cuídala! ⏰ Los sabios: estudio regular — aunque breve — construye crecimiento a largo plazo. Elige un hueco diario realista y manténlo. Pueden ser minutos o horas para «Mitz Mode». ¿Sabías que? El Talmud: al llegar al cielo, una de las primeras preguntas es: «¿Fijaste tiempos para estudiar Torá?»",
        "fr": "Fixe ton heure de Torah et garde-la ! ⏰ Les Sages : étude régulière — même courte — construit une croissance durable. Choisis un créneau quotidien réaliste et tiens-le. Quelques minutes ou des heures pour le « Mitz Mode ». Tu savais ? Le Talmud : en montant au ciel, on demande : « As-tu fixé des moments pour la Torah ? »",
        "ru": "Задай время для Торы и береги его! ⏰ Мудрецы: регулярное учение — даже короткое — даёт рост надолго. Выбери реальный ежедневный слот и держись его. Минуты или часы для «Mitz Mode». А знаешь? Талмуд: на небесах одним из первых вопросов: «Установил ли ты время для Торы?»",
    },
    "Unite in prayer! Take a moment to pray for Klal Yisrael (the Jewish people) 🌍. Ask for peace, safety, health, and prosperity for our brothers and sisters worldwide. Did you know? When we pray for the entire Jewish nation, our individual prayers become even more powerful! It's like joining a worldwide spiritual group hug 🤗.": {
        "he": "התאחדו בתפילה! קחו רגע להתפלל על כלל ישראל 🌍 — שלום, ביטחון, בריאות ושגשוג לאחים ואחיות בכל העולם. ידעתם? כשמתפללים על כל העם — התפילות האישיות מתחזקות! כמו חיבוק רוחני עולמי 🤗.",
        "es": "¡Únete en oración! Ora un momento por Klal Israel 🌍 — paz, seguridad, salud y prosperidad para hermanos y hermanas en todo el mundo. ¿Sabías que? Al orar por toda la nación, ¡tus oraciones personales se fortalecen! Como un abrazo espiritual mundial 🤗.",
        "fr": "Unis-toi dans la prière ! Prie un instant pour Klal Israël 🌍 — paix, sécurité, santé et prospérité pour nos frères et sœurs partout. Tu savais ? Prier pour toute la nation renforce tes prières personnelles ! Comme un câlin spirituel mondial 🤗.",
        "ru": "Объединись в молитве! Помолись о Клал Исраэль 🌍 — о мире, безопасности, здоровье и благополучии братьев и сестёр по всему миру. А знаешь? Молясь за весь народ, личные молитвы становятся сильнее! Как всемирные духовные объятия 🤗.",
    },
    "Actively oppose idolatry! 🔨 The Rambam explains in Chapter 7 that we have a positive commandment to destroy items of idol worship and everything used for it. Here's something powerful: We don't just avoid idol worship - we actively work to eliminate it! Did you know? Even the wood and stones from an idol must be destroyed. Today's mission: Take an active stand against false beliefs in your life.": {
        "he": "התנגדו פעילות לעבודה זרה! 🔨 הרמב\"ם בפרק ז: מצווה להשמיד כלי עבודה זרה וכל מה שנעשה לשמה. וזה חזק: לא רק להימנע — לפעול להסרה! ידעתם? גם עץ ואבנים מעבודה זרה חייבים השמדה. משימה להיום: עמדה פעילה נגד אמונות שקר בחייכם.",
        "es": "¡Oponte activamente a la idolatría! 🔨 El Rambam, cap. 7: mitzvá de destruir objetos de culto idólatra y todo lo usado para ello. Y esto es poderoso: no solo evitar — ¡actuar para eliminar! ¿Sabías que? Hasta madera y piedras del ídolo deben destruirse. Reto del día: postura activa contra creencias falsas en tu vida.",
        "fr": "Oppose-toi activement à l'idolâtrie ! 🔨 Le Rambam, ch. 7 : mitzva de détruire les objets de culte idolâtre et tout ce qui sert à cela. Et c'est puissant : ne pas seulement éviter — agir pour éliminer ! Tu savais ? Même bois et pierres d'une idole doivent être détruits. Défi du jour : position active contre les fausses croyances dans ta vie.",
        "ru": "Активно противостой идолопоклонству! 🔨 Рамбам, гл. 7: мицва уничтожать предметы идолопоклонства и всё для него. И это мощно: не только избегать — действовать! А знаешь? Даже дерево и камни от идола должны быть уничтожены. Задание на сегодня: активная позиция против ложных убеждений в жизни.",
    },
    "Actively oppose idolatry! 🔨 The Rambam explains in Chapter 7 that we have a positive commandment to destroy items of idol worship and everything used for it. Here's something powerful: We don't just avoid idol worship - we actively work to eliminate it! Did you know? Even the wood and stones from an idol must be destroyed. Today's mission: Take an active stand against negative influences in your life.": {
        "he": "התנגדו פעילות לעבודה זרה! 🔨 הרמב\"ם בפרק ז': מצווה להשמיד כלי עבודה זרה. לא רק להימנע — לפעול להסרה! ידעתם? גם עץ ואבנים מעבודה זרה — השמדה. משימה: עמדה פעילה נגד השפעות שליליות.",
        "es": "¡Oponte activamente a la idolatría! 🔨 El Rambam, cap. 7: mitzvá de destruir objetos de culto idólatra. No solo evitar — ¡actuar para eliminar! ¿Sabías que? Hasta madera y piedras del ídolo deben destruirse. Reto del día: postura activa contra influencias negativas en tu vida.",
        "fr": "Oppose-toi activement à l'idolâtrie ! 🔨 Le Rambam, ch. 7 : mitzva de détruire les objets de culte idolâtre. Pas seulement éviter — agir pour éliminer ! Tu savais ? Même bois et pierres d'une idole doivent être détruits. Défi du jour : position active contre les influences négatives dans ta vie.",
        "ru": "Активно противостой идолопоклонству! 🔨 Рамбам, гл. 7: мицва уничтожать предметы идолопоклонства. Не только избегать — действовать! А знаешь? Даже дерево и камни от идола должны быть уничтожены. Задание на сегодня: активная позиция против негативных влияний в жизни.",
    },
    "Celebrate the gift of joy! Take a moment to thank G-d for your ability to laugh and smile 😊. Whether it's from a good joke, time with friends, or a funny moment - laughter is G-d's special medicine for the soul. Did you know? The Talmud tells us that a person who brings joy to others is rewarded greatly! 🎭": {
        "he": "חגגו את מתנת השמחה! קחו רגע להודות לה' על היכולת לצחוק ולחייך 😊. בדיחה טובה, זמן עם חברים או רגע מצחיק — צחוק הוא תרופת הנשמה של ה'. ידעתם? הגמרא: מי שמביא שמחה לאחרים — מתוגמל בגדולה! 🎭",
        "es": "¡Celebra el regalo de la alegría! Agradece a D-s por poder reír y sonreír 😊. Un buen chiste, amigos o un momento gracioso — la risa es medicina especial del alma. ¿Sabías que? El Talmud: quien trae alegría a otros — gran recompensa. 🎭",
        "fr": "Célèbre le don de la joie ! Remercie D. de pouvoir rire et sourire 😊. Une bonne blague, des amis ou un moment drôle — le rire est le remède spécial de l'âme. Tu savais ? Le Talmud : qui apporte de la joie aux autres — grande récompense. 🎭",
        "ru": "Празднуй дар радости! Поблагодари В-га за способность смеяться и улыбаться 😊. Шутка, друзья или смешной момент — смех лекарство для души. А знаешь? Талмуд: приносящий радость другим — великая награда. 🎭",
    },
    "Crown yourself with Torah! 👑 The Rambam teaches that a Jewish king must write TWO Torah scrolls - one for his treasury and one that never leaves his side! Here's the amazing lesson: No matter how powerful or busy you are, Torah should be your constant companion! Did you know? The king would read from his Torah scroll every day, teaching us to make daily Torah study a priority! Your mission: Set a fixed time for Torah study, even if it's just a few minutes.": {
        "he": "התכתרו בתורה! 👑 הרמב\"ם: מלך יהודי כותב שני ספרי תורה — אחד לאוצר ואחד שלא עוזב אותו! והנה השיעור המדהים: כמה שאתם עסוקים — התורה רעיה קבועה! ידעתם? המלך קרא מספר התורה מדי יום. המשימה שלכם: זמן קבוע ללימוד, אפילו דקות.",
        "es": "¡Corónate con la Torá! 👑 El Rambam: un rey judío escribe dos rollos — uno para el tesoro y otro que no lo deja. La lección increíble: por ocupado que estés, la Torá es compañera constante. ¿Sabías que? El rey leía su rollo cada día. Tu reto: tiempo fijo para estudio, aunque sean minutos.",
        "fr": "Couronne-toi de Torah ! 👑 Le Rambam : un roi juif écrit deux rouleaux — un pour le trésor, un qui ne le quitte jamais. La leçon incroyable : aussi occupé que tu sois, la Torah reste compagne. Tu savais ? Le roi lisait son rouleau chaque jour. Ton défi : un moment fixe pour l'étude, même quelques minutes.",
        "ru": "Увенчай себя Торой! 👑 Рамбам: еврейский царь пишет два свитка — один для сокровищницы, другой не покидает его. Урок потрясающий: как бы ты ни был занят — Тора рядом. А знаешь? Царь читал свиток каждый день. Твоё задание: фиксированное время для учения, хоть минуты.",
    },
    "Discover the deeper meaning of the beard in Judaism! 🧔 Did you know? Kabbalists say that the 13 attributes of Divine mercy can emanate through the hairs of the beard! Now that's what I call a valuable hairloom.": {
        "he": "גלו את המשמעות העמוקה של הזקן ביהדות! 🧔 ידעתם? קבליסטים אומרים שי\"ג מידות הרחמים יכולות להתגלות דרך שערות הזקן! זו באמת ירושה שיערית יקרת ערך — סמל של קדושה, בגרות וכבוד למסורת. גם אם אין לכם זקן — הערכה למנהג הזה מחזקת את הקשר לעם ישראל.",
        "es": "¡Descubre el significado profundo de la barba en el judaísmo! 🧔 ¿Sabías que? Los cabalistas dicen que las 13 atributos de misericordia pueden emanar por los pelos de la barba. ¡Eso sí que es una herencia «peluda» valiosa!",
        "fr": "Découvre le sens profond de la barbe dans le judaïsme ! 🧔 Tu savais ? Les kabbalistes disent que les 13 attributs de miséricorde peuvent émaner par les poils de la barbe. Voilà un héritage « poilu » précieux !",
        "ru": "Открой глубокий смысл бороды в иудаизме! 🧔 А знаешь? Каббалисты говорят: 13 атрибутов милосердия могут исходить через волосы бороды. Вот это я называю ценной «волосатой» реликвией!",
    },
    "Double your love! ❤️ The Rambam explains two beautiful mitzvot: loving fellow Jews and showing special love to converts. Why the extra love for converts? They chose to join our people and follow Torah - that's amazing! Here's something practical: Make an extra effort today to show love to another Jew through action - whether they were born Jewish or chose to join our people!": {
        "he": "הכפילו את האהבה! ❤️ הרמב\"ם מסביר שתי מצוות יפות: אהבת ישראל ואהבה מיוחדת לגרים. למה אהבה נוספת לגרים? הם בחרו להצטרף לעמנו וללכת בתורה — מדהים! היום — מאמץ נוסף להפגין אהבה ליהודי אחר במעשה, נולד יהודי או בחר להצטרף.",
        "es": "¡Duplica el amor! ❤️ El Rambam explica dos mitzvot hermosas: amar a los judíos y amor especial a los conversos. ¿Por qué más amor a los conversos? Eligieron unirse a nuestro pueblo y seguir la Torá — ¡increíble! Algo práctico: hoy, esfuerzo extra por mostrar amor a otro judío en acción — nacido judío o converso.",
        "fr": "Double ton amour ! ❤️ Le Rambam explique deux belles mitzvot : aimer les Juifs et un amour spécial pour les convertis. Pourquoi plus d'amour pour les convertis ? Ils ont choisi de rejoindre notre peuple et la Torah — incroyable ! Concrètement : aujourd'hui, effort en plus pour montrer de l'amour à un autre Juif par l'action — né juif ou converti.",
        "ru": "Удвой любовь! ❤️ Рамбам объясняет две прекрасные мицвы: любовь к евреям и особая любовь к герам. Почему больше любви к герам? Они выбрали наш народ и Тору — потрясающе! Практично: сегодня — лишнее усилие показать любовь другому еврею делом — от рождения или гер.",
    },
}

FULL_REWRITES.update(_MORE)

_MORE2: dict[str, dict[str, str]] = {
    "Connect with Psalm 6! 🙏 Did you know? This powerful psalm is one of the Tehillim often recited for healing! Here's something amazing: King David teaches us how to pour out our hearts to G-d in times of distress. Today's mission: Recite this psalm with feeling, especially when praying for someone who is ill.": {
        "he": "התחברו לתהילים ו'! 🙏 ידעתם? מזמור עוצמתי מן התהילים לרפואה! וזה מדהים: דוד המלך מלמד לשפוך לב לפני ה' בצרה. משימה להיום: אמרו את המזמור ברגש, במיוחד כשמתפללים על חולה — הלב הפתוח מגיע רחוק ומקרב את התפילה לשמיים.",
        "es": "¡Conéctate con el Salmo 6! 🙏 ¿Sabías que? Un salmo poderoso de Tehilim para la sanación. Y esto es increíble: el rey David enseña a derramar el corazón ante D-s en la angustia. Reto del día: recítalo con sentimiento, especialmente por alguien enfermo.",
        "fr": "Connecte-toi au Psaume 6 ! 🙏 Tu savais ? Un psaume puissant des Tehilim pour la guérison. Et c'est incroyable : le roi David enseigne à déverser son cœur devant D. dans la détresse. Défi du jour : récite-le avec émotion, surtout pour un malade.",
        "ru": "Соединись с Псалмом 6! 🙏 А знаешь? Мощный псалом из Техилим для исцеления. И это потрясающе: царь Давид учит изливать сердце перед В-гом в беде. Задание на сегодня: читай с чувством, особенно о больном.",
    },
    "Dive into Psalm 3 of Tehillim! 📖 Did you know? This powerful psalm was composed by King David when fleeing from his own son Absalom! Here's something amazing: Even in his darkest moment, David found strength in his faith. The psalm teaches us that G-d is our shield and protector, no matter how many opponents we face! Today's mission: Read this psalm and find your own strength in times of challenge.": {
        "he": "צללו לתהילים ג'! 📖 ידעתם? דוד המלך חיבר אותו בבריחה מפני בנו אבשלום! וזה מדהים: גם ברגע החשוך ביותר — כוח באמונה. המזמור מלמד: ה' מגן ומגן, כמה יריבים שיהיו! משימה להיום: קראו ומצאו כוח בזמני אתגר.",
        "es": "¡Sumérgete en el Salmo 3 de Tehilim! 📖 ¿Sabías que? David lo compuso huyendo de su hijo Absalón. Y esto es increíble: incluso en su momento más oscuro — fortaleza en la fe. El salmo enseña: D-s es escudo y protector. Reto del día: léelo y encuentra fuerza en tiempos difíciles.",
        "fr": "Plonge dans le Psaume 3 des Tehilim ! 📖 Tu savais ? David l'a composé en fuyant son fils Absalom. Et c'est incroyable : même dans son heure la plus sombre — force dans la foi. Le psaume enseigne : D. est bouclier et protecteur. Défi du jour : lis-le et trouve ta force dans l'épreuve.",
        "ru": "Погрузись в Псалом 3 из Техилим! 📖 А знаешь? Давид написал его, бегя от сына Авшалома. И это потрясающе: даже в самый тёмный момент — сила в вере. Псалом учит: В-г — щит и защитник. Задание на сегодня: читай и находи силу в трудные времена.",
    },
    "Understand true and false prophecy! 🔮 The Rambam reveals something fascinating in Chapter 10: If a prophet predicts something bad will happen and it doesn't - that doesn't make them false! Why? Because G-d is merciful and might cancel the decree if people repent, just like with Nineveh. But here's the key: If a prophet predicts something good and it doesn't happen, they're definitely false! Because G-d never cancels good prophecies (except once, during the First Temple's destruction). Today's mission: Remember that G-d's mercy can always override negative decrees.": {
        "he": "הבינו נבואה אמיתית ושקרית! 🔮 הרמב\"ם בפרק י: נביא שחזה רעה שלא באה — לא בהכרח שקרי! למה? ה' רחום ועלול לבטל גזירה בתשובה, כמו בנינוה. והנה המפתח: חזה טובה שלא באה — בהכרח שקרי! ה' לא מבטל נבואות טובות (חוץ מפעם אחת, בחורבן הבית הראשון). משימה להיום: רחמי ה' יכולים לבטל גזירות שליליות.",
        "es": "¡Entiende la profecía verdadera y la falsa! 🔮 El Rambam, cap. 10: si un profeta predice mal y no ocurre — ¡no es falso! ¿Por qué? D-s es misericordioso y puede cancelar el decreto con arrepentimiento, como en Nínive. La clave: predice bien y no ocurre — ¡falso! D-s no cancela profecías buenas (salvo una vez, en la destrucción del Primer Templo). Reto del día: la misericordia de D-s puede anular decretos negativos.",
        "fr": "Comprends la vraie et la fausse prophétie ! 🔮 Le Rambam, ch. 10 : un prophète annonce du mal qui n'arrive pas — pas forcément faux ! Pourquoi ? D. est miséricordieux et peut annuler le décret par le repentir, comme à Ninive. La clé : annonce du bien qui n'arrive pas — faux ! D. n'annule pas les bonnes prophéties (sauf une fois, à la destruction du Premier Temple). Défi du jour : la miséricorde de D. peut annuler les décrets négatifs.",
        "ru": "Пойми истинное и ложное пророчество! 🔮 Рамбам, гл. 10: пророк предсказал зло, а оно не случилось — не обязательно ложный! Почему? В-г милосерден и может отменить указ при покаянии, как в Ниневии. Вот ключ: предсказал добро, а оно не сбылось — точно ложный! В-г не отменяет добрые пророчества (кроме одного раза, при разрушении Первого Храма). Задание на сегодня: милость В-га может отменить негативные указы.",
    },
    "Rise above revenge! 🌅 The Torah teaches us something powerful: Don't take revenge, even when you have the chance! Here's a classic example: If someone refused to lend you something, and later they ask to borrow from you - don't say 'No, just like you did to me!' Instead, help them! Did you know? This mitzvah helps us become more like G-d, who gives good even to those who don't deserve it. Today's challenge: Do something nice for someone who wasn't nice to you.": {
        "he": "התרוממו מעל נקמה! 🌅 התורה מלמדת משהו חזק: אל תקחו נקמה, גם כשיש הזדמנות! דוגמה קלאסית: מישהו סירב להלוות — ואחר כך מבקש ממך? אל תגידו «לא, כמו שעשית לי!» — עזרו! ידעתם? המצווה הזו מקרבת להיות כמו ה', שנותן טוב גם למי שלא ראוי. אתגר להיום: עשו טוב למי שלא היה נחמד אליכם.",
        "es": "¡Supera la venganza! 🌅 La Torá enseña algo poderoso: no te vengues, aunque puedas. Un ejemplo clásico: alguien no te prestó — y luego te pide? No digas «¡no, como tú a mí!» — ¡ayúdalo! ¿Sabías que? Esta mitzvá nos acerca a ser como D-s, que da bien incluso a quien no lo merece. Reto del día: haz algo bueno por quien no fue amable contigo.",
        "fr": "Dépasse la vengeance ! 🌅 La Torah enseigne quelque chose de puissant : ne te venge pas, même si tu le peux. Exemple classique : quelqu'un refuse de te prêter — puis te demande ? Ne dis pas « non, comme tu as fait ! » — aide-le ! Tu savais ? Cette mitzva nous rapproche de D., qui donne du bien même à qui ne le mérite pas. Défi du jour : fais du bien à quelqu'un qui n'a pas été gentil avec toi.",
        "ru": "Поднимись над местью! 🌅 Тора учит: не мсти, даже когда можешь. Классический пример: кто-то не одолжил — а потом просит у тебя? Не говори «нет, как ты мне!» — помоги! А знаешь? Эта мицва приближает к В-гу, дающему добро даже незаслуженным. Вызов на сегодня: сделай добро тому, кто был груб с тобой.",
    },
    "Meet the miraculous Samech (ס)! 🔄 The Samech's shape holds a secret: Unlike other letters, it's completely enclosed - teaching about G-d's encompassing protection. Did you know? The Talmud says it miraculously floated in the Tablets of the Ten Commandments! Since the tablets were engraved all the way through, as a circle its inside had no connection to the Tablet! Today's challenge: Feel G-d's protective presence surrounding you": {
        "he": "הכירו את סמך (ס) הנסי! 🔄 סוד הצורה: בניגוד לאותיות אחרות — סגורה לגמרי, על הגנת ה' הסובבת. ידעתם? הגמרא: נסית צפה בלוחות עשרת הדיברות! הלוחות חקוקים משני הצדדים — כעיגול, הפנים לא מחובר ללוח! אתגר להיום: חושו בהגנת ה' מסביבכם.",
        "es": "¡Conoce al milagroso Samej (ס)! 🔄 Su forma guarda un secreto: a diferencia de otras letras, está totalmente cerrada — la protección envolvente de D-s. ¿Sabías que? El Talmud: flotaba milagrosamente en las Tablas de los Diez Mandamientos. Reto del día: siente la presencia protectora de D-s rodeándote.",
        "fr": "Découvre le Samekh (ס) miraculeux ! 🔄 Sa forme cache un secret : contrairement aux autres lettres, elle est totalement fermée — la protection enveloppante de D. Tu savais ? Le Talmud : elle flottait miraculeusement dans les Tables des Dix Commandements. Défi du jour : sens la présence protectrice de D. autour de toi.",
        "ru": "Познакомься с чудесным Самех (ס)! 🔄 Секрет формы: в отличие от других букв, полностью замкнута — всеобъемлющая защита В-га. А знаешь? Талмуд: чудесно парил на Скрижалях Десяти Заповедей. Вызов на сегодня: почувствуй защитное присутствие В-га вокруг себя.",
    },
    "Meet the holy Kuf (ק)! 👣 This unique letter teaches about holiness and physicality. Its shape - like someone walking - shows how we must bring holiness into our physical actions. Did you know? The word Kadosh (holy) starts with Kuf, teaching that true holiness means elevating the physical world, not escaping it! Today's mission: Make one physical activity holy by doing it mindfully for a higher purpose": {
        "he": "הכירו את קוף (ק) הקדוש! 👣 אות ייחודית על קדושה וגשמיות. הצורה — כמו הולך — מראה איך להכניס קדושה למעשים גשמיים. ידעתם? «קדוש» מתחיל בקוף — קדושה אמיתית מרימה את העולם הגשמי, לא בורחת ממנו! משימה להיום: הפכו פעילות גשמית אחת לקדושה בכוונה גבוהה.",
        "es": "¡Conoce al santo Kuf (ק)! 👣 Letra única sobre santidad y lo físico. Su forma — como quien camina — muestra cómo traer santidad a lo físico. ¿Sabías que? «Kadosh» (santo) empieza con Kuf: la santidad verdadera eleva lo físico, no escapa de él. Reto del día: haz santa una actividad física con intención elevada.",
        "fr": "Découvre le Kouf (ק) saint ! 👣 Lettre unique sur sainteté et physicalité. Sa forme — comme quelqu'un qui marche — montre comment amener la sainteté dans l'action physique. Tu savais ? « Kadosh » (saint) commence par Kouf : la vraie sainteté élève le monde physique, ne s'en échappe pas. Défi du jour : rends sainte une action physique par une intention élevée.",
        "ru": "Познакомься со святым Куф (ק)! 👣 Уникальная буква о святости и физическом. Форма — как идущий — показывает, как вносить святость в физические дела. А знаешь? «Кадош» (святой) начинается с Куф: истинная святость возвышает физический мир, а не убегает от него. Задание на сегодня: возвыси одно физическое дело святой целью.",
    },
    "Explore the mighty Aleph (א)! ✡ The first letter of the Alef-Bet represents G-d's oneness and unity! Did you know? Its shape is made of a Vav (ו) with two Yuds (י), representing heaven above and earth below, connected by G-d's presence! The numerical value is 1, teaching us about G-d's absolute unity. Today's mission: Notice how G-d connects heaven and earth in your daily life.": {
        "he": "גלו את האלף (א) העוצמתי! ✡ האות הראשונה — אחדות ה'. ידעתם? הצורה: וו (ו) עם שני יודים (י) — שמיים וארץ, מחוברים בנוכחות ה'. ערך 1 — אחדות מוחלטת. משימה להיום: שימו לב איך ה' מחבר שמיים וארץ בחיי היום.",
        "es": "¡Explora el poderoso Alef (א)! ✡ La primera letra — la unidad de D-s. ¿Sabías que? Su forma: Vav (ו) con dos Yud (י) — cielo y tierra unidos por la presencia de D-s. Valor 1 — unidad absoluta. Reto del día: nota cómo D-s conecta cielo y tierra en tu día a día.",
        "fr": "Explore l'Alef (א) puissant ! ✡ La première lettre — l'unité de D. Tu savais ? Sa forme : Vav (ו) avec deux Yod (י) — ciel et terre reliés par la présence de D. Valeur 1 — unité absolue. Défi du jour : remarque comment D. relie ciel et terre dans ton quotidien.",
        "ru": "Исследуй могучий Алеф (א)! ✡ Первая буква — единство В-га. А знаешь? Форма: Вав (ו) с двумя Йуд (י) — небо и земля, связанные присутствием В-га. Число 1 — абсолютное единство. Задание на сегодня: заметь, как В-г соединяет небо и землю в повседневности.",
    },
    "Take a Shabbat prep course! Did you know that preparing for Shabbat is itself a special mitzvah? Halacha teaches us that the actions we take before Shabbat are imbued with special holiness. Pick one prep mission today: maybe setting the table beautifully, cooking a special dish, finding special Shabbat clothes, or tidying your home. Each act, done with the intention of honoring Shabbat, transforms mundane tasks into mitzvot. It's like building a spiritual ramp to welcome the Queen Shabbat! Source: Rambam, Hilchot Shabbat 30:1; Shulchan Aruch, Orach Chaim 250.": {
        "he": "קורס הכנה לשבת! ידעתם? ההכנה לשבת היא מצווה בפני עצמה! ההלכה: מעשים לפני שבת נטועים בקדושה מיוחדת. בחרו משימת הכנה היום: שולחן יפה, מנה מיוחדת, בגדי שבת או סידור הבית. כל מעשה לכבוד שבת — מצווה. כמו רמפה רוחנית לקבלת מלכת השבת!",
        "es": "¡Curso de prep para Shabat! ¿Sabías que? Preparar Shabat es mitzvá en sí. La halajá: los actos previos llevan santidad especial. Elige una misión hoy: mesa bonita, plato especial, ropa de Shabat o ordenar la casa. Cada acto para honrar Shabat — mitzvá. ¡Como una rampa espiritual para recibir a la Reina Shabat!",
        "fr": "Cours de préparation pour Shabbat ! Tu savais ? Préparer Shabbat est une mitzva en soi. La halakha : les actes d'avant Shabbat portent une sainteté spéciale. Choisis une mission aujourd'hui : belle table, plat spécial, vêtements de Shabbat ou ranger la maison. Chaque acte pour honorer Shabbat — mitzva. Comme une rampe spirituelle pour accueillir la Reine Shabbat !",
        "ru": "Курс подготовки к Шаббату! А знаешь? Подготовка к Шаббату — сама по себе мицва! Галаха: дела перед Шаббатом наполнены особой святостью. Выбери задание сегодня: красивый стол, особое блюдо, одежда для Шаббата или уборка. Каждое дело для чести Шаббата — мицва. Как духовный пандус для встречи Царицы Шаббата!",
    },
}

FULL_REWRITES.update(_MORE2)
