"""Hand-authored full Cyrillic RU rewrites for worst Latin-heavy catalog keys."""

from __future__ import annotations

MANUAL_RU_DEEP: dict[str, str] = {
    "Jewish law applies in the marketplace and office just as in the synagogue. Honest weights, fair deals, and trustworthy conduct are Torah obligations — not optional \"extra credit.\"\n\nWhat this includes:\n• Geneivat da'at (גְּנֵבַת דַּעַת — deception): misleading a customer or employer about price, quality, terms, or your qualifications.\n• Ona'ah (אוֹנָאָה): overcharging or underpaying when the other party does not know the fair value. A variation of one-sixth or more above or below fair market price triggers the Torah laws of financial fraud, requiring the overcharged amount to be fully refunded.\n• Keeping your word: honoring agreements, deadlines, and commitments; not making promises you cannot keep.\n• Paying workers on time: wages owed must be paid when due (Leviticus 19:13).\n• Not stealing in any form — including time theft, expense fraud, or taking what is not yours.\n• Taxes and debts: fulfilling legal obligations honestly; not cheating the government or private parties.\n\nKey idea:\n\"In righteousness you shall judge your fellow\" (Leviticus 19:15) — business dealings are judged by the same moral standard as ritual mitzvot. A Jew's integrity (yosher — יֹשֶׁר) is a sanctification of G-d's name in the world.\n\nHow to practice:\n• Be transparent in sales, billing, and negotiations.\n• When in doubt, ask a rabbi or trusted advisor about a specific contract or industry practice.\n• Treat employees, clients, and employers with the dignity the Torah demands.\n\nCheck this off as a daily intention to act with honesty in all financial and professional interactions.":
        "Еврейский закон действует на рынке и в офисе так же, как в синагоге. Честные весы, справедливые сделки и надёжное поведение — обязательства Торы, а не «дополнительные баллы».\n\nЧто сюда входит:\n• Генейват даат (גְּנֵבַת דַּעַת — обман): вводить клиента или работодателя в заблуждение о цене, качестве, условиях или вашей квалификации.\n• Онаа (אוֹנָאָה): завышать или занижать цену, когда другая сторона не знает справедливой стоимости. Разница в одну шестую и более от рыночной цены запускает законы Торы о финансовом обмане и требует полного возврата переплаты.\n• Держать слово: соблюдать договоры, сроки и обязательства; не обещать того, что не сможете выполнить.\n• Платить работникам вовремя: зарплата должна выплачиваться в срок (Ваикра 19:13).\n• Не воровать ни в какой форме — включая кражу времени, махинации с расходами или присвоение чужого.\n• Налоги и долги: честно выполнять юридические обязательства; не обманывать государство и частных лиц.\n\nГлавная идея:\n«В праведности будешь судить ближнего своего» (Ваикра 19:15) — деловые отношения оцениваются по тому же нравственному стандарту, что и ритуальные мицвот. Честность еврея (йошер — יֹשֶׁר) — это освящение имени В-га в мире.\n\nКак применять:\n• Будьте прозрачны в продажах, счетах и переговорах.\n• При сомнениях спросите рава или доверенного советника о конкретном договоре или отраслевой практике.\n• Относитесь к сотрудникам, клиентам и работодателям с достоинством, которого требует Тора.\n\nОтметьте это как ежедневное намерение действовать честно во всех финансовых и профессиональных делах.",
    "Chabad (Alter Rebbe / Arizal): haircut and shaving restrictions continue the entire 49 days through Erev Shavuot — adults do not take haircuts on Lag BaOmer (the sole exception is upsherin for a 3-year-old boy). Lag BaOmer is a day of intense joy with music, bonfires, and celebration, but haircut restrictions remain until Shavuot.\n\nMusic is generally avoided through Shavuot per Chabad practice, with Lag BaOmer as a day without music restrictions. Weddings follow your Chabad rabbi's guidance.\n\nAsk your Chabad rabbi for details on your community.":
        "Хабад (Альтер Ребе / Аризаль): ограничения на стрижку и бритьё действуют все 49 дней до Эрева Шавуота — взрослые не стригутся и в Лаг ба-Омер (единственное исключение — апшерин для трёхлетнего мальчика). Лаг ба-Омер — день радости с музыкой, кострами и праздником, но запрет на стрижку сохраняется до Шавуота.\n\nПо обычаю Хабада музыку обычно избегают до Шавуота; в Лаг ба-Омер музыкальных ограничений нет. Свадьбы — по указанию вашего рава Хабада.\n\nУточните детали для вашей общины у рава Хабада.",
    "Spread some smiles: Say a kind word! 🗣️👂 The mitzvah of greeting people with warmth and kindness (Hachnassat Orchim - welcoming guests, and general acts of chesed) is a daily opportunity to brighten someone's day immeasurably! A genuine smile, a friendly 'Shalom,' or a thoughtful word of encouragement can transform someone's experience. The Sages teach that even a small act of kindness has profound spiritual value. Who in your life could use a word of upliftment today? Make it your mission to spread some positivity!":
        "Разделите улыбки: скажите доброе слово! 🗣️👂 Мицва тёплого приветствия и доброты (ахнасат орхим — приём гостей и акты хесед) — ежедневная возможность неизмеримо осветлить чей-то день! Искренняя улыбка, дружелюбное «Шалом» или ободряющее слово могут изменить чужой опыт. Мудрецы учат: даже маленький акт доброты имеет глубокую духовную ценность. Кому в вашей жизни сегодня нужна поддержка? Сделайте своей миссией разделить позитив!",
    "ona'ah — Overcharging or underpaying when the other party does not know the fair value. A variation of one-sixth or more above or below fair market price triggers the Torah laws of financial fraud (Bava Metzia 49b), requiring the overcharged amount to be fully refunded. Honest business is a mitzvah; \"everyone does it\" does not excuse geneivat da'at or ona'ah.":
        "онаа — переплата или недоплата, когда другая сторона не знает справедливой цены. Отклонение на шестую и более от рыночной цены запускает законы Торы о финансовом обмане (Бава Меция 49б) и требует полного возврата переплаты. Честный бизнес — мицва; «все так делают» не оправдывает генейват даат или онаа.",
    "Be a peacemaker: Make peace between people! 🕊️ The mitzvah of Rodef Shalom (pursuing peace) is one of the greatest mitzvot in Judaism, described as one of the things 'a person eats its fruits in this world, and the principal remains for him in the World to Come.' (Peah 1:1). Whether it's helping to resolve an argument between friends, encouraging acceptance between different groups, or simply diffusing tension in a conversation, peacemaking is an act that brings immense spiritual reward. The Talmud (Sanhedrin 6b) praises those who pursue peace. Look for a small opportunity today to bring harmony into your environment, be it at home, at work, or in your community. Even a gentle word can make a huge difference!":
        "Будьте миротворцем: установите мир между людьми! 🕊️ Мицва родеф шалом (стремление к миру) — одна из величайших; о ней сказано: «человек вкушает плоды в этом мире, а основной капитал остаётся для него в мире грядущем» (Пеа 1:1). Помочь друзьям помириться, сблизить разные группы или снять напряжение в разговоре — всё это приносит огромную духовную награду. Талмуд (Санхедрин 6б) восхваляет тех, кто гоняется за миром. Найдите сегодня маленькую возможность принести гармонию — дома, на работе или в общине. Даже мягкое слово может многое изменить!",
    "Chazal (חז\"ל) is an acronym for \"our Sages of blessed memory\" — the rabbis of the Mishnah, Talmud, and midrash who transmitted halacha and values. When a source says \"Chazal teach,\" it refers to this collective tradition rather than a single author.":
        "Хазал (חז\"ל) — аббревиатура «наши мудрецы, да будет благословенна их память» — раввины Мишны, Талмуда и мидраша, передавшие галаху и ценности. Когда источник говорит «Хазал учат», речь об этой коллективной традиции, а не об одном авторе.",
    "Saw a lost object recently? 🔍 Don't just ignore it! Go back and try to return it to its owner (if possible). That's the mitzvah of Hashavat Aveidah (returning lost objects). The Torah teaches that if you see your fellow's animal or belongings wandering off, you may not look away — you must make an effort to return them. Our sages devoted entire discussions to this mitzvah: how hard you must try, what you can keep as a reward for your trouble, and why restoring someone's property is also restoring their dignity.":
        "Недавно видели потерянную вещь? 🔍 Не проходите мимо! Вернитесь и постарайтесь отдать владельцу (если возможно). Это мицва ашават авейда — возврат потерянного. Тора учит: если вы видите, как блуждает скот или имущество соседа, нельзя отвернуться — нужно приложить усилия, чтобы вернуть. Мудрецы посвятили целые обсуждения этой мицве: насколько усердно стараться, что можно оставить себе в награду за труд и почему возвращение чужого имущества — это также возвращение достоинства.",
    "shmirat halashon — guarding one's speech from lashon hara and harmful words":
        "шмират hалашон — оберегать речь от лашон hара и вредных слов",
    "shmirat halashon":
        "«шмират hалашон»",
    "Online languages use Google Translate. Quality varies.":
        "Онлайн-языки используют «Гугл Переводчик». Качество может отличаться.",
    "yad soledet bo — Yad soledet bo (\"when the hand recoils\") is the heat threshold for bishul on Shabbat — roughly 110–113°F (43–45°C). Food already fully cooked may sometimes be reheated dry on Shabbat; liquids are stricter. This is why a blech keeps food warm without reaching cooking temperature.":
        "яд соледет бо — «когда рука отдёргивается» — порог температуры для бишула в Шаббат, примерно 43–45 °C (110–113 °F). Уже полностью приготовленную еду иногда можно сухо разогреть в Шаббат; с жидкостями строже. Поэтому блех держит еду тёплой, не доводя до температуры готовки.",
    "Yad soledet bo (\"when the hand recoils\") is the heat threshold for bishul on Shabbat — roughly 110–113°F (43–45°C). Food already fully cooked may sometimes be reheated dry on Shabbat; liquids are stricter. This is why a blech keeps food warm without reaching cooking temperature.":
        "Яд соледет бо («когда рука отдёргивается») — порог температуры для бишула в Шаббат, примерно 43–45 °C (110–113 °F). Уже полностью приготовленную еду иногда можно сухо разогреть в Шаббат; с жидкостями строже. Поэтому блех держит еду тёплой, не доводя до температуры готовки.",
    "Shehecheyanu (Sephardic — Shulchan Arukh O.C. 692:1; Yalkut Yosef): Recite only before the first evening Megillah reading. Do not repeat Shehecheyanu at the daytime reading — the blessing from the night covers the entire holiday; repeating it in the daytime is a bracha levatala.":
        "Шехехияну (сефарды — Шулхан Арух О.Х. 692:1; Ялкут Йосеф): произносить только перед первым вечерним чтением Мегиллы. Не повторяйте Шехехияну при дневном чтении — ночное благословение охватывает весь праздник; повторение днём — браха леватала.",
    "Yahrzeit is the annual Hebrew-calendar date of a relative's death. Many light a 24-hour candle, visit the grave, give charity, and lead services if they are a kohen or know the customs. Parents' yahrzeits are especially observed. The name means \"time of year\" in Yiddish — a day to remember and elevate the soul.":
        "Ярцайт — годовщина смерти родственника по еврейскому календарю. Многие зажигают 24-часовую свечу, посещают могилу, дают цдаку и ведут службу, если они коэн или знают обычаи. Особенно соблюдают ярцайты родителей. Название на идише означает «время года» — день поминовения и возвышения души.",
    "refuah shleimah — complete healing; said when praying for someone ill":
        "рефуа шлема — полное исцеление; произносится при молитве за больного",
    "birchat hamapil":
        "«брахат hамапиль»",
    "assur bemelacha":
        "«асур бэмелаха»",
    "Pikuach nefesh — Pikuach nefesh (saving life) overrides Shabbat and almost all mitzvot. Call emergency services, drive to hospital, and carry medicine when life is at risk. Doctors and nurses have detailed halacha for their shifts — but a layperson should never hesitate to save life. After the danger passes, ask your rav about what you did.":
        "Пикуах нефеш — спасение жизни — отменяет Шаббат и почти все мицвот. Звоните в экстренные службы, езжайте в больницу, носите лекарства, когда жизнь под угрозой. У врачей и медсестёр есть подробная галаха для смен — но мирянин никогда не должен колебаться спасать жизнь. Когда опасность минует, спросите рава о том, что вы сделали.",
    "netilat yadayim — Netilat yadayim is ritual handwashing with a cup (keli). Morning washing removes ruach ra'ah after sleep: pour water three times on each hand in alternating sequence (right, left, right, left, right, left). Before bread, pour two or three times consecutively on each hand to purify for eating.":
        "нетилат ядаим — ритуальное омовение рук из чаши (кели). Утреннее омовение убирает руах раа после сна: наливай воду три раза на каждую руку поочерёдно (право, лево, право, лево, право, лево). Перед хлебом — два или три раза подряд на каждую руку.",
    "borei nefashot — Borei nefashot is the short after-blessing on many foods and drinks — fruit (aside from dates, grapes, olives, figs, and pomegranates which use the Me'ein Shalosh bracha), vegetables, drinks (other than wine/grape juice which use Me'ein Shalosh), meat, cheese, etc.":
        "борей нефашот — короткое послеблагословение на многие продукты и напитки: фрукты (кроме фиников, винограда, оливок, инжира и гранатов — там Меэйн Шалош), овощи, напитки (кроме вина и виноградного сока), мясо, сыр и т.д.",
    "borei nefashot":
        "«борей нефашот»",
    "mayim achronim":
        "«маим ахроним»",
    "bitachon — Bitachon is trust in G-d — believing that He provides what you need and that hardship can have purpose even when you cannot see it. It is related to emunah (faith) but stresses calm reliance in daily worry. Mussar and Chasidut both teach practical bitachon.":
        "битахон — доверие В-гу: вера, что Он даёт необходимое и что трудности могут иметь смысл, даже когда вы его не видите. Связано с эмуной, но подчёркивает спокойную опору в ежедневных заботах. И мусар, и хасидут учат практическому битахону.",
    "Targum Onkelos — Targum Onkelos is the Aramaic translation of the Torah read in Shnayim Mikra v'Echad Targum. It was taught at Ezra's time to understand Torah. One who finds Onkelos difficult may substitute Rashi's commentary for the third reading (O.C. 285:2). Some use an accurate English translation instead.":
        "Таргум Онкелос — арамейский перевод Торы, читаемый в Шнайим Микра в'Эхад Таргум. Его учили во времена Эзры для понимания Торы. Кому трудно — может заменить третье чтение комментарием Раши (О.Х. 285:2). Некоторые используют точный перевод на родном языке.",
    "Targum Onkelos is the Aramaic translation of the Torah read in Shnayim Mikra v'Echad Targum. It was taught at Ezra's time to understand Torah. One who finds Onkelos difficult may substitute Rashi's commentary for the third reading (O.C. 285:2). Some use an accurate English translation instead.":
        "Таргум Онкелос — арамейский перевод Торы, читаемый в Шнайим Микра в'Эхад Таргум. Его учили во времена Эзры для понимания Торы. Кому трудно — может заменить третье чтение комментарием Раши (О.Х. 285:2). Некоторые используют точный перевод на родном языке.",
    "trop — Trop (ta'amei hamikra) are the cantillation marks above and below Hebrew in a Chumash that tell the baal koreh how to chant Torah — melody and phrase breaks. Learning trop is a skill separate from understanding the words. Congregants follow the chant in their books during the reading.":
        "троп (таамей hа-микра) — знаки кантилляции над и под текстом в Хумаше, по которым бааль коре читает Тору с мелодией и паузами. Изучение тропа — отдельный навык от понимания слов. Прихожане следят по книгам во время чтения.",
    "Trop (ta'amei hamikra) are the cantillation marks above and below Hebrew in a Chumash that tell the baal koreh how to chant Torah — melody and phrase breaks. Learning trop is a skill separate from understanding the words. Congregants follow the chant in their books during the reading.":
        "Троп (таамей hа-микра) — знаки кантилляции над и под текстом в Хумаше, по которым бааль коре читает Тору с мелодией и паузами. Изучение тропа — отдельный навык от понимания слов. Прихожане следят по книгам во время чтения.",
    "Tanya — The Tanya is Rabbi Schneur Zalman of Liadi's foundational Chabad work on the Jewish soul, divine service, and practical mysticism. Its full Hebrew name is Likutei Amarim (\"collected sayings\"). Chabad's daily Chitas program includes a portion of Tanya each day alongside Chumash and Tehillim. You can read it in Hebrew or English on Sefaria.":
        "Тания — основополагающий труд раввина Шнеура Залмана из Лиади о еврейской душе, божественной службе и практическом мистицизме. Полное название на иврите — Ликутей Амарим («собранные изречения»). Ежедневная программа Хитас включает порцию Тании вместе с Хумашем и Техиллим. Можно читать на иврите или английском на Sefaria.",
    "The Tanya is Rabbi Schneur Zalman of Liadi's foundational Chabad work on the Jewish soul, divine service, and practical mysticism. Its full Hebrew name is Likutei Amarim (\"collected sayings\"). Chabad's daily Chitas program includes a portion of Tanya each day alongside Chumash and Tehillim. You can read it in Hebrew or English on Sefaria.":
        "Тания — основополагающий труд раввина Шнеура Залмана из Лиади о еврейской душе, божественной службе и практическом мистицизме. Полное название на иврите — Ликутей Амарим («собранные изречения»). Ежедневная программа Хитас включает порцию Тании вместе с Хумашем и Техиллим. Можно читать на иврите или английском на Sefaria.",
    "Birkat Ha'Ilanot":
        "Биркат hа-Иланот",
    "Birkat Ha'Ilanot — Blessing on Fruit Trees":
        "Биркат hа-Иланот — благословение на плодовые деревья",
    "Mah Nishtanah":
        "«ма ништана»",
    "patur — Patur means exempt from a particular mitzvah in a given situation — for example, someone ill on Yom Kippur from fasting, or a child before bar mitzvah. Patur is not \"off the hook\" morally; it means the obligation does not apply to you now. A different mitzvah or leniency may apply instead.":
        "патур — освобождение от конкретной мицвы в данной ситуации — например, больной в Йом Кипур от поста или ребёнок до бар-мицва. Патур — не «сходишь с крючка» морально; обязательство просто не применяется к вам сейчас. Вместо этого может действовать другая мицва или послабление.",
    "Patur means exempt from a particular mitzvah in a given situation — for example, someone ill on Yom Kippur from fasting, or a child before bar mitzvah. Patur is not \"off the hook\" morally; it means the obligation does not apply to you now. A different mitzvah or leniency may apply instead.":
        "Патур означает освобождение от конкретной мицвы в данной ситуации — например, больной в Йом Кипур от поста или ребёнок до бар-мицва. Это не моральная «отмазка»; обязательство просто не применяется к вам сейчас. Вместо этого может действовать другая мицва или послабление.",
    "Modah — feminine form of Modeh (grateful) in Modeh Ani":
        "Мода — женская форма «моде» (благодарный) в «Модэ ани»",
    "Amen — Amen affirms a bracha someone else recited, \"so may it be.\" The Talmud praises one who answers Amen even more than the one who made the blessing. It should not be rushed or mumbled; it is a small but constant mitzvah opportunity in synagogue and at home. (Literally, it's an acronym for 'G-d, King Who is faithful' — Keil Melech Ne'eman).":
        "Амен подтверждает браху, произнесённую другим — «так да будет». Талмуд хвалит отвечающего «амен» даже больше, чем благословляющего. Не торопитесь и не бубните — это маленькая, но постоянная мицва в синагоге и дома. (Дословно акроним «Б-г, Царь, Который верен» — Кейл Мелех Неэман).",
    "Amen affirms a bracha someone else recited, \"so may it be.\" The Talmud praises one who answers Amen even more than the one who made the blessing. It should not be rushed or mumbled; it is a small but constant mitzvah opportunity in synagogue and at home. (Literally, it's an acronym for 'G-d, King Who is faithful' — Keil Melech Ne'eman).":
        "«Амен» подтверждает браху, произнесённую другим — «так да будет». Талмуд хвалит отвечающего «амен» даже больше, чем благословляющего. Не торопитесь и не бубните — это маленькая, но постоянная мицва в синагоге и дома. (Дословно акроним «Б-г, Царь, Который верен» — Кейл Мелех Неэман).",
    "Borei pri hagafen is the blessing on wine and grape juice — \"Who creates the fruit of the vine.\" It is required before Kiddush, the four cups at the Seder, and drinking wine for simcha. After the blessing, drink a meaningful amount (revi'it per many poskim). Ordinary table grapes use a different blessing.":
        "Борей при hагафен — благословение на вино и виноградный сок: «Который создаёт плод лозы». Нужно перед Киддушем, четырьмя чашами на Седере и вином для симхи. После благословения выпейте значимое количество (ревиит по мнению многих посеким). Обычный столовый виноград — с другой брахой.",
    "Tap into ancient wisdom! 📚 Open Pirkei Avot (Ethics of the Fathers) and learn one teaching that speaks to you. These are instructions and life lessons passed down through generations of sages! Pick any chapter and find practical life wisdom that's just as relevant today as it was hundreds or thousands of years ago!":
        "Погрузитесь в древнюю мудрость! 📚 Откройте Пиркей Авот (Этика отцов) и изучите одно учение, которое вам откликается. Это наставления и жизненные уроки, передававшиеся поколениями мудрецов! Выберите любую главу и найдите практическую мудрость, столь же актуальную сегодня, как сотни или тысячи лет назад!",
    "Do the mitzvah of praying for others! Take a moment to think of someone who needs healing (refuah shleimah) 🙏. Did you know? The Hebrew word for prayer (tefillah) comes from the root word l'hitpallel- meaning 'to judge oneself.' When we pray for others, we become more compassionate people ourselves!":
        "Выполните мицву молиться за других! Найдите момент подумать о ком-то, кому нужно исцеление (рефуа шлема) 🙏. Знаете ли? Слово «тфила» происходит от корня леhитпалель — «судить себя». Когда молимся за других, сами становимся сострадательнее!",
    "Tzeit — Tzeit (tzeit hakochavim) is halachic nightfall — when three medium stars appear and the day ends for night mitzvot like counting the Omer, bedikat chametz, Chanukah candles, Purim, and the end of Shabbat. It is not identical to sunset; communities follow different standards — from three medium stars to fixed minutes after sunset, and in some Diaspora communities much later (e.g. Rabbeinu Tam). Note: While standard Shabbat and weekday Erev Yom Tov candles must be lit before sunset, whenever a festival begins on a Saturday night (Motzei Shabbat), the Yom Tov candles strictly must be lit after sunset, only once nightfall (tzeit) has arrived, using a pre-existing flame — lighting them before sunset on Shabbat is a severe violation. Shavuot candles also wait for tzeit. The app shows local zmanim; when in doubt on a borderline mitzvah, ask your rav.":
        "Цейт (цейт hа-кохавим) — галахическое наступление ночи, когда видны три средние звезды и день заканчивается для ночных мицвот: сфира омера, бедикат хамец, свечи Хануки, Пурим и выход Шаббата. Это не то же самое, что закат; общины следуют разным стандартам — от трёх звёзд до фиксированных минут после заката, а в Галуте иногда гораздо позже (например, Рабейну Там). Стандартные свечи Шаббата и Эрева Йом Тов зажигают до заката; если праздник начинается в субботу вечером (моцеи Шаббат), свечи Йом Тов — только после заката, когда наступил цейт, от уже горящего огня. Свечи Шавуота тоже ждут цейта. Приложение показывает местные зманим; при сомнении в пограничной мицве спросите рава.",
    "Tzeit (tzeit hakochavim) is halachic nightfall — when three medium stars appear and the day ends for night mitzvot like counting the Omer, bedikat chametz, Chanukah candles, Purim, and the end of Shabbat. It is not identical to sunset; communities follow different standards — from three medium stars to fixed minutes after sunset, and in some Diaspora communities much later (e.g. Rabbeinu Tam). Note: While standard Shabbat and weekday Erev Yom Tov candles must be lit before sunset, whenever a festival begins on a Saturday night (Motzei Shabbat), the Yom Tov candles strictly must be lit after sunset, only once nightfall (tzeit) has arrived, using a pre-existing flame — lighting them before sunset on Shabbat is a severe violation. Shavuot candles also wait for tzeit. The app shows local zmanim; when in doubt on a borderline mitzvah, ask your rav.":
        "Цейт (цейт hа-кохавим) — галахическое наступление ночи, когда видны три средние звезды и день заканчивается для ночных мицвот: сфира омера, бедикат хамец, свечи Хануки, Пурим и выход Шаббата. Это не то же самое, что закат; общины следуют разным стандартам. Стандартные свечи Шаббата и Эрева Йом Тов зажигают до заката; если праздник начинается в субботу вечером (моцеи Шаббат), свечи Йом Тов — только после заката, когда наступил цейт, от уже горящего огня. Свечи Шавуота тоже ждут цейта. Приложение показывает местные зманим; при сомнении спросите рава.",
    "Borei Pri HaGafen — Borei pri hagafen is the blessing on wine and grape juice — \"Who creates the fruit of the vine.\" It is required before Kiddush, the four cups at the Seder, and drinking wine for simcha. After the blessing, drink a meaningful amount (revi'it per many poskim). Ordinary table grapes use a different blessing.":
        "Борей при hа-Гафен — благословение на вино и виноградный сок: «Который создаёт плод лозы». Нужно перед Киддушем, четырьмя чашами на Седере и вином для симхи. После благословения выпейте значимое количество (ревиит по мнению многих посеким). Обычный столовый виноград — с другой брахой.",
    "Seder — The Seder is the ordered Pesach night meal — four cups of wine, matzah, maror, and reading the Haggadah so children ask questions. Recline to the left for the four cups, matzah, korech, and afikoman — not during maror or chazeret. It reenacts leaving Egypt. Timing matters: matzah afikoman before halachic midnight per many poskim. Prepare the plate, Hagaddah, and guests' needs before Yom Tov begins so the night runs with joy, not panic.":
        "Седер — упорядоченная пасхальная трапеза: четыре чаши вина, маца, марор и чтение Агады, чтобы дети задавали вопросы. Отклоняйтесь влево при четырёх чашах, маце, корехе и афикомане — не при мароре или хазерете. Воссоздаёт исход из Египта. Важно время: афикоман до галахической полуночи по мнению многих посеким. Подготовьте тарелку, Агаду и нужды гостей до Йом Тов — чтобы ночь прошла с радостью, а не в спешке.",
    "The Seder is the ordered Pesach night meal — four cups of wine, matzah, maror, and reading the Haggadah so children ask questions. Recline to the left for the four cups, matzah, korech, and afikoman — not during maror or chazeret. It reenacts leaving Egypt. Timing matters: matzah afikoman before halachic midnight per many poskim. Prepare the plate, Hagaddah, and guests' needs before Yom Tov begins so the night runs with joy, not panic.":
        "Седер — упорядоченная пасхальная трапеза: четыре чаши вина, маца, марор и чтение Агады, чтобы дети задавали вопросы. Отклоняйтесь влево при четырёх чашах, маце, корехе и афикомане — не при мароре или хазерете. Воссоздаёт исход из Египта. Афикоман — до галахической полуночи по мнению многих посеким. Подготовьте тарелку, Агаду и нужды гостей до Йом Тов.",
    "k'dei achilat pras — K'dei achilat pras is the halachic time limit to consume a specific volume of food so it counts as one act of eating — about 4–7 minutes per many poskim. It applies to eating a kezayit of matzah at the Seder, maror, and eating enough bread or cake within that window to require an after-blessing (Birkat Hamazon or al hamichya). If you ate a kezayit of bread within k'dei achilat pras, Birkat Hamazon covers the whole meal.":
        "кдей ахилат прас — галахический предел времени, чтобы съесть нужный объём как один акт еды — около 4–7 минут по мнению многих посеким. Применяется к кезайиту мацы на Седере, марору и к достаточному количеству хлеба или выпечки для брахи ахрона (Биркат а-Мазон или ал ха-михья). Если съели кезайит хлеба в кдей ахилат прас, Биркат а-Мазон покрывает всю трапезу.",
    "Maror is bitter herb at the Seder — horseradish root or romaine — reminding the bitterness of slavery. A kezayit is required at the Seder. Charoset's sweetness is dipped with maror in Korech (Hillel's sandwich). Prepare enough fresh maror; grated horseradish loses strength quickly.":
        "Марор — горькая трава на Седере (хрен или салат ромэн), напоминающая горечь рабства. На Седере нужен кезайит. Сладость харосета сочетается с марором в корехе (сэндвич Хиллеля). Заготовьте достаточно свежего марора — тертый хрен быстро теряет силу.",
    "maror — Maror is bitter herb at the Seder — horseradish root or romaine — reminding the bitterness of slavery. A kezayit is required at the Seder. Charoset's sweetness is dipped with maror in Korech (Hillel's sandwich). Prepare enough fresh maror; grated horseradish loses strength quickly.":
        "марор — горькая трава на Седере (хрен или салат ромэн), напоминающая горечь рабства; нужен кезайит. В корехе марор с харосетом. Свежий марор; тертый хрен быстро слабеет.",
    "Minhag": "минhаг",
    "Master the art of loving rebuke! 💝 The Torah gives us an amazing tool: If you see someone doing something wrong, don't just stay quiet or gossip about it - help them grow! Here's the key: Speak privately, gently, and make it clear you're coming from a place of love. Did you know? The word for rebuke (תוכחה) is related to the word for proof (הוכחה), teaching us to help others see proof of a better way! Today's challenge: If you need to give feedback, do it with kindness and wisdom.": (
        "Овладейте искусством любящего упрека! 💝 Тора: «Укори ближнего» (Ваикра 19:17). Говорите наедине, мягко, из любви. "
        "Тохаха связана с «доказательством» лучшего пути. Сегодня: дайте обратную связь с добротой."
    ),
    "Ne'ilah": "неила",
    "Purim Meshulash — mishloach manot on Sunday (16 Adar)\n\nDeferred from Shabbat because Purim mitzvot are not performed on Shabbat this year.\n\nThe mitzvah:\n• Send at least two different ready-to-eat foods or drinks to one friend today — one package.\n• Deliver before sunset; a messenger is fine.\n• Food should be ready to eat without cooking; label sender and recipient.\n\nYou should have prepared packages before Shabbat. If not, ask your rav what you may still do today.": (
        "Пурим Мешугаш — мишлоах манот в воскресенье (16 Адар).\n\n"
        "Перенесено с Шаббата: мицвот Пурима в этом году не выполняют в Шаббат.\n\n"
        "Мицва:\n"
        "• Отправьте двум разным готовым продуктам или напиткам одному другу — одна посылка.\n"
        "• Доставьте до заката; можно через посланника.\n"
        "• Еда готова без готовки; укажите отправителя и получателя.\n\n"
        "Готовьте посылки до Шаббата; иначе спросите рава."
    ),
    "Afikoman": "афикоман",
    "Aleinu": "алейну",
    "Barchu": "барху",
    "Bentching": "бентчинг",
    "Emunah": "эмуна",
    "Borei Pri HaGafen": "борей при hа-гафен",
    "Choresh": "хореш",
    "Gozez": "гозез",
    "Hakafot": "hакафот",
    "Kinot": "кинот",
    "Korech": "корех",
}
