"""Batch 15: guillemet glossary M–b — explicit mappings."""

from __future__ import annotations

TOP50_BATCH15: dict[str, str] = {
    "Mezonot": "мезонот",
    "Mishloach Manot": "мишлоах манот",
    "Mishnah Berurah": "мишна брура",
    "Modah": "мода",
    "Muktzeh": "мукце",
    "Musaf": "мусаф",
    "Mussar": "мусар",
    "Nachum Ish Gamzu": "нахум иш гамзу",
    "Nevi'im": "невиим",
    "Peninei Halakha": "пениней hалаха",
    "Purim Meshulash": "пурим мешугаш",
    "Rabbi": "раввин",
    "Rashi": "раши",
    "Retzei": "рецеи",
    "Seder": "седер",
    "Sefardim": "сефарды",
    "Sefirah": "сефира",
    "Selichot": "селихот",
    "Seudah": "сеуда",
    "Shamayim": "шамаим",
    "Shavuot": "шавуот",
    "Shemini Atzeret": "шемини ацерет",
    "Shemoneh Esrei": "шмоне эре",
    "Shemoneh Esrei/Tachanun": "шмоне эре/таханун",
    "Shir HaMaalot": "шир hа-маалот",
    "Shulchan Aruch": "шулхан арух",
    "Simchat Torah": "симхат тора",
    "Simchat Yom Tov": "симхат йом тов",
    "Sukkah": "сукка",
    "Taanit Bechorot": "таанит бехорот",
    "Tachanun": "таханун",
    "Tanach": "танах",
    "Tanya": "тания",
    "Tefilat Nedavah": "тфилат недава",
    "Vatodi'enu": "ватодиену",
    "Yaknehaz": "якнеhаз",
    "Yom Yerushalayim": "йом йерушалаим",
    "Zachor": "захор",
    "Zohar": "зоар",
    "aggadah": "агада",
    "alot hashachar": "алот hашахар",
    "aravah": "арава",
    "assur bemelacha": "асур бе-мелаха",
    "bedieved": "бедиевед",
    "bedikat chametz": "бедикат хамец",
    "beged": "бегед",
    "bein kodesh l'kodesh": "бейн кодеш ле-кодеш",
    "beitzah": "бейца",
    "bentcher": "бентчер",
    "besamim": "бесамим",
}

