"""Informal RU (ty) bodies for Rosh Chodesh seasonal explainers."""

from __future__ import annotations

_ROSH_CHODESH_SHORT = 'Рош Ходеш — первый день каждого еврейского месяца, а иногда и 30-й день предыдущего.\n\nОсобые observances: «Яале вьяво» в молитвах и Биркат а-Мазон, полу-Алел, Мусаф и особое чтение Торы.\n\nРош Ходеш — полупраздник: пост и траурные речи обычно не проводят. Распространённый обычай — замужним женщинам воздерживаться от некоторых видов работы в честь дня.'

_ROSH_CHODESH_GENERAL = 'Рош Ходеш (ראש חודש) — Новый месяц — полупраздник с дополнительными молитвами и обычаями.\n\nПраздничная трапеза (мицва):\n• Мицва увеличить трапезу в Рош Ходеш — хотя бы дополнительное блюдо в честь дня (Шулхан Арух О.Х. 419:1).\n• Ешь днём: позким связывают это с пиром санхедрина в Бейт Яазек для свидетелей новолуния (Мишна Рош а-Шана 2:5; Орхот Хаим и Коль Бо на О.Х. 419).\n• Деньги на трапезы Рош Ходеш — как на Шаббат и Йом Тов — не вычитаются из годового пропитания; если тратишь больше на эти мицвот, Небеса добавляют (Песикта де-Рав Кахана; Тур О.Х. 419; Маген Аврахам 419:1).\n\nМолитва сегодня (в разделах утренней, дневной и вечерней молитвы):\n• «Яале вьяво» в Амиде Шахарит, Минха и Маарив — и в Биркат а-Мазон, если ешь хлеб\n• Полу-Алел на Шахарите (полный Алел, если Рош Ходеш в Ханука; без Алела в Тишрей / Рош а-Шана)\n• Мусаф после Шахарита — сними тфилин перед Мусафом\n• Таханун не читают весь день\n\nДругие обычаи:\n• Пост и траурные речи в Рош Ходеш обычно не проводят\n• Распространённый обычай: замужние женщины воздерживаются от некоторой melacha (шитьё, стирка и т.д.) как дополнительный знак почёта — уточни у рава\n\nКогда Рош Ходеш длится два дня (30-й предыдущего месяца и 1-й), observances действуют оба дня.'

_ROSH_CHODESH_FEMALE = 'Рош Ходеш (ראש חודש) — Новый месяц — полупраздник с дополнительными молитвами и обычаями.\n\nПраздничная трапеза (мицва):\n• Мицва увеличить трапезу в Рош Ходеш — хотя бы дополнительное блюдо в честь дня (Шулхан Арух О.Х. 419:1).\n• Ешь днём: позким связывают это с пиром санхедрина в Бейт Яазек для свидетелей новолуния (Мишна Рош а-Шана 2:5; Орхот Хаим и Коль Бо на О.Х. 419).\n• Деньги на трапезы Рош Ходеш — как на Шаббат и Йом Тов — не вычитаются из годового пропитания; если тратишь больше на эти мицвот, Небеса добавляют (Песикта де-Рав Кахана; Тур О.Х. 419; Маген Аврахам 419:1).\n\nМолитва сегодня (в разделах утренней, дневной и вечерней молитвы):\n• Если читаешь Амиду Шахарит, Минха или Маарив — добавь «Яале вьяво» в «Рацей». Шахарит/Минха: вставь в «Рацей»; если уже завершила «Рацей» — вернись к началу; если закончила Амиду — повтори только эту Амиду. Только Маарив Рош Ходеш: если забыла после «Рацей» — не повторяй (Брахот 30б; Шулхан Арух О.Х. 422:1)\n• Если говоришь Биркат а-Мазон, когда ешь хлеб — добавь «Яале вьяво» и там\n• Ашкеназский обычай — большинство позков обязывает в Шахарит и Минха в эти дни\n• Сефардский обычай — многие женщины выполняют дневную обязанность одной молитвой; если молишь дополнительную Амиду и забудешь «Яале вьяво» — спроси рава о недава (nedavah)\n• Полу-Алел на Шахарите, если читаешь Алел (по минхагу; полный Алел в Ханука)\n• Таханун не читают весь день\n\nДругие обычаи:\n• Пост и траурные речи в Рош Ходеш обычно не проводят\n• Распространённый обычай: замужние женщины воздерживаются от некоторой melacha (шитьё, стирка и т.д.) как дополнительный знак почёта — уточни у рава\n\nКогда Рош Ходеш длится два дня (30-й предыдущего месяца и 1-й), observances действуют оба дня.'

ROSH_CHODESH_RU_BY_PREFIX: dict[str, str] = {
    "Rosh Chodesh (the New Month) is the first day": _ROSH_CHODESH_SHORT,
    "Rosh Chodesh (ראש חודש) — the New Month — is a semi-holiday with extra prayer and customs.\n\nFestive meal (mitzvah):\n• It is a mitzvah to increase your meal on Rosh Chodesh — at minimum add an extra dish or special food in honor of the day (Shulchan Arukh O.C. 419:1).\n• Have the meal during the day. Poskim write this commemorates the feast the Sanhedrin held at Beit Ya'zek for witnesses who came to testify they saw the new moon (Mishnah Rosh Hashanah 2:5; Orchos Chaim and Kol Bo, cited on O.C. 419).\n• Money spent on Rosh Chodesh meals — like Shabbat and Yom Tov — is not deducted from the income allotted to you on Rosh Hashanah; if you spend more for these mitzvos, Heaven adds to your allotment (Pesikta de-Rav Kahana, cited in Tur O.C. 419 and Magen Avraham 419:1).\n\nDavening today (listed in your Morning, Afternoon, and Evening Prayer sections):\n• If you recite Shacharit, Mincha, or Maariv Amidah": _ROSH_CHODESH_FEMALE,
    "Rosh Chodesh (ראש חודש) — the New Month — is a semi-holiday with extra prayer and customs.\n\nFestive meal (mitzvah):\n• It is a mitzvah to increase your meal on Rosh Chodesh — at minimum add an extra dish or special food in honor of the day (Shulchan Arukh O.C. 419:1).\n• Have the meal during the day. Poskim write this commemorates the feast the Sanhedrin held at Beit Ya'zek for witnesses who came to testify they saw the new moon (Mishnah Rosh Hashanah 2:5; Orchos Chaim and Kol Bo, cited on O.C. 419).\n• Money spent on Rosh Chodesh meals — like Shabbat and Yom Tov — is not deducted from the income allotted to you on Rosh Hashanah; if you spend more for these mitzvos, Heaven adds to your allotment (Pesikta de-Rav Kahana, cited in Tur O.C. 419 and Magen Avraham 419:1).\n\nDavening today (listed in your Morning, Afternoon, and Evening Prayer sections):\n• Yaaleh V'yavo in Shacharit, Mincha": _ROSH_CHODESH_GENERAL,
    "Rosh Chodesh falls during Chanukah — recite Full Hallel at Shacharit (the Chanukah obligation), not the usual Half Hallel of Rosh Chodesh (Peninei Halakha 12-02-07).\n\nBefore Musaf:\nRemove tefillin before Musaf — do not wear tefillin during the Musaf Amidah.\n\nTachanun is omitted.": (
        "Рош Ходеш в Хануку — читай полный Алел на Шахарите (обязанность Хануки), а не обычный полу-Алел Рош Ходеш (Пениней а-Алаха 12-02-07).\n\n"
        "Перед Мусафом:\n"
        "Сними тфилин до Мусафа — не надевай тфилин во время Амиды Мусаф.\n\n"
        "Таханун не читают."
    ),
}


def rosh_chodesh_ru_for_key(key: str) -> str | None:
    best: str | None = None
    best_len = 0
    for prefix, val in ROSH_CHODESH_RU_BY_PREFIX.items():
        if key.startswith(prefix) and len(prefix) > best_len:
            best = val
            best_len = len(prefix)
    return best
