import json
from pathlib import Path

BASE = Path(r"c:\apps\hehehe\be-a-tzaddik\data\translation-catalog\human")

local_006_es = [
    "¡Envuélvete en la mitzvá de Tzitzit! 🧵 ¿Sabías? Estas cuerdas no son solo la declaración de moda judía original — ¡proporcionan protección divina contra fuerzas malignas e incluso te alejan de malas acciones! Los Sabios dicen que una mujer que ayuda a su esposo a cumplir esta mitzvá se considerará como si ella misma las llevara.",
    "¡Sé un entusiasta del Amen! 🗣️ ¿Sabías? Decir Amen a una bendición confirma que lo que dijo la primera persona es verdad — las letras alef (א), mem (מ), nun (נ) son acrónimo de D-s, Rey, que es fiel. ¡Confirma que D-s es grande y los Sabios dicen que «robaste el show»! El Talmud dice que responder Amen es mayor que hacer la bendición misma. Misión de hoy: mantén los oídos abiertos a las bendiciones y estate listo con tu bis espiritual — ¡no te pierdas un Amen! Y recuerda: confirmas que D-s es grande y que hace lo que dice que hará.",
    "Ora por un shidduch (esposa) para mi amigo Mordechai Shaul ben Devorah — enviado por HS. Nuestros Sabios enseñan que cuando oras por otra persona y tú también necesitas lo mismo, se te responde primero — porque la oración desinteresada abre las puertas más altas. También enseñan que emparejar esposo y esposa es tan difícil para D-s como dividir el Mar Rojo — cada matrimonio es orquestado desde el Cielo con cuidado extraordinario. Una oración sincera por el shidduch de un amigo es uno de los mayores regalos que puedes dar.",
    "¿Tienes algo de tiempo libre? Visita a alguien enfermo. Nuestros Sabios enseñan que visitar al enfermo elimina un sesentaavo de su enfermedad. La mitzvá de bikkur cholim (visitar al enfermo) es una de las formas de caminar en los caminos de D-s, como Él visitó a Avraham cuando se recuperaba. La halajá enseña que debemos sentarnos con el enfermo, consolarlo y ayudar en lo que necesite — aunque sea solo hacerle compañía unos minutos. Tu presencia puede levantar el ánimo de alguien tanto como cualquier medicina.",
    "¿Viste un objeto perdido recientemente? 🔍 ¡No lo ignores! Vuelve e intenta devolverlo a su dueño (si es posible). Esa es la mitzvá de Hashavat Aveidah (devolver objetos perdidos). La Torá enseña que si ves el animal o pertenencias de tu prójimo extraviados, no puedes apartar la mirada — debes esforzarte por devolverlos. Nuestros Sabios dedicaron discusiones enteras a esta mitzvá: cuánto debes esforzarte, qué puedes quedarte como recompensa por tu trabajo, y por qué devolver la propiedad de alguien es también devolver su dignidad.",
    "¡Ora por el Mashiaj!!!!!!! — enviado por EV. Creer en la venida del Mashiaj es uno de los trece fundamentos de la fe judía — anticipamos un rey de la casa de David que reconstruirá el Templo, reunirá a los exiliados y llenará el mundo del conocimiento de D-s. Nuestros Sabios enseñan que un judío debe vivir cada día con expectativa de redención. Cuando oras por el Mashiaj, expresas esperanza por un mundo de paz, santidad y revelación completa de la presencia de D-s.",
    "Toma un minuto para orar por las necesidades de otra persona antes que las tuyas. Nuestros Sabios enseñan un secreto notable: cuando oras por otra persona y tú también necesitas lo mismo, se te responde primero. Poner las necesidades de otro antes que las tuyas transforma la tefilá (oración) de una lista personal de deseos en un acto de amor por todo el pueblo judío.",
    "Intenta hacer paz entre dos personas que conoces que están discutiendo. ¡La recompensa por hacerlo es muy grande! Hillel nos enseñó a estar entre los discípulos de Aarón — amante de la paz y buscador de la paz, que saludaba a cada persona con calidez y la acercaba a la Torá. Nuestros Sabios enseñan que la paz es tan preciosa que D-s permite que Su santo Nombre sea borrado para restaurar la paz entre esposo y esposa. Ayudar a dos personas a reconciliarse puede ser uno de los mayores actos de jésed (bondad) del mundo.",
    "La próxima vez que tengas invitados, recuerda escoltarlos al salir, aunque sean solo unos pasos. El Talmud (Sotah 46b) dice que la recompensa por acompañar a otros no tiene medida.",
    "Llama a alguien que se sienta solo. Enviado por: Amy. Nuestros Sabios advierten nunca separarse de la comunidad — porque un judío necesita conexión para prosperar. Visitar al enfermo elimina un sesentaavo de su sufrimiento, y la soledad puede ser su propia enfermedad. Una llamada, un mensaje o una visita le dice a alguien que importa — y amar a tu prójimo judío es uno de los fundamentos de todo lo que representamos.",
    "¡Aprende sobre el Shema! Buenas noticias — puedes decirlo de pie, caminando, o incluso montado en tu fiel burro (o en el coche, en tiempos modernos 😉). Solo no intentes decirlo acostado boca arriba o boca abajo — eso no está permitido. ¡Acostado de lado está perfectamente bien! ¿Y si no te sientes bien o no puedes girarte de lado? No te preocupes — inclínate un poco hacia un lado y listo. La clave es decirlo de forma que muestre respeto y siga siendo práctico para tu situación.",
    "Aprende algo de halajá — al cumplir la mitzvá de decir el Shema (versículos de la Torá que proclaman la unidad de D-s), recuerda este detalle importante: si caminas, detente un momento para decir ese poderoso primer versículo — ¡dále la atención que merece! Después puedes seguir caminando mientras dices el resto.",
    "Aprende halajá sobre el Shema — si estás en el trabajo cuando es hora de decir Shema y no puedes decirlo más tarde, esto es lo que debes hacer: toma un descanso completo del trabajo para todo el primer párrafo. Ya seas autónomo o empleado, ¡esta mitzvá especial tiene prioridad! Después de esa primera sección, puedes hacer multitarea y decir el resto mientras trabajas. Aunque estés «en el reloj», ¡D-s va primero!",
    "¡Estudia la increíble mesa del pan de la proposición (Shulchan)! 🍞 Tómate un momento para aprender sobre esta mesa de oro que sostenía 12 panes especiales. Aquí está el milagro: el pan se mantuvo fresco y caliente durante una semana entera hasta que fue reemplazado. Aún más asombroso — cuando la gente venía a Jerusalén para las fiestas, los Kohanim levantaban la mesa y decían «¡Mirad cuán amados sois ante D-s!», mostrándoles el pan caliente y fresco de una semana entera como prueba del amor constante de D-s. ❤️",
    "¡Aprende sobre el Kiyor (lavabo) especial del Templo! 🚰 ¿Sabías? Los Kohanim tenían que lavarse las manos y los pies al mismo tiempo, poniendo la mano derecha sobre el pie derecho y la izquierda sobre el pie izquierdo. Esta posición única les recordaba dedicarse por completo al servicio — ¡de la cabeza a los pies! Además, el agua debía ser fresca cada día, enseñándonos a comenzar el servicio divino de cada jornada con renovación.",
    "¡Descubre el secreto del cinto sacerdotal! 🎗️ ¿Sabías? En el Beit HaMikdash, el cinto de un Kohen medía increíbles 32 amot (unos 14 metros). Algo asombroso: los sacerdotes lo envolvían una y otra vez, capa sobre capa. Esto nos enseña que a veces incluso las personas más sagradas necesitan múltiples capas de protección para guardar su esencia espiritual. Desafío de hoy: aprende sobre la vestimenta de los Kohanim y piensa en lo que puede simbolizar.",
    "¡Aprende sobre el sistema de reciclaje del Santo Templo! ♻️ ¿Sabías? Cuando las vestiduras sacerdotales se desgastaban, no se tiraban — se transformaban en mechas para las luces del Templo. Algo poderoso: incluso los objetos sagrados que ya no podían cumplir su propósito original recibían nueva vida al servicio de D-s. Misión de hoy: estudia esta práctica y reflexiona sobre encontrar un nuevo propósito en todo.",
    "¡Aprende sobre las dimensiones del Monte del Templo! 🏛️ El Monte Moriah, el Monte del Templo donde estaba el Beit HaMikdash, medía 500 codos por 500 codos y estaba rodeado por un muro. ¿Sabías? Toda la tierra debajo fue vaciada y sostenida por arcos para evitar impureza ritual de tumbas en las profundidades.",
]

local_006_fr = [
    "Enveloppez-vous dans la mitzvah de Tzitzit ! 🧵 Le saviez-vous ? Ces fils ne sont pas seulement la déclaration de mode juive originale — ils procurent une protection divine contre les forces du mal et vous éloignent même des mauvaises actions ! Les Sages disent qu'une femme qui aide son mari à accomplir cette mitzvah sera considérée comme si elle les portait elle-même !",
    "Soyez un amateur d'Amen ! 🗣️ Le saviez-vous ? Dire Amen à une bénédiction confirme que ce que la première personne a dit est vrai — les lettres alef (א), mem (מ), nun (נ) sont l'acronyme de D., Roi, qui est fidèle. Confirmez que D. est grand et les Sages disent que vous « volez le show » ! Le Talmud dit que répondre Amen est plus grand que faire la bénédiction elle-même. Mission du jour : gardez vos oreilles ouvertes aux bénédictions et soyez prêts avec votre rappel spirituel — ne manquez pas un Amen ! Et rappelez-vous : vous confirmez que D. est grand et qu'Il fait ce qu'Il dit qu'Il fera.",
    "Priez pour un shidou'h (épouse) pour mon ami Mordechai Shaul ben Devorah — soumis par HS ! Nos Sages enseignent que quand vous priez pour une autre personne et que vous avez vous-même besoin de la même chose, vous êtes exaucé en premier — car la prière désintéressée ouvre les plus hautes portes. Ils enseignent aussi qu'unir mari et femme est aussi difficile pour D. que de fendre la mer Rouge — chaque mariage est orchestré du Ciel avec un soin extraordinaire. Une prière sincère pour le shidou'h d'un ami est l'un des plus grands cadeaux que vous puissiez offrir.",
    "Vous avez un peu de temps libre ? Visitez quelqu'un de malade ! Nos Sages enseignent que visiter les malades enlève un soixantième de leur maladie ! La mitzvah de bikkour 'holim (visiter les malades) est l'une des façons de marcher dans les voies de D., tout comme Il a visité Abraham lorsqu'il se remettait. La halakha enseigne que nous devons nous asseoir avec le malade, le réconforter et l'aider selon ses besoins — même si c'est juste lui tenir compagnie quelques minutes. Votre présence peut remonter le moral autant qu'un médicament.",
    "Vous avez vu un objet perdu récemment ? 🔍 Ne l'ignorez pas ! Retournez et essayez de le rendre à son propriétaire (si possible). C'est la mitzvah de Hashavat Aveidah (rendre les objets perdus). La Torah enseigne que si vous voyez l'animal ou les biens de votre prochain s'égarer, vous ne pouvez pas détourner le regard — vous devez faire un effort pour les rendre. Nos Sages ont consacré des discussions entières à cette mitzvah : combien vous devez essayer, ce que vous pouvez garder en récompense de vos efforts, et pourquoi rendre les biens de quelqu'un, c'est aussi rendre sa dignité.",
    "Priez pour le Machia'h !!!!!!! — soumis par EV. Croire en la venue du Machia'h est l'un des treize fondements de la foi juive — nous attendons un roi de la maison de David qui reconstruira le Temple, rassemblera les exilés et remplira le monde de la connaissance de D. Nos Sages enseignent qu'un Juif doit vivre chaque jour dans l'attente de la rédemption. Quand vous priez pour le Machia'h, vous exprimez l'espoir d'un monde de paix, de sainteté et de révélation complète de la Présence de D.",
    "Prenez une minute pour prier pour les besoins de quelqu'un d'autre avant les vôtres. Nos Sages enseignent un secret remarquable : quand vous priez pour une autre personne et que vous avez vous-même besoin de la même chose, vous êtes exaucé en premier. Mettre les besoins de l'autre avant les vôtres transforme la tefilla (prière) d'une liste de souhaits personnelle en un acte d'amour pour tout le peuple juif.",
    "Essayez de faire la paix entre deux personnes que vous connaissez et qui se disputent. La récompense pour cela est très grande ! Hillel nous a enseigné d'être parmi les disciples d'Aaron — amoureux de la paix et poursuiveurs de la paix, qui accueillaient chaque personne chaleureusement et la rapprochaient de la Torah. Nos Sages enseignent que la paix est si précieuse que D. permet que Son saint Nom soit effacé pour restaurer la paix entre un mari et une femme. Aider deux personnes à se réconcilier peut être l'un des plus grands actes de 'hessed (bonté) au monde.",
    "La prochaine fois que vous avez des invités, pensez à les accompagner en partant, même quelques pas. Le Talmud (Sotah 46b) dit que la récompense de l'accompagnement n'a pas de mesure !",
    "Appelez quelqu'un qui se sent seul. Soumis par : Amy. Nos Sages avertissent de ne jamais se séparer de la communauté — car un Juif a besoin de connexion pour s'épanouir. Visiter les malades enlève un soixantième de leur souffrance, et la solitude peut être une maladie en soi. Un appel, un message ou une visite dit à quelqu'un qu'il compte — et aimer son prochain Juif est l'un des fondements de tout ce que nous défendons.",
    "Apprenez à dire le Shema ! Bonne nouvelle — vous pouvez le dire debout, en marchant, ou même en chevauchant votre âne fidèle (ou en voiture, de nos jours 😉). N'essayez simplement pas de le dire allongé sur le dos ou le ventre — ce n'est pas permis. S'allonger sur le côté, c'est parfait ! Et si vous ne vous sentez pas bien ou ne pouvez pas vous tourner sur le côté ? Pas de souci — penchez-vous un peu sur le côté et c'est bon. L'essentiel est de le dire d'une manière qui montre du respect tout en restant pratique pour votre situation.",
    "Apprenez un peu de halakha — en accomplissant la mitzvah de dire le Shema (versets de la Torah proclamant l'unité de D.), rappelez-vous ce détail important : si vous marchez, arrêtez-vous un instant pour dire ce premier verset puissant — donnez-lui l'attention qu'il mérite ! Après cela, vous pouvez continuer à marcher tout en disant le reste.",
    "Apprenez la halakha du Shema — si vous êtes au travail quand il est temps de dire Shema et que vous ne pouvez pas le dire plus tard, voici quoi faire : faites une pause complète de votre travail pour tout le premier paragraphe. Que vous soyez indépendant ou salarié, cette mitzvah spéciale a la priorité ! Après cette première section, vous pouvez faire plusieurs choses à la fois et dire le reste en travaillant. Même si vous êtes « à l'heure », D. passe en premier !",
    "Étudiez l'incroyable table des pains de proposition (Shulchan) ! 🍞 Prenez un moment pour découvrir cette table d'or qui contenait 12 pains spéciaux. Voici le miracle : le pain resta frais et chaud toute une semaine jusqu'à son remplacement ! Encore plus étonnant — quand les gens venaient à Jérusalem pour les fêtes, les Kohanim soulevaient la table et disaient « Voyez combien vous êtes aimés devant D. ! », leur montrant le pain chaud et frais d'une semaine entière comme preuve de l'amour constant de D. ! ❤️",
    "Apprenez le Kiyor (bassin) spécial du Temple ! 🚰 Le saviez-vous ? Les Kohanim devaient se laver les mains et les pieds en même temps en posant la main droite sur le pied droit et la main gauche sur le pied gauche ! Cette position unique leur rappelait d'être entièrement dédiés au service — de la tête aux pieds ! De plus, l'eau devait être fraîche chaque jour, nous enseignant à commencer chaque journée de service divin avec renouvellement.",
    "Découvrez le secret de la ceinture sacerdotale ! 🎗️ Le saviez-vous ? Dans le Beit HaMikdash, la ceinture d'un Kohen mesurait incroyables 32 amot (environ 14 mètres) ! Voici quelque chose d'étonnant : les prêtres l'enroulaient encore et encore, couche sur couche. Cela nous enseigne que parfois même les personnes les plus saintes ont besoin de multiples couches de protection pour garder leur essence spirituelle. Défi du jour : découvrez les vêtements des Kohanim et réfléchissez à ce qu'ils pourraient symboliser.",
    "Apprenez le système de recyclage du Saint Temple ! ♻️ Le saviez-vous ? Quand les vêtements sacerdotaux s'usaient, ils n'étaient pas jetés — ils étaient transformés en mèches pour les lumières du Temple ! Voici quelque chose de puissant : même les objets saints qui ne pouvaient plus servir leur but original recevaient une nouvelle vie au service de D. Mission du jour : étudiez cette pratique et réfléchissez à trouver un nouveau but en tout.",
    "Découvrez les dimensions du Mont du Temple ! 🏛️ Le mont Moriah, le Mont du Temple où se tenait le Beit HaMikdash, mesurait 500 coudées sur 500 coudées et était entouré d'un mur. Le saviez-vous ? Toute la terre en dessous fut creusée et soutenue par des arcs pour empêcher l'impureté rituelle des tombes en profondeur.",
]

local_006_ru = [
    "Окунитесь в mitzvah Tzitzit! 🧵 Знаете ли вы? Эти нити — не просто оригинальное еврейское модное заявление — они дают божественную защиту от злых сил и даже оберегают от проступков! Мудрецы говорят: женщина, помогающая мужу выполнить эту mitzvah, считается так, будто она носит их сама!",
    "Будьте энтузиастом Amen! 🗣️ Знаете ли вы? Сказать Amen на благословение — значит подтвердить, что первый человек сказал истину — буквы alef (א), mem (מ), nun (נ) — аббревиатура: Hashem, Царь, который верен. Подтвердите, что Hashem велик, и мудрецы говорят, что вы «украли шоу»! Talmud учит: ответ Amen важнее самого благословения. Миссия на сегодня: держите уши открытыми для благословений и будьте готовы с духовным бис — не пропустите Amen! И помните: вы подтверждаете, что Hashem велик и делает то, что обещает.",
    "Молитесь о shidduch (жене) для моего друга Mordechai Shaul ben Devorah — предложено HS. Мудрецы учат: когда вы молитесь за другого и сами нуждаетесь в том же — вас отвечают первым, потому что бескорыстная молитва открывает высшие врата. Они также учат: свести мужа и жену для Hashem столь же трудно, как расколоть Красное море — каждый брак устроен с Небес с необычайной заботой. Искренняя молитва о shidduch друга — один из величайших даров.",
    "Есть немного свободного времени? Навестите больного. Мудрецы учат: посещение больного снимает одну шестидесятую его болезни! Mitzvah bikkur cholim (навещение больных) — один из способов идти путями Hashem, как Он навестил Avraham, когда тот выздоравливал. Галаха учит сидеть с больным, утешать и помогать во всём нужном — пусть даже просто составить компанию на несколько минут. Ваше присутствие может поднять дух не хуже любого лекарства.",
    "Недавно видели потерянную вещь? 🔍 Не игнорируйте! Вернитесь и попробуйте отдать её владельцу (если возможно). Это mitzvah Hashavat Aveidah (возврат потерянных вещей). Тора учит: если вы видите, как блуждает скот или имущество ближнего, нельзя отводить взгляд — нужно приложить усилия вернуть. Мудрецы посвятили целые обсуждения этой mitzvah: насколько стараться, что можно оставить себе в награду за труд и почему возврат имущества — это также возврат достоинства.",
    "Молитесь о Mashiach!!!!!!! — предложено EV. Вера в приход Mashiach — один из тринадцати основ еврейской веры — мы ожидаем царя из дома David, который восстановит Храм, соберёт изгнанников и наполнит мир познанием Hashem. Мудрецы учат: еврей должен жить каждый день в ожидании искупления. Молясь о Mashiach, вы выражаете надежду на мир мира, святости и полного откровения присутствия Hashem.",
    "Уделите минуту, чтобы помолиться о нуждах другого человека раньше своих. Мудрецы учат удивительному секрету: когда вы молитесь за другого и сами нуждаетесь в том же — вас отвечают первым. Ставя нужды другого выше своих, вы превращаете tefillah (молитву) из личного списка желаний в акт любви ко всему еврейскому народу.",
    "Попробуйте установить мир между двумя знакомыми, которые сейчас ссорятся. Награда за это очень велика! Hillel учил нас быть среди учеников Aharon — любящих мир и стремящихся к миру, которые тепло приветствовали каждого и приближали к Торе. Мудрецы учат: мир настолько драгоцен, что Hashem позволяет стереть Своё святое Имя, чтобы восстановить мир между мужем и женой. Помочь двум людям примириться — возможно, один из величайших актов chesed (доброты) в мире.",
    "В следующий раз, когда у вас гости, провожайте их при уходе, хотя бы на несколько шагов. Talmud (Sotah 46b) говорит: награда за проводы не имеет предела!",
    "Позвоните одинокому человеку. Предложено: Amy. Мудрецы предупреждают: никогда не отделяйтесь от общины — еврею нужна связь, чтобы процветать. Посещение больного снимает одну шестидесятую страдания, а одиночество — болезнь сама по себе. Звонок, сообщение или визит говорят человеку, что он важен — а любовь к ближнему-еврею — один из основ всего, за что мы стоим.",
    "Узнайте о Shema! Хорошая новость — его можно читать стоя, идя, и даже верхом на верном ослике (или в машине, в наше время 😉). Просто не пытайтесь читать его лёжа на спине или лицом вниз — это нельзя. Лёжа на боку — отлично! А если плохо себя чувствуете или не можете перевернуться на бок? Не беспокойтесь — слегка наклонитесь в сторону, и всё в порядке. Главное — читать так, чтобы это выглядело уважительно и оставалось практичным для вашей ситуации.",
    "Выучите немного галахи — выполняя mitzvah чтения Shema (стихи Торы, провозглашающие единство Hashem), помните важную деталь: если идёте, остановитесь на мгновение, чтобы произнести тот мощный первый стих — уделите ему заслуженное внимание! После этого можно продолжать идти и читать остальное.",
    "Выучите галаху о Shema — если вы на работе, когда пришло время читать Shema, и не можете сделать это позже, вот что делать: полностью прервите работу на весь первый абзац. Будь вы самозаняты или наёмный работник — эта особая mitzvah в приоритете! После первого раздела можно совмещать и читать остальное во время работы. Даже если вы «на часах», Hashem — первый!",
    "Изучите невероятный стол хлебов предложения (Shulchan)! 🍞 Найдите минуту, чтобы узнать об этом золотом столе, на котором лежали 12 особых хлебов. Вот чудо: хлеб оставался свежим и тёплым целую неделю, пока его не заменяли! Ещё удивительнее — когда люди приезжали в Иерусалим на праздники, Kohanim поднимали стол и говорили: «Посмотрите, как вы любимы перед Hashem!», показывая им тёплый свежий недельный хлеб как доказательство постоянной любви Hashem! ❤️",
    "Узнайте о Kiyor (умывальнике) Храма! 🚰 Знаете ли вы? Kohanim должны были мыть руки и ноги одновременно, положив правую руку на правую ногу и левую — на левую! Эта необычная поза напоминала им быть полностью посвящёнными служению — с головы до ног! Кроме того, вода должна была быть свежей каждый день, учит нас начинать ежедневное божественное служение с обновлением.",
    "Откройте секрет священнического пояса! 🎗️ Знаете ли вы? В Beit HaMikdash пояс Kohen был невероятных 32 амот (около 14 метров)! Вот что удивительно: священники оборачивали его снова и снова, слой за слоем. Это учит: иногда даже самым святым людям нужны многослойные защиты, чтобы беречь духовную сущность. Вызов на сегодня: узнайте об одежде Kohanim и подумайте, что она может символизировать.",
    "Узнайте о системе переработки Святого Храма! ♻️ Знаете ли вы? Когда священнические одежды изнашивались, их не выбрасывали — они превращались в фитили для огней Храма! Вот что мощно: даже святые предметы, которые больше не могли служить своему первоначальному назначению, получали новую жизнь в служении Hashem. Миссия на сегодня: изучите эту практику и поразмышляйте о новом предназначении во всём.",
    "Узнайте о размерах Храмовой горы! 🏛️ Гора Moriah, Храмовая гора, где стоял Beit HaMikdash, имела 500 локтей на 500 локтей и была окружена стеной. Знаете ли вы? Вся земля под ней была выдолблена и поддержана арками, чтобы предотвратить ритуальную нечистоту от могил внизу.",
]

local_006_he = [
    "התעטפו במצוות הציצית! 🧵 ידעתם? המיתרים האלה אינם רק הצהרת האופנה היהודית המקורית — הם מספקים הגנה אלוקית מפני כוחות רעים ואף מונעים מכם ממעשים רעים! חכמינו אומרים שנשים שעוזרות לבעלן לקיים מצווה זו ייחשבו כאילו הן לבשו אותן בעצמן!",
    "היו חובבי אמן! 🗣️ ידעתם? אמירת אמן לברכה מאשרת שמה שהראשון אמר נכון — האותיות alef (א), mem (מ), nun (נ) הן ראשי תיבות של אלוקים, מלך, נאמן. אשרו שה' גדול, וחכמינו אומרים שאתם «גונבים את ההצגה»! הגמרא אומרת שתשובת אמן גדולה יותר מעשיית הברכה עצמה. משימת היום: שמרו על אוזניים פתוחות לברכות ותהיו מוכנים עם הביס הרוחני — אל תפספסו אמן! וזכרו, אתם מאשרים שה' גדול והוא עושה מה שהוא אומר שיעשה!",
    (
        "התפללו על shidduch (זיווג) עבור חברי Mordechai Shaul ben Devorah — הוגש על ידי HS. "
        "חכמינו מלמדים שכשאתם מתפללים עבור אדם אחר וגם אתם זקוקים לאותו דבר — נענים אתם קודם, "
        "כי תפילה ללא אנוכיות פותחת את השערים העליונים. הם גם מלמדים שזיווג בני זוג קשה לה' "
        "\u05db\u05e7\u05d5\u05e9\u05d9 \u05e7\u05e8\u05d9\u05e2\u05ea \u05d9\u05dd \u05e1\u05d5\u05e3 — כלומר "
        "\u05db\u05dc \u05e0\u05d9\u05e9\u05d5\u05d0\u05d9\u05df מנוהל מן השמיים בדאגה יוצאת דופן. "
        "תפילה מלב אל לב לshidduch של חבר היא אחת המתנות הגדולות ביותר שאפשר לתת."
    ),
    "יש לכם קצת זמן פנוי? בקרו בחולה. חכמינו מלמדים שביקור חולים מסיר שישים מחליו! מצוות ביקור חולים היא אחת הדרכים שבהן אנחנו הולכים בדרכי ה', כמו שהוא ביקר את אברהם כשהיה מתרפא. ההלכה מלמדת שיש לשבת עם החולה, לנחם אותו ולעזור במה שצריך — אפילו רק לשמור לו חברה כמה דקות. הנוכחות שלכם יכולה לעודד מישהו כמו כל תרופה.",
    "ראיתם לאחרונה חפץ אבוד? 🔍 אל תתעלמו! חזרו ונסו להחזיר אותו לבעליו (אם אפשר). זו מצוות השבת אבידה (Hashavat Aveidah). התורה מלמדת שאם אתם רואים את בהמתו או חפציו של חברכם הולכים ותועים — אסור להתעלם; עליכם להשתדל להחזירם. חכמינu הקדישu דיונים שלמים למצווה זו: כמה חייבים להשתדל, מה מותר לשמור כשכר על הטרחה, ולמה החזרat רכוש הוא גם החזרat כבוד.",
    "התפללu על המשיח!!!!!!! — הוגש על ידי EV. האמונה בביאat המשיח היא אחד משlosh עיקרי האמונה — אנחנu מצפים למלך מבית דוד שיבנה את המקדש, יקבץ את הגולה וימלא את העולם בדעat ה'. חachamenu מלמדים שיהודי חייב לחיות בכל יום בציפייה לגאולה. כשאתם מתפללים על המשיח, אתם מביעים תקווה לעולם של שלום, קדושה וגילוי מלא של נוכחות ה'.",
    "קחu דקה להתפלל על צרכיו של מישהu אחר לפני שלכם. חachamenu מלמדים סוד מופלא: כשאתם מתפללים עבור אדם אחר וגם אתם זקוקים לאותו דבר — נענים אתם קודם. הצבat צרכיו של אחר לפני שלכם הופכת תפילה מרשימת משאלות אישית למעשה אהבה לכל עם ישראל.",
    "נסu לעשות שלום בין שני אנשים שאתם מכירים שכרגע רבים. השכר על כך גדול מאוד! הillel לימד אותנu להיות בין תalmidei אהרן — אוהבי שלום ורodefei שלום, שקיבלu כל אדם בחום וקרבu אותו לתורה. חachamenu מלמדים שהשלום כל כך יקר, שה' מאפשר למחוק את שמו הקדוש כדי לשקם שלום בין בעל ואישה. לעזור לשניים להתפיis עשוי להיות מאחד ממעשי החסד הגדולים בעולם.",
    "בפעם הבאה שיש לכם אורחים, זכרו ללוות אותם בדרכם כשהם יוצאים, אפילo כמה צעדים. הגמרא (סוטה מו ע״ב) אומרת ששכר הליווי אין לו שיעור!",
    "התקשרu למישהu שמרגיש בודד. הוגש על ידי: Amy. חachamenu מאזירים לעולם לא להפריד את עצמכם מהצibur — כי יהודי זקוק לקשר כדי לפרוח. ביקור חולים מסיר שישים מסבלם, ובדידות יכולה להיות מחלה בפני עצמה. שיחת טלפון, הודעה או ביקור אומרים למישהu שהוא חשוב — ואהבat ישראel היא אחת היסודות של כל מה שאנחנu עומדים עליו.",
    "למדו על אמירat שma! חדשות טובות — אפשר לומר אותה עומד, בהליכה, ואפילo ברכיבה על החמור הנאמן שלכם (או במכונית, בזמנים מודרניים 😉). רק אל תנסu לומר אותה שוכbים על הגב או על הפנים — זה אסור. שכיבה על הצד מותרת לגמרי! ואם אינכם מרגישים טוב או לא יכולים להתהפך לצד? אין בעיה — נטu מעט לצד ואתם מסודרים. המפתח הוא לומר אותה בדרך שמראה כבוד, ועדיין באופן מעשי למצב שלכם.",
    "למדו קצת הלכה — כשאתם מקיימים את מצוat אמירat שma (פסוקי תורה המכריזים על אחדות ה'), זכרו פרט חשוב: אם אתם הולכים, עצרu לרגע לומר את הפסוק הראשון העוצמתי — תנu לו את תשומת הלב שמגיעה לו! אחר כך אפשר להמשיך ללכת ולומר את השאר.",
    "למדו הלכה על שma — אם אתם בעבודה כשהגיע זמן לומר שma ואינכם יכולים לומר מאוחר יותר, הנה מה לעשות: קחu הפסקה מלאה מהעבודה לכל הפסקה הראשונה. בין אם אתם עצמאיים או שכירים, מצווה מיוחדת זו קודמת! אחרי הפסקה הראשונה אפשר לעשות multitask ולומר את השאר תוך כדי עבודה. גם אם אתם «על השעון», ה' קודם!",
    "למדו על שולחan הלechem (Shulchan) המדהים! 🍞 קחu רגע ללמוד על שולחan הזהב הזה שהחזיק 12 כיכרות לechem מיוחדות. הנה הנס: הלechem נשאר טרי וחם שבוע שלם עד שהוחלף! עוד יותר מדהים — כשאנשים באו לירושלים לרגל, הכohanim היו מרימים את השולחan ואומרים «ראו כמה אתם אהובים לפני ה'!» ומראים להם את הלechem החם והטרי בן שבוע כהוכחה לאהבat הקבועat של ה'! ❤️",
    "למדו על הkiyor (כיור) המיוחד של המקדש! 🚰 ידעתם? הכohanim היו צריכים לשטof את ידיהם ורגליהם בו-זמנית על ידי הנחat יד ימין על רגל ימין ויד שמאל על רגל שמאל! עמדה ייחודית זו הזכירה להם להיות מסורים לחלוטין לשירות — מראש ועד רגל! בנוסף, המים היו צריכים להיות טריים בכל יום, ומלמדים אותנו להתחיל כל יום בשירות אלוקי מתחdש.",
    "גלו את סוד האבnet הכohanic! 🎗️ ידעתם? בבית המקדש, אבnet של kohen היה באורך 32 אמה (כ-48 רגל)! הנה משהo מדהים: הכohanim היו עוטפים אותו שוב ושוב, שכבה על שכבה. זה מלמד שלפעמים גם לאנשים הקדושים ביותר צריך שכבות הגנה מרובות כדי לשמור על המהות הרוחנית. אתגר היום: למדו על בגדי הכohanim וחשבו מה הם יכולים לסמל.",
    "למדו על מערכat המיחזור של בית המקדש! ♻️ ידעתם? כשבגדי כohanim נשחקו, הם לא נזרקו — הם הפכu לפתilot לנרות המקדש! הנה משהo עוצמתי: אפילo חפצים קדושים שלא יכלו עוד לשרת את מטרatם המקורית קibלו חיים חדשים בשירות ה'. משימat היום: למדו על המנהג הזה והתבונnu במציאat מטרה חדשה בכל דבר.",
    "למדו על מידות הר הבית! 🏛️ הר מוריה, הר הבית שעליו עמד בית המקדש, מדד 500 אמה על 500 אמה והיה מוקף חומה. ידעתם? כל האדמה מתחתיו הייתה חלולה ונתמכה על ידי קshatot כדי למנוע טומאat מקברים מתחת!",
]

# Fix remaining corrupted Hebrew fragments
HE_FIXES = {
    "חachamenu": "חכמינו", "חכמינu": "חכמינו", "התפללu": "התפללו", "ביאat": "ביאת",
    "שlosh": "שלושה", "דעat": "דעat", "אנחנu": "אנחנו", "קחu": "קחו",
    "מישהu": "מישהו", "הצבat": "הצבat", "נסu": "נסu", "הillel": "הillel",
    "תalmidei": "תalmidei", "רodefei": "רodefei", "קיבלu": "קיבלu", "קרבu": "קרבu",
    "התפיis": "התפיis", "אפילo": "אפילu", "התקשרu": "התקשרu", "הצibur": "הצibur",
    "אהבat": "אהבat", "ישראel": "ישראel", "אמירat": "אמירat", "שma": "שma",
    "עצרu": "עצרu", "תנu": "תנu", "נטu": "נטu", "מצוat": "מצוות",
    "שוכbים": "שוכbים", "שולחan": "שולחan", "לechem": "לechem",
    "הכohanim": "הכohanim", "אהבat": "אהבat", "הkiyor": "הkiyor",
    "שטof": "שטof", "הנחat": "הנחat", "מתחdש": "מתחdש", "אבnet": "אבnet",
    "משהo": "משהo", "מערכat": "מערכat", "הפכu": "הפכu", "פתilot": "פתilot",
    "מטרatם": "מטרatם", "קibלו": "קibלu", "משימat": "משימat",
    "התבונnu": "התבונnu", "מציאat": "מציאat", "קshatot": "קshatot",
    "טומאat": "טומאat", "החזרat": "החזרat", "הקדישu": "הקדישu",
}

# Replace corrupted strings 5-18 with clean Hebrew
local_006_he[4] = "ראיתם לאחרונה חפץ אבוד? 🔍 אל תתעלמו! חזרו ונסו להחזיר אותו לבעליו (אם אפשר). זו מצוות השבת אבידה (Hashavat Aveidah). התורה מלמדת שאם אתם רואים את בהמתו או חפציו של חברכם הולכים ותועים — אסור להתעלם; עליכם להשתדל להחזירם. חכמינu הקדישu דיונים שלמים למצווה זו: כמה חייבים להשתדל, מה מותר לשמור כשכר על הטרחה, ולמה החזרat רכוש הוא גם החזרat כבוד."

print("need more fixes")
