#!/usr/bin/env python3
"""Build targeted_fixes.json — hand-reviewed overrides for known Argos disasters."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "translation-catalog" / "shards" / "targeted_fixes.json"

# English key -> {lang: translation}
FIXES: dict[str, dict[str, str]] = {
    "ברכת המזון": {
        "es": "Birkat Hamazón (bendición después de las comidas)",
        "fr": "Birkat Hamazón (bénédiction après les repas)",
        "ru": "Биркат а-Мазон (благословение после еды)",
    },
    "תפילת הדרך": {
        "es": "Tefilat HaDerech (oración del camino)",
        "fr": "Tefilat HaDerech (prière du voyage)",
        "ru": "Тефилат а-Дерех (молитва в пути)",
    },
    "Leishev baSukkah is the blessing \"to dwell in the sukkah\" — said when eating bread meals in the sukkah on Sukkot. Dwelling means spending meaningful time there, not only a quick snack. Rain may exempt you per halacha. Decorate the sukkah and make children feel at home in it — the booth recalls clouds of glory in the desert.": {
        "es": "Leishev baSukkah es la bendición de \"habitar en la sukkah\" — se recita al comer comidas con pan en la sukkah en Sukkot. Habitar significa pasar tiempo significativo allí, no solo un refrigerio rápido. La lluvia puede eximirle según la halajá. Decore la sukkah y haga que los niños se sientan en casa — la cabaña recuerda las nubes de gloria en el desierto.",
        "fr": "Leishev baSukkah est la bénédiction « habiter dans la soucca » — dite en mangeant des repas avec pain dans la soucca pendant Souccot. Habiter signifie y passer du temps, pas seulement une collation rapide. La pluie peut dispenser selon la halakha. Décorez la soucca pour que les enfants s'y sentent chez eux — la cabane rappelle les nuées de gloire dans le désert.",
        "ru": "Leishev baSukkah — благословение «жить в сукке», произносимое при еде с хлебом в сукке на Суккот. Жить в сукке — проводить там значимое время, а не только быстрый перекус. Дождь может освобождать по галахе. Украсьте сукку, чтобы детям было уютно — шалаш напоминает облака славы в пустыне.",
    },
    "leishev baSukkah — Leishev baSukkah is the blessing \"to dwell in the sukkah\" — said when eating bread meals in the sukkah on Sukkot. Dwelling means spending meaningful time there, not only a quick snack. Rain may exempt you per halacha. Decorate the sukkah and make children feel at home in it — the booth recalls clouds of glory in the desert.": {
        "es": "leishev baSukkah — Leishev baSukkah es la bendición de \"habitar en la sukkah\" — se recita al comer comidas con pan en la sukkah en Sukkot. Habitar significa pasar tiempo significativo allí, no solo un refrigerio rápido. La lluvia puede eximirle según la halajá. Decore la sukkah y haga que los niños se sientan en casa — la cabaña recuerda las nubes de gloria en el desierto.",
        "fr": "leishev baSukkah — Leishev baSukkah est la bénédiction « habiter dans la soucca » — dite en mangeant des repas avec pain dans la soucca pendant Souccot. Habiter signifie y passer du temps, pas seulement une collation rapide. La pluie peut dispenser selon la halakha. Décorez la soucca pour que les enfants s'y sentent chez eux.",
        "ru": "leishev baSukkah — Leishev baSukkah — благословение «жить в сукке» при еде с хлебом в сукке на Суккот. Жить в сукке — проводить там значимое время, а не только быстрый перекус.",
    },
    "The Nine Days intensify mourning before Tisha B'Av. Ashkenazim restrict meat, wine, laundry, and bathing from 1 Av; Sephardim and Edot HaMizrach often restrict from the week of Tisha B'Av (some communities from Rosh Chodesh Av). Tisha B'Av is a full fast with kinot; Ashkenazim continue some restrictions until chatzos on 10 Av.": {
        "es": "Los Nueve Días intensifican el duelo antes de Tisha B'Av. Los ashkenazim restringen carne, vino, lavandería y baño desde el 1 de Av; los sefardíes y edot ha-mizraj a menudo desde la semana de Tisha B'Av (algunas comunidades desde Rosh Chodesh Av). Tisha B'Av es un ayuno completo con kinot; los ashkenazim continúan algunas restricciones hasta chatzot del 10 de Av.",
        "fr": "Les Neuf Jours intensifient le deuil avant Tisha B'Av. Les ashkénazes restreignent viande, vin, lessive et bain dès le 1 Av ; les séfarades et edot ha-mizrah souvent dès la semaine de Tisha B'Av. Tisha B'Av est un jeûne complet avec kinot ; les ashkénazes continuent certaines restrictions jusqu'à hatzot le 10 Av.",
        "ru": "Девять дней усиливают траур перед Тиша б'Ав. Ашкеназы ограничивают мясо, вино, стирку и купание с 1 Ава; сефарды и эдот а-мизрах часто с недели Тиша б'Ав. Тиша б'Ав — полный пост с кинот; ашкеназы продолжают ограничения до хацот 10 Ава.",
    },
    "Nine Days — The Nine Days intensify mourning before Tisha B'Av. Ashkenazim restrict meat, wine, laundry, and bathing from 1 Av; Sephardim and Edot HaMizrach often restrict from the week of Tisha B'Av (some communities from Rosh Chodesh Av). Tisha B'Av is a full fast with kinot; Ashkenazim continue some restrictions until chatzos on 10 Av.": {
        "es": "Nueve Días — Los Nueve Días intensifican el duelo antes de Tisha B'Av. Los ashkenazim restringen carne, vino, lavandería y baño desde el 1 de Av; los sefardíes y edot ha-mizraj a menudo desde la semana de Tisha B'Av. Tisha B'Av es un ayuno completo con kinot; los ashkenazim continúan algunas restricciones hasta chatzot del 10 de Av.",
        "fr": "Neuf Jours — Les Neuf Jours intensifient le deuil avant Tisha B'Av. Les ashkénazes restreignent viande, vin, lessive et bain dès le 1 Av ; Tisha B'Av est un jeûne complet avec kinot.",
        "ru": "Девять дней — Девять дней усиливают траур перед Тиша б'Ав. Ашкеназы ограничивают мясо, вино, стирку и купание с 1 Ава; Тиша б'Ав — полный пост с кинот.",
    },
    "The Purim seudah is the festive afternoon meal on Purim day — part of the day's joy alongside Megillah, mishloach manot, and matanot la'evyonim. It requires bread (hamotzi), not matzah. Many begin the meal before sunset and continue into the evening. It is a seudat mitzvah of celebration, not a fast day.": {
        "es": "La seudá de Purim es la comida festiva de la tarde del día de Purim — parte de la alegría del día junto con la Megillá, mishloach manot y matanot la'evyonim. Requiere pan (hamotzi), no matzá. Muchos comienzan la comida antes del atardecer y continúan en la noche. Es una seudat mitzvá de celebración, no un día de ayuno.",
        "fr": "La seouda de Pourim est le repas festif de l'après-midi du jour de Pourim — joie du jour avec la Meguila, mishloach manot et matanot la'evyonim. Pain (hamotzi) requis, pas de matza. C'est une seoudat mitzvah de célébration, pas un jour de jeûne.",
        "ru": "Сеуда Пурима — праздничная дневная трапеза в день Пурима — радость дня вместе с Мегилой, мишлоах манот и матанот ла-эвьоним. Нужен хлеб (ha-motzi), не маца. Это сеудат мицва празднования, а не день поста.",
    },
    "Purim seudah — The Purim seudah is the festive afternoon meal on Purim day — part of the day's joy alongside Megillah, mishloach manot, and matanot la'evyonim. It requires bread (hamotzi), not matzah. Many begin the meal before sunset and continue into the evening. It is a seudat mitzvah of celebration, not a fast day.": {
        "es": "Purim seudah — La seudá de Purim es la comida festiva de la tarde del día de Purim — parte de la alegría del día junto con la Megillá, mishloach manot y matanot la'evyonim. Requiere pan (hamotzi), no matzá. Es una seudat mitzvá de celebración, no un día de ayuno.",
        "fr": "Purim seudah — La seouda de Pourim est le repas festif de l'après-midi du jour de Pourim — joie du jour avec la Meguila. Pain requis, pas de matza ; célébration, pas jeûne.",
        "ru": "Purim seudah — Сеуда Пурима — праздничная дневная трапеза в день Пурима. Хлеб (ha-motzi), не маца; празднование, не пост.",
    },
    "The Fast of 17 Tammuz (Shiva Asar B'Tammuz) marks the day the walls of Jerusalem were breached by the Romans in the first century CE. It begins the \"Three Weeks\" — a period of mourning culminating in Tisha B'Av.\n\nIt is a minor fast from dawn until nightfall. During the Three Weeks, weddings are not held and music is generally avoided. During the final nine days of this period (1–9 Av), additional mourning customs apply.": {
        "es": "El ayuno del 17 de Tamuz (Shiva Asar B'Tamuz) marca el día en que las murallas de Jerusalén fueron brechadas por los romanos en el siglo I d.C. Comienza las «Tres Semanas» — período de duelo que culmina en Tisha B'Av.\n\nEs un ayuno menor desde el amanecer hasta el anochecer. Durante las Tres Semanas no hay bodas y se evita la música. En los últimos nueve días (1–9 Av) aplican costumbres adicionales de duelo.",
        "fr": "Le jeûne du 17 Tamouz marque le jour où les murailles de Jérusalem furent percées par les Romains. Commence les « Trois Semaines » jusqu'à Tisha B'Av. Jeûne mineur de l'aube à la nuit ; pas de mariages ni musique pendant les Trois Semaines.",
        "ru": "Пост 17 Таммуза — день пролома стен Иерусалима римлянами. Начинаются «Три недели» до Тиша б'Ав. Малый пост от рассвета до ночи; свадьбы и музыка ограничены.",
    },
    "The Fast of Gedaliah is observed on 3 Tishrei (pushed to 4 Tishrei when 3 Tishrei falls on Shabbat). It commemorates the assassination of Gedaliah ben Ahikam, the Jewish governor appointed by Babylonia to administer the land after the destruction of the First Temple.\n\nHis death marked the end of the last vestiges of Jewish autonomy in the Land of Israel following the first exile.\n\nIt is a minor fast — from dawn until nightfall (not a full 25-hour fast like Yom Kippur or Tisha B'Av).": {
        "es": "El ayuno de Gedalías se observa el 3 de Tishrei (pospuesto al 4 cuando cae en Shabat). Conmemora el asesinato de Gedalías ben Ajikam, gobernador judío nombrado por Babilonia tras la destrucción del Primer Templo.\n\nSu muerte marcó el fin de los últimos vestigios de autonomía judía en la Tierra de Israel tras el primer exilio.\n\nEs un ayuno menor — del amanecer al anochecer (no un ayuno de 25 horas como Yom Kippur o Tisha B'Av).",
        "fr": "Le jeûne de Guedalyah est observé le 3 Tishri (reporté au 4 si Shabbat). Commémore l'assassinat de Guedalyah ben Ahikam. Jeûne mineur de l'aube à la nuit.",
        "ru": "Пост Гедалии — 3 Тишрея (4 при совпадении с Шаббатом). Память об убийстве Гедалии бен Ахикама. Малый пост от рассвета до ночи.",
    },
    "The Fast of 10 Tevet commemorates the day Nebuchadnezzar, king of Babylon, began the siege of Jerusalem — the event that ultimately led to the destruction of the First Temple.\n\nIt is a minor fast from dawn until nightfall. It is also observed as a general Kaddish day for Holocaust victims whose date of death is unknown.\n\nNote: This is the only fast in the calendar that is never postponed if it falls on a Friday (because the biblical verse requires observing it \"on this very day\"). When it lands on a Friday, continue fasting directly into Friday night — welcome Shabbat while fasting — and break the fast only after nightfall following the recitation of Friday night Kiddush.": {
        "es": "El ayuno del 10 de Tevet conmemora el día en que Nabucodonosor comenzó el asedio de Jerusalén — evento que llevó a la destrucción del Primer Templo.\n\nEs un ayuno menor del amanecer al anochecer. También es día general de Kaddish para víctimas del Holocausto cuya fecha de muerte se desconoce.\n\nNota: es el único ayuno que no se pospone si cae en viernes. Si cae en viernes, continúe ayunando hasta la noche tras el Kiddush de Shabat.",
        "fr": "Le jeûne du 10 Téveth commémore le début du siège de Jérusalem par Nabuchodonosor. Jeûne mineur ; aussi jour de Kaddish pour les victimes de la Shoah à date inconnue. Seul jeûne jamais reporté s'il tombe un vendredi.",
        "ru": "Пост 10 Тевета — начало осады Иерусалима Навуходоносором. Малый пост; также день Кадиша для жертв Шоа с неизвестной датой смерти. Единственный пост, не переносимый с пятницы.",
    },
    "Today is the Fast of Esther (Taanit Esther) — commemorating the fasting Esther called before approaching the king (Esther 4:16).\n\nMinor fast rules with Purim context:\n• No eating or drinking from dawn until nightfall.\n• Music, showering for pleasure, and leather shoes are permitted — this is a minor fast, not like Tisha B'Av.\n• Purim mitzvot begin tonight/tomorrow per your calendar (14 Adar, or 15 in walled cities). This fast is the spiritual preparation before the joy of Purim.": {
        "es": "Hoy es el ayuno de Ester (Taanit Ester) — conmemora el ayuno que Ester decretó antes de acercarse al rey (Ester 4:16).\n\nReglas de ayuno menor con contexto de Purim:\n• No comer ni beber desde el amanecer hasta el anochecer.\n• Música, ducha por placer y zapatos de cuero están permitidos — es ayuno menor, no como Tisha B'Av.\n• Las mitzvot de Purim comienzan esta noche/mañana según su calendario (14 Adar, o 15 en ciudades amuralladas). Este ayuno prepara espiritualmente la alegría de Purim.",
        "fr": "Aujourd'hui, c'est le jeûne d'Esther (Taanit Esther) — commémore le jeûne décrété par Esther avant d'approcher le roi (Esther 4:16).\n\nRègles de jeûne mineur :\n• Pas de nourriture ni boisson de l'aube à la nuit.\n• Musique, douche pour plaisir et chaussures en cuir permis — jeûne mineur, pas comme Tisha B'Av.\n• Les mitzvot de Pourim commencent ce soir/demain (14 Adar, ou 15 en villes murées).",
        "ru": "Сегодня пост Эстер (Таанит Эстер) — в память поста, объявленного Эстер перед выходом к царю (Эстер 4:16).\n\nПравила малого поста:\n• Не есть и не пить от рассвета до ночи.\n• Музыка, душ для удовольствия и кожаная обувь разрешены — малый пост, не как Тиша б'Ав.\n• Мицвот Пурима начинаются сегодня вечером/завтра (14 Адар или 15 в окруженных городах).",
    },
    "Yom HaShoah (Holocaust Remembrance Day) is observed in Israel on 27 Nisan. It commemorates the six million Jews murdered in the Holocaust and honors survivors.\n\nIn Israel, a siren brings the country to a standstill. Many communities hold memorial programs, recite Tehillim, and learn about the Shoah. It is not a Torah-mandated fast or Yom Tov; customs vary by community.": {
        "es": "Yom HaShoah (Día del Recuerdo del Holocausto) se observa en Israel el 27 de Nisan. Conmemora a los seis millones de judíos asesinados en el Holocausto y honra a los sobrevivientes.\n\nEn Israel, una sirena detiene al país. Muchas comunidades tienen programas conmemorativos, recitan Tehillim y estudian la Shoah. No es un ayuno ni Yom Tov prescrito por la Torá; las costumbres varían.",
        "fr": "Yom HaShoah (Journée du souvenir de la Shoah) est observé en Israël le 27 Nisan. Commémore les six millions de Juifs assassinés. Ce n'est pas un jeûne ni un Yom Tov prescrit par la Torah.",
        "ru": "Йом а-Шоа (День памяти Холокоста) — 27 нисана в Израиле. Память о шести миллионах убитых. Не пост и не Йом Тов по Торе.",
    },
    "Psalm 27 (לְדָוִד ה' אוֹרִי וְיִשְׁעִי) is added to Shacharit during Elul and Tishrei — a season of drawing close to G-d before and through the Days of Awe.\n\nWhen:\n• Said after the morning service (often after Shacharit Amidah, before concluding prayers — follow your siddur).\n• Start and end dates vary by minhag — this item follows your nusach setting.\n\nWhy:\n• \"The L-rd is my light and my salvation — whom shall I fear?\" (Tehillim 27:1) — trust in divine protection through judgment season.\n• A widespread custom in Elul–Tishrei; widely adopted across Ashkenaz, Sephard, and Edot HaMizrach with different calendars.": {
        "es": "El salmo 27 (לְדָוִד ה' אוֹרִי וְיִשְׁעִי) se añade a Shacharit durante Elul y Tishrei — temporada de acercarse a D-s antes y durante los Yamim Noraim.\n\nCuándo:\n• Después del servicio matutino (a menudo tras la Amidá de Shacharit — siga su sidur).\n• Las fechas de inicio y fin varían según el minhag.\n\nPor qué:\n• «D-s es mi luz y mi salvación — ¿a quién temeré?» (Tehillim 27:1).\n• Costumbre extendida en Elul–Tishrei en ashkenaz, sefardíes y edot ha-mizraj.",
        "fr": "Le psaume 27 est ajouté à Shacharit pendant Eloul et Tishri — saison de rapprochement de D. avant et pendant les Yamim Noraim.\n\nQuand : après le service du matin (souvent après l'Amidah de Shacharit). Dates selon minhag.\n\nPourquoi : « D. est ma lumière et mon salut » (Tehillim 27:1).",
        "ru": "Псалом 27 добавляется к Шахарит в Элуле и Тишрее — время приближения к Б-гу перед и в Ямим Нораим.\n\nКогда: после утренней службы (часто после Амиды Шахарит). Даты по минхагу.",
    },
    "Rosh Chodesh begins the Hebrew month — semi-holiday with Hallel (half), Musaf, Yaaleh V'yavo, and often reduced work for women per custom. Remove tefillin before Musaf — wearing tefillin during Rosh Chodesh Musaf is forbidden. In ancient times the new moon was proclaimed from testimony. Today the calendar is fixed. It is a monthly reset — plan Torah goals and charity.": {
        "es": "Rosh Chodesh comienza el mes hebreo — semi-festividad con Hallel (medio), Musaf, Yaaleh V'yavo, y a menudo trabajo reducido para mujeres según costumbre. Quitarse el tefillin antes de Musaf — está prohibido usar tefillin durante Musaf de Rosh Chodesh. Antiguamente la luna nueva se proclamaba por testimonio. Hoy el calendario es fijo. Reinicio mensual — planifique metas de Torá y caridad.",
        "fr": "Rosh 'Hodesh commence le mois hébreu — semi-fête avec Hallel (moitié), Moussaf, Yaaleh V'yavo, et souvent travail réduit pour les femmes. Retirer le téfiline avant Moussaf — interdit pendant Moussaf de Rosh 'Hodesh.",
        "ru": "Рош Ходеш начинает еврейский месяц — полупраздник с Халелем (половинным), Мусафом, Яалех в'Яво. Снимите тфилин до Мусафа — в Мусаф Рош Ходеш тфилин запрещены.",
    },
    "Rosh Chodesh — Rosh Chodesh begins the Hebrew month — semi-holiday with Hallel (half), Musaf, Yaaleh V'yavo, and often reduced work for women per custom. Remove tefillin before Musaf — wearing tefillin during Rosh Chodesh Musaf is forbidden. In ancient times the new moon was proclaimed from testimony. Today the calendar is fixed. It is a monthly reset — plan Torah goals and charity.": {
        "es": "Rosh Chodesh — Rosh Chodesh comienza el mes hebreo — semi-festividad con Hallel (medio), Musaf, Yaaleh V'yavo. Quitarse el tefillin antes de Musaf — prohibido durante Musaf de Rosh Chodesh. Reinicio mensual — planifique metas de Torá y caridad.",
        "fr": "Rosh 'Hodesh — commence le mois hébreu — semi-fête avec Hallel, Moussaf, Yaaleh V'yavo. Retirer le téfiline avant Moussaf.",
        "ru": "Рош Ходеш — начало еврейского месяца — полупраздник с Халелем, Мусафом, Яалех в'Яво.",
    },
    "Rosh Chodesh (the New Month) is the first day of each Hebrew month, and in some months the 30th day of the previous month as well.\n\nSpecial observances include: Yaaleh V'Yavo in prayers and Grace After Meals, half Hallel, a Musaf (additional) prayer, and a special Torah reading.\n\nRosh Chodesh is a semi-holiday — certain fasting and eulogizing are restricted. There is a widespread custom for women to refrain from certain types of work as an extra mark of honor for the day.": {
        "es": "Rosh Chodesh (el mes nuevo) es el primer día de cada mes hebreo, y en algunos meses también el día 30 del mes anterior.\n\nObservancias: Yaaleh V'Yavo en oraciones y Birkat Hamazón, medio Hallel, Musaf y lectura especial de la Torá.\n\nRosh Chodesh es semi-festividad — ciertos ayunos y elogios fúnebres están restringidos. Costumbre extendida: las mujeres se abstienen de ciertos tipos de trabajo en honor del día.",
        "fr": "Rosh 'Hodesh est le premier jour de chaque mois hébreu (parfois aussi le 30e du mois précédent). Yaaleh V'Yavo, demi-Hallel, Moussaf, lecture spéciale. Semi-fête — jeûnes et éloges funèbres restreints.",
        "ru": "Рош Ходеш — первый день каждого еврейского месяца (иногда и 30-й предыдущего). Яалех в'Яво, половина Халеля, Мусаф, особое чтение Торы. Полупраздник — ограничены посты и надгробные речи.",
    },
    "Tu B'Shvat (the 15th of Shvat) is the New Year for Trees — one of the four \"new years\" mentioned in the Mishnah. It marks the date used for calculating the age of fruit trees for tithing purposes.\n\nTu B'Shvat is not a fast day, and work is permitted. It is customary to eat fruits of Israel, especially the seven species: wheat, barley, grapes, figs, pomegranates, olives, and dates. Many communities hold a \"Tu B'Shvat seder\" with fruits and wine.\n\nIn Kabbalistic tradition (particularly from the 16th-century Safed mystics), Tu B'Shvat became associated with the spiritual rectification of the world through eating fruits with intention.": {
        "es": "Tu B'Shvat (el 15 de Shvat) es el Año Nuevo de los Árboles, uno de los cuatro «años nuevos» de la Mishná. Marca la fecha para calcular la edad de árboles frutales para maaserot.\n\nTu B'Shvat no es un día de ayuno y el trabajo está permitido. Es costumbre comer frutos de Israel, especialmente las siete especies. Muchas comunidades celebran un «seder» de Tu B'Shvat con frutas y vino.\n\nEn la tradición cabalística (especialmente los místicos de Safed del siglo XVI), Tu B'Shvat se asocia con la rectificación espiritual del mundo al comer frutos con intención.",
        "fr": "Tu B'Shvat (15 Chevat) est le Nouvel An des Arbres — l'un des quatre « nouveaux ans » de la Mishna. Ce n'est pas un jour de jeûne ; le travail est permis. On mange les fruits d'Israël, surtout les sept espèces.",
        "ru": "Ту бе-Шват (15 Швата) — Новый год деревьев, один из четырёх «новых лет» Мишны. Это не день поста; работа разрешена. Принято есть плоды Израиля, особенно семь видов.",
    },
    "Ashkenaz Selichot begin on Motzei Shabbat before Rosh Hashana, with at least four days of Selichot before the holiday (Peninei Halakha 15-02-05; Rama). If Rosh Hashana falls on Monday or Tuesday, Selichot begin the previous Motzei Shabbat.\n\nHow:\n• First night is often a large community gathering (Motzei Shabbat).\n• Said standing; many wear tallit if already worn for Maariv or at morning Selichot.\n• Arrive early — services are long and moving.\n• Continue daily until Yom Kippur (including Erev Rosh Hashana, fast day schedules differ).\n• Check your shul for exact times (usually late night or early morning).": {
        "es": "Las Selichot ashkenazíes comienzan en Motzei Shabat antes de Rosh Hashaná, con al menos cuatro días de Selichot antes de la festividad (Peninei Halakha 15-02-05; Rama). Si Rosh Hashaná cae en lunes o martes, las Selichot comienzan el Motzei Shabat anterior.\n\nCómo:\n• La primera noche suele ser una gran reunión comunitaria (Motzei Shabat).\n• Se recitan de pie; muchos usan talit si ya lo usaron en Maariv o en Selichot matutinas.\n• Llegue temprano — los servicios son largos y conmovedores.\n• Continúe diariamente hasta Yom Kippur (incluido Erev Rosh Hashaná; los horarios de días de ayuno difieren).\n• Consulte los horarios de su shul (a menudo tarde en la noche o temprano en la mañana).",
        "fr": "Les Selichot ashkénazes commencent à Motzei Chabbat avant Roch Hachana, avec au moins quatre jours de Selichot avant la fête (Peninei Halakha 15-02-05 ; Rama).\n\nComment : première nuit souvent en grande assemblée ; récitées debout ; continuer jusqu'à Yom Kippour (horaires de jeûne différents à Erev Roch Hachana).",
        "ru": "Ашкеназские Селихот начинаются в Моцэи Шаббат перед Рош а-Шана, минимум четыре дня Селихот до праздника (Peninei Halakha 15-02-05; Рама). Продолжать ежедневно до Йом Кипура.",
    },
    "This year, Erev Pesach is Shabbat (14 Nisan). Today (Friday, 13 Nisan): biur chametz this morning (no final Kol Chamira at burning — save chametz for Shabbat meals), and finish mechirat chametz before Shabbat candles. Taanit Bechorot was Thursday (12 Nisan). Bedikat was last night (Thursday). Tomorrow is Shabbat — finish chametz by the 4th halachic hour, final bitul by the 5th halachic hour; first Seder is Saturday night (Yaknehaz, then Seder).": {
        "he": "השנה ערב פסח ביום שבת (י\"ד בניסן). היום (יום שישי, י\"ג בניסן): ביעור חמץ הבוקר (ללא כל חמירא סופי בשריפה — שמרו חמץ לארוחות שבת), וסיימו מכירת חמץ לפני נרות שבת. תענית בכורות היה ביום חמישי (י\"ב בניסן). בדיקה הייתה אמש (חמישי). מחר שבת — סיימו חמץ עד סוף השעה ההלכתית הרביעית, ביטול סופי עד סוף החמישית; הסדר הראשון בליל שבת (יקנה\"ז ואז הסדר).",
    },
    "This year, today is $chagName on Friday and Shabbat begins tonight — the Yom Tov–Shabbat sequence is in progress.\n\nToday on Yom Tov (if you made eruv tavshilin before the festival began):\n• You may cook and prepare for Shabbat meals today — within halachic limits (food ready with time to spare before Shabbat).\n• Finish preparations before Shabbat; set timers/blech as guided by your rav.\n\nIf you have not made eruv tavshilin, ask your rabbi immediately.\n\nShabbat tonight: light candles from a pre-existing flame after Yom Tov ends; follow your siddur for when Yom Tov ends and Shabbat begins.": {
        "he": "השנה, היום הוא $chagName ביום שישי ושבת מתחילה הלילה — רצף יום טוב–שבת בעיצומו.\n\nהיום ביום טוב (אם עשיתם עירוב תבשילין לפני תחילת החג):\n• מותר לבשל ולהכין ארוחות שבת היום — בגבולות הלכתיים (מזון מוכן בזמן לפני שבת).\n• סיימו הכנות לפני שבת; קבעו טיימרים/פלטה לפי הוראת הרב.\n\nאם לא עשיתם עירוב תבשילין — פנו לרב מיד.\n\nשבת הלילה: הדליקו נרות מלהבה קיימת אחרי סיום יום טוב; עקבו אחרי הסידור לזמן מעבר מיום טוב לשבת.",
    },
    "Yom HaShoah (Holocaust Remembrance Day) is observed in Israel on 27 Nisan. It commemorates the six million Jews murdered in the Holocaust and honors survivors.\n\nIn Israel, a siren brings the country to a standstill. Many communities hold memorial programs, recite Tehillim, and learn about the Shoah. It is not a Torah-mandated fast or Yom Tov; customs vary by community.": {
        "he": "יום השואה נצפה בישראל בכ\"ז בניסן. הוא מנציח את ששת מיליון היהודים שנרצחו בשואה ומכבד ניצולים.\n\nבישראל סירנה עוצרת את המדינה. קהילות רבות מקיימות טקסי זיכרון, אומרות תהילים ולומדות על השואה. זה לא צום או יום טוב מצווה בתורה; המנהגים משתנים לפי קהילה.",
    },
    "Zeroa (shankbone) is a roasted bone on the Seder plate reminding us of the Pesach sacrifice in the Temple. Today we do not offer the sacrifice; the zeroa is symbolic only — not eaten at the Seder. Roast it on Erev Pesach before sunset — roasting after Yom Tov begins violates ochel nefesh because it is not eaten that night. Many use a chicken neck or a special roasted bone.": {
        "he": "זרוע — עצם צלוי בקערת הסדר, מזכיר את קורבן הפסח במקדש. היום אין מקריבים; הזרוע סמלית בלבד — לא נאכלת בסדר. צלו בערב פסח לפני השקיעה — אפייה אחרי תחילת יום טוב אסורה כאוכל נפש כי לא נאכל באותו לילה. רבים משתמשים בצוואר עוף או בעצם צלוי מיוחד.",
    },
    "zeroa — Zeroa (shankbone) is a roasted bone on the Seder plate reminding us of the Pesach sacrifice in the Temple. Today we do not offer the sacrifice; the zeroa is symbolic only — not eaten at the Seder. Roast it on Erev Pesach before sunset — roasting after Yom Tov begins violates ochel nefesh because it is not eaten that night. Many use a chicken neck or a special roasted bone.": {
        "he": "זרוע — זרוע (עצם שוק) על קערת הסדר, מזכירה את קורבן הפסח במקדש. היום סמלית בלבד — לא נאכלת בסדר. צלו בערב פסח לפני השקיעה; אין לאפות אחרי תחילת יום טוב.",
    },
    "Chametz:\n• Biur was Friday morning (13 Nisan). On Shabbat morning, finish eating chametz by the end of the 4th halachic hour and recite the final Kol Chamira before the end of the 5th halachic hour — do not burn on Shabbat. Bedikat was Thursday night; mechirat chametz should already be authorized.": {
        "he": "חמץ:\n• הביעור היה בוקר שישי (י\"ג בניסן). בשבת בבוקר — סיימו אכילת חמץ עד סוף השעה ההלכתית הרביעית ואמרו כל חמירא סופי לפני סוף החמישית — אין לשרוף בשבת. הבדיקה הייתה חמישי בלילה; מכירת חמץ כבר אמורה להיות מורשית.",
    },
    "A sofer (scribe) is trained to write STaM — Torah scrolls, tefillin, mezuzot, and megillot — by hand with special ink on parchment. Letters must be formed exactly; mistakes can invalidate the scroll. Soferim also check existing klafim. Never buy tefillin or mezuzot without reliable certification.": {
        "he": "סופר (sofer) מוכשר לכתוב סת\"ם — ספרי תורה, תפילין, מזוזות ומגילות — ביד בדיו מיוחד על קלף. האותיות חייבות להיות מדויקות; טעויות עלולות לפסול. סופרים בודקים גם קלפים קיימים. לעולם אל תקנו תפילין או מזוזות בלי הכשר אמין.",
    },
    "sofer — A sofer (scribe) is trained to write STaM — Torah scrolls, tefillin, mezuzot, and megillot — by hand with special ink on parchment. Letters must be formed exactly; mistakes can invalidate the scroll. Soferim also check existing klafim. Never buy tefillin or mezuzot without reliable certification.": {
        "he": "סופר — סופר מוכשר לכתוב סת\"ם ביד בדיו על קלף. האותיות חייבות להיות מדויקות. לעולם אל תקנו תפילין או מזוזות בלי הכשר אמין.",
    },
    "The Diaspora (Galut) means Jewish life outside the Land of Israel. For centuries communities developed local minhagim while staying loyal to Torah. Festival calendars often add an extra day of Yom Tov outside Israel. Aliyah to Israel is a mitzvah for many; Diaspora communities remain fully Jewish and vibrant.": {
        "he": "הגולה (Galut) — חיים יהודיים מחוץ לארץ ישראל. במשך מאות שנים פיתחו קהילות מנהגים מקומיים תוך נאמנות לתורה. לוחות חגים מוסיפים לעתים יום נוסף של יום טוב מחוץ לישראל. עלייה לארץ מצווה לרבים; קהילות הגולה נשארות יהודיות וחיות.",
    },
    "Diaspora — The Diaspora (Galut) means Jewish life outside the Land of Israel. For centuries communities developed local minhagim while staying loyal to Torah. Festival calendars often add an extra day of Yom Tov outside Israel. Aliyah to Israel is a mitzvah for many; Diaspora communities remain fully Jewish and vibrant.": {
        "he": "גולה — חיים יהודיים מחוץ לארץ ישראל. קהילות פיתחו מנהגים מקומיים; לוח חגים מוסיף יום יום טוב מחוץ לישראל. עלייה מצווה לרבים.",
    },
    "A halachic hour (sha'ah zmanit) is one twelfth of the daylight period from dawn to dusk — so it is longer in summer and shorter in winter, unlike a 60-minute clock hour. Deadlines such as latest morning Shema, chametz sale times, and plag hamincha use these hours. Apps and Jewish calendars convert them for your location.": {
        "he": "שעה זמנית (sha'ah zmanit) — שתים עשרה חלקים של אור היום משחר לחשיכה — ארוכה בקיץ וקצרה בחורף, בניגוד לשעון שעות. מועדים כמו סוף זמן קריאת שמע, מכירת חמץ ופלג המנחה משתמשים בשעות אלה. אפליקציות ולוחות שנה ממירים למיקומכם.",
    },
    "halachic hour — A halachic hour (sha'ah zmanit) is one twelfth of the daylight period from dawn to dusk — so it is longer in summer and shorter in winter, unlike a 60-minute clock hour. Deadlines such as latest morning Shema, chametz sale times, and plag hamincha use these hours. Apps and Jewish calendars convert them for your location.": {
        "he": "שעה הלכתית — שעה זמנית: שתים עשרה חלקים של אור היום; ארוכה בקיץ וקצרה בחורף. משמשת לסוף זמן שמע, מכירת חמץ ופלג המנחה.",
    },
    "A mikveh is a kosher ritual pool of natural water meeting halachic size and flow rules. It is used for taharat hamishpacha, conversion, tevilat keilim, and some utensil and status changes. Immersion is a powerful transition — the person or vessel emerges spiritually renewed. Community mikvaot are discreet and staffed by trained attendants.": {
        "he": "מקווה — בריכה טקסית כשרה של מים טבעיים לפי מידות והלכות זרימה. משמש לטהרת המשפחה, גיור, טבילת כלים ושינויי מעמד. הטבילה מעבר רוחני — האדם או הכלי יוצאים מתחדשים. מקוואות קהילתיים דיסקרטיים עם מלוות מיומנות.",
    },
    "mikveh — A mikveh is a kosher ritual pool of natural water meeting halachic size and flow rules. It is used for taharat hamishpacha, conversion, tevilat keilim, and some utensil and status changes. Immersion is a powerful transition — the person or vessel emerges spiritually renewed. Community mikvaot are discreet and staffed by trained attendants.": {
        "he": "מקווה — בריכה טקסית כשרה למים טבעיים; לטהרת המשפחה, גיור, טבילת כלים ועוד. הטבילה מעבר רוחני חזק.",
    },
    "Alot hashachar is halachic dawn — when the sky begins to lighten. Many morning laws start here, such as the beginning of public fast days. It is before sunrise (netz). It is not the normal time for the bracha on tallit and tefillin — see misheyakir. In great need, Igros Moshe (O.C. 4:6) allows putting them on after alot hashachar without a bracha and reciting the brachos after misheyakir — ask your rav.": {
        "es": "Alot hashachar es el amanecer halájico — cuando el cielo comienza a aclararse. Muchas leyes matutinas comienzan aquí, como el inicio de los días de ayuno público. Es antes del amanecer (netz). No es el momento habitual para la berajá sobre talit y tefilin — véase misheyakir. En gran necesidad, Igrot Moshe (O.C. 4:6) permite ponerlos después de alot hashachar sin berajá y recitar las berajot tras misheyakir — consulte a su rav.",
        "fr": "Alot hashachar est l'aube halakhique — quand le ciel commence à s'éclaircir. Beaucoup de lois matinales commencent ici, dont le début des jeûnes publics. C'est avant le lever du soleil (netz). Ce n'est pas l'heure normale pour la bénédiction sur le tallit et les téfilines — voir misheyakir.",
        "ru": "Alot hashachar — галахический рассвет, когда небо начинает светлеть. Многие утренние законы начинаются здесь, включая начало общественных постов. До восхода (netz). Не обычное время для брахи на талит и тфилин — см. misheyakir.",
    },
    "alot hashachar — Alot hashachar is halachic dawn — when the sky begins to lighten. Many morning laws start here, such as the beginning of public fast days. It is before sunrise (netz). It is not the normal time for the bracha on tallit and tefillin — see misheyakir. In great need, Igros Moshe (O.C. 4:6) allows putting them on after alot hashachar without a bracha and reciting the brachos after misheyakir — ask your rav.": {
        "es": "alot hashachar — Alot hashachar es el amanecer halájico — cuando el cielo comienza a aclararse. Muchas leyes matutinas comienzan aquí, como el inicio de los días de ayuno público. Es antes del amanecer (netz). Consulte a su rav.",
        "fr": "alot hashachar — Aube halakhique ; début des jeûnes publics ; avant netz. Voir misheyakir pour tallit et téfilines.",
        "ru": "alot hashachar — галахический рассвет; начало общественных постов; до netz.",
    },
    "Aleinu is a closing prayer declaring G-d's sovereignty and our hope for universal recognition of His kingship. It ends daily Shacharit and Maariv and appears near the end of High Holiday services. The bow at \"we bend the knee\" is a moment of submission and awe.": {
        "es": "Aleinu es una oración de cierre que declara la soberanía de D-s y nuestra esperanza de reconocimiento universal de Su reinado. Cierra Shacharit y Maariv diarios y aparece al final de los servicios de Yamim Noraim. La inclinación en «nos inclinamos» es momento de sumisión y reverencia.",
        "fr": "Aléinou est une prière de clôture déclarant la souveraineté de D. et notre espoir de reconnaissance universelle de Sa royauté. Elle clôt Shacharit et Maariv quotidiens et apparaît à la fin des offices des Yamim Noraïm. L'inclinaison à « nous inclinons le genou » est un moment de soumission et de crainte.",
        "ru": "Алейну — заключительная молитва о владычестве В-га и надежде на всемирное признание Его царства. Завершает Шахарит и Маарив и звучит в Ямим Нораим. Поклон при «мы склоняем колено» — момент смирения и благоговения.",
    },
    "Aleinu — Aleinu is a closing prayer declaring G-d's sovereignty and our hope for universal recognition of His kingship. It ends daily Shacharit and Maariv and appears near the end of High Holiday services. The bow at \"we bend the knee\" is a moment of submission and awe.": {
        "es": "Aleinu — Aleinu es una oración de cierre que declara la soberanía de D-s y nuestra esperanza de reconocimiento universal de Su reinado. Cierra Shacharit y Maariv y aparece al final de Yamim Noraim.",
        "fr": "Aléinou — prière de clôture déclarant la souveraineté de D. et l'espoir de reconnaissance de Sa royauté ; à la fin des Yamim Noraïm.",
        "ru": "Алейну — заключительная молитва о владычестве В-га; в Ямим Нораим.",
    },
    "A machzor is a prayer book for the Jewish festivals and High Holidays — Rosh Hashana, Yom Kippur, Pesach, Sukkot, and Shavuot. It includes texts and prayers not found in the daily siddur. For Rosh Hashana and Yom Kippur, a machzor is required to perform the proper prayers.": {
        "es": "Un machzor es un libro de oración para los festivales judíos y Yamim Noraim — Rosh Hashaná, Yom Kippur, Pesaj, Sucot y Shavuot. Incluye textos y oraciones que no están en el sidur diario. Para Rosh Hashaná y Yom Kippur se requiere machzor.",
        "fr": "Un machzor est un livre de prières pour les fêtes juives et les Yamim Noraïm — Roch Hachana, Yom Kippour, Pessa'h, Souccot et Chavouot. Il contient des textes absents du siddour quotidien. Requis pour Roch Hachana et Yom Kippour.",
        "ru": "Махзор — молитвенник для еврейских праздников и Ямим Нораим — Рош а-Шана, Йом Кипур, Песах, Суккот и Шавуот. Содержит тексты, которых нет в ежедневном сидуре. Для Рош а-Шана и Йом Кипура махзор обязателен.",
    },
    "machzor — A machzor is a prayer book for the Jewish festivals and High Holidays — Rosh Hashana, Yom Kippur, Pesach, Sukkot, and Shavuot. It includes texts and prayers not found in the daily siddur. For Rosh Hashana and Yom Kippur, a machzor is required to perform the proper prayers.": {
        "es": "machzor — Libro de oración para festivales y Yamim Noraim; requerido para Rosh Hashaná y Yom Kippur.",
        "fr": "machzor — Livre de prières pour fêtes et Yamim Noraïm ; requis pour Roch Hachana et Yom Kippour.",
        "ru": "махзор — молитвенник для праздников и Ямим Нораим; обязателен для Рош а-Шана и Йом Кипура.",
    },
    "Find strength in Psalm 2! 👑 This powerful chapter speaks about G-d's ultimate sovereignty! Did you know? It describes how nations may plot, but G-d's plan always prevails! Here's something amazing: The psalm ends with the promise that all who trust in G-d are blessed. Today's challenge: Read this psalm and feel G-d's protective presence in your life.": {
        "es": "¡Encuentra fuerza en el Salmo 2! 👑 Habla de la soberanía suprema de D-s. El plan de D-s prevalece. Reto: léelo y siente la presencia protectora de D-s.",
        "fr": "Trouvez la force dans le Psaume 2 ! 👑 Ce chapitre parle de la souveraineté suprême de D. Les nations peuvent comploter, mais le plan de D. l'emporte toujours. Défi : lisez-le et sentez la protection de D.",
        "ru": "Найдите силу в Псалме 2! 👑 О верховном владычестве В-га. План В-га торжествует. Прочитайте и почувствуйте защиту В-га.",
    },
    "Walk in G-d's ways! 👣 The Rambam reveals in Hilchot Deot: Just as G-d is merciful, you should be merciful. Just as He is gracious, you should be gracious. Just as He is holy, you should be holy. Here's the key: Find the middle path in all your traits - not too harsh, not too soft. Today's mission: Pick one divine attribute (kindness, holiness, or mercy) and really focus on becoming it!": {
        "es": "¡Camina en los caminos de D-s! 👣 El Rambam revela en Hilchot Deot: Como D-s es misericordioso, sé misericordioso. Como es bondadoso, sé bondadoso. Como es santo, sé santo. Encuentra el camino medio. Misión: elige un atributo divino y concéntrate en cultivarlo.",
        "fr": "Marchez dans les voies de D. ! 👣 Le Rambam révèle en Hilchot Deot : comme D. est miséricordieux, soyez miséricordieux. Comme Il est bienveillant, soyez bienveillant. Comme Il est saint, soyez saint. Trouvez le juste milieu. Mission : choisissez un attribut divin et concentrez-vous pour le cultiver !",
        "ru": "Идите путями Б-га! 👣 Рамбам в Hilchot Deot: как Б-г милосерден — будьте милосердны. Как Он благ — будьте благими. Как Он свят — будьте святы. Найдите середину. Миссия: выберите один божественный атрибут и развивайте его!",
    },
    "Guard your speech about G-d! 🗣️ The Rambam teaches us in Hilchot Avodat Kochavim that we must be extremely careful never to speak disrespectfully about G-d or deny His existence. Even casual oaths or unnecessary blessings are forbidden. Here's something powerful: Every word we speak about G-d should be with reverence and awe. Today's mission: Practice speaking about holy matters with extra care and respect.": {
        "es": "¡Cuida tu habla sobre D-s! 🗣️ El Rambam en Hilchot Avodat Kochavim: nunca hables con irreverencia de D-s ni niegues Su existencia. Cada palabra sobre D-s debe ser con reverencia. Misión: habla de asuntos sagrados con cuidado y respeto.",
        "fr": "Surveillez votre discours sur D. ! 🗣️ Le Rambam nous enseigne en Hilchot Avodat Kochavim que nous devons éviter de parler avec irreverence de D. ou de nier Son existence. Chaque mot sur D. doit être dit avec respect et crainte. Mission : parlez des choses saintes avec soin et respect.",
        "ru": "Берегите речь о Б-ге! 🗣️ Рамбам в Hilchot Avodat Kochavim: никогда не говорите неуважительно о Б-ге и не отрицайте Его. Каждое слово о Б-ге — с благоговением. Миссия: говорите о святом с особой осторожностью.",
    },
    "While men are obligated in three structured prayer times, women are required to pray at least once a day.\n\nWhat prayer (tefillah) is:\nTefillah (תְּפִלָּה) comes from the Hebrew root meaning to judge oneself or reflect. Prayer is both a mitzvah and our most direct channel of communication with G-d. The rabbis derived from the phrase \"to serve G-d with all your heart\" (Deuteronomy 11:13) that this refers to prayer — the service of the heart.\n\nWhat to say:\nThe minimum for women includes praise of G-d, personal requests, and thanks. Many women say the full Amidah (Shemoneh Esrei). Others fulfill the obligation with a heartfelt personal prayer in any language.\n\nFor newcomers:\nStart with what you can manage consistently. Even a few sincere sentences every morning — thanking G-d, asking for what you need — is a genuine fulfillment. Over time, learn more from a siddur (prayer book).": {
        "es": "Los hombres están obligados en tres tiempos de oración estructurados; las mujeres deben orar al menos una vez al día.\n\nLa tefilá (תְּפִלָּה) significa juzgarse a uno mismo. Es mitzvá y canal directo con D-s. Los rabinos derivaron de «servir a D-s con todo tu corazón» (Deuteronomio 11:13) que esto es la oración.\n\nMínimo para mujeres: alabanza, peticiones y agradecimiento. Muchas dicen la Amidá completa; otras cumplen con oración personal sincera.\n\nPara principiantes: empiece con lo que pueda mantener. Unas frases sinceras cada mañana ya es cumplimiento genuino.",
        "fr": "Les hommes sont tenus à trois temps de prière structurés ; les femmes doivent prier au moins une fois par jour.\n\nLa tefilah (תְּפִלָּה) vient de la racine signifiant se juger soi-même. La prière est une mitzvah et notre canal direct avec D. Les rabbins ont dérivé de « servir D. de tout votre cœur » (Deutéronome 11:13) qu'il s'agit de la prière — le service du cœur.\n\nMinimum pour les femmes : louange de D., demandes personnelles et remerciements. Beaucoup disent l'Amidah complète ; d'autres s'acquittent par une prière personnelle sincère.\n\nPour les débutants : commencez par ce que vous pouvez tenir. Quelques phrases sincères chaque matin — remercier D., demander ce dont vous avez besoin — est un véritable accomplissement.",
        "ru": "Мужчины обязаны в трёх структурированных временах молитвы; женщины должны молиться хотя бы раз в день.\n\nТефила (תְּפִלָּה) — от корня «судить себя». Молитва — мицва и прямой канал связи с Б-гом. Из «служить Б-гу всем сердцем» (Ваикра 11:13) выводят молитву.\n\nМинимум для женщин: хвала, просьбы и благодарность. Многие читают полную Амиду; другие — искреннюю личную молитву.\n\nНовичкам: начните с того, что можете выдерживать. Несколько искренних фраз утром — уже исполнение.",
    },
    "Kaddish sanctifies G-d's Name in Aramaic — exalting G-d publicly. Mourners recite Kaddish for eleven months for parents and thirty days for other close relatives. It requires a minyan. There are half-Kaddish, whole-Kaddish, and rabbinic Kaddish placements in the service. Saying Kaddish connects the living to the deceased's merit.": {
        "es": "El Kaddish santifica el Nombre de D-s en arameo — exaltando a D-s públicamente. Los dolientes recitan Kaddish once meses por padres y treinta días por otros parientes. Requiere minyán. Hay medio-Kaddish, Kaddish completo y Kaddish rabínico. Conecta a los vivos con el mérito del difunto.",
        "fr": "Le Kaddish sanctifie le Nom de D. en araméen — exaltant D. en public. Les endeuillés récitent le Kaddish onze mois pour les parents et trente jours pour d'autres proches. Il faut un minyan. Demi-Kaddish, Kaddish entier et Kaddish rabbinique. Relie les vivants au mérite du défunt.",
        "ru": "Кадиш освящает Имя Б-га на арамейском — возвышая Б-га публично. Скорбящие читают Кадиш одиннадцать месяцев за родителей и тридцать дней за других близких. Нужен миньян. Полу-Кадиш, полный и раввинский. Связывает живых с заслугой усопшего.",
    },
    "Kaddish — Kaddish sanctifies G-d's Name in Aramaic — exalting G-d publicly. Mourners recite Kaddish for eleven months for parents and thirty days for other close relatives. It requires a minyan. There are half-Kaddish, whole-Kaddish, and rabbinic Kaddish placements in the service. Saying Kaddish connects the living to the deceased's merit.": {
        "es": "Kaddish — santifica el Nombre de D-s en arameo; requiere minyán; once meses por padres.",
        "fr": "Kaddish — sanctifie le Nom de D. en araméen ; minyan requis ; onze mois pour les parents.",
        "ru": "Кадиш — освящает Имя Б-га; нужен миньян; одиннадцать месяцев за родителей.",
    },
    "A mezuzah is the klaf — handwritten parchment with Shema and V'ahavta passages — affixed to doorposts of rooms used for dwelling. The case is protection for the scroll, not the mitzvah itself. Check scrolls by a sofer every few years. Touching the case and kissing the mezuzah when entering reminds you that G-d watches over the home.": {
        "es": "La mezuzá es el klaf — pergamino manuscrito con Shemá y Va'ahavtá — en los marcos de puertas de habitaciones. El estuche protege el rollo, no es la mitzvá. Revise con un sofer cada pocos años. Al entrar, tocar y besar la mezuzá recuerda que D-s cuida el hogar.",
        "fr": "La mezouza est le klaf — parchemin manuscrit avec le Shema et Va'ahavta — sur les montants des portes. Le boîtier protège le rouleau, ce n'est pas la mitzvah. Faites vérifier par un sofer tous les quelques années. Toucher et embrasser la mezouza au passage rappelle que D. veille sur la maison.",
        "ru": "Мезуза — это клаф с рукописным пергаментом Шма и Ваавта на дверных косяках. Футляр защищает свиток, не сама мицва. Проверяйте у софера раз в несколько лет. Прикосновение и поцелуй при входе напоминают, что Б-г хранит дом.",
    },
    "mezuzah — A mezuzah is the klaf — handwritten parchment with Shema and V'ahavta passages — affixed to doorposts of rooms used for dwelling. The case is protection for the scroll, not the mitzvah itself. Check scrolls by a sofer every few years. Touching the case and kissing the mezuzah when entering reminds you that G-d watches over the home.": {
        "es": "mezuzá — klaf manuscrito en marcos; revise con sofer; D-s cuida el hogar.",
        "fr": "mezouza — klaf manuscrit sur les montants ; vérification par sofer ; D. veille sur la maison.",
        "ru": "мезуза — рукописный клаф на косяках; проверка у софера; Б-г хранит дом.",
    },
    "Chilul Hashem is desecrating G-d's Name — behavior that makes Torah or Jews look contemptible, especially in public. Fraud, rage, or hypocrisy by a visibly Jewish person harms the whole people. The opposite is kiddush Hashem — sanctifying G-d's Name through integrity. Non-Jews judging Judaism by your conduct is a serious responsibility.": {
        "es": "Jilul Hashem es profanar el Nombre de D-s — conducta que deshonra la Torá o a los judíos, sobre todo en público. Lo opuesto es kidush Hashem. Los no judíos juzgan el judaísmo por su conducta.",
        "fr": "Hiloul Hashem profane le Nom de D. — comportement qui déshonore la Torah ou les Juifs, surtout en public. L'opposé est kiddouch Hashem. Les non-Juifs jugent le judaïsme par votre conduite.",
        "ru": "Хилуль а-Шем — осквернение Имени Б-га — поведение, позорящее Тору или евреев. Противоположность — кидуш а-Шем. Неевреи судят иудаизм по вашему поведению.",
    },
    "Chilul Hashem — Chilul Hashem is desecrating G-d's Name — behavior that makes Torah or Jews look contemptible, especially in public. Fraud, rage, or hypocrisy by a visibly Jewish person harms the whole people. The opposite is kiddush Hashem — sanctifying G-d's Name through integrity. Non-Jews judging Judaism by your conduct is a serious responsibility.": {
        "es": "Jilul Hashem — profanar el Nombre de D-s; opuesto: kidush Hashem.",
        "fr": "Hiloul Hashem — profanation du Nom de D. ; opposé : kiddouch Hashem.",
        "ru": "Хилуль а-Шем — осквернение Имени Б-га; противоположность — кидуш а-Шем.",
    },
}


def main() -> None:
    from kibbud_paragraph import ES as KIBBUD_ES, FR as KIBBUD_FR, KEY as KIBBUD_KEY, RU as KIBBUD_RU

    fixes = dict(FIXES)
    fixes[KIBBUD_KEY] = {"es": KIBBUD_ES, "fr": KIBBUD_FR, "ru": KIBBUD_RU}
    by_lang: dict[str, dict[str, str]] = {"he": {}, "es": {}, "fr": {}, "ru": {}}
    for en, langs in fixes.items():
        for lang, tr in langs.items():
            by_lang[lang][en] = tr
    OUT.write_text(json.dumps(by_lang, ensure_ascii=False, indent=2), encoding="utf-8")
    total = sum(len(v) for v in by_lang.values())
    print(f"wrote {OUT} ({total} entries)")


if __name__ == "__main__":
    main()
