#!/usr/bin/env python3
"""Hand-reviewed translations for strings with corrupted Kotlin placeholders."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "translation-catalog" / "placeholder_fixes.json"

# English key -> per-language corrected translation (placeholders byte-for-byte from English)
FIXES: dict[str, dict[str, str]] = {
    "$holidayName is about to begin. Please finish what you are doing, turn off your phone, and prepare to welcome this Yom Tov with joy.\n\nOur Sages teach that rejoicing on Yom Tov is itself a mitzvah — may your observance bring blessing and divine reward to you and your household.": {
        "es": "$holidayName está a punto de comenzar. Termine lo que está haciendo, apague el teléfono y prepárese para recibir este Yom Tov con alegría.\n\nNuestros Sabios enseñan que regocijarse en Yom Tov es en sí misma una mitzvá — que su observancia traiga bendición y recompensa divina a usted y a su hogar.",
        "fr": "$holidayName va commencer. Veuillez terminer ce que vous faites, éteindre votre téléphone et vous préparer à accueillir ce Yom Tov avec joie.\n\nNos Sages enseignent que se réjouir pendant Yom Tov est elle-même une mitzvah — que votre observance vous apporte bénédiction et récompense divine, à vous et à votre foyer.",
    },
    "Today is $name — $meaning\n\nMinor fast rules:\n• No eating or drinking from dawn until nightfall.\n• Washing, music, and showering are generally permitted (unlike Tisha B'Av and Yom Kippur).\n• Special selichot and prayers may be recited in synagogue — check your community schedule.": {
        "es": "Hoy es $name — $meaning\n\nReglas de ayuno menor:\n• No comer ni beber desde el amanecer hasta el anochecer.\n• Lavado, música y ducha están generalmente permitidos (a diferencia de Tisha B'Av y Yom Kippur).\n• Pueden recitarse selichot y oraciones especiales en la sinagoga — consulte el horario de su comunidad.",
        "fr": "Aujourd'hui, c'est $name — $meaning\n\nRègles de jeûne mineur :\n• Ne pas manger ni boire de l'aube jusqu'à la tombée de la nuit.\n• Le lavage, la musique et la douche sont généralement permis (contrairement à Tisha B'Av et Yom Kippur).\n• Des selichot et prières spéciales peuvent être récitées à la synagogue — vérifiez le calendrier de votre communauté.",
    },
    "Read this today (Friday) before Shabbat candles — the app is not for use on Shabbat.\n\nTomorrow is Shabbat and erev $tomorrowChag. $tomorrowChag begins tomorrow night at nightfall (Motzei Shabbat), not tonight. Finish Yaknehaz prep, Yom Tov candles from a pre-existing flame, wine, and festive food before Shabbat ends.": {
        "es": "Lea esto hoy (viernes) antes de las velas de Shabat — la aplicación no debe usarse en Shabat.\n\nMañana es Shabat y erev $tomorrowChag. $tomorrowChag comienza mañana por la noche al anochecer (Motzei Shabat), no esta noche. Termine la preparación de Yaknehaz, las velas de Yom Tov desde una llama preexistente, el vino y la comida festiva antes de que termine Shabat.",
        "fr": "Lisez ceci aujourd'hui (vendredi) avant les bougies de Chabbat — l'application ne doit pas être utilisée pendant Chabbat.\n\nDemain est Chabbat et erev $tomorrowChag. $tomorrowChag commence demain soir à la tombée de la nuit (Motzei Chabbat), pas ce soir. Terminez la préparation Yaknehaz, les bougies de Yom Tov à partir d'une flamme préexistante, le vin et la nourriture festive avant la fin de Chabbat.",
    },
    "New mitzvah submission from the Mitz Mode app:\n            \n            Submitted by: $submitterName\n            Mitzvah text: $mitzvahText\n            \n            Submitted on: ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Please review and consider adding to the mitzvah database.": {
        "es": "Nueva presentación de mitzvá desde la aplicación Mitz Mode:\n            \n            Presentado por: $submitterName\n            Texto de la mitzvá: $mitzvahText\n            \n            Presentado el: ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Revise y considere añadirlo a la base de datos de mitzvot.",
        "fr": "Nouvelle soumission de mitzvah depuis l'application Mitz Mode :\n            \n            Soumis par : $submitterName\n            Texte de la mitzvah : $mitzvahText\n            \n            Soumis le : ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Veuillez examiner et envisager d'ajouter à la base de données des mitzvot.",
    },
    "If you forgot at Maariv on Rosh Chodesh:\n• Still in Retzei before God's name at the conclusion — insert Yaaleh V'yavo there and continue ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Once you finished Retzei, or after the entire Amidah — do not go back and do not repeat. Beit Din sanctified the new month by day, not at night (Berachot 30b; $YAALEH_VYAVO_HALACHA_SOURCE). Continue davening.": {
        "fr": "Si vous avez oublié à Maariv le Rosh Chodesh :\n• Toujours dans Retzei avant le nom de D. à la conclusion — insérez Yaaleh V'yavo là et continuez ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Une fois Retzei terminé, ou après toute l'Amidah — ne revenez pas en arrière et ne répétez pas. Le Beit Din a sanctifié le nouveau mois de jour, pas de nuit (Berachot 30b ; $YAALEH_VYAVO_HALACHA_SOURCE). Continuez la tefillah.",
    },
    "If you forgot:\n• Still in Retzei (before concluding the blessing) — insert Yaaleh V'yavo in its place and continue ($YAALEH_VYAVO_HALACHA_SOURCE).\n• After concluding Retzei — return to the beginning of Retzei, insert Yaaleh V'yavo, and complete the remaining blessings ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Finished the entire Amidah (after the final Yihiyu L'ratzon) — repeat only the $service Amidah (Shemoneh Esrei), never the full service, even if you already davened Musaf, Maariv, or anything else afterward ($YAALEH_VYAVO_HALACHA_SOURCE).": {
        "es": "Si se olvidó:\n• Todavía en Retzei (antes de concluir la bendición) — inserte Yaaleh V'yavo en su lugar y continúe ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Después de concluir Retzei — vuelva al comienzo de Retzei, inserte Yaaleh V'yavo y complete las bendiciones restantes ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Terminó toda la Amidah (después del Yihiyu L'ratzon final) — repita solo la Amidah de $service (Shemoneh Esrei), nunca el servicio completo, aunque ya haya rezado Musaf, Maariv u otra cosa después ($YAALEH_VYAVO_HALACHA_SOURCE).",
        "fr": "Si vous avez oublié :\n• Toujours dans Retzei (avant de conclure la bénédiction) — insérez Yaaleh V'yavo à sa place et continuez ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Après avoir conclu Retzei — revenez au début de Retzei, insérez Yaaleh V'yavo et complétez les bénédictions restantes ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Amidah entière terminée (après le Yihiyu L'ratzon final) — répétez uniquement l'Amidah de $service (Shemoneh Esrei), jamais le service complet, même si vous avez déjà prié Moussaf, Maariv ou autre ensuite ($YAALEH_VYAVO_HALACHA_SOURCE).",
    },
    "This year, today is $chagName on Friday and Shabbat begins tonight — the Yom Tov–Shabbat sequence is in progress.\n\nToday on Yom Tov (if you made eruv tavshilin before the festival began):\n• You may cook and prepare for Shabbat meals today — within halachic limits (food ready with time to spare before Shabbat).\n• Finish preparations before Shabbat; set timers/blech as guided by your rav.\n\nIf you have not made eruv tavshilin, ask your rabbi immediately.\n\nShabbat tonight: light candles from a pre-existing flame after Yom Tov ends; follow your siddur for when Yom Tov ends and Shabbat begins.": {
        "es": "Este año, hoy es $chagName en viernes y Shabat comienza esta noche — la secuencia Yom Tov–Shabat está en curso.\n\nHoy en Yom Tov (si hizo eruv tavshilin antes de que comenzara la festividad):\n• Puede cocinar y preparar las comidas de Shabat hoy — dentro de los límites halájicos (comida lista con tiempo de sobra antes de Shabat).\n• Termine las preparaciones antes de Shabat; programe temporizadores/blech según indique su rav.\n\nSi no hizo eruv tavshilin, consulte a su rabino de inmediato.\n\nShabat esta noche: encienda velas desde una llama preexistente después de que termine Yom Tov; siga su sidur para saber cuándo termina Yom Tov y comienza Shabat.",
        "fr": "Cette année, aujourd'hui c'est $chagName un vendredi et Chabbat commence ce soir — la séquence Yom Tov–Chabbat est en cours.\n\nAujourd'hui pendant Yom Tov (si vous avez fait eruv tavshilin avant le début de la fête) :\n• Vous pouvez cuisiner et préparer les repas de Chabbat aujourd'hui — dans les limites halakhiques (nourriture prête bien avant Chabbat).\n• Terminez les préparations avant Chabbat ; réglez minuteries/blech selon les indications de votre rav.\n\nSi vous n'avez pas fait eruv tavshilin, consultez votre rabbin immédiatement.\n\nChabbat ce soir : allumez les bougies à partir d'une flamme préexistante après la fin de Yom Tov ; suivez votre siddour pour savoir quand Yom Tov se termine et Chabbat commence.",
    },
    "This year, $chagName meets Shabbat on the calendar — you need eruv tavshilin. This doesn't happen every year.\n\nWhy (Peninei Halakha 12:8):\n• On Yom Tov, cooking is generally allowed only for that calendar day of Yom Tov, not for the next day.\n• When Yom Tov is immediately followed by Shabbat, the Sages required eruv tavshilin so you may cook on Yom Tov for Shabbat, and so Shabbat is not forgotten amid festival preparations.\n\n$whenLine\n\nHow (Peninei Halakha 12:8:2):\n• Set aside a baked food (challah or matzah) and a cooked food (meat, fish, or unpeeled hard-boiled egg are common examples).\n• Recite the blessing and declaration from your Machzor or siddur in any language you understand — use the printed wording; do not paraphrase from memory.\n• One eruv per household is sufficient.\n• Food must be appropriate to eat with bread; at least a kezayit of cooked food should remain until Shabbat prep is done.\n• Storage warning: Put the designated eruv foods in a safe, clearly labeled spot. If the eruv foods are eaten or destroyed before you finish cooking for Shabbat on Friday afternoon, your permission to prepare food is canceled (ask your rav if this happens).\n\nLimits:\n• Permits cooking and food prep on Yom Tov for Shabbat only — not cooking on one day of Yom Tov for the next festival day.\n• Food should be ready early enough Friday afternoon that it could theoretically be eaten before Shabbat.\n• Does not permit non-food Shabbat prep (e.g. certain laundry) — ask your rav.": {
        "es": "Este año, $chagName coincide con Shabat en el calendario — necesita eruv tavshilin. Esto no ocurre todos los años.\n\nPor qué (Peninei Halakha 12:8):\n• En Yom Tov, cocinar está permitido generalmente solo para ese día calendario de Yom Tov, no para el día siguiente.\n• Cuando Yom Tov va seguido inmediatamente por Shabat, los Sabios exigieron eruv tavshilin para poder cocinar en Yom Tov para Shabat, y para que Shabat no se olvide entre las preparaciones de la festividad.\n\n$whenLine\n\nCómo (Peninei Halakha 12:8:2):\n• Reserve un alimento horneado (jalá o matzá) y un alimento cocido (carne, pescado o huevo duro sin pelar son ejemplos comunes).\n• Recite la bendición y declaración de su Majzor o sidur en cualquier idioma que entienda — use el texto impreso; no parafrasee de memoria.\n• Un eruv por hogar es suficiente.\n• El alimento debe ser apropiado para comer con pan; al menos un kezayit de comida cocida debe permanecer hasta terminar la preparación de Shabat.\n• Advertencia de almacenamiento: coloque los alimentos del eruv en un lugar seguro y claramente etiquetado. Si se comen o destruyen antes de terminar de cocinar para Shabat el viernes por la tarde, se cancela el permiso (consulte a su rav si ocurre).\n\nLímites:\n• Permite cocinar y preparar comida en Yom Tov solo para Shabat — no cocinar un día de Yom Tov para el siguiente día festivo.\n• La comida debe estar lista lo suficientemente temprano el viernes por la tarde como para poder comerse teóricamente antes de Shabat.\n• No permite preparativos de Shabat que no sean comida (p. ej. cierta lavandería) — consulte a su rav.",
        "fr": "Cette année, $chagName coïncide avec Chabbat dans le calendrier — vous avez besoin d'eruv tavshilin. Cela n'arrive pas tous les ans.\n\nPourquoi (Peninei Halakha 12:8) :\n• Pendant Yom Tov, la cuisson n'est généralement autorisée que pour ce jour civil de Yom Tov, pas pour le lendemain.\n• Lorsque Yom Tov est immédiatement suivi de Chabbat, les Sages ont exigé l'eruv tavshilin afin que vous puissiez cuisiner pendant Yom Tov pour Chabbat, et pour que Chabbat ne soit pas oublié au milieu des préparations de la fête.\n\n$whenLine\n\nComment (Peninei Halakha 12:8:2) :\n• Mettez de côté un aliment cuit au four (hallah ou matza) et un aliment cuit (viande, poisson ou œuf dur non pelé sont des exemples courants).\n• Récitez la bénédiction et la déclaration de votre Mahzor ou siddour dans toute langue que vous comprenez — utilisez le texte imprimé ; ne paraphrasez pas de mémoire.\n• Un eruv par foyer suffit.\n• L'aliment doit convenir à manger avec du pain ; au moins un kezayit de nourriture cuite doit rester jusqu'à la fin des préparations de Chabbat.\n• Avertissement de stockage : placez les aliments de l'eruv dans un endroit sûr et clairement étiqueté. S'ils sont mangés ou détruits avant la fin de la cuisson pour Chabbat vendredi après-midi, la permission est annulée (consultez votre rav si cela arrive).\n\nLimites :\n• Permet la cuisson et la préparation alimentaire pendant Yom Tov uniquement pour Chabbat — pas cuisiner un jour de Yom Tov pour le jour festif suivant.\n• La nourriture doit être prête assez tôt vendredi après-midi pour pouvoir théoriquement être mangée avant Chabbat.\n• N'autorise pas les préparatifs de Chabbat non alimentaires (p. ex. certaine lessive) — consultez votre rav.",
    },
    "After Yom Kippur ends at nightfall${tzeit?.let { \" (approx. $it tonight)\" } ?: \"\"}, it is a mitzvah to eat a proper meal — not only a quick bite.\n\nWhat to do:\n• Complete Maariv and Havdalah (Havdalah includes a candle that was lit throughout Yom Kippur, wine, and no spices).\n• Eat a festive break-fast — many prepare food in advance because cooking restrictions on Yom Kippur end at nightfall.\n• Chabad tradition (Baal HaTanya) teaches that one's livelihood (parnassa) for the year is especially connected to this meal — eat with joy and spiritual intention.\n\nThis item becomes available at nightfall after the fast ends.": {
        "he": "לאחר שיום הכיפורים מסתיים בצאת הכוכבים${tzeit?.let { \" (בערך $it הלילה)\" } ?: \"\"}, מצווה לאכול ארוחה נכונה — לא רק ביס מהיר.\n\nמה לעשות:\n• השלימו מעריב והבדלה (הבדלה כוללת נר שהדליקו לאורך יום הכיפורים, יין וללא בשמים).\n• אכלו ארוחת שבירת צום חגיגית — רבים מכינים מזון מראש כי איסורי בישול ביום הכיפורים מסתיימים בצאת הכוכבים.\n• מסורת חב\"ד (בעל התניא) מלמדת שפרנסת השנה קשורה במיוחד לארוחה זו — אכלו בשמחה ובכוונה.\n\nפריט זה זמין בצאת הכוכבים לאחר סיום הצום.",
        "es": "Después de que Yom Kippur termine al anochecer${tzeit?.let { \" (aprox. $it esta noche)\" } ?: \"\"}, es una mitzvá comer una comida adecuada — no solo un bocado rápido.\n\nQué hacer:\n• Complete Maariv y Havdalah (Havdalah incluye una vela encendida durante todo Yom Kippur, vino y sin especias).\n• Coma un desayuno festivo tras el ayuno — muchos preparan comida con anticipación porque las restricciones de cocina en Yom Kippur terminan al anochecer.\n• La tradición jabad (Baal HaTanya) enseña que el sustento (parnasa) del año está especialmente ligado a esta comida — coma con alegría e intención espiritual.\n\nEste elemento estará disponible al anochecer después de que termine el ayuno.",
        "fr": "Après la fin de Yom Kippour à la tombée de la nuit${tzeit?.let { \" (env. $it ce soir)\" } ?: \"\"}, c'est une mitzvah de prendre un bon repas — pas seulement une bouchée rapide.\n\nQue faire :\n• Terminez Maariv et Havdalah (Havdalah comprend une bougie allumée tout au long de Yom Kippour, du vin et pas d'épices).\n• Prenez un repas festif de rupture du jeûne — beaucoup préparent la nourriture à l'avance car les restrictions de cuisson de Yom Kippour se terminent à la tombée de la nuit.\n• La tradition Habad (Baal HaTanya) enseigne que la subsistance (parnassa) de l'année est particulièrement liée à ce repas — mangez avec joie et intention spirituelle.\n\nCet élément devient disponible à la tombée de la nuit après la fin du jeûne.",
        "ru": "После окончания Йом Кипура с наступлением ночи${tzeit?.let { \" (прим. $it сегодня вечером)\" } ?: \"\"}, мицва — съесть полноценную трапезу, а не только быстрый перекус.\n\nЧто делать:\n• Завершите Маарив и Хавдалу (Хавдала включает свечу, горевшую весь Йом Кипур, вино и без благовоний).\n• Съешьте праздничную трапезу после поста — многие готовят еду заранее, потому что запрет на готовку в Йом Кипур заканчивается с наступлением ночи.\n• Традиция Хабада (Бааль а-Танья) учит, что пропитание (парнаса) на год особенно связано с этой трапезой — ешьте с радостью и духовным намерением.\n\nЭтот пункт станет доступен с наступлением ночи после окончания поста.",
    },
    "Today is Yom Kippur — the Day of Atonement.\n\nThe fast:\n• Began at sunset last night (many communities accepted it earlier with tosefet — adding time from erev onto Yom Kippur) and ends at nightfall tonight${tzeit?.let { \" (approx. $it)\" } ?: \"\"}.\n• Five afflictions: no eating/drinking, no leather shoes, no bathing for pleasure, no anointing, no marital relations.\n• Many wear white; married men who normally wear a kittel do so; tallit is worn all day.\n• The day is spent in prayer — Kol Nidrei was last night before sunset (hatarat nedarim cannot be done on Yom Kippur itself), then Shacharit, Musaf, Mincha, Neilah, then Maariv and Havdalah after nightfall.\n\nAfter nightfall: eat the Motzei Yom Kippur meal (see your checklist). Chabad tradition connects this meal to parnassa for the year.": {
        "he": "היום יום הכיפורים — יום הכיפורים.\n\nהצום:\n• התחיל בשקיעה אמש (קהילות רבות קיבלו אותו מוקדם יותר עם תוספת — הוספת זמן מערב ליום הכיפורים) ומסתיים בצאת הכוכבים הלילה${tzeit?.let { \" (בערך $it)\" } ?: \"\"}.\n• חמש עינויים: אין אכילה/שתייה, אין נעלי עור, אין רחצה להנאה, אין סיכה, אין יחסי אישות.\n• רבים לובשים לבן; גברים נשואים שלובשים כתונת לבן עושים כן; טלית נלבשת כל היום.\n• היום מוקדש לתפילה — כל נדרי היה אמש לפני השקיעה (התרת נדרים אינה אפשרית ביום הכיפורים עצמו), אחר כך שחרית, מוסף, מנחה, נעילה, ואז מעריב והבדלה אחרי צאת הכוכבים.\n\nאחרי צאת הכוכבים: אכלו את ארוחת מוצאי יום הכיפורים (ראו את רשימת הבדיקה). מסורת חב\"ד מקשרת ארוחה זו לפרנסה לשנה.",
        "es": "Hoy es Yom Kippur — el Día de la Expiación.\n\nEl ayuno:\n• Comenzó al atardecer anoche (muchas comunidades lo aceptaron antes con tosefet — añadiendo tiempo del erev a Yom Kippur) y termina al anochecer esta noche${tzeit?.let { \" (aprox. $it)\" } ?: \"\"}.\n• Cinco aflicciones: sin comer/beber, sin zapatos de cuero, sin baño por placer, sin ungir, sin relaciones conyugales.\n• Muchos visten de blanco; hombres casados que usan kittel lo hacen; se usa talit todo el día.\n• El día se dedica a la oración — Kol Nidrei fue anoche antes del atardecer (hatarat nedarim no puede hacerse en Yom Kippur mismo), luego Shacharit, Musaf, Minjá, Neilá, y después Maariv y Havdalah al anochecer.\n\nDespués del anochecer: coma la comida de Motzei Yom Kippur (vea su lista). La tradición jabad conecta esta comida con el sustento del año.",
        "fr": "Aujourd'hui, c'est Yom Kippour — le Jour de l'Expiation.\n\nLe jeûne :\n• A commencé au coucher du soleil hier soir (de nombreuses communautés l'ont accepté plus tôt avec tosefet — ajout de temps de l'erev à Yom Kippour) et se termine à la tombée de la nuit ce soir${tzeit?.let { \" (env. $it)\" } ?: \"\"}.\n• Cinq afflictions : pas de nourriture/boisson, pas de chaussures en cuir, pas de bain pour le plaisir, pas d'onction, pas de relations conjugales.\n• Beaucoup portent du blanc ; les hommes mariés qui portent un kittel le font ; le tallit est porté toute la journée.\n• La journée est consacrée à la prière — Kol Nidrei était hier soir avant le coucher du soleil (hatarat nedarim ne peut pas se faire le jour de Yom Kippour lui-même), puis Shacharit, Moussaf, Min'ha, Neïla, puis Maariv et Havdalah après la tombée de la nuit.\n\nAprès la tombée de la nuit : prenez le repas de Motzei Yom Kippour (voir votre liste). La tradition Habad relie ce repas à la subsistance de l'année.",
        "ru": "Сегодня Йом Кипур — День Искупления.\n\nПост:\n• Начался на закате вчера вечером (многие общины приняли его раньше с тосефет — добавлением времени от Эрева к Йом Кипуру) и заканчивается с наступлением ночи сегодня${tzeit?.let { \" (прим. $it)\" } ?: \"\"}.\n• Пять ограничений: нет еды/питья, нет кожаной обуви, нет купания для удовольствия, нет помазания, нет супружеских отношений.\n• Многие носят белое; женатые мужчины в кителе делают это; талит носят весь день.\n• День посвящён молитве — Кол Нидре был вчера до заката (hatarat nedarim нельзя в сам Йом Кипур), затем Шахарит, Мусаф, Минха, Неила, потом Маарив и Хавдала после наступления ночи.\n\nПосле наступления ночи: съешьте трапезу Моцэи Йом Кипур (см. ваш список). Традиция Хабада связывает эту трапезу с пропитанием на год.",
    },
    "Today is Tisha B'Av — mourning the destruction of both Temples and our exile.\n\nThe fast:\n• Began at sunset last night and ends at nightfall tonight${tzeit?.let { \" (approx. $it)\" } ?: \"\"} — not a dawn-to-dusk fast.\n\nWhat is forbidden today (in addition to eating and drinking):\n• Leather shoes; bathing for pleasure; anointing with cream or cologne; marital relations.\n• Torah study except for mournful passages (Eichah, Iyov, parts of Yirmiyahu, halachot of mourning).\n• Greeting people with \"hello\"; idle conversation; work is discouraged (follow your community).\n• Many sit on the floor or a low stool until chatzos (halachic midday); kinot (elegies) are recited.\n\nWhat is permitted (unlike Yom Kippur in some communities):\n• Music prohibitions are mourning-related — live joyful music is avoided as part of the Three Weeks/Nine Days spirit, but the fast's core prohibitions are the five afflictions above.\n\nAfter nightfall: some mourning restrictions of the Nine Days lift — ask your rav about laundry, meat, and music.": {
        "he": "היום ט' באב — אבל על חורבן שני המקדשים וגלותנו.\n\nהצום:\n• התחיל בשקיעה אמש ומסתיים בצאת הכוכבים הלילה${tzeit?.let { \" (בערך $it)\" } ?: \"\"} — לא צום משחר עד לילה.\n\nמה אסור היום (בנוסף לאכילה ושתייה):\n• נעלי עור; רחצה להנאה; סיכה בקרם או קולוניה; יחסי אישות.\n• לימוד תורה למעט קטעי אבל (איכה, איוב, חלקי ירמיהו, הלכות אבל).\n• לברך ב\"שלום\"; שיחה בטלה; עבודה אינה מומלצת (לפי הקהילה).\n• רבים יושבים על הרצפה או כיסא נמוך עד חצות; קינות נאמרות.\n\nמה מותר (בניגוד ליום הכיפורים בחלק מהקהילות):\n• איסורי מוזיקה קשורים לאבל — נמנעים ממוזיקה שמחה חיה ברוח של שלושת השבועות/תשעה באב, אך ליבת הצום היא חמש העינויים לעיל.\n\nאחרי צאת הכוכבים: חלק מאיסורי האבל של תשעה באב מתבטלים — שאלו את הרב לגבי כביסה, בשר ומוזיקה.",
        "es": "Hoy es Tisha B'Av — luto por la destrucción de ambos Templos y nuestro exilio.\n\nEl ayuno:\n• Comenzó al atardecer anoche y termina al anochecer esta noche${tzeit?.let { \" (aprox. $it)\" } ?: \"\"} — no es un ayuno de amanecer a atardecer.\n\nLo prohibido hoy (además de comer y beber):\n• Zapatos de cuero; baño por placer; ungir con crema o colonia; relaciones conyugales.\n• Estudio de Torá excepto pasajes de duelo (Eijá, Iyov, partes de Irmiyahu, halajot de duelo).\n• Saludar con \"hola\"; conversación ociosa; el trabajo se desaconseja (siga su comunidad).\n• Muchos se sientan en el suelo o en un taburete bajo hasta chatzot (mediodía halájico); se recitan kinot (elegías).\n\nLo permitido (a diferencia de Yom Kippur en algunas comunidades):\n• Las prohibiciones de música están relacionadas con el duelo — se evita música alegre en vivo como parte del espíritu de las Tres Semanas/Nueve Días, pero el núcleo del ayuno son las cinco aflicciones anteriores.\n\nDespués del anochecer: algunas restricciones de duelo de los Nueve Días se levantan — consulte a su rav sobre lavandería, carne y música.",
        "fr": "Aujourd'hui, c'est Tisha B'Av — deuil de la destruction des deux Temples et de notre exil.\n\nLe jeûne :\n• A commencé au coucher du soleil hier soir et se termine à la tombée de la nuit ce soir${tzeit?.let { \" (env. $it)\" } ?: \"\"} — pas un jeûne de l'aube au crépuscule.\n\nCe qui est interdit aujourd'hui (en plus de manger et boire) :\n• Chaussures en cuir ; bain pour le plaisir ; onction avec crème ou eau de Cologne ; relations conjugales.\n• Étude de la Torah sauf passages de deuil (Eikha, Iyov, parties de Yirmiyahu, halakhot du deuil).\n• Saluer avec « bonjour » ; conversation oiseuse ; le travail est déconseillé (suivez votre communauté).\n• Beaucoup s'assoient sur le sol ou un tabouret bas jusqu'à hatzot (midi halakhique) ; kinot (élégies) sont récitées.\n\nCe qui est permis (contrairement à Yom Kippour dans certaines communautés) :\n• Les interdictions de musique sont liées au deuil — on évite la musique joyeuse en direct dans l'esprit des Trois Semaines/Neuf Jours, mais le cœur du jeûne reste les cinq afflictions ci-dessus.\n\nAprès la tombée de la nuit : certaines restrictions de deuil des Neuf Jours se lèvent — consultez votre rav pour la lessive, la viande et la musique.",
        "ru": "Сегодня Тиша б'Ав — скорбь о разрушении обоих Храмов и нашем изгнании.\n\nПост:\n• Начался на закате вчера вечером и заканчивается с наступлением ночи сегодня${tzeit?.let { \" (прим. $it)\" } ?: \"\"} — не пост от рассвета до заката.\n\nЧто запрещено сегодня (кроме еды и питья):\n• Кожаная обувь; купание для удовольствия; помазание кремом или одеколоном; супружеские отношения.\n• Изучение Торы, кроме скорбных отрывков (Эйха, Иов, части Ирмияу, галахот траура).\n• Приветствие «привет»; пустые разговоры; работа не рекомендуется (следуйте своей общине).\n• Многие сидят на полу или низком табурете до хацот (галахический полдень); читают кинот (элегии).\n\nЧто разрешено (в отличие от Йом Кипура в некоторых общинах):\n• Запреты на музыку связаны с трауром — избегают живой радостной музыки в духе Трёх Недель/Девяти Дней, но суть поста — пять ограничений выше.\n\nПосле наступления ночи: часть траурных ограничений Девяти Дней снимается — спросите раввина о стирке, мясе и музыке.",
    },
    "Erev Tisha B'Av prepares us for mourning the destruction of the Temple.\n\nWhen the fast begins:\n• Tisha B'Av starts at sunset tonight${sunset?.let { \" (approx. $it)\" } ?: \"\"} and continues until nightfall tomorrow night — not dawn to dusk like minor fasts.\n\nRestrictions from chatzos (halachic midday) today:\n• From chatzos onward: do not eat meat or drink wine (some extend other restrictions — follow your minhag).\n• Reduce pleasurable activities; avoid laundry, haircuts, and swimming per mourning customs.\n\nSeudah hamafseket — the final meal before the fast:\n• Eat a simple meal alone, sitting on the floor or a low stool, with only one cooked dish (e.g. a hard-boiled egg dipped in ashes, or bread with cold water).\n• Do not eat two cooked dishes together; do not recline; do not greet others with \"hello.\"\n• Finish before sunset; afterward, only water is permitted until the fast begins.\n• Many recite Birkat HaMazon and then change into non-leather shoes before sunset.\n\nAfter sunset tonight until nightfall tomorrow:\n• Five afflictions apply (like Yom Kippur): no eating/drinking, no leather shoes, no bathing for pleasure, no anointing, no marital relations.\n• Additionally: no Torah study except sad topics (Eichah, Job, mourning laws); many sit on the floor until chatzos tomorrow; kinot are recited.$shabbatNote\n\nAsk your rav for details if you are ill, pregnant, or nursing.": {
        "he": "ערב ט' באב מכין אותנו לאבל על חורבן בית המקדש.\n\nמתי מתחיל הצום:\n• ט' באב מתחיל בשקיעה הערב${sunset?.let { \" (בערך $it)\" } ?: \"\"} ונמשך עד צאת הכוכבים מחר בלילה — לא משחר עד לילה כמו צומות קלים.\n\nהגבלות מחצות היום (חצות הלכתי) היום:\n• מחצות ואילך: אל תאכלו בשר ואל תשתו יין (חלק מרחיבים הגבלות — לפי המנהג).\n• הפחיתו פעילויות הנאה; הימנעו מכביסה, תספורת ושחייה לפי מנהגי האבל.\n\nסעודה המפסקת — הארוחה האחרונה לפני הצום:\n• אכלו ארוחה פשוטה ביחידות, יושבים על הרצפה או כיסא נמוך, עם מנה מבושלת אחת בלבד (למשל ביצה קשה טבולה באפר, או לחם עם מים קרים).\n• אל תאכלו שתי מנות מבושלות יחד; אל תסעדו בשכיבה; אל תברכו אחרים ב\"שלום\".\n• סיימו לפני השקיעה; לאחר מכן מותר רק מים עד תחילת הצום.\n• רבים אומרים ברכת המזון ואז מחליפים לנעליים שאינן מעור.\n\nמשקיעה הערב עד צאת הכוכבים מחר:\n• חמש עינויים (כמו ביום הכיפורים): אין אכילה/שתייה, אין נעלי עור, אין רחצה להנאה, אין סיכה, אין יחסי אישות.\n• בנוסף: אין לימוד תורה למעט נושאי אבל (איכה, איוב, הלכות אבל); רבים יושבים על הרצפה עד חצות מחר; קינות נאמרות.$shabbatNote\n\nשאלו את הרב לפרטים אם אתם חולים, בהריון או מניקים.",
        "es": "Erev Tisha B'Av nos prepara para el duelo por la destrucción del Templo.\n\nCuándo comienza el ayuno:\n• Tisha B'Av comienza al atardecer esta noche${sunset?.let { \" (aprox. $it)\" } ?: \"\"} y continúa hasta el anochecer mañana por la noche — no de amanecer a atardecer como los ayunos menores.\n\nRestricciones desde chatzot (mediodía halájico) hoy:\n• Desde chatzot en adelante: no comer carne ni beber vino (algunos extienden otras restricciones — siga su minhag).\n• Reduzca actividades placenteras; evite lavandería, cortes de pelo y natación según costumbres de duelo.\n\nSeudah hamafseket — la comida final antes del ayuno:\n• Coma una comida sencilla solo, sentado en el suelo o en un taburete bajo, con solo un plato cocido (p. ej. huevo duro en ceniza, o pan con agua fría).\n• No coma dos platos cocidos juntos; no se recline; no salude con \"hola\".\n• Termine antes del atardecer; después solo se permite agua hasta que comience el ayuno.\n• Muchos recitan Birkat HaMazon y luego cambian a zapatos sin cuero antes del atardecer.\n\nDespués del atardecer esta noche hasta el anochecer mañana:\n• Cinco aflicciones (como Yom Kippur): sin comer/beber, sin zapatos de cuero, sin baño por placer, sin ungir, sin relaciones conyugales.\n• Además: sin estudio de Torá excepto temas tristes (Eijá, Iyov, leyes de duelo); muchos se sientan en el suelo hasta chatzot mañana; se recitan kinot.$shabbatNote\n\nConsulte a su rav si está enfermo, embarazada o amamantando.",
        "fr": "Erev Tisha B'Av nous prépare au deuil de la destruction du Temple.\n\nQuand le jeûne commence :\n• Tisha B'Av commence au coucher du soleil ce soir${sunset?.let { \" (env. $it)\" } ?: \"\"} et continue jusqu'à la tombée de la nuit demain soir — pas de l'aube au crépuscule comme les jeûnes mineurs.\n\nRestrictions à partir de hatzot (midi halakhique) aujourd'hui :\n• À partir de hatzot : ne pas manger de viande ni boire de vin (certains étendent d'autres restrictions — suivez votre minhag).\n• Réduisez les activités plaisantes ; évitez lessive, coupes de cheveux et natation selon les coutumes de deuil.\n\nSeudah hamafseket — le repas final avant le jeûne :\n• Prenez un repas simple seul, assis sur le sol ou un tabouret bas, avec un seul plat cuit (p. ex. œuf dur trempé dans la cendre, ou pain avec eau froide).\n• Ne mangez pas deux plats cuits ensemble ; ne vous allongez pas ; ne saluez pas avec « bonjour ».\n• Terminez avant le coucher du soleil ; ensuite seule l'eau est permise jusqu'au début du jeûne.\n• Beaucoup récitent Birkat HaMazon puis passent à des chaussures non en cuir avant le coucher du soleil.\n\nAprès le coucher du soleil ce soir jusqu'à la tombée de la nuit demain :\n• Cinq afflictions (comme Yom Kippour) : pas de nourriture/boisson, pas de chaussures en cuir, pas de bain pour le plaisir, pas d'onction, pas de relations conjugales.\n• De plus : pas d'étude de Torah sauf sujets tristes (Eikha, Iyov, lois du deuil) ; beaucoup s'assoient sur le sol jusqu'à hatzot demain ; kinot sont récitées.$shabbatNote\n\nConsultez votre rav si vous êtes malade, enceinte ou allaitez.",
        "ru": "Эрев Тиша б'Ав готовит нас к скорби о разрушении Храма.\n\nКогда начинается пост:\n• Тиша б'Ав начинается на закате сегодня вечером${sunset?.let { \" (прим. $it)\" } ?: \"\"} и продолжается до наступления ночи завтра вечером — не от рассвета до заката, как в малых постах.\n\nОграничения с хацот (галахический полдень) сегодня:\n• С хацот: не есть мясо и не пить вино (некоторые расширяют ограничения — следуйте минхагу).\n• Сократите приятные занятия; избегайте стирки, стрижки и плавания по обычаям траура.\n\nСеуда амафсекет — последняя трапеза перед постом:\n• Ешьте простую трапезу в одиночестве, сидя на полу или низком табурете, только с одним приготовленным блюдом (напр. варёное яйцо в пепле или хлеб с холодной водой).\n• Не ешьте два приготовленных блюда вместе; не возлежите; не приветствуйте «привет».\n• Закончите до заката; после разрешена только вода до начала поста.\n• Многие читают Биркат а-Мазон и переобуваются в немеховую обувь до заката.\n\nПосле заката сегодня до наступления ночи завтра:\n• Пять ограничений (как в Йом Кипур): нет еды/питья, нет кожаной обуви, нет купания для удовольствия, нет помазания, нет супружеских отношений.\n• Кроме того: нет изучения Торы, кроме скорбных тем (Эйха, Иов, законы траура); многие сидят на полу до хацот завтра; читают кинот.$shabbatNote\n\nСпросите раввина, если вы больны, беременны или кормите грудью.",
    },
    "Tomorrow is $fastName — a public fast from dawn (alot hashachar) until nightfall (tzeit).\n\nIf you plan to eat before the fast begins:\n• Set a mental condition (tanai) the night before: \"If I wake up hungry before dawn, I will eat.\" Without this condition, waking early and eating may prohibit you from eating again until the fast officially begins at dawn (Shulchan Arukh O.C. 564:1).\n• If you wake before dawn and want to eat, you may drink water and eat foods that are not normally cooked for a meal — e.g. a piece of cake, fruit, or cereal. A full hot meal is disputed; many avoid a formal cooked meal once they have decided to fast (Mishnah Berurah 564:8–9).\n• Stop all eating and drinking at alot hashachar${alotTomorrow?.let { \" (approx. $it — enable location for your exact zman)\" } ?: \" — enable location in Settings for your dawn time\"}.\n\nPractical prep tonight:\n• Hydrate well and eat a balanced dinner.\n• Plan a lighter morning if you will not eat before dawn.\n• Know your synagogue schedule if you plan to attend special prayers.\n\nWho must fast: Jewish adults (bar/bat mitzvah age and older) in good health. Children below bar/bat mitzvah are not required to fast — train them gradually per your rav.$fridayNote": {
        "he": "מחר $fastName — צום ציבורי משחר (עלות השחר) עד צאת הכוכבים (צאת).\n\nאם מתכננים לאכול לפני תחילת הצום:\n• קבעו תנאי בלילה שלפניו: \"אם אתעורר רעב לפני השחר, אוכל.\" בלי תנאי זה, התעוררות מוקדמת ואכילה עלולה לאסור אכילה נוספת עד תחילת הצום בשחר (שולחן ערוך או\"ח תרס\"ד:א).\n• אם מתעוררים לפני השחר ורוצים לאכול, מותר לשתות מים ולאכול מאכלים שלא מבושלים בדרך כלל לארוחה — למשל עוגה, פירות או דגנים. ארוחה חמה מלאה שנויה במחלוקת; רבים נמנעים מארוחה מבושלת רשמית לאחר שהחליטו לצום (משנה ברורה תרס\"ד:ח-ט).\n• הפסיקו אכילה ושתייה בעלות השחר${alotTomorrow?.let { \" (בערך $it — הפעילו מיקום לזמן המדויק)\" } ?: \" — הפעילו מיקום בהגדרות לזמן השחר\"}.\n\nהכנה מעשית הלילה:\n• שתו היטב ואכלו ארוחת ערב מאוזנת.\n• תכננו בוקר קל יותר אם לא תאכלו לפני השחר.\n• בדקו את לוח הזמנים בבית הכנסת אם מתכננים להגיע לתפילות מיוחדות.\n\nמי חייב בצום: מבוגרים יהודים (מגיל בר/בת מצווה ומעלה) בבריאות טובה. ילדים מתחת לגיל בר/בת מצווה אינם חייבים — חנכו בהדרגה לפי הרב.$fridayNote",
        "es": "Mañana es $fastName — un ayuno público desde el amanecer (alot hashachar) hasta el anochecer (tzeit).\n\nSi planea comer antes de que comience el ayuno:\n• Establezca una condición mental (tanai) la noche anterior: \"Si despierto con hambre antes del amanecer, comeré.\" Sin esta condición, despertar temprano y comer puede prohibirle comer de nuevo hasta que el ayuno comience oficialmente al amanecer (Shulchan Arukh O.C. 564:1).\n• Si despierta antes del amanecer y quiere comer, puede beber agua y comer alimentos que normalmente no se cocinan para una comida — p. ej. un trozo de pastel, fruta o cereal. Una comida caliente completa es disputada; muchos evitan una comida cocida formal una vez decidido ayunar (Mishnah Berurah 564:8–9).\n• Deje de comer y beber en alot hashachar${alotTomorrow?.let { \" (aprox. $it — active la ubicación para su zman exacto)\" } ?: \" — active la ubicación en Ajustes para su hora del amanecer\"}.\n\nPreparación práctica esta noche:\n• Hidrátese bien y coma una cena equilibrada.\n• Planee una mañana más ligera si no comerá antes del amanecer.\n• Conozca el horario de su sinagoga si planea asistir a oraciones especiales.\n\nQuién debe ayunar: adultos judíos (edad bar/bat mitzvá o mayor) en buena salud. Los niños menores no están obligados — entrénelos gradualmente según su rav.$fridayNote",
        "fr": "Demain, c'est $fastName — un jeûne public de l'aube (alot hashachar) à la tombée de la nuit (tzeit).\n\nSi vous prévoyez de manger avant le jeûne :\n• Fixez une condition mentale (tanai) la veille : « Si je me réveille affamé avant l'aube, je mangerai. » Sans cette condition, se réveiller tôt et manger peut vous interdire de manger à nouveau jusqu'au début officiel du jeûne à l'aube (Shoulhan Aroukh O.C. 564:1).\n• Si vous vous réveillez avant l'aube et voulez manger, vous pouvez boire de l'eau et manger des aliments normalement non cuits pour un repas — p. ex. un morceau de gâteau, des fruits ou des céréales. Un repas chaud complet est disputé ; beaucoup évitent un repas cuit formel une fois le jeûne décidé (Mishna Beroura 564:8–9).\n• Arrêtez toute nourriture et boisson à alot hashachar${alotTomorrow?.let { \" (env. $it — activez la localisation pour votre zman exact)\" } ?: \" — activez la localisation dans Réglages pour l'heure de l'aube\"}.\n\nPréparation pratique ce soir :\n• Hydratez-vous bien et prenez un dîner équilibré.\n• Prévoyez un matin plus léger si vous ne mangerez pas avant l'aube.\n• Connaissez l'horaire de votre synagogue si vous prévoyez des prières spéciales.\n\nQui doit jeûner : adultes juifs (âge bar/bat mitzvah et plus) en bonne santé. Les enfants plus jeunes ne sont pas tenus — formez-les progressivement selon votre rav.$fridayNote",
        "ru": "Завтра $fastName — общественный пост с рассвета (alot hashachar) до наступления ночи (tzeit).\n\nЕсли планируете есть до начала поста:\n• Установите условие (tanai) накануне: «Если проснусь голодным до рассвета, буду есть.» Без этого раннее пробуждение и еда могут запретить есть снова до официального начала поста на рассвете (Шулхан Арух О.Х. 564:1).\n• Если проснулись до рассвета и хотите есть, можно пить воду и есть продукты, обычно не готовящиеся для трапезы — напр. кусок торта, фрукты или хлопья. Полноценная горячая трапеза спорна; многие избегают формальной горячей трапезы после решения поститься (Мишна Берура 564:8–9).\n• Прекратите есть и пить в alot hashachar${alotTomorrow?.let { \" (прим. $it — включите геолокацию для точного змана)\" } ?: \" — включите геолокацию в Настройках для времени рассвета\"}.\n\nПрактическая подготовка сегодня вечером:\n• Хорошо пейте и съешьте сбалансированный ужин.\n• Планируйте более лёгкое утро, если не будете есть до рассвета.\n• Узнайте расписание синагоги, если планируете особые молитвы.\n\nКто обязан поститься: взрослые евреи (возраст бар/бат мицва и старше) в добром здоровье. Дети младше не обязаны — приучайте постепенно по указанию раввина.$fridayNote",
    },
    "Sefirat HaOmer links Pesach to Shavuot — counting each day from the Exodus toward receiving the Torah.\n\nToday in the Omer: $todaySummary (day $day of 49).\n\nTonight's count:\n• $tonight night — count $todaySummary after nightfall$timePart.\n$nextNightLine\n\nHow to count:\n• Stand and recite the blessing before counting if you are still saying it with a blessing (if you missed a day, ask your rabbi before continuing with a bracha).\n• Say: \"${omerCountSpeechPhrase(day)}\"\n• Count after nightfall (tzeit); complete before dawn. If you forgot at night, count the next day during the daytime without a bracha. If you do this before sunset, you can continue counting on subsequent nights with a bracha. You only lose the blessing permanently if you miss an entire 24-hour cycle (both night and the following day) — ask your rav.\n\n$nusachWhen": {
        "he": "ספירת העומר מקשרת את פסח לשבועות — ספירת כל יום מיציאת מצרים לקראת קבלת התורה.\n\nהיום בעומר: $todaySummary (יום $day מתוך 49).\n\nספירת הלילה:\n• ליל $tonight — ספרו $todaySummary אחרי צאת הכוכבים$timePart.\n$nextNightLine\n\nאיך לספור:\n• עמדו וברכו לפני הספירה אם עדיין אומרים ברכה (אם פספסתם יום, שאלו את הרב לפני המשך עם ברכה).\n• אמרו: \"${omerCountSpeechPhrase(day)}\"\n• ספרו אחרי צאת הכוכבים (tzeit); סיימו לפני השחר. אם שכחתם בלילה, ספרו ביום למחרת בלי ברכה. אם עושים זאת לפני השקיעה, אפשר להמשיך בלילות הבאים עם ברכה. מאבדים את הברכה לצמיתות רק אם מפספסים מחזור של 24 שעות שלם (גם לילה וגם היום שלאחריו) — שאלו את הרב.\n\n$nusachWhen",
        "es": "Sefirat HaOmer une Pesaj con Shavuot — contando cada día desde el Éxodo hacia la recepción de la Torá.\n\nHoy en el Omer: $todaySummary (día $day de 49).\n\nCuenta de esta noche:\n• Noche de $tonight — cuente $todaySummary después del anochecer$timePart.\n$nextNightLine\n\nCómo contar:\n• Párese y recite la bendición antes de contar si aún la dice con brajá (si omitió un día, consulte a su rabino antes de continuar con brajá).\n• Diga: \"${omerCountSpeechPhrase(day)}\"\n• Cuente después del anochecer (tzeit); termine antes del amanecer. Si olvidó de noche, cuente al día siguiente de día sin brajá. Si lo hace antes del atardecer, puede seguir contando en noches posteriores con brajá. Solo pierde la bendición permanentemente si omite un ciclo completo de 24 horas (noche y día siguiente) — consulte a su rav.\n\n$nusachWhen",
        "fr": "Sefirat HaOmer relie Pessah à Shavouot — en comptant chaque jour depuis l'Exode vers la réception de la Torah.\n\nAujourd'hui dans l'Omer : $todaySummary (jour $day sur 49).\n\nCompte de ce soir :\n• Nuit de $tonight — comptez $todaySummary après la tombée de la nuit$timePart.\n$nextNightLine\n\nComment compter :\n• Tenez-vous debout et récitez la bénédiction avant de compter si vous la dites encore avec une brakha (si vous avez manqué un jour, consultez votre rabbin avant de continuer avec brakha).\n• Dites : \"${omerCountSpeechPhrase(day)}\"\n• Comptez après la tombée de la nuit (tzeit) ; terminez avant l'aube. Si vous avez oublié la nuit, comptez le jour suivant en journée sans brakha. Si vous le faites avant le coucher du soleil, vous pouvez continuer les nuits suivantes avec brakha. Vous perdez la bénédiction définitivement seulement si vous manquez un cycle complet de 24 heures (nuit et jour suivant) — consultez votre rav.\n\n$nusachWhen",
        "ru": "Сефират ha-Omer связывает Песах со Шavuot — считая каждый день от Исхода к получению Торы.\n\nСегодня в Омере: $todaySummary (день $day из 49).\n\nВечерний счёт:\n• Ночь $tonight — считайте $todaySummary после наступления ночи$timePart.\n$nextNightLine\n\nКак считать:\n• Встаньте и произнесите благословение перед счётом, если ещё говорите его с брaхой (если пропустили день, спросите раввина перед продолжением с брaхой).\n• Скажите: \"${omerCountSpeechPhrase(day)}\"\n• Считайте после наступления ночи (tzeit); завершите до рассвета. Если забыли ночью, считайте на следующий день днём без брaхи. Если сделаете это до заката, можете продолжать последующие ночи с брaхой. Брaху теряете навсегда только если пропустите полный 24-часовой цикл (и ночь, и следующий день) — спросите раввина.\n\n$nusachWhen",
    },
    "$holidayName is about to begin. Please finish what you are doing, turn off your phone, and prepare to welcome this Yom Tov with joy.\n\nOur Sages teach that rejoicing on Yom Tov is itself a mitzvah — may your observance bring blessing and divine reward to you and your household.": {
        "es": "$holidayName está a punto de comenzar. Termine lo que está haciendo, apague el teléfono y prepárese para recibir este Yom Tov con alegría.\n\nNuestros Sabios enseñan que regocijarse en Yom Tov es en sí misma una mitzvá — que su observancia traiga bendición y recompensa divina a usted y a su hogar.",
        "fr": "$holidayName va commencer. Veuillez terminer ce que vous faites, éteindre votre téléphone et vous préparer à accueillir ce Yom Tov avec joie.\n\nNos Sages enseignent que se réjouir pendant Yom Tov est elle-même une mitzvah — que votre observance vous apporte bénédiction et récompense divine, à vous et à votre foyer.",
        "ru": "$holidayName вот-вот начнётся. Закончите то, что делаете, выключите телефон и приготовьтесь встретить этот Йом Тов с радостью.\n\nНаши мудрецы учат: радоваться в Йом Тов — сама по себе мицва. Пусть ваше соблюдение принесёт благословение и божественную награду вам и вашему дому.",
    },
    "Today is $name — $meaning\n\nMinor fast rules:\n• No eating or drinking from dawn until nightfall.\n• Washing, music, and showering are generally permitted (unlike Tisha B'Av and Yom Kippur).\n• Special selichot and prayers may be recited in synagogue — check your community schedule.": {
        "es": "Hoy es $name — $meaning\n\nReglas de ayuno menor:\n• No comer ni beber desde el amanecer hasta el anochecer.\n• Lavado, música y ducha están generalmente permitidos (a diferencia de Tisha B'Av y Yom Kippur).\n• Pueden recitarse selichot y oraciones especiales en la sinagoga — consulte el horario de su comunidad.",
        "fr": "Aujourd'hui, c'est $name — $meaning\n\nRègles de jeûne mineur :\n• Ne pas manger ni boire de l'aube jusqu'à la tombée de la nuit.\n• Le lavage, la musique et la douche sont généralement permis (contrairement à Tisha B'Av et Yom Kippur).\n• Des selichot et prières spéciales peuvent être récitées à la synagogue — vérifiez le calendrier de votre communauté.",
        "ru": "Сегодня $name — $meaning\n\nПравила малого поста:\n• Не есть и не пить с рассвета до наступления ночи.\n• Мытьё, музыка и душ, как правило, разрешены (в отличие от Тиша б'Ав и Йом Кипура).\n• В синагоге могут читаться особые селихот и молитвы — проверьте расписание вашей общины.",
    },
    "Read this today (Friday) before Shabbat candles — the app is not for use on Shabbat.\n\nTomorrow is Shabbat and erev $tomorrowChag. $tomorrowChag begins tomorrow night at nightfall (Motzei Shabbat), not tonight. Finish Yaknehaz prep, Yom Tov candles from a pre-existing flame, wine, and festive food before Shabbat ends.": {
        "es": "Lea esto hoy (viernes) antes de las velas de Shabat — la aplicación no debe usarse en Shabat.\n\nMañana es Shabat y erev $tomorrowChag. $tomorrowChag comienza mañana por la noche al anochecer (Motzei Shabat), no esta noche. Termine la preparación de Yaknehaz, las velas de Yom Tov desde una llama preexistente, el vino y la comida festiva antes de que termine Shabat.",
        "fr": "Lisez ceci aujourd'hui (vendredi) avant les bougies de Chabbat — l'application ne doit pas être utilisée pendant Chabbat.\n\nDemain est Chabbat et erev $tomorrowChag. $tomorrowChag commence demain soir à la tombée de la nuit (Motzei Chabbat), pas ce soir. Terminez la préparation Yaknehaz, les bougies de Yom Tov à partir d'une flamme préexistante, le vin et la nourriture festive avant la fin de Chabbat.",
        "ru": "Прочитайте это сегодня (в пятницу) перед зажжением шаббатных свечей — приложение не для использования в Шабbat.\n\nЗавтра Шабbat и эрев $tomorrowChag. $tomorrowChag начинается завтра вечером с наступлением ночи (Моцэи Шабbat), а не сегодня. Завершите подготовку Якнехаз, свечи Йом Тов от уже существующего пламени, вино и праздничную еду до окончания Шабbата.",
    },
    "New mitzvah submission from the Mitz Mode app:\n            \n            Submitted by: $submitterName\n            Mitzvah text: $mitzvahText\n            \n            Submitted on: ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Please review and consider adding to the mitzvah database.": {
        "es": "Nueva presentación de mitzvá desde la aplicación Mitz Mode:\n            \n            Presentado por: $submitterName\n            Texto de la mitzvá: $mitzvahText\n            \n            Presentado el: ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Revise y considere añadirlo a la base de datos de mitzvot.",
        "fr": "Nouvelle soumission de mitzvah depuis l'application Mitz Mode :\n            \n            Soumis par : $submitterName\n            Texte de la mitzvah : $mitzvahText\n            \n            Soumis le : ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Veuillez examiner et envisager d'ajouter à la base de données des mitzvot.",
        "ru": "Новая заявка mitzvah из приложения Mitz Mode:\n            \n            Отправитель: $submitterName\n            Текст мицвы: $mitzvahText\n            \n            Отправлено: ${java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\", java.util.Locale.getDefault()).format(java.util.Date())}\n            \n            Пожалуйста, просмотрите и рассмотрите добавление в базу данных мицvot.",
    },
    "If you forgot at Maariv on Rosh Chodesh:\n• Still in Retzei before God's name at the conclusion — insert Yaaleh V'yavo there and continue ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Once you finished Retzei, or after the entire Amidah — do not go back and do not repeat. Beit Din sanctified the new month by day, not at night (Berachot 30b; $YAALEH_VYAVO_HALACHA_SOURCE). Continue davening.": {
        "fr": "Si vous avez oublié à Maariv le Rosh Chodesh :\n• Toujours dans Retzei avant le nom de D. à la conclusion — insérez Yaaleh V'yavo là et continuez ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Une fois Retzei terminé, ou après toute l'Amidah — ne revenez pas en arrière et ne répétez pas. Le Beit Din a sanctifié le nouveau mois de jour, pas de nuit (Berachot 30b ; $YAALEH_VYAVO_HALACHA_SOURCE). Continuez la tefillah.",
        "ru": "Если вы забыли в Маариве в Рosh Хodesh:\n• Ещё в Рetzee перед Именем Б-га в заключении — вставьте Yaaleh V'yavo там и продолжите ($YAALEH_VYAVO_HALACHA_SOURCE).\n• После завершения Retzei или всей Амиды — не возвращайтесь и не повторяйте. Бейт Дин освящал новый месяц днём, а не ночью (Berachot 30b; $YAALEH_VYAVO_HALACHA_SOURCE). Продолжайте молитву.",
    },
    "If you forgot:\n• Still in Retzei (before concluding the blessing) — insert Yaaleh V'yavo in its place and continue ($YAALEH_VYAVO_HALACHA_SOURCE).\n• After concluding Retzei — return to the beginning of Retzei, insert Yaaleh V'yavo, and complete the remaining blessings ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Finished the entire Amidah (after the final Yihiyu L'ratzon) — repeat only the $service Amidah (Shemoneh Esrei), never the full service, even if you already davened Musaf, Maariv, or anything else afterward ($YAALEH_VYAVO_HALACHA_SOURCE).": {
        "es": "Si se olvidó:\n• Todavía en Retzei (antes de concluir la bendición) — inserte Yaaleh V'yavo en su lugar y continúe ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Después de concluir Retzei — vuelva al comienzo de Retzei, inserte Yaaleh V'yavo y complete las bendiciones restantes ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Terminó toda la Amidah (después del Yihiyu L'ratzon final) — repita solo la Amidah de $service (Shemoneh Esrei), nunca el servicio completo, aunque ya haya rezado Musaf, Maariv u otra cosa después ($YAALEH_VYAVO_HALACHA_SOURCE).",
        "fr": "Si vous avez oublié :\n• Toujours dans Retzei (avant de conclure la bénédiction) — insérez Yaaleh V'yavo à sa place et continuez ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Après avoir conclu Retzei — revenez au début de Retzei, insérez Yaaleh V'yavo et complétez les bénédictions restantes ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Amidah entière terminée (après le Yihiyu L'ratzon final) — répétez uniquement l'Amidah de $service (Shemoneh Esrei), jamais le service complet, même si vous avez déjà prié Moussaf, Maariv ou autre ensuite ($YAALEH_VYAVO_HALACHA_SOURCE).",
        "ru": "Если вы забыли:\n• Ещё в Retzei (до завершения благословения) — вставьте Yaaleh V'yavo на его место и продолжите ($YAALEH_VYAVO_HALACHA_SOURCE).\n• После завершения Retzei — вернитесь к началу Retzei, вставьте Yaaleh V'yavo и завершите оставшиеся благословения ($YAALEH_VYAVO_HALACHA_SOURCE).\n• Завершили всю Амиду (после финального Yihiyu L'ratzon) — повторите только Амиду $service (Shemoneh Esrei), никогда полный порядок, даже если уже молились Musaf, Maariv или что-то ещё после ($YAALEH_VYAVO_HALACHA_SOURCE).",
    },
    "Chanukah night $day of 8 — lighting the menorah.\n\nWhen:\n• Light after tzeit (nightfall) — not before sunset. On Friday, light Chanukah candles before Shabbat candles (approx. 20–25 minutes before nightfall).\n• Friday candle size warning: Because Chanukah candles must burn for at least 30 minutes after nightfall (tzeit), standard small Chanukah candles cannot be used on Friday afternoon — they will burn out before nightfall and invalidate the mitzvah. Use larger candles (like standard Shabbat candles) or pour enough oil to burn for at least ~90 minutes from lighting (often longer if you light well before sunset) so they survive well past dark.\n• On Motzei Shabbat, light Chanukah before or after Havdalah per minhag.\n• Motzei Shabbat lighting: If your custom is to light Chanukah candles before formal Havdalah over wine, you must terminate Shabbat first — recite Atah Chonantanu in the Maariv Amidah, or say \"Baruch hamavdil bein kodesh l'chol\" aloud before striking a match. Melacha remains forbidden until Shabbat has ended.\n\nHow:\n• Pirsumei nisa — publicize the miracle; place menorah by a window or doorway where passersby can see.\n• Placement: Insert candles from right to left in the menorah (universal custom per Shulchan Arukh O.C. 676:5 — Ashkenaz, Sephard, and Chabad).\n• Lighting: Light from left to right, always starting with the newest candle (the leftmost one) and moving toward the right. Use the shamash to light each candle.\n• Oil or candles must burn at least 30 minutes after nightfall.\n• Brachot (first night all three; other nights two): lehadlik ner shel Chanukah, she'asa nissim; Shehecheyanu on first night.\n• Do not use the Chanukah lights for work — shamash is for utility light.\n\nPrayers & meals:\n• Insert Al HaNissim into every Amidah and into Birkat Hamazon (bentching) all day long.\n\n${if (day == 1) \"First night: say all three brachot including Shehecheyanu.\" else \"Tonight: two brachot (no Shehecheyanu unless first time lighting this year).\"}\n\nAfter lighting: sing HaNeiros halalu and Maoz Tzur (custom).": {
        "he": "ליל חנוכה $day מתוך 8 — הדלקת המנורה.\n\nמתי:\n• הדליקו אחרי צאת הכוכבים (tzeit) — לא לפני השקיעה. ביום שישי, הדליקו נרות חנוכה לפני נרות שבת (כ-20–25 דקות לפני צאת הכוכבים).\n• אזהרת גודל נר ביום שישי: כי נרות חנוכה חייבים לבעור לפחות 30 דקות אחרי צאת הכוכבים, נרות חנוכה קטנים סטנדרטיים אינם מתאימים ביום שישי — הם ייכבו לפני צאת הכוכבים ויבטלו את המצווה. השתמשו בנרות גדולים יותר (כמו נרות שבת) או בשפכו מספיק שמן לבעור כ-90 דקות מההדלקה.\n• במוצאי שבת, הדליקו חנוכה לפני או אחרי הבדלה לפי המנהג.\n• הדלקה במוצאי שבת: אם המנהג להדליק לפני הבדלה על היין, יש לצאת משבת קודם — אמרו אתה חוננתנו בעמידת מעריב, או \"ברוך המבדיל בין קודש לחול\" בקול לפני הדלקת גפרור. מלאכה אסורה עד סיום השבת.\n\nאיך:\n• פרסומי ניסא — פרסמו את הנס; הניחו מנורה ליד חלון או פתח.\n• סידור: הכניסו נרות מימין לשמאל (מנהג אוניברסלי לפי שו\"ע או\"ח תרע\"ו:ה).\n• הדלקה: הדליקו משמאל לימין, תמיד מהנר החדש (השמאלי) לימין. השתמשו בשמש להדלקת כל נר.\n• שמן או נרות חייבים לבעור לפחות 30 דקות אחרי צאת הכוכבים.\n• ברכות (לילה ראשון שלוש; שאר הלילות שתיים): להדליק נר של חנוכה, שעשה ניסים; שהחיינו בלילה הראשון.\n• אל תשתמשו באור חנוכה לעבודה — השמש לצורך.\n\nתפילות וארוחות:\n• הוסיפו על הניסים בכל עמידה ובברכת המזון כל היום.\n\n${if (day == 1) \"First night: say all three brachot including Shehecheyanu.\" else \"Tonight: two brachot (no Shehecheyanu unless first time lighting this year).\"}\n\nאחרי ההדלקה: שירו הנרות הללו ומעוז צור (מנהג).",
        "es": "Noche de Janucá $day de 8 — encender la menorá.\n\nCuándo:\n• Encienda después del anochecer (tzeit) — no antes del atardecer. El viernes, encienda velas de Janucá antes de las velas de Shabat (aprox. 20–25 minutos antes del anochecer).\n• Advertencia de velas del viernes: las velas de Janucá deben arder al menos 30 minutos después del anochecer; las velas pequeñas estándar no sirven el viernes por la tarde. Use velas más grandes (como las de Shabat) o suficiente aceite para ~90 minutos desde el encendido.\n• En Motzei Shabat, encienda Janucá antes o después de Havdalah según minhag.\n• Encendido en Motzei Shabat: si su costumbre es encender antes de Havdalah formal sobre vino, debe terminar Shabat primero — recite Atah Chonantanu en la Amidá de Maariv, o diga \"Baruch hamavdil bein kodesh l'chol\" en voz alta antes de encender. Melajá sigue prohibida hasta que Shabat haya terminado.\n\nCómo:\n• Pirsumei nisa — publique el milagro; coloque la menorá junto a una ventana o puerta.\n• Colocación: inserte velas de derecha a izquierda (costumbre universal según Shulchan Arukh O.C. 676:5).\n• Encendido: encienda de izquierda a derecha, siempre desde la vela más nueva (la izquierda). Use el shamash para cada vela.\n• Aceite o velas deben arder al menos 30 minutos después del anochecer.\n• Berajot (primera noche las tres; otras noches dos): lehadlik ner shel Chanukah, she'asa nissim; Shehecheyanu la primera noche.\n• No use las luces de Janucá para trabajo — el shamash es para utilidad.\n\nOraciones y comidas:\n• Inserte Al HaNissim en cada Amidá y en Birkat Hamazón todo el día.\n\n${if (day == 1) \"First night: say all three brachot including Shehecheyanu.\" else \"Tonight: two brachot (no Shehecheyanu unless first time lighting this year).\"}\n\nDespués del encendido: cante HaNeiros halalu y Maoz Tzur (costumbre).",
        "fr": "Nuit de Hanoucca $day sur 8 — allumer la menorah.\n\nQuand :\n• Allumez après la tombée de la nuit (tzeit) — pas avant le coucher du soleil. Vendredi, allumez les bougies de Hanoucca avant celles de Chabbat (env. 20–25 minutes avant la nuit).\n• Avertissement bougies du vendredi : les bougies de Hanoucca doivent brûler au moins 30 minutes après la nuit ; les petites bougies standard ne conviennent pas vendredi après-midi. Utilisez des bougies plus grandes (comme celles de Chabbat) ou assez d'huile pour ~90 minutes.\n• À Motzei Chabbat, allumez Hanoucca avant ou après Havdalah selon minhag.\n• Allumage Motzei Chabbat : si votre coutume est d'allumer avant Havdalah sur le vin, terminez Chabbat d'abord — récitez Atah Chonantanu dans l'Amidah de Maariv, ou dites « Baruch hamavdil bein kodesh l'chol » à voix haute avant d'allumer. Melakha reste interdite jusqu'à la fin de Chabbat.\n\nComment :\n• Pirsoumei nissa — publicisez le miracle ; placez la menorah près d'une fenêtre ou porte.\n• Placement : insérez les bougies de droite à gauche (coutume universelle selon Choulhan Aroukh O.C. 676:5).\n• Allumage : allumez de gauche à droite, toujours depuis la bougie la plus récente (la gauche). Utilisez le shamash pour chaque bougie.\n• Huile ou bougies doivent brûler au moins 30 minutes après la nuit.\n• Bérakhot (première nuit les trois ; autres nuits deux) : lehadlik ner shel Hanoucca, she'asa nissim ; Sheheheyanou la première nuit.\n• N'utilisez pas les lumières de Hanoucca pour le travail — le shamash sert d'utilité.\n\nPrières et repas :\n• Insérez Al HaNissim dans chaque Amidah et dans Birkat HaMazon toute la journée.\n\n${if (day == 1) \"First night: say all three brachot including Shehecheyanu.\" else \"Tonight: two brachot (no Shehecheyanu unless first time lighting this year).\"}\n\nAprès l'allumage : chantez HaNeiros halalu et Maoz Tzur (coutume).",
        "ru": "Ночь Хануки $day из 8 — зажигание меноры.\n\nКогда:\n• Зажигайте после наступления ночи (tzeit) — не до заката. В пятницу зажигайте свечи Хануки перед свечами Шаббата (примерно за 20–25 минут до ночи).\n• Предупреждение о пятничных свечах: свечи Хануки должны гореть минимум 30 минут после наступления ночи; стандартные маленькие свечи не подходят в пятницу днём. Используйте большие свечи (как шаббатные) или достаточно масла на ~90 минут.\n• В Моцэи Шаббат зажигайте Хануку до или после Хавдалы по минхагу.\n• Зажигание в Моцэи Шаббат: если обычай — до формальной Хавдалы над вином, сначала завершите Шаббат — прочитайте Atah Chonantanu в Амиде Маарива или скажите «Baruch hamavdil bein kodesh l'chol» вслух перед зажиганием. Мелаха запрещена до окончания Шаббата.\n\nКак:\n• Пирсумени ниса — возвещайте чудо; поставьте менору у окна или двери.\n• Расстановка: вставляйте свечи справа налево (универсальный обычай по Шулхан Арух О.Х. 676:5).\n• Зажигание: слева направо, всегда с новой свечи (левой). Используйте шамаш для каждой свечи.\n• Масло или свечи должны гореть минимум 30 минут после наступления ночи.\n• Брахот (в первую ночь все три; в остальные две): lehadlik ner shel Chanukah, she'asa nissim; Shehecheyanu в первую ночь.\n• Не используйте огни Хануки для работы — шамаш для бытового света.\n\nМолитвы и трапезы:\n• Вставляйте Al HaNissim в каждую Амиду и в Биркат а-Мазон весь день.\n\n${if (day == 1) \"First night: say all three brachot including Shehecheyanu.\" else \"Tonight: two brachot (no Shehecheyanu unless first time lighting this year).\"}\n\nПосле зажигания: пойте HaNeiros halalu и Maoz Tzur (обычай).",
    },
    "Today is Erev Yom Kippur — a unique day of eating before the holiest fast of the year.\n\nMitzvah to eat today:\n• It is a mitzvah to eat and drink generously all day Erev Yom Kippur (Shulchan Arukh O.C. 604:1; Mishnah Berurah).\n• Have a festive Yom Tov-style meal — many begin with candle lighting and Kiddush as for Yom Tov (ask your rav for your minhag).\n• The Talmud compares eating on Erev Yom Kippur to fasting on Yom Kippur itself for merit (Rosh Hashana 9a).\n\nBefore the fast begins:\n• Halachic fast time: Yom Kippur runs from sunset tonight${sunset?.let { \" (approx. $it)\" } ?: \"\"} until nightfall tomorrow ($tzeitTomorrow).\n• Tosefet (adding from the weekday): Many communities begin abstaining from food and drink somewhat before sunset — accepting the fast early, as we \"add from the weekday onto the holy day\" (Yoma 81b; Shulchan Arukh O.C. 608:1). How many minutes early varies by community; ask your rav. The sunset time in this app is when the fast is definitely in effect, not necessarily when your synagogue begins Kol Nidrei.\n• Kol Nidrei before sunset: Kol Nidrei is the annulment of vows (hatarat nedarim) before the Day of Atonement. A beit din cannot convene on Yom Kippur itself, so Kol Nidrei must be completed before sunset while it is still weekday (Rosh Hashana 9b; Shulchan Arukh O.C. 619:1). That is why services often start well before sunset — so the congregation can finish Kol Nidrei and begin the fast with tosefet while it is still erev.\n• Ask forgiveness from those you may have hurt; give tzedakah; immerse in a mikveh if that is your custom.\n• Light Yom Kippur candles before sunset (married women traditionally light; others follow community — ask your rav).\n\nMotzei Yom Kippur meal:\n• After the fast ends tomorrow night, it is a mitzvah to eat a proper meal — not only a snack. Many have a festive break-fast.\n• Chabad tradition (Baal HaTanya) teaches that one's livelihood (parnassa) for the year is especially connected to this post-Yom Kippur meal — eat with joy and intention after davening and Havdalah.\n\nWho fasts tomorrow: Healthy Jewish adults from bar/bat mitzvah age. Those who are ill, pregnant, nursing, or recently gave birth should ask a rav — often they eat in smaller amounts (shiurim) or are exempt.": {
        "he": "היום ערב יום הכיפורים — יום ייחודי של אכילה לפני הצום הקדוש ביותר של השנה.\n\nמצווה לאכול היום:\n• מצווה לאכול ולשתות בנדיבות כל היום ערב יום הכיפורים (שולחן ערוך או\"ח תר\"ד:א; משנה ברורה).\n• ארוחה חגיגית בסגנון יום טוב — רבים מתחילים בהדלקת נרות וקידוש כמו ביום טוב (שאלו את הרב למנהגכם).\n• התלמוד משווה אכילה בערב יום הכיפורים לצום ביום הכיפורים עצמו לזכות (ראש השנה ט א).\n\nלפני תחילת הצום:\n• זמן הצום ההלכתי: יום הכיפורים נמשך משקיעה הערב${sunset?.let { \" (בערך $it)\" } ?: \"\"} עד צאת הכוכבים מחר ($tzeitTomorrow).\n• תוספת (הוספה מחול על הקודש): קהילות רבות מתחילות להימנע ממזון ושתייה מעט לפני השקיעה — קבלת הצום מוקדם, כפי ש\"מוסיפים מחול על היום הקדוש\" (יומא פא ב; שולחן ערוך או\"ח תר\"ח:א). כמה דקות מוקדם משתנה לפי הקהילה; שאלו את הרב. זמן השקיעה באפליקציה הוא כשהצום בהחלט בתוקף, לא בהכרח כשבית הכנסת מתחיל כל נדרי.\n• כל נדרי לפני השקיעה: כל נדרי הוא התרת נדרים לפני יום הכיפורים. בית דין אינו יכול להתכנס ביום הכיפורים עצמו, ולכן כל נדרי חייב להסתיים לפני השקיעה בעודו חול (ראש השנה ט ב; שולחן ערוך או\"ח תרי\"ט:א). לכן התפילות מתחילות הרבה לפני השקיעה — כדי שהקהילה תסיים כל נדרי ותתחיל את הצום עם תוספת בעוד זה עדיין ערב.\n• בקשו סליחה ממי שאולי פגעתם; תנו צדקה; טבלו במקווה אם זה מנהגכם.\n• הדליקו נרות יום הכיפורים לפני השקיעה (נשים נשואות מדליקות במסורת; אחרים לפי הקהילה — שאלו את הרב).\n\nארוחת מוצאי יום הכיפורים:\n• לאחר סיום הצום מחר בלילה, מצווה לאכול ארוחה נכונה — לא רק חטיף. לרבים יש ארוחת שבירת צום חגיגית.\n• מסורת חב\"ד (בעל התניא) מלמדת שפרנסת השנה קשורה במיוחד לארוחה זו לאחר יום הכיפורים — אכלו בשמחה ובכוונה אחרי התפילה והבדלה.\n\nמי צם מחר: מבוגרים יהודים בריאים מגיל בר/בת מצווה. חולים, נשים בהריון, מניקות או לאחר לידה — שאלו את הרב; לעתים אוכלים בכמויות קטנות (שיעורים) או פטורים.",
    },
}


def main() -> None:
    by_lang: dict[str, dict[str, str]] = {"he": {}, "es": {}, "fr": {}, "ru": {}}
    for en, langs in FIXES.items():
        for lang, tr in langs.items():
            by_lang[lang][en] = tr

    # Pull long seasonal strings from batch shards + restore Kotlin blocks from English
    import re as _re
    re = _re
    strings = json.loads((ROOT / "data" / "translation-catalog" / "strings.json").read_text(encoding="utf-8"))["strings"]
    batch = json.loads((ROOT / "data" / "translation-catalog" / "shards" / "batch_025.json").read_text(encoding="utf-8"))
    extra_prefixes = (
        "Today is Erev Yom Kippur",
        "The week before Sukkot",
        "Sukkot (first day)",
    )

    def kotlin_blocks(text: str) -> list[str]:
        blocks, i = [], 0
        while i < len(text):
            if text.startswith("${", i):
                depth, j = 1, i + 2
                while j < len(text) and depth > 0:
                    if text[j] == "{":
                        depth += 1
                    elif text[j] == "}":
                        depth -= 1
                    j += 1
                blocks.append(text[i:j])
                i = j
            else:
                i += 1
        return blocks

    def restore_blocks(en: str, tr: str) -> str:
        en_b, tr_b = kotlin_blocks(en), kotlin_blocks(tr)
        if len(en_b) == len(tr_b):
            for eb, tb in zip(en_b, tr_b):
                if eb != tb:
                    tr = tr.replace(tb, eb, 1)
        return tr

    def force_english_kotlin(en: str, tr: str) -> str:
        for eb in kotlin_blocks(en):
            for tb in kotlin_blocks(tr):
                if tb != eb:
                    tr = tr.replace(tb, eb, 1)
        return tr

    def replace_first_kotlin_block(tr: str, replacement: str) -> str:
        idx = tr.find("${")
        if idx < 0:
            return tr
        depth, j = 1, idx + 2
        while j < len(tr) and depth > 0:
            if tr[j] == "{":
                depth += 1
            elif tr[j] == "}":
                depth -= 1
            j += 1
        return tr[:idx] + replacement + tr[j:]

    def repair_corrupted_kotlin(en: str, tr: str, lang: str = "") -> str:
        en_blocks = kotlin_blocks(en)
        tr_blocks = kotlin_blocks(tr)
        if len(en_blocks) == len(tr_blocks):
            if any(len(tb) > len(eb) * 2 for eb, tb in zip(en_blocks, tr_blocks)):
                pass  # fall through to mega-block repair below
            else:
                return force_english_kotlin(en, tr)
        for eb in en_blocks:
            if eb in tr:
                continue
            idx = tr.find("${")
            if idx < 0:
                break
            depth, j = 1, idx + 2
            while j < len(tr) and depth > 0:
                if tr[j] == "{":
                    depth += 1
                elif tr[j] == "}":
                    depth -= 1
                j += 1
            giant = tr[idx:j]
            prefix = tr[:idx]
            if j >= len(tr) and len(giant) > len(eb) + 100:
                cut = giant.find("Tosefet")
                if cut < 0:
                    cut = giant.find("טוספט")
                if cut < 0:
                    cut = giant.find("• ")
                suffix = giant[cut:] if cut > 0 else ""
                middles = {
                    "es": " hasta la noche de mañana ($tzeitTomorrow).\n",
                    "fr": " jusqu'à la tombée de la nuit demain ($tzeitTomorrow).\n",
                    "ru": " до наступления ночи завтра ($tzeitTomorrow).\n",
                    "he": " עד צאת הכוכבים מחר ($tzeitTomorrow).\n",
                }
                mid = middles.get(lang, " until nightfall tomorrow ($tzeitTomorrow).\n")
                if suffix and not suffix.startswith("•"):
                    suffix = "• " + suffix.lstrip()
                tr = prefix + eb + mid + suffix
            else:
                tr = prefix + eb + tr[j:]
        return tr

    for prefix in extra_prefixes:
        for en in strings:
            if not en.startswith(prefix):
                continue
            for lang in ("he", "es", "fr", "ru"):
                if en in by_lang[lang]:
                    continue
                tr = batch.get(lang, {}).get(en)
                if not tr:
                    continue
                tr = repair_corrupted_kotlin(en, tr, lang)
                by_lang[lang][en] = tr
            break

    catalog_set = set(strings)
    for lang in by_lang:
        for en, tr in list(by_lang[lang].items()):
            if en in catalog_set:
                by_lang[lang][en] = repair_corrupted_kotlin(en, tr, lang)

    # Erev Yom Kippur — ensure $tzeitTomorrow and sunset kotlin block from English
    for en in strings:
        if not en.startswith("Today is Erev Yom Kippur"):
            continue
        for lang in ("he", "es", "fr", "ru"):
            tr = by_lang[lang].get(en) or batch.get(lang, {}).get(en, "")
            if not tr:
                continue
            tr = repair_corrupted_kotlin(en, tr, lang)
            by_lang[lang][en] = tr
        break

    OUT.write_text(json.dumps(by_lang, ensure_ascii=False, indent=2), encoding="utf-8")
    total = sum(len(v) for v in by_lang.values())
    print(f"wrote {OUT} ({total} entries across langs)")


if __name__ == "__main__":
    main()
