#!/usr/bin/env python3
"""Build local_007.json — final 18 local mitzvot with human translations for gaps."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEYS = json.loads((ROOT / "data/translation-catalog/_keys_local_007.json").read_text(encoding="utf-8"))
COMPOSE = ROOT / "shared/src/commonMain/composeResources/files/translations"
LANGS = ("he", "es", "fr", "ru")

NEW: dict[str, dict[str, str]] = {
    "Pray for a shidduch (wife) for my friend Mordechai Shaul ben Devorah - submitted by HS. Our sages teach that when you pray for another person and you happen to need the same thing yourself, you are answered first — because selfless prayer opens the highest gates. They also teach that matching a husband and wife is as difficult for G-d as splitting the Red Sea, meaning every marriage is orchestrated from Heaven with extraordinary care. A heartfelt prayer for a friend's shidduch is one of the greatest gifts you can give.": {
        "he": "התפללו לשידוך (אישה) עבור חברי מרדכי שאול בן דבורה — הוגש על ידי HS. חכמינו מלמדים שכשמתפללים עבור אדם אחר וגם אתם זקוקים לאותו דבר — נענים קודם, כי תפילה חסרת אנוכיות פותחת את השערים העליונים. הם גם מלמדים שזיווג בני זוג קשה לה' כקריעת ים סוף — כל נישואין מיועדים מן השמים בדאגה יוצאת דופן. תפילה כנה לשידוך של חבר היא מאחת המתנות הגדולות שאפשר לתת.",
        "es": "Ora por un shidduj (esposa) para mi amigo Mordechai Shaul ben Devorah — enviado por HS. Nuestros Sabios enseñan que cuando oras por otra persona y tú también necesitas lo mismo, te responden primero — porque la oración desinteresada abre las puertas más altas. También enseñan que emparejar esposos es tan difícil para D-s como dividir el Mar Rojo; cada matrimonio es orquestado desde el Cielo con cuidado extraordinario. Una oración sincera por el shidduj de un amigo es uno de los mayores regalos que puedes dar.",
        "fr": "Priez pour un shidduj (épouse) pour mon ami Mordechai Shaul ben Devorah — soumis par HS. Nos Sages enseignent que lorsque vous priez pour une autre personne et que vous avez vous-même besoin de la même chose, vous êtes exaucé en premier — car la prière désintéressée ouvre les plus hautes portes. Ils enseignent aussi qu'unir un mari et une femme est aussi difficile pour D. que de fendre la mer Rouge : chaque mariage est orchestré du Ciel avec un soin extraordinaire. Une prière sincère pour le shidduj d'un ami est l'un des plus grands cadeaux que vous puissiez offrir.",
        "ru": "Молитесь о shidduch (жене) для моего друга Mordechai Shaul ben Devorah — от HS. Мудрецы учат: когда вы молитесь за другого и сами нуждаетесь в том же, вас услышат первым — ибо бескорыстная молитва открывает высшие ворота. Они также учат, что свести мужа и жену для Hashem столь же трудно, как рассечь Красное море: каждый брак устроен с Небес с необычайной заботой. Искренняя молитва о shidduch друга — один из величайших даров, которые вы можете дать.",
    },
    "Got some spare time? Visit someone who's sick. Our sages teach that visiting the sick removes one-sixtieth of their illness! The mitzvah of bikkur cholim — visiting the sick — is one of the ways we walk in G-d's ways, just as He visited Abraham when he was recovering. Jewish law teaches that we should sit with the ill, comfort them, and help with whatever they need — even if it's just keeping them company for a few minutes. Your presence can lift someone's spirits as much as any medicine.": {
        "he": "יש לכם קצת זמן פנוי? בקרו מישהו שחולה. חכמינו מלמדים שביקור חולים מסיר אחד משישים מהחולי! מצוות ביקור חולים היא אחת הדרכים ללכת בדרכיו של ה', כשם שביקר את אברהם בהחלמתו. ההלכה מלמדת לשבת עם החולים, לנחם אותם ולעזור במה שצריך — גם אם רק לשהות לידם כמה דקות. הנוכחות שלכם יכולה להרים את רוחם כמו כל תרופה.",
        "es": "¿Tienes un rato libre? Visita a alguien enfermo. Nuestros Sabios enseñan que visitar al enfermo quita una sexagésima parte de su enfermedad. La mitzvá de bikkur jolim — visitar al enfermo — es una forma de andar en los caminos de D-s, como Él visitó a Abraham cuando se recuperaba. La ley judía enseña sentarnos con los enfermos, consolarlos y ayudar en lo que necesiten — aunque sea solo acompañarlos unos minutos. Tu presencia puede levantar el ánimo tanto como cualquier medicina.",
        "fr": "Vous avez un moment libre ? Rendez visite à quelqu'un de malade. Nos Sages enseignent que visiter le malade enlève un soixantième de sa maladie ! La mitzvah de bikkour 'holim — visiter les malades — est l'une des façons de marcher dans les voies de D., comme Il a rendu visite à Abraham lorsqu'il convalesçait. La loi juive enseigne de s'asseoir auprès des malades, les réconforter et les aider — ne serait-ce que quelques minutes de compagnie. Votre présence peut remonter le moral autant qu'un médicament.",
        "ru": "Есть свободная минута? Навестите больного. Мудрецы учат: посещение больного снимает одну шестидесятую болезни! Mitzvah bikkur cholim — навестить больного — один из способов идти путями Hashem, как Он навестил Авраама в выздоровлении. Галаха учит сидеть с больными, утешать и помогать — хотя бы несколько минут рядом. Ваше присутствие может поднять дух не хуже лекарства.",
    },
    "Saw a lost object recently? 🔍 Don't just ignore it! Go back and try to return it to its owner (if possible). That's the mitzvah of Hashavat Aveidah (returning lost objects). The Torah teaches that if you see your fellow's animal or belongings wandering off, you may not look away — you must make an effort to return them. Our sages devoted entire discussions to this mitzvah: how hard you must try, what you can keep as a reward for your trouble, and why restoring someone's property is also restoring their dignity.": {
        "he": "ראיתם לאחרונה חפץ אבוד? 🔍 אל תתעלמו! חזרו ונסו להחזירו לבעליו (אם אפשר). זו מצוות השבת אבידה. התורה מלמדת שאם רואים את בהמת חברכם או חפציו הולכים לאיבוד — אסור להתעלם; חייבים להשתדל להחזיר. חכמינו הקדישו דיונים שלמים למצווה זו: עד כמה חייבים להשתדל, מה מותר לשמור כשכר על הטרחה, ולמה החזרת רכוש הוא גם החזרת כבוד.",
        "es": "¿Viste un objeto perdido recientemente? 🔍 ¡No lo ignores! Vuelve e intenta devolverlo a su dueño (si es posible). Esa es la mitzvá de Hashavat Aveidá (devolver objetos perdidos). La Torá enseña que si ves el animal o pertenencias de tu prójimo extraviándose, no puedes mirar hacia otro lado — debes esforzarte por devolverlos. Nuestros Sabios dedicaron largas discusiones a esta mitzvá: cuánto esforzarse, qué puedes quedarte como recompensa y por qué devolver propiedad es devolver dignidad.",
        "fr": "Vous avez vu un objet perdu récemment ? 🔍 Ne l'ignorez pas ! Retournez et essayez de le rendre à son propriétaire (si possible). C'est la mitzvah de Hashavat Aveidah (rendre les objets perdus). La Torah enseigne : si vous voyez l'animal ou les biens de votre prochain s'égarer, vous ne pouvez pas détourner le regard — vous devez tenter de les rendre. Nos Sages ont consacré de longues discussions à cette mitzvah : jusqu'où s'efforcer, quelle récompense garder, et pourquoi rendre un bien, c'est rendre la dignité.",
        "ru": "Недавно видели потерянную вещь? 🔍 Не проходите мимо! Вернитесь и постарайтесь отдать владельцу (если возможно). Это mitzvah hashavat aveidah — возврат потерянного. Тора учит: если вы видите, как блуждает скот или имущество ближнего, нельзя отворачиваться — нужно стараться вернуть. Мудрецы посвятили этой mitzvah целые обсуждения: как сильно стараться, что можно оставить себе за труд и почему возврат имущества — это возврат достоинства.",
    },
    "Pray for Moshiach!!!!!!! - submitted by EV. Belief in the coming of Mashiach is one of the thirteen foundations of Jewish faith — we anticipate a king from the house of David who will rebuild the Temple, gather the exiles, and fill the world with knowledge of G-d. Our sages teach that a Jew must live every day with the expectation of redemption. When you pray for Mashiach, you express hope for a world of peace, holiness, and the complete revelation of G-d's presence.": {
        "he": "התפללו למשיח!!!!!!! — הוגש על ידי EV. האמונה בביאת המשיח היא אחת משלוש עשרה יסודות האמונה — אנו מצפים למלך מבית דוד שיבנה את המקדש, יקבץ את הגולה וימלא את העולם בדעת ה'. חכמינו מלמדים שיהודי חייב לחיות בכל יום בציפייה לגאולה. כשמתפללים למשיח, מביעים תקווה לעולם של שלום, קדושה וגילוי מלא של נוכחות ה'.",
        "es": "¡Ora por el Mashíaj!!!!!!! — enviado por EV. Creer en la venida del Mashíaj es uno de los trece fundamentos de la fe judía — anticipamos un rey de la casa de David que reconstruirá el Templo, reunirá a los exiliados y llenará el mundo del conocimiento de D-s. Nuestros Sabios enseñan que un judío debe vivir cada día con expectativa de redención. Cuando oras por el Mashíaj, expresas esperanza en un mundo de paz, santidad y revelación plena de la presencia de D-s.",
        "fr": "Priez pour le Mashiah !!!!!!! — soumis par EV. Croire en la venue du Mashiah est l'un des treize fondements de la foi juive — nous attendons un roi de la maison de David qui reconstruira le Temple, rassemblera les exilés et remplira le monde de la connaissance de D. Nos Sages enseignent qu'un Juif doit vivre chaque jour dans l'attente de la rédemption. Prier pour le Mashiah, c'est exprimer l'espoir d'un monde de paix, de sainteté et de révélation complète de la présence de D.",
        "ru": "Молитесь о Mashiach!!!!!!! — от EV. Вера в приход Mashiach — один из тринадцати столпов еврейской веры: мы ждём царя из дома Давида, который восстановит Храм, соберёт изгнанников и наполнит мир познанием Hashem. Мудрецы учат: еврей должен жить каждый день в ожидании геулы. Молясь о Mashiach, вы выражаете надежду на мир, kedushah и полное раскрытие присутствия Hashem.",
    },
    "Take a minute to pray for someone else's needs before your own. Our sages teach a remarkable secret: when you pray for another person and you happen to need the same thing yourself, you are answered first. Putting someone else's needs before your own transforms prayer from a personal wish list into an act of love for the entire Jewish people.": {
        "he": "קחו דקה להתפלל על צרכי אחר לפני שלכם. חכמינו מלמדים סוד מופלא: כשמתפללים עבור אדם אחר וגם אתם זקוקים לאותו דבר — נענים קודם. להעמיד את צרכי האחר לפני שלכם הופך את התפילה מרשימת משאלות אישית למעשה אהבה לכל עם ישראל.",
        "es": "Tómate un minuto para orar por las necesidades de otro antes que las tuyas. Nuestros Sabios enseñan un secreto notable: cuando oras por otra persona y tú también necesitas lo mismo, te responden primero. Poner las necesidades de otro antes que las tuyas transforma la oración de una lista personal de deseos en un acto de amor por todo el pueblo judío.",
        "fr": "Prenez une minute pour prier pour les besoins d'autrui avant les vôtres. Nos Sages enseignent un secret remarquable : lorsque vous priez pour une autre personne et que vous avez vous-même besoin de la même chose, vous êtes exaucé en premier. Placer les besoins d'autrui avant les vôtres transforme la prière d'une liste de souhaits personnelle en acte d'amour pour tout le peuple juif.",
        "ru": "Найдите минуту, чтобы помолиться о нуждах другого раньше своих. Мудрецы открывают замечательный секрет: когда вы молитесь за другого и сами нуждаетесь в том же, вас услышат первым. Ставить нужды другого выше своих превращает молитву из личного списка желаний в акт любви ко всему народу Израиля.",
    },
    "Try to make peace between two people you know who are currently arguing. The reward for doing so is very great! Hillel taught us to be among the disciples of Aaron — a lover of peace and a pursuer of peace, who would greet every person warmly and draw them closer to Torah. Our sages teach that peace is so precious that G-d allows His own holy Name to be erased in order to restore peace between a husband and wife. Helping two people reconcile may be one of the greatest acts of kindness in the world.": {
        "he": "נסו לעשות שלום בין שני אנשים שאתם מכירים שמתווכחים כעת. השכר על כך גדול מאוד! Hillel לימד אותנו להיות מתלמידיו של אהרן — אוהב שלום ורודף שלום, שקיבל כל אדם בחום וקרב אותו לתורה. חכמינו מלמדים שהשלום כל כך יקר, שה' מאפשר למחוק את שמו הקדוש כדי לשקם שלום בין בעל ואישה. לעזור לשניים להתפייס יכול להיות מאחד מעשי החסד הגדולים בעולם.",
        "es": "Intenta hacer la paz entre dos personas que conoces y que están discutiendo. ¡La recompensa es muy grande! Hillel nos enseñó a ser de los discípulos de Aarón — amador de la paz y perseguidor de la paz, que saludaba a cada persona con calidez y la acercaba a la Torá. Nuestros Sabios enseñan que la paz es tan preciosa que D-s permite borrar Su Nombre santo para restaurar la paz entre esposo y esposa. Ayudar a dos personas a reconciliarse puede ser uno de los mayores actos de bondad del mundo.",
        "fr": "Essayez de faire la paix entre deux personnes que vous connaissez et qui se disputent. La récompense est très grande ! Hillel nous a enseigné à être parmi les disciples d'Aaron — amoureux de la paix et poursuivant la paix, qui accueillait chaque personne avec chaleur et la rapprochait de la Torah. Nos Sages enseignent que la paix est si précieuse que D. permet d'effacer Son Nom saint pour rétablir la paix entre mari et femme. Aider deux personnes à se réconcilier peut être l'un des plus grands actes de bonté au monde.",
        "ru": "Постарайтесь примирить двух знакомых, которые сейчас ссорятся. Награда за это велика! Hillel учил нас быть среди учеников Aharon — любящих мир и стремящихся к миру, тепло приветствовавших каждого и приближавших к Торе. Мудрецы учат: мир настолько дорог, что Hashem позволяет стереть Своё святое Имя, чтобы восстановить мир между мужем и женой. Помочь двум людям помириться — одно из величайших актов chesed в мире.",
    },
    "Call someone who is lonely. Submitted by: Amy. Our sages warn never to separate yourself from the community — because a Jew needs connection to thrive. Visiting the sick removes one-sixtieth of their suffering, and loneliness can be its own kind of illness. A phone call, a message, or a visit tells someone they matter — and loving your fellow Jew is one of the foundations of everything we stand for.": {
        "he": "התקשרו למישהו שמרגיש בודד. הוגש על ידי: Amy. חכמינו מזהירים לעולם לא להפריד את עצמכם מהציבור — כי יהודי זקוק לקשר כדי לפרוח. ביקור חולים מסיר אחד משישים מהסבל, ובדידות יכולה להיות מין של מחלה. שיחה, הודעה או ביקור אומרים לאדם שהוא חשוב — ואהבת ישראל היא אחת היסודות של כל מה שאנחנו עומדים עליו.",
        "es": "Llama a alguien que se siente solo. Enviado por: Amy. Nuestros Sabios advierten nunca separarse de la comunidad — porque un judío necesita conexión para prosperar. Visitar al enfermo quita una sexagésima del sufrimiento, y la soledad puede ser su propia enfermedad. Una llamada, un mensaje o una visita le dicen a alguien que importa — y amar a tu prójimo judío es uno de los fundamentos de todo lo que representamos.",
        "fr": "Appelez quelqu'un qui se sent seul. Soumis par : Amy. Nos Sages avertissent de ne jamais se séparer de la communauté — car un Juif a besoin de lien pour s'épanouir. Visiter le malade enlève un soixantième de la souffrance, et la solitude peut être une maladie à part entière. Un appel, un message ou une visite disent à quelqu'un qu'il compte — et aimer son prochain juif est l'un des fondements de tout ce que nous représentons.",
        "ru": "Позвоните одинокому человеку. От Amy. Мудрецы предупреждают: никогда не отделяйтесь от общины — еврею нужна связь, чтобы процветать. Посещение больного снимает одну шестидесятую страдания, а одиночество — своя болезнь. Звонок, сообщение или визит говорят человеку, что он важен — а любовь к ближнему-еврею один из фундаментов всего, за что мы стоим.",
    },
}


def main() -> None:
    bundles = {
        lang: json.loads((COMPOSE / f"{lang}.json").read_text(encoding="utf-8"))["entries"]
        for lang in LANGS
    }
    out: dict[str, dict[str, str]] = {lang: {} for lang in LANGS}
    for key in KEYS:
        for lang in LANGS:
            if key in NEW:
                out[lang][key] = NEW[key][lang]
            else:
                tr = bundles[lang].get(key, key)
                out[lang][key] = tr
    dest = ROOT / "data/translation-catalog/human/local_007.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {dest} ({len(KEYS)} keys)")


if __name__ == "__main__":
    main()
