# Auto-generated Hebrew glossary for batches 000-006
HE_GLOSSARY: dict[str, str] = {
    'Great!': 'מעולה!',
    'Hagbah': 'הגבהה',
    'Hallel': 'הלל',
    'Korech': 'כורך',
    'Koteiv': 'כותב',
    'Maariv': 'מעריב',
    'Mincha': 'מנחה',
    'Minhag': 'מנהג',
    'Mussar': 'מוסר',
    'Pesach': 'פסח',
    'Psalms': 'תהילים',
    'Rambam': 'הרמִב׳ם',
    'Retzei': 'רצה',
    'Seudah': 'סעודה',
    'Shamor': 'שמור',
    'Sukkah': 'סוכה',
    'Sukkot': 'סוכות',
    'Talmud': 'תלמוד',
    'Tanach': 'תנ״ך',
    'Tochen': 'טחן',
    'Yizkor': 'יזכור',
    'Zachor': 'זכור',
    'aliyah': 'עלייה',
    'aravah': 'ערבה',
    'chesed': 'חסד',
    'chiyuv': 'חיוב',
    'gabbai': 'גבאי',
    'gemach': 'גמ״ח',
    'kallah': 'כלה',
    'karpas': 'כרפס',
    'kippah': 'כיפה',
    'kosher': 'כשר',
    'matzah': 'מצה',
    'mikveh': 'מקווה',
    'minyan': 'מניין',
    'nefesh': 'נפש',
    'niddah': 'נדה',
    'nusach': 'נוסח',
    "ona'ah": 'אונאה',
    'pareve': 'פרווה',
    'parsha': 'פרשה',
    'schach': 'סיכך',
    'shinui': 'שינוי',
    'shofar': 'שופר',
    'siddur': 'סדור',
    'tekiah': 'תקיעה',
    'teruah': 'תרועה',
    'tzniut': 'צניעות',
    'yichud': 'יחוד',
    'zmanim': 'זמנים',
    'Chametz': 'חמץ',
    'Choresh': 'חורש',
    'Chumash': 'חומש',
    'Dayeinu': 'דיינו',
    'Hakafot': 'הקפות',
    'Hamapil': 'המפיל',
    'Hamotzi': 'המוציא',
    'Kaddish': 'קדיש',
    'Kashrut': 'כשרות',
    'Ketuvim': 'כתובים',
    'Kiddush': 'קידוש',
    'Melaben': 'מלבן',
    'Melacha': 'מלאכה',
    'Mezonot': 'מעזונות',
    'Mishnah': 'משנה',
    'Muktzeh': 'מוקצה',
    "Ne'ilah": 'נעילה',
    "Nevi'im": 'נביאים',
    'Parshah': 'פרשה',
    'Sefirah': 'ספירה',
    'Shabbos': 'שבת',
    'Shaddai': 'שדי',
    'Shavuot': 'שבועות',
    "Ta'anit": 'תענית',
    "Tu B'Av": 'ט״ו באָב',
    '\\s*/\\s*': '\\s*/\\s*',
    'aggadah': 'אגדה',
    'aveilut': 'אבלות',
    'beitzah': 'בשיית',
    'besamim': 'בשמים',
    'challah': 'חלה',
    'chatzos': 'חצות',
    'chazzan': 'חזן',
    'chinuch': 'חינוך',
    'cholent': 'חולנט',
    'chuppah': 'חופה',
    'halacha': 'הלכה',
    'kaparot': 'כפרות',
    'kehilla': 'קהילה',
    'ketubah': 'כתובה',
    'kezayit': 'כזית',
    'leining': 'לעינינג',
    'machzor': 'מחזור',
    'melicha': 'מליחה',
    'menorah': 'מנורה',
    'mesorah': 'מסורה',
    'mezuzah': 'מזוזה',
    'midrash': 'מדרש',
    'milchig': 'חלבי',
    'mitzvah': 'מצוה',
    'neshama': 'נשמה',
    "revi'it": 'רביעית',
    'shamash': 'שמש',
    'shochet': 'שוחט',
    'simanim': 'סימנים',
    'tevilah': 'טבילה',
    'tzitzit': 'ציצית',
    'Afikoman': 'אפיקומן',
    'Chanukah': 'חנוכה',
    'Chasidim': 'חסידים',
    'Davening': 'תפילה',
    'Diaspora': 'גלות',
    'Gan Eden': 'גן עדן',
    'Haggadah': 'הגדה',
    'Havdalah': 'הבדלה',
    'Hoshanot': 'הושענות',
    "Hotza'ah": 'הוצאה',
    'Kabbalah': 'קבלה',
    'Korbanot': 'קרבנות',
    'Mashiach': 'משיח',
    'Mechabeh': 'מכבה',
    'Megillah': 'מגילה',
    'Sefardim': 'ספרדים',
    'Selichot': 'סליחות',
    'Sephardi': 'ספרדי',
    'Shamayim': 'שמיים',
    'Tachanun': 'תחנון',
    'Tefillin': 'תפילין',
    'Tehillim': 'תהילים',
    'Ushpizin': 'אושפיזין',
    'Yaknehaz': 'יקנה״ז',
    'bedieved': 'בדיעבד',
    'bentcher': 'ברכון',
    'bitachon': 'בטחון',
    'charoset': 'חרוסת',
    'chazeret': 'חזרת',
    'fleishig': 'בשרי',
    'gematria': 'גימטריה',
    'halachot': 'הלכות',
    'hechsher': 'הכשר',
    'karmelit': 'כרמלית',
    'kavannah': 'כוונה',
    'kitniyot': 'קטניות',
    'mechitza': 'מחיצה',
    'melachot': 'מלאכות',
    'rechilut': 'רכילות',
    'shechita': 'שחיטה',
    'shevarim': 'שברים',
    'shloshim': 'שלושים',
    'tashlich': 'תשליך',
    'tefillah': 'תפילה',
    'teshuvah': 'תשובה',
    'tzedakah': 'צדקה',
    'yahrzeit': 'יארצנייט',
    'zemiroth': 'זמירות',
    '17 Tammuz': 'י\u05f7ב בתמוז',
    'Ashkenazi': 'אשכנזי',
    'Bentching': 'בירכת המזון',
    'Blessings': 'ברכות',
    'Chassidut': 'חסידות',
    'Hayom Yom': 'היום יום',
    'Kashering': 'הכשרה',
    'Maoz Tzur': 'מעוז צור',
    'Modeh Ani': 'מודה אני',
    'Nine Days': 'תשעת הימים',
    'Olam HaBa': 'עולם הבא',
    'Pesachdik': 'פסחדיק',
    'Purim day': 'יום פורים',
    'Shacharit': 'שחרית',
    'Shekhinah': 'שכינה',
    'Tashlumin': 'תשלומין',
    'Text Size': 'גודל טקסט',
    'gebrochts': 'געברוברקטס',
    'kneidlach': 'קניידלעך',
    'machloket': 'מחלוקת',
    'Arba Minim': 'ארבעה מינים',
    'Kol Nidrei': 'כל נידרעי',
    'Lag BaOmer': 'ל״ג בעומר',
    'Nusach Ari': 'נוסח האר״י',
    "Tisha B'Av": 'תִּשְׁעָה בְּאָב',
    "Tu B'Shvat": 'ט״ו בשָבָט',
    "Vatodi'enu": 'ותודיענו',
    'Yom Kippur': 'יום הכיפורים',
    'baal koreh': 'בעל קורא',
    'brit milah': 'ברית מילה',
    'egg matzah': 'מצה ביצים',
    "k'fi daato": 'כמו דעתו',
    'kisui rosh': 'כיסוי ראש',
    'misheyakir': 'משהיכיר',
    'Al HaNissim': 'על הניסים',
    'Chol HaMoed': 'חול המועד',
    'Days of Awe': 'ימי נורא',
    'Erev Pesach': 'ערב פסח',
    'Full Hallel': 'הלל מלא',
    'Half Hallel': 'חצי הלל',
    'Keep Kosher': 'שמירת כשרות',
    'Kol Chamira': 'כל חמירא',
    'Krias Shema': 'קריאת שמע',
    'Matan Torah': 'מתן תורה',
    'Pirkei Avot': 'פרקי אבות',
    'Purim Katan': 'פורים קטן',
    "Ruach Ra'ah": 'רוח רעה',
    'Sefer Torah': 'ספר תורה',
    'Three Weeks': 'שלושת השבועות',
    'Torah study': 'לימוד תורה',
    'Yom HaShoah': 'יום השואה',
    'al hamichya': 'על המיחיה',
    "bal yera'eh": 'בא לא יראה',
    'bar mitzvah': 'בר מצוה',
    'bat mitzvah': 'בת מצוה',
    "l'chatchila": 'לְכַתְּחִלָּה',
    'lashon hara': 'לשון הרע',
    'three stars': 'שלושת כוכבים',
    'yetzer hara': 'יצר הרע',
    'Hoshana Raba': 'הושענא רבה',
    'Melave Malka': 'מלווה מלכה',
    'Oneg Shabbat': 'עונג שבת',
    'Pesach Sheni': 'פסח שני',
    'Purim seudah': 'סעודת פורים',
    'Rosh Chodesh': 'ראש חודש',
    'Rosh Hashana': 'ראש השנה',
    'Shalom bayit': 'שלום בית',
    'Shehecheyanu': 'שהחינו',
    'Your Profile': 'הפרופיל שלכם',
    'bal yimatzei': 'בא לא ימצא',
    'biur chametz': 'ביעור חמץ',
    'dairy status': 'סטטוס חלבי',
    'festive meal': 'סעודת מצוה',
    'maleh lugmov': 'מלוא לוגמו',
    'ochel nefesh': 'אוכל נפש',
    'tallit gadol': 'טלית גדול',
    'tallit katan': 'טלית קטן',
    'tzedakah box': 'קופת צדקה',
    'yetzer hatov': 'יצר הטוב',
    '$mitzvotCount': '$mitzvotCount',
    'Add a Mitzvah': 'הוסף מצוה',
    "Asara B'Tevet": 'עש\u05c8וּ בְּטֵבֵת',
    'Baal Shem Tov': 'הב֣שם טוב',
    'Chilul Hashem': 'חילול ה׳',
    'Chofetz Chaim': 'חפץ חיים',
    'Eretz Yisrael': 'ארץ ישראל',
    'Eruv techumin': 'עירוב תחומין',
    'Mah Nishtanah': 'מה נשתנה',
    'Mitzvah Count': 'ספירת מצוות',
    'Plag HaMincha': 'פלג המנחה',
    'Shir HaMaalot': 'שיר המעלות',
    'Shmoneh Esrei': 'שמונה עסרה',
    'Shushan Purim': 'שושן פורים',
    'Simchat Torah': 'שמחת תורה',
    'Taanit Esther': 'תענית אסתר',
    "Yaaleh V'Yavo": 'יעלה ויבוא',
    "Yaaleh V'yavo": 'יעלה ויבוא',
    'Yom HaZikaron': 'יום הזיכרון',
    'chamar medina': 'חמר מדינה',
    'hakarat hatov': 'הכרת הטוב',
    'halachic hour': 'שעה הלכתית',
    'nusach Sefard': 'נוסח ספרד',
    'pirsumei nisa': 'פירסומי ניסא',
    'shomer negiah': 'שומר נגיעה',
    'Beit HaMikdash': 'בית המיקדש',
    'Birkat HaMazon': 'בירכת המזון',
    'Birkat Kohanim': 'בירכת כהנים',
    'Edot HaMizrach': 'עדות המזרח',
    'Elokei Neshama': 'אלוקי נשמה',
    'Eruv chatzerot': 'עירוב שבות',
    'Eruv tavshilin': 'עירוב תבשילין',
    'Fast of Esther': 'תענית אסתר',
    "Gam zu l'tovah": 'גם זו לתובה',
    'Hadlakat Nerot': 'הדלקת נרות',
    'Kiddush Hashem': 'קידוש ה׳',
    'Kiddush Levana': 'קידוש לבנה',
    "Makeh B'patish": 'מכה בפתיש',
    'Pikuach nefesh': 'פיקוח נפש',
    'Sefirat HaOmer': 'ספירת העומר',
    'Shabbat Shalom': 'שבת שלום',
    'Shemoneh Esrei': 'שמונה עסרה',
    'Shulchan Aruch': 'שולחן ערוך',
    'Targum Onkelos': 'תרגום אונקלוס',
    'Today is also:': 'היום גם:',
    "Yom Ha'atzmaut": 'יום העצמאות',
    'alot hashachar': 'עלות השחר',
    'borei nefashot': 'בורא נפשות',
    "chutz la'aretz": 'חו֥ לָאָאֶרֶץ',
    'e.g., Sarah B.': 'לדוגמה, Sarah B.',
    "geneivat da'at": 'גניבת דעת',
    'lechem mishneh': 'לחם משנה',
    'maaser kesafim': 'מעשר כספים',
    'mayim achronim': 'מים אחרונים',
    "ona'at devarim": 'אונאת דברים',
    'seudat mitzvah': 'סעודת מצוה',
    'shmurah matzah': 'מצה שמורה',
    'tevilat keilim': 'טבילת כלים',
    'yad soledet bo': 'יד סולדת בו',
    'yirat Shamayim': 'ייראת שמיים',
    'Borei Pri HaEtz': 'בורא פרי העץ',
    'HaNeiros halalu': 'הנרות הלאלו',
    'Jewish Holidays': 'חגי ישראל',
    'Mishloach Manot': 'משלוח מנות',
    'Mishnah Berurah': 'משנה ברורה',
    'Peninei Halakha': 'פניני הלכה',
    "Pesukei d'Zimra": 'פסוקי דזמרה',
    'Purim Meshulash': 'פורים משולש',
    'Shabbat candles': 'נרות שבת',
    'Shemini Atzeret': 'שמיני עצרת',
    'Simchat Yom Tov': 'שימחת יום טוב',
    'Taanit Bechorot': 'תענית בכורות',
    'Tefilat Nedavah': 'תפלת נדבה',
    'The 39 Melachot': 'ל\u05f9ט המלאכות',
    'assur bemelacha': 'אסור במלאכה',
    'bedikat chametz': 'בדיקת חמץ',
    'birchat hamapil': 'ברכת המאפיל',
    'bracha acharona': 'ברכה אחרונה',
    'candle lighting': 'הדלקת נרות',
    'neshama yeteira': 'נשמה יתירה',
    'netilat yadayim': 'נתילת ידים',
    'nusach Ashkenaz': 'נוסח אשכנז',
    'plowing melacha': 'מלאכת חרישה',
    'refuah shleimah': 'רפואה שלמה',
    'seudah shlishit': 'סעודה שלישית',
    'shaliach tzibur': 'שליחציבור',
    'Al netilat lulav': 'על נתילת לולב',
    'Fast of 10 Tevet': 'תענית י\u05f7ב בתבֵת',
    'Fast of Gedaliah': 'תענית גדליה',
    'Megillah reading': 'קריאת מגילה',
    'Modesty (Tznius)': 'צניעות',
    'Nachum Ish Gamzu': 'נחום איש גאמזו',
    'Shema al HaMitah': 'קריאת שמע על המטה',
    'What is Shabbat?': 'מהי שבת?',
    'Yom Yerushalayim': 'יום ירושלים',
    'building melacha': 'מלאכת בנייה',
    "chametz she'avar": 'חמץ שעבר',
    'gemilut chasadim': 'גמילות חסדים',
    'grinding melacha': 'מלאכת טחינה',
    'halachic chatzos': 'חצות הלכתית',
    'kneading melacha': 'מלאכת לישה',
    'leishev baSukkah': 'לשב בסוכה',
    'mechirat chametz': 'מכירת חמץ',
    'planting melacha': 'מלאכת זריעה',
    'shmirat halashon': 'שמירת הלשון',
    '(Nusach Ashkenaz)': '(נוסח אשכנז)',
    'Birchot HaShachar': 'ברכת השחר',
    'Borei Pri HaGafen': 'בורא פרי הגפן',
    'Fast of 17 Tammuz': 'תענית י\u05f7ב בתמוז',
    'Grace After Meals': 'בירכת המזון',
    'Pesach (Passover)': 'פסח (פסח)',
    'Psalms — Tehillim': 'תהילים הידו',
    'Shabbat & Yom Tov': 'שבת ויום טוב',
    'Shabbos — Shabbat': 'שבת השבת',
    'Submission Failed': 'השליחה נכשלה',
    "Traveler's Prayer": 'תפילת הדרך',
    "What's a Mitzvah?": 'מהי מצוה?',
    'cheshbon hanefesh': 'חשבון הנפש',
    'hafrashat challah': 'הפרשת חלה',
    'Al Netilat Yadayim': 'על נתילת ידים',
    'Borei Pri HaAdamah': 'בורא פרי האדמה',
    'Chol HaMoed Pesach': 'חול המועד פסח',
    'Chol HaMoed Sukkot': 'חול המועד סוכות',
    'Machatzit HaShekel': 'מחצית השקל',
    'What did you have?': 'מה אכלתם?',
    "bein kodesh l'chol": 'בין קודש לחול',
    "k'dei achilat pras": 'כדי אכילת פרס',
    'laundering melacha': 'מלאכת כביסה',
    "matanot la'evyonim": 'מתנות לאביונים',
    'the Land of Israel': 'ארץ ישראל',
    "walk in G-d's ways": 'התהלך בדרכי ה׳',
    '100 Daily Blessings': 'מאה ברכות יומיות',
    'Borei Minei Besamim': 'בורא מיני בשמים',
    'Havdalah in Kiddush': 'הבדלה בקידוש',
    'Mitzvah Description': 'תיאור מצוה',
    'Ritual hand washing': 'נתילת ידים',
    'broken shofar blast': 'תקיעת שופר שבורה',
    'demolishing melacha': 'מלאכת סתירה',
    'taharat hamishpacha': 'טהרת המשפחה',
    'All holidays & fasts': 'כל החגים והצומות',
    'Blessing After Meals': 'ברכה אחר אוכל',
    'Blessings after food': 'ברכות אחר אוכל',
    'Return to Mitz Mode?': 'לחזור למצב מצב?',
    "bein kodesh l'kodesh": 'בין קודש לקודש',
    'Aseret Yemei Teshuvah': 'עשרת ימי תשובה',
    'Blessings before food': 'ברכות לפני אוכל',
    'Kitzur Shulchan Arukh': 'קיצור שולחן ערוך',
    'Maariv Shemoneh Esrei': 'מעריב שמונה עסרה',
    'Seudah — festive meal': 'סעודה חגיגית',
    'Shomer Daltot Yisrael': 'שומר דלתות ישראל',
    "borei me'orei ha'eish": 'בורא מאורעי האור',
    'fast day before Purim': 'תענית לפני פורים',
    'honoring your parents': 'כיבוד אב ואם',
    'Browse all 39 melachot': 'עיון בל\u05f9ט המלאכות',
    'Choose city for zmanim': 'בחרו עיר לזמנים',
    "Kiddush b'Makom Seudah": 'קידוש במקום סעודה',
    'Location Access Needed': 'נדרשת גישה למיקום',
    'loving your fellow Jew': 'אהבת לזולתך',
    'milchig — dairy status': 'חלבי הסטטוס',
    'Daily Mitzvot Checklist': 'רשימת מצוות יומית',
    'Location & Prayer Times': 'מיקום וזמני תפילה',
    'Losh — kneading melacha': 'לישה מלאכת לישה',
    'Meat / Dairy Wait Times': 'זמנימני המתנה בשר וחלב',
    "Minimum Pesukei D'Zimra": 'מינימום פסוקי דזמרה',
    'Shabbat Candle Lighting': 'הדלקת נרות שבת',
    'Shemoneh Esrei/Tachanun': 'שמונה עסרה/תחנון',
    'acts of loving-kindness': 'גמילות חסדים',
    'Ashkenazi prayer wording': 'נוסח תפילה אשכנזי',
    'Boneh — building melacha': 'בניה מלאכת בנייה',
}
