# -*- coding: utf-8 -*-
def T(he, es, fr, ru):
    return (he, es, fr, ru)

ENTRIES = {
    "Birkat Kohanim — Priestly blessing; recited daily by everyone in Israel and by Sephardim worldwide; usually recited only on festivals by Ashkenazim in the Diaspora": T(
        "Birkat Kohanim — bracha kohanim; ne'emar yom yom le'chol ba'aretz u'leSefarad ba'olam; Ashkenazim ba'golah le'rov rak bechagim",
        "Birkat Kohanim — Bendicion sacerdotal; recitada diariamente por todos en Israel y por sefardies en todo el mundo; generalmente solo en fiestas por ashkenazim en la Diáspora",
        "Birkat Kohanim — Benediction sacerdotale ; recitee quotidiennement par tous en Israel et par les Sepharadim ; generalement seulement aux fetes par les Ashkenazim en Diaspora",
        "Birkat Kohanim — Svyashchennicheskoe blagoslovenie; ezhednevno v Izraile i u sefardov; ashkenazy v galute obychno tolko na prazdniki",
    ),
    "Say/text something nice to someone else or do a nice act for them. An act of kindness with no ulterior motives (except for scoring yet another mitzvah! Cha-Ching!)": T(
        "אמרו/שלחו משהו נחמד למישהו אחר או עשו מעשה טוב עבורם. מעשה חסד ללא מניעות זרות (חוץ מעוד mitzvah! Cha-Ching!)",
        "Di o envia algo agradable a otra persona o haz un acto amable por ella. Un acto de bondad sin motivos ocultos (excepto sumar otra mitzvá! Cha-Ching!)",
        "Dites ou envoyez quelque chose d'agreable a quelqu'un ou faites un acte gentil. Un acte de bonte sans arriere-pensee (sauf une mitzvah de plus ! Cha-Ching !)",
        "Skazhite ili otpravte chto-to priyatnoe drugomu ili sdelayte dobroe delo. Akt dobroty bez skrytykh motivev (krome esche odной mitzvah! Cha-Ching!)",
    ),
    "Sephardi — Half Hallel:\nDo not recite a blessing over Partial (Half) Hallel — say the psalms without a bracha (Shulchan Arukh O.C. 422:2; Peninei Halakha 05-01-12).": T(
        "Sephardi — Half Hallel:\nAl tomru bracha al Half Hallel — omru et hatehillim bli bracha (Shulchan Arukh O.C. 422:2; Peninei Halakha 05-01-12).",
        "Sefardi — Half Hallel:\nNo recites una bendicion sobre el Half Hallel — diga los salmos sin bracha (Shuljan Aruj O.C. 422:2; Peninei Halakha 05-01-12).",
        "Sepharadi — Half Hallel :\nNe recitez pas de benediction sur le Half Hallel — dites les psaumes sans bracha (Choulhan Aroukh O.C. 422:2 ; Peninei Halakha 05-01-12).",
        "Sephardi — Half Hallel:\nNe proiznosite brakhu nad Half Hallel — chitayte psalmy bez brakhi (Shulchan Arukh O.C. 422:2; Peninei Halakha 05-01-12).",
    ),
    "a group of Jews who follow a movement that emphasizes deep mystical devotion, joyful worship, and a close-knit community led by a spiritual leader known as a Rebbe.": T(
        "קבוצת יהודים העוקבים אחר תנועה המדגישה מסירות מיסטית עמוקה, עבודה שמחה, וקהילה קרובה בראשות מנהיג רוחני הידוע כ-Rebbe",
        "grupo de judios que siguen un movimiento que enfatiza devocion mistica profunda, culto alegre y comunidad unida liderada por un Rebbe",
        "groupe de Juifs suivant un mouvement qui met l'accent sur la devotion mystique, le culte joyeux et une communaute unie dirigee par un Rebbe",
        "gruppa evreev, sleduyushchikh dvizheniyu s glubokoy mistической predannostyu, radostnym bogosluzheniem i obshchinoy pod rukovodstvom Rebbe",
    ),
    "${yaalehVyavoFemaleAmidahLead(\"Maariv\")}\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nIf you say Birkat Hamazon when you eat bread tonight, add Yaaleh V'yavo there too.": T(
        "${yaalehVyavoFemaleAmidahLead(\"Maariv\")}\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nIf you say Birkat Hamazon when you eat bread tonight, add Yaaleh V'yavo there too.",
        "${yaalehVyavoFemaleAmidahLead(\"Maariv\")}\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nSi dices Birkat Hamazon cuando comas pan esta noche, anade Yaaleh V'yavo alli tambien.",
        "${yaalehVyavoFemaleAmidahLead(\"Maariv\")}\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nSi vous dites Birkat HaMazon ce soir apres du pain, ajoutez Yaaleh V'yavo la aussi.",
        "${yaalehVyavoFemaleAmidahLead(\"Maariv\")}\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nEsli vecherom govorite Birkat Hamazon posle khleba, dobavte Yaaleh V'yavo i tam.",
    ),
    "Today is $holidayName (Yom Tov — a festival day). Please put away your device and keep the day holy. Melacha (forbidden labor) applies on Yom Tov similar to Shabbat.": T(
        "היום $holidayName (Yom Tov — yom chag). אנא הניחu את המכשיר ושמרu על קדושת היום. Melacha (avoda asura) chala beYom Tov kmo beShabbat.",
        "Hoy es $holidayName (Yom Tov — dia festivo). Por favor guarda tu dispositivo y manten el dia santo. Melacha aplica en Yom Tov similar a Shabat.",
        "Aujourd'hui c'est $holidayName (Yom Tov — jour de fete). Veuillez ranger votre appareil et garder le jour saint. Melacha s'applique le Yom Tov comme Chabbat.",
        "Segodnya $holidayName (Yom Tov — prazdnichnyy den). Uберите устройство и соблюдайте святость дня. Melacha применяется в Yom Tov как в Shabbat.",
    ),
    "הרחמן הוא יזכנו לימות המשיח ולחיי העולם הבא. מגדיל ישועות מלכו, ועשה חסד למשיחו, לדוד ולזרעו עד עולם. עשה שלום במרומיו, הוא יעשה שלום עלינו ועל כל ישראל. ואמרו: אמן.": T(
        "הרחמן הוא יזכנו לימות המשיח ולחיי העולם הבא. מגדיל ישועות מלכו, ועשה חסד למשיחו, לדוד ולזרעו עד עולם. עשה שלום במרומיו, הוא יעשה שלום עלינו ועל כל ישראל. ואמרו: אמן.",
        "El Compasivo nos haga merecedores de los dias del Mashiaj y de la vida del mundo venidero. El engrandece las salvaciones de Su rey y hace bondad a Su ungido, a David y a su descendencia para siempre. Haga paz en Sus alturas, El haga paz sobre nosotros y sobre todo Israel. Y digan: Amen.",
        "Que le Miséricordieux nous fasse meriter les jours du Machia'h et la vie du monde a venir. Il magnifie les delivrances de Son roi et fait grace a Son oint, a David et a sa descendance a jamais. Faites la paix dans Ses hauteurs, qu'Il fasse la paix sur nous et sur tout Israel. Et dites : Amen.",
        "Da udostoit nas Milostivyy dney Mashiakha i zhizni v gрядushchem mire. On velichit spaseniya Tsarya Svoyego i tvorit milost Pomazanniku, Davidu i potomstvu ego vo veki. Tvori mir na vysotakh Svoyikh, da tvorit mir nad nami i nad vsem Izrailem. I skazhite: Amen.",
    ),
    "mechitza — A mechitza divides men and women's seating in shul during prayer so focus stays on tefillah per traditional practice. Heights and designs vary by community.": T(
        "mechitza — מחיצה מפרידה בין מקומות ישיבה לגברים ונשים בבית כנסת בתפילה כדי שהמיקוד יישאר בתפילה לפי מנהג מסורתי. גובה ועיצוב משתנים לפי קהילה.",
        "mechitza — Una mechitza divide los asientos de hombres y mujeres en la shul durante la oración para mantener el enfoque en la tefillah según la práctica tradicional. Las alturas y diseños varían según la comunidad.",
        "mechitza — Une mechitza sépare les places des hommes et des femmes à la shul pendant la prière afin que l'attention reste sur la tefillah selon la pratique traditionnelle. Hauteurs et designs varient selon la communauté.",
        "mechitza — Mechitza razdelyaet mesta muzhchin i zhenshchin v shul vo vremya molitvy, chtoby fokus ostalsya na tefillah po traditsionnoy praktike. Vysota i dizayn razlichayutsya po obshchinam.",
    ),
    "${yaalehVyavoFemaleAmidahLead(\"Mincha\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Mincha\")}\n\nIf you say Birkat Hamazon when you eat bread today, add Yaaleh V'yavo there too.": T(
        "${yaalehVyavoFemaleAmidahLead(\"Mincha\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Mincha\")}\n\nIf you say Birkat Hamazon when you eat bread today, add Yaaleh V'yavo there too.",
        "${yaalehVyavoFemaleAmidahLead(\"Mincha\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Mincha\")}\n\nSi dices Birkat Hamazon cuando comas pan hoy, añade Yaaleh V'yavo allí también.",
        "${yaalehVyavoFemaleAmidahLead(\"Mincha\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Mincha\")}\n\nSi vous dites Birkat HaMazon aujourd'hui après du pain, ajoutez Yaaleh V'yavo là aussi.",
        "${yaalehVyavoFemaleAmidahLead(\"Mincha\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Mincha\")}\n\nEsli segodnya govorite Birkat Hamazon posle khleba, dobavte Yaaleh V'yavo i tam.",
    ),
    "Shehecheyanu (Ashkenaz — Rema O.C. 692:1): Recite before the first evening Megillah reading. Ashkenazim also recite Shehecheyanu before the first daytime Megillah reading.": T(
        "Shehecheyanu (Ashkenaz — Rema O.C. 692:1): Omru lifnei kriat Megillah harishona ba'erev. Ashkenazim omrim Shehecheyanu gam lifnei kriat Megillah hayom harishona.",
        "Shehecheyanu (Ashkenaz — Rema O.C. 692:1): Recitar antes de la primera lectura nocturna de la Meguilá. Los ashkenazim también recitan Shehecheyanu antes de la primera lectura diurna de la Meguilá.",
        "Shehecheyanu (Ashkenaz — Rema O.C. 692:1) : Réciter avant la première lecture du soir de la Meguila. Les Ashkenazim récitent aussi Shehecheyanu avant la première lecture de jour de la Meguila.",
        "Shehecheyanu (Ashkenaz — Rema O.C. 692:1): Proiznosite pered pervym vechernim chteniem Megillah. Ashkenazy takzhe proiznosyat Shehecheyanu pered pervym dnevnym chteniem Megillah.",
    ),
    "Tomorrow is erev Purim — and this year is Purim Meshulash in Jerusalem. Shabbat is in the middle, so you need the full plan now (not only tomorrow).\n\n${fullScheduleBlock()}": T(
        "Machar erev Purim — u'b'shanah zo Purim Meshulash biYerushalayim. Shabbat ba'emtza, lachein tzarich et ha'tochnit ha'mele'a achshav (lo rak machar).\n\n${fullScheduleBlock()}",
        "Mañana es erev Purim — y este año es Purim Meshulash en Jerusalén. Shabat está en medio, así que necesitas el plan completo ahora (no solo mañana).\n\n${fullScheduleBlock()}",
        "Demain c'est erev Pourim — et cette année c'est Pourim Mechoulash à Jérusalem. Chabbat est au milieu, il vous faut donc le plan complet maintenant (pas seulement demain).\n\n${fullScheduleBlock()}",
        "Zavtra erev Purim — i v etom godu Purim Meshulash v Ierusalime. Shabbat poseredine, poetomu nuzhen polnyy plan seychas (ne tolko zavtra).\n\n${fullScheduleBlock()}",
    ),
    "minor fast on 10 Tevet from dawn until nightfall; the only fast never postponed when it falls on Friday before Shabbat — in which case we break it with Friday night Kiddush": T(
        "tzom katan be-y' Asara B'Tevet me'alot ha'shemesh ad tzeit ha'kochavim; ha'tzom ha'yechidi she'lo nidchah k'she'hu nofel be'yom shishi lifnei Shabbat — u'va'mikre kach shovrim oto beKiddush leil Shabbat",
        "ayuno menor el 10 de Tevet desde el amanecer hasta la noche; el único ayuno que nunca se pospone cuando cae en viernes antes de Shabat — en cuyo caso lo rompemos con el Kiddush del viernes por la noche",
        "jeûne mineur le 10 Tévet de l'aube à la nuit ; le seul jeûne jamais reporté quand il tombe un vendredi avant Chabbat — auquel cas on le rompt avec le Kiddush du vendredi soir",
        "malyy post 10 Tevet s rassveta do nochi; edinstvennyy post, kotoryy nikogda ne perenositsya, esli padaet v pyatnitsu pered Shabbat — v etom sluchae preryvaem ego pyatnichnym vechernim Kiddush",
    ),
    "Saw a lost object recently? 🔍 Don't just ignore it! Go back and try to return it to its owner (if possible). That's the mitzvah of Hashavat Aveidah (returning lost objects).": T(
        "ראיתם לאחרונה חפץ אבוד? 🔍 אל תתעלמו! חזרו ונסו להחזירו לבעליו (אם אפשר). זו המצווה של השבת אבידה.",
        "¿Viste un objeto perdido recientemente? 🔍 ¡No lo ignores! Regresa e intenta devolverlo a su dueño (si es posible). Esa es la mitzvá de Hashavat Aveidah (devolver objetos perdidos).",
        "Vous avez vu un objet perdu récemment ? 🔍 Ne l'ignorez pas ! Retournez essayer de le rendre à son propriétaire (si possible). C'est la mitzvah de Hashavat Aveidah (restitution des objets perdus).",
        "Nedavno videli poteryannuyu veshch? 🔍 Ne ignoriruyte! Vernites i poprobuyte vernut ee vladeltsu (esli vozmozhno). Eto mitzvah Hashavat Aveidah (vozvrashchenie poteryannogo).",
    ),
    "Before chag — every erev Yom Tov:\n$sunsetLine\n$cookingLine\n• Turn off phones and devices before Yom Tov — this app is for prep, not use on chag.\n$shulServicesLine$simchasBlock": T(
        "Lifnei chag — kol erev Yom Tov:\n$sunsetLine\n$cookingLine\n• Kabe'u telefonim u'machshevim lifnei Yom Tov — ha'app hazeh le'hachana, lo le'shimmush bechag.\n$shulServicesLine$simchasBlock",
        "Antes del chag — cada erev Yom Tov:\n$sunsetLine\n$cookingLine\n• Apaga teléfonos y dispositivos antes de Yom Tov — esta app es para preparación, no para usar en chag.\n$shulServicesLine$simchasBlock",
        "Avant le chag — chaque erev Yom Tov :\n$sunsetLine\n$cookingLine\n• Éteignez téléphones et appareils avant Yom Tov — cette app sert à la préparation, pas à l'usage le jour de fête.\n$shulServicesLine$simchasBlock",
        "Pered chag — kazhdyy erev Yom Tov:\n$sunsetLine\n$cookingLine\n• Vyklyuchite telefony i ustroystva pered Yom Tov — eto prilozhenie dlya podgotovki, ne dlya ispolzovaniya v chag.\n$shulServicesLine$simchasBlock",
    ),
    "Chasidim — a group of Jews who follow a movement that emphasizes deep mystical devotion, joyful worship, and a close-knit community led by a spiritual leader known as a Rebbe.": T(
        "Chasidim — k'vutzat Yehudim ha'okvim acharei tnu'ah ha'medgasheset mesirut mistit amuka, avodah smeicha, ve'kehillah krova bi'rashtut manhig ruchani ha'yadu'a keRebbe.",
        "Jasidim — grupo de judíos que siguen un movimiento que enfatiza devoción mística profunda, culto alegre y comunidad unida liderada por un Rebbe.",
        "Hassidim — groupe de Juifs suivant un mouvement qui met l'accent sur la dévotion mystique profonde, le culte joyeux et une communauté soudée dirigée par un Rebbe.",
        "Hasidim — gruppa evreev, sleduyushchikh dvizheniyu s glubokoy mistической predannostyu, radostnym bogosluzheniem i tesnoy obshchinoy pod rukovodstvom Rebbe.",
    ),
    "${yaalehVyavoFemaleAmidahLead(\"Shacharit\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nIf you say Birkat Hamazon when you eat bread today, add Yaaleh V'yavo there too.": T(
        "${yaalehVyavoFemaleAmidahLead(\"Shacharit\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nIf you say Birkat Hamazon when you eat bread today, add Yaaleh V'yavo there too.",
        "${yaalehVyavoFemaleAmidahLead(\"Shacharit\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nSi dices Birkat Hamazon cuando comas pan hoy, añade Yaaleh V'yavo allí también.",
        "${yaalehVyavoFemaleAmidahLead(\"Shacharit\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nSi vous dites Birkat HaMazon aujourd'hui après du pain, ajoutez Yaaleh V'yavo là aussi.",
        "${yaalehVyavoFemaleAmidahLead(\"Shacharit\")}\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nEsli segodnya govorite Birkat Hamazon posle khleba, dobavte Yaaleh V'yavo i tam.",
    ),
    "Beit HaMikdash — The Beit HaMikdash (Holy Temple) stood in Jerusalem as the center of sacrifice, pilgrimage, and divine presence. Its destruction on Tisha B'Av is mourned yearly.": T(
        "Beit HaMikdash — Beit HaMikdash (Mikdash HaKodesh) amad biYerushalayim k'merkaz korban, aliyah l'regel ve'shechinah. Churbano beTisha B'Av ne'evl shanah b'shanah.",
        "Beit HaMikdash — El Beit HaMikdash (Templo Sagrado) estuvo en Jerusalén como centro de sacrificio, peregrinación y presencia divina. Su destrucción en Tisha B'Av se llora anualmente.",
        "Beit HaMikdash — Le Beit HaMikdash (Temple Saint) se dressait à Jérusalem comme centre de sacrifice, pèlerinage et présence divine. Sa destruction à Ticha BeAv est pleurée chaque année.",
        "Beit HaMikdash — Beit HaMikdash (Svyatoy Khram) stoyal v Ierusalime kak tsentr zhertvoprinosheniy, palomnichestva i bozhestvennogo prisutstviya. Ego razrushenie v Tisha B'Av opлакивается ежегодно.",
    ),
    "Bracha acharona is the after-blessing said when you ate or drank enough of a food but did not have a bread meal requiring Birkat Hamazon — for example borei nefashot or al hamichya.": T(
        "Bracha acharona hi ha'bracha achar kvi'at ma'achal o mashke shelo hayta seudat lechem ha'tzricha Birkat Hamazon — lemashal borei nefashot o al hamichya.",
        "Bracha acharona es la bendición posterior cuando comiste o bebiste suficiente de un alimento pero no tuviste una comida con pan que requiera Birkat Hamazon — por ejemplo borei nefashot o al hamichya.",
        "Bracha acharona est la bénédiction après avoir mangé ou bu assez d'un aliment sans repas de pain nécessitant Birkat HaMazon — par exemple borei nefashot ou al hamichya.",
        "Bracha acharona — poslebrachie posle edy ili napitka bez khlebной трапезы, trebuyushchey Birkat Hamazon — naprimer borei nefashot ili al hamichya.",
    ),
    "YaKNeHaZ is a mnemonic for the order when Shabbat flows directly into Yom Tov (for example Saturday night Pesach). Use your siddur's festival night Kiddush section for instructions.": T(
        "YaKNeHaZ hu zikaron l'seder k'sheShabbat over yashir leYom Tov (lemashal motzaei Shabbat Pesach). Hashav siddur le'hanhagot Kiddush leil chag.",
        "YaKNeHaZ es un mnemónico para el orden cuando Shabat pasa directamente a Yom Tov (por ejemplo, noche de Pesaj). Usa la sección de Kiddush festivo nocturno de tu sidur.",
        "YaKNeHaZ est un moyen mnémotechnique pour l'ordre quand Chabbat enchaîne directement sur Yom Tov (par ex. samedi soir de Pessah). Consultez la section Kiddush de fête du soir de votre siddour.",
        "YaKNeHaZ — mnemonika poryadka, kogda Shabbat perekhodit neposredstvenno v Yom Tov (naprimer, subbotu vecherom Pesach). Ispolzuyte razdel prazdnichnogo vechernего Kiddush v siddure.",
    ),
    "Mezonot (borei minei mezonot) is the blessing on grain foods that are not bread — cake, crackers, pasta, cereal. It is shorter than hamotzi but still thanks G-d for grain sustenance.": T(
        "Mezonot (borei minei mezonot) hi ha'bracha al ma'achalei dagan she'einam lechem — ugah, krakers, pasta, dagan. Ktzurah mehamotzi aval modah la'Hashem al mazon dagan.",
        "Mezonot (borei minei mezonot) es la bendición sobre alimentos de grano que no son pan — pastel, galletas, pasta, cereal. Es más corta que hamotzi pero agradece a D-s por el sustento de grano.",
        "Mezonot (borei minei mezonot) est la bénédiction sur les aliments de céréales qui ne sont pas du pain — gâteau, crackers, pâtes, céréales. Plus courte que hamotzi mais remercie D. pour la subsistance de céréales.",
        "Mezonot (borei minei mezonot) — brakha na zernovye produkty, ne yavlyayushchiesya khlebom — keks, krekery, makaron, khlopya. Koroche hamotzi, no blagodarit V-ga za zernovoe propitanie.",
    ),
    "Next time you have guests, keep in mind to escort them on their way as they leave, even for just a few steps. The Talmud (Sotah 46b) says the reward for escorting others has no measure!": T(
        "Ba'pa'am haba'a she'yeish lachem orchim, zekhru le'lave otam baderech k'shehem yotz'im, afilu kama tzadadim. HaTalmud (Sotah 46b) omrim she'sachar ha'levaya ein lo shiur!",
        "La próxima vez que tengas invitados, recuerda escoltarlos al salir, aunque sean solo unos pasos. El Talmud (Sotah 46b) dice que la recompensa por acompañar a otros no tiene medida.",
        "La prochaine fois que vous avez des invités, pensez à les accompagner en partant, même quelques pas. Le Talmud (Sotah 46b) dit que la récompense de l'accompagnement n'a pas de mesure !",
        "V sleduyushchiy raz, kogda u vas gosti, provozhayte ikh pri ukhode, khotya by neskolko shagov. Talmud (Sotah 46b) govorit, chto nagrada za provody ne imeet predela!",
    ),
    "Ruach Ra'ah (\"evil spirit\") is a rabbinic term for the impurity resting on hands after sleep. Morning netilat yadayim removes it by washing hands alternating right and left 3 times each.": T(
        "Ruach Ra'ah (\"ruach ra'ah\") hu term rabbani le'tumah ha'nuchach al ha'yadayim achar sheinah. Netilat yadayim baboker me'akher oto bi'khlitat yadayim yemin u'smol shalosh pe'amim kol achat.",
        "Ruach Ra'ah (\"espíritu malo\") es un término rabínico para la impureza en las manos tras dormir. El netilat yadayim matutino lo elimina lavando manos alternando derecha e izquierda 3 veces cada una.",
        "Ruach Ra'ah (« esprit mauvais ») est un terme rabbinique pour l'impureté sur les mains après le sommeil. Le netilat yadayim du matin l'enlève en lavant les mains droite et gauche 3 fois chacune.",
        "Ruach Ra'ah («zloy dukh») — rabbinicheskiy termin dlya tumah na rukakh posle sna. Utrennyaya netilat yadayim ustraняet ego, promyvaya ruki po ocheredi pravyyu i levuyu po 3 raza.",
    ),
    "Asara B'Tevet — minor fast on 10 Tevet from dawn until nightfall; the only fast never postponed when it falls on Friday before Shabbat — in which case we break it with Friday night Kiddush": T(
        "Asara B'Tevet — tzom katan be-y' Tevet me'alot ha'shemesh ad tzeit ha'kochavim; ha'tzom ha'yechidi she'lo nidchah k'she'hu nofel be'yom shishi lifnei Shabbat — u'va'mikre kach shovrim oto beKiddush leil Shabbat",
        "Asara B'Tevet — ayuno menor el 10 de Tevet desde el amanecer hasta la noche; el único ayuno que nunca se pospone cuando cae en viernes antes de Shabat — en cuyo caso lo rompemos con el Kiddush del viernes por la noche",
        "Asara B'Tevet — jeûne mineur le 10 Tévet de l'aube à la nuit ; le seul jeûne jamais reporté quand il tombe un vendredi avant Chabbat — auquel cas on le rompt avec le Kiddush du vendredi soir",
        "Asara B'Tevet — malyy post 10 Tevet s rassveta do nochi; edinstvennyy post, kotoryy nikogda ne perenositsya, esli padaet v pyatnitsu pered Shabbat — v etom sluchae preryvaem ego pyatnichnym vechernim Kiddush",
    ),
    "Kallah means bride; kallah classes teach taharat hamishpacha, mitzvot of the home, and wedding laws before marriage. The kallah and chatan prepare for chuppah and building a Jewish family.": T(
        "Kallah mashma kalah; shiurei kallah melamedim taharat hamishpacha, mitzvot shel habayit ve'chukei nisuin lifnei ha'nisuin. Ha'kallah ve'ha'chatan mitkadshim le'chuppah u'le'binyan mishpacha Yehudit.",
        "Kallah significa novia; las clases de kallah enseñan taharat hamishpacha, mitzvot del hogar y leyes de boda antes del matrimonio. La kallah y el chatan se preparan para la jupá y construir una familia judía.",
        "Kallah signifie mariée ; les cours de kallah enseignent taharat hamishpacha, mitzvot du foyer et lois de mariage avant les noces. La kallah et le hatan se préparent pour la houppa et bâtir une famille juive.",
        "Kallah oznachaet nevestu; zanyatiya kallah uchат taharat hamishpacha, mitzvot doma i svadebnym zakonam do braka. Kallah i chatan gotovyatsya k chuppah i sozdaniyu evreyskoy semyi.",
    ),
    "Vatodi'enu (\"You have made us know\") is an insert in the Maariv Amidah on Saturday night when Yom Tov begins after Shabbat. It acknowledges that Shabbat has ended and the festival has begun.": T(
        "Vatodi'enu (\"hoda'atanu\") hu haser baAmidah shel Maariv be'motzaei Shabbat k'sheYom Tov mat'hil achar Shabbat. Hu me'ir sheShabbat nigmer veha'chag hit'hil.",
        "Vatodi'enu (\"Nos has hecho saber\") es una inserción en la Amidá de Maariv el sábado por la noche cuando Yom Tov comienza tras Shabat. Reconoce que Shabat terminó y la festividad comenzó.",
        "Vatodi'enu (« Tu nous as fait savoir ») est une insertion dans l'Amidah de Maariv le samedi soir quand Yom Tov commence après Chabbat. Elle reconnaît que Chabbat est fini et la fête a commencé.",
        "Vatodi'enu («Ty sdelal nas znaющimi») — vstavka v Amidah Maariv v subbotu vecherom, kogda Yom Tov nachinaetsya posle Shabbat. Priznaet okonchanie Shabbat i nachalo prazdnika.",
    ),
    "Mezonot — Mezonot (borei minei mezonot) is the blessing on grain foods that are not bread — cake, crackers, pasta, cereal. It is shorter than hamotzi but still thanks G-d for grain sustenance.": T(
        "Mezonot — Mezonot (borei minei mezonot) hi ha'bracha al ma'achalei dagan she'einam lechem — ugah, krakers, pasta, dagan. Ktzurah mehamotzi aval modah la'Hashem al mazon dagan.",
        "Mezonot — Mezonot (borei minei mezonot) es la bendición sobre alimentos de grano que no son pan — pastel, galletas, pasta, cereal. Es más corta que hamotzi pero agradece a D-s por el sustento de grano.",
        "Mezonot — Mezonot (borei minei mezonot) est la bénédiction sur les aliments de céréales qui ne sont pas du pain — gâteau, crackers, pâtes, céréales. Plus courte que hamotzi mais remercie D. pour la subsistance de céréales.",
        "Mezonot — Mezonot (borei minei mezonot) — brakha na zernovye produkty, ne yavlyayushchiesya khlebom — keks, krekery, makaron, khlopya. Koroche hamotzi, no blagodarit V-ga za zernovoe propitanie.",
    ),
    "Yaknehaz — YaKNeHaZ is a mnemonic for the order when Shabbat flows directly into Yom Tov (for example Saturday night Pesach). Use your siddur's festival night Kiddush section for instructions.": T(
        "Yaknehaz — YaKNeHaZ hu zikaron l'seder k'sheShabbat over yashir leYom Tov (lemashal motzaei Shabbat Pesach). Hashav siddur le'hanhagot Kiddush leil chag.",
        "Yaknehaz — YaKNeHaZ es un mnemónico para el orden cuando Shabat pasa directamente a Yom Tov (por ejemplo, noche de Pesaj). Usa la sección de Kiddush festivo nocturno de tu sidur.",
        "Yaknehaz — YaKNeHaZ est un moyen mnémotechnique pour l'ordre quand Chabbat enchaîne directement sur Yom Tov (par ex. samedi soir de Pessah). Consultez la section Kiddush de fête du soir de votre siddour.",
        "Yaknehaz — YaKNeHaZ — mnemonika poryadka, kogda Shabbat perekhodit neposredstvenno v Yom Tov (naprimer, subbotu vecherom Pesach). Ispolzuyte razdel prazdnichnogo vechernего Kiddush v siddure.",
    ),
    "Add Yaaleh V'yavo in the Maariv Amidah on Rosh Chodesh — in the blessing Retzei (Avodah).\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nAlso add Yaaleh V'yavo in bentching if you eat bread tonight.": T(
        "Hosifu Yaaleh V'yavo baAmidah shel Maariv beRosh Chodesh — bi'bracha Retzei (Avodah).\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nHosifu Yaaleh V'yavo gam bebentching im tochlu lechem ha'layla.",
        "Añade Yaaleh V'yavo en la Amidá de Maariv en Rosh Jodesh — en la bendición Retzei (Avodah).\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nTambién añade Yaaleh V'yavo en bentching si comes pan esta noche.",
        "Ajoutez Yaaleh V'yavo dans l'Amidah de Maariv à Roch 'Hodesh — dans la bénédiction Retzei (Avodah).\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nAjoutez aussi Yaaleh V'yavo au bentching si vous mangez du pain ce soir.",
        "Dobavte Yaaleh V'yavo v Amidah Maariv v Rosh Chodesh — v brakhe Retzei (Avodah).\n\n${yaalehVyavoForgotMaarivRoshChodesh()}\n\nTakzhe dobavte Yaaleh V'yavo v bentching, esli vecherom est khleb.",
    ),
    "Purim is tomorrow. Plan all four mitzvot: Megillah (night and morning), matanot la'evyonim, mishloach manot, and tomorrow's festive seudah (afternoon meal). Confirm reading times with your shul.": T(
        "Purim machar. Tichnu et arba hamitzvot: Megillah (layla u'boker), matanot la'evyonim, mishloach manot, ve'seudat Purim machar (seudah ba'tzohorayim). Achru zmanei kriah im ha'shul.",
        "Purim es mañana. Planifica las cuatro mitzvot: Meguilá (noche y mañana), matanot la'evyonim, mishloach manot y la seudá festiva de mañana (comida vespertina). Confirma horarios de lectura con tu shul.",
        "Pourim est demain. Planifiez les quatre mitzvot : Meguila (soir et matin), matanot la'evyonim, mishloach manot et la seudah festive de demain (repas de l'après-midi). Confirmez les horaires de lecture avec votre shul.",
        "Purim zavtra. Zaplaniruyte chetyre mitzvot: Megillah (noch i utro), matanot la'evyonim, mishloach manot i prazdnichnuyu seudah zavtra (obed posle poludnya). Utochnite vremya chteniya v shul.",
    ),
    "Take a minute to pray for someone else's needs before your own. The sages teach that when you pray for others with pure intentions, and you happen to need the same thing, you get answered first!": T(
        "Kachu dakah le'hitpalel al tzorkhei acherim lifnei shelkha. Ha'chachamim melamedim she'k'she'mitpalelim la'acheirim be'kavanah tehorah, ve'gam atah tzarich et oto davar — anuim rishonim!",
        "Tómate un minuto para orar por las necesidades de otros antes que las tuyas. Los sabios enseñan que cuando oras por otros con intenciones puras y tú necesitas lo mismo, ¡te responden primero!",
        "Prenez une minute pour prier pour les besoins d'autrui avant les vôtres. Les sages enseignent que quand vous priez pour les autres avec de bonnes intentions et que vous avez le même besoin, vous êtes exaucé en premier !",
        "Udelyte minutu molitve o nuzhdakh drugikh prezhde svoikh. Mudretsy uchат: kogda molites za drugikh s chistymi namereniyami i vam nuzhno to zhe — vam otvechayut pervym!",
    ),
    "Aggadah is the non-legal storytelling and teaching in the Talmud and midrash — ethics, theology, and narrative. It complements halacha (law). Shabbat table stories and many midrashim are aggadah.": T(
        "Aggadah hi ha'sippur ve'ha'limud she'einam halacha baTalmud u'vamidrash — musar, emunah ve'sippur. Hi meshalemet et ha'halacha. Sippurei shulchan Shabbat ve'rabim midrashim hem aggadah.",
        "Aggadah es la narrativa y enseñanza no legal en el Talmud y midrash — ética, teología y relatos. Complementa la halajá (ley). Las historias de mesa de Shabat y muchos midrashim son aggadah.",
        "Aggadah est le récit et l'enseignement non juridique du Talmud et du midrash — éthique, théologie et narration. Elle complète la halakha (loi). Les histoires de table de Chabbat et beaucoup de midrashim sont aggadah.",
        "Aggadah — nelegalnye rasskazy i ucheniya v Talmude i midrashe — etika, bogoslovie i narrativ. Dopolnayet halakhu (zakon). Shabbat-stol rasskazy i mnogie midrashim — eto aggadah.",
    ),
    "Please put away your device and keep Shabbat. Rest, pray, learn Torah, and enjoy time with family and community. Melacha (forbidden labor) applies on Shabbat, including most phone and device use.": T(
        "אנא הניחu את המכשיר ושמרu על Shabbat. נוחu, התפללu, למdu Torah, והנu מזמן עם משפחה וקהילה. Melacha (avoda asura) chala beShabbat, כולל רוב השימוש בטלפון ובמכשירים.",
        "Por favor guarda tu dispositivo y guarda Shabat. Descansa, ora, aprende Torá y disfruta con familia y comunidad. Melacha (trabajo prohibido) aplica en Shabat, incluyendo la mayoría del uso de teléfono y dispositivos.",
        "Veuillez ranger votre appareil et garder Chabbat. Reposez-vous, priez, étudiez la Torah et profitez de la famille et de la communauté. Melacha (travail interdit) s'applique le Chabbat, y compris la plupart de l'usage du téléphone et des appareils.",
        "Uберите ustroystvo i soblyudayte Shabbat. Otdykhnite, molites, uchites Toru i provodite vremya s semyey i obshchinoy. Melacha (zapreshchennyy trud) primenyaetsya v Shabbat, vklyuchaya bolshinstvo ispolzovaniya telefona i ustroystv.",
    ),
    "Nevi'im (Prophets) is the middle section of Tanach — Joshua, Kings, Isaiah, Jeremiah, and the other prophetic books. They call Israel to justice and loyalty to Hashem. Reading them is Torah study.": T(
        "Nevi'im (Nevi'im) hu helek ha'emtza'i shel Tanach — Yehoshua, Melachim, Yeshayahu, Yirmiyahu ve'sefer nevi'im acherim. Hem kor'im leYisrael le'tzedek u'le'emunah ba'Hashem. Kriatam hi limud Torah.",
        "Nevi'im (Profetas) es la sección central del Tanaj — Josué, Reyes, Isaías, Jeremías y los demás libros proféticos. Llaman a Israel a la justicia y lealtad a Hashem. Leerlos es estudio de Torá.",
        "Nevi'im (Prophètes) est la section centrale du Tanakh — Josué, Rois, Isaïe, Jérémie et les autres livres prophétiques. Ils appellent Israël à la justice et à la fidélité à Hachem. Les lire est étude de Torah.",
        "Nevi'im (Proroki) — srednyaya chast Tanakh — Yehoshua, Melakhim, Yeshayahu, Yirmiyahu i drugie knigi prorokov. Prizyvayut Izrail k spravedlivosti i vernosti Hashemu. Chtenie ikh — izuchenie Tory.",
    ),
    "catch-all blessing on fragrant herbs, spices, flowers, fruit, etc. (often said as the spice blessing in Havdalah after Shabbat, though some will say a more specific blessing on pleasant fragrances)": T(
        "bracha klalit al samim, tavlinim, perachim, pri, ve'ch. (l'rov ne'emra ke'brachat ha'besamim baHavdalah achar Shabbat, af al pi she'yesh ha'omrim bracha meyuchedet yoter al rei'ach naim)",
        "bendición general sobre hierbas aromáticas, especias, flores, fruta, etc. (a menudo dicha como bendición de especias en Havdalah tras Shabat, aunque algunos dicen una bendición más específica sobre fragancias agradables)",
        "bénédiction générale sur herbes parfumées, épices, fleurs, fruits, etc. (souvent dite comme bénédiction des épices à Havdalah après Chabbat, bien que certains disent une bénédiction plus spécifique sur les parfums agréables)",
        "obshchaya brakha na aromatnye travy, specii, tsvety, plody i t.d. (chasto kak brakha na specii v Havdalah posle Shabbat, khotya nekotorye govoryat bolee konkretnuyu brakhu na priyatnye zapakhi)",
    ),
    "kallah — Kallah means bride; kallah classes teach taharat hamishpacha, mitzvot of the home, and wedding laws before marriage. The kallah and chatan prepare for chuppah and building a Jewish family.": T(
        "kallah — Kallah mashma kalah; shiurei kallah melamedim taharat hamishpacha, mitzvot shel habayit ve'chukei nisuin lifnei ha'nisuin. Ha'kallah ve'ha'chatan mitkadshim le'chuppah u'le'binyan mishpacha Yehudit.",
        "kallah — Kallah significa novia; las clases de kallah enseñan taharat hamishpacha, mitzvot del hogar y leyes de boda antes del matrimonio. La kallah y el chatan se preparan para la jupá y construir una familia judía.",
        "kallah — Kallah signifie mariée ; les cours de kallah enseignent taharat hamishpacha, mitzvot du foyer et lois de mariage avant les noces. La kallah et le hatan se préparent pour la houppa et bâtir une famille juive.",
        "kallah — Kallah oznachaet nevestu; zanyatiya kallah uchат taharat hamishpacha, mitzvot doma i svadebnym zakonam do braka. Kallah i chatan gotovyatsya k chuppah i sozdaniyu evreyskoy semyi.",
    ),
    "When (Northern Hemisphere — your location):\nSay it during Nissan, when fruit trees in your area begin to blossom — ideally as early in the month as you first see flowers (Shulchan Arukh O.C. 226:1).": T(
        "Matay (hemisphere tzafoni — hamakom shelkha):\nOmru bechodesh Nissan, k'she'etz pri ba'ezor shelkha mat'hil le'porach — ideally me'urav ba'chodesh k'she'atem ro'im perachim rishonim (Shulchan Arukh O.C. 226:1).",
        "Cuándo (hemisferio norte — tu ubicación):\nDilo durante Nissan, cuando los árboles frutales de tu zona empiecen a florecer — idealmente tan pronto en el mes como veas las primeras flores (Shuljan Aruj O.C. 226:1).",
        "Quand (hémisphère nord — votre lieu) :\nDites-le pendant Nissan, quand les arbres fruitiers de votre région commencent à fleurir — idéalement dès les premières fleurs du mois (Choulhan Aroukh O.C. 226:1).",
        "Kogda (severnoe polusharie — vash region):\nGovorite v Nissan, kogda plodovye derevya v vashem rayone nachinayut tsvet — idealno kak mozhno ranshe v mesyatse, kogda uvidite pervye tsvety (Shulchan Arukh O.C. 226:1).",
    ),
    "Nefesh is the 'animal' part of the soul closest to physical life — appetite, hunger, physical desires, etc. Torah and mitzvot attempt to refine the nefesh toward holiness instead of animal instincts.": T(
        "Nefesh hi helek ha'nefesh ha'karov le'chayim gashmiyim — ta'avah, ra'av, ta'avot gufaniyot ve'ch. Torah u'mitzvot me'ayenim le'zakh et ha'nefesh le'kedushah bimkom instinkt behemi.",
        "Nefesh es la parte 'animal' del alma más cercana a la vida física — apetito, hambre, deseos físicos, etc. Torá y mitzvot intentan refinar el nefesh hacia la santidad en lugar de instintos animales.",
        "Nefesh est la partie « animale » de l'âme la plus proche de la vie physique — appétit, faim, désirs physiques, etc. Torah et mitzvot cherchent à raffiner le nefesh vers la sainteté plutôt que les instincts animaux.",
        "Nefesh — «zhivotnaya» chast dushi, blizhayshaya k fizicheskoy zhizni — appetit, golod, fizicheskie zhelaniya i t.d. Tora i mitzvot stremyatsya ochistit nefesh k kedushah vmesto zhivotnykh instinktov.",
    ),
    "Spread the joy of mitzvot! Share the Mitz Mode app with your friends 📱. Every time they use it to do a mitzvah, you get credit for that mitzvah too! It's like creating an endless chain of good deeds!": T(
        "הפיצu את שמחת המצוות! שתפu את אפליקציית Mitz Mode עם חברים 📱. בכל פעם שהם משתמשים בה לעשות mitzvah, גם אתם מקבלים זcredit לmitzvah הזו! זה כמו ליצור שרשרת אינסופית של מעשים טובים!",
        "¡Difunde la alegría de las mitzvot! Comparte la app Mitz Mode con tus amigos 📱. Cada vez que la usen para hacer una mitzvá, ¡tú también recibes crédito por esa mitzvá! ¡Es como crear una cadena infinita de buenas acciones!",
        "Diffusez la joie des mitzvot ! Partagez l'app Mitz Mode avec vos amis 📱. Chaque fois qu'ils l'utilisent pour une mitzvah, vous recevez aussi le mérite de cette mitzvah ! C'est comme créer une chaîne infinie de bonnes actions !",
        "Rasprostranyayte radost mitzvot! Podelites prilozheniem Mitz Mode s druzyami 📱. Kazhdyy raz, kogda oni delayut mitzvah cherez nego, vy tozhe poluchаете zaslugu za etu mitzvah! Eto kak beskonechnaya tsep dobrodelaniy!",
    ),
    "bracha acharona — Bracha acharona is the after-blessing said when you ate or drank enough of a food but did not have a bread meal requiring Birkat Hamazon — for example borei nefashot or al hamichya.": T(
        "bracha acharona — Bracha acharona hi ha'bracha achar kvi'at ma'achal o mashke shelo hayta seudat lechem ha'tzricha Birkat Hamazon — lemashal borei nefashot o al hamichya.",
        "bracha acharona — Bracha acharona es la bendición posterior cuando comiste o bebiste suficiente de un alimento pero no tuviste una comida con pan que requiera Birkat Hamazon — por ejemplo borei nefashot o al hamichya.",
        "bracha acharona — Bracha acharona est la bénédiction après avoir mangé ou bu assez d'un aliment sans repas de pain nécessitant Birkat HaMazon — par exemple borei nefashot ou al hamichya.",
        "bracha acharona — Bracha acharona — poslebrachie posle edy ili napitka bez khlebной трапезы, trebuyushchey Birkat Hamazon — naprimer borei nefashot ili al hamichya.",
    ),
    "Ruach Ra'ah — Ruach Ra'ah (\"evil spirit\") is a rabbinic term for the impurity resting on hands after sleep. Morning netilat yadayim removes it by washing hands alternating right and left 3 times each.": T(
        "Ruach Ra'ah — Ruach Ra'ah (\"ruach ra'ah\") hu term rabbani le'tumah ha'nuchach al ha'yadayim achar sheinah. Netilat yadayim baboker me'akher oto bi'khlitat yadayim yemin u'smol shalosh pe'amim kol achat.",
        "Ruach Ra'ah — Ruach Ra'ah (\"espíritu malo\") es un término rabínico para la impureza en las manos tras dormir. El netilat yadayim matutino lo elimina lavando manos alternando derecha e izquierda 3 veces cada una.",
        "Ruach Ra'ah — Ruach Ra'ah (« esprit mauvais ») est un terme rabbinique pour l'impureté sur les mains après le sommeil. Le netilat yadayim du matin l'enlève en lavant les mains droite et gauche 3 fois chacune.",
        "Ruach Ra'ah — Ruach Ra'ah («zloy dukh») — rabbinicheskiy termin dlya tumah na rukakh posle sna. Utrennyaya netilat yadayim ustraняet ego, promyvaya ruki po ocheredi pravyyu i levuyu po 3 raza.",
    ),
    "Chametz is leavened grain product made from wheat, barley, rye, oats, or spelt. Bread, beer, and many processed foods can be chametz. On Pesach, owning, eating, or benefiting from chametz is forbidden.": T(
        "Chametz hu ma'achal dagan chamutz me'chitah, se'orah, shifon, shibolet shu'al o kusmin. Lechem, shikur ve'rabim ma'achalim me'ukavim yecholim lihyot chametz. BePesach, achizat, achilah o hana'ah mechametz asura.",
        "Chametz es producto de grano fermentado de trigo, cebada, centeno, avena o espelta. Pan, cerveza y muchos alimentos procesados pueden ser chametz. En Pesaj, poseer, comer o beneficiarse de chametz está prohibido.",
        "Chametz est un produit de céréales levé de blé, orge, seigle, avoine ou épeautre. Pain, bière et beaucoup d'aliments transformés peuvent être chametz. À Pessah, posséder, manger ou profiter de chametz est interdit.",
        "Chametz — kislyy zernovoy produkt iz pshenitsy, yachmenya, rzhi, ovsa ili polby. Khleb, pivo i mnogie obrabotannye produkty mogut byt chametz. Na Pesach vladenie, eda ili polza ot chametz zapreshcheny.",
    ),
    "Vatodi'enu — Vatodi'enu (\"You have made us know\") is an insert in the Maariv Amidah on Saturday night when Yom Tov begins after Shabbat. It acknowledges that Shabbat has ended and the festival has begun.": T(
        "Vatodi'enu — Vatodi'enu (\"hoda'atanu\") hu haser baAmidah shel Maariv be'motzaei Shabbat k'sheYom Tov mat'hil achar Shabbat. Hu me'ir sheShabbat nigmer veha'chag hit'hil.",
        "Vatodi'enu — Vatodi'enu (\"Nos has hecho saber\") es una inserción en la Amidá de Maariv el sábado por la noche cuando Yom Tov comienza tras Shabat. Reconoce que Shabat terminó y la festividad comenzó.",
        "Vatodi'enu — Vatodi'enu (« Tu nous as fait savoir ») est une insertion dans l'Amidah de Maariv le samedi soir quand Yom Tov commence après Chabbat. Elle reconnaît que Chabbat est fini et la fête a commencé.",
        "Vatodi'enu — Vatodi'enu («Ty sdelal nas znaющimi») — vstavka v Amidah Maariv v subbotu vecherom, kogda Yom Tov nachinaetsya posle Shabbat. Priznaet okonchanie Shabbat i nachalo prazdnika.",
    ),
    "Get rid of something chametz (leavened) you're not going to eat and have in mind that you're fulfilling the mitzvah of cleaning your home of chametz for Pesach. If it is currently Pesach, eat some matzah!": T(
        "Hishlikhu davar chametz (chamutz) she'einachem ochelin oto u'kavanu she'atem mekayemim mitzvat nikuy habayit mechametz lePesach. Im kach zman Pesach, ochlu ktzat matzah!",
        "Desecha algo chametz (fermentado) que no vayas a comer y ten presente que cumples la mitzvá de limpiar tu hogar de chametz para Pesaj. Si ahora es Pesaj, ¡come un poco de matzá!",
        "Débarrassez-vous d'un chametz (levé) que vous ne mangerez pas en ayant l'intention d'accomplir la mitzvah de nettoyer votre maison du chametz pour Pessah. Si nous sommes déjà à Pessah, mangez de la matza !",
        "Izavites ot chem-to chametz (kislogo), chto ne budete est, s namereniem vypolnit mitzvah ochistki doma ot chametz k Pesach. Esli seychas Pesach — seshite nemnogo matzah!",
    ),
    "Add Yaaleh V'yavo in the Shacharit Amidah on Rosh Chodesh — in the blessing Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nAlso add Yaaleh V'yavo in bentching if you eat bread today.": T(
        "Hosifu Yaaleh V'yavo baAmidah shel Shacharit beRosh Chodesh — bi'bracha Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nHosifu Yaaleh V'yavo gam bebentching im tochlu lechem hayom.",
        "Añade Yaaleh V'yavo en la Amidá de Shajarit en Rosh Jodesh — en la bendición Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nTambién añade Yaaleh V'yavo en bentching si comes pan hoy.",
        "Ajoutez Yaaleh V'yavo dans l'Amidah de Shacharit à Roch 'Hodesh — dans la bénédiction Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nAjoutez aussi Yaaleh V'yavo au bentching si vous mangez du pain aujourd'hui.",
        "Dobavte Yaaleh V'yavo v Amidah Shacharit v Rosh Chodesh — v brakhe Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha(\"Shacharit\")}\n\nTakzhe dobavte Yaaleh V'yavo v bentching, esli segodnya est khleb.",
    ),
    "aggadah — Aggadah is the non-legal storytelling and teaching in the Talmud and midrash — ethics, theology, and narrative. It complements halacha (law). Shabbat table stories and many midrashim are aggadah.": T(
        "aggadah — Aggadah hi ha'sippur ve'ha'limud she'einam halacha baTalmud u'vamidrash — musar, emunah ve'sippur. Hi meshalemet et ha'halacha. Sippurei shulchan Shabbat ve'rabim midrashim hem aggadah.",
        "aggadah — Aggadah es la narrativa y enseñanza no legal en el Talmud y midrash — ética, teología y relatos. Complementa la halajá (ley). Las historias de mesa de Shabat y muchos midrashim son aggadah.",
        "aggadah — Aggadah est le récit et l'enseignement non juridique du Talmud et du midrash — éthique, théologie et narration. Elle complète la halakha (loi). Les histoires de table de Chabbat et beaucoup de midrashim sont aggadah.",
        "aggadah — Aggadah — nelegalnye rasskazy i ucheniya v Talmude i midrashe — etika, bogoslovie i narrativ. Dopolnayet halakhu (zakon). Shabbat-stol rasskazy i mnogie midrashim — eto aggadah.",
    ),
    "Nevi'im — Nevi'im (Prophets) is the middle section of Tanach — Joshua, Kings, Isaiah, Jeremiah, and the other prophetic books. They call Israel to justice and loyalty to Hashem. Reading them is Torah study.": T(
        "Nevi'im — Nevi'im (Nevi'im) hu helek ha'emtza'i shel Tanach — Yehoshua, Melachim, Yeshayahu, Yirmiyahu ve'sefer nevi'im acherim. Hem kor'im leYisrael le'tzedek u'le'emunah ba'Hashem. Kriatam hi limud Torah.",
        "Nevi'im — Nevi'im (Profetas) es la sección central del Tanaj — Josué, Reyes, Isaías, Jeremías y los demás libros proféticos. Llaman a Israel a la justicia y lealtad a Hashem. Leerlos es estudio de Torá.",
        "Nevi'im — Nevi'im (Prophètes) est la section centrale du Tanakh — Josué, Rois, Isaïe, Jérémie et les autres livres prophétiques. Ils appellent Israël à la justice et à la fidélité à Hachem. Les lire est étude de Torah.",
        "Nevi'im — Nevi'im (Proroki) — srednyaya chast Tanakh — Yehoshua, Melakhim, Yeshayahu, Yirmiyahu i drugie knigi prorokov. Prizyvayut Izrail k spravedlivosti i vernosti Hashemu. Chtenie ikh — izuchenie Tory.",
    ),
    "Thank G-d for giving you the ability to feel textures and temperatures 🤚. From soft bristly grass to cooling water to a fluffy blanket - every sensation is a unique blessing that adds richness to our lives!": T(
        "הודu לה' שנתן לכם את היכולת להרגיש מרקמים וטמפרטורות 🤚. מעשב רך וסמרתי ועד מים מקררים ושמיכה רכה — כל תחושה היא bracha ייחודית שמעשירה את חיינו!",
        "Agradece a D-s por darte la capacidad de sentir texturas y temperaturas 🤚. Desde hierba suave y cerosa hasta agua refrescante y una manta mullida — ¡cada sensación es una bendición única que enriquece nuestras vidas!",
        "Remerciez D. de vous avoir donné la capacité de sentir textures et températures 🤚. De l'herbe douce et rêche à l'eau fraîche et une couverture moelleuse — chaque sensation est une bénédiction unique qui enrichit nos vies !",
        "Blagodarite V-ga za sposobnost chuvstvovat faktury i temperatury 🤚. Ot myagkoy kolюchey travy do prokhladnoy vody i pushenogo odeyala — kazhdoe oshchushchenie unikalnaya brakha, obogashchayushchaya zhizn!",
    ),
    "nefesh — Nefesh is the 'animal' part of the soul closest to physical life — appetite, hunger, physical desires, etc. Torah and mitzvot attempt to refine the nefesh toward holiness instead of animal instincts.": T(
        "nefesh — Nefesh hi helek ha'nefesh ha'karov le'chayim gashmiyim — ta'avah, ra'av, ta'avot gufaniyot ve'ch. Torah u'mitzvot me'ayenim le'zakh et ha'nefesh le'kedushah bimkom instinkt behemi.",
        "nefesh — Nefesh es la parte 'animal' del alma más cercana a la vida física — apetito, hambre, deseos físicos, etc. Torá y mitzvot intentan refinar el nefesh hacia la santidad en lugar de instintos animales.",
        "nefesh — Nefesh est la partie « animale » de l'âme la plus proche de la vie physique — appétit, faim, désirs physiques, etc. Torah et mitzvot cherchent à raffiner le nefesh vers la sainteté plutôt que les instincts animaux.",
        "nefesh — Nefesh — «zhivotnaya» chast dushi, blizhayshaya k fizicheskoy zhizni — appetit, golod, fizicheskie zhelaniya i t.d. Tora i mitzvot stremyatsya ochistit nefesh k kedushah vmesto zhivotnykh instinktov.",
    ),
}
