# -*- coding: utf-8 -*-
def T(he, es, fr, ru):
    return (he, es, fr, ru)

ENTRIES = {
    "Learn about Tefillin! 👑 Did you know? The head Tefillin contains the same four Torah passages as the arm Tefillin, but arranged differently! Today's mission: Learn about how Tefillin connects our minds to G-d.": T(
        "למdu על Tefillin! 👑 ידעתם? Tefillin shel rosh mekabelim et arba haparshiyot shel Tefillin shel yad, aval be'seder shonе! Ha'mission shel hayom: limud al eich Tefillin mechabrim et moachenu la'Hashem.",
        "¡Aprende sobre Tefilín! 👑 ¿Sabías? El Tefilín de la cabeza contiene los mismos cuatro pasajes de Torá que el del brazo, ¡pero ordenados de forma distinta! Misión de hoy: aprende cómo el Tefilín conecta nuestra mente con D-s.",
        "Apprenez sur les Téfilines ! 👑 Le saviez-vous ? Le Téfiline de la tête contient les mêmes quatre passages de Torah que celui du bras, mais disposés différemment ! Mission du jour : apprendre comment les Téfilines relient notre esprit à D.",
        "Uchites o Tefillin! 👑 Znali li? Tefillin na golove soderzhit te zhe chetyre otryvka Tory, chto i na ruke, no v drugom poryadke! Zadacha dnya: kak Tefillin svyazyvaet um s V-gom.",
    ),
    "Discover the deeper meaning of the beard in Judaism! 🧔 Did you know? Kabbalists say that the 13 attributes of Divine mercy can emanate through the hairs of the beard! Now that's what I call a valuable hairloom.": T(
        "גלו את המשמעות העמוקה של הזקן ביהדות! 🧔 ידעתם? קabbalistim omrim she-13 midot ha'rachamim yecholim le'histalek דרך שערות הזקן! זו באמת ירושה שיערית יקרת ערך.",
        "¡Descubre el significado profundo de la barba en el judaísmo! 🧔 ¿Sabías? Los cabalistas dicen que los 13 atributos de la misericordia divina pueden emanar a través de los pelos de la barba. ¡Eso sí que es un legado valioso!",
        "Découvrez la signification profonde de la barbe dans le judaïsme ! 🧔 Les kabbalistes disent que les 13 attributs de miséricorde divine peuvent émaner par les poils de la barbe ! Voilà un héritage précieux !",
        "Otkroyte glubokiy smysl borody v iudaizme! 🧔 Kabbалisty govoryat, chto 13 svoystv bozhestvennoy milosti mogut izluchatsya cherez volosy borody! Vot eto tsennoye nasledie!",
    ),
    "Maleh lugmov is drinking a cheekful from the Kiddush cup (approx 2 fl oz) after the blessing — from at least a total of a revi'it of wine or grape juice in the cup. Grape juice counts like wine for many poskim.": T(
        "Maleh lugmov hu shtiyah maleh lugma mi'kos haKiddush (b'kiruv 60 ml) achar ha'bracha — mi'klal revi'it yain o mishmash anavim ba'kos. Mishmash anavim nechshav keyayin le'rabim mi'ha'poskim.",
        "Maleh lugmov es beber un puñado de la copa de Kiddush (aprox. 60 ml) tras la bendición — de al menos un revi'it de vino o jugo de uva en la copa. El jugo de uva cuenta como vino para muchos poskim.",
        "Maleh lugmov consiste à boire une joue pleine de la coupe de Kiddush (env. 60 ml) après la bénédiction — d'au moins un revi'it de vin ou jus de raisin dans la coupe. Le jus de raisin compte comme du vin pour beaucoup de poskim.",
        "Maleh lugmov — vypit polnye shcheki iz Kiddush-kubka (okolo 60 ml) posle brakhi — iz ne menee revi'it vina ili vinogradnogo soka. Vinogradnyy sok schitaetsya vinom u mnogikh poskim.",
    ),
    "Chametz — Chametz is leavened grain product made from wheat, barley, rye, oats, or spelt. Bread, beer, and many processed foods can be chametz. On Pesach, owning, eating, or benefiting from chametz is forbidden.": T(
        "Chametz — Chametz hu ma'achal dagan chamutz me'chitah, se'orah, shifon, shibolet shu'al o kusmin. Lechem, shikur ve'rabim ma'achalim me'ukavim yecholim lihyot chametz. BePesach, achizat, achilah o hana'ah mechametz asura.",
        "Chametz — Chametz es producto de grano fermentado de trigo, cebada, centeno, avena o espelta. Pan, cerveza y muchos alimentos procesados pueden ser chametz. En Pesaj, poseer, comer o beneficiarse de chametz está prohibido.",
        "Chametz — Chametz est un produit de céréales levé de blé, orge, seigle, avoine ou épeautre. Pain, bière et beaucoup d'aliments transformés peuvent être chametz. À Pessah, posséder, manger ou profiter de chametz est interdit.",
        "Chametz — Chametz — kislyy zernovoy produkt iz pshenitsy, yachmenya, rzhi, ovsa ili polby. Khleb, pivo i mnogie obrabotannye produkty mogut byt chametz. Na Pesach vladenie, eda ili polza ot chametz zapreshcheny.",
    ),
    "Rosh Chodesh during Chanukah — if you recite Hallel, say Full Hallel at Shacharit (the Chanukah practice), not Half Hallel (Peninei Halakha 12-02-07). Optional for women — follow your minhag.\n\nTachanun is omitted.": T(
        "Rosh Chodesh beChanukah — im omrim Hallel, omru Full Hallel beShacharit (minhag Chanukah), lo Half Hallel (Peninei Halakha 12-02-07). Reshut le'nashim — lefi minhagchem.\n\nTachanun batel.",
        "Rosh Jodesh durante Janucá — si recitas Halel, di Halel completo en Shajarit (práctica de Janucá), no Medio Halel (Peninei Halakha 12-02-07). Opcional para mujeres — sigue tu minhag.\n\nTachanún se omite.",
        "Roch 'Hodesh pendant Hanoucca — si vous récitez Hallel, dites Hallel complet à Shacharit (pratique de Hanoucca), pas Demi-Hallel (Peninei Halakha 12-02-07). Optionnel pour les femmes — suivez votre minhag.\n\nTa'hanoun est omis.",
        "Rosh Chodesh vo vremya Chanukah — esli chitaete Hallel, govorete Polnyy Hallel na Shacharit (obychay Chanukah), ne Polu-Hallel (Peninei Halakha 12-02-07). Po zhelaniyu dlya zhenshchin — po vashemu minhag.\n\nTachanun propuskayetsya.",
    ),
    "Thank G-d for giving you the ability to smell your surroundings. Not only do you know when someone is baking cookies, but it can help you avoid danger. What if everything in the whole world smelled like cardboard?": T(
        "הודu לה' שנתן לכם את היכולת להריח את סביבתכם. לא רק שאתם יודעים כשמישהו אופה עוגיות, אלא שזה יכול לעזור להימנע מסכנה. מה אם הכל בעולם היה מריח כמו קarton?",
        "Agradece a D-s por darte la capacidad de oler tu entorno. No solo sabes cuándo alguien hornea galletas, sino que puede ayudarte a evitar peligros. ¿Y si todo el mundo oliera a cartón?",
        "Remerciez D. de vous avoir donné la capacité de sentir votre environnement. Vous savez quand quelqu'un fait des biscuits, et cela peut vous aider à éviter un danger. Et si tout sentait le carton ?",
        "Blagodarite V-ga za sposobnost chuvstvovat zapakhi vokrug. Vy ne tolko znaete, kogda pekut pechene, no eto pomogaet izbezhat opasnosti. Chto esli by vsyo v mire pakhlo kartonom?",
    ),
    "Tanach (Tanakh) is the Hebrew Bible in three parts: Torah (the five books), Nevi'im (Prophets), and Ketuvim (Writings). Reading Tanach in Hebrew or translation is Torah study; Psalms (Tehillim) are part of Ketuvim.": T(
        "Tanach (Tanakh) hu haMikra be'shalosh chlakim: Torah (chamesh chumashim), Nevi'im veKetuvim. Kriat Tanach be'Ivrit o b'targum hi limud Torah; Tehillim hem helek miKetuvim.",
        "Tanaj (Tanaj) es la Biblia hebrea en tres partes: Torá (los cinco libros), Nevi'im (Profetas) y Ketuvim (Escrituras). Leer Tanaj en hebreo o traducción es estudio de Torá; los Salmos (Tehillim) son parte de Ketuvim.",
        "Tanakh est la Bible hébraïque en trois parties : Torah (cinq livres), Nevi'im (Prophètes) et Ketuvim (Écrits). Lire le Tanakh en hébreu ou traduction est étude de Torah ; les Psaumes (Tehillim) font partie des Ketuvim.",
        "Tanakh — evreyskaya Bibliya v trekh chastyakh: Tora (pyat knig), Nevi'im (Proroki) i Ketuvim (Pisaniya). Chtenie Tanakh na ivrite ili v perevode — izuchenie Tory; Tehillim — chast Ketuvim.",
    ),
    "Tomorrow is erev $tomorrowChag — the Yom Tov–Shabbat rules below apply starting then. Use today (during the day) to prepare so you are not caught tonight or tomorrow without eruv tavshilin, flames, or food in place.": T(
        "Machar erev $tomorrowChag — chukei Yom Tov–Shabbat lemata chalim me'az. Hasivu et hayom (be'or hayom) le'hachana kedei shelo tippalelu ha'layla o machar bli eruv tavshilin, nerot o ochel ba'makom.",
        "Mañana es erev $tomorrowChag — las reglas de Yom Tov–Shabat abajo aplican desde entonces. Usa hoy (durante el día) para prepararte y no quedarte esta noche o mañana sin eruv tavshilin, llamas o comida lista.",
        "Demain c'est erev $tomorrowChag — les règles Yom Tov–Chabbat ci-dessous s'appliquent dès lors. Utilisez aujourd'hui (de jour) pour préparer afin de ne pas être pris ce soir ou demain sans erouv tavshilin, flammes ou nourriture en place.",
        "Zavtra erev $tomorrowChag — pravila Yom Tov–Shabbat nizhe deystvuyut s etogo momenta. Ispolzuyte segodnya (dnyom) dlya podgotovki, chtoby ne okazatsya vecherom ili zavtra bez eruv tavshilin, ognya ili edy.",
    ),
    "Add your own mitzvah! ✡ The Talmud teaches that each person has their own unique way of serving G-d. Think of a mitzvah that can bring more light into the world and submit it in the 'Add a Mitzvah' section of the app!": T(
        "הוסיפu mitzvah משלכם! ✡ התalmud melamed she'le'chol adam derech yechida le'avod et ha'Hashem. חשbu al mitzvah she'yechol le'havi or nוסף la'olam ve'shlichu ba'Add a Mitzvah' ba'app!",
        "¡Añade tu propia mitzvá! ✡ El Talmud enseña que cada persona tiene su forma única de servir a D-s. Piensa en una mitzvá que traiga más luz al mundo y envíala en la sección 'Add a Mitzvah' de la app.",
        "Ajoutez votre propre mitzvah ! ✡ Le Talmud enseigne que chaque personne a sa façon unique de servir D. Pensez à une mitzvah qui apporte plus de lumière au monde et soumettez-la dans la section « Add a Mitzvah » de l'app !",
        "Dobavte svoyu mitzvah! ✡ Talmud uchит, chto u kazhdogo svoy put sluzheniya V-gu. Pridumayte mitzvah, kotoraya prineset bolshe sveta, i otpravte v razdele 'Add a Mitzvah' v prilozhenii!",
    ),
    "Borei Minei Besamim — catch-all blessing on fragrant herbs, spices, flowers, fruit, etc. (often said as the spice blessing in Havdalah after Shabbat, though some will say a more specific blessing on pleasant fragrances)": T(
        "Borei Minei Besamim — bracha klalit al samim, tavlinim, perachim, pri ve'ch. (l'rov ne'emra ke'brachat ha'besamim baHavdalah achar Shabbat, af al pi she'yesh ha'omrim bracha meyuchedet yoter al rei'ach naim)",
        "Borei Minei Besamim — bendición general sobre hierbas aromáticas, especias, flores, fruta, etc. (a menudo dicha como bendición de especias en Havdalah tras Shabat, aunque algunos dicen una bendición más específica sobre fragancias agradables)",
        "Borei Minei Besamim — bénédiction générale sur herbes parfumées, épices, fleurs, fruits, etc. (souvent dite comme bénédiction des épices à Havdalah après Chabbat, bien que certains disent une bénédiction plus spécifique sur les parfums agréables)",
        "Borei Minei Besamim — obshchaya brakha na aromatnye travy, specii, tsvety, plody i t.d. (chasto kak brakha na specii v Havdalah posle Shabbat, khotya nekotorye govoryat bolee konkretnuyu brakhu na priyatnye zapakhi)",
    ),
    "Olam HaBa is the World to Come — the eternal reality of closeness to G-d after this life (Heaven). Mitzvot, Torah study, and acts of kindness build merits that the sages describe as unfathomable treasures in that world.": T(
        "Olam HaBa hu Olam HaBa — ha'metziut ha'nitzchit shel kirvat la'Hashem achar hachayim ha'eleh (Gan Eden). Mitzvot, limud Torah u'ma'asim tovim bonim zechuyot she'ha'chachamim mesaprim aleihen ke'otzrot bli shiur ba'olam hahu.",
        "Olam HaBa es el Mundo Venidero — la realidad eterna de cercanía a D-s tras esta vida (Cielo). Mitzvot, estudio de Torá y actos de bondad acumulan méritos que los sabios describen como tesoros inconmensurables en ese mundo.",
        "Olam HaBa est le Monde à Venir — la réalité éternelle de proximité avec D. après cette vie (Paradis). Mitzvot, étude de Torah et actes de bonté accumulent des mérites que les sages décrivent comme des trésors incommensurables dans ce monde.",
        "Olam HaBa — Mir gрядushchiy — vechnaya blizost k V-gu posle etoy zhizni (Ray). Mitzvot, izuchenie Tory i dobrye dela sozdayut zaslugi, kotorye mudretsy opisyvayut kak nepostizhimye sokrovishcha v tom mire.",
    ),
    "Pshat is the plain, straightforward meaning of a Torah verse — what the text says on its surface before deeper layers. Rashi on Chumash mainly explains pshat. Learning pshat is the foundation before midrash or Kabbalah.": T(
        "Pshat hu pshat ha'pshuta shel pasuk baTorah — mah ha'ktav omair ba'glishah lifnei shichvot amokot. Rashi al haChumash mefareshet ba'ikar pshat. Limud pshat hu ha'yessod lifnei midrash o Kabbalah.",
        "Pshat es el significado llano y directo de un versículo de Torá — lo que el texto dice en superficie antes de capas más profundas. Rashi en Jumash explica principalmente pshat. Aprender pshat es la base antes del midrash o la Cábala.",
        "Pshat est le sens simple et direct d'un verset de Torah — ce que le texte dit en surface avant les couches profondes. Rachi sur le 'Houmash explique surtout le pshat. Apprendre le pshat est la base avant midrash ou Kabbale.",
        "Pshat — prostoy, pryamoy smysl stikha Tory — chto tekst govorit na poverkhnosti do glubokikh sloev. Rashi na Humash obyasnyaet preimushchestvenno pshat. Izuchenie pshat — osnova pered midrashem ili Kabbala.",
    ),
    "Shir HaMaalot is Psalm 126 — \"When G-d returns the captivity of Zion\" — sung before bentching on Shabbat and festivals. It expresses joy in redemption and hope for complete return. Many know the tune from Shabbat tables.": T(
        "Shir HaMaalot hu Tehillim 126 — \"B'shuv Hashem et shivat Tzion\" — sharim lifnei bentching beShabbat u'vachagim. Hu me'ir simcha bi'geulah ve'tikvah le'shiva shlema. Rabim makirim et ha'niggun mi'shulchanot Shabbat.",
        "Shir HaMaalot es el Salmo 126 — \"Cuando D-s haga volver a Sión\" — cantado antes del bentching en Shabat y fiestas. Expresa alegría por la redención y esperanza de retorno completo. Muchos conocen la melodía de las mesas de Shabat.",
        "Shir HaMaalot est le Psaume 126 — « Quand D. fera revenir Sion » — chanté avant le bentching le Chabbat et les fêtes. Il exprime la joie de la rédemption et l'espoir du retour complet. Beaucoup connaissent l'air des tables de Chabbat.",
        "Shir HaMaalot — Psalom 126 — «Kogda V-s vernet plen Tziona» — poyetsya pered bentching v Shabbat i prazdniki. Vyrazhaet radost geuly i nadezhdu na polnoye vozvrashchenie. Mnogie znayut napev so shabbat-stolov.",
    ),
    "Borei pri ha'adamah is the blessing on produce that grows from the earth — potatoes, cucumbers, melons, and many berries. It covers foods that are not tree fruit. Water and plain beverages have their own blessings or none.": T(
        "Borei pri ha'adamah hi ha'bracha al pri ha'adamah — tapuchim, melafefonim, avatiach ve'rabim perot shatich. Hi mechasa al ma'achalim she'einam pri ha'etz. Mayim u'mashkim pshutim yesh lahem brachot acherot o ein.",
        "Borei pri ha'adamah es la bendición sobre productos que crecen de la tierra — papas, pepinos, melones y muchas bayas. Cubre alimentos que no son fruta de árbol. El agua y bebidas simples tienen sus propias bendiciones o ninguna.",
        "Borei pri ha'adamah est la bénédiction sur les produits qui poussent de la terre — pommes de terre, concombres, melons et beaucoup de baies. Elle couvre les aliments qui ne sont pas des fruits d'arbre. L'eau et les boissons simples ont leurs propres bénédictions ou aucune.",
        "Borei pri ha'adamah — brakha na produkty, rastushchie iz zemli — kartofel, ogurtsy, dyni i mnogie yagody. Pokryvaet produkty, ne yavlyayushchiesya plodami dereva. Voda i prostye napitki imeyut svoi brakhi ili ne imeyut.",
    ),
    "Yom Yerushalayim marks the reunification of Jerusalem in 1967, observed on 28 Iyar.\n\nMany communities recite Hallel and hold festive gatherings. As with Yom Ha'atzmaut, customs and halachic rulings vary — consult your rav.": T(
        "Yom Yerushalayim me'ayen et ichud Yerushalayim bi'1967, nitzav be-28 Iyar.\n\nKehillot rabot omrim Hallel ve'ochazot be'asifot chagigiyot. K'mo Yom Ha'atzmaut, minhagim u'psakim shonim — histakeletz ba'rav.",
        "Yom Yerushalayim conmemora la reunificación de Jerusalén en 1967, observado el 28 de Iyar.\n\nMuchas comunidades recitan Halel y celebran reuniones festivas. Como Yom Ha'atzmaut, las costumbres y decisiones halájicas varían — consulta a tu rav.",
        "Yom Yeroushalayim marque la réunification de Jérusalem en 1967, observé le 28 Iyar.\n\nBeaucoup de communautés récitent Hallel et tiennent des rassemblements festifs. Comme Yom Ha'atsmaout, coutumes et décisions halakhiques varient — consultez votre rav.",
        "Yom Yerushalayim otmechaet vossoedinenie Ierusalima v 1967, nablyudayetsya 28 Iyar.\n\nMnogie obshchiny chitayut Hallel i provodyat prazdnichnye sobraniya. Kak Yom Ha'atzmaut, obychai i psakim razlichayutsya — obratites k ravu.",
    ),
    "Tanach — Tanach (Tanakh) is the Hebrew Bible in three parts: Torah (the five books), Nevi'im (Prophets), and Ketuvim (Writings). Reading Tanach in Hebrew or translation is Torah study; Psalms (Tehillim) are part of Ketuvim.": T(
        "Tanach — Tanach (Tanakh) hu haMikra be'shalosh chlakim: Torah (chamesh chumashim), Nevi'im veKetuvim. Kriat Tanach be'Ivrit o b'targum hi limud Torah; Tehillim hem helek miKetuvim.",
        "Tanaj — Tanaj (Tanaj) es la Biblia hebrea en tres partes: Torá (los cinco libros), Nevi'im (Profetas) y Ketuvim (Escrituras). Leer Tanaj en hebreo o traducción es estudio de Torá; los Salmos (Tehillim) son parte de Ketuvim.",
        "Tanakh — Tanakh est la Bible hébraïque en trois parties : Torah (cinq livres), Nevi'im (Prophètes) et Ketuvim (Écrits). Lire le Tanakh en hébreu ou traduction est étude de Torah ; les Psaumes (Tehillim) font partie des Ketuvim.",
        "Tanakh — Tanakh — evreyskaya Bibliya v trekh chastyakh: Tora (pyat knig), Nevi'im (Proroki) i Ketuvim (Pisaniya). Chtenie Tanakh na ivrite ili v perevode — izuchenie Tory; Tehillim — chast Ketuvim.",
    ),
    "Make every day special! Take a moment to think about the upcoming Shabbat 🌅. Maybe plan a special dish you'll make, or imagine the peaceful atmosphere you'll create. Did you know? It's a mitzvah to remember Shabbat every day!": T(
        "עשu כל יom מיוחד! קחu רגע לחשוב על Shabbat הקרוב 🌅. אולי תכננu מנה מיוחדת או דמיינu את האווירה השלווה. ידעתם? זו mitzvah לזכור את Shabbat בכל יom!",
        "¡Haz especial cada día! Tómate un momento para pensar en el próximo Shabat 🌅. Quizá planifica un plato especial o imagina la atmósfera pacífica que crearás. ¿Sabías? ¡Es mitzvá recordar Shabat cada día!",
        "Rendez chaque jour spécial ! Prenez un moment pour penser au prochain Chabbat 🌅. Planifiez peut-être un plat spécial ou imaginez l'atmosphère paisible que vous créerez. Le saviez-vous ? C'est une mitzvah de se souvenir de Chabbat chaque jour !",
        "Delайte kazhdyy den osobennym! Udelyte minutu predstoyashchemu Shabbat 🌅. Mozhet, zaplaniruyte osobennoe blyudo ili predstavte mirnuyu atmosferu. Znali li? Eto mitzvah pomnit Shabbat kazhdyy den!",
    ),
    "Marvel at the miracle of breath! Notice how G-d designed our bodies to breathe automatically 🫁, giving us life with almost no effort. Each breath is a gift - try taking one deep, mindful breath right now and thank G-d for it!": T(
        "התפעלu מניס הneshimah! שימu לב איך ה' תכנן את גופנו לנשום אוטומטית 🫁, ונותן לנו חיים כמעט ללא מאמץ. כל נשימה היא מתנה — נסu נשימה עמוקה ומודעת עכשיו והודu לה'!",
        "¡Maravíllate con el milagro de la respiración! Observa cómo D-s diseñó nuestros cuerpos para respirar automáticamente 🫁, dándonos vida casi sin esfuerzo. Cada respiración es un regalo — ¡toma una respiración profunda y consciente ahora y agradece a D-s!",
        "Émerveillez-vous du miracle de la respiration ! Remarquez comment D. a conçu nos corps pour respirer automatiquement 🫁, nous donnant la vie presque sans effort. Chaque souffle est un cadeau — prenez une respiration profonde et consciente maintenant et remerciez D. !",
        "Udivites chudu dykhaniya! Zametьte, kak V-s sozdal nashi tela dlya avtomaticheskogo dykhaniya 🫁, daruya zhizn pochti bez usiliy. Kazhdoe dykhanie — dar — sdelayte glubokiy osозnannyy vдох seychas i poblagodarite V-ga!",
    ),
    "The Zohar is the classic work of Kabbalah, attributed to Rabbi Shimon bar Yochai, written in Aramaic. It illuminates the Torah's inner dimensions. Many study a daily snippet; full mastery requires Hebrew/Aramaic and guidance.": T(
        "HaZohar hu sefer haKabbalah ha'klasi, minuy le'Rabbi Shimon bar Yochai, katuv be'Aramit. Hu me'ir et pnimiyut haTorah. Rabim lomdim ktzat yom yom; shleimut doreshet Ivrit/Aramit ve'hadracha.",
        "El Zóhar es la obra clásica de la Cábala, atribuida al Rabí Shimón bar Yojai, escrita en arameo. Ilumina las dimensiones internas de la Torá. Muchos estudian un fragmento diario; el dominio pleno requiere hebreo/aramaico y guía.",
        "Le Zohar est l'œuvre classique de la Kabbale, attribuée au Rabbi Shimon bar Yo'haï, écrite en araméen. Il éclaire les dimensions intérieures de la Torah. Beaucoup étudient un extrait quotidien ; la maîtrise complète exige hébreu/araméen et guidance.",
        "Zohar — klassicheskoe proizvedenie Kabbaly, prpisыvaemoe Rabbenu Shimonu bar Yochai, napisano na arameyskom. Osveshchaet vnutrennie izmereniya Tory. Mnogie uchат ezhednevnyy otryvok; polnoe osvoenie trebuet ivrit/ arameyskogo i nastavnika.",
    ),
    "maleh lugmov — Maleh lugmov is drinking a cheekful from the Kiddush cup (approx 2 fl oz) after the blessing — from at least a total of a revi'it of wine or grape juice in the cup. Grape juice counts like wine for many poskim.": T(
        "maleh lugmov — Maleh lugmov hu shtiyah maleh lugma mi'kos haKiddush (b'kiruv 60 ml) achar ha'bracha — mi'klal revi'it yain o mishmash anavim ba'kos. Mishmash anavim nechshav keyayin le'rabim mi'ha'poskim.",
        "maleh lugmov — Maleh lugmov es beber un puñado de la copa de Kiddush (aprox. 60 ml) tras la bendición — de al menos un revi'it de vino o jugo de uva en la copa. El jugo de uva cuenta como vino para muchos poskim.",
        "maleh lugmov — Maleh lugmov consiste à boire une joue pleine de la coupe de Kiddush (env. 60 ml) après la bénédiction — d'au moins un revi'it de vin ou jus de raisin dans la coupe. Le jus de raisin compte comme du vin pour beaucoup de poskim.",
        "maleh lugmov — Maleh lugmov — vypit polnye shcheki iz Kiddush-kubka (okolo 60 ml) posle brakhi — iz ne menee revi'it vina ili vinogradnogo soka. Vinogradnyy sok schitaetsya vinom u mnogikh poskim.",
    ),
    "Do the powerful mitzvah of praying for others! Think of someone who's looking for their soulmate (shidduch) and say a heartfelt prayer for them 💑. Your sincere prayer could be the key that opens the gates of blessing for them!": T(
        "עשu את mitzvah העוצמתי של התפלל עבור אחרים! חשbu על מישהו שמחפש shidduch והתפללu עבורו בכנות 💑. התפילה הכנה שלכם יכולה להיות המפתח שפותח שערי bracha עבורם!",
        "¡Haz la poderosa mitzvá de orar por otros! Piensa en alguien que busca su alma gemela (shidduj) y ora sinceramente por ellos 💑. ¡Tu oración sincera podría ser la llave que abra las puertas de la bendición para ellos!",
        "Accomplissez la mitzvah puissante de prier pour les autres ! Pensez à quelqu'un qui cherche son âme sœur (shidou'h) et priez sincèrement pour lui 💑. Votre prière sincère pourrait ouvrir les portes de la bénédiction pour lui !",
        "Vypolnite silnuyu mitzvah molitvy za drugikh! Vspomnite kogo-to, kto ishchет zyuzhnuyu polovinku (shidduch), i iskrenne pomolites za nego 💑. Vasha iskrennyaya molitva mozhet otkryt vorota brakhi dlya nego!",
    ),
    "Treif means non-kosher — originally torn flesh of improperly slaughtered animals, now any forbidden food. Mixing treif into a kosher kitchen can require kashering. \"Kosher style\" restaurants without supervision are not kosher.": T(
        "Treif mashma lo kasher — b'mekor nevelah shel behema she'nishchat shelo k'hilchata, hayom kol ma'achal asur. Erev treif ba'mitbach kasher yechol le'drosh hashgacha/kashering. \"Kosher style\" bli hashgacha ein kasher.",
        "Treif significa no kosher — originalmente carne desgarrada de animales mal sacrificados, ahora cualquier alimento prohibido. Mezclar treif en una cocina kosher puede requerir kashering. Restaurantes \"estilo kosher\" sin supervisión no son kosher.",
        "Treif signifie non cacher — à l'origine chair déchirée d'animaux mal abattus, aujourd'hui tout aliment interdit. Mélanger du treif dans une cuisine casher peut exiger un kashering. Les restaurants « style casher » sans supervision ne sont pas casher.",
        "Treif oznachaet ne kosher — iznachalno rvanoye myaso nepravilno zabitykh zhivotnykh, seychas lyubaya zapreshchennaya eda. Smeshivanie treif v koshernoy kukhne mozhet trebovat kashering. Restorany «kosher style» bez nadzora ne kosher.",
    ),
    "pshat — Pshat is the plain, straightforward meaning of a Torah verse — what the text says on its surface before deeper layers. Rashi on Chumash mainly explains pshat. Learning pshat is the foundation before midrash or Kabbalah.": T(
        "pshat — Pshat hu pshat ha'pshuta shel pasuk baTorah — mah ha'ktav omair ba'glishah lifnei shichvot amokot. Rashi al haChumash mefareshet ba'ikar pshat. Limud pshat hu ha'yessod lifnei midrash o Kabbalah.",
        "pshat — Pshat es el significado llano y directo de un versículo de Torá — lo que el texto dice en superficie antes de capas más profundas. Rashi en Jumash explica principalmente pshat. Aprender pshat es la base antes del midrash o la Cábala.",
        "pshat — Pshat est le sens simple et direct d'un verset de Torah — ce que le texte dit en surface avant les couches profondes. Rachi sur le 'Houmash explique surtout le pshat. Apprendre le pshat est la base avant midrash ou Kabbale.",
        "pshat — Pshat — prostoy, pryamoy smysl stikha Tory — chto tekst govorit na poverkhnosti do glubokikh sloev. Rashi na Humash obyasnyaet preimushchestvenno pshat. Izuchenie pshat — osnova pered midrashem ili Kabbala.",
    ),
    "Yom Tov (literally \"good day\") is a biblical festival such as Pesach, Shavuot, Sukkot, or Rosh Hashana. It resembles Shabbat in joy and in restricting melacha, but cooking and carrying are generally permitted for festival needs.": T(
        "Yom Tov (mashma \"yom tov\") hu chag miKra k'Pesach, Shavuot, Sukkot o Rosh Hashana. Domeh leShabbat ba'simcha u'v'issur melacha, aval bishul ve'hotza'ah mutarim le'tzorkhei chag.",
        "Yom Tov (literalmente \"día bueno\") es una festividad bíblica como Pesaj, Shavuot, Sucot o Rosh Hashaná. Se parece a Shabat en alegría y restricción de melajá, pero cocinar y transportar generalmente están permitidos para necesidades festivas.",
        "Yom Tov (littéralement « bon jour ») est une fête biblique comme Pessah, Chavouot, Souccot ou Roch Hachana. Il ressemble à Chabbat par la joie et la restriction de melakha, mais cuisiner et porter sont généralement permis pour les besoins de la fête.",
        "Yom Tov (doslovno «horoshiy den») — bibliyskiy prazdnik, kak Pesach, Shavuot, Sukkot ili Rosh Hashana. Pohozh na Shabbat radostyu i zapretom melacha, no gotovka i perenos obychno razreshены dlya nuzhd prazdnika.",
    ),
    "Olam HaBa — Olam HaBa is the World to Come — the eternal reality of closeness to G-d after this life (Heaven). Mitzvot, Torah study, and acts of kindness build merits that the sages describe as unfathomable treasures in that world.": T(
        "Olam HaBa — Olam HaBa hu Olam HaBa — ha'metziut ha'nitzchit shel kirvat la'Hashem achar hachayim ha'eleh (Gan Eden). Mitzvot, limud Torah u'ma'asim tovim bonim zechuyot she'ha'chachamim mesaprim aleihen ke'otzrot bli shiur ba'olam hahu.",
        "Olam HaBa — Olam HaBa es el Mundo Venidero — la realidad eterna de cercanía a D-s tras esta vida (Cielo). Mitzvot, estudio de Torá y actos de bondad acumulan méritos que los sabios describen como tesoros inconmensurables en ese mundo.",
        "Olam HaBa — Olam HaBa est le Monde à Venir — la réalité éternelle de proximité avec D. après cette vie (Paradis). Mitzvot, étude de Torah et actes de bonté accumulent des mérites que les sages décrivent comme des trésors incommensurables dans ce monde.",
        "Olam HaBa — Olam HaBa — Mir gрядushchiy — vechnaya blizost k V-gu posle etoy zhizni (Ray). Mitzvot, izuchenie Tory i dobrye dela sozdayut zaslugi, kotorye mudretsy opisyvayut kak nepostizhimye sokrovishcha v tom mire.",
    ),
    "Ketuvim (Writings) is the third section of Tanach — Psalms (Tehillim), Proverbs, Esther, Ruth, Daniel, and others. It includes poetry, history, and wisdom literature. Tehillim is the most commonly recited book for comfort and praise.": T(
        "Ketuvim (Ketuvim) hu helek ha'shelishi shel Tanach — Tehillim, Mishlei, Esther, Rut, Daniel ve'acharim. Hu koleh shira, historia ve'chochmah. Tehillim hu ha'sefer ha'ne'emar yoter le'nechama u'le'hallel.",
        "Ketuvim (Escrituras) es la tercera sección del Tanaj — Salmos (Tehillim), Proverbios, Ester, Rut, Daniel y otros. Incluye poesía, historia y literatura de sabiduría. Tehillim es el libro más recitado para consuelo y alabanza.",
        "Ketuvim (Écrits) est la troisième section du Tanakh — Psaumes (Tehillim), Proverbes, Esther, Ruth, Daniel et autres. Elle comprend poésie, histoire et sagesse. Tehillim est le livre le plus récité pour réconfort et louange.",
        "Ketuvim (Pisaniya) — tretya chast Tanakh — Tehillim, Mishlei, Ester, Rut, Daniel i drugie. Vklyuchaet poeziyu, istoriyu i mudrost. Tehillim — kniga, chitaemaya chashche vsego dlya utesheniya i hvaly.",
    ),
    "Zohar — The Zohar is the classic work of Kabbalah, attributed to Rabbi Shimon bar Yochai, written in Aramaic. It illuminates the Torah's inner dimensions. Many study a daily snippet; full mastery requires Hebrew/Aramaic and guidance.": T(
        "Zohar — HaZohar hu sefer haKabbalah ha'klasi, minuy le'Rabbi Shimon bar Yochai, katuv be'Aramit. Hu me'ir et pnimiyut haTorah. Rabim lomdim ktzat yom yom; shleimut doreshet Ivrit/Aramit ve'hadracha.",
        "Zóhar — El Zóhar es la obra clásica de la Cábala, atribuida al Rabí Shimón bar Yojai, escrita en arameo. Ilumina las dimensiones internas de la Torá. Muchos estudian un fragmento diario; el dominio pleno requiere hebreo/aramaico y guía.",
        "Zohar — Le Zohar est l'œuvre classique de la Kabbale, attribuée au Rabbi Shimon bar Yo'haï, écrite en araméen. Il éclaire les dimensions intérieures de la Torah. Beaucoup étudient un extrait quotidien ; la maîtrise complète exige hébreu/araméen et guidance.",
        "Zohar — Zohar — klassicheskoe proizvedenie Kabbaly, prpisыvaemoe Rabbenu Shimonu bar Yochai, napisano na arameyskom. Osveshchaet vnutrennie izmereniya Tory. Mnogie uchат ezhednevnyy otryvok; polnoe osvoenie trebuet ivrita/ arameyskogo i nastavnika.",
    ),
    "Peninei Halakha is Rabbi Eliezer Melamed's modern Hebrew halacha series (available in English online), organized by topic — Shabbat, festivals, prayer, family, and Israel. It is clear, sourced, and widely used for practical questions.": T(
        "Peninei Halakha hu seder halacha b'Ivrit moderna shel haRav Eliezer Melamed (zamin gam be'Anglit ba'internet), me'urgan le'fi nusha — Shabbat, chagim, tefillah, mishpacha veYisrael. Barur, me'uyan ve'nifutz le'she'elot ma'asiyot.",
        "Peninei Halakha es la serie moderna de halajá en hebreo del Rabí Eliezer Melamed (disponible en inglés en línea), organizada por tema — Shabat, fiestas, oración, familia e Israel. Es clara, con fuentes y muy usada para preguntas prácticas.",
        "Peninei Halakha est la série moderne de halakha en hébreu du Rav Eliezer Melamed (disponible en anglais en ligne), organisée par sujet — Chabbat, fêtes, prière, famille et Israël. Claire, sourcée et largement utilisée pour les questions pratiques.",
        "Peninei Halakha — sovremennaya ivritskaya seriya halakhi Rava Eliezera Melameda (dostupna na angliyskom onlayn), po temam — Shabbat, prazdniki, molitva, semya i Izrail. Yasnaya, s istochnikami, shiroko ispolzuetsya dlya prakticheskikh voprosov.",
    ),
    "treif — Treif means non-kosher — originally torn flesh of improperly slaughtered animals, now any forbidden food. Mixing treif into a kosher kitchen can require kashering. \"Kosher style\" restaurants without supervision are not kosher.": T(
        "treif — Treif mashma lo kasher — b'mekor nevelah shel behema she'nishchat shelo k'hilchata, hayom kol ma'achal asur. Erev treif ba'mitbach kasher yechol le'drosh hashgacha/kashering. \"Kosher style\" bli hashgacha ein kasher.",
        "treif — Treif significa no kosher — originalmente carne desgarrada de animales mal sacrificados, ahora cualquier alimento prohibido. Mezclar treif en una cocina kosher puede requerir kashering. Restaurantes \"estilo kosher\" sin supervisión no son kosher.",
        "treif — Treif signifie non cacher — à l'origine chair déchirée d'animaux mal abattus, aujourd'hui tout aliment interdit. Mélanger du treif dans une cuisine casher peut exiger un kashering. Les restaurants « style casher » sans supervision ne sont pas casher.",
        "treif — Treif oznachaet ne kosher — iznachalno rvanoye myaso nepravilno zabitykh zhivotnykh, seychas lyubaya zapreshchennaya eda. Smeshivanie treif v koshernoy kukhne mozhet trebovat kashering. Restorany «kosher style» bez nadzora ne kosher.",
    ),
    "The Baal Shem Tov (Rabbi Israel ben Eliezer, c. 1700–1760) founded the Chasidic movement, teaching that every Jew can serve G-d with joy and that divine presence fills all creation. Chabad traces its spiritual lineage to his disciples.": T(
        "HaBaal Shem Tov (Rabbi Yisrael ben Eliezer, c. 1700–1760) yisad et tnu'at haChasidut, melamed she'kol Yehudi yachol la'avod et ha'Hashem be'simcha ve'she'hashra'at haShechinah mamla et kol ha'beriah. Chabad omeket et sharshelta ha'ruchanit le'talmidav.",
        "El Baal Shem Tov (Rabí Israel ben Eliezer, c. 1700–1760) fundó el movimiento jasídico, enseñando que todo judío puede servir a D-s con alegría y que la presencia divina llena toda la creación. Jabad remonta su linaje espiritual a sus discípulos.",
        "Le Baal Shem Tov (Rabbi Israel ben Eliezer, c. 1700–1760) a fondé le mouvement hassidique, enseignant que tout Juif peut servir D. avec joie et que la présence divine remplit toute la création. Habad trace sa lignée spirituelle à ses disciples.",
        "Baal Shem Tov (Rav Yisrael ben Eliezer, ok. 1700–1760) osnoval khasidskoe dvizhenie, uchа ya, chto kazhdyy evrey mozhet sluzhit V-gu s radostyu i chto bozhestvennoe prisutstvie napolnyaet vse tvorenie. Chabad vedet dukhovnuyu liniyu k ego uchenikam.",
    ),
    "Shir HaMaalot — Shir HaMaalot is Psalm 126 — \"When G-d returns the captivity of Zion\" — sung before bentching on Shabbat and festivals. It expresses joy in redemption and hope for complete return. Many know the tune from Shabbat tables.": T(
        "Shir HaMaalot — Shir HaMaalot hu Tehillim 126 — \"B'shuv Hashem et shivat Tzion\" — sharim lifnei bentching beShabbat u'vachagim. Hu me'ir simcha bi'geulah ve'tikvah le'shiva shlema. Rabim makirim et ha'niggun mi'shulchanot Shabbat.",
        "Shir HaMaalot — Shir HaMaalot es el Salmo 126 — \"Cuando D-s haga volver a Sión\" — cantado antes del bentching en Shabat y fiestas. Expresa alegría por la redención y esperanza de retorno completo. Muchos conocen la melodía de las mesas de Shabat.",
        "Shir HaMaalot — Shir HaMaalot est le Psaume 126 — « Quand D. fera revenir Sion » — chanté avant le bentching le Chabbat et les fêtes. Il exprime la joie de la rédemption et l'espoir du retour complet. Beaucoup connaissent l'air des tables de Chabbat.",
        "Shir HaMaalot — Shir HaMaalot — Psalom 126 — «Kogda V-s vernet plen Tziona» — poyetsya pered bentching v Shabbat i prazdniki. Vyrazhaet radost geuly i nadezhdu na polnoye vozvrashchenie. Mnogie znayut napev so shabbat-stolov.",
    ),
    "Mashiach (Moshiach) is the righteous anointed king from David's line who will rebuild the Temple, gather the exiles, and bring universal knowledge of G-d. Belief in his coming is a foundation of Jewish faith. We pray for redemption daily.": T(
        "Mashiach (Moshiach) hu melech tzadik m'shuch m'zera David she'yivneh et haMikdash, yekabetz et ha'gola ve'yavi da'at et ha'Hashem la'olam kulo. Emunah bi'vo'o hi yesod ha'emunah ha'Yehudit. Mitpalelim le'geulah yom yom.",
        "Mashiach (Moshiaj) es el rey justo ungido del linaje de David que reconstruirá el Templo, reunirá a los exiliados y traerá conocimiento universal de D-s. Creer en su venida es fundamento de la fe judía. Oramos por la redención diariamente.",
        "Machiach (Moshiach) est le roi juste oint de la lignée de David qui reconstruira le Temple, rassemblera les exilés et apportera la connaissance universelle de D. Croire en sa venue est un fondement de la foi juive. Nous prions pour la rédemption chaque jour.",
        "Mashiach (Moshiach) — pravednyy pomazannyy tsar iz roda David, kotoryy vosstanovit Khram, soberet izgnannikov i prineset vsемirnoye poznanie V-ga. Vera v ego prikhod — osnova evreyskoy very. My molimsya o geule ezhednevno.",
    ),
    "Yom Tov — Yom Tov (literally \"good day\") is a biblical festival such as Pesach, Shavuot, Sukkot, or Rosh Hashana. It resembles Shabbat in joy and in restricting melacha, but cooking and carrying are generally permitted for festival needs.": T(
        "Yom Tov — Yom Tov (mashma \"yom tov\") hu chag miKra k'Pesach, Shavuot, Sukkot o Rosh Hashana. Domeh leShabbat ba'simcha u'v'issur melacha, aval bishul ve'hotza'ah mutarim le'tzorkhei chag.",
        "Yom Tov — Yom Tov (literalmente \"día bueno\") es una festividad bíblica como Pesaj, Shavuot, Sucot o Rosh Hashaná. Se parece a Shabat en alegría y restricción de melajá, pero cocinar y transportar generalmente están permitidos para necesidades festivas.",
        "Yom Tov — Yom Tov (littéralement « bon jour ») est une fête biblique comme Pessah, Chavouot, Souccot ou Roch Hachana. Il ressemble à Chabbat par la joie et la restriction de melakha, mais cuisiner et porter sont généralement permis pour les besoins de la fête.",
        "Yom Tov — Yom Tov (doslovno «horoshiy den») — bibliyskiy prazdnik, kak Pesach, Shavuot, Sukkot ili Rosh Hashana. Pohozh na Shabbat radostyu i zapretom melacha, no gotovka i perenos obychno razreshены dlya nuzhd prazdnika.",
    ),
    "A keli is a vessel, utensil, or tool. It generally refers to any manufactured object or receptacle that holds, processes, or contains something. A keli is used for netilat yadayim — a cup, bottle, or washing cup (usually) with two handles.": T(
        "Keli hu keli, kli o kelim. Hu l'rov me'ayen kol davar meyuchad o makhlit she'machzik, me'ayen o mekabel davar. Keli meshamshim le'netilat yadayim — kos, bakbuk o kos netilah (l'rov) im shnei yadot.",
        "Un keli es un recipiente, utensilio o herramienta. Generalmente se refiere a cualquier objeto fabricado o receptáculo que sostiene, procesa o contiene algo. Un keli se usa para netilat yadayim — una copa, botella o jarrilla (usualmente) con dos asas.",
        "Un keli est un récipient, ustensile ou outil. Il désigne généralement tout objet fabriqué ou réceptacle qui contient ou traite quelque chose. Un keli sert au netilat yadayim — une coupe, bouteille ou gobelet (souvent) à deux anses.",
        "Keli — sosud, prinadlezhnost ili instrument. Obychno lyuboy izgotovlennyy predmet ili emkost, kotoraya derzhit ili soderzhit chto-to. Keli ispolzuetsya dlya netilat yadayim — kubok, butylka ili kovsh (обыchno) s dvumya ruchkami.",
    ),
    "Borei Pri HaAdamah — Borei pri ha'adamah is the blessing on produce that grows from the earth — potatoes, cucumbers, melons, and many berries. It covers foods that are not tree fruit. Water and plain beverages have their own blessings or none.": T(
        "Borei Pri HaAdamah — Borei pri ha'adamah hi ha'bracha al pri ha'adamah — tapuchim, melafefonim, avatiach ve'rabim perot shatich. Hi mechasa al ma'achalim she'einam pri ha'etz. Mayim u'mashkim pshutim yesh lahem brachot acherot o ein.",
        "Borei Pri HaAdamah — Borei pri ha'adamah es la bendición sobre productos que crecen de la tierra — papas, pepinos, melones y muchas bayas. Cubre alimentos que no son fruta de árbol. El agua y bebidas simples tienen sus propias bendiciones o ninguna.",
        "Borei Pri HaAdamah — Borei pri ha'adamah est la bénédiction sur les produits qui poussent de la terre — pommes de terre, concombres, melons et beaucoup de baies. Elle couvre les aliments qui ne sont pas des fruits d'arbre. L'eau et les boissons simples ont leurs propres bénédictions ou aucune.",
        "Borei Pri HaAdamah — Borei pri ha'adamah — brakha na produkty, rastushchie iz zemli — kartofel, ogurtsy, dyni i mnogie yagody. Pokryvaet produkty, ne yavlyayushchiesya plodami dereva. Voda i prostye napitki imeyut svoi brakhi ili ne imeyut.",
    ),
    "Daven (davening) means to pray. You 'daven' the daily services (Shacharit, Mincha, Maariv). The word is Yiddish-derived Ashkenazi slang but widely understood. People often say \"daven Shacharit\" for a service and \"daven\" for praying in general.": T(
        "Daven (davening) mashma le'hitpalel. 'Daven' et hatefillot hayom yom (Shacharit, Mincha, Maariv). Ha'milah hi slang Ashkenazi miYiddish aval me'uvetet. Omrim 'daven Shacharit' le'tefillah u'daven' le'hitpallel b'chlal.",
        "Daven (davening) significa orar. Se 'daven' los servicios diarios (Shajarit, Minjá, Maariv). La palabra es jerga ashkenazí del yiddish pero ampliamente entendida. Se dice \"daven Shacharit\" para un servicio y \"daven\" para orar en general.",
        "Daven (davening) signifie prier. On « daven » les offices quotidiens (Shacharit, Min'ha, Maariv). Le mot est un argot ashkénaze du yiddish mais largement compris. On dit « daven Shacharit » pour un office et « daven » pour prier en général.",
        "Daven (davening) oznachaet molitsya. 'Daven' — ezhednevnye sluzhby (Shacharit, Mincha, Maariv). Slovo iz ashkenazskogo zhargona na idishe, no shiroko ponimaetsya. Govoryat «daven Shacharit» o sluzhbe i «daven» o molitve voobshche.",
    ),
    "Ketuvim — Ketuvim (Writings) is the third section of Tanach — Psalms (Tehillim), Proverbs, Esther, Ruth, Daniel, and others. It includes poetry, history, and wisdom literature. Tehillim is the most commonly recited book for comfort and praise.": T(
        "Ketuvim — Ketuvim (Ketuvim) hu helek ha'shelishi shel Tanach — Tehillim, Mishlei, Esther, Rut, Daniel ve'acharim. Hu koleh shira, historia ve'chochmah. Tehillim hu ha'sefer ha'ne'emar yoter le'nechama u'le'hallel.",
        "Ketuvim — Ketuvim (Escrituras) es la tercera sección del Tanaj — Salmos (Tehillim), Proverbios, Ester, Rut, Daniel y otros. Incluye poesía, historia y literatura de sabiduría. Tehillim es el libro más recitado para consuelo y alabanza.",
        "Ketuvim — Ketuvim (Écrits) est la troisième section du Tanakh — Psaumes (Tehillim), Proverbes, Esther, Ruth, Daniel et autres. Elle comprend poésie, histoire et sagesse. Tehillim est le livre le plus récité pour réconfort et louange.",
        "Ketuvim — Ketuvim (Pisaniya) — tretya chast Tanakh — Tehillim, Mishlei, Ester, Rut, Daniel i drugie. Vklyuchaet poeziyu, istoriyu i mudrost. Tehillim — kniga, chitaemaya chashche vsego dlya utesheniya i hvaly.",
    ),
    "Chazeret is the second bitter herb on the Seder plate in some traditions — often romaine lettuce stalk — alongside maror. Not every community uses a separate chazeret; some use only horseradish for maror. Follow your Haggadah and family custom.": T(
        "Chazeret hu ha'maror ha'sheni ba'ke'arah baSeder b'chlk minhagim — l'rov chazeret chasah — yachad im maror. Lo kol kehillah meshameshet chazeret nifrad; yesh ha'omrim rak chrain le'maror. L'fi haHaggadah u'minhag ha'mishpacha.",
        "Chazeret es la segunda hierba amarga en el plato del Seder en algunas tradiciones — a menudo lechuga romana — junto al maror. No toda comunidad usa chazeret separado; algunos usan solo rábano picante para maror. Sigue tu Hagadá y costumbre familiar.",
        "Chazeret est la deuxième herbe amère sur l'assiette du Seder dans certaines traditions — souvent une tige de laitue romaine — aux côtés du maror. Toutes les communautés n'utilisent pas un chazeret séparé ; certains n'utilisent que du raifort pour le maror. Suivez votre Hagada et coutume familiale.",
        "Chazeret — vtoraya gorkaya trava na seder-tarelke v nekotorykh traditsiyakh — chasto salat romen — ryadom s maror. Ne vse obshchiny ispolzuyut otdelnyy chazeret; nekotorye tolko khren dlya maror. Sleduyte Hagade i semeynomu obychayu.",
    ),
    "Keli — A keli is a vessel, utensil, or tool. It generally refers to any manufactured object or receptacle that holds, processes, or contains something. A keli is used for netilat yadayim — a cup, bottle, or washing cup (usually) with two handles.": T(
        "Keli — Keli hu keli, kli o kelim. Hu l'rov me'ayen kol davar meyuchad o makhlit she'machzik, me'ayen o mekabel davar. Keli meshamshim le'netilat yadayim — kos, bakbuk o kos netilah (l'rov) im shnei yadot.",
        "Keli — Un keli es un recipiente, utensilio o herramienta. Generalmente se refiere a cualquier objeto fabricado o receptáculo que sostiene, procesa o contiene algo. Un keli se usa para netilat yadayim — una copa, botella o jarrilla (usualmente) con dos asas.",
        "Keli — Un keli est un récipient, ustensile ou outil. Il désigne généralement tout objet fabriqué ou réceptacle qui contient ou traite quelque chose. Un keli sert au netilat yadayim — une coupe, bouteille ou gobelet (souvent) à deux anses.",
        "Keli — Keli — sosud, prinadlezhnost ili instrument. Obychno lyuboy izgotovlennyy predmet ili emkost. Keli ispolzuetsya dlya netilat yadayim — kubok, butylka ili kovsh (обыchno) s dvumya ruchkami.",
    ),
    "Leining is chanting the Torah portion from the scroll with precise trop (cantillation). The baal koreh trains for months. Congregants follow in a Chumash. Hearing every word on Shabbat morning fulfills the communal mitzvah of public Torah reading.": T(
        "Leining hu kriat haparsha min haSefer Torah im trop m'duyak. Ha'baal koreh mit'amen chodshim. Ha'tzibur omdim im Chumash. Shmi'at kol milah beShabbat baboker mekayemet mitzvat kriat haTorah ba'tzibur.",
        "Leining es cantar la porción de Torá del rollo con trop preciso (cantilación). El baal kore entrena meses. Los feligreses siguen en un Jumash. Escuchar cada palabra el Shabat por la mañana cumple la mitzvá comunitaria de lectura pública de Torá.",
        "Leining consiste à lire la portion de Torah du rouleau avec un trop précis (cantillation). Le baal koré s'entraîne des mois. Les fidèles suivent dans un 'Houmash. Entendre chaque mot le Chabbat matin accomplit la mitzvah communautaire de lecture publique de Torah.",
        "Leining — chtenie parshi iz svitka s tochnym trop (kantillyatsiey). Baal koreh treniruetsya mesyatsami. Molящiesya sleduyut v Humash. Slushanie kazhdogo slova v Shabbat utrom vypolnyaet obshchinную mitzvah publichnogo chteniya Tory.",
    ),
    "Rosh Hashana is the Jewish New Year and Day of Judgment — shofar, festive meals, and solemn prayer. It begins the Ten Days of Teshuvah leading to Yom Kippur. Customs include apples in honey, new fruit, and tashlich. Work is forbidden like Yom Tov.": T(
        "Rosh Hashana hu Rosh Hashana u'Yom HaDin — shofar, seudot chagigiyot u'tefillah chamurah. Hu matchil et Aseret Yemei Teshuvah ad Yom Kippur. Minhagim: tapuach bidvash, pri chadash ve'tashlich. Melacha asura kmo Yom Tov.",
        "Rosh Hashaná es el Año Nuevo judío y Día del Juicio — shofar, comidas festivas y oración solemne. Comienza los Diez Días de Teshuvá hacia Yom Kipur. Costumbres: manzanas en miel, fruta nueva y tashlij. El trabajo está prohibido como Yom Tov.",
        "Roch Hachana est le Nouvel An juif et le Jour du Jugement — shofar, repas festifs et prière solennelle. Il commence les Dix Jours de Techouva menant à Yom Kippour. Coutumes : pommes au miel, fruit nouveau et tachlich. Le travail est interdit comme Yom Tov.",
        "Rosh Hashana — evreyskiy Novyy god i Sudnyy den — shofar, prazdnichnye трапезы i torzhestvennaya molitva. Nachinaet Desyat dney teshuvy do Yom Kippur. Obychai: yabloki s medom, novyy plod i tashlich. Trud zapreshchen kak Yom Tov.",
    ),
    "A bentcher (birkon) is a small booklet with Birkat Hamazon and sometimes Shabbat songs and benching additions. Keeping one at the table makes bentching after bread meals easy. Many are bilingual; some include zimun instructions and festival inserts.": T(
        "Bentcher (birkon) hu sefer katan im Birkat Hamazon ve'l'f'amim shirim leShabbat vetosafot lebentching. Le'hash'ir oto al ha'shulchan makhel et ha'bentching achar seudat lechem. Rabim dvei lashon; yesh im hanchayot zimun vetosafot lechagim.",
        "Un bentcher (birkon) es un librito con Birkat Hamazon y a veces canciones de Shabat y adiciones de bentching. Tener uno en la mesa facilita el bentching tras comidas con pan. Muchos son bilingües; algunos incluyen instrucciones de zimun e inserciones festivas.",
        "Un bentcher (birkon) est un petit livret avec Birkat HaMazon et parfois des chants de Chabbat et additions de bentching. En garder un à table facilite le bentching après les repas avec pain. Beaucoup sont bilingues ; certains incluent instructions de zimoun et insertions de fêtes.",
        "Bentcher (birkon) — malenkaya knizhka s Birkat Hamazon i inogda shabbat-pesen i dobavleniyami k bentching. Derzhat na stole uproshchaet bentching posle khlebных трапез. Mnogie dvuyazychnye; nekotorye s instruktsiyami zimun i prazdnichnymi vstavkami.",
    ),
    "Chazal (חז\"ל) is an acronym for \"our Sages of blessed memory\" — the rabbis of the Mishnah, Talmud, and midrash who transmitted halacha and values. When a source says \"Chazal teach,\" it refers to this collective tradition rather than a single author.": T(
        "Chazal (חז\"ל) hu roshei teivot le\"chachameinu zikhronam livracha\" — rabbanim shel haMishnah, haTalmud veha'midrash she'hעבירu halacha u'mussar. K'she'ha'mekor omair \"Chazal omrim,\" hu ha'masoret ha'klalit ve'lo mechaber yachid.",
        "Chazal (חז\"ל) es un acrónimo de \"nuestros Sabios de bendita memoria\" — los rabinos del Mishná, Talmud y midrash que transmitieron halajá y valores. Cuando una fuente dice \"Chazal enseñan,\" se refiere a esta tradición colectiva, no a un autor único.",
        "Chazal (חז\"ל) est un acronyme pour « nos Sages que leur mémoire soit bénie » — les rabbins de la Michna, du Talmud et du midrash qui ont transmis halakha et valeurs. Quand une source dit « Chazal enseignent, » c'est cette tradition collective, pas un auteur unique.",
        "Chazal (חז\"ל) — akronim «nashi Mudretsy da budet blagoslovena ikh pamyat» — ravviny Mishny, Talmuda i midrasha, peredavshie halakhu i tsennosti. Kogda istochnik govorit «Chazal uchат,» eto kollektivnaya traditsiya, a ne odin avtor.",
    ),
    "Mashiach — Mashiach (Moshiach) is the righteous anointed king from David's line who will rebuild the Temple, gather the exiles, and bring universal knowledge of G-d. Belief in his coming is a foundation of Jewish faith. We pray for redemption daily.": T(
        "Mashiach — Mashiach (Moshiach) hu melech tzadik m'shuch m'zera David she'yivneh et haMikdash, yekabetz et ha'gola ve'yavi da'at et ha'Hashem la'olam kulo. Emunah bi'vo'o hi yesod ha'emunah ha'Yehudit. Mitpalelim le'geulah yom yom.",
        "Mashiach — Mashiach (Moshiaj) es el rey justo ungido del linaje de David que reconstruirá el Templo, reunirá a los exiliados y traerá conocimiento universal de D-s. Creer en su venida es fundamento de la fe judía. Oramos por la redención diariamente.",
        "Machiach — Machiach (Moshiach) est le roi juste oint de la lignée de David qui reconstruira le Temple, rassemblera les exilés et apportera la connaissance universelle de D. Croire en sa venue est un fondement de la foi juive. Nous prions pour la rédemption chaque jour.",
        "Mashiach — Mashiach (Moshiach) — pravednyy pomazannyy tsar iz roda David, kotoryy vosstanovit Khram, soberet izgnannikov i prineset vsемirnoye poznanie V-ga. Vera v ego prikhod — osnova evreyskoy very. My molimsya o geule ezhednevno.",
    ),
    "Psak is a halachic ruling — the answer a qualified posek gives for your real case, not a theoretical debate. Judaism has legitimate range between authorities; your job is to follow your rav's psak consistently rather than shop around for leniencies.": T(
        "Psak hu psak halacha — ha'teshuvah she'posek barur nosen le'mikre shelkha ha'amiti, lo l'vivuch te'oreti. BeYahadut yesh range legitimi bein rabbanim; tachlichem le'kabel psak ha'rav shelkhem be'emtza ve'lo le'chapes kulot.",
        "Psak es una decisión halájica — la respuesta que un posek calificado da a tu caso real, no un debate teórico. El judaísmo tiene rangos legítimos entre autoridades; tu tarea es seguir el psak de tu rav consistentemente en lugar de buscar leniencias.",
        "Psak est une décision halakhique — la réponse qu'un posek qualifié donne pour votre cas réel, pas un débat théorique. Le judaïsme a des écarts légitimes entre autorités ; votre rôle est de suivre le psak de votre rav de façon cohérente plutôt que de chercher des assouplissements.",
        "Psak — halakhicheskoye reshenie — otvet kvalifitsirovannogo poseka na vash realnyy sluchay, a ne teoreticheskiy spor. V iudaizme est dopustimye razlichiya mezhdu autoritetami; vasha zadacha — posledovatelno sledovat psak vashego rava, a ne iskat poslableniya.",
    ),
    "Tzedakah is usually translated \"charity,\" but the root means justice — sharing what G-d entrusted to you with those in need. The sages list it among the pillars on which the world stands; even a small coin given with a full heart is a great mitzvah.": T(
        "Tzedakah meturgemet le\"charity,\" aval ha'shoresh mashma tzedek — le'chalek et mah she'hafkid Hashem etkhem im ha'needyim. Ha'chachamim me'anyenim otah bein amudei ha'olam; afilu pruta she'nitanah be'lev shalem hi mitzvah gedolah.",
        "Tzedaká se traduce usualmente como \"caridad,\" pero la raíz significa justicia — compartir lo que D-s te confió con quienes lo necesitan. Los sabios la incluyen entre los pilares del mundo; incluso una moneda pequeña dada con corazón pleno es una gran mitzvá.",
        "Tsedaka se traduit souvent par « charité, » mais la racine signifie justice — partager ce que D. vous a confié avec les nécessiteux. Les sages la comptent parmi les piliers du monde ; même une petite pièce donnée de bon cœur est une grande mitzvah.",
        "Tzedakah obychno perevodyat kak «blagotvoritelnost,» no koren znachit spravedlivost — delitsya tem, chto V-s vam vveril, s nuzhdayushchimisya. Mudretsy schitayut ee odним iz stolpov mira; dazhe malaya moneta, dannaya ot vsego serdtsa — velikaya mitzvah.",
    ),
    "Baal Shem Tov — The Baal Shem Tov (Rabbi Israel ben Eliezer, c. 1700–1760) founded the Chasidic movement, teaching that every Jew can serve G-d with joy and that divine presence fills all creation. Chabad traces its spiritual lineage to his disciples.": T(
        "Baal Shem Tov — HaBaal Shem Tov (Rabbi Yisrael ben Eliezer, c. 1700–1760) yisad et tnu'at haChasidut, melamed she'kol Yehudi yachol la'avod et ha'Hashem be'simcha ve'she'hashra'at haShechinah mamla et kol ha'beriah. Chabad omeket et sharshelta ha'ruchanit le'talmidav.",
        "Baal Shem Tov — El Baal Shem Tov (Rabí Israel ben Eliezer, c. 1700–1760) fundó el movimiento jasídico, enseñando que todo judío puede servir a D-s con alegría y que la presencia divina llena toda la creación. Jabad remonta su linaje espiritual a sus discípulos.",
        "Baal Shem Tov — Le Baal Shem Tov (Rabbi Israel ben Eliezer, c. 1700–1760) a fondé le mouvement hassidique, enseignant que tout Juif peut servir D. avec joie et que la présence divine remplit toute la création. Habad trace sa lignée spirituelle à ses disciples.",
        "Baal Shem Tov — Baal Shem Tov (Rav Yisrael ben Eliezer, ok. 1700–1760) osnoval khasidskoe dvizhenie, uchа ya, chto kazhdyy evrey mozhet sluzhit V-gu s radostyu i chto bozhestvennoe prisutstvie napolnyaet vse tvorenie. Chabad vedet dukhovnuyu liniyu k ego uchenikam.",
    ),
    "daven — Daven (davening) means to pray. You 'daven' the daily services (Shacharit, Mincha, Maariv). The word is Yiddish-derived Ashkenazi slang but widely understood. People often say \"daven Shacharit\" for a service and \"daven\" for praying in general.": T(
        "daven — Daven (davening) mashma le'hitpalel. 'Daven' et hatefillot hayom yom (Shacharit, Mincha, Maariv). Ha'milah hi slang Ashkenazi miYiddish aval me'uvetet. Omrim 'daven Shacharit' le'tefillah u'daven' le'hitpallel b'chlal.",
        "daven — Daven (davening) significa orar. Se 'daven' los servicios diarios (Shajarit, Minjá, Maariv). La palabra es jerga ashkenazí del yiddish pero ampliamente entendida. Se dice \"daven Shacharit\" para un servicio y \"daven\" para orar en general.",
        "daven — Daven (davening) signifie prier. On « daven » les offices quotidiens (Shacharit, Min'ha, Maariv). Le mot est un argot ashkénaze du yiddish mais largement compris. On dit « daven Shacharit » pour un office et « daven » pour prier en général.",
        "daven — Daven (davening) oznachaet molitsya. 'Daven' — ezhednevnye sluzhby (Shacharit, Mincha, Maariv). Slovo iz ashkenazskogo zhargona na idishe, no shiroko ponimaetsya. Govoryat «daven Shacharit» o sluzhbe i «daven» o molitve voobshche.",
    ),
}
