# -*- coding: utf-8 -*-
from rest_data import T

ENTRIES = {
    "Melave Malka — escorting the Shabbat Queen — Motzei Shabbat meal (מְלַוֶּה מַלְכָּה) through dawn Sunday": T(
        "Melave Malka — melave et malkat haShabbat — seudat Motzei Shabbat (מְלַוֶּה מַלְכָּה) ad shacharit yom rishon",
        "Melave Malka — escoltar a la Reina del Shabat — comida de Motzei Shabat (Melave Malka) hasta el amanecer del domingo",
        "Melave Malka — escorter la Reine de Chabbat — repas de Motzei Chabbat (Melave Malka) jusqu'a l'aube du dimanche",
        "Melave Malka — провожать Shabbat Queen — трапеза Motzei Shabbat (Melave Malka) до рассвета воскресенья",
    ),
    'Zachor — "remember" from the Exodus version of the Ten Commandments telling the Jews to remember Shabbat': T(
        'Zachor — "zachor" min nusach Shemot shel aseret hadibrot lehazkir et Yisrael lezachor et haShabbat',
        'Zachor — "recordar" de la version del Exodo de los Diez Mandamientos que ordena recordar el Shabat',
        'Zachor — "souviens-toi" de la version Exode des Dix Commandements ordonnant de se souvenir de Chabbat',
        'Zachor — "remember" iz varianta Exodus Desyati zapovedey, povelivayushchego pomnit Shabbat',
    ),
    "Spend the next 30 seconds thanking G-d for everything you could possibly thank Him for. - Submitted by MB": T(
        "Bilu 30 shniyot lehodot laHashem al kol ma she'efshar lehodot lo. — Nishlach al yedei MB",
        "Pasa los proximos 30 segundos agradeciendo a D-s por todo lo que puedas agradecerle. — Enviado por MB",
        "Passez les 30 prochaines secondes a remercier D. pour tout ce que vous pouvez lui remercier. — Soumis par MB",
        "Potratite sleduyushchie 30 sekund, blagodarya V-ga za vse, za chto mozhno poblagodarit. — Ot MB",
    ),
    "colloquial marker for halachic nightfall (tzeit); actual timing varies slightly by community and location": T(
        "three stars — siman amami le'tzeit halakhti; hazman ha'amiti meshutaf kmo zeh bein kehillot u'mekomot",
        "marcador coloquial del anochecer halajico (tzeit); el momento exacto varia segun comunidad y lugar",
        "marqueur courant de la nuit halakhique (tzeit) ; le moment exact varie selon communaute et lieu",
        "razgovornyy marker halakhicheskogo nasta (tzeit); tochnoe vremya nemnogo razlichayetsya po obshchinam",
    ),
    "Fast of the Firstborn on Erev Pesach (many break or nullify the fast with the seudat mitzvah after a siyum)": T(
        "Taanit Bechorot beErev Pesach (rabbim shovrim o mevatelim et hatzom im seudat mitzvah le'achar siyum)",
        "Ayuno de los primogenitos en Erev Pesaj (muchos lo interrumpen o anulan con la seudat mitzvah tras un siyum)",
        "Jeune des premiers-nes a Erev Pessah (beaucoup l'interrompent ou l'annulent avec la seudat mitzvah apres un siyoum)",
        "Post pervorodnykh v Erev Pesach (mnogie preryvayut ili otmenyayut post seudat mitzvah posle siyum)",
    ),
    "The klaf is the special kosher parchment on which scribes write Torah scrolls, mezuzots, tefillin scrolls, etc.": T(
        "Klaf hu klaf kosher meyuchad she'alav kotvim sofrim sefer Torah, mezuzot, klaf tefillin v'ch.",
        "El klaf es el pergamino kosher especial sobre el que los escribas escriben rollos de Torá, mezuzot, klaf de tefilín, etc.",
        "Le klaf est le parchemin casher special sur lequel les scribes ecrivent rouleaux de Torah, mezouzot, klaf de tefilin, etc.",
        "Klaf — osobый kosher-pergament, na kotorom soferim pisayut svitki Tory, mezuzot, klaf tefillin i t.d.",
    ),
    "Try to make peace between two people you know who are currently arguing. The reward for doing so is very great!": T(
        "Nasa'u la'asot shalom bein shnayim she'atem makirim she'nimatzim be'machloket. Hasachar le'kach gadol me'od!",
        "Intenta hacer paz entre dos personas que conoces que estan discutiendo. La recompensa por hacerlo es muy grande!",
        "Essayez de faire la paix entre deux personnes que vous connaissez qui se disputent. La recompense est tres grande !",
        "Poprobuyte primirit dvukh znakomykh, kotoryye ssoryatsya. Nagrada za eto ochen velika!",
    ),
    "Ashkenaz — Full Hallel (Chanukah):\nRecite the blessings before Full Hallel as on Chanukah (Mishnah Berurah 422:8).": T(
        "Ashkenaz — Full Hallel (Chanukah):\nLe'omar brachot lifnei Full Hallel kmo beChanukah (Mishnah Berurah 422:8).",
        "Ashkenaz — Full Hallel (Janucá):\nRecita las bendiciones antes del Full Hallel como en Janucá (Mishnah Berurah 422:8).",
        "Ashkenaz — Full Hallel (Hanoucca) :\nRecitez les benedictions avant le Full Hallel comme a Hanoucca (Mishna Beroura 422:8).",
        "Ashkenaz — Full Hallel (Hanukah):\nProiznesite blagosloveniya pered Full Hallel kak na Hanuke (Mishnah Berurah 422:8).",
    ),
    "Got some spare time? Visit someone who's sick. The Talmud (Nedarim 39b) says this removes 1/60th of their illness!": T(
        "Yesh lachem zman panui? Bkru et mi she'choleh. HaTalmud (Nedarim 39b) omershe'zeh m'paset echad mi'shishim me'choleihu!",
        "Tienes tiempo libre? Visita a alguien enfermo. El Talmud (Nedarim 39b) dice que esto quita 1/60 de su enfermedad!",
        "Vous avez du temps libre ? Visitez quelqu'un de malade. Le Talmud (Nedarim 39b) dit que cela retire 1/60 de la maladie !",
        "Est svobodnoe vremya? Naveshchayte bolnogo. Talmud (Nedarim 39b) govorit, chto eto ubirayet 1/60 bolezni!",
    ),
    "tallit katan — small four-cornered garment with tzitzit, worn generally over or under a shirt per community custom": T(
        "tallit katan — beged katan ba'al arba kenafot im tzitzit, nilbash mi'it le'mata o mi'it le'ma'la lefi minhag",
        "tallit katan — prenda pequena de cuatro esquinas con tzitzit, usada sobre o bajo la camisa segun la costumbre",
        "tallit katan — petit vetement a quatre coins avec tsitsit, porte au-dessus ou en dessous de la chemise selon la coutume",
        "tallit katan — nebolshaya chetyrekhugolnaya odezhda s tzitzit, nosimaya nad ili pod rubashkoy po obychayu",
    ),
    "Shomer Daltot Yisrael — Guardian of the doors of Israel (acronym Shin-Dalet-Yod (one of Hashem's names) on mezuzah)": T(
        "Shomer Daltot Yisrael — Shomer Daltot Yisrael (roshei teivot Shin-Dalet-Yod, shem miShemot Hashem, al hamezuzah)",
        "Shomer Daltot Yisrael — Guardian de las puertas de Israel (acronimo Shin-Dalet-Yod, uno de los nombres de Hashem, en la mezuza)",
        "Shomer Daltot Yisrael — Gardien des portes d'Israel (acronyme Shin-Dalet-Yod, un des noms de Hashem, sur la mezouza)",
        "Shomer Daltot Yisrael — Khranitel dverey Izrailya (akronim Shin-Dalet-Yod, odno iz imen Hashem, na mezuzah)",
    ),
    "Pesach meets Shabbat this year — some steps happen today or tonight (before tomorrow's erev Pesach checklist):\n\n$body": T(
        "Pesach meets Shabbat this year — some steps happen today or tonight (before tomorrow's erev Pesach checklist):\n\n$body",
        "Pesaj coincide con Shabat este ano — algunos pasos ocurren hoy o esta noche (antes de la lista de manana de erev Pesaj):\n\n$body",
        "Pessah tombe avec Chabbat cette annee — certaines etapes ont lieu aujourd'hui ou ce soir (avant la liste de demain d'erev Pessah) :\n\n$body",
        "Pesach v etom godu vpadaet na Shabbat — nekotoryye shagi proiskhodyat segodnya ili segodnya vecherom (do spiska zavtra erev Pesach):\n\n$body",
    ),
    "Sephardi — Full Hallel (Chanukah):\nRecite the blessings before Full Hallel as on Chanukah (Shulchan Arukh O.C. 422:2).": T(
        "Sephardi — Full Hallel (Chanukah):\nLe'omar brachot lifnei Full Hallel kmo beChanukah (Shulchan Arukh O.C. 422:2).",
        "Sefardi — Full Hallel (Januca):\nRecita las bendiciones antes del Full Hallel como en Januca (Shulchan Aruj O.C. 422:2).",
        "Sepharadi — Full Hallel (Hanoucca) :\nRecitez les benedictions avant le Full Hallel comme a Hanoucca (Choulhan Aroukh O.C. 422:2).",
        "Sephardi — Full Hallel (Hanukah):\nProiznesite blagosloveniya pered Full Hallel kak na Hanuke (Shulchan Arukh O.C. 422:2).",
    ),
    "klaf — The klaf is the special kosher parchment on which scribes write Torah scrolls, mezuzots, tefillin scrolls, etc.": T(
        "klaf — Klaf hu klaf kosher meyuchad she'alav kotvim sofrim sefer Torah, mezuzot, klaf tefillin v'ch.",
        "klaf — El klaf es el pergamino kosher especial sobre el que los escribas escriben rollos de Tora, mezuzot, klaf de tefilin, etc.",
        "klaf — Le klaf est le parchemin casher special sur lequel les scribes ecrivent rouleaux de Torah, mezouzot, klaf de tefilin, etc.",
        "klaf — Osobый kosher-pergament, na kotorom soferim pisayut svitki Tory, mezuzot, klaf tefillin i t.d.",
    ),
    "Kiddush sanctifies Shabbat or Yom Tov over wine (or grape juice, or possibly bread/other drinks if in need; ask a rav).": T(
        "Kiddush mekadesh et haShabbat o Yom Tov al yayin (o michyat anavim, o efshar al lechem/mashkei acherim be'tzorach; sha'alu rav).",
        "Kiddush santifica Shabat o Yom Tov sobre vino (o jugo de uva, o posiblemente pan/otras bebidas si es necesario; consulta a un rav).",
        "Kiddouch sanctifie Chabbat ou Yom Tov sur le vin (ou jus de raisin, ou possiblement pain/autres boissons si besoin ; demandez a un rav).",
        "Kiddush osvyashchaet Shabbat ili Yom Tov nad vinom (ili vinogradnym sokom, vozmozhno khlebom/drugimi napitkami pri nuzhde; sprosite rava).",
    ),
    "three stars — colloquial marker for halachic nightfall (tzeit); actual timing varies slightly by community and location": T(
        "three stars — siman amami le'tzeit halakhti; hazman ha'amiti meshutaf kmo zeh bein kehillot u'mekomot",
        "tres estrellas — marcador coloquial del anochecer halajico (tzeit); el momento exacto varia segun comunidad y lugar",
        "trois etoiles — marqueur courant de la nuit halakhique (tzeit) ; le moment exact varie selon communaute et lieu",
        "tri zvezdy — razgovornyy marker halakhicheskogo nasta (tzeit); tochnoe vremya razlichayetsya po obshchinam",
    ),
    "Chabad — Full Hallel (Chanukah):\nFollow Ashkenazic custom — recite the blessings before Full Hallel (Alter Rebbe's Siddur).": T(
        "Chabad — Full Hallel (Chanukah):\nK'minhag Ashkenaz — le'omar brachot lifnei Full Hallel (Siddur Alter Rebbe).",
        "Jabad — Full Hallel (Januca):\nSigue la costumbre ashkenazi — recita las bendiciones antes del Full Hallel (Siddur del Alter Rebbe).",
        "Habad — Full Hallel (Hanoucca) :\nSuivez la coutume ashkenaze — recitez les benedictions avant le Full Hallel (Siddour Alter Rebbe).",
        "Chabad — Full Hallel (Hanukah):\nSleduyte ashkenazskomu obychayu — proiznesite blagosloveniya pered Full Hallel (Siddur Alter Rebbe).",
    ),
    "Taanit Bechorot — Fast of the Firstborn on Erev Pesach (many break or nullify the fast with the seudat mitzvah after a siyum)": T(
        "Taanit Bechorot — Tzom habechorot beErev Pesach (rabbim shovrim o mevatelim et hatzom im seudat mitzvah le'achar siyum)",
        "Taanit Bechorot — Ayuno de los primogenitos en Erev Pesaj (muchos lo interrumpen o anulan con la seudat mitzvah tras un siyum)",
        "Ta'anit Bechorot — Jeune des premiers-nes a Erev Pessah (beaucoup l'interrompent ou l'annulent avec la seudat mitzvah apres un siyoum)",
        "Taanit Bechorot — Post pervorodnykh v Erev Pesach (mnogie preryvayut post seudat mitzvah posle siyum)",
    ),
    "This year, Shabbat is Erev $chagName — $chagName begins tonight at nightfall (Motzei Shabbat). This doesn't happen every year.": T(
        "This year, Shabbat is Erev $chagName — $chagName begins tonight at nightfall (Motzei Shabbat). This doesn't happen every year.",
        "Este ano, Shabat es Erev $chagName — $chagName comienza esta noche al anochecer (Motzei Shabat). Esto no ocurre todos los anos.",
        "Cette annee, Chabbat est Erev $chagName — $chagName commence ce soir a la tombee de la nuit (Motzei Chabbat). Cela n'arrive pas chaque annee.",
        "V etom godu Shabbat — Erev $chagName — $chagName nachinayetsya segodnya vecherom (Motzei Shabbat). Eto sluchayetsya ne kazhdyy god.",
    ),
    "on this day of the New Moon\n            on this day of the Festival of Matzot\n            on this day of the Festival of Sukkot": T(
        "bayom hachodesh hazeh\n            beyom chag hamatzot hazeh\n            beyom chag hasukkot hazeh",
        "En este dia de Rosh Jodesh\n            en este dia de la Fiesta de los Matzot\n            en este dia de la Fiesta de Sucot",
        "En ce jour de Roch 'Hodech\n            en ce jour de la Fete des Matsot\n            en ce jour de la Fete de Souccot",
        "V etot den novomesyachiya\n            v etot den prazdnika matzot\n            v etot den prazdnika Sukkot",
    ),
    "Shamayim means Heaven or the skies — in yirat Shamayim (awe of Heaven) it means living with awareness that G-d sees all actions.": T(
        "Shamayim — Shamayim omershamayim o raki'a; be'yirat Shamayim zeh chayim im moda'ut she'Hashem ro'eh et kol ma'asim.",
        "Shamayim significa Cielo o los cielos — en yirat Shamayim (temor del Cielo) significa vivir con conciencia de que D-s ve todas las acciones.",
        "Shamayim signifie Ciel ou les cieux — dans yirat Shamayim (crainte du Ciel) cela signifie vivre avec conscience que D. voit toutes les actions.",
        "Shamayim oznachaet Nebo ili nebesa — v yirat Shamayim eto zhizn s osoznaniem, chto V-gh vidit vse postupki.",
    ),
    "Kiddush — Kiddush sanctifies Shabbat or Yom Tov over wine (or grape juice, or possibly bread/other drinks if in need; ask a rav).": T(
        "Kiddush — Kiddush mekadesh et haShabbat o Yom Tov al yayin (o michyat anavim, o efshar al lechem/mashkei acherim be'tzorach; sha'alu rav).",
        "Kiddush — Kiddush santifica Shabat o Yom Tov sobre vino (o jugo de uva, o posiblemente pan/otras bebidas si es necesario; consulta a un rav).",
        "Kiddouch — Kiddouch sanctifie Chabbat ou Yom Tov sur le vin (ou jus de raisin, ou possiblement pain/autres boissons si besoin ; demandez a un rav).",
        "Kiddush — Kiddush osvyashchaet Shabbat ili Yom Tov nad vinom (ili vinogradnym sokom; sprosite rava pri nuzhde).",
    ),
    "This year, Shabbat is Erev Rosh Hashana — Rosh Hashana begins tonight at nightfall (Motzei Shabbat). This doesn't happen every year.": T(
        "This year, Shabbat is Erev Rosh Hashana — Rosh Hashana begins tonight at nightfall (Motzei Shabbat). This doesn't happen every year.",
        "Este ano, Shabat es Erev Rosh Hashana — Rosh Hashana comienza esta noche al anochecer (Motzei Shabat). Esto no ocurre todos los anos.",
        "Cette annee, Chabbat est Erev Roch Hachana — Roch Hachana commence ce soir a la tombee de la nuit (Motzei Chabbat). Cela n'arrive pas chaque annee.",
        "V etom godu Shabbat — Erev Rosh Hashana — Rosh Hashana nachinayetsya segodnya vecherom (Motzei Shabbat). Eto sluchayetsya ne kazhdyy god.",
    ),
    "Get a Chumash and open to a random page and verse. whatever verse you land on, it's supposed to be a message from G-d - Submitted by HB": T(
        "Kchu Chumash u'ftchu le'ad amud u'pasuk achakai. Ha'pasuk she'tipgu bo amur lihyot meshima me'Hashem — Nishlach al yedei HB",
        "Toma un Jumash y abrelo en una pagina y versiculo al azar. El versiculo en el que caigas se supone que es un mensaje de D-s — Enviado por HB",
        "Prenez un Houmach et ouvrez a une page et un verset au hasard. Le verset sur lequel vous tombez est cense etre un message de D. — Soumis par HB",
        "Voz'mite Humash i otkroyte na sluchaynoy stranitse i stikhe. Stikh, na kotoryy popadete, dolzhen byt poslaniyem ot V-ga — Ot HB",
    ),
    "matzah balls; those who observe the stringency of not eating gebrochts do not eat kneidlach on Pesach until the 8th day in the diaspora": T(
        "kneidlach — kneydlach; hamachmirim al gebrokts lo ochlim kneidlach bePesach ad hayom hashmini ba'golah",
        "bolas de matza; quienes observan la stringencia de no comer gebrokts no comen kneidlach en Pesaj hasta el 8.o dia en la diaspora",
        "boulettes de matza ; ceux qui observent la stringence de ne pas manger gebrokts ne mangent pas kneidlach a Pessah jusqu'au 8e jour en diaspora",
        "matzah-klyotsy; soblyudayushchie strogoct ne yest gebrokts ne yedyat kneidlach na Pesach do 8-go dnya v galute",
    ),
    "Chabad — Half Hallel:\nFollow Ashkenazic custom — recite the blessings before Half Hallel (Alter Rebbe's Siddur; ask your rav if unsure).": T(
        "Chabad — Half Hallel:\nK'minhag Ashkenaz — le'omar brachot lifnei Half Hallel (Siddur Alter Rebbe; sha'alu et ravchem im lo barur).",
        "Jabad — Half Hallel:\nSigue la costumbre ashkenazi — recita las bendiciones antes del Half Hallel (Siddur del Alter Rebbe; consulta a tu rav si tienes dudas).",
        "Habad — Half Hallel :\nSuivez la coutume ashkenaze — recitez les benedictions avant le Half Hallel (Siddour Alter Rebbe ; demandez a votre rav si incertain).",
        "Chabad — Half Hallel:\nSleduyte ashkenazskomu obychayu — proiznesite blagosloveniya pered Half Hallel (Siddur Alter Rebbe; sprosite rava esli ne uvereny).",
    ),
    "This is the knobby, stem-like protrusion that extends from the top of the etrog (opposite the branch). The shoshanta rests on top of it.": T(
        "Pitom — zeh habelbul hazotef min rosh ha'etrog (neged ha'anaf). Ha'shoshanta nohevet alav.",
        "Este es el protuberancia nodular en forma de tallo que se extiende desde la parte superior del etrog (opuesta a la rama). La shoshanta descansa sobre ella.",
        "C'est la protuberance nodulaire en forme de tige qui s'etend du sommet de l'etrog (opposee a la branche). La shoshanta repose dessus.",
        "Eto bugraatoe steblevidnoe vystuplenie na vershine etrog (protiv vetki). Shoshanta pokoyetsya na nem.",
    ),
    "Shabbat candles before sunset; weekday Erev Yom Tov before sunset; Motzei Shabbat going into a Yom Tov at tzeit from a pre-existing flame": T(
        "Hadlakat nerot — nerot Shabbat lifnei shkia; Erev Yom Tov bechol yom lifnei shkia; Motzei Shabbat leYom Tov be'tzeit me'ner kayam",
        "Velas de Shabat antes del atardecer; Erev Yom Tov entre semana antes del atardecer; Motzei Shabat entrando en Yom Tov al tzeit desde llama preexistente",
        "Bougies de Chabbat avant le coucher du soleil ; Erev Yom Tov en semaine avant le coucher ; Motzei Chabbat entrant dans Yom Tov au tzeit d'une flamme existante",
        "Shabbat-svechi do zakata; budniy Erev Yom Tov do zakata; Motzei Shabbat v Yom Tov v tzeit s suschestvuyushchego ognya",
    ),
    'Add Yaaleh V\'yavo in the Mincha Amidah on Rosh Chodesh — in the blessing Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha("Mincha")}': T(
        'Add Yaaleh V\'yavo in the Mincha Amidah on Rosh Chodesh — in the blessing Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha("Mincha")}',
        'Anade Yaaleh V\'yavo en el Amidá de Minjá en Rosh Jodesh — en la bendición Retzei (Avodá).\n\n${yaalehVyavoForgotShacharitOrMincha("Mincha")}',
        'Ajoutez Yaaleh V\'yavo dans l\'Amidah de Min\'ha a Roch \'Hodech — dans la benediction Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha("Mincha")}',
        'Dobavte Yaaleh V\'yavo v Mincha Amidah v Rosh Chodesh — v brakhe Retzei (Avodah).\n\n${yaalehVyavoForgotShacharitOrMincha("Mincha")}',
    ),
    "counting period between 2nd day of Pesach and Shavuot; mourning customs and when they end vary by minhag (Ashkenaz, Sephard, Chabad, etc.)": T(
        "Sefirah — sfirat ha'omer bein yom sheni shel Pesach leShavuot; minhagei evell u'motar ha'evell meshutafim lefi minhag (Ashkenaz, Sefarad, Chabad v'ch.)",
        "periodo de conteo entre el 2.o dia de Pesaj y Shavuot; costumbres de luto y su fin varian segun minhag (Ashkenaz, Sefarad, Jabad, etc.)",
        "periode de compte entre le 2e jour de Pessah et Chavouot ; coutumes de deuil et leur fin varient selon minhag (Ashkenaz, Sepharad, Habad, etc.)",
        "period scheta mezhdu 2-m dnyom Pesach i Shavuot; obychai skorbi i i okonchanie razlichayutsya po minhag (Ashkenaz, Sephard, Chabad i t.d.)",
    ),
    "Mishloach manot are ready-to-eat food gifts sent to at least one Jewish friend on Purim day — minimally two different foods in one package.": T(
        "Mishloach manot — matanot ochel mukhan le'achila le'achad me're'im Yehudim bePurim — le'minimum shtei ma'achalot shonot be'ariza achat.",
        "Mishloach manot son regalos de comida lista para comer enviados a al menos un amigo judio en Purim — minimo dos alimentos diferentes en un paquete.",
        "Mishloach manot sont des cadeaux alimentaires prets a manger envoyes a au moins un ami juif a Pourim — minimum deux aliments differents dans un colis.",
        "Mishloach manot — gotovye edible podarki khotya by odnomu evreyskomu drugu v Purim — minimum dva raznykh produkta v odnoy upakovke.",
    ),
    "Shamayim — Shamayim means Heaven or the skies — in yirat Shamayim (awe of Heaven) it means living with awareness that G-d sees all actions.": T(
        "Shamayim — Shamayim omershamayim o raki'a; be'yirat Shamayim zeh chayim im moda'ut she'Hashem ro'eh et kol ma'asim.",
        "Shamayim — Shamayim significa Cielo o los cielos — en yirat Shamayim significa vivir con conciencia de que D-s ve todas las acciones.",
        "Shamayim — Shamayim signifie Ciel ou les cieux — dans yirat Shamayim cela signifie vivre avec conscience que D. voit toutes les actions.",
        "Shamayim — Shamayim oznachaet Nebo — v yirat Shamayim eto zhizn s osoznaniem, chto V-gh vidit vse postupki.",
    ),
    'Rabbi is the English word for a Jewish spiritual leader with rabbinical ordination (semicha). From Hebrew Ribbi ("my master" or "my teacher").': T(
        "Rabbi — Milah Anglit lemanhig ruchani Yehudi im semicha. MiIvrit Ribbi (rabi sheli o moreh sheli).",
        'Rabbi es la palabra inglesa para un lider espiritual judio con ordenacion rabinica (semija). Del hebreo Ribbi ("mi maestro" o "mi rabino").',
        'Rabbi est le mot anglais pour un leader spirituel juif avec ordination rabbinique (semikha). De l\'hebreu Ribbi ("mon maitre" ou "mon enseignant").',
        'Rabbi — angliyskoe slovo dlya evreyskogo dukhovnogo lidera s semicha. Ot ivrita Ribbi ("moy uchitel").',
    ),
    "Blessings before reading:\n• Al mikra megillah\n• She'asa nissim\n• Shehecheyanu (recited on the first night; Ashkenazim recite it by day as well)": T(
        "Brachot lifnei kri'a:\n• Al mikra megillah\n• She'asa nissim\n• Shehecheyanu (ne'emar balaila harishon; Ashkenazim omrim gam ba'yom)",
        "Bendiciones antes de la lectura:\n• Al mikra megillah\n• She'asa nissim\n• Shehecheyanu (recitada la primera noche; ashkenazim tambien la recitan de dia)",
        "Benedictions avant la lecture :\n• Al mikra megillah\n• She'asa nissim\n• Shehecheyanu (recitee la premiere nuit ; Ashkenazim aussi le jour)",
        "Blagosloveniya pered chteniem:\n• Al mikra megillah\n• She'asa nissim\n• Shehecheyanu (v pervyy vecher; ashkenazy takzhe dnem)",
    ),
    "This year, tomorrow (Shabbat) is Erev $chagName — $chagName begins tomorrow night at nightfall (Motzei Shabbat). This doesn't happen every year.": T(
        "This year, tomorrow (Shabbat) is Erev $chagName — $chagName begins tomorrow night at nightfall (Motzei Shabbat). This doesn't happen every year.",
        "Este ano, manana (Shabat) es Erev $chagName — $chagName comienza manana noche al anochecer (Motzei Shabat). Esto no ocurre todos los anos.",
        "Cette annee, demain (Chabbat) est Erev $chagName — $chagName commence demain soir a la tombee de la nuit (Motzei Chabbat). Cela n'arrive pas chaque annee.",
        "V etom godu zavtra (Shabbat) — Erev $chagName — $chagName nachinayetsya zavtra vecherom (Motzei Shabbat). Eto sluchayetsya ne kazhdyy god.",
    ),
    "pitom — This is the knobby, stem-like protrusion that extends from the top of the etrog (opposite the branch). The shoshanta rests on top of it.": T(
        "pitom — zeh habelbul hazotef min rosh ha'etrog (neged ha'anaf). Ha'shoshanta nohevet alav.",
        "pitom — Esta es la protuberancia nodular en forma de tallo que se extiende desde la parte superior del etrog (opuesta a la rama). La shoshanta descansa sobre ella.",
        "pitom — C'est la protuberance nodulaire en forme de tige qui s'etend du sommet de l'etrog (opposee a la branche). La shoshanta repose dessus.",
        "pitom — Bugraatoe steblevidnoe vystuplenie na vershine etrog (protiv vetki). Shoshanta pokoyetsya na nem.",
    ),
    "Priestly blessing; recited daily by everyone in Israel and by Sephardim worldwide; usually recited only on festivals by Ashkenazim in the Diaspora": T(
        "Birkat Kohanim — ne'emar yom yom le'chol ba'aretz u'leSefarad ba'olam; Ashkenazim ba'golah le'rov rak bechagim",
        "Bendicion sacerdotal; recitada diariamente por todos en Israel y por sefardies en todo el mundo; generalmente solo en fiestas por ashkenazim en la Diáspora",
        "Benediction sacerdotale ; recitee quotidiennement par tous en Israel et par les Sepharadim dans le monde ; generalement seulement aux fetes par les Ashkenazim en Diaspora",
        "Svyashchennicheskoe blagoslovenie; ezhednevno v Izraile i u sefardov v mire; ashkenazy v galute obychno tolko na prazdniki",
    ),
    "kneidlach — matzah balls; those who observe the stringency of not eating gebrochts do not eat kneidlach on Pesach until the 8th day in the diaspora": T(
        "kneidlach — kneydlach; hamachmirim al gebrokts lo ochlim kneidlach bePesach ad hayom hashmini ba'golah",
        "kneidlach — bolas de matza; quienes observan no comer gebrokts no comen kneidlach en Pesaj hasta el 8.o dia en la diaspora",
        "kneidlach — boulettes de matza ; ceux qui observent gebrokts ne mangent pas kneidlach a Pessah jusqu'au 8e jour en diaspora",
        "kneidlach — matzah-klyotsy; soblyudayushchie gebrokts ne yedyat kneidlach na Pesach do 8-go dnya v galute",
    ),
    "Sefirah — counting period between 2nd day of Pesach and Shavuot; mourning customs and when they end vary by minhag (Ashkenaz, Sephard, Chabad, etc.)": T(
        "Sefirah — sfirat ha'omer bein yom sheni shel Pesach leShavuot; minhagei evell u'motar ha'evell meshutafim lefi minhag",
        "Sefirah — periodo de conteo entre el 2.o dia de Pesaj y Shavuot; costumbres de luto varian segun minhag",
        "Sefira — periode de compte entre le 2e jour de Pessah et Chavouot ; coutumes de deuil varient selon minhag",
        "Sefirah — period scheta ot 2-go dnya Pesach do Shavuot; obychai skorbi razlichayutsya po minhag",
    ),
    "33rd day of the Omer; mourning eased in many communities; Chabad keeps haircut restrictions until Shavuot except for a 3 year old boy's first haircut": T(
        "Lag BaOmer — yom lamed-gimel ba'Omer; hefer evell b'kehillot rabot; Chabad shomerim al tisporet ad Shavuot chutz mi'tisporet rishona leben ben gimel",
        "33.o dia del Omer; luto aliviado en muchas comunidades; Jabad mantiene restricciones de corte hasta Shavuot excepto primer corte de nino de 3 anos",
        "33e jour de l'Omer ; deuil allege dans de nombreuses communautes ; Habad garde restrictions de coupe jusqu'a Chavouot sauf premiere coupe a 3 ans",
        "33-y den Omera; skorb osvlablenayetsya; Chabad soblyudayet zapret strizhki do Shavuot krome pervoy strizhki trekhletnego",
    ),
    'Rabbi — Rabbi is the English word for a Jewish spiritual leader with rabbinical ordination (semicha). From Hebrew Ribbi ("my master" or "my teacher").': T(
        "Rabbi — Milah Anglit lemanhig ruchani Yehudi im semicha. MiIvrit Ribbi (rabi sheli o moreh sheli).",
        'Rabbi — Rabbi es la palabra inglesa para un lider espiritual judio con ordenacion rabinica (semija). Del hebreo Ribbi ("mi maestro" o "mi rabino").',
        'Rabbi — Rabbi est le mot anglais pour un leader spirituel juif avec ordination rabbinique (semikha). De l\'hebreu Ribbi ("mon maitre" ou "mon enseignant").',
        'Rabbi — Angliyskoe slovo dlya evreyskogo dukhovnogo lidera s semicha. Ot ivrita Ribbi ("moy uchitel").',
    ),
    "This year, tomorrow (Shabbat) is Erev Rosh Hashana — Rosh Hashana begins tomorrow night at nightfall (Motzei Shabbat). This doesn't happen every year.": T(
        "This year, tomorrow (Shabbat) is Erev Rosh Hashana — Rosh Hashana begins tomorrow night at nightfall (Motzei Shabbat). This doesn't happen every year.",
        "Este ano, manana (Shabat) es Erev Rosh Hashana — Rosh Hashana comienza manana noche al anochecer (Motzei Shabat). Esto no ocurre todos los anos.",
        "Cette annee, demain (Chabbat) est Erev Roch Hachana — Roch Hachana commence demain soir (Motzei Chabbat). Cela n'arrive pas chaque annee.",
        "V etom godu zavtra (Shabbat) — Erev Rosh Hashana — Rosh Hashana nachinayetsya zavtra vecherom (Motzei Shabbat). Eto sluchayetsya ne kazhdyy god.",
    ),
    "Shul (synagogue) is the community house of prayer, Torah, and chesed. Beyond services, it often hosts classes, youth programs, and charity organizations.": T(
        "Shul — beit haknesset hu beit tefillah, Torah vechesed shel ha'kehillah. Milevad tefillot, hu me'arach shiurim, tochniyot no'ar ve'irgunim le'tzedakah.",
        "Shul (sinagoga) es la casa comunitaria de oracion, Torá y chesed. Ademas de servicios, suele ofrecer clases, programas juveniles y organizaciones de caridad.",
        "Shul (synagogue) est la maison communautaire de priere, Torah et chesed. Au-dela des offices, elle accueille cours, programmes jeunesse et organisations de tsedaka.",
        "Shul (sinagoga) — obshchinnyy dom molitvy, Tory i chesed. Pomimo sluzhb — zanyatiya, molodezhnye programmy i blagotvoritelnye organizatsii.",
    ),
    "candle lighting — Shabbat candles before sunset; weekday Erev Yom Tov before sunset; Motzei Shabbat going into a Yom Tov at tzeit from a pre-existing flame": T(
        "Hadlakat nerot — nerot Shabbat lifnei shkia; Erev Yom Tov bechol yom lifnei shkia; Motzei Shabbat leYom Tov be'tzeit me'ner kayam",
        "Encendido de velas — velas de Shabat antes del atardecer; Erev Yom Tov entre semana antes del atardecer; Motzei Shabat a Yom Tov al tzeit desde llama preexistente",
        "Allumage des bougies — bougies de Chabbat avant le coucher ; Erev Yom Tov en semaine ; Motzei Chabbat entrant dans Yom Tov au tzeit d'une flamme existante",
        "Zazhiganie svechey — Shabbat-svechi do zakata; budniy Erev Yom Tov do zakata; Motzei Shabbat v Yom Tov v tzeit s suschestvuyushchego ognya",
    ),
    "A mechitza divides men and women's seating in shul during prayer so focus stays on tefillah per traditional practice. Heights and designs vary by community.": T(
        "Mechitza — mechitza mechaleket bein yeshivat gvarim v'nashim be'shul bit'fillah kedei le'hachzik et ha'kavanah. Gvohot v'otzamot meshutafot lefi kehillah.",
        "Una mechitza divide los asientos de hombres y mujeres en la shul durante la oracion para mantener el enfoque en la tefillah. Alturas y disenos varian segun la comunidad.",
        "Une mehitsa separe les places des hommes et des femmes a la shul pendant la priere pour garder le focus sur la tefila. Hauteurs et designs varient selon la communaute.",
        "Mechitza razdelyayet mesta muzhchin i zhenshchin v shul vo vremya molitvy dlya fokusa na tefillah. Vysota i dizayn razlichayutsya po obshchinam.",
    ),
    "Mishloach Manot — Mishloach manot are ready-to-eat food gifts sent to at least one Jewish friend on Purim day — minimally two different foods in one package.": T(
        "Mishloach Manot — matanot ochel mukhan le'achila le'achad me're'im Yehudim bePurim — le'minimum shtei ma'achalot shonot be'ariza achat.",
        "Mishloach Manot — regalos de comida lista para comer enviados a al menos un amigo judio en Purim — minimo dos alimentos diferentes en un paquete.",
        "Mishloach Manot — cadeaux alimentaires prets a manger envoyes a au moins un ami juif a Pourim — minimum deux aliments differents dans un colis.",
        "Mishloach Manot — gotovye edible podarki khotya by odnomu evreyskomu drugu v Purim — minimum dva raznykh produkta v upakovke.",
    ),
    "shul — Shul (synagogue) is the community house of prayer, Torah, and chesed. Beyond services, it often hosts classes, youth programs, and charity organizations.": T(
        "shul — beit haknesset hu beit tefillah, Torah vechesed shel ha'kehillah. Milevad tefillot, hu me'arach shiurim, tochniyot no'ar ve'irgunim le'tzedakah.",
        "shul — Shul (sinagoga) es la casa comunitaria de oracion, Tora y chesed. Ademas de servicios, suele ofrecer clases, programas juveniles y organizaciones de caridad.",
        "shul — Shul (synagogue) est la maison communautaire de priere, Torah et chesed. Au-dela des offices, elle accueille cours, programmes jeunesse et organisations de tsedaka.",
        "shul — Shul (sinagoga) — obshchinnyy dom molitvy, Tory i chesed. Pomimo sluzhb — zanyatiya, molodezhnye programmy i blagotvoritelnye organizatsii.",
    ),
    "The Beit HaMikdash (Holy Temple) stood in Jerusalem as the center of sacrifice, pilgrimage, and divine presence. Its destruction on Tisha B'Av is mourned yearly.": T(
        "Beit HaMikdash — Beit HaMikdash amad biYerushalayim k'merkaz korban, aliyah l'regel ve'shechinah. Churbano beTisha B'Av ne'evl shanah b'shanah.",
        "El Beit HaMikdash (Templo Sagrado) estuvo en Jerusalen como centro de sacrificio, peregrinacion y presencia divina. Su destruccion en Tisha B'Av se llora anualmente.",
        "Le Beit HaMikdash (Temple Saint) se dressait a Jerusalem comme centre de sacrifice, pelerinage et presence divine. Sa destruction a Ticha BeAv est pleuree chaque annee.",
        "Beit HaMikdash stoyal v Ierusalime kak tsentr zhertvoprinosheniy, palomnichestva i bozhestvennogo prisutstviya. Ego razrushenie v Tisha B'Av opлакивается ежегодно.",
    ),
    "Lag BaOmer — 33rd day of the Omer; mourning eased in many communities; Chabad keeps haircut restrictions until Shavuot except for a 3 year old boy's first haircut": T(
        "Lag BaOmer — yom lamed-gimel ba'Omer; hefer evell b'kehillot rabot; Chabad shomerim al tisporet ad Shavuot chutz mi'tisporet rishona leben gimel",
        "Lag BaOmer — 33.o dia del Omer; luto aliviado en muchas comunidades; Jabad mantiene restricciones de corte hasta Shavuot excepto primer corte de nino de 3 anos",
        "Lag BaOmer — 33e jour de l'Omer ; deuil allege ; Habad garde restrictions de coupe jusqu'a Chavouot sauf premiere coupe a 3 ans",
        "Lag BaOmer — 33-y den Omera; skorb osvlablenayetsya; Chabad soblyudayet zapret strizhki do Shavuot krome pervoy strizhki trekhletnego",
    ),
}
