# -*- coding: utf-8 -*-
from rest_data import T

ENTRIES = {
    "unusual change of method that sometimes permits melacha leniency": T(
        "shinui — שינוי שיטה חריג שלפעמים מתיר הקלות במלאכה",
        "cambio inusual de método que a veces permite una leniencia en melajá",
        "changement inhabituel de méthode permettant parfois un assouplissement de melakha",
        "необычное изменение метода, иногда допускающее послабление в melacha",
    ),
    "Nachum Ish Gamzu — sage known for finding good in every situation": T(
        "נחum Ish Gamzu — חכam הידוע במציאת טוב בכל מצב",
        "Nachum Ish Gamzu — sabio conocido por encontrar lo bueno en toda situación",
        "Na'houm Ish Gam Zou — sage connu pour trouver le bien en toute situation",
        "Nachum Ish Gamzu — мудрец, известный умением находить добро в любой ситуации",
    ),
    "Put on Tefillin during morning prayers (except Shabbat/Festivals)": T(
        "הנחת תפילין בתפילת שחרית (מלבד שבת וחagim)",
        "Ponerse tefilín durante las oraciones matutinas (excepto Shabat/Fiestas)",
        "Mettre les téfilines pendant les prières du matin (sauf Chabbat/Fêtes)",
        "Надевать tefillin во время утренней молитвы (кроме Шабbata/праздников)",
    ),
    "candles, often referring especially to Shabbat and Yom Tov lights": T(
        "nerot — נרות, לעיתים קרובות במיוחד נרות שבת ויom tov",
        "velas, a menudo especialmente las luces de Shabat y Yom Tov",
        "bougies, souvent surtout les lumières de Chabbat et Yom Tov",
        "свечи, часто особенно шabbat- и yom tov-свет",
    ),
    "imitating divine kindness (clothing the needy, visiting the sick)": T(
        "הליכה בדרכי ה' — חקיית חסד אלוקי (הלבשת עneiim, בikur cholim)",
        "imitar la bondad divina (vestir a los necesitados, visitar enfermos)",
        "imiter la bonté divine (vêtir les nécessiteux, visiter les malades)",
        "подражание божественной доброте (одевать нуждающихся, навещать больных)",
    ),
    "Barchu — call to bless G-d that opens communal prayer with a minyan": T(
        "Barchu — קריאה לברך את ה' שפותחת תפילה ציבורית עם מניין",
        "Barchu — llamada a bendecir a D-s que abre la oración comunitaria con un minyán",
        "Barchou — appel à bénir D. qui ouvre la prière communautaire avec un minyan",
        "Barchu — призыв благословить В-га, открывающий общественную молитву с minyan",
    ),
    "charity box; collecting coins for those in need is itself a mitzvah": T(
        "קupat tzedakah — איסוף מטבעות לneedyim הוא בפני עצmo mitzvah",
        "caja de caridad; recolectar monedas para quienes lo necesitan es en sí una mitzvá",
        "boîte de tsedaka ; collecter des pièces pour les nécessiteux est une mitzvah en soi",
        "ящик для tzedakah; сбор монет для нуждающихся — сама по себе mitzvah",
    ),
    "mesorah — tradition faithfully transmitted generation to generation": T(
        "mesorah — מסורה שנמסרה נאmanh מדור לדור",
        "mesorah — tradición transmitida fielmente de generación en generación",
        "mesora — tradition transmise fidèlement de génération en génération",
        "mesorah — традиция, faithfully передаваемая из поколения в поколение",
    ),
    "Give the next person you see a blessing for a long and healthy life.": T(
        "תנו לnext person שתפגשu ברכה לחיים ארukim ובריאim.",
        "Dale a la próxima persona que veas una bendición de vida larga y saludable.",
        "Donnez à la prochaine personne que vous voyez une bénédiction pour une vie longue et saine.",
        "Пожелайте следующему встречному долгой и здоровой жизни.",
    ),
    "Havdalah in Kiddush — Yaknehaz order when Shabbat leads into Yom Tov": T(
        "Havdalah בkiddush — סדר Yaknehaz כששבת נכנסת ליom tov",
        "Havdalah en Kiddush — orden Yaknehaz cuando el Shabat entra en Yom Tov",
        "Havdalah dans le Kiddouch — ordre Yaknehaz quand Chabbat mène au Yom Tov",
        "Havdalah в Kiddush — порядок Yaknehaz, когда Шабbat переходит в Yom Tov",
    ),
    "Shemoneh Esrei — the eighteen (now nineteen) blessings of the Amidah": T(
        "Shemoneh Esrei — שmoneh esre (כיום tisha esre) brachot shel ha'amidah",
        "Shemoneh Esrei — las dieciocho (ahora diecinueve) bendiciones del Amidá",
        "Chemoné Esré — les dix-huit (maintenant dix-neuf) bénédictions de l'Amidah",
        "Shemoneh Esrei — восемнадцать (теперь девятнадцать) благословений Amidah",
    ),
    "Shmoneh Esrei — the nineteen blessings of the standing Amidah prayer": T(
        "Shmoneh Esrei — תשע עשרה brachot shel tefilat ha'amidah",
        "Shmoneh Esrei — las diecinueve bendiciones de la oración Amidá de pie",
        "Chemoné Esré — les dix-neuf bénédictions de la prière Amidah debout",
        "Shmoneh Esrei — девятнадцать благословений стоячей молитвы Amidah",
    ),
    "Erev — the day before a holy day (Erev Shabbat is friday until sunset": T(
        "Erev — יom lifnei yom kodesh (Erev Shabbat hu yom shishi ad hasheki'a",
        "Erev — el día antes de un día santo (Erev Shabat es viernes hasta el atardecer",
        "Erev — le jour avant un jour saint (Erev Chabbat est vendredi jusqu'au coucher du soleil",
        "Erev — день перед святым днём (Erev Shabbat — пятница до заката",
    ),
    "Eruv techumin — extends the Shabbat walking boundary in special cases": T(
        "Eruv techumin — מרחיב את תחום הליכת השבת במקרים מיוחדים",
        "Eruv techumin — extiende el límite de caminata del Shabat en casos especiales",
        "Erouv techoumin — étend la limite de marche du Chabbat dans des cas spéciaux",
        "Eruv techumin — расширяет shabbat-границу ходьбы в особых случаях",
    ),
    "Honor Shabbat! Pick out a special wine (or grape juice) for Kiddush 🍷": T(
        "כבdu et haShabbat! Bchru yayin meyuchad (o michyat anavim) leKiddush 🍷",
        "¡Honra el Shabat! Elige un vino especial (o jugo de uva) para el Kiddush 🍷",
        "Honorez Chabbat ! Choisissez un vin spécial (ou du jus de raisin) pour le Kiddouch 🍷",
        "Почитайте Шабbat! Выберите особое вино (или виноградный сок) для Kiddush 🍷",
    ),
    "Motzei Shabbat — Motzei Shabbat is Saturday night after Shabbat ends.": T(
        "Motzei Shabbat — מוצאי שבת הוא ליל שבת לאחר סיום השבת.",
        "Motzei Shabat — Motzei Shabat es la noche del sábado tras terminar el Shabat.",
        "Motzei Chabbat — Motzei Chabbat est le samedi soir après la fin de Chabbat.",
        "Motzei Shabbat — субботний вечер после окончания Шаббата.",
    ),
    "hakarat hatov — recognizing the good; thanking someone for a kindness": T(
        "hakarat hatov — הכרת הטוב; הודאה למישהו על טובה",
        "hakarat hatov — reconocer lo bueno; agradecer a alguien por una bondad",
        "hakarat hatov — reconnaître le bien ; remercier quelqu'un pour une bonté",
        "hakarat hatov — признание добра; благодарность за доброту",
    ),
    "praying; any prayer, often refers to the formal daily prayer services": T(
        "davening — תפילה; כל תפילה, לעיתים קרובות מתייחסת לתפילות היומיות",
        "orar; cualquier oración, a menudo se refiere a los servicios diarios formales",
        "prier ; toute prière, désigne souvent les offices quotidiens formels",
        "молиться; любая молитва, часто относится к формальным ежедневным службам",
    ),
    "refuah shleimah — complete healing; said when praying for someone ill": T(
        "refuah shleimah — רפואה שלמה; נאמר בתפילה עבור חולה",
        "refuah shleimah — sanación completa; se dice al orar por alguien enfermo",
        "refoua chleima — guérison complète ; dite en priant pour une personne malade",
        "refuah shleimah — полное исцеление; произносится при молитве о больном",
    ),
    '"guard (Shabbat)" from the Deuteronomy version of the Ten Commandments': T(
        '"שmor (Shabbat)" מנוסח דvarim של עשרת הדibrot',
        '"guardar (Shabat)" de la versión de Deuteronomio de los Diez Mandamientos',
        '"garder (Chabbat)" de la version Deutéronome des Dix Commandements',
        '"guardar (Shabbat)" из варианта Deuteronomy Десяти заповедей',
    ),
    "loving your fellow Jew — central Torah principle taught by Rabbi Akiva": T(
        "אהבat l'reacha kamocha — עיקרון תורה מרכזי שלמד רבי עקיבא",
        "amar a tu prójimo judío — principio central de la Torá enseñado por el rabí Akiva",
        "aimer son prochain Juif — principe central de la Torah enseigné par Rabbi Akiva",
        "любить ближнего еврея — центральный принцип Торы, которому учил рабbi Akiva",
    ),
    "neutral foods (neither meat nor dairy) such as fish, eggs, and produce": T(
        "pareve — מזonot neutralim (לא בשר ולא חalav) כמו דag, beitzim וyerek",
        "alimentos neutros (ni carne ni lácteos) como pescado, huevos y productos vegetales",
        "aliments neutres (ni viande ni laitier) tels que poisson, œufs et produits végétaux",
        "нейтральные продукты (ни мясо, ни молочное), например рыба, яйца и овощи",
    ),
    "Chol HaMoed Sukkot — intermediate Sukkot days between the Festival days": T(
        "חול המועד של סוכות — ימי חול המועד של סוכות בין ימי החag",
        "Chol HaMoed Sucot — días intermedios de Sucot entre los días de fiesta",
        "Hol Hamoed Souccot — jours intermédiaires de Souccot entre les jours de fête",
        "Chol HaMoed Sukkot — промежуточные дни Суккот между праздничными днями",
    ),
    "Matan Torah — receiving the Torah at Mount Sinai, celebrated on Shavuot": T(
        "Matan Torah — קבלת התורה בהar Sinai, החag בshavuot",
        "Matan Torah — recibir la Torá en el Monte Sinaí, celebrado en Shavuot",
        "Matan Torah — réception de la Torah au mont Sinaï, célébrée à Chavouot",
        "Matan Torah — получение Торы на горе Синай, празднуется на Shavuot",
    ),
    "blessing entrusting the soul to G-d before sleep, part of bedtime Shema": T(
        "Hamapil — bracha המפקידa et hanefesh leHashem lifnei sheina, חלק מShema al hamita",
        "bendición que encomienda el alma a D-s antes de dormir, parte del Shema nocturno",
        "bénédiction confiant l'âme à D. avant le sommeil, partie du Shema du coucher",
        "благословение, вручающее душу В-гу перед сном, часть вечерней Шма",
    ),
    "palm branch waved with the etrog, willows, and myrtle branches on Sukkot": T(
        "lulav — ענף דקל שננענע עם etrog, aravot vehadasim בסוכות",
        "rama de palma ondeada con el etrog, sauces y mirto en Sucot",
        "branche de palmier agitée avec l'etrog, saules et myrte à Souccot",
        "palmовая ветвь с etrog, ивой и миртом на Суккот",
    ),
    "14 Adar (15 in walled cities); Megillah, gifts to friends/poor, and feast": T(
        "י\"ד באדר (ט\"ו בערים מukafot choma); Megillah, matanot la'evyonim useudah",
        "14 Adar (15 en ciudades amuralladas); Meguilá, regalos a amigos/pobres y festín",
        "14 Adar (15 dans les villes fortifiées) ; Meguila, cadeaux aux amis/pauvres et festin",
        "14 Adar (15 в городах с стеной); Megillah, подарки друзьям/бедным и пир",
    ),
    "Nerot — candles, often referring especially to Shabbat and Yom Tov lights": T(
        "Nerot — נרות, לעיתים קרובות במיוחד נרות שבת ויom tov",
        "Nerot — velas, a menudo especialmente las luces de Shabat y Yom Tov",
        "Nerot — bougies, souvent surtout les lumières de Chabbat et Yom Tov",
        "Nerot — свечи, часто особенно шabbat- и yom tov-свет",
    ),
    "matzah guarded from moisture from harvest; required by many for the Seder": T(
        "shmurah matzah — matzah hashmurah melehetem min haktzir; נדרשת לרabim leSeder",
        "matzá vigilada desde la cosecha; requerida por muchos para la Seder",
        "matza surveillée dès la récolte ; requise par beaucoup pour la Seder",
        "matzah, охраняемая от влаги с урожая; требуется многими для Seder",
    ),
    "melachot — the 39 categories of transformative labor forbidden on Shabbat": T(
        "melachot — ל\"ט קטegorיות של מלאכה משנה האסורה בשבת",
        "melachot — las 39 categorías de trabajo transformador prohibido en Shabat",
        "melachot — les 39 catégories de travail transformateur interdit le Chabbat",
        "melachot — 39 категорий преобразующего труда, запрещённого в Шабbat",
    ),
    "shinui — unusual change of method that sometimes permits melacha leniency": T(
        "shinui — שינוי שיטה חריג שלפעמים מתיר הקלות במלאכה",
        "shinui — cambio inusual de método que a veces permite una leniencia en melajá",
        "shinui — changement inhabituel de méthode permettant parfois un assouplissement de melakha",
        "shinui — необычное изменение метода, иногда допускающее послабление в melacha",
    ),
    "this too is for the good; trust that hardship can be for the greater good": T(
        "Gam zu l'tovah — gam zu letovah; bitachon she'osher yechol lihyot letovah haklalit",
        "esto también es para el bien; confía en que la dificultad puede ser para un bien mayor",
        "ceci aussi est pour le bien ; ayez confiance que l'épreuve peut servir un bien plus grand",
        "и это — на благо; верьте, что трудности могут быть к общему благу",
    ),
    "Chol HaMoed Pesach — intermediate days of Pesach between the festival days": T(
        "חול המועד של פesach — ימי חול המועד של פesach בין ימי החag",
        "Chol HaMoed Pesaj — días intermedios de Pesaj entre los días de fiesta",
        "Hol Hamoed Pessah — jours intermédiaires de Pessah entre les jours de fête",
        "Chol HaMoed Pesach — промежуточные дни Песаха между праздничными днями",
    ),
    "Pray for a refuah shleimah (complete healing) for Raphael Yosef ben Rachel": T(
        "התpalelu lrefuah shleimah leRaphael Yosef ben Rachel",
        "Oren por una refuah shleimah (sanación completa) para Raphael Yosef ben Rachel",
        "Priez pour une refoua chleima pour Raphael Yosef ben Rachel",
        "Молитесь о refuah shleimah (полном исцелении) для Raphael Yosef ben Rachel",
    ),
    "borei me'orei ha'eish — blessing over fire in Yaknehaz and regular Havdalah": T(
        "borei me'orei ha'eish — bracha al ha'esh beYaknehaz uveHavdalah regila",
        "borei me'orei ha'eish — bendición sobre el fuego en Yaknehaz y Havdalah regular",
        "borei me'orei ha'eish — bénédiction sur le feu dans Yaknehaz et la Havdalah ordinaire",
        "borei me'orei ha'eish — благословение на огонь в Yaknehaz и обычной Havdalah",
    ),
    "shmirat halashon — guarding one's speech from lashon hara and harmful words": T(
        "shmirat halashon — שmirat halashon melashon hara umeilimim mazikim",
        "shmirat halashon — guardar el habla de lashon hara y palabras dañinas",
        "shmirat halashon — garder sa parole du lashon hara et des paroles nuisibles",
        "shmirat halashon — оберегать речь от lashon hara и вредных слов",
    ),
    "Eruv chatzerot — symbolic merging of courtyards allowing carrying on Shabbat": T(
        "Eruv chatzerot — mizug semli shel chatzerot hamafshir hotza'ah baShabbat",
        "Eruv chatzerot — fusión simbólica de patios que permite transportar en Shabat",
        "Erouv 'hatzerot — fusion symbolique de cours permettant le transport le Chabbat",
        "Eruv chatzerot — символическое объединение дворов, разрешающее перенос в Шабbat",
    ),
    "shortened Hallel psalms on Rosh Chodesh and after the first Yom Tov of Pesach": T(
        "Half Hallel — hallel katzar beRosh Chodesh ule'achar Yom Tov rishon shel Pesach",
        "Hallel acortado en Rosh Jodesh y tras el primer Yom Tov de Pesaj",
        "Hallel raccourci à Roch 'Hodech et après le premier Yom Tov de Pessah",
        "сокращённый Hallel в Rosh Chodesh и после первого Yom Tov Песаха",
    ),
    "yirat Shamayim — fearing of Heaven; living with awareness that G-d is present": T(
        "yirat Shamayim — yirat shamayim; chayim im moda'ut le'nokhachut Hashem",
        "yirat Shamayim — temor del Cielo; vivir con conciencia de que D-s está presente",
        "yirat Shamayim — crainte du Ciel ; vivre avec conscience que D. est présent",
        "yirat Shamayim — страх Небес; жизнь с осознанием присутствия В-га",
    ),
    "ביום ראש החדש הזה\n            ביום חג המצות הזה\n            ביום חג הסכות הזה": T(
        "ביום ראש החדש הזה\n            ביום חג המצות הזה\n            ביום חג הסכות הזה",
        "En este día de Rosh Jodesh\n            en este día de la Fiesta de los Matzot\n            en este día de la Fiesta de Sucot",
        "En ce jour de Roch 'Hodech\n            en ce jour de la Fête des Matsot\n            en ce jour de la Fête de Souccot",
        "В этот день новомесячия\n            в этот день праздника мацев\n            в этот день праздника Суккот",
    ),
    "Aseret Yemei Teshuvah — Ten Days of Repentance from Rosh Hashana to Yom Kippur": T(
        "Aseret Yemei Teshuvah — עשרת ימei teshuvah מראש השנה עד יom kippur",
        "Aseret Yemei Teshuvah — Diez Días de Arrepentimiento de Rosh Hashaná a Yom Kipur",
        "Aseret Yemei Teshouva — Dix Jours de Repentance de Roch Hachana à Yom Kippour",
        "Aseret Yemei Teshuvah — Десять дней покаяния от Рosh а-Шана до Yom Kippur",
    ),
    "Clean your bathroom extra spick and span in honor of Shabbat. - Submitted by AS": T(
        "נקו את חדר האמבטיה במיוחד לכבוד שבת. — נשלח על ידי AS",
        "Limpia tu baño extra impecable en honor del Shabat. — Enviado por AS",
        "Nettoyez votre salle de bain particulièrement bien en l'honneur de Chabbat. — Soumis par AS",
        "Уберите в ванной особенно тщательно в честь Шабbata. — От AS",
    ),
    'Shamor — "guard (Shabbat)" from the Deuteronomy version of the Ten Commandments': T(
        'Shamor — "שmor (Shabbat)" מנוסח דvarim של עשרת הדibrot',
        'Shamor — "guardar (Shabat)" de la versión de Deuteronomio de los Diez Mandamientos',
        'Shamor — "garder (Chabbat)" de la version Deutéronome des Dix Commandements',
        'Shamor — "guardar (Shabbat)" из варианта Deuteronomy Десяти заповедей',
    ),
    "dancing while circling around the synagogue with Torah scrolls on Simchat Torah": T(
        "Hakafot — rikudim bisvivat beit haknesset im sifrei Torah beSimchat Torah",
        "Hakafot — bailar rodeando la sinagoga con rollos de Torá en Simjat Torá",
        "Hakafot — danser en tournant autour de la synagogue avec les rouleaux de Torah à Sim'hat Torah",
        "Hakafot — танцы с обходом синагоги со свитками Торы в Симхат Тора",
    ),
    "pareve — neutral foods (neither meat nor dairy) such as fish, eggs, and produce": T(
        "pareve — mazonot neutralim (lo basar velo chalav) kmo dag, beitzim veryek",
        "pareve — alimentos neutros (ni carne ni lácteos) como pescado, huevos y productos vegetales",
        "pareve — aliments neutres (ni viande ni laitier) tels que poisson, œufs et produits végétaux",
        "pareve — нейтральные продукты (ни мясо, ни молочное), например рыба, яйца и овощи",
    ),
    "Ashkenazi-Chasidic prayer rite (not the same as Sephardic Nusach Edot HaMizrach)": T(
        "nusach Sefard — nusach tefillah Ashkenazi-Chasidic (lo zeh nusach Sefarad Edot HaMizrach)",
        "Rito de oración ashkenazí-jasídico (no es lo mismo que el Nusaj Sefaradí Edot HaMizrach)",
        "Rite de prière ashkénaze-hassidique (pas le même que le Nousah Séfarade Edot HaMizrach)",
        "Ашкеназско-хasidic молитвенный обряд (не то же, что сефардский Nusach Edot HaMizrach)",
    ),
    "Davening — praying; any prayer, often refers to the formal daily prayer services": T(
        "Davening — tefillah; kol tefillah, le'itim krovot mithyaches le'tefillot hayomiot",
        "Davening — orar; cualquier oración, a menudo se refiere a los servicios diarios formales",
        "Davening — prier ; toute prière, désigne souvent les offices quotidiens formels",
        "Davening — молиться; любая молитва, часто относится к формальным ежедневным службам",
    ),
    "lulav — palm branch waved with the etrog, willows, and myrtle branches on Sukkot": T(
        "lulav — klat degel shenina'ne'a im etrog, aravot vehadasim beSukkot",
        "lulav — rama de palma ondeada con el etrog, sauces y mirto en Sucot",
        "lulav — branche de palmier agitée avec l'etrog, saules et myrte à Souccot",
        "lulav — palmовая ветвь с etrog, ивой и миртом на Суккот",
    ),
    "Hamapil — blessing entrusting the soul to G-d before sleep, part of bedtime Shema": T(
        "Hamapil — bracha hamefakeda et hanefesh leHashem lifnei sheina, chelek miShema al hamita",
        "Hamapil — bendición que encomienda el alma a D-s antes de dormir, parte del Shema nocturno",
        "Hamapil — bénédiction confiant l'âme à D. avant le sommeil, partie du Shema du coucher",
        "Hamapil — благословение, вручающее душу В-гу перед сном, часть вечерней Шма",
    ),
    "chametz that was in your possession over Pesach (forbidden to benefit from after)": T(
        "chametz she'avar — chametz shehayta bereshutcha al Pesach (asur lehanot mimenu le'achar)",
        "chametz que estuvo en tu posesión durante Pesaj (prohibido beneficiarse después)",
        "hamets qui était en votre possession pendant Pessah (interdit d'en profiter après)",
        "chametz, бывший в вашем владении на Песах (запрещено пользоваться после)",
    ),
    "seudat mitzvah — festive meal tied to a mitzvah (e.g. brit, siyum, wedding, etc.)": T(
        "seudat mitzvah — seudah chagigit keshura lemitzvah (l'mashal brit, siyum, chupah v'ch.)",
        "seudat mitzvah — comida festiva ligada a una mitzvá (p. ej. brit, siyum, boda, etc.)",
        "seudat mitzvah — repas festif lié à une mitzvah (p. ex. brit, siyoum, mariage, etc.)",
        "seudat mitzvah — праздничная трапеза, связанная с mitzvah (напр. brit, siyum, свадьба и т.д.)",
    ),
    "tzedakah box — charity box; collecting coins for those in need is itself a mitzvah": T(
        "tzedakah box — kupat tzedakah; le'asef matbe'ot lanechyim hu b'fnei atzmo mitzvah",
        "tzedakah box — caja de caridad; recolectar monedas para quienes lo necesitan es en sí una mitzvá",
        "tzedakah box — boîte de tsedaka ; collecter des pièces pour les nécessiteux est une mitzvah en soi",
        "tzedakah box — ящик для tzedakah; сбор монет для нуждающихся — сама по себе mitzvah",
    ),
    "Say a quick prayer for patience. Sometimes the best things take a moment to load! 🙏": T(
        "אמרו תפילה קצרה לסבלנות. לפעמים הדברים הטובים ביותר לוקחים רגע לטעון! 🙏",
        "Di una oración rápida por paciencia. ¡A veces lo mejor tarda un momento en cargar! 🙏",
        "Dites une prière rapide pour la patience. Parfois les meilleures choses prennent un moment à charger ! 🙏",
        "Произнесите короткую молитву о терпении. Иногда лучшее требует времени на загрузку! 🙏",
    ),
    "meat status; dairy may not be eaten for a waiting period afterward, usually 6 hours": T(
        "fleishig — status basari; chalav asur le'echol ad zman hamtana, le'rov 6 sha'ot",
        "estado de carne; no se puede comer lácteo durante un período de espera, generalmente 6 horas",
        "statut viande ; produits laitiers interdits pendant une période d'attente, généralement 6 heures",
        "мясной статус; молочное нельзя есть в течение периода ожидания, обычно 6 часов",
    ),
    "in kashrut, a certification that food was produced under reliable kosher supervision": T(
        "hechsher — be'kashrut, te'udah she'ochel yutzar betakhashoret kosher ne'emana",
        "en kashrut, certificación de que el alimento se produjo bajo supervisión kosher confiable",
        "en cacherout, certification que l'aliment a été produit sous supervision casher fiable",
        "в kashrut — сертификация, что продукт произведён под надёжным kosher-надзором",
    ),
    "Purim day — 14 Adar (15 in walled cities); Megillah, gifts to friends/poor, and feast": T(
        "Purim day — yud-daled ba'adar (tet-vav be'ir mukafet choma); Megillah, mishloach manot useudah",
        "Día de Purim — 14 Adar (15 en ciudades amuralladas); Meguilá, regalos a amigos/pobres y festín",
        "Jour de Pourim — 14 Adar (15 dans les villes fortifiées) ; Meguila, cadeaux aux amis/pauvres et festin",
        "День Пурим — 14 Adar (15 в городах с стеной); Megillah, подарки друзьям/бедным и пир",
    ),
    "large prayer shawl with tzitzit worn during Shacharit/Musaf and all day on Yom Kippur": T(
        "tallit gadol — talit gadol im tzitzit hanilbash beShacharit/Musaf vechol hayom beYom Kippur",
        "talit grande con tzitzit usado en Shajarit/Musaf y todo el día en Yom Kipur",
        "grand talit avec tsitsit porté à Shacharit/Moussaf et toute la journée à Yom Kippour",
        "большой talit с tzitzit, носимый на Shacharit/Musaf и весь день в Yom Kippur",
    ),
    "A blech is a metal cover placed on the stove to cover flames and heat food on Shabbat.": T(
        "Blech hu michseh metali hamotam al ha'kira lekasot lehavot ulechamem ochel baShabbat.",
        "Un blech es una cubierta metálica colocada sobre la estufa para cubrir las llamas y calentar comida en Shabat.",
        "Un blech est un couvercle métallique placé sur la cuisinière pour couvrir les flammes et réchauffer les aliments le Chabbat.",
        "Blech — металлическая крышка на плите, чтобы прикрыть пламя и подогревать еду в Шабbat.",
    ),
    "Pray for a shidduch (wife) for my friend Mordechai Shaul ben Devorah - submitted by HS": T(
        "התpalelu lshidduch (isha) lechaver Mordechai Shaul ben Devorah — nishlach al yedei HS",
        "Oren por un shidduj (esposa) para mi amigo Mordechai Shaul ben Devorah — enviado por HS",
        "Priez pour un shidou'h (épouse) pour mon ami Mordechai Shaul ben Devorah — soumis par HS",
        "Молитесь о shidduch (жене) для моего друга Mordechai Shaul ben Devorah — от HS",
    ),
    "completion of a Torah text such as a tractate of the Talmud, often with a festive meal": T(
        "siyum — siyum ketav Torah k'mo masechet baTalmud, le'itim krovot im seudah chagigit",
        "siyum — finalización de un texto de Torá como un tratado del Talmud, a menudo con comida festiva",
        "siyoum — achèvement d'un texte de Torah comme un traité du Talmud, souvent avec un repas festif",
        "siyum — завершение Torah-текста, например трактата Talmud, часто с праздничной трапезой",
    ),
    "honoring your parents — Kibud Av V'Eim - mitzvah to honor/respect and care for parents": T(
        "Kibud Av V'Eim — mitzvah lekhabed ule'akvod ule'tend lehorim",
        "honrar a tus padres — Kibud Av V'Eim — mitzvá de honrar/respetar y cuidar a los padres",
        "honorer vos parents — Kiboud Av V'Éim — mitzvah d'honorer/respecter et prendre soin des parents",
        "почитание родителей — Kibud Av V'Eim — mitzvah почитать/уважать и заботиться о родителях",
    ),
    "walk in G-d's ways — imitating divine kindness (clothing the needy, visiting the sick)": T(
        "le'lech bidrachav — le'hakot chesed Eloki (hilbashat nechyim, bikkur cholim)",
        "caminar en los caminos de D-s — imitar la bondad divina (vestir a los necesitados, visitar enfermos)",
        "marcher dans les voies de D. — imiter la bonté divine (vêtir les nécessiteux, visiter les malades)",
        "идти путями В-га — подражать божественной доброте (одевать нуждающихся, навещать больных)",
    ),
    "Pray for a refuah shleimah (complete healing) for Sarah Dina bat Odel - submitted by DM": T(
        "התpalelu lrefuah shleimah leSarah Dina bat Odel — nishlach al yedei DM",
        "Oren por una refuah shleimah (sanación completa) para Sarah Dina bat Odel — enviado por DM",
        "Priez pour une refoua chleima pour Sarah Dina bat Odel — soumis par DM",
        "Молитесь о refuah shleimah (полном исцелении) для Sarah Dina bat Odel — от DM",
    ),
    "priest descended from Aaron. They perform the service in the Temple when it's standing.": T(
        "kohen — kohen yoresh Aharon. Hem meshartim baMikdash ke'she'hu omed.",
        "sacerdote descendiente de Aarón. Realizan el servicio en el Templo cuando está en pie.",
        "prêtre descendant d'Aaron. Ils officient au Temple quand il est debout.",
        "священник из рода Aharon. Они служат в Храме, когда он стоит.",
    ),
    "Learn the laws of lashon hara (evil speech) from the Chofetz Chaim.  -Submitted by Moshe": T(
        "למdu et chukei lashon hara (dibur ra) me'et haChafetz Chaim. — Nishlach al yedei Moshe",
        "Aprende las leyes de lashon hara (mala lengua) del Jofetz Jaim. — Enviado por Moshe",
        "Apprenez les lois du lashon hara (mauvaise langue) du Hafets Haïm. — Soumis par Moshe",
        "Изучите законы lashon hara (злой речи) у Chofetz Chaim. — От Moshe",
    ),
    "Rain. Can refer to the prayer for rain inserted on Shemini Atzeret throughout the winter": T(
        "Geshem — Matar. Yechol le'hithayech litfillat geshem haniknet beShemini Atzeret lechol hachoref",
        "Lluvia. Puede referirse a la oración por la lluvia insertada en Shemini Atzeret durante el invierno",
        "Pluie. Peut désigner la prière pour la pluie insérée à Chemini Atseret tout l'hiver",
        "Дождь. Может относиться к молитве о дожде, добавляемой в Shemini Atzeret на всю зиму",
    ),
    "Hakafot — dancing while circling around the synagogue with Torah scrolls on Simchat Torah": T(
        "Hakafot — rikudim bisvivat beit haknesset im sifrei Torah beSimchat Torah",
        "Hakafot — bailar rodeando la sinagoga con rollos de Torá en Simjat Torá",
        "Hakafot — danser en tournant autour de la synagogue avec les rouleaux de Torah à Sim'hat Torah",
        "Hakafot — танцы с обходом синагоги со свитками Торы в Симхат Тора",
    ),
    "escorting the Shabbat Queen — Motzei Shabbat meal (מְלַוֶּה מַלְכָּה) through dawn Sunday": T(
        "Melave Malka — melave et malkat haShabbat — seudat Motzei Shabbat (מְלַוֶּה מַלְכָּה) ad shacharit yom rishon",
        "escoltar a la Reina del Shabat — comida de Motzei Shabat (Melave Malka) hasta el amanecer del domingo",
        "escorter la Reine de Chabbat — repas de Motzei Chabbat (Melave Malka) jusqu'à l'aube du dimanche",
        "провожать Shabbat Queen — трапеза Motzei Shabbat (Melave Malka) до рассвета воскресенья",
    ),
    "Gam zu l'tovah — this too is for the good; trust that hardship can be for the greater good": T(
        "Gam zu l'tovah — gam zu letovah; bitachon she'osher yechol lihyot letovah ha'klalit",
        "Gam zu l'tovah — esto también es para el bien; confía en que la dificultad puede ser para un bien mayor",
        "Gam zu l'tovah — ceci aussi est pour le bien ; ayez confiance que l'épreuve peut servir un bien plus grand",
        "Gam zu l'tovah — и это — на благо; верьте, что трудности могут быть к общему благу",
    ),
    "shmurah matzah — matzah guarded from moisture from harvest; required by many for the Seder": T(
        "shmurah matzah — matzah hashmurah melehetem min haktzir; nidréshet l'rabim leSeder",
        "shmurah matzah — matzá vigilada desde la cosecha; requerida por muchos para la Seder",
        "shmurah matza — matza surveillée dès la récolte ; requise par beaucoup pour la Seder",
        "shmurah matzah — matzah, охраняемая от влаги с урожая; требуется многими для Seder",
    ),
    "Guardian of the doors of Israel (acronym Shin-Dalet-Yod (one of Hashem's names) on mezuzah)": T(
        "Shomer Daltot Yisrael — Shomer Daltot Yisrael (roshei teivot Shin-Dalet-Yod, shem miShemot Hashem, al hamezuzah)",
        "Guardián de las puertas de Israel (acrónimo Shin-Dalet-Yod, uno de los nombres de Hashem, en la mezuzá)",
        "Gardien des portes d'Israël (acronyme Shin-Dalet-Yod, un des noms de Hashem, sur la mezouza)",
        "Хранитель дверей Израиля (акроним Shin-Dalet-Yod, одно из имён Hashem, на mezuzah)",
    ),
    "Half Hallel — shortened Hallel psalms on Rosh Chodesh and after the first Yom Tov of Pesach": T(
        "Half Hallel — hallel katzar beRosh Chodesh ule'achar Yom Tov rishon shel Pesach",
        "Half Hallel — salmos de Hallel acortados en Rosh Jodesh y tras el primer Yom Tov de Pesaj",
        "Half Hallel — psaumes de Hallel raccourcis à Roch 'Hodech et après le premier Yom Tov de Pessah",
        "Half Hallel — сокращённые psalms Hallel в Rosh Chodesh и после первого Yom Tov Песаха",
    ),
    "Thank G-d for the gift of this moment. Even when technology fails, gratitude always works! 🙏": T(
        "הודu laHashem al matnat harega hazeh. Afilu ke'she'technologia nichshal, hakarat todah tamid ovedet! 🙏",
        "Agradece a D-s por el regalo de este momento. ¡Incluso cuando la tecnología falla, la gratitud siempre funciona! 🙏",
        "Remerciez D. pour le don de cet instant. Même quand la technologie échoue, la gratitude fonctionne toujours ! 🙏",
        "Благодарите В-га за дар этого момента. Даже когда технология подводит, благодарность всегда работает! 🙏",
    ),
    "Blech — A blech is a metal cover placed on the stove to cover flames and heat food on Shabbat.": T(
        "Blech — Blech hu michseh metali hamotam al ha'kira lekasot lehavot ulechamem ochel baShabbat.",
        "Blech — Un blech es una cubierta metálica colocada sobre la estufa para cubrir las llamas y calentar comida en Shabat.",
        "Blech — Un blech est un couvercle métallique placé sur la cuisinière pour couvrir les flammes et réchauffer les aliments le Chabbat.",
        "Blech — металлическая крышка на плите, чтобы прикрыть пламя и подогревать еду в Шабbat.",
    ),
    "fleishig — meat status; dairy may not be eaten for a waiting period afterward, usually 6 hours": T(
        "fleishig — status basari; chalav asur le'echol ad zman hamtana, le'rov 6 sha'ot",
        "fleishig — estado de carne; no se puede comer lácteo durante un período de espera, generalmente 6 horas",
        "fleishig — statut viande ; produits laitiers interdits pendant une période d'attente, généralement 6 heures",
        "fleishig — мясной статус; молочное нельзя есть в течение периода ожидания, обычно 6 часов",
    ),
    "siyum — completion of a Torah text such as a tractate of the Talmud, often with a festive meal": T(
        "siyum — siyum ketav Torah k'mo masechet baTalmud, le'itim krovot im seudah chagigit",
        "siyum — finalización de un texto de Torá como un tratado del Talmud, a menudo con comida festiva",
        "siyoum — achèvement d'un texte de Torah comme un traité du Talmud, souvent avec un repas festif",
        "siyum — завершение Torah-текста, например трактата Talmud, часто с праздничной трапезой",
    ),
    '"remember" from the Exodus version of the Ten Commandments telling the Jews to remember Shabbat': T(
        '"zachor" min nusach Shemot shel aseret hadibrot lehazkir et Yisrael lezachor et haShabbat',
        '"recordar" de la version del Exodo de los Diez Mandamientos que ordena recordar el Shabat',
        '"souviens-toi" de la version Exode des Dix Commandements ordonnant de se souvenir de Chabbat',
        '"remember" iz varianta Exodus Desyati zapovedey, povelivayushchego pomnit Shabbat',
    ),
    "hechsher — in kashrut, a certification that food was produced under reliable kosher supervision": T(
        "hechsher — be'kashrut, te'udah she'ochel yutzar betakhashoret kosher ne'emana",
        "hechsher — en kashrut, certificación de que el alimento se produjo bajo supervisión kosher confiable",
        "he'hser — en cacherout, certification que l'aliment a été produit sous supervision casher fiable",
        "hechsher — в kashrut — сертификация, что продукт произведён под надёжным kosher-надзором",
    ),
    "kohen — priest descended from Aaron. They perform the service in the Temple when it's standing.": T(
        "kohen — kohen yoresh Aharon. Hem meshartim baMikdash ke'she'hu omed.",
        "kohen — sacerdote descendiente de Aarón. Realizan el servicio en el Templo cuando está en pie.",
        "kohen — prêtre descendant d'Aaron. Ils officient au Temple quand il est debout.",
        "kohen — священник из рода Aharon. Они служат в Храме, когда он стоит.",
    ),
    "nusach Sefard — Ashkenazi-Chasidic prayer rite (not the same as Sephardic Nusach Edot HaMizrach)": T(
        "nusach Sefard — nusach tefillah Ashkenazi-Chasidic (lo zeh nusach Sefarad Edot HaMizrach)",
        "nusach Sefard — rito de oración ashkenazí-jasídico (no es lo mismo que el Nusaj Sefaradí Edot HaMizrach)",
        "nusah Sefard — rite de prière ashkénaze-hassidique (pas le même que le Nousah Séfarade Edot HaMizrach)",
        "nusach Sefard — ашkenazско-хasidic молитвенный обряд (не то же, что сефардский Nusach Edot HaMizrach)",
    ),
    "Bedtime Shema (first paragraph - though recommended to say entire Shema for spiritual protection)": T(
        "Shema al hamita (paragraf rishon — im muvtach le'emor et kol haShema le'haganah ruchanit)",
        "Shema nocturno (primer párrafo — aunque se recomienda decir todo el Shema para protección espiritual)",
        "Shema du coucher (premier paragraphe — bien qu'il soit recommandé de dire tout le Shema pour protection spirituelle)",
        "Вечерняя Шма (первый абзац — хотя рекомендуется читать всю Шму для духовной защиты)",
    ),
    "Geshem — Rain. Can refer to the prayer for rain inserted on Shemini Atzeret throughout the winter": T(
        "Geshem — Matar. Yechol le'hithayech litfillat geshem haniknet beShemini Atzeret lechol hachoref",
        "Geshem — Lluvia. Puede referirse a la oración por la lluvia insertada en Shemini Atzeret durante el invierno",
        "Geshem — Pluie. Peut désigner la prière pour la pluie insérée à Chemini Atseret tout l'hiver",
        "Geshem — Дождь. Может относиться к молитве о дожде, добавляемой в Shemini Atzeret на всю зиму",
    ),
    "small four-cornered garment with tzitzit, worn generally over or under a shirt per community custom": T(
        "tallit katan — beged katan ba'al arba kenafot im tzitzit, nilbash mi'it le'mata o mi'it le'ma'la lefi minhag",
        "prenda pequeña de cuatro esquinas con tzitzit, usada sobre o bajo la camisa según la costumbre",
        "petit vêtement à quatre coins avec tsitsit, porté au-dessus ou en dessous de la chemise selon la coutume",
        "небольшая четырёхугольная одежда с tzitzit, носимая поверх или под рубашкой по обычаю общины",
    ),
    "chametz she'avar — chametz that was in your possession over Pesach (forbidden to benefit from after)": T(
        "chametz she'avar — chametz shehayta bereshutcha al Pesach (asur lehanot mimenu le'achar)",
        "chametz she'avar — chametz que estuvo en tu posesión durante Pesaj (prohibido beneficiarse después)",
        "hamets she'avar — hamets qui était en votre possession pendant Pessah (interdit d'en profiter après)",
        "chametz she'avar — chametz, бывший в вашем владении на Песах (запрещено пользоваться после)",
    ),
    "tallit gadol — large prayer shawl with tzitzit worn during Shacharit/Musaf and all day on Yom Kippur": T(
        "tallit gadol — talit gadol im tzitzit hanilbash beShacharit/Musaf vechol hayom beYom Kippur",
        "tallit gadol — talit grande con tzitzit usado en Shajarit/Musaf y todo el día en Yom Kipur",
        "tallit gadol — grand talit avec tsitsit porté à Shacharit/Moussaf et toute la journée à Yom Kippour",
        "tallit gadol — большой talit с tzitzit, носимый на Shacharit/Musaf и весь день в Yom Kippur",
    ),
    "בראש חודש: הרחמן הוא יחדש עלינו את החדש הזה לטובה ולברכה.\nבסוכות: הרחמן הוא יקים לנו את סכת דוד הנופלת.": T(
        "בראש חודש: הרחמן הוא יחדש עלינו את החדש הזה לטובה ולברכה.\nבסוכות: הרחמן הוא יקים לנו את סכת דוד הנופלת.",
        "En Rosh Jodesh: El Compasivo renueve para nosotros este mes para bien y bendición.\nEn Sucot: El Compasivo erija para nosotros la caída cabaña de David.",
        "À Roch 'Hodech : Que le Miséricordieux renouvelle pour nous ce mois pour le bien et la bénédiction.\nÀ Souccot : Que le Miséricordieux dresse pour nous la cabane de David tombée.",
        "В новом месяце: да обновит для нас Милостивый этот месяц ко благу и благословению.\nНа Суккот: да восстановит для нас Милostивый палатку павшего David.",
    ),
    "Ashkenaz — Half Hallel:\nRecite the blessings before Half Hallel on Rosh Chodesh (Mishnah Berurah 422:8).": T(
        "Ashkenaz — Half Hallel:\nLe'omar brachot lifnei Half Hallel beRosh Chodesh (Mishnah Berurah 422:8).",
        "Ashkenaz — Half Hallel:\nRecita las bendiciones antes del Half Hallel en Rosh Jodesh (Mishnah Berurah 422:8).",
        "Ashkenaz — Half Hallel :\nRécitez les bénédictions avant le Half Hallel à Roch 'Hodech (Mishna Beroura 422:8).",
        "Ashkenaz — Half Hallel:\nПроизнесите благословения перед Half Hallel в Rosh Chodesh (Mishnah Berurah 422:8).",
    ),
}
