"""Hand-reviewed Hebrew for long Shabbat + Sukkot guide paragraphs."""

from __future__ import annotations

FIXES: dict[str, str] = {
    "Shabbat is the holiest day of the week — the Jewish Sabbath. It begins at sunset on Friday and ends when three stars appear on Saturday night (approximately 25 hours).\n\nWhat to prepare before Shabbat:\n1. Cooking: All cooking must be done before Shabbat begins. A blech (a metal sheet covering the stove flame) or a pre-set hot plate keeps food warm on Shabbat without cooking.\n2. Timers: Electric lights, the hot plate, and other appliances can be left on or set to turn on/off using a Shabbos timer (pre-set before Shabbat).\n3. Lay out what you need: siddur (prayer book), Chumash (Torah book), clothes, children's items — anything you will want.\n4. Candles: Light Shabbat candles 18 minutes before sunset (see next item).\n\nOn Shabbat — things we do NOT do:\n• Write, draw, or erase\n• Cook, bake, or light fire\n• Turn electricity on or off (including phones, lights, and appliances)\n• Drive or ride in a motorized vehicle\n• Handle money or engage in commerce\n\nOn Shabbat — what we DO:\n• Attend synagogue for Friday night and Saturday morning services\n• Say Kiddush — a blessing over wine sanctifying Shabbat\n• Eat three festive meals (Friday night, Saturday afternoon, and a third before nightfall)\n• Study Torah, sing Shabbat songs (zemiroth), rest, and spend time with family": (
        "השבת היא היום הקדוש בשבוע. מתחילה בשקיעה ביום שישי ומסתיימת בצאת שלושה כוכבים (כ-25 שעות).\n\nהכנה לפני שבת:\n1. בישול: הכל לפני כניסת שבת. פלטה או שמירת חום מראש.\n2. טיימרים: אורות ומכשירים — טיימר שבת מוקדם.\n3. הכינו: סידור, חומש, בגדים, ציוד ילדים.\n4. נרות: 18 דקות לפני שקיעה.\n\nאסור בשבת: כתיבה, בישול, חשמל, נסיעה ברכב, כסף ומסחר.\n\nעושים בשבת: תפילה, קידוש, שלוש סעודות, לימוד תורה, זמירות, מנוחה ומשפחה."
    ),
    "Sukkot begins on 15 Tishrei and lasts seven days (in the Diaspora, the first two days are full Yom Tov, followed by five days of Chol HaMoed). It commemorates the 40 years the Jewish people dwelt in the desert under G-d's protection.\n\nKey observances:\n• Dwelling in a sukkah (a temporary outdoor booth with a roof of natural plant material) — at minimum, eating meals there\n• Taking the Arba Minim (Four Species): lulav (palm branch), etrog (citron), hadassim (myrtle), aravot (willow)\n\nArba Minim — by nusach:\n• Ashkenaz / most Sefard: waved in six directions (east, south, west, north, up, down) during Hallel; bracha on the first day (and in Chutz LaAretz, also on the second day of Yom Tov)\n• Chabad: hold lulav in right hand, etrog in left; wave in the same six directions plus some add an extra motion; follow your Chabad siddur\n• Yemenite (Baladi): may bind aravot differently and follow distinct waving customs — ask your community\n• Not taken on Shabbat; in Israel, the first day is the primary Torah obligation; in Chutz LaAretz, the first two Yom Tov days\n\nHallel:\n• Full Hallel every day of Sukkot in most communities\n• Some Yemenite and other traditions differ on certain days — follow your siddur": (
        "סוכות מתחילה בט\"ו בתשרי שבעה ימים (בגולה: שני ימים יום טוב וחמשה חול המועד). מזכירה 40 שנה במדבר תחת הגנת ה'.\n\nמצוות עיקריות: ישיבה בסוכה (לפחות סעודות); ארבעת המינים.\n\nלפי נוסח: אשכנז/ספרד — נענוע בששה כיוונים בהלל; ברכה ביום ראשון (ובחו\"ל גם ביום ב'). חב\"ד — לולב בימין, אתרוג בשמאל; לפי סידור חב\"ד. תימני — שאלו קהילה. לא בשבת.\n\nהלל: מלא ברוב קהילות — לפי סידורכם."
    ),
}
