# UI / descriptive overrides for es, fr, ru (key -> {es, fr, ru})
UI: dict[str, dict[str, str]] = {
    "No": {"es": "No", "fr": "Non", "ru": "Нет"},
    "Back": {"es": "Atrás", "fr": "Retour", "ru": "Назад"},
    "Done": {"es": "Listo", "fr": "Terminé", "ru": "Готово"},
    "Next": {"es": "Siguiente", "fr": "Suivant", "ru": "Далее"},
    "Skip": {"es": "Omitir", "fr": "Passer", "ru": "Пропустить"},
    "About": {"es": "Acerca de", "fr": "À propos", "ru": "О приложении"},
    "Clear": {"es": "Borrar", "fr": "Effacer", "ru": "Очистить"},
    "Close": {"es": "Cerrar", "fr": "Fermer", "ru": "Закрыть"},
    "CLOSE": {"es": "CERRAR", "fr": "FERMER", "ru": "ЗАКРЫТЬ"},
    "Cancel": {"es": "Cancelar", "fr": "Annuler", "ru": "Отмена"},
    "Male": {"es": "Hombre", "fr": "Homme", "ru": "Мужской"},
    "Female": {"es": "Mujer", "fr": "Femme", "ru": "Женский"},
    "else": {"es": "otro", "fr": "autre", "ru": "другое"},
    "Great!": {"es": "¡Genial!", "fr": "Super !", "ru": "Отлично!"},
    "‹ Back": {"es": "‹ Atrás", "fr": "‹ Retour", "ru": "‹ Назад"},
    "Activity": {"es": "Actividad", "fr": "Activité", "ru": "Активность"},
    "Settings": {"es": "Ajustes", "fr": "Réglages", "ru": "Настройки"},
    "BLESSED!!": {"es": "¡BENDITO!!", "fr": "BÉNI !!", "ru": "БЛАГОСЛОВЕН!!"},
    "Clear All": {"es": "Borrar todo", "fr": "Tout effacer", "ru": "Очистить всё"},
    "Text Size": {"es": "Tamaño del texto", "fr": "Taille du texte", "ru": "Размер текста"},
    "Text size": {"es": "Tamaño del texto", "fr": "Taille du texte", "ru": "Размер текста"},
    "Disclaimer": {"es": "Aviso legal", "fr": "Avertissement", "ru": "Отказ от ответственности"},
    "Guidelines": {"es": "Guías", "fr": "Directives", "ru": "Руководство"},
    "Mazel Tov!": {"es": "¡Mazal Tov!", "fr": "Mazal Tov !", "ru": "Мазал тов!"},
    "Mitzvah Me": {"es": "Mitzvá conmigo", "fr": "Mitzvah moi", "ru": "Мицва мне"},
    "Explanation": {"es": "Explicación", "fr": "Explication", "ru": "Пояснение"},
    "Parsha: $it": {"es": "Parashá: $it", "fr": "Paracha : $it", "ru": "Параша: $it"},
    "Search city": {"es": "Buscar ciudad", "fr": "Rechercher une ville", "ru": "Поиск города"},
    "Torah Study": {"es": "Estudio de Torá", "fr": "Étude de la Torah", "ru": "Изучение Торы"},
    "Torah study": {"es": "Estudio de Torá", "fr": "Étude de la Torah", "ru": "Изучение Торы"},
    "Upon waking": {"es": "Al despertar", "fr": "Au réveil", "ru": "При пробуждении"},
    "Cancel timer": {"es": "Cancelar temporizador", "fr": "Annuler le minuteur", "ru": "Отменить таймер"},
    "Daily Prayer": {"es": "Oración diaria", "fr": "Prière quotidienne", "ru": "Ежедневная молитва"},
    "Learn more ↗": {"es": "Más información ↗", "fr": "En savoir plus ↗", "ru": "Подробнее ↗"},
    "About Tzitzit": {"es": "Acerca de los tzitzit", "fr": "À propos des tsitsit", "ru": "О цицит"},
    "Current Level": {"es": "Nivel actual", "fr": "Niveau actuel", "ru": "Текущий уровень"},
    "Kashrut Timer": {"es": "Temporizador de kashrut", "fr": "Minuteur cacher", "ru": "Таймер кашрута"},
    "Makeup prayer": {"es": "Oración de compensación", "fr": "Prière de rattrapage", "ru": "Дополнительная молитва"},
    "Open Settings": {"es": "Abrir ajustes", "fr": "Ouvrir les réglages", "ru": "Открыть настройки"},
    "Times for $it": {"es": "Horarios de $it", "fr": "Horaires pour $it", "ru": "Время для $it"},
    "About Tefillin": {"es": "Acerca de los tefilín", "fr": "À propos des téfilines", "ru": "О тфилин"},
    "Evening Prayer": {"es": "Oración de la tarde", "fr": "Prière du soir", "ru": "Вечерняя молитва"},
    "Motzei Shabbat": {"es": "Motzei Shabat", "fr": "Motzei Chabbat", "ru": "Моцэи Шаббат"},
    "Loading song...": {"es": "Cargando canción...", "fr": "Chargement de la chanson...", "ru": "Загрузка песни..."},
    "Ongoing mitzvot": {"es": "Mitzvot en curso", "fr": "Mitzvot en cours", "ru": "Текущие мицвот"},
    "Select Language": {"es": "Seleccionar idioma", "fr": "Choisir la langue", "ru": "Выбрать язык"},
    "Shabbat guide ›": {"es": "Guía de Shabat ›", "fr": "Guide du Chabbat ›", "ru": "Путеводитель по Шаббату ›"},
    "Your wait times": {"es": "Tiempos de espera", "fr": "Vos temps d'attente", "ru": "Время ожидания"},
    "Afternoon Prayer": {"es": "Oración de la tarde (Minjá)", "fr": "Prière de l'après-midi (Min'ha)", "ru": "Минха (дневная молитва)"},
    "It's Shabbat Now": {"es": "Ahora es Shabat", "fr": "C'est Chabbat maintenant", "ru": "Сейчас Шаббат"},
    "Tzaddik Alert!!!": {"es": "¡Alerta de Tzaddik!!!", "fr": "Alerte Tsaddik !!!", "ru": "Оповещение Цадик!!!"},
    "Brought to you by": {"es": "Presentado por", "fr": "Présenté par", "ru": "Представлено"},
    "Language Settings": {"es": "Ajustes de idioma", "fr": "Réglages de langue", "ru": "Настройки языка"},
    "✓ You may now eat": {"es": "✓ Ya puede comer", "fr": "✓ Vous pouvez manger", "ru": "✓ Теперь можно есть"},
    "Add custom mitzvah": {"es": "Añadir mitzvá personalizada", "fr": "Ajouter une mitzvah personnelle", "ru": "Добавить свою мицву"},
    "Eating & Blessings": {"es": "Comida y bendiciones", "fr": "Repas et bénédictions", "ru": "Еда и благословения"},
    "Enable Translation": {"es": "Activar traducción", "fr": "Activer la traduction", "ru": "Включить перевод"},
    "Family Purity Laws": {"es": "Leyes de pureza familiar", "fr": "Lois de pureté familiale", "ru": "Законы семейной чистоты"},
    "Loading checklist…": {"es": "Cargando lista…", "fr": "Chargement de la liste…", "ru": "Загрузка списка…"},
    "Shabbat & Holidays": {"es": "Shabat y festividades", "fr": "Chabbat et fêtes", "ru": "Шаббат и праздники"},
    "Translate the app!": {"es": "¡Traduce la aplicación!", "fr": "Traduisez l'application !", "ru": "Переведите приложение!"},
    "What did you have?": {"es": "¿Qué comió?", "fr": "Qu'avez-vous pris ?", "ru": "Что вы ели?"},
    "What is Shabbat?": {"es": "¿Qué es Shabat?", "fr": "Qu'est-ce que le Chabbat ?", "ru": "Что такое Шаббат?"},
    "What's a Mitzvah?": {"es": "¿Qué es una mitzvá?", "fr": "Qu'est-ce qu'une mitzvah ?", "ru": "Что такое мицва?"},
    "Jewish Holidays": {"es": "Fiestas judías", "fr": "Fêtes juives", "ru": "Еврейские праздники"},
    "Your Profile": {"es": "Su perfil", "fr": "Votre profil", "ru": "Ваш профиль"},
    "Return to Mitz Mode?": {"es": "¿Volver a Mitz Mode?", "fr": "Revenir au Mitz Mode ?", "ru": "Вернуться в Mitz Mode?"},
    "Location Access Needed": {"es": "Se necesita acceso a la ubicación", "fr": "Accès à la localisation requis", "ru": "Нужен доступ к местоположению"},
}
