# -*- coding: utf-8 -*-
"""Write human-quality local_003 translations for all 4 languages."""
import json
from pathlib import Path

OUT = Path(r"c:\apps\hehehe\be-a-tzaddik\data\translation-catalog\human")

HE = [
    "לכו בדרכיו של ה'! 👣 הרמב\"ם חושף בהלכות דעות: כשם שה' הוא רחום — גם אתם היו רחומים; כשם שהוא חנון — גם אתם חנונים; כשם שהוא קדוש — גם אתם קדושים. הנה המפתח: מצאו את דרך האמצע בכל תכונותיכם — לא קשים מדי, לא רכים מדי. המשימה של היום: בחרו תכונה אלוקית אחת (חסד, קדושה או רחמים) והתמקדו באמת להפוך לכאלה!",
    "בחרו את חבריכם בחוכמה! 🤝 הרמב\"ם מלמד לקח חיים מכריע: אדם מושפע באופן טבעי מהתנהגות ומהדעות של חבריו. לכן מצווה להתחבר לצדיקים וללמוד מדרכיהם! האתגר שלכם: בלו היום זמן או שוחחו עם מישהו שמעורר בכם להיות טובים יותר. התכונות הטובות שלו ידבקו גם בכם!",
    "כפילו את האהבה! ❤️ הרמב\"ם מסביר שתי מצוות יפות: אהבת ישראל והראיית אהבה מיוחדת לגרים. למה אהבה נוספת לגרים? הם בחרו להצטרף לעמנו וללכת בדרכי התורה — זה מדהים! הנה משהו מעשי: השקיעו היום מאמץ נוסף להראות אהבה ליהודי אחר במעשה — בין אם נולד כך או בחר בכך!",
    "גלו את האות ד' (ד)! 🚪 צורת האות הזו מלמדת על ענווה — היא כפופה, כמו מי שצנוע. שמה פירושו \"דלת\" בעברית, ומזכיר לנו שענווה היא הדלת לכל צמיחה רוחנית. ידעתם? גימטריית הד' היא 4, וקשורה ל-4 רוחות העולם — מראה שאדם עניו פתוח ללמוד מכולם! קחו רגע לתרגל ענווה היום על ידי למידת משהו חדש ממישהו אחר.",
    "שמרו על לבכם משנאה! ❤️ התורה מלמדת משהו עמוק: גם אם מישהו פגע בכם, אל תאחסנו שנאה בלב. במקום זה — דברו איתו על מה שמטריד אתכם! ידעתם? המילה \"שנאה\" ו\"שינה\" חולקות את אותן האותיות — שנאה גורמת לנו להיות \"רדומים\" רוחנית. המשימה שלכם: אם אתם מרגישים שליליות כלפי מישהו, נסו שיחה כנה ומכבדת, או פנו לרב להדרכה.",
    "שלטו באמנות התוכחה מאהבה! 💝 התורה נותנת כלי מדהים: אם אתם רואים מישהו עושה משהו לא נכון — אל תשתקו ואל תרכלו; עזרו לו לגדול! המפתח: דברו בפרטיות, בעדינות, והבהירו שאתם באים ממקום של אהבה. ידעתם? \"תוכחה\" קשורה ל\"הוכחה\" — לעזור לאחרים לראות הוכחה לדרך טובה יותר! האתגר של היום: אם צריך לתת משוב — עשו זאת בחסד ובחוכמה.",
    "גלו את האות המיסטית ה' (ה)! ✡ האות העוצמתית הזו מייצגת את נוכחות ה' בעולמנו! צורתה מלמדת: יש לה פתח למטה — גם אם נפלנו, תמיד אפשר לחזור לה'. ידעתם? האות ה' מופיעה פעמיים בשם ה' — מלמדת שה' נוכח גם בעולם הרוחני וגם בגשמי! קחו רגע לשים לב לנוכחות ה' בחייכם היום.",
    "הראו תשומת לב מיוחדת למי שזקוק לכך ביותר! 🤗 התורה נותנת מצווה מיוחדת להיות עדינים במיוחד עם אלמנות ויתומים. למה? כי חוו אובדן ועלולים להרגיש פגיעים יותר. משהו עוצמתי: הגמרא מלמדת שה' עצמו הוא שומרם! כשאתם עוזרים להם — אתם שותפים לה'! המשימה של היום: הראו חסד נוסף למישהו שעלול להרגיש בודד או פגיע.",
    "שמרו על לשונכם! 👄 כוח הדיבור מדהים — הוא יכול לבנות עולמות או להרוס אותם! ידעתם? גימטריית \"דיבור\" שווה לגימטריית \"דבורה\" — כמו דבורה שיכולה לייצר דבש או לעקוץ, גם מילותינו יכולות להיות מתוקות או מזיקות! האתגר של היום: לפני שמדברים על אחרים, שאלו: האם זה אמת? האם זה נחמד? האם זה הכרחי? הפכו את מילותיכם לדבש!",
    "התעלו מעל נקמה! 🌅 התורה מלמדת: אל תקחו נקמה, גם כשיש לכם הזדמנות! דוגמה קלאסית: אם מישהו סירב להלוות לכם, ואחר כך הוא מבקש מכם — אל תגידו \"לא, בדיוק כמו שעשית לי!\" במקום זה — עזרו לו! ידעתם? מצווה זו עוזרת לנו להיות יותר כמו ה', שנותן טוב גם למי שלא מגיע לו. האתגר של היום: עשו משהו נחמד למישהו שלא היה נחמד אליכם.",
    "שחררו טינות! 🕊️ הנה מצווה מדהימה: גם אם אינכם נוקמים — אל תחזיקו את הכאב! דוגמה מהתורה: כשמישהו מבקש לשאול — אל תגידו \"בטח, אני לא כמוך שסירבת לי!\" — פשוט הלוו בלב שלם! ידעתם? להחזיק טינה כמו לשתות רעל ולקוות שהאחר יחלה. שחררו את עצמכם! המשימה של היום: החליפו טינה בברכה.",
    "אמצו את מתנת לימוד התורה! 📚 הרמב\"ם חושף: לימוד תורה הוא לא רק ידע — זו התחברות לחכמת ה'! ידעתם? כל מילה של תורה שאתם לומדים יוצרת מלאך שילווה אתכם לנצח! המשימה שלכם: הקדישו היום אפילו 5 דקות ללמוד משהו חדש — פסוק, הלכה או סיפור. כל רגע לימוד הוא יקר!",
    "כבדו מורי תורה! 👨‍🏫 הרמב\"ם מלמד: מורה תורה כמו הורה שנותן לנו חיים נצחיים! ידעתם? הכבוד למורה תורה כה גדול, שאם גם אביכם וגם מורה תורה נושאים משא כבד — עוזרים קודם למורה (אלא אם האב גם תלמיד חכם)! המשימה של היום: הראו הערכה למי שלימד אתכם תורה — בהודעה, בשיחה או במתנה קטנה.",
    "גלו את האות ו' (ו)! ✡ האות המדהימה הזו דמוית וו, המחברת שמיים וארץ! ידעתם? \"ו\" פירושו \"ו\" — מלמד שכל הבריאה מחוברת! גימטרייתה 6, מייצגת ששת ימי הבריאה. משהו מגניב: כשמוסיפים ו' בתחילת פועל עברי, הוא הופך לעבר — מראה שה' חורג מזמן! קחו רגע לשים לב לקשרים בחייכם.",
    "חוו את כוח המזוזה! 🏠 הרמב\"ם מסביר: בכל מעבר ליד מזוזה, היא מזכירה את נוכחות ה' ומעירה אותנו משינה רוחנית! המילה \"מזוזה\" שווה 65 בגימטריה — כמו \"היכל\", חדר/ארמון. הקשר מרמז שהמזוזה הופכת בית למקדש מini — מקום לשכינה. בנוסף, טקסט המזוזה מכיל 713 אותיות — גימטריית \"תשובה\".",
    "למדו על מצוות כתיבת ספר תורה! ✍️ לכל גבר יהudi יש מצווה לכתוב (או לפי דעות, לשתף בכתיבת) ספר תורה! יש אומרים שאפשר לקיים זאת היום בקניית ספרים כמו חumash, tanach וספרים קדושים אחרים. כל אות בתורה מתאימה לנשמה יehudit — אות אחת חסרה פוסלת את כל הס\"ת, ומראה כמה כל יehudi חשוב!",
    "עטרו את עצמכם בתורה! 👑 הרמב\"ם מלמד: מלך יehudi חייב לכתוב שני ספרי תורה — אחד לאוצר ואחד שלא יעזוב אותו! הלקח: לא משנה כמה אתם ע busyים או חזקים — התורה צריכה להיות בן זוג קבוע! ידעתם? המלך קרא מס\"תו בכל יום — מלמד לקבוע זמן לימוד יומי! המשימה שלכם: קבעו זמן קבוע ללימוד, גם אם רק כמה דקות.",
    "התאספו להשראה! 👥 למדו על מצוות ההakhel המיוחדת! כל שבע שנים התאסף כל העם — גברים, נשים וילדים — לשמוע את המלך קורא בתורה! משהו מדהים: הביאו גם תינוקות, וההורים זכו בשכר מיוחד! הלקח? לפעמים רק הנוכחות בקהילה קדושה מעלה את הנשמה! המשימה של היום: הצטרפו לשיעור תורה או התgathering, גם אם באינטרנט.",
    "גלו את האות ז' (ז)! ✡ האות העוצמתית נראית כמו כתר עם חרב מצביעה למטה! ידעתם? \"זין\" פירושו \"נשק\" — התורה היא נשקנו הרוחני נגד שליליות! גימטרייתה 7, קשורה לשבת, היום השביעי. צורת הז' מלמדת לכתור את מעשינו הגשמיים במטרה רוחנית! קחו רגע להעלות פעילות גשמית בכוונה קדושה.",
    "למדו על איסור עבודה זרה! 🛡️ הרמב\"ם מסביר: זה לא רק פסלים — זה כל דבר שאנחנו שמים לפני ה'! ידעתם? כשאנחנו מתנגדים לפולחן של כסף, תהילה או \"אלים\" מזויפים — אנחנו מעידים שה' הוא הכוח האמיתי היחיד! האתגר של היום: זהו משהו שאולי העליתם יותר מדי, וקחו צעד לשים את ה' בראש.",
    "שמרו על דיבורכם על ה'! 🗣️ הרמב\"ם מלמד בהלכות עבודה זרה: חייבים להיזהר שלא לדבר בזלזול על ה' או להכחיש את קיומו. גם שבועות או ברכות מיותרות אסורות. משהו עוצמתי: כל מילה על ה' צריכה להיות ביראה. המשימה של היום: דברו על עניינים קדושים בזהירות ובכבוד מוגבר.",
    "שמרו את ביתכם מדברים אסורים! 🎨 הרמב\"ם מלמד: יש להיזהר מסוגי תמונות מסוימים — פסלי דמויות אנושיות בולטות אסורים, ואסור ליצור תמונות של מערכת השמש או מלאכים! חלק מחמירים גם לבובות, רבים מקילים. המשימה של היום: שימו לב לשמור את הבית נקי מתמונות בעייתיות!",
    "גלו את האות ט' (ט)! ✡ האות המדהימה מייצגת טוב — היא האות הראשונה במילה \"טוב\" בתורה! ידעתם? צורתה כפופה פנימה — טוב אמיתי לעיתים נסתר וצנוע. גימטרייתה 9, מייצגת 9 חודשי הריון — זמן שבו טוב נסתר גדל! קחו רגע לשים לב לברכות הנסתרות בחייכם.",
    "גלו את כוח היוד (י)! ✡ האות הקטנה ביותר מחזיקה חכמה עצומה! גודלה מלמד ענווה, ובכל זאת היא האות הראשונה בשם ה'! ידעתם? היוד מייצגת נקודה אחת — גם מעשה טוב קטן יכול להשפיע ללא סוף! גימטרייתה 10, קשורה לעשרת הדיברות.",
    "חשפו את מסתורי הכ\"ף (כ)! 👑 במיסטיקה יehudit, הכ\"ף מייצגת כתר — לא כתר של גאווה! ידעתם? צורת הכ\"ף הכפופה (כ) מייצגת כריעה והכנעה, וגימטרייתה 20 — גיל שבו מתחיל מרדף החכמה. הכ\"ף הסופית (ך) מלמדת שהישג אמיתי בא דרך ענווה."
]

ES = [
    "¡Camina en los caminos de D-s! 👣 El Rambam revela en Hilchot De'ot: Así como D-s es misericordioso, tú también debes serlo. Así como Él es bondadoso, tú también. Así como Él es santo, tú también. La clave: encuentra el camino medio en todos tus rasgos — ni demasiado duro ni demasiado blando. Misión de hoy: elige un atributo divino (bondad, santidad o misericordia) y concéntrate en convertirte en ello.",
    "¡Elige tus amigos con sabiduría! 🤝 El Rambam enseña una lección crucial: una persona se ve naturalmente influenciada por el comportamiento y las opiniones de sus amigos. Por eso es una mitzvá conectarse con los justos y aprender de sus caminos. Tu reto: pasa tiempo hoy o charla con alguien que te inspire a ser mejor. ¡Sus buenas cualidades se contagiarán!",
    "¡Duplica tu amor! ❤️ El Rambam explica dos hermosas mitzvot: amar a los judíos y mostrar amor especial a los conversos (gerim). ¿Por qué amor extra hacia los conversos? ¡Eligieron unirse a nuestro pueblo y seguir la Torá! Algo práctico: haz un esfuerzo extra hoy por mostrar amor a otro judío con acciones — nacido judío o quien eligió unirse.",
    "¡Descubre la letra Dalet (ד)! 🚪 La forma de esta letra enseña humildad — está inclinada, como quien es modesto. Su nombre significa 'puerta' en hebreo, recordándonos que la humildad es la puerta a todo crecimiento espiritual. ¿Sabías? Su valor numérico es 4, conectado con las cuatro direcciones — ¡un humilde está abierto a aprender de todos! Practica humildad hoy aprendiendo algo nuevo de otra persona.",
    "¡Protege tu corazón del odio! ❤️ La Torá enseña algo profundo: aunque alguien te haya hecho daño, no guardes odio en el corazón. ¡Habla con esa persona sobre lo que te molesta! ¿Sabías? La palabra hebrea para odio (sina) comparte letras con la de sueño (sheinah) — el odio nos deja 'dormidos' espiritualmente. Misión: si sientes negatividad hacia alguien, intenta una conversación honesta y respetuosa, o consulta a un rabino.",
    "¡Domina el arte del reproche amoroso! 💝 La Torá nos da una herramienta increíble: si ves a alguien hacer algo mal, no te quedes callado ni chismes — ¡ayúdalo a crecer! La clave: habla en privado, con suavidad y deja claro que vienes desde el amor. ¿Sabías? 'Tochajá' (reproche) está relacionada con 'hojajá' (prueba) — ayudar a ver prueba de un camino mejor. Reto de hoy: da retroalimentación con bondad y sabiduría.",
    "¡Explora la mística letra Heh (ה)! ✡ ¡Esta letra poderosa representa la presencia de D-s en nuestro mundo! Su forma enseña: tiene una abertura abajo — aunque caigamos, siempre podemos volver a D-s. ¿Sabías? La Heh aparece dos veces en el Nombre de cuatro letras de D-s — presente en lo espiritual y lo físico. Nota la presencia de D-s en tu vida hoy.",
    "¡Muestra cuidado extra a quienes más lo necesitan! 🤗 La Torá nos manda ser especialmente gentiles con viudas y huérfanos. ¿Por qué? Han experimentado pérdida y pueden sentirse más vulnerables. Algo poderoso: ¡el Talmud enseña que D-s mismo es su guardián! Cuando los ayudas, te asocias con D-s. Misión de hoy: muestra bondad extra a alguien que pueda sentirse solo o vulnerable.",
    "¡Cuida tu lengua! 👄 El poder del habla es increíble — puede construir mundos o destruirlos. ¿Sabías? 'Dibur' (habla) y 'dvorah' (abeja) tienen el mismo valor numérico (gematria) — como la abeja puede hacer miel o picar, nuestras palabras pueden ser dulces o dañinas. Reto: antes de hablar de otros, pregúntate: ¿Es verdad? ¿Es amable? ¿Es necesario? ¡Haz tus palabras dulces como miel!",
    "¡Elévate por encima de la venganza! 🌅 La Torá enseña: no te vengues, ¡aunque tengas la oportunidad! Ejemplo clásico: si alguien se negó a prestarte algo y luego te lo pide — no digas '¡No, como tú conmigo!' ¡Ayúdalo! Esta mitzvá nos hace más parecidos a D-s, que da bien incluso a quien no lo merece. Reto: haz algo amable por quien no fue amable contigo.",
    "¡Suelta rencores! 🕊️ Una mitzvá asombrosa: aunque no te vengues, tampoco guardes el dolor. Ejemplo de la Torá: cuando alguien pide prestado, no digas 'Claro, no soy como tú que me negaste' — presta con corazón pleno. Guardar rencor es como beber veneno esperando que el otro enferme. ¡Libérate! Misión: reemplaza un rencor con una bendición.",
    "¡Abraza el regalo del estudio de Torá! 📚 El Rambam revela: aprender Torá no es solo conocimiento — ¡es conectar con la sabiduría de D-s! ¿Sabías? Cada palabra de Torá que aprendes crea un ángel que te acompañará para siempre. Misión: dedica hoy aunque sean 5 minutos a aprender algo nuevo — versículo, ley o historia. ¡Cada momento vale oro!",
    "¡Honra a los maestros de Torá! 👨‍🏫 El Rambam enseña: un maestro de Torá es como un padre que nos da vida eterna. ¿Sabías? El respeto es tan grande que si tu padre y tu maestro cargan algo pesado, ayudas primero al maestro (salvo que tu padre también sea erudito en Torá). Misión: muestra gratitud a quien te enseñó Torá — mensaje, llamada o pequeño regalo.",
    "¡Descubre la letra Vav (ו)! ✡ Esta letra parece un gancho que conecta cielo y tierra. ¿Sabías? 'Vav' significa 'y', enseñando que todo en la creación está conectado. Su valor es 6, los seis días de creación. Algo genial: añadir Vav al inicio de un verbo hebreo cambia futuro a pasado — ¡D-s trasciende el tiempo! Nota las conexiones en tu vida.",
    "¡Experimenta el poder de la Mezuzá! 🏠 El Rambam explica: cada vez que pasas junto a una mezuzá, recuerdas a D-s y despiertas del sueño espiritual. 'Mezuzá' vale 65 en gematria, igual que 'hekhal' (palacio) — sugiere que transforma la casa en un mini-palacio para la Presencia Divina. El texto tiene 713 letras, valor de 'teshuvá' (arrepentimiento).",
    "¡Aprende sobre la mitzvá de escribir un Sefer Torá! ✍️ Todo hombre judío tiene la mitzvá de escribir (o según algunas opiniones, participar en escribir) un rollo de Torá. Algunos dicen que hoy se cumple comprando libros como Jumash, Tanaj y otros sagrados. Cada letra corresponde a un alma judía; falta una letra e invalida todo el rollo — ¡cada judío importa!",
    "¡Corónate con Torá! 👑 El Rambam enseña: un rey judío debe escribir DOS rollos de Torá — uno para el tesoro y otro que nunca lo abandone. Lección: por poderoso o ocupado que estés, la Torá debe ser tu compañera constante. ¿Sabías? El rey leía cada día — ¡prioridad diaria de estudio! Misión: fija un horario de estudio, aunque sean pocos minutos.",
    "¡Reúnete para inspiración! 👥 Conoce la especial mitzvá de Hakhel: cada siete años, toda la nación — hombres, mujeres y niños — se reunía para oír al rey leer la Torá. ¡Incluso bebés venían y los padres recibían recompensa especial! A veces solo estar en una reunión santa eleva el alma. Misión: únete a una clase de Torá o reunión, aunque sea en línea.",
    "¡Descubre la letra Zayin (ז)! ✡ Parece una corona con espada apuntando abajo. ¿Sabías? 'Zayin' significa 'arma' — la Torá es nuestro arma espiritual contra la negatividad. Su valor es 7, conectado con Shabat. Su forma enseña a coronar acciones físicas con propósito espiritual. Eleva hoy una actividad física con intención santa.",
    "¡Aprende sobre la prohibición de idolatría! 🛡️ El Rambam explica: no es solo estatuas — ¡es cualquier cosa que pongamos antes que D-s! Cuando resistimos adorar dinero, fama u otros 'dioses', testificamos que D-s es el único poder verdadero. Reto: identifica algo demasiado importante en tu vida y da un paso para poner a D-s primero.",
    "¡Cuida tu habla sobre D-s! 🗣️ El Rambam en Hilchot Avodah Zarah: debemos evitar hablar con irreverencia de D-s o negar Su existencia. Juramentos casuales o bendiciones innecesarias también están prohibidos. Cada palabra sobre D-s debe ser con reverencia. Misión: habla de asuntos sagrados con cuidado y respeto extra.",
    "¡Protege tu hogar de cosas prohibidas! 🎨 El Rambam enseña cuidado con ciertas imágenes: figuras humanas salientes como estatuas están prohibidas; tampoco imágenes de cuerpos celestes o ángeles. Algunos extienden esto a muñecas; muchos son lenientes. Misión: mantén tu hogar libre de imágenes problemáticas.",
    "¡Descubre la letra Tet (ט)! ✡ Representa bondad — ¡primera letra de 'Tov' (bueno) en la Torá! Su forma curva hacia adentro enseña que el bien verdadero suele ser modesto y oculto. Valor 9, los nueve meses de embarazo — bondad oculta que crece. Nota hoy las bendiciones ocultas en tu vida.",
    "¡Explora el poder de Yud (י)! ✡ ¡La letra más pequeña con sabiduría inmensa! Su tamaño enseña humildad, pero es la primera letra del Nombre de D-s. Representa un punto — ¡un pequeño acto de bondad puede tener impacto infinito! Valor 10, los Diez Mandamientos.",
    "¡Descubre los misterios de Kaf (כ)! 👑 En la mística judía, Kaf representa Keter (corona) — ¡no de orgullo! La forma curvada (כ) es inclinarse con humildad; valor 20, edad en que comienza la búsqueda de sabiduría. La Kaf final (ך) enseña que el logro verdadero viene por humildad."
]

FR = [
    "Marchez dans les voies de D. ! 👣 Le Rambam révèle dans Hilchot De'ot : tout comme D. est miséricordieux, vous aussi soyez-le. Tout comme Il est bienveillant, vous aussi. Tout comme Il est saint, vous aussi. La clé : trouvez la voie médiane dans tous vos traits — ni trop dur, ni trop mou. Mission du jour : choisissez un attribut divin (bonté, sainteté ou miséricorde) et concentrez-vous pour l'incarner !",
    "Choisissez vos amis avec sagesse ! 🤝 Le Rambam enseigne une leçon cruciale : on est naturellement influencé par le comportement et les opinions de nos amis. C'est pourquoi c'est une mitzvah de se lier aux justes et d'apprendre de leurs voies ! Votre défi : passez du temps aujourd'hui ou discutez avec quelqu'un qui vous pousse à devenir meilleur. Ses bonnes qualités vous contamineront !",
    "Doublez votre amour ! ❤️ Le Rambam explique deux belles mitzvot : aimer ses coreligionnaires juifs et montrer un amour particulier aux convertis (guerim). Pourquoi un amour supplémentaire pour les convertis ? Ils ont choisi de rejoindre notre peuple et la Torah — c'est merveilleux ! Concret : faites un effort supplémentaire aujourd'hui pour montrer de l'amour à un autre Juif par des actes — qu'il soit né juif ou converti.",
    "Découvrez la lettre Dalet (ד) ! 🚪 La forme de cette lettre enseigne l'humilité — elle est courbée, comme quelqu'un de modeste. Son nom signifie « porte » en hébreu, rappelant que l'humilité est la porte de toute croissance spirituelle. Le saviez-vous ? Sa valeur numérique est 4, liée aux quatre directions — une personne humble est ouverte à apprendre de tous ! Pratiquez l'humilité aujourd'hui en apprenant quelque chose de nouveau auprès de quelqu'un d'autre.",
    "Gardez votre cœur contre la haine ! ❤️ La Torah nous enseigne quelque chose de profond : même si quelqu'un vous a fait du tort, ne gardez pas la haine dans votre cœur. Parlez-lui de ce qui vous préoccupe ! Le saviez-vous ? Le mot hébreu pour la haine (sina) partage les lettres de celui pour le sommeil (sheinah) — la haine nous endort spirituellement. Mission : si vous ressentez de la négativité envers quelqu'un, tentez une conversation honnête et respectueuse, ou consultez un rabbin.",
    "Maîtrisez l'art du reproche amoureux ! 💝 La Torah nous donne un outil merveilleux : si vous voyez quelqu'un faire mal, ne restez pas silencieux ni ne commérez — aidez-le à grandir ! La clé : parlez en privé, avec douceur, en montrant que vous agissez par amour. Le saviez-vous ? « To'hah' » (reproche) est lié à « hoha'ah' » (preuve) — aider l'autre à voir la preuve d'un meilleur chemin ! Défi du jour : donnez un retour avec bonté et sagesse.",
    "Explorez la lettre mystique Heh (ה) ! ✡ Cette lettre puissante représente la présence de D. dans notre monde ! Sa forme enseigne : elle a une ouverture en bas — même si nous tombons, nous pouvons toujours revenir à D. Le saviez-vous ? La Heh apparaît deux fois dans le Nom à quatre lettres de D. — présent dans les mondes spirituel et physique ! Remarquez la présence de D. dans votre vie aujourd'hui.",
    "Montrez une attention particulière à ceux qui en ont le plus besoin ! 🤗 La Torah nous commande d'être particulièrement doux avec les veuves et les orphelins. Pourquoi ? Ils ont connu la perte et peuvent se sentir plus vulnérables. Quelque chose de puissant : le Talmud enseigne que D. Lui-même est leur gardien ! Quand vous les aidez, vous vous associez à D. ! Mission : montrez une bonté supplémentaire à quelqu'un qui pourrait se sentir seul ou vulnérable.",
    "Gardez votre langue ! 👄 Le pouvoir de la parole est incroyable — elle peut construire des mondes ou les détruire ! Le saviez-vous ? « Dibour » (parole) et « dvorah » (abeille) ont la même valeur numérique (guematria) — comme l'abeille peut faire du miel ou piquer, nos mots peuvent être doux ou blessants ! Défi : avant de parler des autres, demandez-vous : Est-ce vrai ? Est-ce gentil ? Est-ce nécessaire ? Que vos paroles soient douces comme le miel !",
    "Élevez-vous au-dessus de la vengeance ! 🌅 La Torah enseigne : ne vous vengez pas, même quand vous en avez l'occasion ! Exemple classique : si quelqu'un a refusé de vous prêter quelque chose et vous le demande ensuite — ne dites pas « Non, comme tu as fait avec moi ! » Aidez-le ! Cette mitzvah nous rend plus semblables à D., qui donne le bien même à l'indigne. Défi : faites quelque chose de gentil pour quelqu'un qui ne l'a pas été envers vous.",
    "Lâchez prise sur les rancunes ! 🕊️ Une mitzvah merveilleuse : même si vous ne vous vengez pas, ne gardez pas la blessure non plus ! Exemple de la Torah : quand quelqu'un demande à emprunter, ne dites pas « Bien sûr, je ne suis pas comme toi qui m'as refusé » — prêtez de bon cœur ! Garder rancune, c'est boire du poison en espérant que l'autre tombe malade. Libérez-vous ! Mission : remplacez une rancune par une bénédiction.",
    "Accueillez le don de l'étude de la Torah ! 📚 Le Rambam révèle : apprendre la Torah n'est pas seulement acquérir des connaissances — c'est se connecter à la sagesse de D. ! Le saviez-vous ? Chaque mot de Torah que vous apprenez crée un ange qui vous accompagnera pour toujours ! Mission : consacrez aujourd'hui ne serait-ce que 5 minutes à apprendre quelque chose de nouveau — verset, loi ou récit. Chaque instant compte !",
    "Honorez les enseignants de Torah ! 👨‍🏫 Le Rambam enseigne : un maître de Torah est comme un parent qui nous donne la vie éternelle ! Le saviez-vous ? Le respect dû à un enseignant est si grand que si votre père et votre maître portent tous deux une charge lourde, vous aidez d'abord le maître (sauf si votre père est aussi érudit en Torah) ! Mission : montrez votre gratitude à celui qui vous a enseigné la Torah — message, appel ou petit cadeau.",
    "Découvrez la lettre Vav (ו) ! ✡ Cette lettre ressemble à un crochet reliant ciel et terre ! Le saviez-vous ? « Vav » signifie « et », enseignant que toute la création est connectée ! Sa valeur est 6, les six jours de la création. Quelque chose de cool : ajouter un Vav au début d'un verbe hébreu transforme le futur en passé — D. transcende le temps ! Remarquez les connexions dans votre vie.",
    "Vivez la puissance de la Mezouza ! 🏠 Le Rambam explique : chaque passage près d'une mezouza rappelle D. et vous réveille du sommeil spirituel ! « Mezouza » vaut 65 en guematria, comme « hekhal » (palais) — suggérant qu'elle transforme la maison en mini-palais pour la Présence divine. Le texte contient 713 lettres, valeur de « teshouva' » (repentir).",
    "Apprenez la mitzvah d'écrire un Sefer Torah ! ✍️ Tout homme juif a la mitzvah d'écrire (ou, selon certains, de participer à l'écriture d') un rouleau de Torah ! Certains disent qu'aujourd'hui on peut l'accomplir en achetant des livres comme Joumash, Tanakh et autres livres saints. Chaque lettre correspond à une âme juive ; une lettre manquante invalide tout le rouleau — chaque Juif compte !",
    "Couronnez-vous de Torah ! 👑 Le Rambam enseigne : un roi juif doit écrire DEUX rouleaux de Torah — un pour le trésor et un qui ne le quitte jamais ! Leçon : aussi puissant ou occupé que vous soyez, la Torah doit être votre compagne constante ! Le saviez-vous ? Le roi lisait chaque jour — priorité quotidienne d'étude ! Mission : fixez un moment d'étude, même quelques minutes.",
    "Rassemblez-vous pour l'inspiration ! 👥 Découvrez la mitzvah spéciale de Hakhel ! Tous les sept ans, toute la nation — hommes, femmes et enfants — se rassemblait pour entendre le roi lire la Torah ! Même les bébés venaient, et les parents recevaient une récompense spéciale ! Parfois, être présent dans une assemblée sainte élève l'âme ! Mission : rejoignez un cours de Torah ou un rassemblement, même en ligne.",
    "Découvrez la lettre Zayin (ז) ! ✡ Cette lettre ressemble à une couronne avec une épée pointant vers le bas ! Le saviez-vous ? « Zayin » signifie « arme » — la Torah est notre arme spirituelle contre la négativité ! Sa valeur est 7, liée au Chabbat. Sa forme enseigne à couronner nos actions physiques d'un but spirituel ! Élevez aujourd'hui une activité physique par une intention sainte.",
    "Apprenez l'interdiction de l'idolâtrie ! 🛡️ Le Rambam explique : ce n'est pas seulement les statues — c'est tout ce que nous mettons avant D. ! Quand nous résistons à adorer l'argent, la gloire ou de faux « dieux », nous témoignons que D. est le seul vrai pouvoir ! Défi : identifiez quelque chose de trop important dans votre vie et faites un pas pour mettre D. en premier.",
    "Surveillez votre parole à propos de D. ! 🗣️ Le Rambam enseigne dans Hilchot Avodah Zarah : ne jamais parler avec irreverence de D. ni nier Son existence. Serments futiles ou bénédictions inutiles sont interdits. Chaque mot sur D. doit être empreint de crainte révérencielle. Mission : parlez des sujets saints avec soin et respect accru.",
    "Protégez votre maison des choses interdites ! 🎨 Le Rambam enseigne la prudence avec certains types d'images : les figures humaines saillantes comme statues sont interdites ; on ne peut pas non plus faire d'images de corps célestes ou d'anges ! Certains étendent cela aux poupées ; beaucoup sont indulgents. Mission : veillez à garder votre maison libre d'images problématiques !",
    "Découvrez la lettre Tet (ט) ! ✡ Cette lettre représente la bonté — première lettre du mot « Tov » (bon) dans la Torah ! Sa forme courbée vers l'intérieur enseigne que le vrai bien est souvent caché et modeste. Valeur 9, les neuf mois de grossesse — un bien caché qui grandit ! Remarquez aujourd'hui les bénédictions cachées dans votre vie.",
    "Explorez la puissance du Yud (י) ! ✡ La plus petite lettre recèle une sagesse immense ! Sa taille enseigne l'humilité, yet c'est la première lettre du Nom saint de D. ! Le saviez-vous ? Le Yud représente un point — même le plus petit acte de bonté peut avoir un impact infini ! Valeur 10, les Dix Commandements.",
    "Découvrez les mystères du Kaf (כ) ! 👑 Dans la mystique juive, le Kaf représente Keter (couronne) — mais pas celle de l'orgueil ! La forme courbée (כ) symbolise l'inclinaison humble ; valeur 20, l'âge où commence la quête de sagesse. Le Kaf final (ך) enseigne que le vrai accomplissement vient par l'humilité."
]

RU = [
    "Идите путями Hashem! 👣 Рамбам в Hilchot De'ot раскрывает: как Hashem милостив — будьте и вы милостивы; как Он благ — будьте благими; как Он свят — будьте святы. Ключ: найдите золотую середину во всех чертах — не слишком жёстко, не слишком мягко. Задание на сегодня: выберите одно божественное качество (доброта, святость или милость) и сосредоточьтесь стать им!",
    "Выбирайте друзей мудро! 🤝 Рамбам учит важному уроку: человек естественно подвержен влиянию поведения и мнений друзей. Поэтому mitzvah — общаться с праведниками и учиться у них! Ваш вызов: проведите время или поговорите сегодня с тем, кто вдохновляет вас быть лучше. Их хорошие качества передадутся и вам!",
    "Удвойте любовь! ❤️ Рамбам объясняет две прекрасные mitzvot: любовь к евреям и особая любовь к герам (обращённым). Почему дополнительная любовь к герам? Они выбрали присоединиться к нашему народу и следовать Торе — это удивительно! Практика: приложите сегодня дополнительные усилия, чтобы проявить любовь к другому еврею делом — рождённому или выбравшему путь!",
    "Откройте букву Dalet (ד)! 🚪 Форма этой буквы учит смирению — она согнута, как скромный человек. Её имя значит «дверь» по-еврейски, напоминая, что смирение — дверь ко всему духовному росту. Знаете ли вы? Числовое значение Dalet — 4, связано с четырьмя сторонами света — смиренный открыт учиться у всех! Практикуйте смирение сегодня, узнав что-то новое от другого.",
    "Берегите сердце от ненависти! ❤️ Тора учит глубокому: даже если кто-то причинил вам боль, не храните ненависть. Вместо этого — поговорите о том, что беспокоит! Знаете ли вы? Слово «sina» (ненависть) и «sheinah» (сон) имеют одни буквы — ненависть делает нас духовно «спящими». Задание: если чувствуете негатив к кому-то, попробуйте честный уважительный разговор или обратитесь к раввину.",
    "Овладейте искусством любящего упрека! 💝 Тора даёт удивительный инструмент: видите, что кто-то поступает неправильно — не молчите и не сплетничайте, помогите расти! Ключ: говорите наедине, мягко, показывая, что действуете из любви. Знаете ли вы? «Tochachah» (упрек) связана с «hochachah» (доказательство) — помочь увидеть доказательство лучшего пути! Вызов: давая обратную связь, делайте это с добротой и мудростью.",
    "Исследуйте мистическую букву Heh (ה)! ✡ Эта могущественная буква представляет присутствие Hashem в мире! Её форма учит: внизу открытие — даже упав, мы можем вернуться к Hashem. Знаете ли вы? Heh дважды в Имени Hashem — присутствие в духовном и физическом! Заметьте присутствие Hashem в жизни сегодня.",
    "Проявляйте особую заботу к нуждающимся больше всех! 🤗 Тора даёт особую mitzvah быть особенно нежными с вдовами и сиротами. Почему? Они пережили потерю и могут чувствовать себя уязвимее. Мощно: Тalmud учит, что Hashem Сам их защитник! Помогая им, вы сотрудничаете с Hashem! Задание: проявите дополнительную доброту к тому, кто может чувствовать себя одиноким или уязвимым.",
    "Берегите язык! 👄 Сила речи невероятна — она может строить миры или разрушать! Знаете ли вы? «Dibur» (речь) и «dvorah» (пчела) имеют одинаковую gematria — как пчела может дать мёд или ужалить, слова могут быть сладкими или вредными! Вызов: прежде чем говорить о других, спросите: правда ли? добро ли? необходимо ли? Пусть слова будут сладки, как мёд!",
    "Поднимитесь над местью! 🌅 Тора учит: не мстите, даже когда есть возможность! Классический пример: если кто-то отказал одолжить, а потом просит у вас — не говорите «Нет, как ты со мной!» Помогите! Эта mitzvah делает нас ближе к Hashem, Который даёт добро даже не достойным. Вызов: сделайте что-то доброе для того, кто был недобр к вам.",
    "Отпустите обиды! 🕊️ Удивительная mitzvah: даже не мстя, не держите боль! Пример Торы: когда просят одолжить — не говорите «Конечно, я не как ты, отказавший мне» — одолжите от всего сердца! Держать обиду — как пить яд, надеясь, что заболеет другой. Освободите себя! Задание: замените обиду благословением.",
    "Примите дар изучения Торы! 📚 Рамбам раскрывает: изучение Торы — не просто знания, а связь с мудростью Hashem! Знаете ли вы? Каждое слово Торы, которое вы учите, создаёт ангела, который будет сопровождать вас вечно! Задание: выделите сегодня хотя бы 5 минут на новое — стих, закон или историю. Каждый миг бесценен!",
    "Чтите учителей Торы! 👨‍🏫 Рамбам учит: учитель Торы как родитель, дающий вечную жизнь! Знаете ли вы? Уважение настолько велико, что если отец и учитель несут тяжёлое — сначала помогаете учителю (если отец не тalmid chacham)! Задание: выразите благодарность тому, кто научил вас Торе — сообщением, звонком или маленьким подарком.",
    "Откройте букву Vav (ו)! ✡ Эта буква похожа на крюк, соединяющий небо и землю! Знаете ли вы? «Vav» значит «и», учит, что всё в творении связано! Значение 6 — шесть дней творения. Круто: добавление Vav в начале глагола меняет будущее на прошедшее — Hashem вне времени! Заметьте связи в жизни.",
    "Испытайте силу Mezuzah! 🏠 Рамбам объясняет: проходя мимо mezuzah, вы вспоминаете Hashem и пробуждаетесь от духовного сна! «Mezuzah» = 65 в gematria, как «hekhal» (дворец) — дом становится мини-дворцом для Божественного присутствия. Текст содержит 713 букв — значение «teshuvah» (покаяние).",
    "Узнайте о mitzvah написания свитка Торы! ✍️ Каждый еврей-мужчина обязан написать (или по некоторым мнениям участвовать в написании) Sefer Torah! Некоторые говорят, что сегодня можно выполнить, покупая Chumash, Tanach и другие священные книги. Каждая буква соответствует еврейской душе; одной не хватает — весь свиток пасул — каждый еврей важен!",
    "Увенчайте себя Торой! 👑 Рамбам учит: еврейский царь должен написать ДВА свитка — один в сокровищницу, другой всегда с собой! Урок: как бы вы ни были заняты или могущественны — Тора должна быть постоянным спутником! Царь читал каждый день — ежедневный приоритет учёбы! Задание: установите фиксированное время учёбы, хотя бы несколько минут.",
    "Собирайтесь для вдохновения! 👥 Узнайте об особой mitzvah Hakhel! Каждые семь лет весь народ — мужчины, женщины и дети — собирался слушать, как царь читает Тору! Даже младенцев приносили — родители получали особую награду! Иногда просто присутствие на святом собрании возвышает душу! Задание: присоединитесь к уроку Торы или собранию, даже онлайн.",
    "Откройте букву Zayin (ז)! ✡ Похожа на корону с мечом, направленным вниз! Знаете ли вы? «Zayin» значит «оружие» — Тора наше духовное оружие против негатива! Значение 7 — связь с Шabbat. Форма учит венчать физические действия духовной целью! Вознесите сегодня физическую деятельность святой intent.",
    "Узнайте о запрете idol worship! 🛡️ Рамбам объясняет: не только статуи — всё, что мы ставим выше Hashem! Сопротивляясь поклонению деньгам, славе или ложным «богам», мы свидетельствуем, что Hashem — единственная истинная сила! Вызов: найдите то, что слишком важно, и сделайте шаг, чтобы поставить Hashem первым.",
    "Берегите речь о Hashem! 🗣️ Рамбам в Hilchot Avodah Zarah: нельзя говорить неуважительно о Hashem или отрицать Его существование. Пустые клятвы и лишние благословения запрещены. Каждое слово о Hashem — с благоговением. Задание: говорите о святом с особой осторожностью и уважением.",
    "Оберегайте дом от запретного! 🎨 Рамбам учит осторожности с изображениями: выпуклые человеческие фигуры как статуи запрещены; нельзя создавать изображения небесных тел или ангелов! Некоторые распространяют это на куклы; многие снисходительны. Задание: следите, чтобы дом был свободен от проблемных изображений!",
    "Откройте букву Tet (ט)! ✡ Представляет добро — первая буква слова «Tov» (хорошо) в Торе! Форма изогнута внутрь — истинное добро часто скрыто и скромно. Значение 9 — девять месяцев беременности, когда скрытое добро растёт! Заметьте сегодня скрытые благословения.",
    "Исследуйте силу Yud (י)! ✡ Крошечная буква с огромной мудростью! Размер учит смирению, и это первая буква Имени Hashem! Yud — точка: даже малое доброе дело может иметь бесконечный эффект! Значение 10 — Десять заповедей.",
    "Раскройте тайны Kaf (כ)! 👑 В еврейской мистике Kaf — Keter (корона), но не гордости! Изогнутая форма (כ) — смиренное поклонение; значение 20 — возраст начала поиска мудрости. Финальная Kaf (ך) учит: истинное достижение приходит через смирение."
]

# emit via emit_local_003.py or __main__ below
if __name__ == "__main__":
    import subprocess, sys
    subprocess.check_call([sys.executable, str(Path(__file__).parent / "emit_local_003.py")])
