# -*- coding: utf-8 -*-
"""Write all 8 local_005 and local_006 human translation JSON files."""
import json
import sys
from pathlib import Path

OUT = Path(r"c:\apps\hehehe\be-a-tzaddik\data\translation-catalog\human")
TOOLS = Path(__file__).resolve().parent


def write_json(name: str, key: str, strings: list) -> None:
    path = OUT / name
    path.write_text(
        json.dumps({key: strings}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def load_py_arrays(module_name: str, *names: str) -> dict:
    ns = {"__builtins__": __builtins__}
    src = (TOOLS / module_name).read_text(encoding="utf-8")
    # Strip side-effect writes from helper modules
    lines = []
    for line in src.splitlines():
        if line.strip().startswith("OUT.write_text"):
            continue
        if line.strip().startswith('print(') and "wrote" in line:
            continue
        if line.strip().startswith("assert len(HE)"):
            continue
        if line.strip().startswith("bad_count") or line.strip().startswith("for i, s in enumerate(HE"):
            break
        lines.append(line)
    exec("\n".join(lines), ns)
    return {n: ns[n] for n in names}


# --- local_005 ---
L005_ES = [
    "¡Explora el poderoso Alef (א)! ✡ ¡La primera letra del Alef-Bet representa la unidad de D-s! ¿Sabías? Su forma está hecha de un Vav (ו) con dos Yud (י), representando el cielo arriba y la tierra abajo, conectados por la presencia de D-s. El valor numérico es 1, enseñándonos la unidad absoluta de D-s. Misión de hoy: fíjate en cómo D-s conecta cielo y tierra en tu vida diaria.",
    "¡Aprende de la sabiduría del Ramban! 📜 El Ramban escribió una carta poderosa a su hijo que sigue inspirando a la gente hoy. ¿Sabías? Dijo que leer esta carta a diario ayudaría a que tus tefilot (oraciones) fueran respondidas. Algo asombroso: la carta se centra en desarrollar humildad y hablar con suavidad a todos. Desafío de hoy: lee la carta y elige un consejo para practicar.",
    "¡Sumérgete en las profundidades de la Kabbalá! 🌊 Los grandes rabinos enfatizaron que aprender Kabbalá correctamente puede transformar tu práctica judía. ¿Sabías? El Arizal dijo que en estas generaciones posteriores no solo está permitido, sino que es una mitzvá revelar estas enseñanzas. Algo poderoso: la Kabbalá nos ayuda a entender las razones más profundas detrás de las mitzvot. Misión de hoy: aprende una idea mística sobre una mitzvá que haces con regularidad.",
    "¡Honra a los difuntos como corresponde! 🕯️ El Rambam enseña en el capítulo 11 que no debemos intentar comunicarnos con los muertos para pedirles información. En el libro de Samuel, el rey Shaul intentó contactar al profeta Samuel fallecido. El espíritu de Samuel se le apareció y lo reprendió por esa transgresión — y bueno, digamos que a partir de ahí las cosas fueron cuesta abajo para Shaul. Esto nos enseña: 1. Hay vida después de la muerte, 2. No debemos pedir información a los espíritus, y 3. Si buscas consejo — ¡llama a tu madre; está esperando que llames de todos modos!",
    "¡Encuentra fuerza en el Salmo 2! 👑 Este poderoso capítulo habla de la soberanía suprema de D-s. ¿Sabías? Describe cómo las naciones pueden conspirar, pero el plan de D-s siempre prevalece. Algo increíble: el salmo termina prometiendo que todos los que confían en D-s son bendecidos. Desafío de hoy: lee este salmo y siente la presencia protectora de D-s en tu vida.",
    "¡Sumérgete en el Salmo 3 de Tehilim! 📖 ¿Sabías? Este poderoso salmo fue compuesto por el rey David cuando huía de su propio hijo Absalom. Algo asombroso: incluso en su momento más oscuro, David encontró fuerza en su fe. El salmo nos enseña que D-s es nuestro escudo y protector, sin importar cuántos oponentes enfrentemos. Misión de hoy: lee este salmo y encuentra tu propia fuerza en tiempos difíciles.",
    "¡Explora el fascinante tema de los trucos de magia en la halajá! 🎩 Algo sorprendente: aunque la Torá prohíbe la hechicería real, hacer ilusiones para entretenimiento suele estar bien, siempre que la gente entienda que no es real. ¿Sabías? La diferencia clave es que los trucos de magia hoy se entienden claramente como ilusiones hábiles, no poderes sobrenaturales.",
    "¡Descubre el significado profundo de la barba en el judaísmo! 🧔 ¿Sabías? Los cabalistas dicen que los 13 atributos de la misericordia divina pueden emanar a través de los pelos de la barba. ¡A eso sí que le llamo un auténtico legado capilar!",
    "¡Experimenta el poder del Salmo 5! 🌅 ¿Sabías? Esta tefilá matutina del rey David nos enseña cómo empezar el día con fe. Algo hermoso: el salmo muestra que D-s escucha nuestra voz por la mañana, enseñándonos a comenzar cada día con oración y esperanza. Misión: empieza tu mañana leyendo este salmo edificante.",
    "¡Ora por una refuah shleimah (sanación completa) para Raphael Yosef ben Rachel! Al orar por alguien enfermo, usamos su nombre hebreo junto con el nombre hebreo de su madre. Según la tradición rabínica (como en el Talmud), las madres a menudo se consideran con menos obligaciones espirituales y poseen inmensa gracia, lo que hace poderoso su mérito al orar por una pronta recuperación.",
    "¡Conéctate con el Salmo 6! 🙏 ¿Sabías? Este poderoso salmo es uno de los Tehilim que a menudo se recitan por la sanación. Algo asombroso: el rey David nos enseña cómo derramar el corazón ante D-s en tiempos de angustia. Misión de hoy: recita este salmo con sentimiento, especialmente cuando ores por alguien enfermo.",
    "Toma un Jumash y abre en una página y versículo al azar — Enviado por HB. Muchos judíos tienen la querida costumbre de abrir la Torá para buscar inspiración o guía en momentos importantes de la vida. Ya sea que veas el versículo como un mensaje personal o simplemente como una chispa para reflexionar, el acto en sí te conecta con la Torá — y nuestros Sabios enseñan que incluso estudiar un solo versículo es una mitzvá en sí. Lee lentamente lo que te salga, piensa qué podría significar para tu vida ahora y deja que las palabras penetren.",
    "¡Descubre el poder del Salmo 7! 🛡️ ¿Sabías? Este salmo es la respuesta de David a acusaciones falsas. Algo increíble: nos enseña a mantener nuestra integridad incluso ante críticas injustas. Misión de hoy: lee este salmo y reflexiona sobre mantener tu brújula moral en tiempos difíciles.",
    "¡Explora la majestuosidad del Salmo 8! 🌠 ¿Sabías? Este salmo celebra la maravilla de la creación de D-s y el papel especial de la humanidad en ella. Algo asombroso: cuando David miró las estrellas, se inspiró a escribir sobre la dignidad humana y nuestro propósito divino. Misión de hoy: sal afuera, mira el cielo nocturno y recita este salmo edificante.",
    "¡Abraza el poder del Teshuvá (arrepentimiento)! 🌱 ¿Sabías? El Rambam enseña que incluso un pensamiento de arrepentimiento puede transformar a una persona al instante. Algo increíble: el arrepentimiento verdadero tiene el poder de convertir errores pasados en méritos. Misión de hoy: tómate un momento para reflexionar sobre algo que quieras mejorar y haz un cambio positivo.",
    "¡Abraza el poder del Shema! 🌅 ¿Sabías? Esta tefilá central se recita dos veces al día para declarar la unidad de D-s y nuestro amor por Él. Algo asombroso: el Shema contiene principios fundamentales de la fe judía en solo unos versículos. ¡Y los Sabios enseñan que tiene el poder de proteger cuerpos enteros! Misión de hoy: di el Shema con intención, enfocándote en las palabras.",
    "¡Conéctate a través de la tefilá! 🙏 ¿Sabías? La tefilá es nuestra conexión Wi-Fi espiritual con D-s. Algo hermoso: las bendiciones fueron prescritas por los Sabios, que sabían abrir las puertas celestiales con palabras y frases específicas. Solo al decir las palabras del sidur, nuestras oraciones ascienden a alturas insondables. Misión de hoy: elige una tefilá para decir con concentración y sentimiento extra.",
    "¡Experimenta el poder de la tefilá comunitaria! 👥 ¿Sabías? Orar con un minyan (grupo de 10) amplifica el poder de nuestras tefilot. Algo asombroso: el Talmud enseña que D-s nunca rechaza las oraciones de la comunidad. Misión de hoy: únete a un minyan para la tefilá si puedes.",
    "¡Aprende sobre la bendición de Birkat Kohanim! 🙌 ¿Sabías? Cuando los Kohanim bendicen al pueblo, actúan como canales de la bendición divina. Los Sabios dicen que la Shejiná (Presencia Divina de D-s) aparece entre sus dedos cuando los levantan. Esta bendición especial no ha cambiado en miles de años desde los tiempos de Aarón el Sumo Sacerdote, el primer Kohen. ¡Todos los Kohanim de hoy descienden de él!",
    "¡Aprende sobre las Tefilín! 👑 ¿Sabías? La Tefilá de la cabeza contiene los mismos cuatro pasajes de Torá que la del brazo, ¡pero ordenados de forma distinta! Misión de hoy: aprende cómo las Tefilín conectan nuestra mente con D-s.",
    "Pasa los próximos 30 segundos agradeciendo a D-s por todo lo que puedas. — Enviado por MB. Después de que el pueblo judío comió y quedó satisfecho en el desierto, Moisés les enseñó a bendecir a D-s — estableciendo la gratitud como parte fundamental de la vida judía. Nuestros Sabios preguntan: ¿Quién es verdaderamente rico? Quien está contento con lo que ya tiene. No necesitas una oración larga — solo pausa y nombra los regalos frente a ti ahora: tu respiración, tus ojos, alguien que amas, la comida en tu mesa.",
    "¡Descubre el poder de la Mezuzá! 🚪 ¿Sabías? ¡Es como un sistema de seguridad divino para tu hogar! Los Sabios dicen que cuando una fuerza destructiva quiere dañar a alguien, si ve una mezuzá kosher en el marco de la puerta, se asusta por el Nombre de D-s escrito en ella y huye.",
    "¡Limpia tu baño extra impecable en honor del Shabat! — Enviado por AS. Nuestros Sabios enseñan que prepararse para el Shabat es en sí una mitzvá — y quien se esfuerza el viernes disfruta las recompensas en Shabat. Un hermoso midrash describe cómo dos ángeles acompañan a una persona a casa desde la sinagoga el viernes por la noche: uno bueno, uno malo. Si encuentran el hogar listo — velas encendidas, mesa puesta — el ángel bueno bendice que el próximo Shabat sea igual y el malo se ve obligado a decir «amén». Honrar el Shabat significa hacer que todo el hogar se sienta como un palacio para el Rey.",
    "¡Ora por una refuah shleimah (sanación completa) para Sarah Dina bat Odel — enviado por DM! Al orar por alguien enfermo, usamos su nombre hebreo junto con el nombre hebreo de su madre — porque enseñanzas místicas, como las del Zohar, sugieren que la esencia espiritual más profunda del alma está íntimamente conectada con la madre. Usar el nombre de la madre apela a la compasión divina y a la energía maternal nutritiva.",
    "¡Domina el arte de Birkat HaMazon! 🍽️ ¿Sabías? Esto no es solo un «gracias por la comida» — ¡es un banquete espiritual de cuatro bendiciones! Los rabinos nos enseñan que es una segulá (costumbre auspiciosa) para la riqueza lavarse y tener una comida con pan todos los días. Y algunos dicen que si lo dices entero con intención, estarás a salvo de todo daño. 😊",
]

L005_FR = [
    "Explorez la puissance de l'Alef (א) ! ✡ La première lettre de l'Alef-Bet représente l'unité de D. ! Le saviez-vous ? Sa forme est faite d'un Vav (ו) avec deux Yod (י), représentant le ciel au-dessus et la terre en dessous, reliés par la Présence de D. Sa valeur numérique est 1, nous enseignant l'unité absolue de D. Mission du jour : remarquez comment D. relie ciel et terre dans votre vie quotidienne.",
    "Apprenez de la sagesse du Ramban ! 📜 Le Ramban a écrit une lettre puissante à son fils qui inspire encore aujourd'hui ! Le saviez-vous ? Il a dit que lire cette lettre chaque jour aiderait à ce que vos prières soient exaucées ! Voici quelque chose d'étonnant : la lettre se concentre sur l'humilité et parler doucement à chacun. Défi du jour : lisez la lettre et choisissez un conseil à pratiquer.",
    "Plongez dans les profondeurs de la Kabbale ! 🌊 Les grands rabbins ont souligné qu'apprendre la Kabbale correctement peut transformer votre pratique juive ! Le saviez-vous ? L'Arizal a dit que dans ces générations tardives, non seulement c'est permis mais c'est une mitzvah de révéler ces enseignements ! Voici quelque chose de puissant : la Kabbale nous aide à comprendre les raisons profondes derrière les mitzvot. Mission du jour : apprenez un enseignement mystique sur une mitzvah que vous faites régulièrement.",
    "Honorez les défunts comme il se doit ! 🕯️ Le Rambam enseigne au chapitre 11 que nous ne devons pas tenter de communiquer avec les morts pour leur demander des informations. Dans le livre de Samuel, le roi Shaul a tenté de contacter le prophète Samuel décédé. L'esprit de Samuel lui est apparu et l'a réprimandé pour cette transgression — et disons-le gentiment, les choses n'ont fait qu'empirer pour Shaul. Cela nous enseigne : 1. Il y a une vie après la mort, 2. Nous ne devons pas demander d'informations aux esprits, et 3. Si vous cherchez un conseil — appelez simplement votre mère ; elle attend votre appel de toute façon !",
    "Trouvez la force dans le Psaume 2 ! 👑 Ce chapitre puissant parle de la souveraineté suprême de D. ! Le saviez-vous ? Il décrit comment les nations peuvent comploter, mais le plan de D. l'emporte toujours ! Voici quelque chose d'incroyable : le psaume se termine en promettant que tous ceux qui placent leur confiance en D. sont bénis. Défi du jour : lisez ce psaume et sentez la Présence protectrice de D. dans votre vie.",
    "Plongez dans le Psaume 3 des Tehilim ! 📖 Le saviez-vous ? Ce puissant psaume a été composé par le roi David lorsqu'il fuyait son propre fils Absalom ! Voici quelque chose d'étonnant : même dans son moment le plus sombre, David a trouvé la force dans sa foi. Le psaume nous enseigne que D. est notre bouclier et protecteur, quels que soient nos adversaires ! Mission du jour : lisez ce psaume et trouvez votre propre force dans les moments difficiles.",
    "Explorez le fascinant sujet des tours de magie dans la halakha ! 🎩 Voici quelque chose de surprenant : bien que la Torah interdise la sorcellerie réelle, faire des illusions pour le divertissement est généralement permis, tant que les gens comprennent que ce n'est pas réel ! Le saviez-vous ? La différence clé est que les tours de magie aujourd'hui sont clairement compris comme des illusions habiles, pas des pouvoirs surnaturels.",
    "Découvrez la signification profonde de la barbe dans le judaïsme ! 🧔 Le saviez-vous ? Les kabbalistes disent que les 13 attributs de miséricorde divine peuvent émaner à travers les poils de la barbe ! Voilà ce qu'on appelle un véritable héritage capillaire !",
    "Vivez la puissance du Psaume 5 ! 🌅 Le saviez-vous ? Cette prière matinale du roi David nous enseigne comment commencer la journée avec foi ! Voici quelque chose de beau : le psaume montre que D. écoute notre voix le matin, nous enseignant à commencer chaque jour avec prière et espoir. Mission : commencez votre matinée en lisant ce psaume édifiant.",
    "Priez pour une refoua shleima (guérison complète) pour Raphael Yosef ben Rachel ! Lorsque nous prions pour une personne malade, nous utilisons son nom hébreu avec le nom hébreu de sa mère. Selon la tradition rabbinique (comme dans le Talmud), les mères sont souvent considérées comme ayant moins de dettes spirituelles et possédant une grâce immense, ce qui rend leur mérite puissant pour une guérison rapide.",
    "Connectez-vous au Psaume 6 ! 🙏 Le saviez-vous ? Ce puissant psaume est l'un des Tehilim souvent récités pour la guérison ! Voici quelque chose d'étonnant : le roi David nous enseigne comment verser notre cœur devant D. dans les moments de détresse. Mission du jour : récitez ce psaume avec sentiment, surtout en priant pour une personne malade.",
    "Prenez un 'Houmash et ouvrez-le à une page et un verset au hasard — Soumis par HB. Beaucoup de Juifs ont la précieuse coutume d'ouvrir la Torah pour chercher inspiration ou guidance aux moments importants de la vie. Que vous voyiez le verset comme un message personnel ou simplement comme une étincelle de réflexion, l'acte lui-même vous connecte à la Torah — et nos Sages enseignent qu'étudier même un seul verset est une mitzvah en soi. Lisez lentement ce sur quoi vous tombez, réfléchissez à ce que cela pourrait signifier pour votre vie maintenant, et laissez les mots pénétrer.",
    "Découvrez la puissance du Psaume 7 ! 🛡️ Le saviez-vous ? Ce psaume est la réponse de David aux fausses accusations ! Voici quelque chose d'incroyable : il nous enseigne à maintenir notre intégrité même face à des critiques injustes. Mission du jour : lisez ce psaume et réfléchissez à garder votre boussole morale dans les moments difficiles.",
    "Explorez la majesté du Psaume 8 ! 🌠 Le saviez-vous ? Ce psaume célèbre la merveille de la création de D. et le rôle spécial de l'humanité ! Voici quelque chose d'étonnant : quand David regardait les étoiles, il s'est senti inspiré pour écrire sur la dignité humaine et notre but divin. Mission du jour : sortez, regardez le ciel nocturne et récitez ce psaume édifiant.",
    "Embrassez la puissance du Teshouva (repentir) ! 🌱 Le saviez-vous ? Le Rambam enseigne qu'une seule pensée de repentir peut transformer une personne instantanément ! Voici quelque chose d'incroyable : le vrai repentir a le pouvoir de convertir les erreurs passées en mérites. Mission du jour : prenez un moment pour réfléchir à une chose que vous aimeriez améliorer et faites un changement positif.",
    "Embrassez la puissance du Shema ! 🌅 Le saviez-vous ? Cette prière centrale est récitée deux fois par jour pour proclamer l'unité de D. et notre amour pour Lui ! Voici quelque chose d'étonnant : le Shema contient les principes fondamentaux de la foi juive en quelques versets seulement. Et les Sages enseignent qu'il a le pouvoir de protéger des corps entiers ! Mission du jour : dites le Shema avec intention, en vous concentrant sur les mots.",
    "Connectez-vous par la prière ! 🙏 Le saviez-vous ? La prière est notre connexion Wi-Fi spirituelle à D. ! Voici quelque chose de beau : les bénédictions ont été prescrites par les Sages, qui savaient ouvrir les portes célestes avec des mots et phrases spécifiques. En disant simplement les mots du siddour, nos prières montent vers des hauteurs insondables ! Mission du jour : choisissez une prière à dire avec concentration et sentiment supplémentaires.",
    "Vivez la puissance de la prière communautaire ! 👥 Le saviez-vous ? Prier avec un minyan (groupe de 10) amplifie la puissance de nos prières ! Voici quelque chose d'étonnant : le Talmud enseigne que D. ne rejette jamais les prières d'une communauté. Mission du jour : rejoignez un minyan pour la prière si possible.",
    "Apprenez la bénédiction de Birkat Kohanim ! 🙌 Le saviez-vous ? Quand les Kohanim bénissent le peuple, ils agissent comme des canaux de bénédiction divine ! Les Sages disent que la Chekhina (Présence Divine de D.) apparaît entre leurs doigts quand ils les lèvent. Cette bénédiction spéciale est restée inchangée depuis l'époque d'Aaron le Grand Prêtre, le premier Kohen. Tous les Kohanim d'aujourd'hui descendent de lui !",
    "Apprenez les Tefilin ! 👑 Le saviez-vous ? Le Tefilin de la tête contient les mêmes quatre passages de Torah que celui du bras, mais arrangés différemment ! Mission du jour : découvrez comment les Tefilin relient notre esprit à D.",
    "Passez les 30 prochaines secondes à remercier D. pour tout ce pour quoi vous pouvez Le remercier. — Soumis par MB. Après que le peuple juif eut mangé et fut rassasié dans le désert, Moïse leur enseigna à bénir D. — établissant la gratitude comme partie fondamentale de la vie juive. Nos Sages demandent : Qui est vraiment riche ? Celui qui est heureux avec ce qu'il a déjà. Vous n'avez pas besoin d'une longue prière — faites juste une pause et nommez les cadeaux devant vous maintenant : votre respiration, vos yeux, quelqu'un que vous aimez, la nourriture sur votre table.",
    "Découvrez la puissance de la Mezouza ! 🚪 Le saviez-vous ? C'est comme un système de sécurité divin pour votre maison ! Les Sages disent que lorsqu'une force destructrice veut nuire à quelqu'un, si elle voit une mezouza casher sur le montant de la porte, elle a peur du Nom de D. inscrit dessus et s'enfuit.",
    "Nettoyez votre salle de bain extra impeccablement en l'honneur du Chabbat ! — Soumis par AS. Nos Sages enseignent que se préparer pour le Chabbat est en soi une mitzvah — et que celui qui peine le vendredi jouira des récompenses le Chabbat. Un beau midrash décrit comment deux anges accompagnent une personne à la maison depuis la synagogue le vendredi soir : un bon, un mauvais. S'ils trouvent la maison prête — bougies allumées, table dressée — le bon ange bénit que le prochain Chabbat soit pareil et le mauvais est forcé de dire « amen ». Honorer le Chabbat, c'est faire que toute la maison ressemble à un palais pour le Roi.",
    "Priez pour une refoua shleima (guérison complète) pour Sarah Dina bat Odel — soumis par DM ! Lorsque nous prions pour une personne malade, nous utilisons son nom hébreu avec le nom hébreu de sa mère — car les enseignements mystiques, comme ceux du Zohar, suggèrent que l'essence spirituelle la plus profonde de l'âme est intimement liée à la mère. Utiliser le nom de la mère vise à invoquer la compassion divine et l'énergie maternelle nourricière.",
    "Maîtrisez l'art de Birkat HaMazon ! 🍽️ Le saviez-vous ? Ce n'est pas juste un « merci pour le repas » — c'est un festin spirituel de quatre bénédictions ! Les rabbins nous enseignent que c'est une segoula (pratique propice) pour la richesse de se laver et prendre un repas avec du pain chaque jour. Et certains disent que si vous le dites entièrement avec intention, vous serez préservé de tout mal. 😊",
]

L005_RU = [
    "Исследуйте могучий Алеф (א)! ✡ Первая буква Алеф-Бет символизирует единство Hashem! Знаете ли вы? Её форма — Вав (ו) с двумя Юд (י), представляющими небо выше и землю ниже, связанные присутствием Hashem. Числовое значение — 1, учит нас абсолютному единству Hashem. Миссия на сегодня: заметьте, как Hashem соединяет небо и землю в вашей повседневной жизни.",
    "Учитесь мудрости Рамбана! 📜 Рамбан написал сыну мощное письмо, которое до сих пор вдохновляет людей! Знаете ли вы? Он сказал, что ежедневное чтение этого письма поможет, чтобы ваши молитвы были услышаны! Вот что удивительно: письмо сосредоточено на смирении и мягком общении со всеми. Вызов на сегодня: прочитайте письмо и выберите один совет для практики.",
    "Погрузитесь в глубины Каббалы! 🌊 Великие раввины подчёркивали, что правильное изучение Каббалы может изменить вашу еврейскую практику. Знаете ли вы? Аризаль сказал, что в этих поздних поколениях не только разрешено, но и mitzvah раскрывать эти учения! Вот что мощно: Каббала помогает понять более глубокие причины mitzvot. Миссия на сегодня: узнайте одно мистическое прозрение о mitzvah, которую вы делаете регулярно.",
    "Почитайте усопших должным образом! 🕯️ Рамбам учит в главе 11, что нельзя пытаться общаться с мёртвыми, чтобы спрашивать у них информацию. В книге Shmuel царь Shaul попытался связаться с умершим пророком Shmuel. Дух Shmuel явился ему и упрекнул за это нарушение — и, скажем мягко, дальше у Shaul пошло только хуже. Это учит нас: 1. Есть жизнь после смерти, 2. Нельзя спрашивать духов там о информации, и 3. Если нужен совет — просто позвоните маме; она всё равно ждёт вашего звонка!",
    "Найдите силу в Псалме 2! 👑 Эта мощная глава говорит о верховном господстве Hashem! Знаете ли вы? Она описывает, как народы могут строить заговоры, но план Hashem всегда побеждает! Вот что невероятно: псалом заканчивается обещанием, что все, кто уповает на Hashem, благословенны. Вызов на сегодня: прочитайте этот псалом и почувствуйте защитное присутствие Hashem в жизни.",
    "Погрузитесь в Псалом 3 из Tehilim! 📖 Знаете ли вы? Этот мощный псалом сочинил царь David, когда бежал от собственного сына Avshalom! Вот что удивительно: даже в самый тёмный момент David нашёл силу в вере. Псалом учит, что Hashem — наш щит и защитник, сколько бы противников мы ни встретили! Миссия на сегодня: прочитайте этот псалом и найдите свою силу в трудные времена.",
    "Исследуйте увлекательную тему фокусов в галахе! 🎩 Вот что удивительно: хотя Тора запрещает настоящее колдовство, иллюзии для развлечения обычно допустимы — если люди понимают, что это не реально! Знаете ли вы? Ключевая разница в том, что фокусы сегодня явно воспринимаются как умелые иллюзии, а не сверхъестественные силы.",
    "Откройте глубокий смысл бороды в иудаизме! 🧔 Знаете ли вы? Каббалисты говорят, что 13 атрибутов божественной милости могут исходить через волосы бороды. Вот это я называю настоящей «волосной» реликвией!",
    "Почувствуйте силу Псалма 5! 🌅 Знаете ли вы? Эта утренняя молитва царя David учит начинать день с верой! Вот что прекрасно: псалом показывает, что Hashem слушает наш голос утром, учит нас начинать каждый день с молитвы и надежды. Миссия: начните утро с этого воодушевляющего псалма.",
    "Молитесь о refuah shleimah (полном исцелении) для Raphael Yosef ben Rachel. Молясь о больном, мы используем его еврейское имя вместе с еврейским именем матери. По раввинской традиции (как в Talmud), матери часто считаются имеющими меньше духовных обязательств и обладающими огромной благодатью — их заслуга мощна при молитве о скором выздоровлении.",
    "Соединитесь с Псалмом 6! 🙏 Знаете ли вы? Этот мощный псалом — один из Tehilim, часто читаемых для исцеления! Вот что удивительно: царь David учит нас изливать сердце перед Hashem в трудные времена. Миссия на сегодня: прочитайте этот псалом с чувством, особенно молясь о больном.",
    "Возьмите Chumash и откройте на случайной странице и стихе — Предложено HB. У многих евреев есть дорогая традиция открывать Тору в поисках вдохновения или руководства в важные моменты жизни. Видите ли вы стих как личное послание или просто как искру для размышления — сам акт связывает вас с Торой, и мудрецы учат, что изучение даже одного стиха — сама по себе mitzvah. Прочитайте медленно то, на что попали, подумайте, что это может значить для вашей жизни сейчас, и дайте словам проникнуть.",
    "Откройте силу Псалма 7! 🛡️ Знаете ли вы? Этот псалом — ответ David на ложные обвинения! Вот что невероятно: он учит сохранять честность даже перед несправедливой критикой. Миссия на сегодня: прочитайте этот псалом и подумайте о сохранении морального компаса в трудные времена.",
    "Исследуйте величие Псалма 8! 🌠 Знаете ли вы? Этот псалом воспевает чудо творения Hashem и особую роль человечества! Вот что удивительно: когда David смотрел на звёзды, он вдохновился написать о человеческом достоинстве и нашем божественном предназначении. Миссия на сегодня: выйдите, посмотрите на ночное небо и прочитайте этот воодушевляющий псалом.",
    "Примите силу Teshuvah (покаяния)! 🌱 Знаете ли вы? Рамбам учит, что даже одна мысль о покаянии может мгновенно преобразить человека! Вот что невероятно: истинное покаяние способно превратить прошлые ошибки в заслуги. Миссия на сегодня: остановитесь и подумайте об одном, что хотели бы улучшить, и сделайте позитивное изменение.",
    "Примите силу Shema! 🌅 Знаете ли вы? Эта центральная молитва читается дважды в день, чтобы провозгласить единство Hashem и нашу любовь к Нему! Вот что удивительно: Shema содержит основы еврейской веры всего в нескольких стихах. И мудрецы учат, что она способна защищать целые тела! Миссия на сегодня: произнесите Shema с намерением, сосредоточившись на словах.",
    "Соединитесь через молитву! 🙏 Знаете ли вы? Молитва — наше духовное Wi-Fi-соединение с Hashem! Вот что прекрасно: благословения установлены мудрецами, которые знали, как открывать небесные врата определёнными словами и фразами. Просто произнося слова из siddur, наши молитвы восходят к непостижимым высотам! Миссия на сегодня: выберите одну молитву и произнесите её с особой сосредоточенностью и чувством.",
    "Почувствуйте силу общинной молитвы! 👥 Знаете ли вы? Молитва с minyan (группой из 10) усиливает силу наших молитв! Вот что удивительно: Talmud учит, что Hashem никогда не отвергает молитвы общины. Миссия на сегодня: присоединитесь к minyan для молитвы, если возможно.",
    "Узнайте о благословении Birkat Kohanim! 🙌 Знаете ли вы? Когда Kohanim благословляют народ, они служат каналами божественного благословения! Мудрецы говорят, что Shechinah (Божественное присутствие Hashem) появляется между их пальцами, когда они поднимают руки. Это особое благословение не менялось тысячи лет со времён Aharon первосвященника, первого Kohen. Все Kohanim сегодня — его потомки!",
    "Узнайте о Tefillin! 👑 Знаете ли вы? Tefillin на голове содержит те же четыре отрывка Торы, что и на руке, но расположены иначе! Миссия на сегодня: узнайте, как Tefillin связывает наш разум с Hashem.",
    "Проведите следующие 30 секунд, благодаря Hashem за всё, за что только можете. — Предложено MB. После того как еврейский народ поел и насытился в пустыне, Moshe научил их благословлять Hashem — установив благодарность как фундаментальную часть еврейской жизни. Мудрецы спрашивают: кто по-настоящему богат? Тот, кто доволен тем, что уже имеет. Не нужна длинная молитва — просто остановитесь и назовите дары перед вами сейчас: дыхание, глаза, любимого человека, еду на столе.",
    "Откройте силу Mezuzah! 🚪 Знаете ли вы? Это как божественная система безопасности для вашего дома! Мудрецы говорят: когда разрушительная сила хочет навредить кому-то, если она видит kosher mezuzah на дверном косяке, её пугает Имя Hashem, написанное на ней, и она убегает.",
    "Уберите ванную особенно тщательно в честь Шabbat! — Предложено AS. Мудрецы учат: подготовка к Шabbat — сама по себе mitzvah — и кто трудится в пятницу, наслаждается наградой в Шabbat. Прекрасный midrash описывает, как два ангела сопровождают человека домой из синагоги в пятницу вечером: один добрый, один злой. Если дом готов — свечи зажжены, стол накрыт — добрый ангел благословляет, чтобы следующий Шabbat был таким же, а злой вынужден сказать «амен». Почитание Шabbat — сделать весь дом похожим на дворец для Царя.",
    "Молитесь о refuah shleimah (полном исцелении) для Sarah Dina bat Odel — предложено DM. Молясь о больном, мы используем его еврейское имя вместе с именем матери — потому что мистические учения, как в Zohar, говорят, что глубочайшая духовная суть души тесно связана с матерью. Использование имени матери призвано обратиться к божественному милосердию и материнской заботе.",
    "Овладейте искусством Birkat HaMazon! 🍽️ Знаете ли вы? Это не просто «спасибо за еду» — это четырёхкурсовый духовный пир благословений! Раввины учат, что это segulah (благоприятная практика) для богатства — мыться и есть хлеб каждый день. И некоторые говорят: если произнесёте всё с намерением, будете защищены от всякого вреда. 😊",
]

# Hebrew local_005 - load from companion data file
L005_HE = load_py_arrays("local_005_he_data.py", "HE")["HE"]

# local_006 - reuse proven arrays
tr = load_py_arrays("_write_translations.py", "local_006_es", "local_006_fr", "local_006_ru")
he006 = load_py_arrays("_write_he_final.py", "HE")["HE"]

FILES = [
    ("local_005_he_only.json", "he", L005_HE, 25),
    ("local_005_es_only.json", "es", L005_ES, 25),
    ("local_005_fr_only.json", "fr", L005_FR, 25),
    ("local_005_ru_only.json", "ru", L005_RU, 25),
    ("local_006_he_only.json", "he", he006, 18),
    ("local_006_es_only.json", "es", tr["local_006_es"], 18),
    ("local_006_fr_only.json", "fr", tr["local_006_fr"], 18),
    ("local_006_ru_only.json", "ru", tr["local_006_ru"], 18),
]

if __name__ == "__main__":
    ok = True
    for fname, key, strings, expected in FILES:
        if len(strings) != expected:
            print(f"FAIL build {fname}: got {len(strings)}, expected {expected}", file=sys.stderr)
            ok = False
            continue
        write_json(fname, key, strings)
        print(f"OK {OUT / fname}: {len(strings)}")
    if not ok:
        sys.exit(1)
