package com.beardytop.beatzaddik.domain

/**
 * Maps KosherJava Parsha enum names to display names and verified reader URLs.
 * Chabad links use current default_cdo parsha pages (not deprecated article_cdo aids).
 * Sefaria links use parsha title refs that resolve to the weekly Torah portion text.
 */
object ParshaData {

    data class ParshaInfo(
        val displayName: String,
        val chabadUrl: String,
        /** Sefaria ref segment (e.g. "Beha'alotcha" or "Deuteronomy.33.1-34.12"). */
        val sefariaRef: String,
    ) {
        val sefariaUrl: String
            get() = "https://www.sefaria.org/${sefariaRef.replace(" ", "%20").replace("'", "%27")}"
    }

    private val map: Map<String, ParshaInfo> = mapOf(
        "BERESHIS"            to ParshaInfo("Bereishit",          "https://www.chabad.org/parshah/default_cdo/aid/7781/jewish/Bereshit.htm",           "Bereishit"),
        "NOACH"               to ParshaInfo("Noach",              "https://www.chabad.org/parshah/default_cdo/aid/9168/jewish/Noach.htm",               "Noach"),
        "LECH_LECHA"          to ParshaInfo("Lech Lecha",         "https://www.chabad.org/parshah/default_cdo/aid/9169/jewish/Lech-Lecha.htm",          "Lech Lecha"),
        "VAYERA"              to ParshaInfo("Vayera",             "https://www.chabad.org/parshah/default_cdo/aid/9170/jewish/Vayera.htm",              "Vayera"),
        "CHAYEI_SARA"         to ParshaInfo("Chayei Sara",        "https://www.chabad.org/parshah/default_cdo/aid/9171/jewish/Chayei-Sarah.htm",        "Chayei Sara"),
        "TOLDOS"              to ParshaInfo("Toldot",             "https://www.chabad.org/parshah/default_cdo/aid/9172/jewish/Toldot.htm",              "Toldot"),
        "VAYETZEI"            to ParshaInfo("Vayetze",            "https://www.chabad.org/parshah/default_cdo/aid/9173/jewish/Vayetze.htm",              "Vayetze"),
        "VAYISHLACH"          to ParshaInfo("Vayishlach",         "https://www.chabad.org/parshah/default_cdo/aid/15554/jewish/Vayishlach.htm",         "Vayishlach"),
        "VAYESHEV"            to ParshaInfo("Vayeshev",           "https://www.chabad.org/parshah/default_cdo/aid/15555/jewish/Vayeshev.htm",           "Vayeshev"),
        "MIKETZ"              to ParshaInfo("Miketz",             "https://www.chabad.org/parshah/default_cdo/aid/15556/jewish/Miketz.htm",              "Miketz"),
        "VAYIGASH"            to ParshaInfo("Vayigash",           "https://www.chabad.org/parshah/default_cdo/aid/15557/jewish/Vayigash.htm",           "Vayigash"),
        "VAYECHI"             to ParshaInfo("Vayechi",            "https://www.chabad.org/parshah/default_cdo/aid/15558/jewish/Vayechi.htm",              "Vayechi"),
        "SHEMOS"              to ParshaInfo("Shemot",             "https://www.chabad.org/parshah/default_cdo/aid/15559/jewish/Shemot.htm",              "Shemot"),
        "VAERA"               to ParshaInfo("Va'era",             "https://www.chabad.org/parshah/default_cdo/aid/15560/jewish/Vaera.htm",              "Vaera"),
        "BO"                  to ParshaInfo("Bo",                 "https://www.chabad.org/parshah/default_cdo/aid/15561/jewish/Bo.htm",                  "Bo"),
        "BESHALACH"           to ParshaInfo("Beshalach",          "https://www.chabad.org/parshah/default_cdo/aid/15562/jewish/Beshalach.htm",           "Beshalach"),
        "YISRO"               to ParshaInfo("Yitro",              "https://www.chabad.org/parshah/default_cdo/aid/15563/jewish/Yitro.htm",              "Yitro"),
        "MISHPATIM"           to ParshaInfo("Mishpatim",          "https://www.chabad.org/parshah/default_cdo/aid/15564/jewish/Mishpatim.htm",          "Mishpatim"),
        "TERUMAH"             to ParshaInfo("Terumah",            "https://www.chabad.org/parshah/default_cdo/aid/15565/jewish/Terumah.htm",            "Terumah"),
        "TETZAVEH"            to ParshaInfo("Tetzaveh",           "https://www.chabad.org/parshah/default_cdo/aid/15566/jewish/Tetzaveh.htm",           "Tetzaveh"),
        "KI_SISA"             to ParshaInfo("Ki Tisa",            "https://www.chabad.org/parshah/default_cdo/aid/15567/jewish/Ki-Tisa.htm",            "Ki Tisa"),
        "VAYAKHEL"            to ParshaInfo("Vayakhel",           "https://www.chabad.org/parshah/default_cdo/aid/15568/jewish/Vayakhel.htm",           "Vayakhel"),
        "PEKUDEI"             to ParshaInfo("Pekudei",            "https://www.chabad.org/parshah/default_cdo/aid/15570/jewish/Pekudei.htm",            "Pekudei"),
        "VAYAKHEL_PEKUDEI"    to ParshaInfo("Vayakhel-Pekudei",   "https://www.chabad.org/parshah/default_cdo/aid/15569/jewish/Vayakhel-Pekudei.htm",   "Vayakhel-Pekudei"),
        "VAYIKRA"             to ParshaInfo("Vayikra",            "https://www.chabad.org/parshah/default_cdo/aid/15574/jewish/Vayikra.htm",              "Vayikra"),
        "TZAV"                to ParshaInfo("Tzav",               "https://www.chabad.org/parshah/default_cdo/aid/15575/jewish/Tzav.htm",               "Tzav"),
        "SHMINI"              to ParshaInfo("Shemini",            "https://www.chabad.org/parshah/default_cdo/aid/15576/jewish/Shemini.htm",            "Shemini"),
        "TAZRIA"              to ParshaInfo("Tazria",             "https://www.chabad.org/parshah/default_cdo/aid/15577/jewish/Tazria.htm",              "Tazria"),
        "METZORA"             to ParshaInfo("Metzora",            "https://www.chabad.org/parshah/default_cdo/aid/15579/jewish/Metzora.htm",             "Metzora"),
        "TAZRIA_METZORA"      to ParshaInfo("Tazria-Metzora",     "https://www.chabad.org/parshah/default_cdo/aid/15578/jewish/Tazria-Metzora.htm",     "Tazria-Metzora"),
        "ACHREI_MOS"          to ParshaInfo("Achrei Mot",         "https://www.chabad.org/parshah/default_cdo/aid/15580/jewish/Acharei-Mot.htm",        "Achrei Mot"),
        "KEDOSHIM"            to ParshaInfo("Kedoshim",           "https://www.chabad.org/parshah/default_cdo/aid/15582/jewish/Kedoshim.htm",           "Kedoshim"),
        "ACHREI_MOS_KEDOSHIM" to ParshaInfo("Achrei Mot-Kedoshim","https://www.chabad.org/parshah/default_cdo/aid/15581/jewish/Acharei-Kedoshim.htm",  "Achrei Mot-Kedoshim"),
        "EMOR"                to ParshaInfo("Emor",               "https://www.chabad.org/parshah/default_cdo/aid/15583/jewish/Emor.htm",               "Emor"),
        "BEHAR"               to ParshaInfo("Behar",              "https://www.chabad.org/parshah/default_cdo/aid/15584/jewish/Behar.htm",              "Behar"),
        "BECHUKOSAI"          to ParshaInfo("Bechukotai",         "https://www.chabad.org/parshah/default_cdo/aid/15586/jewish/Bechukotai.htm",         "Bechukotai"),
        "BEHAR_BECHUKOSAI"    to ParshaInfo("Behar-Bechukotai",   "https://www.chabad.org/parshah/default_cdo/aid/15585/jewish/Behar-Bechukotai.htm",   "Behar-Bechukotai"),
        "BAMIDBAR"            to ParshaInfo("Bamidbar",           "https://www.chabad.org/parshah/default_cdo/aid/36466/jewish/Bamidbar.htm",           "Bamidbar"),
        "NASSO"               to ParshaInfo("Nasso",              "https://www.chabad.org/parshah/default_cdo/aid/39589/jewish/Naso.htm",               "Nasso"),
        "BEHAALOSCHA"         to ParshaInfo("Beha'alotcha",       "https://www.chabad.org/parshah/default_cdo/aid/36744/jewish/Behaalotecha.htm",       "Beha'alotcha"),
        "SHLACH"              to ParshaInfo("Shelach",            "https://www.chabad.org/parshah/default_cdo/aid/45586/jewish/Shelach.htm",             "Shlach"),
        "KORACH"              to ParshaInfo("Korach",             "https://www.chabad.org/parshah/default_cdo/aid/45591/jewish/Korach.htm",             "Korach"),
        "CHUKAS"              to ParshaInfo("Chukat",             "https://www.chabad.org/parshah/default_cdo/aid/45612/jewish/Chukat.htm",             "Chukat"),
        "BALAK"               to ParshaInfo("Balak",              "https://www.chabad.org/parshah/default_cdo/aid/45614/jewish/Balak.htm",              "Balak"),
        "CHUKAS_BALAK"        to ParshaInfo("Chukat-Balak",       "https://www.chabad.org/parshah/default_cdo/aid/45613/jewish/Chukat-Balak.htm",       "Chukat-Balak"),
        "PINCHAS"             to ParshaInfo("Pinchas",            "https://www.chabad.org/parshah/default_cdo/aid/45615/jewish/Pinchas.htm",            "Pinchas"),
        "MATOS"               to ParshaInfo("Matot",              "https://www.chabad.org/parshah/default_cdo/aid/52598/jewish/Matot.htm",              "Matot"),
        "MASEI"               to ParshaInfo("Masei",              "https://www.chabad.org/parshah/default_cdo/aid/52600/jewish/Masei.htm",              "Masei"),
        "MATOS_MASEI"         to ParshaInfo("Matot-Masei",        "https://www.chabad.org/parshah/default_cdo/aid/52599/jewish/Matot-Masei.htm",        "Matot-Masei"),
        "DEVARIM"             to ParshaInfo("Devarim",            "https://www.chabad.org/parshah/default_cdo/aid/36232/jewish/Devarim.htm",              "Devarim"),
        "VAESCHANAN"          to ParshaInfo("Va'etchanan",        "https://www.chabad.org/parshah/default_cdo/aid/36233/jewish/Vaetchanan.htm",         "Vaetchanan"),
        "EIKEV"               to ParshaInfo("Eikev",              "https://www.chabad.org/parshah/default_cdo/aid/36234/jewish/Eikev.htm",              "Eikev"),
        "REEH"                to ParshaInfo("Re'eh",              "https://www.chabad.org/parshah/default_cdo/aid/36235/jewish/Reeh.htm",               "Re'eh"),
        "SHOFTIM"             to ParshaInfo("Shoftim",            "https://www.chabad.org/parshah/default_cdo/aid/36236/jewish/Shoftim.htm",           "Deuteronomy.16.18-21.9"),
        "KI_SEITZEI"          to ParshaInfo("Ki Teitzei",         "https://www.chabad.org/parshah/default_cdo/aid/36237/jewish/Ki-Teitzei.htm",         "Ki Teitzei"),
        "KI_SAVO"             to ParshaInfo("Ki Tavo",            "https://www.chabad.org/parshah/default_cdo/aid/36238/jewish/Ki-Tavo.htm",            "Ki Tavo"),
        "NITZAVIM"            to ParshaInfo("Nitzavim",           "https://www.chabad.org/parshah/default_cdo/aid/36239/jewish/Nitzavim.htm",           "Nitzavim"),
        "VAYEILECH"           to ParshaInfo("Vayelech",           "https://www.chabad.org/parshah/default_cdo/aid/36240/jewish/Vayelech.htm",           "Vayeilech"),
        "NITZAVIM_VAYEILECH"  to ParshaInfo("Nitzavim-Vayelech",  "https://www.chabad.org/parshah/default_cdo/aid/53151/jewish/Nitzavim-Vayelech.htm",  "Nitzavim-Vayelech"),
        "HAAZINU"             to ParshaInfo("Ha'azinu",           "https://www.chabad.org/parshah/default_cdo/aid/36241/jewish/Haazinu.htm",            "Haazinu"),
        "VZOS_HABERACHA"      to ParshaInfo("Vezot Habracha",     "https://www.chabad.org/parshah/default_cdo/aid/36242/jewish/VZot-HaBerachah.htm",    "Deuteronomy.33.1-34.12"),
    )

    /** Standard Hebrew names for weekly parsha display (Ashkenazi Israeli convention). */
    private val hebrewNames: Map<String, String> = mapOf(
        "Bereishit" to "בראשית",
        "Noach" to "נח",
        "Lech Lecha" to "לך לך",
        "Vayera" to "וירא",
        "Chayei Sara" to "חיי שרה",
        "Toldot" to "תולדות",
        "Vayetze" to "ויצא",
        "Vayishlach" to "וישלח",
        "Vayeshev" to "וישב",
        "Miketz" to "מקץ",
        "Vayigash" to "ויגש",
        "Vayechi" to "ויחי",
        "Shemot" to "שמות",
        "Va'era" to "וארא",
        "Bo" to "בא",
        "Beshalach" to "בשלח",
        "Yitro" to "יתרו",
        "Mishpatim" to "משפטים",
        "Terumah" to "תרומה",
        "Tetzaveh" to "תצוה",
        "Ki Tisa" to "כי תשא",
        "Vayakhel" to "ויקהל",
        "Pekudei" to "פקודי",
        "Vayakhel-Pekudei" to "ויקהל-פקודי",
        "Vayikra" to "ויקרא",
        "Tzav" to "צו",
        "Shemini" to "שמיני",
        "Tazria" to "תזריע",
        "Metzora" to "מצורע",
        "Tazria-Metzora" to "תזריע-מצורע",
        "Achrei Mot" to "אחרי מות",
        "Kedoshim" to "קדושים",
        "Achrei Mot-Kedoshim" to "אחרי מות-קדושים",
        "Emor" to "אמור",
        "Behar" to "בהר",
        "Bechukotai" to "בחוקתי",
        "Behar-Bechukotai" to "בהר-בחוקתי",
        "Bamidbar" to "במדבר",
        "Nasso" to "נשא",
        "Beha'alotcha" to "בהעלותך",
        "Shelach" to "שלח",
        "Korach" to "קרח",
        "Chukat" to "חוקת",
        "Balak" to "בלק",
        "Chukat-Balak" to "חוקת-בלק",
        "Pinchas" to "פינחס",
        "Matot" to "מטות",
        "Masei" to "מסעי",
        "Matot-Masei" to "מטות-מסעי",
        "Devarim" to "דברים",
        "Va'etchanan" to "ואתחנן",
        "Eikev" to "עקב",
        "Re'eh" to "ראה",
        "Shoftim" to "שופטים",
        "Ki Teitzei" to "כי תצא",
        "Ki Tavo" to "כי תבוא",
        "Nitzavim" to "נצבים",
        "Vayelech" to "וילך",
        "Nitzavim-Vayelech" to "נצבים-וילך",
        "Ha'azinu" to "האזינו",
        "Vezot Habracha" to "וזאת הברכה",
    )

    private val spanishNames: Map<String, String> = mapOf(
        "Bereishit" to "Bereshit",
        "Noach" to "Noaj",
        "Lech Lecha" to "Lej Lejá",
        "Vayera" to "Vayerá",
        "Chayei Sara" to "Jayé Sara",
        "Toldot" to "Toldot",
        "Vayetze" to "Vayetzé",
        "Vayishlach" to "Vayishlaj",
        "Vayeshev" to "Vayéshev",
        "Miketz" to "Miketz",
        "Vayigash" to "Vayigash",
        "Vayechi" to "Vayéji",
        "Shemot" to "Shemot",
        "Va'era" to "Vaerá",
        "Bo" to "Bo",
        "Beshalach" to "Beshalaj",
        "Yitro" to "Yitró",
        "Mishpatim" to "Mishpatim",
        "Terumah" to "Terumá",
        "Tetzaveh" to "Tetzavé",
        "Ki Tisa" to "Ki Tisá",
        "Vayakhel" to "Vayakel",
        "Pekudei" to "Pekudé",
        "Vayakhel-Pekudei" to "Vayakel-Pekudé",
        "Vayikra" to "Vayikrá",
        "Tzav" to "Tzav",
        "Shemini" to "Sheminí",
        "Tazria" to "Tazriá",
        "Metzora" to "Metzorá",
        "Tazria-Metzora" to "Tazriá-Metzorá",
        "Achrei Mot" to "Ajré Mot",
        "Kedoshim" to "Kedoshim",
        "Achrei Mot-Kedoshim" to "Ajré Mot-Kedoshim",
        "Emor" to "Emor",
        "Behar" to "Behar",
        "Bechukotai" to "Bejukotai",
        "Behar-Bechukotai" to "Behar-Bejukotai",
        "Bamidbar" to "Bamidbar",
        "Nasso" to "Nasó",
        "Beha'alotcha" to "Behaalotjá",
        "Shelach" to "Shelaj",
        "Korach" to "Koraj",
        "Chukat" to "Jukat",
        "Balak" to "Balak",
        "Chukat-Balak" to "Jukat-Balak",
        "Pinchas" to "Pinjas",
        "Matot" to "Matot",
        "Masei" to "Maséi",
        "Matot-Masei" to "Matot-Maséi",
        "Devarim" to "Devarim",
        "Va'etchanan" to "Vaetjanán",
        "Eikev" to "Eikev",
        "Re'eh" to "Reé",
        "Shoftim" to "Shoftim",
        "Ki Teitzei" to "Ki Teitzé",
        "Ki Tavo" to "Ki Tavó",
        "Nitzavim" to "Nitzavim",
        "Vayelech" to "Vayélej",
        "Nitzavim-Vayelech" to "Nitzavim-Vayélej",
        "Ha'azinu" to "Haazinú",
        "Vezot Habracha" to "Vezot Habrajá",
    )

    private val frenchNames: Map<String, String> = mapOf(
        "Bereishit" to "Béréchit",
        "Noach" to "Noah",
        "Lech Lecha" to "Lekh Lekha",
        "Vayera" to "Vayera",
        "Chayei Sara" to "Hayé Sara",
        "Toldot" to "Toldot",
        "Vayetze" to "Vayétsé",
        "Vayishlach" to "Vayichlah",
        "Vayeshev" to "Vayéchev",
        "Miketz" to "Mikéts",
        "Vayigash" to "Vayigach",
        "Vayechi" to "Vayéhi",
        "Shemot" to "Chemot",
        "Va'era" to "Vaéra",
        "Bo" to "Bo",
        "Beshalach" to "Béchalac",
        "Yitro" to "Yitro",
        "Mishpatim" to "Michpatim",
        "Terumah" to "Térouma",
        "Tetzaveh" to "Tétsavé",
        "Ki Tisa" to "Ki Tissa",
        "Vayakhel" to "Vayakel",
        "Pekudei" to "Pékoudé",
        "Vayakhel-Pekudei" to "Vayakel-Pékoudé",
        "Vayikra" to "Vayikra",
        "Tzav" to "Tsav",
        "Shemini" to "Chemchini",
        "Tazria" to "Tazria",
        "Metzora" to "Metsora",
        "Tazria-Metzora" to "Tazria-Metsora",
        "Achrei Mot" to "A'haré mot",
        "Kedoshim" to "Kédochim",
        "Achrei Mot-Kedoshim" to "A'haré mot-Kédochim",
        "Emor" to "Emor",
        "Behar" to "Béhar",
        "Bechukotai" to "Bé'houkotaï",
        "Behar-Bechukotai" to "Béhar-Bé'houkotaï",
        "Bamidbar" to "Bamidbar",
        "Nasso" to "Nasson",
        "Beha'alotcha" to "Behaaloté'ha",
        "Shelach" to "Chela'h",
        "Korach" to "Korah",
        "Chukat" to "Houkat",
        "Balak" to "Balak",
        "Chukat-Balak" to "Houkat-Balak",
        "Pinchas" to "Pin'has",
        "Matot" to "Matot",
        "Masei" to "Masséï",
        "Matot-Masei" to "Matot-Masséï",
        "Devarim" to "Dévarim",
        "Va'etchanan" to "Vaét'hanan",
        "Eikev" to "Ekev",
        "Re'eh" to "Réé",
        "Shoftim" to "Choftim",
        "Ki Teitzei" to "Ki tétsé",
        "Ki Tavo" to "Ki tavo",
        "Nitzavim" to "Nitsavim",
        "Vayelech" to "Vayéle'h",
        "Nitzavim-Vayelech" to "Nitsavim-Vayéle'h",
        "Ha'azinu" to "Haazinou",
        "Vezot Habracha" to "Zot Habérakha",
    )

    private val russianNames: Map<String, String> = mapOf(
        "Bereishit" to "Берешит",
        "Noach" to "Ноах",
        "Lech Lecha" to "Лех Леха",
        "Vayera" to "Вайера",
        "Chayei Sara" to "Хайей Сара",
        "Toldot" to "Толдот",
        "Vayetze" to "Вайеце",
        "Vayishlach" to "Вайишлах",
        "Vayeshev" to "Вайешев",
        "Miketz" to "Микец",
        "Vayigash" to "Вайигаш",
        "Vayechi" to "Вайехи",
        "Shemot" to "Шмот",
        "Va'era" to "Ваэра",
        "Bo" to "Бо",
        "Beshalach" to "Бешалах",
        "Yitro" to "Итро",
        "Mishpatim" to "Мишпатим",
        "Terumah" to "Терума",
        "Tetzaveh" to "Тецаве",
        "Ki Tisa" to "Ки Тиса",
        "Vayakhel" to "Вайакель",
        "Pekudei" to "Пекудей",
        "Vayakhel-Pekudei" to "Вайакель-Пекудей",
        "Vayikra" to "Вайикра",
        "Tzav" to "Цав",
        "Shemini" to "Шмини",
        "Tazria" to "Тазрия",
        "Metzora" to "Мецора",
        "Tazria-Metzora" to "Тазрия-Мецора",
        "Achrei Mot" to "Ахарей Мот",
        "Kedoshim" to "Кедошим",
        "Achrei Mot-Kedoshim" to "Ахарей Мот-Кедошим",
        "Emor" to "Эмор",
        "Behar" to "Бехар",
        "Bechukotai" to "Бехукотай",
        "Behar-Bechukotai" to "Бехар-Бехукотай",
        "Bamidbar" to "Бамидбар",
        "Nasso" to "Насо",
        "Beha'alotcha" to "Беаалотха",
        "Shelach" to "Шлах",
        "Korach" to "Корах",
        "Chukat" to "Хукат",
        "Balak" to "Балак",
        "Chukat-Balak" to "Хукат-Балак",
        "Pinchas" to "Пинхас",
        "Matot" to "Матот",
        "Masei" to "Масей",
        "Matot-Masei" to "Матот-Масей",
        "Devarim" to "Дварим",
        "Va'etchanan" to "Ваэтханан",
        "Eikev" to "Эйкев",
        "Re'eh" to "Рээ",
        "Shoftim" to "Шофтим",
        "Ki Teitzei" to "Ки Теце",
        "Ki Tavo" to "Ки Таво",
        "Nitzavim" to "Ницавим",
        "Vayelech" to "Вайелех",
        "Nitzavim-Vayelech" to "Ницавим-Вайелех",
        "Ha'azinu" to "Хаазину",
        "Vezot Habracha" to "Везот аБраха",
    )

    private val localeNames: Map<String, Map<String, String>> = mapOf(
        "he" to hebrewNames,
        "es" to spanishNames,
        "fr" to frenchNames,
        "ru" to russianNames,
    )

    /** Localized parsha name for UI templates (e.g. checklist title, calendar header). */
    fun localizedDisplayName(englishDisplayName: String, languageCode: String): String =
        when (languageCode) {
            "yi" -> hebrewNames[englishDisplayName] ?: englishDisplayName
            else -> localeNames[languageCode]?.get(englishDisplayName) ?: englishDisplayName
        }

    /** Returns display info for a KosherJava parsha enum name, or null if unknown/no parsha. */
    fun forKey(kosherJavaName: String?): ParshaInfo? =
        if (kosherJavaName == null || kosherJavaName == "NONE") null
        else map[kosherJavaName]

    /** Lookup by English display name (e.g. from calendar header). */
    fun forDisplayName(displayName: String?): ParshaInfo? {
        if (displayName.isNullOrBlank()) return null
        val trimmed = displayName.trim()
        return map.values.firstOrNull { it.displayName.equals(trimmed, ignoreCase = true) }
    }

    fun displayLabel(kosherJavaName: String?): String? =
        forKey(kosherJavaName)?.displayName
            ?: kosherJavaName?.takeIf { it.isNotBlank() && it != "NONE" }
                ?.replace('_', ' ')
                ?.trim()
}
