# -*- coding: utf-8 -*-
"""Remaining overlay translations (381 strings)."""

PART: dict[str, dict[str, str]] = {
    'Tap the\n"Mitzvah Me" button for a mitzvah!': {
        "he": 'הקישו על כפתור\n"מצווה אותי" למצווה!',
        "es": '¡Toca el botón\n"Mitzvá conmigo" para una mitzvá!',
        "fr": 'Appuyez sur le bouton\n« Mitzvah Me » pour une mitzvah !',
        "ru": 'Нажмите кнопку\n«Mitzvah Me» для выполнения mitzvah!',
    },
    'Tap the "Mitzvah Me"\nbutton for a mitzvah!': {
        "he": 'הקישו על כפתור "מצווה אותי"\nלמצווה!',
        "es": '¡Toca el botón "Mitzvá conmigo"\npara una mitzvá!',
        "fr": 'Appuyez sur le bouton « Mitzvah Me »\npour une mitzvah !',
        "ru": 'Нажмите кнопку «Mitzvah Me»\nдля выполнения mitzvah!',
    },
    "gemilut chasadim — acts of loving-kindness": {
        "he": "גמילות חסדים — מעשי חסד",
        "es": "gemilut chasadim — actos de bondad amorosa",
        "fr": "gemilout 'hasadim — actes de bonté",
        "ru": "gemilut chasadim — акты любящей доброты",
    },
    "kehilla — Jewish community or congregation": {
        "he": "קהילה — קהילה יהודית או קהל",
        "es": "kehilla — comunidad o congregación judía",
        "fr": "kehilah — communauté ou congrégation juive",
        "ru": "kehilla — еврейская община или приход",
    },
    "nusach Ashkenaz — Ashkenazi prayer wording": {
        "he": "נוסח אשכנז — נוסח תפילה אשכנזי",
        "es": "nusach Ashkenaz — formulación de oración ashkenazí",
        "fr": "noussah Ashkenaz — texte de prière ashkénaze",
        "ru": "nusach Ashkenaz — ашкеназский молитвенный текст",
    },
    "Chag — festival (everyday term for Yom Tov)": {
        "he": "חג — מונח יומיומי ליום טוב",
        "es": "Chag — fiesta (término cotidiano para Yom Tov)",
        "fr": "Hag — fête (terme courant pour Yom Tov)",
        "ru": "Chag — праздник (обычное название Yom Tov)",
    },
    "fast marking breaching of Jerusalem's walls": {
        "he": "צום לציון פרצת חומות ירושלים",
        "es": "ayuno que conmemora la brecha en los muros de Jerusalén",
        "fr": "jeûne commémorant la brèche dans les murailles de Jérusalem",
        "ru": "пост в память о проломе стен Иерусалима",
    },
    "fast mourning the destruction of the Temple": {
        "he": "צום לאבל על חורבן הבית",
        "es": "ayuno de luto por la destrucción del Templo",
        "fr": "jeûne de deuil pour la destruction du Temple",
        "ru": "пост скорби о разрушении Храма",
    },
    "salting meat to remove blood after shechita": {
        "he": "מליחת בשר להוצאת דם לאחר שחיטה",
        "es": "salado de carne para extraer la sangre tras el shejitá",
        "fr": "salage de la viande pour éliminer le sang après le she'hita",
        "ru": "посол мяса для удаления крови после shechita",
    },
    "candles lit before sunset to welcome Shabbat": {
        "he": "נרות המודלקים לפני השקיעה לקבלת פני השבת",
        "es": "velas encendidas antes del atardecer para recibir el Shabat",
        "fr": "bougies allumées avant le coucher du soleil pour accueillir Chabbat",
        "ru": "свечи, зажигаемые до заката для встречи Шаббата",
    },
    "complete Hallel psalms on festivals/Chanukah": {
        "he": "הלל שלם בחגים/חנוכה",
        "es": "salmos completos de Hallel en fiestas/Janucá",
        "fr": "psaumes complets de Hallel aux fêtes/Hanoucca",
        "ru": "полный Hallel на праздниках/Хануке",
    },
    "gematria — numerical value of Hebrew letters": {
        "he": "גימטריה — ערך מספרי של אותיות עבריות",
        "es": "gematria — valor numérico de las letras hebreas",
        "fr": "guématria — valeur numérique des lettres hébraïques",
        "ru": "gematria — числовое значение еврейских букв",
    },
    "prayer; from a root meaning to judge oneself": {
        "he": "תפילה; משורש שמשמעו לשפוט את עצמו",
        "es": "oración; de una raíz que significa juzgarse a uno mismo",
        "fr": "prière ; d'une racine signifiant se juger soi-même",
        "ru": "молитва; от корня «судить себя»",
    },
    "At least one prayer daily (typically morning)": {
        "he": "לפחות תפילה אחת ביום (בדרך כלל שחרית)",
        "es": "Al menos una oración diaria (típicamente por la mañana)",
        "fr": "Au moins une prière par jour (généralement le matin)",
        "ru": "Как минимум одна молитва в день (обычно утром)",
    },
    "Hamapil blessing (according to many opinions)": {
        "he": "ברכת המפיל (לפי דעות רבות)",
        "es": "Bendición Hamapil (según muchas opiniones)",
        "fr": "Bénédiction Hamapil (selon de nombreuses opinions)",
        "ru": "Благословение Hamapil (по мнению многих)",
    },
    "Prepare for and observe Shabbat and Festivals": {
        "he": "הכנה ושמירה על שבת וחגים",
        "es": "Preparar y observar Shabat y fiestas",
        "fr": "Préparer et observer Chabbat et les fêtes",
        "ru": "Готовиться и соблюдать Шаббат и праздники",
    },
    "central Torah principle taught by Rabbi Akiva": {
        "he": "עיקרון תורה מרכזי שלמד רבי עקיבא",
        "es": "principio central de la Torá enseñado por el rabí Akiva",
        "fr": "principe central de la Torah enseigné par Rabbi Akiva",
        "ru": "центральный принцип Торы, которому учил рабbi Akiva",
    },
    "forbidden to do melacha on Shabbat or Yom Tov": {
        "he": "אסור לעשות מלאכה בשבת או ביום טוב",
        "es": "prohibido realizar melajá en Shabat o Yom Tov",
        "fr": "interdit de faire une melakha le Chabbat ou un Yom Tov",
        "ru": "запрещено выполнять melacha в Шабbat или Yom Tov",
    },
    "garment; tzitzit apply to four-cornered beged": {
        "he": "beged — בeged; ציצית חלים על beged בעl arba kenafot",
        "es": "prenda; los tzitzit aplican a un beged de cuatro esquinas",
        "fr": "vêtement ; les tsitsit s'appliquent à un beged à quatre coins",
        "ru": "одежда; tzitzit относятся к четырёхугольной beged",
    },
    "Call someone who is lonely.\n\nSubmitted by: Amy": {
        "he": "התקשרו למישהו שמרגיש בודד.\n\nנשלח על ידי: Amy",
        "es": "Llama a alguien que se sienta solo.\n\nEnviado por: Amy",
        "fr": "Appelez quelqu'un qui se sent seul.\n\nSoumis par : Amy",
        "ru": "Позвоните кому-то одинокому.\n\nОт Amy",
    },
    "Fast of Gedaliah — fast day after Rosh Hashana": {
        "he": "צום גedalya — יום צום לאחר ראש השנה",
        "es": "Ayuno de Gedaliah — día de ayuno después de Rosh Hashaná",
        "fr": "Jeûne de Gedalia — jour de jeûne après Roch Hachana",
        "ru": "Пост Гедалии — день поста после Рош а-Шана",
    },
    "Gozez — shearing or cutting hair/nails melacha": {
        "he": "גוזז — מלאכת גזיזת שיער/ציפורניים",
        "es": "Gozez — melajá de esquilar o cortar cabello/uñas",
        "fr": "Gozez — melakha de tonte ou coupe de cheveux/ongles",
        "ru": "Gozez — мелаха стрижки волос/ногтей",
    },
    "Major & minor holidays, Yom Tov, and fast days": {
        "he": "חגים גדולים וקטנים, ימי טוב וימי צום",
        "es": "Fiestas mayores y menores, Yom Tov y días de ayuno",
        "fr": "Fêtes majeures et mineures, Yom Tov et jours de jeûne",
        "ru": "Большие и малые праздники, Yom Tov и дни поста",
    },
    "Makeh B'patish — final finishing touch melacha": {
        "he": "מכה בפטיש — מלאכת גימור סופי",
        "es": "Makeh B'patish — melajá del toque final de acabado",
        "fr": "Makeh B'patish — melakha de la touche finale",
        "ru": "Makeh B'patish — мелаха финального завершения",
    },
    "Yaknehaz order when Shabbat leads into Yom Tov": {
        "he": "סדר Yaknehaz כששבת נכנסת ליום טוב",
        "es": "Orden Yaknehaz cuando el Shabat entra en Yom Tov",
        "fr": "Ordre Yaknehaz quand Chabbat mène au Yom Tov",
        "ru": "Порядок Yaknehaz, когда Шабbat переходит в Yom Tov",
    },
    "e.g., Call your grandmother to check on her...": {
        "he": "למשל, התקשרו לסבתא לבדוק מה שלומה...",
        "es": "p. ej., Llama a tu abuela para ver cómo está...",
        "fr": "p. ex., Appelez votre grand-mère pour prendre de ses nouvelles...",
        "ru": "напр., позвоните бабушке узнать, как она...",
    },
    "elegies read on Tisha B'Av mourning the Temple": {
        "he": "קינות הנקראות בתשעה באב לאבל על הבית",
        "es": "elegías leídas en Tisha B'Av por el luto del Templo",
        "fr": "élégies lues à Ticha BeAv pour le deuil du Temple",
        "ru": "элегии, читаемые в Тиша бе-Аv в скорби о Храме",
    },
    "feminine form of Modeh (grateful) in Modeh Ani": {
        "he": "צורה נקבית של 'מודה' (מודה) ב'מודה אני'",
        "es": "forma femenina de Modeh (agradecido) en Modeh Ani",
        "fr": "forme féminine de Modeh (reconnaissant) dans Modeh Ani",
        "ru": "женская форма Modeh (благодарный) в Modeh Ani",
    },
    "paragraph sung after lighting Chanukah candles": {
        "he": "פסוקה הנשירה לאחר הדלקת נרות חנוכה",
        "es": "párrafo cantado tras encender las velas de Janucá",
        "fr": "paragraphe chanté après l'allumage des bougies de Hanoucca",
        "ru": "абзац, поющийся после зажигания ханukah-свечей",
    },
    "sage known for finding good in every situation": {
        "he": "חכם הידוע במציאת טוב בכל מצב",
        "es": "sabio conocido por encontrar lo bueno en toda situación",
        "fr": "sage connu pour trouver le bien en toute situation",
        "ru": "мудрец, известный умением находить добро в любой ситуации",
    },
    "Chanukah candelabra; candles are lit each night": {
        "he": "מנורת חנוכה; נרות מודלקים בכל לילה",
        "es": "candelabro de Janucá; se encienden velas cada noche",
        "fr": "chandelier de Hanoucca ; bougies allumées chaque soir",
        "ru": "hanukah-менора; свечи зажигаются каждый вечер",
    },
    "skullcap worn as a sign of G-d's presence above": {
        "he": "כיסוי ראש המסמל את נוכחות ה' מעל",
        "es": "gorro usado como señal de la presencia de D-s arriba",
        "fr": "calotte portée comme signe de la présence de D. au-dessus",
        "ru": "головной убор как знак присутствия В-га сверху",
    },
    "Parshah — weekly Torah portion read in synagogue": {
        "he": "פרשה — פרשת השבוע הנקראת בבית הכנסת",
        "es": "Parshah — porción semanal de la Torá leída en la sinagoga",
        "fr": "Paracha — portion hebdomadaire de Torah lue à la synagogue",
        "ru": "Parshah — еженедельная Torah-порция в синагоге",
    },
    "Wear Tzitzit (recommended for divine protection)": {
        "he": "לבישת ציצית (מומלץ לשמירה אלוקית)",
        "es": "Usar tzitzit (recomendado para protección divina)",
        "fr": "Porter des tsitsit (recommandé pour la protection divine)",
        "ru": "Носить tzitzit (рекомендуется для божественной защиты)",
    },
    "halachic midnight or midday depending on context": {
        "he": "חצות הלכתית — חצות לילה או חצות יום לפי ההקשר",
        "es": "medianoche o mediodía halájica según el contexto",
        "fr": "minuit ou midi halakhique selon le contexte",
        "ru": "галахическое полночь или полдень в зависимости от контекста",
    },
    '"Rock of Ages," Chanukah hymn sung after lighting': {
        "he": '"מעוז צור", שיר חנוכה הנשיר לאחר ההדלקה',
        "es": '"Maoz Tzur", himno de Janucá cantado tras encender las velas',
        "fr": '"Maoz Tzur", hymne de Hanoucca chanté après l\'allumage',
        "ru": '"Maoz Tzur", hanukah-гимн, поющийся после зажигания',
    },
    "Talmudic commentary and discussion on the Mishnah": {
        "he": "פרשנות ודיון תalmudי על המשנה",
        "es": "comentario y discusión talmúdica sobre la Mishná",
        "fr": "commentaire et discussion talmudiques sur la Mishna",
        "ru": "талmudический комментарий и обсуждение Mishnah",
    },
    "aravah — willow branches used in the Four Species": {
        "he": "ערבה — ענפי ערבה בארבעת המינים",
        "es": "aravah — ramas de sauce en las Cuatro Especies",
        "fr": "aravah — branches de saule parmi les Quatre Espèces",
        "ru": "aravah — ивовые ветви среди Четырёх видов",
    },
    "etrog — citron, one of the Four Species on Sukkot": {
        "he": "אתrog — אתrog, אחד מארבעת המינים בסוכות",
        "es": "etrog — cidra, una de las Cuatro Especies en Sucot",
        "fr": "etrog — cédrat, l'une des Quatre Espèces à Souccot",
        "ru": "etrog — цитрон, один из Четырёх видов на Суккот",
    },
    "marriage contract outlining husband's obligations": {
        "he": "חוזה נישואין המפרט את חובות הבעל",
        "es": "contrato matrimonial que detalla las obligaciones del esposo",
        "fr": "contrat de mariage détaillant les obligations du mari",
        "ru": "брачный договор с обязанностями мужа",
    },
    "intermediate Sukkot days between the Festival days": {
        "he": "ימי חול המועד של סוכות בין ימי החג",
        "es": "días intermedios de Sucot entre los días de fiesta",
        "fr": "jours intermédiaires de Souccot entre les jours de fête",
        "ru": "промежуточные дни Суккот между праздничными днями",
    },
    "Al Netilat Yadayim — blessing on ritual handwashing": {
        "he": "על נטילת ידיים — ברכה על נטילת ידיים",
        "es": "Al Netilat Yadayim — bendición sobre el lavado ritual de manos",
        "fr": "Al Netilat Yadayim — bénédiction sur le lavage rituel des mains",
        "ru": "Al Netilat Yadayim — благословение на ритуальное омовение рук",
    },
    "What they are, key differences, and the 39 melachot": {
        "he": "מה הן, ההבדלים העיקריים, ול\"ט המלאכות",
        "es": "Qué son, diferencias clave y las 39 melachot",
        "fr": "Ce qu'elles sont, différences clés et les 39 melachot",
        "ru": "Что это, ключевые различия и 39 melachot",
    },
    "blessing over fire in Yaknehaz and regular Havdalah": {
        "he": "ברכה על האש ב-Yaknehaz ובהavdalah הרגילה",
        "es": "bendición sobre el fuego en Yaknehaz y Havdalah regular",
        "fr": "bénédiction sur le feu dans Yaknehaz et la Havdalah ordinaire",
        "ru": "благословение на огонь в Yaknehaz и обычной Havdalah",
    },
    "complete healing; said when praying for someone ill": {
        "he": "רפואה שלמה; נאמר בתפילה עבור חולה",
        "es": "sanación completa; se dice al orar por alguien enfermo",
        "fr": "guérison complète ; dite en priant pour une personne malade",
        "ru": "полное исцеление; произносится при молитве о больном",
    },
    "hair covering for married women in many communities": {
        "he": "כיסוי שיער לנשואות בקהילות רבות",
        "es": "cobertura del cabello para mujeres casadas en muchas comunidades",
        "fr": "couvre-chef pour femmes mariées dans de nombreuses communautés",
        "ru": "покрытие волос для замужних женщин во многих общинах",
    },
    "nullification (e.g. Kol Chamira nullifying chametz)": {
        "he": "ביטul (למשל כל chamira המבטל chametz)",
        "es": "anulación (p. ej. Kol Chamira anulando chametz)",
        "fr": "annulation (p. ex. Kol Chamira annulant le hamets)",
        "ru": "аннулирование (напр. Kol Chamira, annuliruyushchiy chametz)",
    },
    "the eighteen (now nineteen) blessings of the Amidah": {
        "he": "שמונה עשרה (כיום תשע עשרה) ברכות של העמידה",
        "es": "las dieciocho (ahora diecinueve) bendiciones del Amidá",
        "fr": "les dix-huit (maintenant dix-neuf) bénédictions de l'Amidah",
        "ru": "восемнадцать (теперь девятнадцать) благословений Amidah",
    },
    "wind or spirit; middle soul level in some teachings": {
        "he": "רוח; רמה אמצעית של הנשמה בחלק מהתורות",
        "es": "viento o espíritu; nivel medio del alma en algunas enseñanzas",
        "fr": "vent ou esprit ; niveau intermédiaire de l'âme dans certains enseignements",
        "ru": "ветер или дух; средний уровень души в некоторых учениях",
    },
    "Motzei Shabbat is Saturday night after Shabbat ends.": {
        "he": "מוצאי שבת הוא ליל שבת לאחר סיום השבת.",
        "es": "Motzei Shabat es la noche del sábado tras terminar el Shabat.",
        "fr": "Motzei Chabbat est le samedi soir après la fin de Chabbat.",
        "ru": "Motzei Shabbat — субботний вечер после окончания Шаббата.",
    },
    "Musaf (only on Rosh Chodesh, Festivals, and Shabbat)": {
        "he": "מוסaf (רק בראש חודש, חגים ושבת)",
        "es": "Musaf (solo en Rosh Jodesh, fiestas y Shabat)",
        "fr": "Moussaf (seulement à Roch 'Hodech, fêtes et Chabbat)",
        "ru": "Musaf (только в Rosh Chodesh, на праздники и Шабbat)",
    },
}
